/*
 * cuda_sam3_1_kernels.h - HIP kernel sources for SAM 3 (RDNA4).
 *
 * Concatenated after hip_kernels_common_src. We close the extern "C" {
 * brace opened by the common preamble at the end of our string.
 *
 * Phase 1 kernels:
 *   patch_embed_sam3        Conv2d(3, 1024, k=14, s=14, bias=False)
 *                           Output layout: flat (grid*grid, D).
 *   pos_embed_tile_add      x[py,px,:] += pos[py%P, px%P, :] (P=24).
 *
 * Follow-up phases add: 2D axial RoPE, windowed/global ViT MHA,
 * FPN convs, CLIP text MHA, DETR enc/dec, pixel decoder, post-process.
 */
#ifndef CUDA_SAM3_1_KERNELS_H_
#define CUDA_SAM3_1_KERNELS_H_

static const char cuda_sam3_1_kernels_src[] =
"\n"
"/* ===================== SAM 3 kernels ===================== */\n"
"\n"
"/* ---- patch_embed_sam3 ----\n"
" * Conv2d(3, D=1024, kernel_size=14, stride=14, bias=False), no padding.\n"
" * Output layout: flat (grid*grid, D) row-major (matches HF / CPU runner).\n"
" *\n"
" * Grid: (grid, grid), blockDim: 128 threads — each block computes one\n"
" * patch; threads stride across output channels.\n"
" */\n"
"__global__ void patch_embed_sam3(float *out,           /* [grid*grid, D] */\n"
"                                  const half_raw *w,    /* [D, 3, 14, 14] F16 */\n"
"                                  const float *img,     /* [3, img_size, img_size] CHW F32 */\n"
"                                  int grid, int img_size, int D) {\n"
"    int py = blockIdx.y;\n"
"    int px = blockIdx.x;\n"
"    if (py >= grid || px >= grid) return;\n"
"    const int K = 14;\n"
"    int iy0 = py * K;\n"
"    int ix0 = px * K;\n"
"    int HW = img_size * img_size;\n"
"    for (int co = threadIdx.x; co < D; co += blockDim.x) {\n"
"        float acc = 0.f;\n"
"        for (int ci = 0; ci < 3; ci++) {\n"
"            const float *ch = img + (size_t)ci * HW;\n"
"            for (int ky = 0; ky < K; ky++) {\n"
"                for (int kx = 0; kx < K; kx++) {\n"
"                    int widx = ((co * 3 + ci) * K + ky) * K + kx;\n"
"                    acc += half_to_float(w[widx])\n"
"                         * ch[(iy0 + ky) * img_size + (ix0 + kx)];\n"
"                }\n"
"            }\n"
"        }\n"
"        out[(py * grid + px) * D + co] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* ---- pos_embed_tile_add ----\n"
" * In-place tokens += tile(pos[P, P, D], grid/P, grid/P) along the\n"
" * spatial axes. For SAM 3: P=24, grid=72, so pos is repeated 3x3.\n"
" */\n"
"__global__ void pos_embed_tile_add(float *tokens,         /* [grid*grid, D] */\n"
"                                    const float *pos,      /* [P, P, D] */\n"
"                                    int grid, int P, int D) {\n"
"    int py = blockIdx.y;\n"
"    int px = blockIdx.x;\n"
"    if (py >= grid || px >= grid) return;\n"
"    int sy = py % P, sx = px % P;\n"
"    float       *t = tokens + ((size_t)py * grid + px) * D;\n"
"    const float *s = pos    + ((size_t)sy * P   + sx) * D;\n"
"    for (int d = threadIdx.x; d < D; d += blockDim.x) t[d] += s[d];\n"
"}\n"
"\n"
"\n"
"/* ---- window_partition_f32 ----\n"
" * (H, W, D) -> (nW = (H/ws)*(W/ws), ws*ws, D). Spatial permute only.\n"
" * One thread per (widx, local_t, c) cell. */\n"
"__global__ void window_partition_f32(float *dst, const float *src,\n"
"                                       int H, int W, int D, int ws) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int nwh = H / ws, nww = W / ws;\n"
"    int total = nwh * nww * ws * ws * D;\n"
"    if (idx >= total) return;\n"
"    int c = idx % D;\n"
"    int t = (idx / D) % (ws * ws);\n"
"    int widx = idx / (D * ws * ws);\n"
"    int wy = widx / nww, wx = widx % nww;\n"
"    int dy = t / ws, dx = t % ws;\n"
"    int py = wy * ws + dy, px = wx * ws + dx;\n"
"    dst[idx] = src[(py * W + px) * D + c];\n"
"}\n"
"\n"
"__global__ void window_unpartition_f32(float *dst, const float *src,\n"
"                                         int H, int W, int D, int ws) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = H * W * D;\n"
"    if (idx >= total) return;\n"
"    int c = idx % D;\n"
"    int px = (idx / D) % W;\n"
"    int py = idx / (D * W);\n"
"    int nww = W / ws;\n"
"    int wy = py / ws, dy = py % ws;\n"
"    int wx = px / ws, dx = px % ws;\n"
"    int widx = wy * nww + wx;\n"
"    int t = dy * ws + dx;\n"
"    dst[idx] = src[(widx * ws * ws + t) * D + c];\n"
"}\n"
"\n"
"/* ---- rope_apply_qk_f32 ----\n"
" * In-place pairwise-rotation RoPE applied to Q and K slots of a fused\n"
" * QKV buffer (n_tok, 3*D). Rope table layout: (rope_seq, head_dim)\n"
" * with repeat_interleaved(2) so that cos[2p]==cos[2p+1]. Per-token\n"
" * rope_idx = t % rope_seq (caller windows tokens so window-local).\n"
" * Grid: (n_tok,). Block: heads=16 threads, each thread handles one head. */\n"
"__global__ void rope_apply_qk_f32(float *qkv, const float *cos_tbl,\n"
"                                    const float *sin_tbl, int rope_seq,\n"
"                                    int n_tok, int heads, int head_dim, int D) {\n"
"    int t = blockIdx.x;\n"
"    int h = threadIdx.x;\n"
"    if (t >= n_tok || h >= heads) return;\n"
"    int ri = t % rope_seq;\n"
"    const float *c = cos_tbl + (size_t)ri * head_dim;\n"
"    const float *s = sin_tbl + (size_t)ri * head_dim;\n"
"    float *qh = qkv + (size_t)t * 3 * D + h * head_dim;\n"
"    float *kh = qh + D;\n"
"    int pairs = head_dim / 2;\n"
"    for (int p = 0; p < pairs; p++) {\n"
"        float cc = c[2*p], ss = s[2*p];\n"
"        float qa = qh[2*p], qb = qh[2*p + 1];\n"
"        qh[2*p]     = qa * cc - qb * ss;\n"
"        qh[2*p + 1] = qb * cc + qa * ss;\n"
"        float ka = kh[2*p], kb = kh[2*p + 1];\n"
"        kh[2*p]     = ka * cc - kb * ss;\n"
"        kh[2*p + 1] = kb * cc + ka * ss;\n"
"    }\n"
"}\n"
"\n"
"\n"
"/* ---- tokens_to_nchw_f32 ----\n"
" * Transpose (n_tok=H*W, D) row-major  →  (D, H, W) NCHW. */\n"
"__global__ void tokens_to_nchw_f32(float *dst, const float *src,\n"
"                                     int H, int W, int D) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = D * H * W;\n"
"    if (idx >= total) return;\n"
"    int x = idx % W;\n"
"    int y = (idx / W) % H;\n"
"    int c = idx / (H * W);\n"
"    dst[idx] = src[((size_t)y * W + x) * D + c];\n"
"}\n"
"\n"
"/* ---- conv2d_1x1_f16 ----\n"
" * y[co, y, x] = b[co] + sum_ci w[co, ci] * x[ci, y, x].  F16 weights. */\n"
"__global__ void conv2d_1x1_f16(float *y,\n"
"                                const half_raw *w, const float *bias,\n"
"                                const float *x,\n"
"                                int Ci, int Co, int H, int W) {\n"
"    int px = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int py = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int co = blockIdx.z;\n"
"    if (px >= W || py >= H || co >= Co) return;\n"
"    float acc = bias ? bias[co] : 0.f;\n"
"    size_t HW = (size_t)H * W;\n"
"    size_t o = py * W + px;\n"
"    for (int ci = 0; ci < Ci; ci++)\n"
"        acc += half_to_float(w[(size_t)co * Ci + ci]) * x[(size_t)ci * HW + o];\n"
"    y[(size_t)co * HW + o] = acc;\n"
"}\n"
"\n"
"/* ---- conv2d_3x3_pad1_f16 ----\n"
" * Standard conv, pad=1 stride=1. Input/output NCHW F32, weight F16. */\n"
"__global__ void conv2d_3x3_pad1_f16(float *y,\n"
"                                     const half_raw *w, const float *bias,\n"
"                                     const float *x,\n"
"                                     int Ci, int Co, int H, int W) {\n"
"    int px = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int py = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int co = blockIdx.z;\n"
"    if (px >= W || py >= H || co >= Co) return;\n"
"    float acc = bias ? bias[co] : 0.f;\n"
"    size_t HW = (size_t)H * W;\n"
"    for (int ci = 0; ci < Ci; ci++) {\n"
"        const float *xc = x + (size_t)ci * HW;\n"
"        const half_raw *wc = w + ((size_t)co * Ci + ci) * 9;\n"
"        for (int ky = 0; ky < 3; ky++) {\n"
"            int ny = py + ky - 1;\n"
"            if (ny < 0 || ny >= H) continue;\n"
"            for (int kx = 0; kx < 3; kx++) {\n"
"                int nx = px + kx - 1;\n"
"                if (nx < 0 || nx >= W) continue;\n"
"                acc += half_to_float(wc[ky*3 + kx]) * xc[ny * W + nx];\n"
"            }\n"
"        }\n"
"    }\n"
"    y[(size_t)co * HW + px + py * W] = acc;\n"
"}\n"
"\n"
"/* ---- conv2d_1x1_f32 ----\n"
" * F32-weight variant: eliminates F16 weight-quant drift that compounds\n"
" * for large Ci (e.g. FPN conv_1x1 with Ci=1024). */\n"
"__global__ void conv2d_1x1_f32(float *y,\n"
"                                const float *w, const float *bias,\n"
"                                const float *x,\n"
"                                int Ci, int Co, int H, int W) {\n"
"    int px = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int py = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int co = blockIdx.z;\n"
"    if (px >= W || py >= H || co >= Co) return;\n"
"    float acc = bias ? bias[co] : 0.f;\n"
"    size_t HW = (size_t)H * W;\n"
"    size_t o = py * W + px;\n"
"    for (int ci = 0; ci < Ci; ci++)\n"
"        acc += w[(size_t)co * Ci + ci] * x[(size_t)ci * HW + o];\n"
"    y[(size_t)co * HW + o] = acc;\n"
"}\n"
"\n"
"/* ---- conv2d_3x3_pad1_f32 ---- */\n"
"__global__ void conv2d_3x3_pad1_f32(float *y,\n"
"                                     const float *w, const float *bias,\n"
"                                     const float *x,\n"
"                                     int Ci, int Co, int H, int W) {\n"
"    int px = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int py = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int co = blockIdx.z;\n"
"    if (px >= W || py >= H || co >= Co) return;\n"
"    float acc = bias ? bias[co] : 0.f;\n"
"    size_t HW = (size_t)H * W;\n"
"    for (int ci = 0; ci < Ci; ci++) {\n"
"        const float *xc = x + (size_t)ci * HW;\n"
"        const float *wc = w + ((size_t)co * Ci + ci) * 9;\n"
"        for (int ky = 0; ky < 3; ky++) {\n"
"            int ny = py + ky - 1;\n"
"            if (ny < 0 || ny >= H) continue;\n"
"            for (int kx = 0; kx < 3; kx++) {\n"
"                int nx = px + kx - 1;\n"
"                if (nx < 0 || nx >= W) continue;\n"
"                acc += wc[ky*3 + kx] * xc[ny * W + nx];\n"
"            }\n"
"        }\n"
"    }\n"
"    y[(size_t)co * HW + px + py * W] = acc;\n"
"}\n"
"\n"
"/* ---- convT_k2s2_f16 ----\n"
" * ConvTranspose2d k=2 s=2 p=0. Input (Ci, H, W) → (Co, 2H, 2W).\n"
" * Weight layout: (Ci, Co, 2, 2) — matches torch.nn.ConvTranspose2d.\n"
" * y[co, oy, ox] = bias[co] + sum_ci x[ci, iy, ix] * w[ci, co, ky, kx]\n"
" *   where oy = iy*2 + ky, ox = ix*2 + kx → for each output, input is\n"
" *   iy = oy/2, ix = ox/2, ky = oy%2, kx = ox%2. */\n"
"__global__ void convT_k2s2_f16(float *y,\n"
"                                const half_raw *w, const float *bias,\n"
"                                const float *x,\n"
"                                int Ci, int Co, int H, int W) {\n"
"    int ox = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oy = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int co = blockIdx.z;\n"
"    int OH = H * 2, OW = W * 2;\n"
"    if (ox >= OW || oy >= OH || co >= Co) return;\n"
"    int iy = oy >> 1, ix = ox >> 1;\n"
"    int ky = oy & 1, kx = ox & 1;\n"
"    float acc = bias ? bias[co] : 0.f;\n"
"    size_t HW = (size_t)H * W;\n"
"    for (int ci = 0; ci < Ci; ci++) {\n"
"        size_t widx = (((size_t)ci * Co + co) * 2 + ky) * 2 + kx;\n"
"        acc += half_to_float(w[widx]) * x[(size_t)ci * HW + iy * W + ix];\n"
"    }\n"
"    y[((size_t)co * OH + oy) * OW + ox] = acc;\n"
"}\n"
"\n"
"/* ---- maxpool_k2s2_f32 ----\n"
" * MaxPool 2x2 stride 2. Input (C, H, W) → (C, H/2, W/2). */\n"
"__global__ void maxpool_k2s2_f32(float *y, const float *x,\n"
"                                   int C, int H, int W) {\n"
"    int OW = W / 2, OH = H / 2;\n"
"    int ox = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oy = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int c  = blockIdx.z;\n"
"    if (ox >= OW || oy >= OH || c >= C) return;\n"
"    int ix = ox * 2, iy = oy * 2;\n"
"    size_t HW = (size_t)H * W;\n"
"    const float *xc = x + (size_t)c * HW;\n"
"    float a = xc[iy * W + ix];\n"
"    float b = xc[iy * W + ix + 1];\n"
"    float cc = xc[(iy + 1) * W + ix];\n"
"    float dd = xc[(iy + 1) * W + ix + 1];\n"
"    float m = a > b ? a : b;\n"
"    float n = cc > dd ? cc : dd;\n"
"    y[((size_t)c * OH + oy) * OW + ox] = m > n ? m : n;\n"
"}\n"
"\n"
"\n"
"/* ---- gelu_erf_f32 ----\n"
" * Exact erf-based GELU used by CLIP text encoder (HF ACT2FN[\"gelu\"]). */\n"
"__global__ void gelu_erf_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) {\n"
"        float v = x[i];\n"
"        x[i] = 0.5f * v * (1.0f + erff(v * 0.70710678118654752440f));\n"
"    }\n"
"}\n"
"\n"
"/* ---- clip_causal_attn_f32 ----\n"
" * Causal self-attention for small T (<=64). Grid: (heads,). Block: T.\n"
" * qkv layout (T, 3, D); D = heads*hd. Output (T, D). */\n"
"__global__ void clip_causal_attn_f32(float *out, const float *qkv,\n"
"                                       int T, int D, int heads, int hd,\n"
"                                       float scale) {\n"
"    int h = blockIdx.x;\n"
"    int t = threadIdx.x;\n"
"    if (t >= T || h >= heads) return;\n"
"    const float *Q = qkv + (size_t)t * 3 * D + 0 * D + h * hd;\n"
"    float scores[64];\n"
"    float mx = -1e30f;\n"
"    for (int k = 0; k <= t; k++) {\n"
"        const float *Kk = qkv + (size_t)k * 3 * D + 1 * D + h * hd;\n"
"        float s = 0.0f;\n"
"        for (int d = 0; d < hd; d++) s += Q[d] * Kk[d];\n"
"        s *= scale;\n"
"        scores[k] = s;\n"
"        if (s > mx) mx = s;\n"
"    }\n"
"    float sum = 0.0f;\n"
"    for (int k = 0; k <= t; k++) { scores[k] = expf(scores[k] - mx); sum += scores[k]; }\n"
"    float inv = 1.0f / sum;\n"
"    float *O = out + (size_t)t * D + h * hd;\n"
"    for (int d = 0; d < hd; d++) O[d] = 0.0f;\n"
"    for (int k = 0; k <= t; k++) {\n"
"        const float *Vk = qkv + (size_t)k * 3 * D + 2 * D + h * hd;\n"
"        float a = scores[k] * inv;\n"
"        for (int d = 0; d < hd; d++) O[d] += a * Vk[d];\n"
"    }\n"
"}\n"
"\n"
"\n"
"/* ---- nchw_to_tokens_f32 ----\n"
" * (C, H, W) NCHW -> (H*W, C) tokens row-major. */\n"
"__global__ void nchw_to_tokens_f32(float *dst, const float *src,\n"
"                                     int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * H * W;\n"
"    if (idx >= total) return;\n"
"    int c  = idx % C;\n"
"    int tx = (idx / C) % W;\n"
"    int ty = idx / (C * W);\n"
"    dst[idx] = src[((size_t)c * H + ty) * W + tx];\n"
"}\n"
"\n"
"/* ---- add_with_pos_f32 ----\n"
" * dst[i] = src[i] + pos[i], length n. */\n"
"__global__ void add_with_pos_f32(float *dst, const float *src, const float *pos, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] = src[i] + pos[i];\n"
"}\n"
"\n"
"\n"
"/* ---- mha_hd32_f32 ----\n"
" * Generic MHA with head_dim=32, online (streaming) softmax.\n"
" * Q: (Nq, D), K/V: (Nk, D), D = heads*hd. out: (Nq, D).\n"
" * Optional key_mask[Nk]: mask==0 -> score=-inf.\n"
" * Grid: (heads, Nq). Block: hd (= 32). Each thread holds one hd element. */\n"
"__global__ void mha_hd32_f32(float *out,\n"
"                               const float *Q, const float *K, const float *V,\n"
"                               const int *key_mask,\n"
"                               const float *bias_hqk,\n"
"                               int Nq, int Nk, int D, int heads, int hd,\n"
"                               float scale) {\n"
"    int h = blockIdx.x;\n"
"    int q = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (h >= heads || q >= Nq || tid >= hd) return;\n"
"    const float *Qv = Q + (size_t)q * D + h * hd;\n"
"    float qreg = Qv[tid];\n"
"    extern __shared__ float sh[];\n"
"    /* sh[0] = dot/score; sh[1] = m; sh[2] = l (shared across threads). */\n"
"    float m = -1e30f, l = 0.0f;\n"
"    float acc = 0.0f;\n"
"    for (int k = 0; k < Nk; k++) {\n"
"        const float *Kk = K + (size_t)k * D + h * hd;\n"
"        float kv = Kk[tid];\n"
"        float prod = qreg * kv;\n"
"        /* Block reduction across 32 threads. */\n"
"        sh[tid] = prod;\n"
"        __syncthreads();\n"
"        if (tid < 16) sh[tid] += sh[tid + 16]; __syncthreads();\n"
"        if (tid < 8)  sh[tid] += sh[tid + 8];  __syncthreads();\n"
"        if (tid < 4)  sh[tid] += sh[tid + 4];  __syncthreads();\n"
"        if (tid < 2)  sh[tid] += sh[tid + 2];  __syncthreads();\n"
"        if (tid < 1)  sh[tid] += sh[tid + 1];  __syncthreads();\n"
"        float s = sh[0] * scale;\n"
"        if (bias_hqk) s += bias_hqk[((size_t)h * Nq + q) * Nk + k];\n"
"        if (key_mask && key_mask[k] == 0) s = -1e30f;\n"
"        float m_new = s > m ? s : m;\n"
"        float alpha = expf(m - m_new);\n"
"        float p = expf(s - m_new);\n"
"        l = alpha * l + p;\n"
"        const float *Vk = V + (size_t)k * D + h * hd;\n"
"        acc = alpha * acc + p * Vk[tid];\n"
"        m = m_new;\n"
"        __syncthreads();\n"
"    }\n"
"    float inv = l > 0.0f ? 1.0f / l : 0.0f;\n"
"    out[(size_t)q * D + h * hd + tid] = acc * inv;\n"
"}\n"
"\n"
"\n"
"/* ---- rpb_assemble_f32 ----\n"
" * Assemble RPB bias (heads, Nt=Nq+1, H*W) from ex (Nq, W, heads) and\n"
" * ey (Nq, H, heads). Presence row (t=0) stays zero (caller memsets). */\n"
"__global__ void rpb_assemble_f32(float *rpb, const float *ex, const float *ey,\n"
"                                   int Nq, int H, int W, int heads) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int Npix = H * W;\n"
"    int total = heads * Nq * Npix;\n"
"    if (idx >= total) return;\n"
"    int pix = idx % Npix;\n"
"    int q   = (idx / Npix) % Nq;\n"
"    int h   = idx / (Npix * Nq);\n"
"    int x = pix % W, y = pix / W;\n"
"    float v = ex[((size_t)q * W + x) * heads + h]\n"
"            + ey[((size_t)q * H + y) * heads + h];\n"
"    int Nt = Nq + 1;\n"
"    rpb[((size_t)h * Nt + (q + 1)) * Npix + pix] = v;\n"
"}\n"
"\n"
"\n"
"/* ---- tokens_to_chw_f32 ----\n"
" * Inverse of nchw_to_tokens_f32: (H*W, C) -> (C, H, W) row-major. */\n"
"__global__ void tokens_to_chw_f32(float *dst, const float *src,\n"
"                                    int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * H * W;\n"
"    if (idx >= total) return;\n"
"    int w = idx % W;\n"
"    int h = (idx / W) % H;\n"
"    int c = idx / (H * W);\n"
"    dst[idx] = src[((size_t)(h * W + w)) * C + c];\n"
"}\n"
"\n"
"/* ---- groupnorm_f32 ----\n"
" * (C, H, W). Groups along channel. One block per group. */\n"
"__global__ void groupnorm_f32(float *x, const float *w, const float *b,\n"
"                                int C, int H, int W, int G, float eps) {\n"
"    int g   = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    int gc  = C / G;\n"
"    int spatial = H * W;\n"
"    int n   = gc * spatial;\n"
"    int c0  = g * gc;\n"
"    extern __shared__ float sh[];\n"
"    float *ssum = sh, *ssq = sh + blockDim.x;\n"
"    float sum = 0.0f, sq = 0.0f;\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int c  = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float v = x[(size_t)c * spatial + sp];\n"
"        sum += v; sq += v * v;\n"
"    }\n"
"    ssum[tid] = sum; ssq[tid] = sq;\n"
"    __syncthreads();\n"
"    for (int s = blockDim.x / 2; s > 0; s >>= 1) {\n"
"        if (tid < s) { ssum[tid] += ssum[tid + s]; ssq[tid] += ssq[tid + s]; }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = ssum[0] / (float)n;\n"
"    float var  = ssq[0] / (float)n - mean * mean;\n"
"    float inv  = rsqrtf(var + eps);\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int c  = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        size_t off = (size_t)c * spatial + sp;\n"
"        x[off] = (x[off] - mean) * inv * w[c] + b[c];\n"
"    }\n"
"}\n"
"\n"
"/* ---- nearest_upsample_f32 ----\n"
" * (C, Hi, Wi) -> (C, Ho, Wo) nearest-neighbor, matching torch F.interpolate. */\n"
"__global__ void nearest_upsample_f32(float *dst, const float *src,\n"
"                                       int C, int Hi, int Wi, int Ho, int Wo) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * Ho * Wo;\n"
"    if (idx >= total) return;\n"
"    int ow = idx % Wo;\n"
"    int oh = (idx / Wo) % Ho;\n"
"    int c  = idx / (Ho * Wo);\n"
"    int ih = (int)((long long)oh * Hi / Ho); if (ih >= Hi) ih = Hi - 1;\n"
"    int iw = (int)((long long)ow * Wi / Wo); if (iw >= Wi) iw = Wi - 1;\n"
"    dst[idx] = src[((size_t)c * Hi + ih) * Wi + iw];\n"
"}\n"
"\n"
"/* ---- einsum_qc_chw_f32 ----\n"
" * out[q, h, w] = sum_c me[q, c] * instance[c, h, w].\n"
" * Grid: (ceil(HW/256), Nq). Block: 256. */\n"
"__global__ void einsum_qc_chw_f32(float *out, const float *me,\n"
"                                    const float *instance,\n"
"                                    int Nq, int D, int H, int W) {\n"
"    int q  = blockIdx.y;\n"
"    int pix = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int HW = H * W;\n"
"    if (q >= Nq || pix >= HW) return;\n"
"    const float *mev = me + (size_t)q * D;\n"
"    float acc = 0.0f;\n"
"    for (int c = 0; c < D; c++)\n"
"        acc += mev[c] * instance[(size_t)c * HW + pix];\n"
"    out[(size_t)q * HW + pix] = acc;\n"
"}\n"
"\n"
"} /* extern \"C\" */\n"
;

#endif /* CUDA_SAM3_1_KERNELS_H_ */
