/*
 * hip_tex_dec_kernels.h - HIPRTC kernel source strings for TRELLIS.2 tex_dec.
 *
 * Scope (Phase 2 scaffolding): coord hash table + submanifold sparse conv3d
 * (F32). Future additions: LayerNorm, Linear, SiLU, C2S gather.
 *
 * Kernels here mirror the CPU reference in common/trellis2_shape_decoder.h so
 * HIP output matches t2sd_sparse_conv bitwise (up to FP summation order).
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_TEX_DEC_KERNELS_H
#define HIP_TEX_DEC_KERNELS_H

static const char hip_tex_dec_kernels_src[] =
"\n"
"/* 20-bit packed (z,y,x) -> uint64. Valid when coords in [0, 2^20). */\n"
"__device__ __forceinline__ unsigned long long t2_pack_zyx(int z, int y, int x) {\n"
"    return ((unsigned long long)(unsigned int)z << 40) |\n"
"           ((unsigned long long)(unsigned int)y << 20) |\n"
"            (unsigned long long)(unsigned int)x;\n"
"}\n"
"\n"
"__device__ __forceinline__ unsigned int t2_hash64(unsigned long long k) {\n"
"    k ^= k >> 33; k *= 0xff51afd7ed558ccdULL;\n"
"    k ^= k >> 33; k *= 0xc4ceb9fe1a85ec53ULL;\n"
"    k ^= k >> 33;\n"
"    return (unsigned int)k;\n"
"}\n"
"\n"
"/* Populate open-addressing coord hash. keys[] must be zero-initialized.\n"
" * Capacity must be power of two, cap_mask = cap - 1. Stored key = packed+1\n"
" * so key==0 means empty. vals[] holds the original voxel index. */\n"
"extern \"C\" __global__ void hash_insert_kernel(\n"
"    unsigned long long *keys, int *vals, int cap_mask,\n"
"    const int *coords, int N) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N) return;\n"
"    int z = coords[i*4 + 1], y = coords[i*4 + 2], x = coords[i*4 + 3];\n"
"    unsigned long long k = (unsigned long long)t2_pack_zyx(z, y, x) + 1ULL;\n"
"    unsigned int h = t2_hash64(k) & (unsigned int)cap_mask;\n"
"    for (int probe = 0; probe <= cap_mask; probe++) {\n"
"        unsigned long long prev = atomicCAS(&keys[h], 0ULL, k);\n"
"        if (prev == 0ULL) { vals[h] = i; return; }\n"
"        if (prev == k)     { vals[h] = i; return; }\n"
"        h = (h + 1) & (unsigned int)cap_mask;\n"
"    }\n"
"}\n"
"\n"
"__device__ __forceinline__ int t2_hash_lookup(\n"
"    const unsigned long long *keys, const int *vals, int cap_mask,\n"
"    int z, int y, int x) {\n"
"    unsigned long long k = (unsigned long long)t2_pack_zyx(z, y, x) + 1ULL;\n"
"    unsigned int h = t2_hash64(k) & (unsigned int)cap_mask;\n"
"    for (int probe = 0; probe <= cap_mask; probe++) {\n"
"        unsigned long long cur = keys[h];\n"
"        if (cur == 0ULL) return -1;\n"
"        if (cur == k)    return vals[h];\n"
"        h = (h + 1) & (unsigned int)cap_mask;\n"
"    }\n"
"    return -1;\n"
"}\n"
"\n"
"/* Submanifold sparse conv3d, kernel=3, stride=1, F32.\n"
" * Weight layout: [out_C, 27, in_C] (matches CPU t2sd_sparse_conv).\n"
" *   k_idx = kd*9 + kh*3 + kw, with kd/kh/kw in [0,3) over delta z/y/x.\n"
" * Grid: N blocks. Block: 256 threads, one per output channel slice. */\n"
"extern \"C\" __global__ void sparse_conv3d_f32(\n"
"    float *out, const float *feats, const int *coords,\n"
"    const float *weight, const float *bias,\n"
"    const unsigned long long *keys, const int *vals, int cap_mask,\n"
"    int in_C, int out_C) {\n"
"    int i = blockIdx.x;\n"
"    int z = coords[i*4 + 1], y = coords[i*4 + 2], x = coords[i*4 + 3];\n"
"    for (int oc = threadIdx.x; oc < out_C; oc += blockDim.x) {\n"
"        float acc = bias ? bias[oc] : 0.0f;\n"
"        for (int kd = 0; kd < 3; kd++) {\n"
"            int nz = z + kd - 1;\n"
"            for (int kh = 0; kh < 3; kh++) {\n"
"                int ny = y + kh - 1;\n"
"                for (int kw = 0; kw < 3; kw++) {\n"
"                    int nx = x + kw - 1;\n"
"                    int ni = t2_hash_lookup(keys, vals, cap_mask, nz, ny, nx);\n"
"                    if (ni < 0) continue;\n"
"                    int k_idx = (kd*3 + kh)*3 + kw;\n"
"                    const float *w = weight + ((size_t)oc * 27 + k_idx) * in_C;\n"
"                    const float *f = feats + (size_t)ni * in_C;\n"
"                    for (int c = 0; c < in_C; c++) acc += w[c] * f[c];\n"
"                }\n"
"            }\n"
"        }\n"
"        out[(size_t)i * out_C + oc] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* Tiled submanifold sparse conv3d, kernel=3, stride=1, F32.\n"
" * Same layout as sparse_conv3d_f32 but: grid=(N, out_C/BN), block=64 threads.\n"
" * BN=64, BK=32. Neighbor feat slabs loaded into LDS once and shared across\n"
" * 64 output channels; weight tile staged through LDS for coalesced reads.\n"
" * Requires out_C % 64 == 0 and in_C % 32 == 0. */\n"
"extern \"C\" __global__ void sparse_conv3d_tiled_f32(\n"
"    float *out, const float *feats, const int *coords,\n"
"    const float *weight, const float *bias,\n"
"    const unsigned long long *keys, const int *vals, int cap_mask,\n"
"    int in_C, int out_C) {\n"
"    const int BN = 64;\n"
"    const int BK = 32;\n"
"    int vox     = blockIdx.x;\n"
"    int oc_base = blockIdx.y * BN;\n"
"    int tid     = threadIdx.x;\n"
"    int oc      = oc_base + tid;\n"
"    int z = coords[vox*4 + 1], y = coords[vox*4 + 2], x = coords[vox*4 + 3];\n"
"    __shared__ int   nbr[27];\n"
"    __shared__ float smFeat[BK];\n"
"    __shared__ float smW[BN][BK];\n"
"    if (tid < 27) {\n"
"        int kd = tid / 9;\n"
"        int kh = (tid / 3) % 3;\n"
"        int kw = tid % 3;\n"
"        nbr[tid] = t2_hash_lookup(keys, vals, cap_mask,\n"
"                                  z + kd - 1, y + kh - 1, x + kw - 1);\n"
"    }\n"
"    __syncthreads();\n"
"    float acc = bias ? bias[oc] : 0.0f;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        int ni = nbr[k];\n"
"        if (ni < 0) continue;\n"
"        for (int ic = 0; ic < in_C; ic += BK) {\n"
"            if (tid < BK) smFeat[tid] = feats[(size_t)ni * in_C + ic + tid];\n"
"            /* Cooperatively load BN*BK=2048 weight floats. 64 threads * 32 loads.\n"
"             * Flat index -> (row, col); consecutive tids cover col within a row\n"
"             * for coalesced global reads. */\n"
"            #pragma unroll\n"
"            for (int it = 0; it < (BN * BK) / 64; it++) {\n"
"                int idx = it * 64 + tid;\n"
"                int row = idx / BK;\n"
"                int col = idx % BK;\n"
"                smW[row][col] = weight[((size_t)(oc_base + row) * 27 + k) * in_C + ic + col];\n"
"            }\n"
"            __syncthreads();\n"
"            float p = 0.0f;\n"
"            #pragma unroll\n"
"            for (int j = 0; j < BK; j++) p += smW[tid][j] * smFeat[j];\n"
"            acc += p;\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    if (oc < out_C) out[(size_t)vox * out_C + oc] = acc;\n"
"}\n"
"\n"
"/* Build submanifold conv neighbor_map (flex_gemm-compatible).\n"
" * For each voxel idx and kernel slot v in [0,27):\n"
" *   offsets (dx, dy, dz) = (v/9 - 1, (v/3)%3 - 1, v%3 - 1)\n"
" *   applied to coord columns (1, 2, 3) respectively; hash lookup.\n"
" *   No match -> 0xFFFFFFFF sentinel. Self (v=13) -> idx.\n"
" * Matches flex_gemm hashmap_lookup_submanifold_conv_neighbour_map_kernel\n"
" * bit-for-bit (mirror-write trick produces same result as naive enum\n"
" * for symmetric 3x3x3 kernels).\n"
" * Grid: (N + 7)/8 blocks of (8, 27) threads. Output: [N, 27] uint32. */\n"
"extern \"C\" __global__ void t2_build_nmap_f32(\n"
"    unsigned int *nmap, const int *coords,\n"
"    const unsigned long long *keys, const int *vals, int cap_mask, int N) {\n"
"    int idx = blockIdx.x * blockDim.y + threadIdx.y;\n"
"    int v   = threadIdx.x;\n"
"    if (idx >= N || v >= 27) return;\n"
"    int c1 = coords[idx*4 + 1];\n"
"    int c2 = coords[idx*4 + 2];\n"
"    int c3 = coords[idx*4 + 3];\n"
"    int d1 = (v / 9) - 1;\n"
"    int d2 = ((v / 3) % 3) - 1;\n"
"    int d3 = (v % 3) - 1;\n"
"    int ni;\n"
"    if (v == 13) {\n"
"        ni = idx;\n"
"    } else {\n"
"        ni = t2_hash_lookup(keys, vals, cap_mask, c1 + d1, c2 + d2, c3 + d3);\n"
"    }\n"
"    nmap[(size_t)idx * 27 + v] = (ni < 0) ? 0xFFFFFFFFu : (unsigned int)ni;\n"
"}\n"
"\n"
"/* Tiled submanifold conv3d that consumes a precomputed neighbor_map.\n"
" * Same math as sparse_conv3d_tiled_f32 but neighbor indices come from\n"
" * nmap[idx*27 + k] (0xFFFFFFFF = skip) instead of coord-delta hash.\n"
" * Required for flex_gemm weight compatibility (trained against flex_gemm's\n"
" * neighbor ordering). */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_tiled_f32(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int in_C, int out_C) {\n"
"    const int BN = 64;\n"
"    const int BK = 32;\n"
"    int vox     = blockIdx.x;\n"
"    int oc_base = blockIdx.y * BN;\n"
"    int tid     = threadIdx.x;\n"
"    int oc      = oc_base + tid;\n"
"    __shared__ int   nbr[27];\n"
"    __shared__ float smFeat[BK];\n"
"    __shared__ float smW[BN][BK];\n"
"    if (tid < 27) {\n"
"        unsigned int u = nmap[(size_t)vox * 27 + tid];\n"
"        nbr[tid] = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"    }\n"
"    __syncthreads();\n"
"    float acc = bias ? bias[oc] : 0.0f;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        int ni = nbr[k];\n"
"        if (ni < 0) continue;\n"
"        for (int ic = 0; ic < in_C; ic += BK) {\n"
"            if (tid < BK) smFeat[tid] = feats[(size_t)ni * in_C + ic + tid];\n"
"            #pragma unroll\n"
"            for (int it = 0; it < (BN * BK) / 64; it++) {\n"
"                int ix = it * 64 + tid;\n"
"                int row = ix / BK;\n"
"                int col = ix % BK;\n"
"                smW[row][col] = weight[((size_t)(oc_base + row) * 27 + k) * in_C + ic + col];\n"
"            }\n"
"            __syncthreads();\n"
"            float p = 0.0f;\n"
"            #pragma unroll\n"
"            for (int j = 0; j < BK; j++) p += smW[tid][j] * smFeat[j];\n"
"            acc += p;\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    if (oc < out_C) out[(size_t)vox * out_C + oc] = acc;\n"
"}\n"
"\n"
"/* Scalar fallback of sparse_conv3d_nmap for odd shapes. */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_f32(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int in_C, int out_C) {\n"
"    int i = blockIdx.x;\n"
"    for (int oc = threadIdx.x; oc < out_C; oc += blockDim.x) {\n"
"        float acc = bias ? bias[oc] : 0.0f;\n"
"        for (int k = 0; k < 27; k++) {\n"
"            unsigned int u = nmap[(size_t)i * 27 + k];\n"
"            if (u == 0xFFFFFFFFu) continue;\n"
"            int ni = (int)u;\n"
"            const float *w = weight + ((size_t)oc * 27 + k) * in_C;\n"
"            const float *f = feats + (size_t)ni * in_C;\n"
"            for (int c = 0; c < in_C; c++) acc += w[c] * f[c];\n"
"        }\n"
"        out[(size_t)i * out_C + oc] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* LayerNorm across the C axis. One block per row (voxel).\n"
" * w and/or b may be null (pass in_affine=0 / b=nullptr to skip).\n"
" * Grid: N, Block: 256. Uses block-wide sum via shared memory. */\n"
"extern \"C\" __global__ void t2_layernorm_f32(\n"
"    float *dst, const float *src, const float *w, const float *b,\n"
"    int C, float eps, int has_w, int has_b) {\n"
"    int i = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    int nt  = blockDim.x;\n"
"    const float *xi = src + (size_t)i * C;\n"
"    float *yi       = dst + (size_t)i * C;\n"
"    __shared__ float sdata[256];\n"
"    float s = 0.0f;\n"
"    for (int j = tid; j < C; j += nt) s += xi[j];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int off = nt/2; off > 0; off >>= 1) {\n"
"        if (tid < off) sdata[tid] += sdata[tid + off];\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = sdata[0] / (float)C;\n"
"    __syncthreads();\n"
"    float v = 0.0f;\n"
"    for (int j = tid; j < C; j += nt) { float d = xi[j] - mean; v += d*d; }\n"
"    sdata[tid] = v; __syncthreads();\n"
"    for (int off = nt/2; off > 0; off >>= 1) {\n"
"        if (tid < off) sdata[tid] += sdata[tid + off];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv = rsqrtf(sdata[0] / (float)C + eps);\n"
"    for (int j = tid; j < C; j += nt) {\n"
"        float y = (xi[j] - mean) * inv;\n"
"        if (has_w) y *= w[j];\n"
"        if (has_b) y += b[j];\n"
"        yi[j] = y;\n"
"    }\n"
"}\n"
"\n"
"/* Elementwise SiLU: y = x * sigmoid(x). */\n"
"extern \"C\" __global__ void t2_silu_f32(float *y, const float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float v = x[i];\n"
"    y[i] = v / (1.0f + __expf(-v));\n"
"}\n"
"\n"
"/* GELU tanh approximation (matches t2sd_gelu). In-place. */\n"
"extern \"C\" __global__ void t2_gelu_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float v = x[i];\n"
"    float t = 0.7978845608f * (v + 0.044715f * v * v * v);\n"
"    x[i] = 0.5f * v * (1.0f + tanhf(t));\n"
"}\n"
"\n"
"/* Elementwise add: a[i] += b[i]. */\n"
"extern \"C\" __global__ void t2_add_f32(float *a, const float *b, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    a[i] += b[i];\n"
"}\n"
"\n"
"/* Linear: out[N, out_C] = in[N, in_C] @ W[out_C, in_C]^T + bias[out_C].\n"
" * Simple tiled kernel, one block per (row_tile, col_tile). Block=16x16.\n"
" * Grid: ((out_C + 15)/16, (N + 15)/16). bias may be null. */\n"
"extern \"C\" __global__ void t2_linear_f32(\n"
"    float *out, const float *in, const float *W, const float *bias,\n"
"    int N, int in_C, int out_C) {\n"
"    const int BM = 16, BN = 16, BK = 16;\n"
"    __shared__ float As[BM][BK];\n"
"    __shared__ float Bs[BN][BK];\n"
"    int row = blockIdx.y * BM + threadIdx.y;\n"
"    int col = blockIdx.x * BN + threadIdx.x;\n"
"    float acc = 0.0f;\n"
"    for (int k0 = 0; k0 < in_C; k0 += BK) {\n"
"        int kk = k0 + threadIdx.x;\n"
"        As[threadIdx.y][threadIdx.x] =\n"
"            (row < N && kk < in_C) ? in[(size_t)row * in_C + kk] : 0.0f;\n"
"        int kk2 = k0 + threadIdx.y;\n"
"        Bs[threadIdx.x][threadIdx.y] =\n"
"            (col < out_C && kk2 < in_C) ? W[(size_t)col * in_C + kk2] : 0.0f;\n"
"        __syncthreads();\n"
"        #pragma unroll\n"
"        for (int k = 0; k < BK; k++)\n"
"            acc += As[threadIdx.y][k] * Bs[threadIdx.x][k];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < N && col < out_C) {\n"
"        if (bias) acc += bias[col];\n"
"        out[(size_t)row * out_C + col] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* C2S gather: build fine features from coarse residual block.\n"
" * Inputs:\n"
" *   h_coarse   [N_coarse, C_out8*8]  -- output of conv1 (channel-expanded)\n"
" *   x_coarse   [N_coarse, C_in]       -- raw feats before conv1\n"
" *   idx        [N_fine]               -- parent voxel in coarse\n"
" *   subidx     [N_fine]               -- child slot 0..7\n"
" * Outputs:\n"
" *   h_fine     [N_fine, C_out8]       -- gather C_out8 slice from h_coarse\n"
" *   x_fine     [N_fine, C_in8]        -- gather C_in/8 slice from x_coarse\n"
" * Where C_out8 = C_out, C_in8 = C_in / 8.\n"
" * Grid: (N_fine, (max(C_out8,C_in8)+255)/256), Block: 256. */\n"
"extern \"C\" __global__ void t2_c2s_gather_f32(\n"
"    float *h_fine, float *x_fine,\n"
"    const float *h_coarse, const float *x_coarse,\n"
"    const long long *idx, const long long *subidx,\n"
"    int C_out8, int C_in8) {\n"
"    int i = blockIdx.x;\n"
"    int tid_base = blockIdx.y * blockDim.x;\n"
"    int tid = tid_base + threadIdx.x;\n"
"    int p  = (int)idx[i];\n"
"    int sb = (int)subidx[i];\n"
"    if (tid < C_out8) {\n"
"        h_fine[(size_t)i * C_out8 + tid] =\n"
"            h_coarse[((size_t)p * 8 + sb) * C_out8 + tid];\n"
"    }\n"
"    if (tid < C_in8) {\n"
"        /* x_coarse reshape [N_coarse, 8, C_in8]; slot sb of row p. */\n"
"        x_fine[(size_t)i * C_in8 + tid] =\n"
"            x_coarse[((size_t)p * 8 + sb) * C_in8 + tid];\n"
"    }\n"
"}\n"
"\n"
"/* Residual add with channel-repeat: h[i, c] += x[i, c / rep]. */\n"
"extern \"C\" __global__ void t2_residual_repeat_f32(\n"
"    float *h, const float *x, int N, int C_out, int C_in8) {\n"
"    int i = blockIdx.x;\n"
"    int rep = C_out / C_in8;\n"
"    for (int c = threadIdx.x; c < C_out; c += blockDim.x) {\n"
"        h[(size_t)i * C_out + c] += x[(size_t)i * C_in8 + (c / rep)];\n"
"    }\n"
"    (void)N;\n"
"}\n"
;

#endif /* HIP_TEX_DEC_KERNELS_H */
