/*
 * hip_tex_dec_kernels.h - HIPRTC kernel source strings for TRELLIS.2 tex_dec.
 *
 * Scope (Phase 2 scaffolding): coord hash table + submanifold sparse conv3d
 * (F32). Future additions: LayerNorm, Linear, SiLU, C2S gather.
 *
 * Kernels here mirror the CPU reference in common/trellis2_shape_decoder.h so
 * HIP output matches t2sd_sparse_conv bitwise (up to FP summation order).
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_TEX_DEC_KERNELS_H
#define HIP_TEX_DEC_KERNELS_H

static const char hip_tex_dec_kernels_src[] =
"\n"
"/* 20-bit packed (z,y,x) -> uint64. Valid when coords in [0, 2^20). */\n"
"__device__ __forceinline__ unsigned long long t2_pack_zyx(int z, int y, int x) {\n"
"    return ((unsigned long long)(unsigned int)z << 40) |\n"
"           ((unsigned long long)(unsigned int)y << 20) |\n"
"            (unsigned long long)(unsigned int)x;\n"
"}\n"
"\n"
"__device__ __forceinline__ unsigned int t2_hash64(unsigned long long k) {\n"
"    k ^= k >> 33; k *= 0xff51afd7ed558ccdULL;\n"
"    k ^= k >> 33; k *= 0xc4ceb9fe1a85ec53ULL;\n"
"    k ^= k >> 33;\n"
"    return (unsigned int)k;\n"
"}\n"
"\n"
"/* Populate open-addressing coord hash. keys[] must be zero-initialized.\n"
" * Capacity must be power of two, cap_mask = cap - 1. Stored key = packed+1\n"
" * so key==0 means empty. vals[] holds the original voxel index. */\n"
"extern \"C\" __global__ void hash_insert_kernel(\n"
"    unsigned long long *keys, int *vals, int cap_mask,\n"
"    const int *coords, int N) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N) return;\n"
"    int z = coords[i*4 + 1], y = coords[i*4 + 2], x = coords[i*4 + 3];\n"
"    unsigned long long k = (unsigned long long)t2_pack_zyx(z, y, x) + 1ULL;\n"
"    unsigned int h = t2_hash64(k) & (unsigned int)cap_mask;\n"
"    for (int probe = 0; probe <= cap_mask; probe++) {\n"
"        unsigned long long prev = atomicCAS(&keys[h], 0ULL, k);\n"
"        if (prev == 0ULL) { vals[h] = i; return; }\n"
"        if (prev == k)     { vals[h] = i; return; }\n"
"        h = (h + 1) & (unsigned int)cap_mask;\n"
"    }\n"
"}\n"
"\n"
"__device__ __forceinline__ int t2_hash_lookup(\n"
"    const unsigned long long *keys, const int *vals, int cap_mask,\n"
"    int z, int y, int x) {\n"
"    unsigned long long k = (unsigned long long)t2_pack_zyx(z, y, x) + 1ULL;\n"
"    unsigned int h = t2_hash64(k) & (unsigned int)cap_mask;\n"
"    for (int probe = 0; probe <= cap_mask; probe++) {\n"
"        unsigned long long cur = keys[h];\n"
"        if (cur == 0ULL) return -1;\n"
"        if (cur == k)    return vals[h];\n"
"        h = (h + 1) & (unsigned int)cap_mask;\n"
"    }\n"
"    return -1;\n"
"}\n"
"\n"
"/* Submanifold sparse conv3d, kernel=3, stride=1, F32.\n"
" * Weight layout: [out_C, 27, in_C] (matches CPU t2sd_sparse_conv).\n"
" *   k_idx = kd*9 + kh*3 + kw, with kd/kh/kw in [0,3) over delta z/y/x.\n"
" * Grid: N blocks. Block: 256 threads, one per output channel slice. */\n"
"extern \"C\" __global__ void sparse_conv3d_f32(\n"
"    float *out, const float *feats, const int *coords,\n"
"    const float *weight, const float *bias,\n"
"    const unsigned long long *keys, const int *vals, int cap_mask,\n"
"    int in_C, int out_C) {\n"
"    int i = blockIdx.x;\n"
"    int z = coords[i*4 + 1], y = coords[i*4 + 2], x = coords[i*4 + 3];\n"
"    for (int oc = threadIdx.x; oc < out_C; oc += blockDim.x) {\n"
"        float acc = bias ? bias[oc] : 0.0f;\n"
"        for (int kd = 0; kd < 3; kd++) {\n"
"            int nz = z + kd - 1;\n"
"            for (int kh = 0; kh < 3; kh++) {\n"
"                int ny = y + kh - 1;\n"
"                for (int kw = 0; kw < 3; kw++) {\n"
"                    int nx = x + kw - 1;\n"
"                    int ni = t2_hash_lookup(keys, vals, cap_mask, nz, ny, nx);\n"
"                    if (ni < 0) continue;\n"
"                    int k_idx = (kd*3 + kh)*3 + kw;\n"
"                    const float *w = weight + ((size_t)oc * 27 + k_idx) * in_C;\n"
"                    const float *f = feats + (size_t)ni * in_C;\n"
"                    for (int c = 0; c < in_C; c++) acc += w[c] * f[c];\n"
"                }\n"
"            }\n"
"        }\n"
"        out[(size_t)i * out_C + oc] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* Tiled submanifold sparse conv3d, kernel=3, stride=1, F32.\n"
" * Same layout as sparse_conv3d_f32 but: grid=(N, out_C/BN), block=64 threads.\n"
" * BN=64, BK=32. Neighbor feat slabs loaded into LDS once and shared across\n"
" * 64 output channels; weight tile staged through LDS for coalesced reads.\n"
" * Requires out_C % 64 == 0 and in_C % 32 == 0. */\n"
"extern \"C\" __global__ void sparse_conv3d_tiled_f32(\n"
"    float *out, const float *feats, const int *coords,\n"
"    const float *weight, const float *bias,\n"
"    const unsigned long long *keys, const int *vals, int cap_mask,\n"
"    int in_C, int out_C) {\n"
"    const int BN = 64;\n"
"    const int BK = 32;\n"
"    int vox     = blockIdx.x;\n"
"    int oc_base = blockIdx.y * BN;\n"
"    int tid     = threadIdx.x;\n"
"    int oc      = oc_base + tid;\n"
"    int z = coords[vox*4 + 1], y = coords[vox*4 + 2], x = coords[vox*4 + 3];\n"
"    __shared__ int   nbr[27];\n"
"    __shared__ float smFeat[BK];\n"
"    __shared__ float smW[BN][BK];\n"
"    if (tid < 27) {\n"
"        int kd = tid / 9;\n"
"        int kh = (tid / 3) % 3;\n"
"        int kw = tid % 3;\n"
"        nbr[tid] = t2_hash_lookup(keys, vals, cap_mask,\n"
"                                  z + kd - 1, y + kh - 1, x + kw - 1);\n"
"    }\n"
"    __syncthreads();\n"
"    float acc = bias ? bias[oc] : 0.0f;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        int ni = nbr[k];\n"
"        if (ni < 0) continue;\n"
"        for (int ic = 0; ic < in_C; ic += BK) {\n"
"            if (tid < BK) smFeat[tid] = feats[(size_t)ni * in_C + ic + tid];\n"
"            /* Cooperatively load BN*BK=2048 weight floats. 64 threads * 32 loads.\n"
"             * Flat index -> (row, col); consecutive tids cover col within a row\n"
"             * for coalesced global reads. */\n"
"            #pragma unroll\n"
"            for (int it = 0; it < (BN * BK) / 64; it++) {\n"
"                int idx = it * 64 + tid;\n"
"                int row = idx / BK;\n"
"                int col = idx % BK;\n"
"                smW[row][col] = weight[((size_t)(oc_base + row) * 27 + k) * in_C + ic + col];\n"
"            }\n"
"            __syncthreads();\n"
"            float p = 0.0f;\n"
"            #pragma unroll\n"
"            for (int j = 0; j < BK; j++) p += smW[tid][j] * smFeat[j];\n"
"            acc += p;\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    if (oc < out_C) out[(size_t)vox * out_C + oc] = acc;\n"
"}\n"
"\n"
"/* Build submanifold conv neighbor_map (flex_gemm-compatible).\n"
" * For each voxel idx and kernel slot v in [0,27):\n"
" *   offsets (dx, dy, dz) = (v/9 - 1, (v/3)%3 - 1, v%3 - 1)\n"
" *   applied to coord columns (1, 2, 3) respectively; hash lookup.\n"
" *   No match -> 0xFFFFFFFF sentinel. Self (v=13) -> idx.\n"
" * Matches flex_gemm hashmap_lookup_submanifold_conv_neighbour_map_kernel\n"
" * bit-for-bit (mirror-write trick produces same result as naive enum\n"
" * for symmetric 3x3x3 kernels).\n"
" * Grid: (N + 7)/8 blocks of (8, 27) threads. Output: [N, 27] uint32. */\n"
"extern \"C\" __global__ void t2_build_nmap_f32(\n"
"    unsigned int *nmap, const int *coords,\n"
"    const unsigned long long *keys, const int *vals, int cap_mask, int N) {\n"
"    int idx = blockIdx.x * blockDim.y + threadIdx.y;\n"
"    int v   = threadIdx.x;\n"
"    if (idx >= N || v >= 27) return;\n"
"    int c1 = coords[idx*4 + 1];\n"
"    int c2 = coords[idx*4 + 2];\n"
"    int c3 = coords[idx*4 + 3];\n"
"    int d1 = (v / 9) - 1;\n"
"    int d2 = ((v / 3) % 3) - 1;\n"
"    int d3 = (v % 3) - 1;\n"
"    int ni;\n"
"    if (v == 13) {\n"
"        ni = idx;\n"
"    } else {\n"
"        ni = t2_hash_lookup(keys, vals, cap_mask, c1 + d1, c2 + d2, c3 + d3);\n"
"    }\n"
"    nmap[(size_t)idx * 27 + v] = (ni < 0) ? 0xFFFFFFFFu : (unsigned int)ni;\n"
"}\n"
"\n"
"/* Tiled submanifold conv3d that consumes a precomputed neighbor_map.\n"
" * Same math as sparse_conv3d_tiled_f32 but neighbor indices come from\n"
" * nmap[idx*27 + k] (0xFFFFFFFF = skip) instead of coord-delta hash.\n"
" * Required for flex_gemm weight compatibility (trained against flex_gemm's\n"
" * neighbor ordering). */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_tiled_f32(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int in_C, int out_C) {\n"
"    const int BN = 64;\n"
"    const int BK = 32;\n"
"    int vox     = blockIdx.x;\n"
"    int oc_base = blockIdx.y * BN;\n"
"    int tid     = threadIdx.x;\n"
"    int oc      = oc_base + tid;\n"
"    __shared__ int   nbr[27];\n"
"    __shared__ float smFeat[BK];\n"
"    __shared__ float smW[BN][BK];\n"
"    if (tid < 27) {\n"
"        unsigned int u = nmap[(size_t)vox * 27 + tid];\n"
"        nbr[tid] = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"    }\n"
"    __syncthreads();\n"
"    float acc = bias ? bias[oc] : 0.0f;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        int ni = nbr[k];\n"
"        if (ni < 0) continue;\n"
"        for (int ic = 0; ic < in_C; ic += BK) {\n"
"            if (tid < BK) smFeat[tid] = feats[(size_t)ni * in_C + ic + tid];\n"
"            #pragma unroll\n"
"            for (int it = 0; it < (BN * BK) / 64; it++) {\n"
"                int ix = it * 64 + tid;\n"
"                int row = ix / BK;\n"
"                int col = ix % BK;\n"
"                smW[row][col] = weight[((size_t)(oc_base + row) * 27 + k) * in_C + ic + col];\n"
"            }\n"
"            __syncthreads();\n"
"            float p = 0.0f;\n"
"            #pragma unroll\n"
"            for (int j = 0; j < BK; j++) p += smW[tid][j] * smFeat[j];\n"
"            acc += p;\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    if (oc < out_C) out[(size_t)vox * out_C + oc] = acc;\n"
"}\n"
"\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"/* sparse_conv3d_nmap_tiled_bf16: WMMA BF16 variant of the F32 tiled spconv.\n"
" * Output tile: 16 voxels x 16 oc. One wave (32 threads) per CTA.\n"
" * Requires in_C %% 16 == 0 and out_C %% 16 == 0; voxel count not required to align.\n"
" * Weights and feats are F32 in memory (truncated to BF16 in flight at SMEM load).\n"
" * Grid: ((N + 15)/16, (out_C + 15)/16), Block: 32. */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_tiled_bf16(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int N, int in_C, int out_C) {\n"
"    int vox_base = blockIdx.x * 16;\n"
"    int oc_base  = blockIdx.y * 16;\n"
"    int tid  = threadIdx.x;\n"
"    int idx  = tid & 15;\n"
"    int half = tid >> 4;\n"
"    __shared__ short smA[16 * 16]; /* W[oc_local, ic_local] */\n"
"    __shared__ short smB[16 * 16]; /* F[vox_local, ic_local] */\n"
"    __shared__ int   nbr[16 * 27];\n"
"    /* Preload all 27 neighbor indices for this voxel tile.\n"
"     * 16 vox x 27 = 432 entries; 32 threads -> ~14 each. */\n"
"    for (int it = tid; it < 16 * 27; it += 32) {\n"
"        int vl = it / 27;\n"
"        int kk = it - vl * 27;\n"
"        int vg = vox_base + vl;\n"
"        if (vg < N) {\n"
"            unsigned int u = nmap[(size_t)vg * 27 + kk];\n"
"            nbr[it] = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"        } else {\n"
"            nbr[it] = -1;\n"
"        }\n"
"    }\n"
"    __syncthreads();\n"
"    typedef float  float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short  bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    for (int k = 0; k < 27; k++) {\n"
"        for (int ic = 0; ic < in_C; ic += 16) {\n"
"            /* Each thread loads 8 SMEM entries for A and 8 for B (32 threads x 8 = 256 = 16x16). */\n"
"            for (int it = 0; it < 8; it++) {\n"
"                int e = tid * 8 + it;\n"
"                int er = e >> 4;        /* row 0..15 */\n"
"                int ek = e & 15;        /* col 0..15 */\n"
"                int oc_g = oc_base + er;\n"
"                int ic_g = ic + ek;\n"
"                float wv = (oc_g < out_C) ? weight[((size_t)oc_g * 27 + k) * in_C + ic_g] : 0.f;\n"
"                unsigned int wb; memcpy(&wb, &wv, 4);\n"
"                smA[er * 16 + ek] = (short)(wb >> 16);\n"
"            }\n"
"            for (int it = 0; it < 8; it++) {\n"
"                int e = tid * 8 + it;\n"
"                int er = e >> 4;        /* vox_local 0..15 */\n"
"                int ek = e & 15;        /* ic_local 0..15 */\n"
"                int ni = nbr[er * 27 + k];\n"
"                int ic_g = ic + ek;\n"
"                float fv = (ni >= 0) ? feats[(size_t)ni * in_C + ic_g] : 0.f;\n"
"                unsigned int fb; memcpy(&fb, &fv, 4);\n"
"                smB[er * 16 + ek] = (short)(fb >> 16);\n"
"            }\n"
"            __syncthreads();\n"
"            bf16x8 av, bv;\n"
"            int k_off = half * 8;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                av[i] = smA[idx * 16 + k_off + i];\n"
"                bv[i] = smB[idx * 16 + k_off + i];\n"
"            }\n"
"            cv = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(av, bv, cv);\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    /* Output: lane (idx, half) holds D[oc_local = half*8+i, vox_local = idx] for i in 0..7.\n"
"     * Store to out[vox, oc]. */\n"
"    int vg = vox_base + idx;\n"
"    if (vg < N) {\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int oc_local = half * 8 + i;\n"
"            int oc_g = oc_base + oc_local;\n"
"            if (oc_g < out_C) {\n"
"                float v = cv[i];\n"
"                if (bias) v += bias[oc_g];\n"
"                out[(size_t)vg * out_C + oc_g] = v;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* Wider variant: 16 vox x 32 oc output tile, 2 waves (64 threads) per CTA.\n"
" * Two oc-quadrants share smB[vox=16, ic=16] -> halves activation BW vs 16x16.\n"
" * Per ic-step: load smA0[16x16]+smA1[16x16] (one per wave) + smB[16x16]; 2 wmma. */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_tiled_bf16_x2(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int N, int in_C, int out_C) {\n"
"    int vox_base = blockIdx.x * 16;\n"
"    int oc_base  = blockIdx.y * 32;\n"
"    int tid  = threadIdx.x;\n"
"    int wave = tid >> 5;     /* 0 or 1 */\n"
"    int lane = tid & 31;\n"
"    int idx  = lane & 15;\n"
"    int half = lane >> 4;\n"
"    __shared__ short smA[2][16 * 16]; /* per-wave W tile */\n"
"    __shared__ short smB[16 * 16];    /* shared activation tile */\n"
"    __shared__ int   nbr[16 * 27];\n"
"    /* 64 threads load 432 nbrs cooperatively. */\n"
"    for (int it = tid; it < 16 * 27; it += 64) {\n"
"        int vl = it / 27;\n"
"        int kk = it - vl * 27;\n"
"        int vg = vox_base + vl;\n"
"        if (vg < N) {\n"
"            unsigned int u = nmap[(size_t)vg * 27 + kk];\n"
"            nbr[it] = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"        } else {\n"
"            nbr[it] = -1;\n"
"        }\n"
"    }\n"
"    __syncthreads();\n"
"    typedef float  float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short  bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    int oc_wave_base = oc_base + wave * 16;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        for (int ic = 0; ic < in_C; ic += 16) {\n"
"            /* Each wave (32 lanes) loads its own smA[wave] (256 entries, 8 per lane). */\n"
"            for (int it = 0; it < 8; it++) {\n"
"                int e = lane * 8 + it;\n"
"                int er = e >> 4;\n"
"                int ek = e & 15;\n"
"                int oc_g = oc_wave_base + er;\n"
"                int ic_g = ic + ek;\n"
"                float wv = (oc_g < out_C) ? weight[((size_t)oc_g * 27 + k) * in_C + ic_g] : 0.f;\n"
"                unsigned int wb; memcpy(&wb, &wv, 4);\n"
"                smA[wave][er * 16 + ek] = (short)(wb >> 16);\n"
"            }\n"
"            /* Wave 0 owns smB load (32 lanes x 8 = 256 entries). */\n"
"            if (wave == 0) {\n"
"                for (int it = 0; it < 8; it++) {\n"
"                    int e = lane * 8 + it;\n"
"                    int er = e >> 4;\n"
"                    int ek = e & 15;\n"
"                    int ni = nbr[er * 27 + k];\n"
"                    int ic_g = ic + ek;\n"
"                    float fv = (ni >= 0) ? feats[(size_t)ni * in_C + ic_g] : 0.f;\n"
"                    unsigned int fb; memcpy(&fb, &fv, 4);\n"
"                    smB[er * 16 + ek] = (short)(fb >> 16);\n"
"                }\n"
"            }\n"
"            __syncthreads();\n"
"            bf16x8 av, bv;\n"
"            int k_off = half * 8;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                av[i] = smA[wave][idx * 16 + k_off + i];\n"
"                bv[i] = smB[idx * 16 + k_off + i];\n"
"            }\n"
"            cv = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(av, bv, cv);\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    int vg = vox_base + idx;\n"
"    if (vg < N) {\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int oc_local = half * 8 + i;\n"
"            int oc_g = oc_wave_base + oc_local;\n"
"            if (oc_g < out_C) {\n"
"                float v = cv[i];\n"
"                if (bias) v += bias[oc_g];\n"
"                out[(size_t)vg * out_C + oc_g] = v;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* 32 vox x 32 oc output tile. 4 waves (128 threads) per CTA in a 2x2 grid:\n"
"   wave 0: (vox 0..15, oc 0..15)  wave 1: (vox 0..15, oc 16..31)\n"
"   wave 2: (vox 16..31, oc 0..15) wave 3: (vox 16..31, oc 16..31)\n"
" * smA[2][16x16] keyed by oc-half (shared across vox-halves);\n"
" * smB[2][16x16] keyed by vox-half (shared across oc-halves).\n"
" * Per ic-step: 4 wmma; A/B traffic each reused 2x. AI ~16 FLOPs/byte. */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_tiled_bf16_x4(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int N, int in_C, int out_C) {\n"
"    int vox_base = blockIdx.x * 32;\n"
"    int oc_base  = blockIdx.y * 32;\n"
"    int tid  = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int wv   = wave >> 1;     /* 0/1 vox half */\n"
"    int wo   = wave & 1;      /* 0/1 oc half */\n"
"    int idx  = lane & 15;\n"
"    int half = lane >> 4;\n"
"    __shared__ short smA[2][16 * 16]; /* indexed by wo */\n"
"    __shared__ short smB[2][16 * 16]; /* indexed by wv */\n"
"    __shared__ int   nbr[32 * 27];\n"
"    for (int it = tid; it < 32 * 27; it += 128) {\n"
"        int vl = it / 27;\n"
"        int kk = it - vl * 27;\n"
"        int vg = vox_base + vl;\n"
"        if (vg < N) {\n"
"            unsigned int u = nmap[(size_t)vg * 27 + kk];\n"
"            nbr[it] = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"        } else {\n"
"            nbr[it] = -1;\n"
"        }\n"
"    }\n"
"    __syncthreads();\n"
"    typedef float  float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short  bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    int oc_q_base = oc_base + wo * 16;\n"
"    int vox_q_base = vox_base + wv * 16;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        for (int ic = 0; ic < in_C; ic += 16) {\n"
"            /* smA[wo]: only waves with wv==0 load; smB[wv]: only waves with wo==0 load. */\n"
"            if (wv == 0) {\n"
"                for (int it = 0; it < 8; it++) {\n"
"                    int e = lane * 8 + it;\n"
"                    int er = e >> 4;\n"
"                    int ek = e & 15;\n"
"                    int oc_g = oc_q_base + er;\n"
"                    int ic_g = ic + ek;\n"
"                    float wv_f = (oc_g < out_C) ? weight[((size_t)oc_g * 27 + k) * in_C + ic_g] : 0.f;\n"
"                    unsigned int wb; memcpy(&wb, &wv_f, 4);\n"
"                    smA[wo][er * 16 + ek] = (short)(wb >> 16);\n"
"                }\n"
"            }\n"
"            if (wo == 0) {\n"
"                for (int it = 0; it < 8; it++) {\n"
"                    int e = lane * 8 + it;\n"
"                    int er = e >> 4;\n"
"                    int ek = e & 15;\n"
"                    int ni = nbr[(wv * 16 + er) * 27 + k];\n"
"                    int ic_g = ic + ek;\n"
"                    float fv = (ni >= 0) ? feats[(size_t)ni * in_C + ic_g] : 0.f;\n"
"                    unsigned int fb; memcpy(&fb, &fv, 4);\n"
"                    smB[wv][er * 16 + ek] = (short)(fb >> 16);\n"
"                }\n"
"            }\n"
"            __syncthreads();\n"
"            bf16x8 av, bv;\n"
"            int k_off = half * 8;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                av[i] = smA[wo][idx * 16 + k_off + i];\n"
"                bv[i] = smB[wv][idx * 16 + k_off + i];\n"
"            }\n"
"            cv = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(av, bv, cv);\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    int vg = vox_q_base + idx;\n"
"    if (vg < N) {\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int oc_local = half * 8 + i;\n"
"            int oc_g = oc_q_base + oc_local;\n"
"            if (oc_g < out_C) {\n"
"                float v = cv[i];\n"
"                if (bias) v += bias[oc_g];\n"
"                out[(size_t)vg * out_C + oc_g] = v;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* 32 vox x 64 oc output tile. 8 waves (256 threads) per CTA in a 2x4 grid:\n"
"   wv (vox-half 0/1) x wo (oc-quad 0..3).\n"
" * smA[4][16x16] keyed by oc-quad (shared across vox-halves);\n"
" * smB[2][16x16] keyed by vox-half (shared across all 4 oc-quads).\n"
" * Per ic-step: 8 wmma; A reused 2x, B reused 4x. */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_tiled_bf16_x8(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int N, int in_C, int out_C) {\n"
"    int vox_base = blockIdx.x * 32;\n"
"    int oc_base  = blockIdx.y * 64;\n"
"    int tid  = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int wv   = wave >> 2;     /* 0/1 */\n"
"    int wo   = wave & 3;      /* 0..3 */\n"
"    int idx  = lane & 15;\n"
"    int half = lane >> 4;\n"
"    __shared__ short smA[4][16 * 16];\n"
"    __shared__ short smB[2][16 * 16];\n"
"    __shared__ int   nbr[32 * 27];\n"
"    for (int it = tid; it < 32 * 27; it += 256) {\n"
"        int vl = it / 27;\n"
"        int kk = it - vl * 27;\n"
"        int vg = vox_base + vl;\n"
"        if (vg < N) {\n"
"            unsigned int u = nmap[(size_t)vg * 27 + kk];\n"
"            nbr[it] = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"        } else {\n"
"            nbr[it] = -1;\n"
"        }\n"
"    }\n"
"    __syncthreads();\n"
"    typedef float  float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short  bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    int oc_q_base = oc_base + wo * 16;\n"
"    int vox_q_base = vox_base + wv * 16;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        for (int ic = 0; ic < in_C; ic += 16) {\n"
"            /* smA loaded by waves with wv==0 (one wave per oc-quad). */\n"
"            if (wv == 0) {\n"
"                for (int it = 0; it < 8; it++) {\n"
"                    int e = lane * 8 + it;\n"
"                    int er = e >> 4;\n"
"                    int ek = e & 15;\n"
"                    int oc_g = oc_q_base + er;\n"
"                    int ic_g = ic + ek;\n"
"                    float wv_f = (oc_g < out_C) ? weight[((size_t)oc_g * 27 + k) * in_C + ic_g] : 0.f;\n"
"                    unsigned int wb; memcpy(&wb, &wv_f, 4);\n"
"                    smA[wo][er * 16 + ek] = (short)(wb >> 16);\n"
"                }\n"
"            }\n"
"            /* smB loaded by waves with wo==0 (one wave per vox-half). */\n"
"            if (wo == 0) {\n"
"                for (int it = 0; it < 8; it++) {\n"
"                    int e = lane * 8 + it;\n"
"                    int er = e >> 4;\n"
"                    int ek = e & 15;\n"
"                    int ni = nbr[(wv * 16 + er) * 27 + k];\n"
"                    int ic_g = ic + ek;\n"
"                    float fv = (ni >= 0) ? feats[(size_t)ni * in_C + ic_g] : 0.f;\n"
"                    unsigned int fb; memcpy(&fb, &fv, 4);\n"
"                    smB[wv][er * 16 + ek] = (short)(fb >> 16);\n"
"                }\n"
"            }\n"
"            __syncthreads();\n"
"            bf16x8 av, bv;\n"
"            int k_off = half * 8;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                av[i] = smA[wo][idx * 16 + k_off + i];\n"
"                bv[i] = smB[wv][idx * 16 + k_off + i];\n"
"            }\n"
"            cv = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(av, bv, cv);\n"
"            __syncthreads();\n"
"        }\n"
"    }\n"
"    int vg = vox_q_base + idx;\n"
"    if (vg < N) {\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int oc_local = half * 8 + i;\n"
"            int oc_g = oc_q_base + oc_local;\n"
"            if (oc_g < out_C) {\n"
"                float v = cv[i];\n"
"                if (bias) v += bias[oc_g];\n"
"                out[(size_t)vg * out_C + oc_g] = v;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"
"/* Gather-and-pack for the flex_gemm-style spconv path:\n"
" * out_bf16[m, k, c] = bf16(feats[nmap[m_base+m, k], c]) (or 0 for invalid).\n"
" * Grid: (M, 27, 1); each block fills one (m, k) row of in_C BF16 elements. */\n"
"extern \"C\" __global__ void t2_gather27_pack_bf16(\n"
"    short *out_bf16, const float *feats, const unsigned int *nmap,\n"
"    int m_base, int M, int in_C) {\n"
"    int m = blockIdx.x;\n"
"    int k = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (m >= M) return;\n"
"    int g = m + m_base;\n"
"    unsigned int u = nmap[(size_t)g * 27 + k];\n"
"    int ni = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"    short *dst = out_bf16 + ((size_t)m * 27 + k) * in_C;\n"
"    if (ni < 0) {\n"
"        for (int c = tid; c < in_C; c += blockDim.x) dst[c] = 0;\n"
"    } else {\n"
"        const float *src = feats + (size_t)ni * in_C;\n"
"        for (int c = tid; c < in_C; c += blockDim.x) {\n"
"            float v = src[c];\n"
"            unsigned int u2; memcpy(&u2, &v, 4);\n"
"            u2 = u2 + ((u2 >> 16) & 1u) + 0x7FFFu;\n"
"            dst[c] = (short)(u2 >> 16);\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* Fatter gather-pack variant: each block handles MB voxels x 27 neighbors\n"
" * using vectorized float2 loads + packed int stores (2 BF16 per int). Cuts\n"
" * launched blocks by 27*MB and doubles per-thread load width.\n"
" * Grid: (ceil(M/MB), 1, 1), Block: 256 threads. Requires in_C %% 2 == 0. */\n"
"extern \"C\" __global__ void t2_gather27_pack_bf16_v2(\n"
"    short *out_bf16, const float *feats, const unsigned int *nmap,\n"
"    int m_base, int M, int in_C) {\n"
"    const int MB = 4;\n"
"    int m_block = blockIdx.x * MB;\n"
"    int t = threadIdx.x;\n"
"    int mb = t / 64;\n"
"    int lane = t % 64;\n"
"    int m = m_block + mb;\n"
"    if (m >= M) return;\n"
"    int g = m + m_base;\n"
"    int half_C = in_C >> 1;\n"
"    for (int k = 0; k < 27; k++) {\n"
"        unsigned int u = nmap[(size_t)g * 27 + k];\n"
"        int ni = (u == 0xFFFFFFFFu) ? -1 : (int)u;\n"
"        int *dst = (int *)(out_bf16 + ((size_t)m * 27 + k) * in_C);\n"
"        if (ni < 0) {\n"
"            for (int c = lane; c < half_C; c += 64) dst[c] = 0;\n"
"        } else {\n"
"            const float2 *src = (const float2 *)(feats + (size_t)ni * in_C);\n"
"            for (int c = lane; c < half_C; c += 64) {\n"
"                float2 v = src[c];\n"
"                unsigned int u0, u1;\n"
"                memcpy(&u0, &v.x, 4); u0 = u0 + ((u0 >> 16) & 1u) + 0x7FFFu;\n"
"                memcpy(&u1, &v.y, 4); u1 = u1 + ((u1 >> 16) & 1u) + 0x7FFFu;\n"
"                dst[c] = (int)((u0 >> 16) | (u1 & 0xFFFF0000u));\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* Scalar fallback of sparse_conv3d_nmap for odd shapes. */\n"
"extern \"C\" __global__ void sparse_conv3d_nmap_f32(\n"
"    float *out, const float *feats,\n"
"    const unsigned int *nmap,\n"
"    const float *weight, const float *bias,\n"
"    int in_C, int out_C) {\n"
"    int i = blockIdx.x;\n"
"    for (int oc = threadIdx.x; oc < out_C; oc += blockDim.x) {\n"
"        float acc = bias ? bias[oc] : 0.0f;\n"
"        for (int k = 0; k < 27; k++) {\n"
"            unsigned int u = nmap[(size_t)i * 27 + k];\n"
"            if (u == 0xFFFFFFFFu) continue;\n"
"            int ni = (int)u;\n"
"            const float *w = weight + ((size_t)oc * 27 + k) * in_C;\n"
"            const float *f = feats + (size_t)ni * in_C;\n"
"            for (int c = 0; c < in_C; c++) acc += w[c] * f[c];\n"
"        }\n"
"        out[(size_t)i * out_C + oc] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* LayerNorm across the C axis. One block per row (voxel).\n"
" * w and/or b may be null (pass in_affine=0 / b=nullptr to skip).\n"
" * Grid: N, Block: 256. Uses block-wide sum via shared memory. */\n"
"extern \"C\" __global__ void t2_layernorm_f32(\n"
"    float *dst, const float *src, const float *w, const float *b,\n"
"    int C, float eps, int has_w, int has_b) {\n"
"    int i = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    int nt  = blockDim.x;\n"
"    const float *xi = src + (size_t)i * C;\n"
"    float *yi       = dst + (size_t)i * C;\n"
"    __shared__ float sdata[256];\n"
"    float s = 0.0f;\n"
"    for (int j = tid; j < C; j += nt) s += xi[j];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int off = nt/2; off > 0; off >>= 1) {\n"
"        if (tid < off) sdata[tid] += sdata[tid + off];\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = sdata[0] / (float)C;\n"
"    __syncthreads();\n"
"    float v = 0.0f;\n"
"    for (int j = tid; j < C; j += nt) { float d = xi[j] - mean; v += d*d; }\n"
"    sdata[tid] = v; __syncthreads();\n"
"    for (int off = nt/2; off > 0; off >>= 1) {\n"
"        if (tid < off) sdata[tid] += sdata[tid + off];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv = rsqrtf(sdata[0] / (float)C + eps);\n"
"    for (int j = tid; j < C; j += nt) {\n"
"        float y = (xi[j] - mean) * inv;\n"
"        if (has_w) y *= w[j];\n"
"        if (has_b) y += b[j];\n"
"        yi[j] = y;\n"
"    }\n"
"}\n"
"\n"
"/* Elementwise SiLU: y = x * sigmoid(x). */\n"
"extern \"C\" __global__ void t2_silu_f32(float *y, const float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float v = x[i];\n"
"    y[i] = v / (1.0f + __expf(-v));\n"
"}\n"
"\n"
"/* GELU tanh approximation (matches t2sd_gelu). In-place. */\n"
"extern \"C\" __global__ void t2_gelu_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float v = x[i];\n"
"    float t = 0.7978845608f * (v + 0.044715f * v * v * v);\n"
"    x[i] = 0.5f * v * (1.0f + tanhf(t));\n"
"}\n"
"\n"
"/* Elementwise add: a[i] += b[i]. */\n"
"extern \"C\" __global__ void t2_add_f32(float *a, const float *b, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    a[i] += b[i];\n"
"}\n"
"\n"
"/* Linear: out[N, out_C] = in[N, in_C] @ W[out_C, in_C]^T + bias[out_C].\n"
" * Simple tiled kernel, one block per (row_tile, col_tile). Block=16x16.\n"
" * Grid: ((out_C + 15)/16, (N + 15)/16). bias may be null. */\n"
"extern \"C\" __global__ void t2_linear_f32(\n"
"    float *out, const float *in, const float *W, const float *bias,\n"
"    int N, int in_C, int out_C) {\n"
"    const int BM = 16, BN = 16, BK = 16;\n"
"    __shared__ float As[BM][BK];\n"
"    __shared__ float Bs[BN][BK];\n"
"    int row = blockIdx.y * BM + threadIdx.y;\n"
"    int col = blockIdx.x * BN + threadIdx.x;\n"
"    float acc = 0.0f;\n"
"    for (int k0 = 0; k0 < in_C; k0 += BK) {\n"
"        int kk = k0 + threadIdx.x;\n"
"        As[threadIdx.y][threadIdx.x] =\n"
"            (row < N && kk < in_C) ? in[(size_t)row * in_C + kk] : 0.0f;\n"
"        int kk2 = k0 + threadIdx.y;\n"
"        Bs[threadIdx.x][threadIdx.y] =\n"
"            (col < out_C && kk2 < in_C) ? W[(size_t)col * in_C + kk2] : 0.0f;\n"
"        __syncthreads();\n"
"        #pragma unroll\n"
"        for (int k = 0; k < BK; k++)\n"
"            acc += As[threadIdx.y][k] * Bs[threadIdx.x][k];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < N && col < out_C) {\n"
"        if (bias) acc += bias[col];\n"
"        out[(size_t)row * out_C + col] = acc;\n"
"    }\n"
"}\n"
"\n"
"/* C2S gather: build fine features from coarse residual block.\n"
" * Inputs:\n"
" *   h_coarse   [N_coarse, C_out8*8]  -- output of conv1 (channel-expanded)\n"
" *   x_coarse   [N_coarse, C_in]       -- raw feats before conv1\n"
" *   idx        [N_fine]               -- parent voxel in coarse\n"
" *   subidx     [N_fine]               -- child slot 0..7\n"
" * Outputs:\n"
" *   h_fine     [N_fine, C_out8]       -- gather C_out8 slice from h_coarse\n"
" *   x_fine     [N_fine, C_in8]        -- gather C_in/8 slice from x_coarse\n"
" * Where C_out8 = C_out, C_in8 = C_in / 8.\n"
" * Grid: (N_fine, (max(C_out8,C_in8)+255)/256), Block: 256. */\n"
"extern \"C\" __global__ void t2_c2s_gather_f32(\n"
"    float *h_fine, float *x_fine,\n"
"    const float *h_coarse, const float *x_coarse,\n"
"    const long long *idx, const long long *subidx,\n"
"    int C_out8, int C_in8) {\n"
"    int i = blockIdx.x;\n"
"    int tid_base = blockIdx.y * blockDim.x;\n"
"    int tid = tid_base + threadIdx.x;\n"
"    int p  = (int)idx[i];\n"
"    int sb = (int)subidx[i];\n"
"    if (tid < C_out8) {\n"
"        h_fine[(size_t)i * C_out8 + tid] =\n"
"            h_coarse[((size_t)p * 8 + sb) * C_out8 + tid];\n"
"    }\n"
"    if (tid < C_in8) {\n"
"        /* x_coarse reshape [N_coarse, 8, C_in8]; slot sb of row p. */\n"
"        x_fine[(size_t)i * C_in8 + tid] =\n"
"            x_coarse[((size_t)p * 8 + sb) * C_in8 + tid];\n"
"    }\n"
"}\n"
"\n"
"/* Residual add with channel-repeat: h[i, c] += x[i, c / rep]. */\n"
"extern \"C\" __global__ void t2_residual_repeat_f32(\n"
"    float *h, const float *x, int N, int C_out, int C_in8) {\n"
"    int i = blockIdx.x;\n"
"    int rep = C_out / C_in8;\n"
"    for (int c = threadIdx.x; c < C_out; c += blockDim.x) {\n"
"        h[(size_t)i * C_out + c] += x[(size_t)i * C_in8 + (c / rep)];\n"
"    }\n"
"    (void)N;\n"
"}\n"
"\n"
"/* F32 -> BF16 packer (round-to-nearest-even). For hipBLASLt activation cast. */\n"
"typedef unsigned short bf16_raw_td;\n"
"__device__ __forceinline__ bf16_raw_td td_f32_to_bf16(float f) {\n"
"    unsigned int u = __float_as_uint(f);\n"
"    unsigned int rounded = u + ((u >> 16) & 1u) + 0x7FFFu;\n"
"    return (bf16_raw_td)(rounded >> 16);\n"
"}\n"
"extern \"C\" __global__ void t2_pack_bf16_from_f32(bf16_raw_td *dst, const float *src, int n) {\n"
"    int gid = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int idx4 = gid * 4;\n"
"    if (idx4 + 3 < n) {\n"
"        float4 f4 = *((const float4 *)(src + idx4));\n"
"        unsigned long long packed =\n"
"              ((unsigned long long)td_f32_to_bf16(f4.x))\n"
"            | (((unsigned long long)td_f32_to_bf16(f4.y)) << 16)\n"
"            | (((unsigned long long)td_f32_to_bf16(f4.z)) << 32)\n"
"            | (((unsigned long long)td_f32_to_bf16(f4.w)) << 48);\n"
"        *((unsigned long long *)(dst + idx4)) = packed;\n"
"    } else {\n"
"        for (int i = idx4; i < n && i < idx4 + 4; i++) dst[i] = td_f32_to_bf16(src[i]);\n"
"    }\n"
"}\n"
;

#endif /* HIP_TEX_DEC_KERNELS_H */
