/*
 * hip_qimg_kernels.h - HIP kernel source strings for Qwen-Image
 *
 * Contains all Qwen-Image specific HIP kernels as a C string literal for
 * HIPRTC runtime compilation. Concatenated after hip_kernels_common_src
 * (which opens extern "C" {) and closes it at the end.
 *
 * Port of cuda_qimg_runner.h kernels for AMD ROCm/HIP (RDNA4, gfx1201).
 * Key differences from CUDA version:
 *   - __shfl_xor_sync -> __shfl_xor (no sync mask on HIP)
 *   - __shfl_down_sync -> __shfl_down
 *   - No FP8 hardware: weights dequanted to F32 on CPU before upload
 *   - No PTX inline asm: BF16 truncation uses memcpy
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_QIMG_KERNELS_H
#define HIP_QIMG_KERNELS_H

static const char hip_qimg_specific_kernels[] =
"\n"

/* ---- FP8 LUT for weight dequantization ---- */
"__device__ __constant__ float d_fp8_to_f32_lut[256];\n"
"\n"

/* ---- gemm_fp8w_f32: FP8 weights dequanted via LUT, F32 inputs+accum ---- */
"/* FP8 LUT GEMM: dequant weights via constant memory LUT, F32 inputs+accum.\n"
" * W is raw FP8 bytes [n_out, n_in], X is F32 [n_tok, n_in].\n"
" * Grid: (ceil(n_out/64), ceil(n_tok/16)), Block: (16, 16) */\n"
"__global__ void gemm_fp8w_f32(float *Y, const unsigned char *W, const float *X,\n"
"    const float *bias, int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- gemm_opt_fp8: Optimized 128x128 tiled FP8 LUT GEMM with fused BF16 trunc ---- */
"/* Optimized GEMM: FP8 weights via LUT, 128x128 tiles, 256 threads.\n"
" * Each thread computes 8x8 outputs. Fused BF16 truncation on output.\n"
" * W[N,K] is FP8, X[M,K] is F32, Y[M,N] is F32.\n"
" * Grid: (ceil(N/128), ceil(M/128)), Block: (256) */\n"
"#define OPT_BM 128\n"
"#define OPT_BN 128\n"
"#define OPT_BK 16\n"
"#define OPT_TM 8\n"
"#define OPT_TN 8\n"
"__global__ void gemm_opt_fp8(float *Y, const unsigned char *W, const float *X,\n"
"                              const float *bias, int N, int K, int M) {\n"
"    __shared__ float smA[OPT_BK][OPT_BM];\n"
"    __shared__ float smB[OPT_BK][OPT_BN];\n"
"    int tid = threadIdx.x;\n"
"    int bm = blockIdx.y * OPT_BM, bn = blockIdx.x * OPT_BN;\n"
"    int tr = tid / 16, tc = tid % 16;\n"
"    float acc[OPT_TM][OPT_TN];\n"
"    for (int i = 0; i < OPT_TM; i++)\n"
"        for (int j = 0; j < OPT_TN; j++) acc[i][j] = 0.0f;\n"
"    for (int k = 0; k < K; k += OPT_BK) {\n"
"        /* Load A tile: X[bm..bm+BM, k..k+BK] -> smA[BK][BM] (transposed) */\n"
"        for (int _i = tid; _i < OPT_BM*OPT_BK; _i += 256) {\n"
"            int _r = _i % OPT_BM, _c = _i / OPT_BM;\n"
"            int gr = bm+_r, gk = k+_c;\n"
"            smA[_c][_r] = (gr<M&&gk<K) ? X[gr*K+gk] : 0.0f;\n"
"        }\n"
"        /* Load B tile: W[bn..bn+BN, k..k+BK] -> smB[BK][BN] (transposed, FP8 LUT) */\n"
"        for (int _i = tid; _i < OPT_BN*OPT_BK; _i += 256) {\n"
"            int _r = _i % OPT_BN, _c = _i / OPT_BN;\n"
"            int gn = bn+_r, gk = k+_c;\n"
"            smB[_c][_r] = (gn<N&&gk<K) ? d_fp8_to_f32_lut[W[(long)gn*K+gk]] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        /* Compute 8x8 per thread */\n"
"        for (int kk = 0; kk < OPT_BK; kk++) {\n"
"            float af[OPT_TM], bf[OPT_TN];\n"
"            for (int i=0;i<OPT_TM;i++) af[i] = smA[kk][tr*OPT_TM+i];\n"
"            for (int j=0;j<OPT_TN;j++) bf[j] = smB[kk][tc*OPT_TN+j];\n"
"            for (int i=0;i<OPT_TM;i++)\n"
"                for (int j=0;j<OPT_TN;j++) acc[i][j] += af[i]*bf[j];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    /* Write output with fused BF16 truncation + bias */\n"
"    for (int i=0;i<OPT_TM;i++) {\n"
"        int gr = bm+tr*OPT_TM+i; if(gr>=M) continue;\n"
"        for (int j=0;j<OPT_TN;j++) {\n"
"            int gn = bn+tc*OPT_TN+j;\n"
"            if(gn<N) {\n"
"                float val = acc[i][j]+(bias?bias[gn]:0.0f);\n"
"                /* Fused BF16 truncation */\n"
"                unsigned int bits;\n"
"                memcpy(&bits, &val, 4);\n"
"                bits += 0x7FFFu+((bits>>16)&1u); bits &= 0xFFFF0000u;\n"
"                memcpy(&val, &bits, 4);\n"
"                Y[gr*N+gn] = val;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"#undef OPT_BM\n"
"#undef OPT_BN\n"
"#undef OPT_BK\n"
"#undef OPT_TM\n"
"#undef OPT_TN\n"
"\n"

/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */
"/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */\n"
"__global__ void gemm_f32_f32(float *Y, const float *W, const float *X,\n"
"                              const float *bias,\n"
"                              int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* Per-head RMSNorm: x[N, dim], w[head_dim], n_heads, head_dim */
"__global__ void rmsnorm_per_head_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int n_heads, int head_dim) {\n"
"    int tok = blockIdx.x;\n"
"    int h = blockIdx.y;\n"
"    if (tok >= N || h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    float *hd = x + tok * dim + h * head_dim;\n"
"    float ss = 0.0f;\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        ss += hd[i] * hd[i];\n"
"    /* Warp reduce */\n"
"    for (int m = 16; m > 0; m >>= 1)\n"
"        ss += __shfl_xor(ss, m);\n"
"    float inv = rsqrtf(ss / (float)head_dim + 1e-6f);\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        hd[i] *= inv * w[i];\n"
"}\n"
"\n"

/* adaLN modulate: out = LN(x) * (1+scale) + shift */
"__global__ void adaln_modulate_f32(float *__restrict__ out,\n"
"    const float *__restrict__ x, const float *__restrict__ shift,\n"
"    const float *__restrict__ scale, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    /* Compute mean */\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) s += x[tok*dim+i];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    /* Compute var */\n"
"    s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) { float d = x[tok*dim+i] - mean; s += d*d; }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    /* Apply modulation */\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        out[tok*dim+i] = ((x[tok*dim+i] - mean) * inv) * (1.0f + scale[i]) + shift[i];\n"
"}\n"
"\n"

/* Gated residual: x += gate * proj */
"__global__ void gated_add_f32(float *__restrict__ x,\n"
"    const float *__restrict__ proj, const float *__restrict__ gate,\n"
"    int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N * dim) return;\n"
"    int col = i % dim;\n"
"    x[i] += gate[col] * proj[i];\n"
"}\n"
"\n"

/* Patchify: latent [C, H, W] → tokens [H/ps*W/ps, C*ps*ps] */
"__global__ void patchify_f32(float *__restrict__ out,\n"
"    const float *__restrict__ latent, int C, int H, int W, int ps) {\n"
"    int tok = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int hp = H / ps, wp = W / ps;\n"
"    if (tok >= hp * wp) return;\n"
"    int py = tok / wp, px = tok % wp;\n"
"    int tok_dim = C * ps * ps;\n"
"    int idx = 0;\n"
"    for (int c = 0; c < C; c++)\n"
"        for (int dy = 0; dy < ps; dy++)\n"
"            for (int dx = 0; dx < ps; dx++)\n"
"                out[tok * tok_dim + idx++] = latent[c * H * W + (py*ps+dy) * W + (px*ps+dx)];\n"
"}\n"
"\n"

/* Unpatchify: tokens [seq, C*ps*ps] → latent [C, H, W] */
"__global__ void unpatchify_f32(float *__restrict__ out,\n"
"    const float *__restrict__ tokens, int C, int H, int W, int ps) {\n"
"    int tok = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int hp = H / ps, wp = W / ps;\n"
"    if (tok >= hp * wp) return;\n"
"    int py = tok / wp, px = tok % wp;\n"
"    int tok_dim = C * ps * ps;\n"
"    int idx = 0;\n"
"    for (int c = 0; c < C; c++)\n"
"        for (int dy = 0; dy < ps; dy++)\n"
"            for (int dx = 0; dx < ps; dx++)\n"
"                out[c * H * W + (py*ps+dy) * W + (px*ps+dx)] = tokens[tok * tok_dim + idx++];\n"
"}\n"
"\n"

/* Euler step: x = x + dt * v */
"__global__ void euler_step_f32(float *__restrict__ x,\n"
"    const float *__restrict__ v, float dt, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] += dt * v[i];\n"
"}\n"
"\n"

/* CFG combine: out = v_uncond + cfg_scale * (v_cond - v_uncond) */
"__global__ void cfg_combine_f32(float *__restrict__ out,\n"
"    const float *__restrict__ v_cond, const float *__restrict__ v_uncond,\n"
"    float cfg_scale, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) out[i] = v_uncond[i] + cfg_scale * (v_cond[i] - v_uncond[i]);\n"
"}\n"
"\n"

/* Conv2D for VAE: replicate or zero padding, handles any spatial size. */
"__global__ void vae_conv2d_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co, int kh, int kw, int pad_replicate) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oh = h, ow = w;\n"
"    int total = co * oh * ow;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / (oh * ow);\n"
"    int rem = idx % (oh * ow);\n"
"    int oy = rem / ow, ox = rem % ow;\n"
"    int ph = (kh - 1) / 2, pw = (kw - 1) / 2;\n"
"    float sum = bias ? bias[oc] : 0.0f;\n"
"    for (int ic = 0; ic < ci; ic++) {\n"
"        for (int fy = 0; fy < kh; fy++) {\n"
"            for (int fx = 0; fx < kw; fx++) {\n"
"                int iy = oy + fy - ph, ix = ox + fx - pw;\n"
"                if (pad_replicate) {\n"
"                    if (iy < 0) iy = 0; if (iy >= h) iy = h - 1;\n"
"                    if (ix < 0) ix = 0; if (ix >= w) ix = w - 1;\n"
"                } else {\n"
"                    if (iy < 0 || iy >= h || ix < 0 || ix >= w) continue;\n"
"                }\n"
"                sum += inp[ic * h * w + iy * w + ix] *\n"
"                       weight[((oc * ci + ic) * kh + fy) * kw + fx];\n"
"            }\n"
"        }\n"
"    }\n"
"    out[idx] = sum;\n"
"}\n"
"\n"

/* BF16 WMMA implicit-GEMM conv2d 3x3 (replicate or zero pad).
 * Layout: in[Ci,H,W], weight[Co,Ci,3,3], out[Co,H,W].
 * Treats conv as GEMM: M=Co, N=H*W, K=Ci*9.
 * Grid: (Co/16, ceil(H*W/16)). Block: 32 (one wave).
 * Each wave produces a 16x16 output tile (16 oc rows × 16 spatial cols).
 * Lane L: half = L>>4, idx = L&15. A row = idx (oc), B col = idx (sp pixel),
 * K-fragment per lane = half*8..+7. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void vae_conv2d_3x3_wmma_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co, int pad_replicate) {\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    int oc_tile = blockIdx.x * 16;\n"
"    int sp_tile = blockIdx.y * 16;\n"
"    int lane = threadIdx.x;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int sp = h * w;\n"
"    int K_total = ci * 9;\n"
"    float8 acc = {0,0,0,0,0,0,0,0};\n"
"    int oc_a = oc_tile + idx;\n"
"    int spi  = sp_tile + idx;\n"
"    int oy = (spi < sp) ? (spi / w) : 0;\n"
"    int ox = (spi < sp) ? (spi % w) : 0;\n"
"    for (int k0 = 0; k0 < K_total; k0 += 16) {\n"
"        bf16x8 a, b;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int k = k0 + half * 8 + i;\n"
"            int ic = k / 9;\n"
"            int fyx = k - ic * 9;\n"
"            int fy = fyx / 3;\n"
"            int fx = fyx - fy * 3;\n"
"            float wv = 0.f;\n"
"            if (ic < ci && oc_a < co)\n"
"                wv = weight[((oc_a * ci + ic) * 3 + fy) * 3 + fx];\n"
"            float xv = 0.f;\n"
"            if (ic < ci && spi < sp) {\n"
"                int iy = oy + fy - 1;\n"
"                int ix = ox + fx - 1;\n"
"                if (pad_replicate) {\n"
"                    if (iy < 0) iy = 0; if (iy >= h) iy = h - 1;\n"
"                    if (ix < 0) ix = 0; if (ix >= w) ix = w - 1;\n"
"                    xv = inp[ic * sp + iy * w + ix];\n"
"                } else if (iy >= 0 && iy < h && ix >= 0 && ix < w) {\n"
"                    xv = inp[ic * sp + iy * w + ix];\n"
"                }\n"
"            }\n"
"            unsigned int bw, bx;\n"
"            memcpy(&bw, &wv, 4); memcpy(&bx, &xv, 4);\n"
"            a[i] = (short)(bw >> 16);\n"
"            b[i] = (short)(bx >> 16);\n"
"        }\n"
"        acc = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a, b, acc);\n"
"    }\n"
"    for (int i = 0; i < 8; i++) {\n"
"        int oc = oc_tile + half * 8 + i;\n"
"        if (oc < co && spi < sp) {\n"
"            float v = acc[i] + (bias ? bias[oc] : 0.f);\n"
"            out[oc * sp + spi] = v;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* BF16 WMMA implicit-GEMM conv2d 1x1: M=Co, N=H*W, K=Ci.
 * Same lane layout as the 3x3 kernel; K-loop strides Ci. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void vae_conv2d_1x1_wmma_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co) {\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    int oc_tile = blockIdx.x * 16;\n"
"    int sp_tile = blockIdx.y * 16;\n"
"    int lane = threadIdx.x;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int sp = h * w;\n"
"    int oc_a = oc_tile + idx;\n"
"    int spi  = sp_tile + idx;\n"
"    float8 acc = {0,0,0,0,0,0,0,0};\n"
"    for (int k0 = 0; k0 < ci; k0 += 16) {\n"
"        bf16x8 a, b;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int k = k0 + half * 8 + i;\n"
"            float wv = 0.f, xv = 0.f;\n"
"            if (k < ci && oc_a < co) wv = weight[oc_a * ci + k];\n"
"            if (k < ci && spi < sp)  xv = inp[k * sp + spi];\n"
"            unsigned int bw, bx;\n"
"            memcpy(&bw, &wv, 4); memcpy(&bx, &xv, 4);\n"
"            a[i] = (short)(bw >> 16);\n"
"            b[i] = (short)(bx >> 16);\n"
"        }\n"
"        acc = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a, b, acc);\n"
"    }\n"
"    for (int i = 0; i < 8; i++) {\n"
"        int oc = oc_tile + half * 8 + i;\n"
"        if (oc < co && spi < sp) {\n"
"            float v = acc[i] + (bias ? bias[oc] : 0.f);\n"
"            out[oc * sp + spi] = v;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* VAE spatial self-attention (single-head, head_dim=C). Layout:
 *   QKV input: [3*C, spatial] (channels-first, interleaved Q,K,V along channel dim)
 *   Output:    [C, spatial]
 * One CTA per query position. 1 wave (32 threads). Each lane owns 12 channels
 * for C=384 (default Qwen-Image VAE) and uses online FA2 softmax. KV is tiled
 * BKV=8 rows into LDS each iteration. Online softmax uses shfl_xor reduction.
 * Constraints: C must be a multiple of 32. */
"#define VAE_ATTN_BKV  8\n"
"__global__ void vae_self_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ qkv,\n"
"    int spatial, int C) {\n"
"    int qi = blockIdx.x;\n"
"    if (qi >= spatial) return;\n"
"    int lane = threadIdx.x;\n"
"    int ept = C / 32;            /* 12 for C=384 */\n"
"    float scale = rsqrtf((float)C);\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem;             /* [BKV, C] */\n"
"    float *smV = smem + VAE_ATTN_BKV * C;\n"
"    /* Each lane caches its own ept channels of Q[qi]. Layout in qkv is\n"
"     * qkv[ch * spatial + qi] for ch in [0, 3*C). Q occupies ch in [0, C). */\n"
"    float q_r[16];\n"
"    for (int e = 0; e < ept; e++) {\n"
"        int d = lane * ept + e;\n"
"        q_r[e] = qkv[(long)d * spatial + qi];\n"
"    }\n"
"    float m_i = -1e30f, l_i = 0.f;\n"
"    float O_r[16];\n"
"    for (int e = 0; e < ept; e++) O_r[e] = 0.f;\n"
"    int n_tiles = (spatial + VAE_ATTN_BKV - 1) / VAE_ATTN_BKV;\n"
"    int n_threads = 32;\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int kv_base = t * VAE_ATTN_BKV;\n"
"        int kv_lim  = kv_base + VAE_ATTN_BKV;\n"
"        if (kv_lim > spatial) kv_lim = spatial;\n"
"        int n_kv = kv_lim - kv_base;\n"
"        /* Cooperative load smK,smV: [n_kv, C] each. K is qkv[C..2C, kv], V is qkv[2C..3C, kv]. */\n"
"        for (int idx = lane; idx < VAE_ATTN_BKV * C; idx += n_threads) {\n"
"            int kj = idx / C;\n"
"            int d  = idx - kj * C;\n"
"            int kvi = kv_base + kj;\n"
"            float kv_k = 0.f, kv_v = 0.f;\n"
"            if (kvi < spatial) {\n"
"                kv_k = qkv[(long)(C + d) * spatial + kvi];\n"
"                kv_v = qkv[(long)(2 * C + d) * spatial + kvi];\n"
"            }\n"
"            smK[idx] = kv_k;\n"
"            smV[idx] = kv_v;\n"
"        }\n"
"        /* Wave-local sync (1 wave): no global barrier needed but issue a fence so the LDS writes settle. */\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        for (int kj = 0; kj < n_kv; kj++) {\n"
"            float dot = 0.f;\n"
"            for (int e = 0; e < ept; e++) {\n"
"                int d = lane * ept + e;\n"
"                dot += q_r[e] * smK[kj * C + d];\n"
"            }\n"
"            for (int off = 16; off > 0; off >>= 1) dot += __shfl_xor(dot, off);\n"
"            float score = dot * scale;\n"
"            float m_new = fmaxf(m_i, score);\n"
"            float alpha = expf(m_i - m_new);\n"
"            float p     = expf(score - m_new);\n"
"            l_i = l_i * alpha + p;\n"
"            for (int e = 0; e < ept; e++) {\n"
"                int d = lane * ept + e;\n"
"                O_r[e] = O_r[e] * alpha + p * smV[kj * C + d];\n"
"            }\n"
"            m_i = m_new;\n"
"        }\n"
"    }\n"
"    float inv = (l_i > 0.f) ? (1.f / l_i) : 0.f;\n"
"    for (int e = 0; e < ept; e++) {\n"
"        int d = lane * ept + e;\n"
"        out[(long)d * spatial + qi] = O_r[e] * inv;\n"
"    }\n"
"}\n"
"\n"

/* VAE single-head spatial self-attention (Q-blocked, channels-first).
 * Same semantics as vae_self_attn_f32 above, but each CTA handles QB queries
 * sharing the K/V LDS tile, and BKV bumped to 16. With QB=8 BKV=16, KV global
 * traffic drops 16x vs the 1-query-per-CTA version — needed for spatial>=16k.
 * LDS per CTA = 2 * BKV * C * 4 = 48 KB at C=384 (fits 64 KB limit).
 * Block = QB * 32 threads (QB waves, 1 wave per query). Grid = ceil(spatial/QB). */
"#define VAE_ATTN_QB    8\n"
"#define VAE_ATTN_BKVB  16\n"
"__global__ void vae_self_attn_qb_f32(float *__restrict__ out,\n"
"    const float *__restrict__ qkv,\n"
"    int spatial, int C) {\n"
"    int wid  = threadIdx.x >> 5;          /* wave index in CTA */\n"
"    int lane = threadIdx.x & 31;\n"
"    int qi   = blockIdx.x * VAE_ATTN_QB + wid;\n"
"    int ept  = C / 32;\n"
"    float scale = rsqrtf((float)C);\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem;\n"
"    float *smV = smem + VAE_ATTN_BKVB * C;\n"
"    int active = (qi < spatial);\n"
"    float q_r[16];\n"
"    if (active) {\n"
"        for (int e = 0; e < ept; e++) {\n"
"            int d = lane * ept + e;\n"
"            q_r[e] = qkv[(long)d * spatial + qi];\n"
"        }\n"
"    } else {\n"
"        for (int e = 0; e < ept; e++) q_r[e] = 0.f;\n"
"    }\n"
"    float m_i = -1e30f, l_i = 0.f;\n"
"    float O_r[16];\n"
"    for (int e = 0; e < ept; e++) O_r[e] = 0.f;\n"
"    int n_threads = blockDim.x;\n"
"    int tid = threadIdx.x;\n"
"    int n_tiles = (spatial + VAE_ATTN_BKVB - 1) / VAE_ATTN_BKVB;\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int kv_base = t * VAE_ATTN_BKVB;\n"
"        int kv_lim  = kv_base + VAE_ATTN_BKVB;\n"
"        if (kv_lim > spatial) kv_lim = spatial;\n"
"        int n_kv = kv_lim - kv_base;\n"
"        for (int idx = tid; idx < VAE_ATTN_BKVB * C; idx += n_threads) {\n"
"            int kj = idx / C;\n"
"            int d  = idx - kj * C;\n"
"            int kvi = kv_base + kj;\n"
"            float kv_k = 0.f, kv_v = 0.f;\n"
"            if (kvi < spatial) {\n"
"                kv_k = qkv[(long)(C + d) * spatial + kvi];\n"
"                kv_v = qkv[(long)(2 * C + d) * spatial + kvi];\n"
"            }\n"
"            smK[idx] = kv_k;\n"
"            smV[idx] = kv_v;\n"
"        }\n"
"        __syncthreads();\n"
"        if (active) {\n"
"            for (int kj = 0; kj < n_kv; kj++) {\n"
"                float dot = 0.f;\n"
"                for (int e = 0; e < ept; e++) {\n"
"                    int d = lane * ept + e;\n"
"                    dot += q_r[e] * smK[kj * C + d];\n"
"                }\n"
"                for (int off = 16; off > 0; off >>= 1) dot += __shfl_xor(dot, off);\n"
"                float score = dot * scale;\n"
"                float m_new = fmaxf(m_i, score);\n"
"                float alpha = expf(m_i - m_new);\n"
"                float p     = expf(score - m_new);\n"
"                l_i = l_i * alpha + p;\n"
"                for (int e = 0; e < ept; e++) {\n"
"                    int d = lane * ept + e;\n"
"                    O_r[e] = O_r[e] * alpha + p * smV[kj * C + d];\n"
"                }\n"
"                m_i = m_new;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (active) {\n"
"        float inv = (l_i > 0.f) ? (1.f / l_i) : 0.f;\n"
"        for (int e = 0; e < ept; e++) {\n"
"            int d = lane * ept + e;\n"
"            out[(long)d * spatial + qi] = O_r[e] * inv;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

/* RMS norm for VAE: L2-normalize along channels, scale by sqrt(C) * gamma */
"__global__ void vae_rmsnorm_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ gamma,\n"
"    int C, int spatial) {\n"
"    int s = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (s >= spatial) return;\n"
"    float sum_sq = 0.0f;\n"
"    for (int c = 0; c < C; c++) {\n"
"        float v = inp[c * spatial + s];\n"
"        sum_sq += v * v;\n"
"    }\n"
"    float inv_norm = rsqrtf(sum_sq + 1e-12f);\n"
"    float scale = sqrtf((float)C);\n"
"    for (int c = 0; c < C; c++) {\n"
"        float gv = gamma ? gamma[c] : 1.0f;\n"
"        out[c * spatial + s] = inp[c * spatial + s] * inv_norm * scale * gv;\n"
"    }\n"
"}\n"
"\n"

/* SiLU for VAE */
"__global__ void vae_silu_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] = x[i] / (1.0f + expf(-x[i]));\n"
"}\n"
"\n"

/* Nearest-neighbor 2x upsample: [C, H, W] → [C, 2H, 2W] */
"__global__ void nn_upsample2x_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oH = H * 2, oW = W * 2;\n"
"    int total = C * oH * oW;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (oH * oW);\n"
"    int rem = idx % (oH * oW);\n"
"    int oy = rem / oW, ox = rem % oW;\n"
"    int iy = oy / 2, ix = ox / 2;\n"
"    out[idx] = inp[c * H * W + iy * W + ix];\n"
"}\n"
"\n"

/* BF16 truncation: round F32 to BF16 precision in-place */
"__global__ void truncate_bf16_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &x[i], 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&x[i], &bits, 4);\n"
"}\n"
"\n"

/* RMSNorm with weight: x[N, dim] *= rsqrt(mean(x^2)) * w[dim] */
"__global__ void rmsnorm_weighted_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) {\n"
"        float v = x[tok * dim + i];\n"
"        s += v * v;\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        x[tok * dim + i] *= inv * w[i];\n"
"}\n"
"\n"

/* 2D RoPE for image tokens */
"__global__ void rope_2d_f32(float *__restrict__ q, float *__restrict__ k,\n"
"    int n_tok, int n_heads, int head_dim, int h_patches, int w_patches,\n"
"    int t_dim, int h_dim, int w_dim, float theta) {\n"
"    int tok = blockIdx.x;\n"
"    int head = threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    int ph = tok / w_patches, pw = tok % w_patches;\n"
"    float ph_f = (float)ph - (float)(h_patches / 2);\n"
"    float pw_f = (float)pw - (float)(w_patches / 2);\n"
"    int off = head * head_dim;\n"
"    /* Height RoPE at offset t_dim */\n"
"    for (int i = 0; i < h_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)h_dim);\n"
"        float angle = ph_f * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"    /* Width RoPE at offset t_dim + h_dim */\n"
"    for (int i = 0; i < w_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)w_dim);\n"
"        float angle = pw_f * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + h_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"}\n"
"\n"

/* 3-axis RoPE for text tokens */
"__global__ void rope_1d_f32(float *__restrict__ q, float *__restrict__ k,\n"
"    int n_tok, int n_heads, int head_dim, int txt_start,\n"
"    int t_dim, int h_dim, int w_dim, float theta) {\n"
"    int tok = blockIdx.x;\n"
"    int head = threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    int off = head * head_dim;\n"
"    float pos = (float)(txt_start + tok);\n"
"    /* Temporal RoPE */\n"
"    for (int i = 0; i < t_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)t_dim);\n"
"        float angle = pos * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"    /* Height RoPE */\n"
"    for (int i = 0; i < h_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)h_dim);\n"
"        float angle = pos * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"    /* Width RoPE */\n"
"    for (int i = 0; i < w_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)w_dim);\n"
"        float angle = pos * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + h_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"}\n"
"\n"

/* Flash attention for head_dim=128 */
"__device__ __forceinline__ float to_bf16(float f) {\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &f, 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&f, &bits, 4);\n"
"    return f;\n"
"}\n"
"\n"
"#define FA2_WARPS   4\n"
"#define FA2_BKV    16\n"
"#define FA2_HD    128\n"
"#define FA2_EPT     4\n"
"\n"
"__global__ void flash_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    int h  = blockIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int lane    = threadIdx.x % 32;\n"
"    int qi = blockIdx.y * FA2_WARPS + warp_id;\n"
"    float scale = rsqrtf((float)head_dim);\n"
"\n"
"    float q_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) {\n"
"        int d = lane * FA2_EPT + e;\n"
"        q_r[e] = (qi < N && d < head_dim) ? Q[qi * dim + h * head_dim + d] : 0.0f;\n"
"    }\n"
"\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) O_r[e] = 0.0f;\n"
"\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem;\n"
"    float *smV = smem + FA2_BKV * FA2_HD;\n"
"\n"
"    int n_tiles = (N + FA2_BKV - 1) / FA2_BKV;\n"
"    int n_threads = FA2_WARPS * 32;\n"
"\n"
"    for (int tile = 0; tile < n_tiles; tile++) {\n"
"        int kv_base = tile * FA2_BKV;\n"
"        for (int idx = threadIdx.x; idx < FA2_BKV * FA2_HD; idx += n_threads) {\n"
"            int kj = idx / FA2_HD, d = idx % FA2_HD;\n"
"            int kv_tok = kv_base + kj;\n"
"            smK[idx] = (kv_tok < N) ? K[kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"            smV[idx] = (kv_tok < N) ? V[kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        for (int kj = 0; kj < FA2_BKV; kj++) {\n"
"            float dot = 0.0f;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                dot += q_r[e] * smK[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            for (int off = 16; off > 0; off >>= 1)\n"
"                dot += __shfl_xor(dot, off);\n"
"            float score = (kv_base + kj < N) ? dot * scale : -1e30f;\n"
"\n"
"            float new_max = fmaxf(m_i, score);\n"
"            float alpha = expf(m_i - new_max);\n"
"            float p = expf(score - new_max);\n"
"            l_i = l_i * alpha + p;\n"
"            for (int e = 0; e < FA2_EPT; e++) {\n"
"                O_r[e] = O_r[e] * alpha + p * smV[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            }\n"
"            m_i = new_max;\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    if (qi < N) {\n"
"        float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        for (int e = 0; e < FA2_EPT; e++) {\n"
"            int d = lane * FA2_EPT + e;\n"
"            if (d < head_dim)\n"
"                out[qi * dim + h * head_dim + d] = O_r[e] * inv_l;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

/* ---- flash_attn_sa_wmma_f32: BF16 WMMA self-attention (gfx12, head_dim=128).
 * Ported from rdna4/trellis2/hip_trellis2_kernels.h. Grid (n_heads, ceil(N/64)),
 * block 128 = 4 waves. Each wave owns 16 query rows. Br_cta=64, Bc=16. F32 I/O,
 * BF16 in matrix cores. Falls back to scalar via dispatch when head_dim != 128. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void flash_attn_sa_wmma_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    (void)head_dim;\n"
"    int h = blockIdx.x;\n"
"    int cta_q0 = blockIdx.y * 64;\n"
"    int tid = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int dim = n_heads * 128;\n"
"    float scale = rsqrtf(128.f);\n"
"    __shared__ short smK[16*128];\n"
"    __shared__ short smVt[128*16];\n"
"    __shared__ short smQ[4*16*128];\n"
"    __shared__ short smP[4*16*16];\n"
"    short *myQ = smQ + wave * (16*128);\n"
"    short *myP = smP + wave * (16*16);\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    int wq0 = cta_q0 + wave * 16;\n"
"    for (int it = 0; it < 64; it++) {\n"
"        int e = lane * 64 + it;\n"
"        int r = e >> 7;\n"
"        int d = e & 127;\n"
"        int qi = wq0 + r;\n"
"        float qv = (qi < N) ? Q[(long)qi*dim + h*128 + d] : 0.f;\n"
"        unsigned int b; memcpy(&b, &qv, 4);\n"
"        myQ[r*128 + d] = (short)(b >> 16);\n"
"    }\n"
"    float8 O0 = {0,0,0,0,0,0,0,0};\n"
"    float8 O1 = O0, O2 = O0, O3 = O0, O4 = O0, O5 = O0, O6 = O0, O7 = O0;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv = (N + 15) / 16;\n"
"    for (int kv = 0; kv < n_kv; kv++) {\n"
"        int kv_base = kv * 16;\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            float v = (kvi < N) ? K[(long)kvi*dim + h*128 + d] : 0.f;\n"
"            unsigned int b; memcpy(&b, &v, 4);\n"
"            smK[r*128 + d] = (short)(b >> 16);\n"
"        }\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            float v = (kvi < N) ? V[(long)kvi*dim + h*128 + d] : 0.f;\n"
"            unsigned int b; memcpy(&b, &v, 4);\n"
"            smVt[d*16 + r] = (short)(b >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        float8 S = {0,0,0,0,0,0,0,0};\n"
"        for (int kt = 0; kt < 8; kt++) {\n"
"            int k_off = kt * 16 + half * 8;\n"
"            bf16x8 qa, kb;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                qa[i] = myQ[idx*128 + k_off + i];\n"
"                kb[i] = smK[idx*128 + k_off + i];\n"
"            }\n"
"            S = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(qa, kb, S);\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float s = S[i] * scale;\n"
"            int kvi_col = kv_base + idx;\n"
"            if (kvi_col >= N) s = -1e30f;\n"
"            S[i] = s;\n"
"            float m = s;\n"
"            m = fmaxf(m, __shfl_xor(m, 1));\n"
"            m = fmaxf(m, __shfl_xor(m, 2));\n"
"            m = fmaxf(m, __shfl_xor(m, 4));\n"
"            m = fmaxf(m, __shfl_xor(m, 8));\n"
"            row_max[i] = m;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float m_new = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = expf(m_i[i] - m_new);\n"
"            float p = expf(S[i] - m_new);\n"
"            S[i] = p;\n"
"            float rs = p;\n"
"            rs += __shfl_xor(rs, 1);\n"
"            rs += __shfl_xor(rs, 2);\n"
"            rs += __shfl_xor(rs, 4);\n"
"            rs += __shfl_xor(rs, 8);\n"
"            l_i[i] = l_i[i] * alpha[i] + rs;\n"
"            m_i[i] = m_new;\n"
"        }\n"
"        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"        for (int t = 0; t < 8; t++)\n"
"            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = half*8 + i;\n"
"            float pv = S[i];\n"
"            unsigned int b; memcpy(&b, &pv, 4);\n"
"            myP[row*16 + idx] = (short)(b >> 16);\n"
"        }\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        bf16x8 pa;\n"
"        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half*8 + i];\n"
"        for (int t = 0; t < 8; t++) {\n"
"            int hd_base = t * 16;\n"
"            bf16x8 vb;\n"
"            for (int i = 0; i < 8; i++) vb[i] = smVt[(hd_base + idx)*16 + half*8 + i];\n"
"            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(pa, vb, *Os[t]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"    float inv_l[8];\n"
"    for (int i = 0; i < 8; i++)\n"
"        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = t*16 + idx;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int qi = wq0 + half*8 + i;\n"
"            if (qi < N)\n"
"                out[(long)qi*dim + h*128 + col] = (*Os[t])[i] * inv_l[i];\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* FP8 roundtrip quantization */
"__global__ void quantize_fp8_roundtrip_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float v = x[i];\n"
"    if (v > 448.0f) v = 448.0f;\n"
"    if (v < -448.0f) v = -448.0f;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &v, 4);\n"
"    unsigned int sign = bits >> 31;\n"
"    int exp = (int)((bits >> 23) & 0xFF) - 127;\n"
"    unsigned int mant = bits & 0x7FFFFF;\n"
"    int fp8_exp = exp + 7;\n"
"    float result;\n"
"    if (exp < -9) { result = 0.0f; }\n"
"    else if (fp8_exp <= 0) {\n"
"        unsigned int full_mant = mant | 0x800000;\n"
"        int shift = 1 - fp8_exp + 20;\n"
"        if (shift >= 24) { result = 0.0f; }\n"
"        else {\n"
"            unsigned int fp8_mant = (full_mant + (1u << (shift-1))) >> shift;\n"
"            if (fp8_mant > 7) fp8_mant = 7;\n"
"            result = ldexpf((float)fp8_mant / 8.0f, -6);\n"
"            if (sign) result = -result;\n"
"        }\n"
"    } else if (fp8_exp >= 15) {\n"
"        result = sign ? -448.0f : 448.0f;\n"
"    } else {\n"
"        unsigned int fp8_mant = (mant + (1u << 19)) >> 20;\n"
"        if (fp8_mant > 7) { fp8_mant = 0; fp8_exp++; }\n"
"        if (fp8_exp >= 15) { result = sign ? -448.0f : 448.0f; }\n"
"        else { result = ldexpf(1.0f + (float)fp8_mant / 8.0f, fp8_exp - 7);\n"
"               if (sign) result = -result; }\n"
"    }\n"
"    x[i] = result;\n"
"}\n"
"\n"

/* ---- gemm_fp8w_bf16a_wmma_t: BF16-act × FP8-wt WMMA (gfx12 matrix cores)
 *
 * Ported from rdna4/flux2/hip_flux2_kernels.h::gemm_fp8w_bf16a_wmma_t.
 * Qwen-Image FP8 weights have no per-tensor scale (vs Flux.2 Klein), so the
 * w_scale parameter is dropped — output is acc + bias directly.
 *
 * 256 threads = 8 waves per CTA in a 2×4 (M×N) layout, each wave computes
 * a 64×32 sub-tile via 4×2 = 8 WMMA ops with 8 separate float8 accumulators
 * and shared-memory staging. CTA tile 128×128 output.
 *
 * Lane layout (empirically verified on gfx1201 via flux2 wmma_selftest):
 *   A frag (M=16,K=16,bf16): lane L holds A[row=L&15, k=(L>>4)*8..(L>>4)*8+7]
 *   B frag (N=16,K=16,bf16): lane L holds B[col=L&15, k=(L>>4)*8..(L>>4)*8+7]
 *   C out  (M=16,N=16,f32):  lane L holds C[m=(L>>4)*8 + i, n=L&15] for i=0..7
 *
 * Shared memory per CTA: 2 × 128 × 16 × sizeof(short) = 8 KB. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_fp8w_bf16a_wmma_t(float *Y, const unsigned char *W, const float *X,\n"
"                                        const float *bias, int n_out, int n_in, int n_tok) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;       /* 0..7 */\n"
"    int lane    = tid & 31;\n"
"    int wM = wave_id & 1;         /* 0 or 1 */\n"
"    int wN = wave_id >> 1;        /* 0..3 */\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];\n"
"    __shared__ short smB[128*16];\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        /* Load A[128,16] cooperatively: 2048 elements / 256 threads = 8 per thread */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int row = cta_m0 + er;\n"
"            int kp  = k + ek;\n"
"            float xv = (row < n_tok && kp < n_in) ? X[(long)row * n_in + kp] : 0.f;\n"
"            unsigned int xbits; memcpy(&xbits, &xv, 4);\n"
"            smA[er * 16 + ek] = (short)(xbits >> 16);\n"
"        }\n"
"        /* Load B[128,16] via FP8 LUT */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int col = cta_n0 + er;\n"
"            int kp  = k + ek;\n"
"            float wv = (col < n_out && kp < n_in) ? d_fp8_to_f32_lut[W[(long)col * n_in + kp]] : 0.f;\n"
"            unsigned int wbits; memcpy(&wbits, &wv, 4);\n"
"            smB[er * 16 + ek] = (short)(wbits >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        int a_base_row = wM * 64;\n"
"        int b_base_row = wN * 32;\n"
"        bf16x8 a0, a1, a2, a3, b0, b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row + 0  + idx) * 16 + k_off + i];\n"
"            a1[i] = smA[(a_base_row + 16 + idx) * 16 + k_off + i];\n"
"            a2[i] = smA[(a_base_row + 32 + idx) * 16 + k_off + i];\n"
"            a3[i] = smA[(a_base_row + 48 + idx) * 16 + k_off + i];\n"
"            b0[i] = smB[(b_base_row + 0  + idx) * 16 + k_off + i];\n"
"            b1[i] = smB[(b_base_row + 16 + idx) * 16 + k_off + i];\n"
"        }\n"
"        cv00 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b0, cv00);\n"
"        cv01 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b1, cv01);\n"
"        cv10 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b0, cv10);\n"
"        cv11 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b1, cv11);\n"
"        cv20 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b0, cv20);\n"
"        cv21 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b1, cv21);\n"
"        cv30 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b0, cv30);\n"
"        cv31 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b1, cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int ms[8]       = {0,   0,  16, 16, 32, 32, 48, 48};\n"
"    int ns[8]       = {0,  16,   0, 16,  0, 16,  0, 16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + ns[t] + idx;\n"
"        if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + ms[t] + half * 8 + i;\n"
"            if (row < n_tok)\n"
"                Y[(long)row * n_out + col] = acc[i] + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ============================================================
 * FP8×FP8 WMMA path (gfx12). Activations are quantized to E4M3
 * with one scale factor per output row (max-abs / 448), then a
 * 3-LDS-buffer pipelined 128×128 MMA kernel produces F32 output
 * with `acc * scale[row] + bias[col]` writeback.
 *
 * Ported from rdna4/fp8/bench_fp8_gemm.c::gemm_fp8_pipe32_pgr2
 * (the ~218 TF/s mm0 winner). Differences vs the source:
 *   - Per-row activation-scale multiplier on writeback (Qwen-Image
 *     FP8 weights have no per-tensor scale, but the activation
 *     dynamic range needs a per-row rescale to avoid e4m3 outlier
 *     crush).
 *   - Bias-add fused on writeback.
 *   - M-tail handled by zero-padding rows in the quantizer and
 *     gating writes by row < n_tok.
 * ============================================================ */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"

"typedef unsigned char qimg_u8;\n"
"typedef unsigned int  qimg_u32;\n"
"typedef qimg_u32 qimg_u32x2 __attribute__((ext_vector_type(2)));\n"
"typedef qimg_u8  qimg_u8x8  __attribute__((ext_vector_type(8)));\n"
"typedef qimg_u8  qimg_u8x16 __attribute__((ext_vector_type(16)));\n"
"typedef float    qimg_f8    __attribute__((ext_vector_type(8)));\n"

"__device__ __forceinline__ qimg_u32x2 qimg_pack_a8(qimg_u8x8 v) {\n"
"    union { qimg_u8x8 b; qimg_u32x2 w; } u; u.b = v; return u.w;\n"
"}\n"

"__device__ __forceinline__ void qimg_lds_signal(void) {\n"
"    __asm__ __volatile__(\"s_barrier_signal -1\" ::: \"memory\");\n"
"}\n"
"__device__ __forceinline__ void qimg_lds_wait(void) {\n"
"    __asm__ __volatile__(\"s_barrier_wait 0xffff\" ::: \"memory\");\n"
"}\n"
"__device__ __forceinline__ void qimg_lds_barrier(void) { qimg_lds_signal(); qimg_lds_wait(); }\n"

"#define QIMG_WMMA_FP8(A,B,C) C = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(A, B, C)\n"

/* F32 -> FP8 E4M3 (round-nearest, saturate at ±448). Mirrors the rounding
 * scheme used in quantize_fp8_roundtrip_f32 above; output is the raw byte. */
"__device__ __forceinline__ qimg_u8 qimg_f32_to_fp8_e4m3(float f) {\n"
"    if (f > 448.0f) f = 448.0f;\n"
"    if (f < -448.0f) f = -448.0f;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &f, 4);\n"
"    unsigned int sign = bits >> 31;\n"
"    int e = (int)((bits >> 23) & 0xFFu) - 127;\n"
"    unsigned int mant = bits & 0x7FFFFFu;\n"
"    int fp8_exp = e + 7;\n"
"    if (e < -9) return (qimg_u8)(sign << 7);\n"
"    if (fp8_exp <= 0) {\n"
"        unsigned int full_mant = mant | 0x800000u;\n"
"        int shift = 1 - fp8_exp + 20;\n"
"        if (shift >= 24) return (qimg_u8)(sign << 7);\n"
"        unsigned int fp8_mant = (full_mant + (1u << (shift-1))) >> shift;\n"
"        if (fp8_mant > 7) fp8_mant = 7;\n"
"        return (qimg_u8)((sign << 7) | (fp8_mant & 7u));\n"
"    }\n"
"    if (fp8_exp >= 15) return (qimg_u8)((sign << 7) | (15u << 3) | 6u);\n"
"    unsigned int fp8_mant = (mant + (1u << 19)) >> 20;\n"
"    if (fp8_mant > 7) { fp8_mant = 0; fp8_exp++; }\n"
"    if (fp8_exp >= 15) return (qimg_u8)((sign << 7) | (15u << 3) | 6u);\n"
"    return (qimg_u8)((sign << 7) | ((unsigned int)fp8_exp << 3) | (fp8_mant & 7u));\n"
"}\n"

/* Per-row max-abs activation quantizer.
 *
 * Grid: (M_pad,)  Block: 256.  One row per block.
 * Inputs:  X     [n_tok, K]      F32, row-major
 * Outputs: X_fp8 [M_pad, K]      raw FP8 E4M3 bytes (rows >= n_tok zeroed)
 *          scales[M_pad]          row scale s_m = max|X[m,:]|/448 (>=eps)
 *
 * Quantization: s_m = max(|x|) / 448 (clamped to >= 1e-12).
 *               x_fp8[m,k] = round(x[m,k] / s_m)  (saturates at ±448).
 * Reconstruction at GEMM writeback:
 *               y[m,n] = (sum_k x_fp8[m,k] * w_fp8[n,k]) * s_m + bias[n].
 */
"__global__ __launch_bounds__(256, 1)\n"
"void qimg_quantize_act_perrow_fp8(const float *X, qimg_u8 *X_fp8, float *scales,\n"
"                                   int n_tok, int K, int M_pad) {\n"
"    int m = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    if (m >= M_pad) return;\n"
"    if (m >= n_tok) {\n"
"        for (int k = tid; k < K; k += 256) X_fp8[(size_t)m * K + k] = (qimg_u8)0;\n"
"        if (tid == 0) scales[m] = 1.0f;\n"
"        return;\n"
"    }\n"
"    float local_max = 0.f;\n"
"    for (int k = tid; k < K; k += 256) {\n"
"        float v = X[(size_t)m * K + k];\n"
"        v = fabsf(v);\n"
"        if (v > local_max) local_max = v;\n"
"    }\n"
"    for (int off = 16; off > 0; off >>= 1) {\n"
"        float other = __shfl_xor(local_max, off, 32);\n"
"        if (other > local_max) local_max = other;\n"
"    }\n"
"    __shared__ float wave_max[8];\n"
"    int wid = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    if (lane == 0) wave_max[wid] = local_max;\n"
"    __syncthreads();\n"
"    float row_max = 0.f;\n"
"    for (int i = 0; i < 8; i++) if (wave_max[i] > row_max) row_max = wave_max[i];\n"
"    float s = row_max * (1.0f / 448.0f);\n"
"    if (s < 1e-12f) s = 1e-12f;\n"
"    float inv_s = 1.0f / s;\n"
"    if (tid == 0) scales[m] = s;\n"
"    for (int k = tid; k < K; k += 256) {\n"
"        float v = X[(size_t)m * K + k] * inv_s;\n"
"        X_fp8[(size_t)m * K + k] = qimg_f32_to_fp8_e4m3(v);\n"
"    }\n"
"}\n"

/* Per-row store helper: Y[r,col] = acc[i] * scales[r] + bias[col], gated by
 * (r < n_tok && col < n_out). 8 different rows per call, one column. */
"__device__ __forceinline__ void qimg_store_acc8_pr(\n"
"    float *Y, const float *bias, const float *scales,\n"
"    qimg_f8 acc, int row0, int col, int N, int n_tok, int n_out) {\n"
"    if (col >= n_out) return;\n"
"    float bv = bias ? bias[col] : 0.0f;\n"
"    if (row0 + 0 < n_tok) Y[(size_t)(row0+0)*N + col] = acc[0] * scales[row0+0] + bv;\n"
"    if (row0 + 1 < n_tok) Y[(size_t)(row0+1)*N + col] = acc[1] * scales[row0+1] + bv;\n"
"    if (row0 + 2 < n_tok) Y[(size_t)(row0+2)*N + col] = acc[2] * scales[row0+2] + bv;\n"
"    if (row0 + 3 < n_tok) Y[(size_t)(row0+3)*N + col] = acc[3] * scales[row0+3] + bv;\n"
"    if (row0 + 4 < n_tok) Y[(size_t)(row0+4)*N + col] = acc[4] * scales[row0+4] + bv;\n"
"    if (row0 + 5 < n_tok) Y[(size_t)(row0+5)*N + col] = acc[5] * scales[row0+5] + bv;\n"
"    if (row0 + 6 < n_tok) Y[(size_t)(row0+6)*N + col] = acc[6] * scales[row0+6] + bv;\n"
"    if (row0 + 7 < n_tok) Y[(size_t)(row0+7)*N + col] = acc[7] * scales[row0+7] + bv;\n"
"}\n"

/* gemm_fp8_fp8w_perrow_pgr2: FP8 act × FP8 wt -> F32, per-row act scale.
 *
 * Layout: A is X[M_pad, K] FP8 row-major (act, pre-quantized);
 *         B is W[N, K]     FP8 row-major (weight stored transposed once);
 *         Y[n_tok, N]      F32 row-major (output).
 * Constraints: K % 32 == 0, N % 128 == 0, M_pad % 128 == 0.
 * Grid:  (N/128, M_pad/128)  Block: 128 (4 waves × 32 lanes).
 *
 * 3-deep LDS buffer pipeline: we issue global loads for K-step (k+64) while
 * computing on rd_buf, holding up to two K-steps in flight before the WMMA
 * burst is done. Mirrors rdna4/fp8/bench_fp8_gemm.c::gemm_fp8_pipe32_pgr2.
 */
"#define QIMG_SPLIT_HI(v) __builtin_shufflevector(v, v, 8,9,10,11,12,13,14,15)\n"
"#define QIMG_SPLIT_LO(v) __builtin_shufflevector(v, v, 0,1,2,3,4,5,6,7)\n"

"__global__ __launch_bounds__(128, 1)\n"
"void gemm_fp8_fp8w_perrow_pgr2(float *Y, const qimg_u8 *W, const qimg_u8 *X,\n"
"                                const float *bias, const float *act_scales,\n"
"                                int n_out, int n_in, int n_tok, int M_pad) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int wM = wave_id & 1;\n"
"    int wN = wave_id >> 1;\n"
"    int half = lane >> 4;\n"
"    int idx = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    int K = n_in;\n"
"    int N = n_out;\n"
"    int e0 = tid * 2 + 0;\n"
"    int e1 = tid * 2 + 1;\n"
"    int r0 = e0 >> 1, r1 = e1 >> 1;\n"
"    int c0 = (e0 & 1) * 16, c1 = (e1 & 1) * 16;\n"
"    __shared__ qimg_u8x8 smA8[3 * 128 * 4];\n"
"    __shared__ qimg_u8x8 smB8[3 * 128 * 4];\n"
"    #define QIMG_LOAD(na0,na1,nb0,nb1, kk) do { \\\n"
"        na0 = *((const qimg_u8x16 *)(X + (size_t)(cta_m0 + r0) * K + (kk) + c0)); \\\n"
"        na1 = *((const qimg_u8x16 *)(X + (size_t)(cta_m0 + r1) * K + (kk) + c1)); \\\n"
"        nb0 = *((const qimg_u8x16 *)(W + (size_t)(cta_n0 + r0) * K + (kk) + c0)); \\\n"
"        nb1 = *((const qimg_u8x16 *)(W + (size_t)(cta_n0 + r1) * K + (kk) + c1)); \\\n"
"    } while(0)\n"
"    #define QIMG_WRITE_LDS(buf_idx, na0,na1,nb0,nb1) do { \\\n"
"        int nbase = (buf_idx) * (128 * 4); \\\n"
"        smA8[nbase + (c0>>3)*128 + r0]     = QIMG_SPLIT_LO(na0); \\\n"
"        smA8[nbase + ((c0>>3)+1)*128 + r0] = QIMG_SPLIT_HI(na0); \\\n"
"        smA8[nbase + (c1>>3)*128 + r1]     = QIMG_SPLIT_LO(na1); \\\n"
"        smA8[nbase + ((c1>>3)+1)*128 + r1] = QIMG_SPLIT_HI(na1); \\\n"
"        smB8[nbase + (c0>>3)*128 + r0]     = QIMG_SPLIT_LO(nb0); \\\n"
"        smB8[nbase + ((c0>>3)+1)*128 + r0] = QIMG_SPLIT_HI(nb0); \\\n"
"        smB8[nbase + (c1>>3)*128 + r1]     = QIMG_SPLIT_LO(nb1); \\\n"
"        smB8[nbase + ((c1>>3)+1)*128 + r1] = QIMG_SPLIT_HI(nb1); \\\n"
"    } while(0)\n"
"    qimg_u8x16 g0a0,g0a1,g0b0,g0b1; QIMG_LOAD(g0a0,g0a1,g0b0,g0b1, 0);\n"
"    QIMG_WRITE_LDS(0, g0a0,g0a1,g0b0,g0b1);\n"
"    qimg_u8x16 g1a0,g1a1,g1b0,g1b1;\n"
"    int has_k1 = (32 < K);\n"
"    if (has_k1) { QIMG_LOAD(g1a0,g1a1,g1b0,g1b1, 32); QIMG_WRITE_LDS(1, g1a0,g1a1,g1b0,g1b1); }\n"
"    qimg_lds_barrier();\n"
"    qimg_f8 z = {0,0,0,0,0,0,0,0};\n"
"    qimg_f8 cv00=z,cv01=z,cv02=z,cv03=z;\n"
"    qimg_f8 cv10=z,cv11=z,cv12=z,cv13=z;\n"
"    qimg_f8 cv20=z,cv21=z,cv22=z,cv23=z;\n"
"    qimg_f8 cv30=z,cv31=z,cv32=z,cv33=z;\n"
"    int rd_buf = 0;\n"
"    int wr_buf = 2;\n"
"    for (int k = 0; k < K; k += 32) {\n"
"        qimg_u8x16 na0,na1,nb0,nb1;\n"
"        int has_far = (k + 64 < K);\n"
"        if (has_far) QIMG_LOAD(na0,na1,nb0,nb1, k + 64);\n"
"        int base = rd_buf * (128 * 4);\n"
"        int a_base = wM * 64;\n"
"        int b_base = wN * 64;\n"
"        for (int kk0 = 0; kk0 < 32; kk0 += 16) {\n"
"            int kslot = (kk0 + k_off) >> 3;\n"
"            qimg_u8x8 a0 = smA8[base + kslot * 128 + (a_base + 0  + idx)];\n"
"            qimg_u8x8 a1 = smA8[base + kslot * 128 + (a_base + 16 + idx)];\n"
"            qimg_u8x8 a2 = smA8[base + kslot * 128 + (a_base + 32 + idx)];\n"
"            qimg_u8x8 a3 = smA8[base + kslot * 128 + (a_base + 48 + idx)];\n"
"            qimg_u8x8 b0 = smB8[base + kslot * 128 + (b_base + 0  + idx)];\n"
"            qimg_u8x8 b1 = smB8[base + kslot * 128 + (b_base + 16 + idx)];\n"
"            qimg_u8x8 b2 = smB8[base + kslot * 128 + (b_base + 32 + idx)];\n"
"            qimg_u8x8 b3 = smB8[base + kslot * 128 + (b_base + 48 + idx)];\n"
"            qimg_u32x2 ra0 = qimg_pack_a8(a0), ra1 = qimg_pack_a8(a1);\n"
"            qimg_u32x2 ra2 = qimg_pack_a8(a2), ra3 = qimg_pack_a8(a3);\n"
"            qimg_u32x2 rb0 = qimg_pack_a8(b0), rb1 = qimg_pack_a8(b1);\n"
"            qimg_u32x2 rb2 = qimg_pack_a8(b2), rb3 = qimg_pack_a8(b3);\n"
"            QIMG_WMMA_FP8(ra0, rb0, cv00); QIMG_WMMA_FP8(ra0, rb1, cv01);\n"
"            QIMG_WMMA_FP8(ra0, rb2, cv02); QIMG_WMMA_FP8(ra0, rb3, cv03);\n"
"            QIMG_WMMA_FP8(ra1, rb0, cv10); QIMG_WMMA_FP8(ra1, rb1, cv11);\n"
"            QIMG_WMMA_FP8(ra1, rb2, cv12); QIMG_WMMA_FP8(ra1, rb3, cv13);\n"
"            QIMG_WMMA_FP8(ra2, rb0, cv20); QIMG_WMMA_FP8(ra2, rb1, cv21);\n"
"            QIMG_WMMA_FP8(ra2, rb2, cv22); QIMG_WMMA_FP8(ra2, rb3, cv23);\n"
"            QIMG_WMMA_FP8(ra3, rb0, cv30); QIMG_WMMA_FP8(ra3, rb1, cv31);\n"
"            QIMG_WMMA_FP8(ra3, rb2, cv32); QIMG_WMMA_FP8(ra3, rb3, cv33);\n"
"        }\n"
"        if (has_far) {\n"
"            QIMG_WRITE_LDS(wr_buf, na0,na1,nb0,nb1);\n"
"            qimg_lds_signal();\n"
"            wr_buf = (wr_buf + 1) % 3;\n"
"            rd_buf = (rd_buf + 1) % 3;\n"
"            qimg_lds_wait();\n"
"        } else if (k + 32 < K) {\n"
"            qimg_lds_signal();\n"
"            rd_buf = (rd_buf + 1) % 3;\n"
"            qimg_lds_wait();\n"
"        }\n"
"    }\n"
"    #undef QIMG_LOAD\n"
"    #undef QIMG_WRITE_LDS\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 64;\n"
"    int row = wave_m0 + half * 8;\n"
"    if (row >= n_tok) return;\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv00, row +  0, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv01, row +  0, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv02, row +  0, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv03, row +  0, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv10, row + 16, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv11, row + 16, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv12, row + 16, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv13, row + 16, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv20, row + 32, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv21, row + 32, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv22, row + 32, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv23, row + 32, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv30, row + 48, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv31, row + 48, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv32, row + 48, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    qimg_store_acc8_pr(Y, bias, act_scales, cv33, row + 48, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"}\n"
"#endif\n"
"\n"

/* ============================================================
 * FP8 flash-attention (gated by QIMG_FP8_ATTN env). HD hardcoded
 * to 128 (Qwen-Image DiT). Per-head symmetric max-abs scale on
 * Q/K (folded into kernel `scale` arg = sQ*sK/sqrt(HD)); V quant
 * with separate scale folded into output multiply.
 *
 * Kernel layout: BQ=64 queries × BKV=16 keys, 4 waves/CTA. WMMA
 * v_wmma_f32_16x16x16_fp8_fp8 for both QK^T and PV. Mirrors
 * rdna4/fp8/bench_fp8_fa.c flash_attn_fp8_4w.
 * ============================================================ */

"#define QIMG_FP8FA_HD   128\n"
"#define QIMG_FP8FA_KNB  (QIMG_FP8FA_HD / 16)\n"
"#define QIMG_FP8FA_BQ   64\n"
"#define QIMG_FP8FA_BKV  16\n"

/* Per-row max-abs quantization for Q: per (token, head), reduce max-abs over
 * head_dim, write Q_fp8 + scales. Q layout [n_tok, n_heads, head_dim] kept;
 * scales are head-major [n_heads, n_tok] for cache-friendly access in FA. */
"__global__ void qimg_q_quant_fp8_perrow(\n"
"    unsigned char *__restrict__ Q_fp8, float *__restrict__ scales,\n"
"    const float *__restrict__ Q, int n_tok, int n_heads, int head_dim) {\n"
"    int row = blockIdx.x;\n"
"    int h   = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    int n_th= blockDim.x;\n"
"    if (row >= n_tok || h >= n_heads) return;\n"
"    long base = (long)row*(n_heads*head_dim) + (long)h*head_dim;\n"
"    float m = 0.f;\n"
"    for (int d = tid; d < head_dim; d += n_th) {\n"
"        float v = Q[base+d]; if (v < 0) v = -v; if (v > m) m = v;\n"
"    }\n"
"    extern __shared__ float qrm_sm[];\n"
"    qrm_sm[tid] = m; __syncthreads();\n"
"    for (int r = n_th/2; r > 0; r >>= 1) {\n"
"        if (tid < r && qrm_sm[tid+r] > qrm_sm[tid]) qrm_sm[tid] = qrm_sm[tid+r];\n"
"        __syncthreads();\n"
"    }\n"
"    float s = qrm_sm[0]/448.f; if (s < 1e-9f) s = 1e-9f;\n"
"    if (tid == 0) scales[(long)h*n_tok + row] = s;\n"
"    float inv = 1.f/s;\n"
"    for (int d = tid; d < head_dim; d += n_th) {\n"
"        float v = Q[base+d] * inv;\n"
"        Q_fp8[base+d] = qimg_f32_to_fp8_e4m3(v);\n"
"    }\n"
"}\n"

/* Per-row K quantize+repack: input [n_tok, n_heads, head_dim] -> output
 * head-major [n_heads, n_tok, head_dim]; per-(token,head) scales head-major. */
"__global__ void qimg_k_quant_repack_fp8_perrow(\n"
"    unsigned char *__restrict__ K_fp8, float *__restrict__ scales,\n"
"    const float *__restrict__ K, int n_tok, int n_heads, int head_dim) {\n"
"    int row = blockIdx.x;\n"
"    int h   = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    int n_th= blockDim.x;\n"
"    if (row >= n_tok || h >= n_heads) return;\n"
"    long base_in  = (long)row*(n_heads*head_dim) + (long)h*head_dim;\n"
"    long base_out = ((long)h*n_tok + row) * head_dim;\n"
"    float m = 0.f;\n"
"    for (int d = tid; d < head_dim; d += n_th) {\n"
"        float v = K[base_in+d]; if (v < 0) v = -v; if (v > m) m = v;\n"
"    }\n"
"    extern __shared__ float krm_sm[];\n"
"    krm_sm[tid] = m; __syncthreads();\n"
"    for (int r = n_th/2; r > 0; r >>= 1) {\n"
"        if (tid < r && krm_sm[tid+r] > krm_sm[tid]) krm_sm[tid] = krm_sm[tid+r];\n"
"        __syncthreads();\n"
"    }\n"
"    float s = krm_sm[0]/448.f; if (s < 1e-9f) s = 1e-9f;\n"
"    if (tid == 0) scales[(long)h*n_tok + row] = s;\n"
"    float inv = 1.f/s;\n"
"    for (int d = tid; d < head_dim; d += n_th) {\n"
"        float v = K[base_in+d] * inv;\n"
"        K_fp8[base_out+d] = qimg_f32_to_fp8_e4m3(v);\n"
"    }\n"
"}\n"

/* Reduce per-head max-abs of Q (and K, V) along (n_tok, head_dim). Block per
 * head, threads cooperatively scan all rows. Writes one F32 per head. */
"__global__ void qimg_qkv_perhead_maxabs_f32(\n"
"    float *__restrict__ q_max, float *__restrict__ k_max, float *__restrict__ v_max,\n"
"    const float *__restrict__ Q, const float *__restrict__ K, const float *__restrict__ V,\n"
"    int n_tok, int n_heads, int head_dim) {\n"
"    int h = blockIdx.x; if (h >= n_heads) return;\n"
"    int tid = threadIdx.x;\n"
"    int n_th = blockDim.x;\n"
"    float qm=0.f, km=0.f, vm=0.f;\n"
"    long total = (long)n_tok * head_dim;\n"
"    for (long t = tid; t < total; t += n_th) {\n"
"        long row = t / head_dim;\n"
"        long d   = t - row * head_dim;\n"
"        long off = row * (long)(n_heads*head_dim) + (long)h*head_dim + d;\n"
"        float qv = Q[off]; if (qv < 0) qv = -qv; if (qv > qm) qm = qv;\n"
"        float kv = K[off]; if (kv < 0) kv = -kv; if (kv > km) km = kv;\n"
"        float vv = V[off]; if (vv < 0) vv = -vv; if (vv > vm) vm = vv;\n"
"    }\n"
"    extern __shared__ float reduce_sm[];\n"
"    float *sQ = reduce_sm;\n"
"    float *sK = reduce_sm + n_th;\n"
"    float *sV = reduce_sm + 2*n_th;\n"
"    sQ[tid] = qm; sK[tid] = km; sV[tid] = vm;\n"
"    __syncthreads();\n"
"    for (int r = n_th/2; r > 0; r >>= 1) {\n"
"        if (tid < r) {\n"
"            if (sQ[tid+r] > sQ[tid]) sQ[tid] = sQ[tid+r];\n"
"            if (sK[tid+r] > sK[tid]) sK[tid] = sK[tid+r];\n"
"            if (sV[tid+r] > sV[tid]) sV[tid] = sV[tid+r];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (tid == 0) {\n"
"        float qs = sQ[0]/448.f; if (qs < 1e-9f) qs = 1e-9f;\n"
"        float ks = sK[0]/448.f; if (ks < 1e-9f) ks = 1e-9f;\n"
"        float vs = sV[0]/448.f; if (vs < 1e-9f) vs = 1e-9f;\n"
"        q_max[h] = qs; k_max[h] = ks; v_max[h] = vs;\n"
"    }\n"
"}\n"

/* Quantize Q into FP8 with the same [n_tok, n_heads, head_dim] layout. */
"__global__ void qimg_q_quant_fp8(\n"
"    unsigned char *__restrict__ Q_fp8, const float *__restrict__ Q,\n"
"    const float *__restrict__ q_scale, int n_tok, int n_heads, int head_dim) {\n"
"    int row = blockIdx.x;\n"
"    int h   = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (row >= n_tok || h >= n_heads) return;\n"
"    float s = q_scale[h]; float inv = 1.f/s;\n"
"    long base = (long)row*(n_heads*head_dim) + (long)h*head_dim;\n"
"    for (int d = tid; d < head_dim; d += blockDim.x) {\n"
"        float v = Q[base+d] * inv;\n"
"        Q_fp8[base+d] = qimg_f32_to_fp8_e4m3(v);\n"
"    }\n"
"}\n"

/* Quantize K (or V) and repack to head-major: [n_tok,n_heads,hd] -> [n_heads,n_tok,hd] FP8 */
"__global__ void qimg_kv_quant_repack_fp8(\n"
"    unsigned char *__restrict__ KV_fp8_hm, const float *__restrict__ KV,\n"
"    const float *__restrict__ kv_scale, int n_tok, int n_heads, int head_dim) {\n"
"    int row = blockIdx.x;\n"
"    int h   = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (row >= n_tok || h >= n_heads) return;\n"
"    float s = kv_scale[h]; float inv = 1.f/s;\n"
"    long base_in  = (long)row*(n_heads*head_dim) + (long)h*head_dim;\n"
"    long base_out = ((long)h*n_tok + row) * head_dim;\n"
"    for (int d = tid; d < head_dim; d += blockDim.x) {\n"
"        float v = KV[base_in+d] * inv;\n"
"        KV_fp8_hm[base_out+d] = qimg_f32_to_fp8_e4m3(v);\n"
"    }\n"
"}\n"

/* Per-row FP8 FA. Q with per-(token,head) sQ, K head-major with per-row sK,
 * V head-major with per-head sV. Score post-WMMA scaled by sQ[m]*sK[n]*1/sqrt(d).
 * smSq[64] loaded once per CTA, smSk[16] reloaded per KV tile. */
"__global__ __launch_bounds__(128, 1)\n"
"void qimg_flash_attn_fp8_4w_perrow(float *out, const unsigned char *Q,\n"
"                                   const unsigned char *K_t, const unsigned char *V_t,\n"
"                                   const float *sQ, const float *sK,\n"
"                                   const float *v_scales,\n"
"                                   int n_tok, int n_heads, float inv_sqrtd) {\n"
"    typedef unsigned char u8;\n"
"    typedef unsigned int  u32;\n"
"    typedef u32 u32x2 __attribute__((ext_vector_type(2)));\n"
"    typedef u8  u8x8  __attribute__((ext_vector_type(8)));\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    const int HD = QIMG_FP8FA_HD;\n"
"    const int BQ = QIMG_FP8FA_BQ;\n"
"    const int BKV= QIMG_FP8FA_BKV;\n"
"    const int K_NB = QIMG_FP8FA_KNB;\n"
"    int h    = blockIdx.x;\n"
"    int qb   = blockIdx.y;\n"
"    int q0   = qb * BQ;\n"
"    int tid  = threadIdx.x;\n"
"    int wid  = tid >> 5;\n"
"    int lid  = tid & 31;\n"
"    int half = lid >> 4;\n"
"    int idx  = lid & 15;\n"
"    int dim  = n_heads * HD;\n"
"    __shared__ u8 smK[16 * QIMG_FP8FA_HD];\n"
"    __shared__ u8 smV[QIMG_FP8FA_HD * 16];\n"
"    __shared__ u8 smP[4 * 16 * 16];\n"
"    __shared__ float smSq[QIMG_FP8FA_BQ];\n"
"    __shared__ float smSk[QIMG_FP8FA_BKV];\n"
"    u8 *smP_w = smP + wid * 16 * 16;\n"
"    /* Load smSq[64] for this CTA's queries (head h, rows q0..q0+63). */\n"
"    for (int i = tid; i < BQ; i += blockDim.x) {\n"
"        int row = q0 + i;\n"
"        smSq[i] = (row < n_tok) ? sQ[(long)h*n_tok + row] : 1.f;\n"
"    }\n"
"    int q_row = q0 + wid * 16 + idx;\n"
"    u32x2 q_reg[QIMG_FP8FA_KNB];\n"
"    {\n"
"        u8x8 tmp;\n"
"        for (int kb = 0; kb < K_NB; kb++) {\n"
"            for (int i = 0; i < 8; i++) {\n"
"                int d = kb * 16 + half * 8 + i;\n"
"                u8 qv = 0;\n"
"                if (q_row < n_tok && d < HD)\n"
"                    qv = Q[(long)q_row * dim + h * HD + d];\n"
"                tmp[i] = qv;\n"
"            }\n"
"            union { u8x8 b; u32x2 w; } u; u.b = tmp; q_reg[kb] = u.w;\n"
"        }\n"
"    }\n"
"    float8 O_acc[QIMG_FP8FA_KNB];\n"
"    for (int kb = 0; kb < K_NB; kb++) for (int i = 0; i < 8; i++) O_acc[kb][i] = 0.f;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv_tiles = (n_tok + BKV - 1) / BKV;\n"
"    int ld_row = tid >> 3;\n"
"    int ld_d0  = (tid & 7) * (HD / 8);\n"
"    /* Pre-fetch this lane's per-row Q scales (8 m_rows). */\n"
"    __syncthreads();\n"
"    float sq_lane[8];\n"
"    for (int i = 0; i < 8; i++) {\n"
"        int m_row = wid*16 + half*8 + i;\n"
"        sq_lane[i] = smSq[m_row];\n"
"    }\n"
"    for (int t = 0; t < n_kv_tiles; t++) {\n"
"        int kv = t * BKV + ld_row;\n"
"        long kv_base = ((long)h * n_tok + kv) * HD;\n"
"        bool kv_ok = (kv < n_tok);\n"
"        for (int j = 0; j < HD/8; j++) {\n"
"            int d = ld_d0 + j;\n"
"            u8 kv_K = 0, kv_V = 0;\n"
"            if (kv_ok && d < HD) { kv_K = K_t[kv_base+d]; kv_V = V_t[kv_base+d]; }\n"
"            smK[ld_row*HD+d] = kv_K;\n"
"            smV[d*16+ld_row] = kv_V;\n"
"        }\n"
"        if (tid < BKV) {\n"
"            int kvi = t*BKV + tid;\n"
"            smSk[tid] = (kvi < n_tok) ? sK[(long)h*n_tok + kvi] : 1.f;\n"
"        }\n"
"        __syncthreads();\n"
"        int kv0 = t * BKV;\n"
"        float8 score = {0,0,0,0,0,0,0,0};\n"
"        for (int kb = 0; kb < K_NB; kb++) {\n"
"            u8x8 b_K;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                int dpos = kb * 16 + half * 8 + i;\n"
"                b_K[i] = smK[idx*HD+dpos];\n"
"            }\n"
"            union { u8x8 b; u32x2 w; } u; u.b = b_K; u32x2 b_K_p = u.w;\n"
"            score = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(q_reg[kb], b_K_p, score);\n"
"        }\n"
"        bool col_valid = (kv0 + idx) < n_tok;\n"
"        float sk_lane = smSk[idx];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float real = score[i] * sq_lane[i] * sk_lane * inv_sqrtd;\n"
"            score[i] = col_valid ? real : -1e30f;\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float v = score[i];\n"
"            v = fmaxf(v, __shfl_xor(v,1,32));\n"
"            v = fmaxf(v, __shfl_xor(v,2,32));\n"
"            v = fmaxf(v, __shfl_xor(v,4,32));\n"
"            v = fmaxf(v, __shfl_xor(v,8,32));\n"
"            row_max[i] = v;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float new_max = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = __expf(m_i[i] - new_max);\n"
"            float ej = __expf(score[i] - new_max);\n"
"            float s = ej;\n"
"            s += __shfl_xor(s,1,32);\n"
"            s += __shfl_xor(s,2,32);\n"
"            s += __shfl_xor(s,4,32);\n"
"            s += __shfl_xor(s,8,32);\n"
"            l_i[i] = l_i[i]*alpha[i] + s;\n"
"            m_i[i] = new_max;\n"
"            score[i] = ej;\n"
"        }\n"
"        for (int kb = 0; kb < K_NB; kb++)\n"
"            for (int i = 0; i < 8; i++) O_acc[kb][i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int m_row = half*8 + i;\n"
"            int n_col = idx;\n"
"            smP_w[m_row*16+n_col] = qimg_f32_to_fp8_e4m3(score[i]);\n"
"        }\n"
"        u8x8 ap_b;\n"
"        for (int i = 0; i < 8; i++) ap_b[i] = smP_w[idx*16 + half*8 + i];\n"
"        union { u8x8 b; u32x2 w; } uap; uap.b = ap_b; u32x2 ap = uap.w;\n"
"        for (int kb = 0; kb < K_NB; kb++) {\n"
"            u8x8 bv;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                int d_col = kb*16 + idx;\n"
"                int kv_k = half*8 + i;\n"
"                bv[i] = smV[d_col*16 + kv_k];\n"
"            }\n"
"            union { u8x8 b; u32x2 w; } uv; uv.b = bv; u32x2 bv_p = uv.w;\n"
"            O_acc[kb] = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(ap, bv_p, O_acc[kb]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    int q_base = q0 + wid * 16;\n"
"    float vs = v_scales[h];\n"
"    for (int kb = 0; kb < K_NB; kb++) {\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int m_row = half*8 + i;\n"
"            int d = kb*16 + idx;\n"
"            int row = q_base + m_row;\n"
"            if (row < n_tok && d < HD) {\n"
"                float v = O_acc[kb][i] * vs / (l_i[i] > 0.f ? l_i[i] : 1.f);\n"
"                out[(long)row*dim + h*HD + d] = v;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"

/* FP8 FA kernel — same layout as flash_attn_fp8_4w. Writes O*v_scale. */
"__global__ __launch_bounds__(128, 1)\n"
"void qimg_flash_attn_fp8_4w(float *out, const unsigned char *Q,\n"
"                            const unsigned char *K_t, const unsigned char *V_t,\n"
"                            const float *qk_scales, const float *v_scales,\n"
"                            int n_tok, int n_heads, float inv_sqrtd) {\n"
"    float scale = qk_scales[blockIdx.x] * inv_sqrtd;\n"
"    typedef unsigned char u8;\n"
"    typedef unsigned int  u32;\n"
"    typedef u32 u32x2 __attribute__((ext_vector_type(2)));\n"
"    typedef u8  u8x8  __attribute__((ext_vector_type(8)));\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    const int HD = QIMG_FP8FA_HD;\n"
"    const int BQ = QIMG_FP8FA_BQ;\n"
"    const int BKV= QIMG_FP8FA_BKV;\n"
"    const int K_NB = QIMG_FP8FA_KNB;\n"
"    int h    = blockIdx.x;\n"
"    int qb   = blockIdx.y;\n"
"    int q0   = qb * BQ;\n"
"    int tid  = threadIdx.x;\n"
"    int wid  = tid >> 5;\n"
"    int lid  = tid & 31;\n"
"    int half = lid >> 4;\n"
"    int idx  = lid & 15;\n"
"    int dim  = n_heads * HD;\n"
"    __shared__ u8 smK[16 * QIMG_FP8FA_HD];\n"
"    __shared__ u8 smV[QIMG_FP8FA_HD * 16];\n"
"    __shared__ u8 smP[4 * 16 * 16];\n"
"    u8 *smP_w = smP + wid * 16 * 16;\n"
"    int q_row = q0 + wid * 16 + idx;\n"
"    u32x2 q_reg[QIMG_FP8FA_KNB];\n"
"    {\n"
"        u8x8 tmp;\n"
"        for (int kb = 0; kb < K_NB; kb++) {\n"
"            for (int i = 0; i < 8; i++) {\n"
"                int d = kb * 16 + half * 8 + i;\n"
"                u8 qv = 0;\n"
"                if (q_row < n_tok && d < HD)\n"
"                    qv = Q[(long)q_row * dim + h * HD + d];\n"
"                tmp[i] = qv;\n"
"            }\n"
"            union { u8x8 b; u32x2 w; } u; u.b = tmp; q_reg[kb] = u.w;\n"
"        }\n"
"    }\n"
"    float8 O_acc[QIMG_FP8FA_KNB];\n"
"    for (int kb = 0; kb < K_NB; kb++) for (int i = 0; i < 8; i++) O_acc[kb][i] = 0.f;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv_tiles = (n_tok + BKV - 1) / BKV;\n"
"    int ld_row = tid >> 3;\n"
"    int ld_d0  = (tid & 7) * (HD / 8);\n"
"    for (int t = 0; t < n_kv_tiles; t++) {\n"
"        int kv = t * BKV + ld_row;\n"
"        long kv_base = ((long)h * n_tok + kv) * HD;\n"
"        bool kv_ok = (kv < n_tok);\n"
"        for (int j = 0; j < HD/8; j++) {\n"
"            int d = ld_d0 + j;\n"
"            u8 kv_K = 0, kv_V = 0;\n"
"            if (kv_ok && d < HD) { kv_K = K_t[kv_base+d]; kv_V = V_t[kv_base+d]; }\n"
"            smK[ld_row*HD+d] = kv_K;\n"
"            smV[d*16+ld_row] = kv_V;\n"
"        }\n"
"        __syncthreads();\n"
"        int kv0 = t * BKV;\n"
"        float8 score = {0,0,0,0,0,0,0,0};\n"
"        for (int kb = 0; kb < K_NB; kb++) {\n"
"            u8x8 b_K;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                int dpos = kb * 16 + half * 8 + i;\n"
"                b_K[i] = smK[idx*HD+dpos];\n"
"            }\n"
"            union { u8x8 b; u32x2 w; } u; u.b = b_K; u32x2 b_K_p = u.w;\n"
"            score = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(q_reg[kb], b_K_p, score);\n"
"        }\n"
"        bool col_valid = (kv0 + idx) < n_tok;\n"
"        for (int i = 0; i < 8; i++) score[i] = col_valid ? score[i] * scale : -1e30f;\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float v = score[i];\n"
"            v = fmaxf(v, __shfl_xor(v,1,32));\n"
"            v = fmaxf(v, __shfl_xor(v,2,32));\n"
"            v = fmaxf(v, __shfl_xor(v,4,32));\n"
"            v = fmaxf(v, __shfl_xor(v,8,32));\n"
"            row_max[i] = v;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float new_max = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = __expf(m_i[i] - new_max);\n"
"            float ej = __expf(score[i] - new_max);\n"
"            float s = ej;\n"
"            s += __shfl_xor(s,1,32);\n"
"            s += __shfl_xor(s,2,32);\n"
"            s += __shfl_xor(s,4,32);\n"
"            s += __shfl_xor(s,8,32);\n"
"            l_i[i] = l_i[i]*alpha[i] + s;\n"
"            m_i[i] = new_max;\n"
"            score[i] = ej;\n"
"        }\n"
"        for (int kb = 0; kb < K_NB; kb++)\n"
"            for (int i = 0; i < 8; i++) O_acc[kb][i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int m_row = half*8 + i;\n"
"            int n_col = idx;\n"
"            smP_w[m_row*16+n_col] = qimg_f32_to_fp8_e4m3(score[i]);\n"
"        }\n"
"        u8x8 ap_b;\n"
"        for (int i = 0; i < 8; i++) ap_b[i] = smP_w[idx*16 + half*8 + i];\n"
"        union { u8x8 b; u32x2 w; } u; u.b = ap_b; u32x2 ap = u.w;\n"
"        for (int kb = 0; kb < K_NB; kb++) {\n"
"            u8x8 bv;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                int d_col = kb*16 + idx;\n"
"                int kv_k = half*8 + i;\n"
"                bv[i] = smV[d_col*16 + kv_k];\n"
"            }\n"
"            union { u8x8 b; u32x2 w; } uv; uv.b = bv; u32x2 bv_p = uv.w;\n"
"            O_acc[kb] = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(ap, bv_p, O_acc[kb]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    int q_base = q0 + wid * 16;\n"
"    float vs = v_scales[h];\n"
"    for (int kb = 0; kb < K_NB; kb++) {\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int m_row = half*8 + i;\n"
"            int d = kb*16 + idx;\n"
"            int row = q_base + m_row;\n"
"            if (row < n_tok && d < HD) {\n"
"                float v = O_acc[kb][i] * vs / (l_i[i] > 0.f ? l_i[i] : 1.f);\n"
"                out[(long)row*dim + h*HD + d] = v;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"

"}\n";  /* close extern "C" from hip_kernels_common_src */

#endif /* HIP_QIMG_KERNELS_H */
