/*
 * hip_qimg_kernels.h - HIP kernel source strings for Qwen-Image
 *
 * Contains all Qwen-Image specific HIP kernels as a C string literal for
 * HIPRTC runtime compilation. Concatenated after hip_kernels_common_src
 * (which opens extern "C" {) and closes it at the end.
 *
 * Port of cuda_qimg_runner.h kernels for AMD ROCm/HIP (RDNA4, gfx1201).
 * Key differences from CUDA version:
 *   - __shfl_xor_sync -> __shfl_xor (no sync mask on HIP)
 *   - __shfl_down_sync -> __shfl_down
 *   - No FP8 hardware: weights dequanted to F32 on CPU before upload
 *   - No PTX inline asm: BF16 truncation uses memcpy
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_QIMG_KERNELS_H
#define HIP_QIMG_KERNELS_H

static const char hip_qimg_specific_kernels[] =
"\n"

/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */
"/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */\n"
"__global__ void gemm_f32_f32(float *Y, const float *W, const float *X,\n"
"                              const float *bias,\n"
"                              int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* Per-head RMSNorm: x[N, dim], w[head_dim], n_heads, head_dim */
"__global__ void rmsnorm_per_head_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int n_heads, int head_dim) {\n"
"    int tok = blockIdx.x;\n"
"    int h = blockIdx.y;\n"
"    if (tok >= N || h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    float *hd = x + tok * dim + h * head_dim;\n"
"    float ss = 0.0f;\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        ss += hd[i] * hd[i];\n"
"    /* Warp reduce */\n"
"    for (int m = 16; m > 0; m >>= 1)\n"
"        ss += __shfl_xor(ss, m);\n"
"    float inv = rsqrtf(ss / (float)head_dim + 1e-6f);\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        hd[i] *= inv * w[i];\n"
"}\n"
"\n"

/* adaLN modulate: out = LN(x) * (1+scale) + shift */
"__global__ void adaln_modulate_f32(float *__restrict__ out,\n"
"    const float *__restrict__ x, const float *__restrict__ shift,\n"
"    const float *__restrict__ scale, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    /* Compute mean */\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) s += x[tok*dim+i];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    /* Compute var */\n"
"    s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) { float d = x[tok*dim+i] - mean; s += d*d; }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    /* Apply modulation */\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        out[tok*dim+i] = ((x[tok*dim+i] - mean) * inv) * (1.0f + scale[i]) + shift[i];\n"
"}\n"
"\n"

/* Gated residual: x += gate * proj */
"__global__ void gated_add_f32(float *__restrict__ x,\n"
"    const float *__restrict__ proj, const float *__restrict__ gate,\n"
"    int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N * dim) return;\n"
"    int col = i % dim;\n"
"    x[i] += gate[col] * proj[i];\n"
"}\n"
"\n"

/* Patchify: latent [C, H, W] → tokens [H/ps*W/ps, C*ps*ps] */
"__global__ void patchify_f32(float *__restrict__ out,\n"
"    const float *__restrict__ latent, int C, int H, int W, int ps) {\n"
"    int tok = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int hp = H / ps, wp = W / ps;\n"
"    if (tok >= hp * wp) return;\n"
"    int py = tok / wp, px = tok % wp;\n"
"    int tok_dim = C * ps * ps;\n"
"    int idx = 0;\n"
"    for (int c = 0; c < C; c++)\n"
"        for (int dy = 0; dy < ps; dy++)\n"
"            for (int dx = 0; dx < ps; dx++)\n"
"                out[tok * tok_dim + idx++] = latent[c * H * W + (py*ps+dy) * W + (px*ps+dx)];\n"
"}\n"
"\n"

/* Unpatchify: tokens [seq, C*ps*ps] → latent [C, H, W] */
"__global__ void unpatchify_f32(float *__restrict__ out,\n"
"    const float *__restrict__ tokens, int C, int H, int W, int ps) {\n"
"    int tok = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int hp = H / ps, wp = W / ps;\n"
"    if (tok >= hp * wp) return;\n"
"    int py = tok / wp, px = tok % wp;\n"
"    int tok_dim = C * ps * ps;\n"
"    int idx = 0;\n"
"    for (int c = 0; c < C; c++)\n"
"        for (int dy = 0; dy < ps; dy++)\n"
"            for (int dx = 0; dx < ps; dx++)\n"
"                out[c * H * W + (py*ps+dy) * W + (px*ps+dx)] = tokens[tok * tok_dim + idx++];\n"
"}\n"
"\n"

/* Euler step: x = x + dt * v */
"__global__ void euler_step_f32(float *__restrict__ x,\n"
"    const float *__restrict__ v, float dt, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] += dt * v[i];\n"
"}\n"
"\n"

/* CFG combine: out = v_uncond + cfg_scale * (v_cond - v_uncond) */
"__global__ void cfg_combine_f32(float *__restrict__ out,\n"
"    const float *__restrict__ v_cond, const float *__restrict__ v_uncond,\n"
"    float cfg_scale, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) out[i] = v_uncond[i] + cfg_scale * (v_cond[i] - v_uncond[i]);\n"
"}\n"
"\n"

/* Conv2D for VAE: replicate or zero padding, handles any spatial size. */
"__global__ void vae_conv2d_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co, int kh, int kw, int pad_replicate) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oh = h, ow = w;\n"
"    int total = co * oh * ow;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / (oh * ow);\n"
"    int rem = idx % (oh * ow);\n"
"    int oy = rem / ow, ox = rem % ow;\n"
"    int ph = (kh - 1) / 2, pw = (kw - 1) / 2;\n"
"    float sum = bias ? bias[oc] : 0.0f;\n"
"    for (int ic = 0; ic < ci; ic++) {\n"
"        for (int fy = 0; fy < kh; fy++) {\n"
"            for (int fx = 0; fx < kw; fx++) {\n"
"                int iy = oy + fy - ph, ix = ox + fx - pw;\n"
"                if (pad_replicate) {\n"
"                    if (iy < 0) iy = 0; if (iy >= h) iy = h - 1;\n"
"                    if (ix < 0) ix = 0; if (ix >= w) ix = w - 1;\n"
"                } else {\n"
"                    if (iy < 0 || iy >= h || ix < 0 || ix >= w) continue;\n"
"                }\n"
"                sum += inp[ic * h * w + iy * w + ix] *\n"
"                       weight[((oc * ci + ic) * kh + fy) * kw + fx];\n"
"            }\n"
"        }\n"
"    }\n"
"    out[idx] = sum;\n"
"}\n"
"\n"

/* RMS norm for VAE: L2-normalize along channels, scale by sqrt(C) * gamma */
"__global__ void vae_rmsnorm_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ gamma,\n"
"    int C, int spatial) {\n"
"    int s = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (s >= spatial) return;\n"
"    float sum_sq = 0.0f;\n"
"    for (int c = 0; c < C; c++) {\n"
"        float v = inp[c * spatial + s];\n"
"        sum_sq += v * v;\n"
"    }\n"
"    float inv_norm = rsqrtf(sum_sq + 1e-12f);\n"
"    float scale = sqrtf((float)C);\n"
"    for (int c = 0; c < C; c++) {\n"
"        float gv = gamma ? gamma[c] : 1.0f;\n"
"        out[c * spatial + s] = inp[c * spatial + s] * inv_norm * scale * gv;\n"
"    }\n"
"}\n"
"\n"

/* SiLU for VAE */
"__global__ void vae_silu_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] = x[i] / (1.0f + expf(-x[i]));\n"
"}\n"
"\n"

/* Nearest-neighbor 2x upsample: [C, H, W] → [C, 2H, 2W] */
"__global__ void nn_upsample2x_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oH = H * 2, oW = W * 2;\n"
"    int total = C * oH * oW;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (oH * oW);\n"
"    int rem = idx % (oH * oW);\n"
"    int oy = rem / oW, ox = rem % oW;\n"
"    int iy = oy / 2, ix = ox / 2;\n"
"    out[idx] = inp[c * H * W + iy * W + ix];\n"
"}\n"
"\n"

/* BF16 truncation: round F32 to BF16 precision in-place */
"__global__ void truncate_bf16_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &x[i], 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&x[i], &bits, 4);\n"
"}\n"
"\n"

/* RMSNorm with weight: x[N, dim] *= rsqrt(mean(x^2)) * w[dim] */
"__global__ void rmsnorm_weighted_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) {\n"
"        float v = x[tok * dim + i];\n"
"        s += v * v;\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        x[tok * dim + i] *= inv * w[i];\n"
"}\n"
"\n"

/* 2D RoPE for image tokens */
"__global__ void rope_2d_f32(float *__restrict__ q, float *__restrict__ k,\n"
"    int n_tok, int n_heads, int head_dim, int h_patches, int w_patches,\n"
"    int t_dim, int h_dim, int w_dim, float theta) {\n"
"    int tok = blockIdx.x;\n"
"    int head = threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    int ph = tok / w_patches, pw = tok % w_patches;\n"
"    float ph_f = (float)ph - (float)(h_patches / 2);\n"
"    float pw_f = (float)pw - (float)(w_patches / 2);\n"
"    int off = head * head_dim;\n"
"    /* Height RoPE at offset t_dim */\n"
"    for (int i = 0; i < h_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)h_dim);\n"
"        float angle = ph_f * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"    /* Width RoPE at offset t_dim + h_dim */\n"
"    for (int i = 0; i < w_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)w_dim);\n"
"        float angle = pw_f * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + h_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"}\n"
"\n"

/* 3-axis RoPE for text tokens */
"__global__ void rope_1d_f32(float *__restrict__ q, float *__restrict__ k,\n"
"    int n_tok, int n_heads, int head_dim, int txt_start,\n"
"    int t_dim, int h_dim, int w_dim, float theta) {\n"
"    int tok = blockIdx.x;\n"
"    int head = threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    int off = head * head_dim;\n"
"    float pos = (float)(txt_start + tok);\n"
"    /* Temporal RoPE */\n"
"    for (int i = 0; i < t_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)t_dim);\n"
"        float angle = pos * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"    /* Height RoPE */\n"
"    for (int i = 0; i < h_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)h_dim);\n"
"        float angle = pos * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"    /* Width RoPE */\n"
"    for (int i = 0; i < w_dim / 2; i++) {\n"
"        float freq = 1.0f / powf(theta, 2.0f * (float)i / (float)w_dim);\n"
"        float angle = pos * freq;\n"
"        float cs = cosf(angle), sn = sinf(angle);\n"
"        int idx = off + t_dim + h_dim + 2 * i;\n"
"        float q0 = q[tok*dim+idx], q1 = q[tok*dim+idx+1];\n"
"        q[tok*dim+idx]   = q0*cs - q1*sn;\n"
"        q[tok*dim+idx+1] = q0*sn + q1*cs;\n"
"        float k0 = k[tok*dim+idx], k1 = k[tok*dim+idx+1];\n"
"        k[tok*dim+idx]   = k0*cs - k1*sn;\n"
"        k[tok*dim+idx+1] = k0*sn + k1*cs;\n"
"    }\n"
"}\n"
"\n"

/* Flash attention for head_dim=128 */
"__device__ __forceinline__ float to_bf16(float f) {\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &f, 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&f, &bits, 4);\n"
"    return f;\n"
"}\n"
"\n"
"#define FA2_WARPS   4\n"
"#define FA2_BKV    16\n"
"#define FA2_HD    128\n"
"#define FA2_EPT     4\n"
"\n"
"__global__ void flash_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    int h  = blockIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int lane    = threadIdx.x % 32;\n"
"    int qi = blockIdx.y * FA2_WARPS + warp_id;\n"
"    float scale = rsqrtf((float)head_dim);\n"
"\n"
"    float q_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) {\n"
"        int d = lane * FA2_EPT + e;\n"
"        q_r[e] = (qi < N && d < head_dim) ? Q[qi * dim + h * head_dim + d] : 0.0f;\n"
"    }\n"
"\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) O_r[e] = 0.0f;\n"
"\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem;\n"
"    float *smV = smem + FA2_BKV * FA2_HD;\n"
"\n"
"    int n_tiles = (N + FA2_BKV - 1) / FA2_BKV;\n"
"    int n_threads = FA2_WARPS * 32;\n"
"\n"
"    for (int tile = 0; tile < n_tiles; tile++) {\n"
"        int kv_base = tile * FA2_BKV;\n"
"        for (int idx = threadIdx.x; idx < FA2_BKV * FA2_HD; idx += n_threads) {\n"
"            int kj = idx / FA2_HD, d = idx % FA2_HD;\n"
"            int kv_tok = kv_base + kj;\n"
"            smK[idx] = (kv_tok < N) ? K[kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"            smV[idx] = (kv_tok < N) ? V[kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        for (int kj = 0; kj < FA2_BKV; kj++) {\n"
"            float dot = 0.0f;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                dot += q_r[e] * smK[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            for (int off = 16; off > 0; off >>= 1)\n"
"                dot += __shfl_xor(dot, off);\n"
"            float score = (kv_base + kj < N) ? dot * scale : -1e30f;\n"
"\n"
"            float new_max = fmaxf(m_i, score);\n"
"            float alpha = expf(m_i - new_max);\n"
"            float p = expf(score - new_max);\n"
"            l_i = l_i * alpha + p;\n"
"            for (int e = 0; e < FA2_EPT; e++) {\n"
"                O_r[e] = O_r[e] * alpha + p * smV[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            }\n"
"            m_i = new_max;\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    if (qi < N) {\n"
"        float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        for (int e = 0; e < FA2_EPT; e++) {\n"
"            int d = lane * FA2_EPT + e;\n"
"            if (d < head_dim)\n"
"                out[qi * dim + h * head_dim + d] = O_r[e] * inv_l;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

/* FP8 roundtrip quantization */
"__global__ void quantize_fp8_roundtrip_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float v = x[i];\n"
"    if (v > 448.0f) v = 448.0f;\n"
"    if (v < -448.0f) v = -448.0f;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &v, 4);\n"
"    unsigned int sign = bits >> 31;\n"
"    int exp = (int)((bits >> 23) & 0xFF) - 127;\n"
"    unsigned int mant = bits & 0x7FFFFF;\n"
"    int fp8_exp = exp + 7;\n"
"    float result;\n"
"    if (exp < -9) { result = 0.0f; }\n"
"    else if (fp8_exp <= 0) {\n"
"        unsigned int full_mant = mant | 0x800000;\n"
"        int shift = 1 - fp8_exp + 20;\n"
"        if (shift >= 24) { result = 0.0f; }\n"
"        else {\n"
"            unsigned int fp8_mant = (full_mant + (1u << (shift-1))) >> shift;\n"
"            if (fp8_mant > 7) fp8_mant = 7;\n"
"            result = ldexpf((float)fp8_mant / 8.0f, -6);\n"
"            if (sign) result = -result;\n"
"        }\n"
"    } else if (fp8_exp >= 15) {\n"
"        result = sign ? -448.0f : 448.0f;\n"
"    } else {\n"
"        unsigned int fp8_mant = (mant + (1u << 19)) >> 20;\n"
"        if (fp8_mant > 7) { fp8_mant = 0; fp8_exp++; }\n"
"        if (fp8_exp >= 15) { result = sign ? -448.0f : 448.0f; }\n"
"        else { result = ldexpf(1.0f + (float)fp8_mant / 8.0f, fp8_exp - 7);\n"
"               if (sign) result = -result; }\n"
"    }\n"
"    x[i] = result;\n"
"}\n"
"\n"

"}\n";  /* close extern "C" from hip_kernels_common_src */

#endif /* HIP_QIMG_KERNELS_H */
