/* CPU shape_dec driver that runs guided forward with caches generated by
 * rdna4/trellis2/tools/pyt_subdiv_to_cache.py. Used to produce a CPU-side
 * numerical reference for the HIP shape_dec backbone (Milestone A).
 *
 * Set T2SD_STOP_AFTER_STAGE=<N> and T2SD_DUMP_PATH=<file.npy> to exit early
 * after stage N's C2S and dump intermediate feats.
 *
 * Usage:
 *   test_shape_dec_dump <weights.st> <slat.npy> <coords.npy> <cache_dir> [-t threads]
 */
#define GGML_DEQUANT_IMPLEMENTATION
#include "../../common/ggml_dequant.h"
#define SAFETENSORS_IMPLEMENTATION
#include "../../common/safetensors.h"
#define SPARSE3D_IMPLEMENTATION
#include "../../common/sparse3d.h"
#define T2_SHAPE_DEC_IMPLEMENTATION
#include "../../common/trellis2_shape_decoder.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

static void *read_npy(const char *p, int *nd, int *dd, size_t elem) {
    FILE *f=fopen(p,"rb"); if(!f){fprintf(stderr,"open %s failed\n",p);return NULL;}
    fseek(f,8,SEEK_SET); uint16_t hl; if(fread(&hl,2,1,f)!=1){fclose(f);return NULL;}
    char *h=malloc(hl+1); fread(h,1,hl,f); h[hl]=0;
    *nd=0; char *sp=strstr(h,"shape"); if(sp){sp=strchr(sp,'('); if(sp){sp++;
        while(*sp&&*sp!=')'){while(*sp==' '||*sp==',')sp++;
            if(*sp==')')break; dd[*nd]=(int)strtol(sp,&sp,10);(*nd)++;}}}
    size_t n=1; for(int i=0;i<*nd;i++) n*=dd[i];
    void *d=malloc(n*elem); fread(d,elem,n,f);
    fclose(f); free(h); return d;
}

int main(int argc, char **argv) {
    if (argc < 5) {
        fprintf(stderr, "Usage: %s <shape_dec.st> <slat.npy> <coords.npy> <cache_dir> [-t threads]\n", argv[0]);
        return 1;
    }
    int n_threads = 8;
    for (int i = 5; i < argc; i++)
        if (!strcmp(argv[i], "-t") && i+1 < argc) n_threads = atoi(argv[++i]);

    t2_shape_dec *dec = t2_shape_dec_load(argv[1]);
    if (!dec) return 1;

    int nd, dd[8];
    float *slat_feats = (float *)read_npy(argv[2], &nd, dd, sizeof(float));
    int N = dd[0], C = nd >= 2 ? dd[1] : 1;
    fprintf(stderr, "slat: [%d,%d]\n", N, C);
    int32_t *coords = (int32_t *)read_npy(argv[3], &nd, dd, sizeof(int32_t));

    sp3d_tensor *slat = sp3d_create(coords, slat_feats, N, C, 1);

    /* Load 3-stage guide from cache_dir (scales 16, 8, 4). */
    int scales[3] = {16, 8, 4};
    t2_shape_dec_subdiv_stage stages[3] = {0};
    int64_t *idx_buf[3] = {0};
    int64_t *sub_buf[3] = {0};
    int32_t *xc_buf[3] = {0};
    for (int s = 0; s < 3; s++) {
        char p[512];
        snprintf(p, sizeof p, "%s/cache_scale%d_c2s_idx.npy", argv[4], scales[s]);
        idx_buf[s] = (int64_t *)read_npy(p, &nd, dd, sizeof(int64_t));
        int Nf = dd[0];
        snprintf(p, sizeof p, "%s/cache_scale%d_c2s_subidx.npy", argv[4], scales[s]);
        int32_t *s32 = (int32_t *)read_npy(p, &nd, dd, sizeof(int32_t));
        sub_buf[s] = (int64_t *)malloc((size_t)Nf * sizeof(int64_t));
        for (int k = 0; k < Nf; k++) sub_buf[s][k] = (int64_t)s32[k];
        free(s32);
        snprintf(p, sizeof p, "%s/cache_scale%d_c2s_x_coords.npy", argv[4], scales[s]);
        xc_buf[s] = (int32_t *)read_npy(p, &nd, dd, sizeof(int32_t));
        stages[s].idx = idx_buf[s];
        stages[s].subidx = sub_buf[s];
        stages[s].x_coords = xc_buf[s];
        stages[s].N_fine = Nf;
        fprintf(stderr, "guide stage %d (scale=%d): N_fine=%d\n", s, scales[s], Nf);
    }
    /* For 4-stage decoder, we only have 3 guides — pad the 4th with whatever
     * (forward_guided counts only stages with conv1_w; the 4th still expects
     * a guide). Fall back: skip the 4th stage by using T2SD_STOP_AFTER_STAGE. */
    t2_shape_dec_guide guide = { stages, 3 };

    /* Force stop after stage 2 (post-c2s); driver exits inside forward. */
    if (!getenv("T2SD_STOP_AFTER_STAGE")) setenv("T2SD_STOP_AFTER_STAGE", "2", 0);
    if (!getenv("T2SD_DUMP_PATH")) setenv("T2SD_DUMP_PATH", "cpu_shape_stage2_c2s.npy", 0);

    /* Decoder has 4 C2S stages; we provide 3 — must stop before stage 3 starts. */
    t2_shape_dec_result r = t2_shape_dec_forward_guided(dec, slat, &guide, n_threads);
    fprintf(stderr, "result: N=%d C=%d\n", r.N, r.C);

    t2_shape_dec_result_free(&r);
    sp3d_free(slat);
    free(slat_feats); free(coords);
    for (int s = 0; s < 3; s++) { free(idx_buf[s]); free(sub_buf[s]); free(xc_buf[s]); }
    t2_shape_dec_free(dec);
    return 0;
}
