/* Batched copies of scalar arithmetic; no BF16 activation packing. */
"__global__ void qwen4_router_batch_native(const unsigned short *gate_w,const unsigned short *sgate_w,\n"
"        const float *x,int ne,int n_cols,float *logits,float *shared_scale) {\n"
"    x+=(size_t)blockIdx.y*n_cols; logits+=(size_t)blockIdx.y*ne; shared_scale+=blockIdx.y;\n"
"    int e = blockIdx.x; int tid = threadIdx.x;\n"
"    const unsigned short *wr = (e < ne) ? gate_w + (size_t)e * n_cols : sgate_w;\n"
"    float p = 0.0f;\n"
"    for (int j = tid; j < n_cols; j += blockDim.x) {\n"
"        unsigned int b16 = (unsigned int)wr[j] << 16; float w; __builtin_memcpy(&w, &b16, 4);\n"
"        p += w * x[j];\n"
"    }\n"
"    for (int o = 16; o > 0; o >>= 1) p += __shfl_down(p, o);\n"
"    __shared__ float ws[8];\n"
"    if ((tid & 31) == 0) ws[tid >> 5] = p;\n"
"    __syncthreads();\n"
"    if (tid == 0) {\n"
"        float t = 0; for (int w = 0; w < 8; w++) t += ws[w];\n"
"        if (e < ne) logits[e] = t;\n"
"        else shared_scale[0] = 1.0f / (1.0f + expf(-t));\n"
"    }\n"
"}\n"
"__global__ void shexp_gateup_silu_q6k_batch(float *out, const unsigned char *gw,\n"
"        const unsigned char *uw, const float *x, int eff, int n_cols) {out+=(size_t)blockIdx.y*eff; x+=(size_t)blockIdx.y*n_cols;\n"
"    int warp_id = threadIdx.x / 32; int lane = threadIdx.x % 32;\n"
"    int row = blockIdx.x * 8 + warp_id; if (row >= eff) return;\n"
"    int nb = n_cols / 256; int row_bytes = nb * 210;\n"
"    int G = nb * 16;\n"
"    float sg = 0.0f, su = 0.0f;\n"
"    for (int g = lane; g < G; g += 32) {\n"
"        int b = g >> 4; int rem = g & 15; int half = rem >> 3; int lp = rem & 7;\n"
"        sg += q6k_dot4(gw + (size_t)row * row_bytes + b * 210, x + b * 256, half, lp);\n"
"        su += q6k_dot4(uw + (size_t)row * row_bytes + b * 210, x + b * 256, half, lp);\n"
"    }\n"
"    for (int o = 16; o > 0; o >>= 1) { sg += __shfl_down(sg, o); su += __shfl_down(su, o); }\n"
"    if (lane == 0) out[row] = (sg / (1.0f + expf(-sg))) * su;\n"
"}\n"
"__global__ void shexp_down_accum_q6k_batch(float *accum, const unsigned char *dw,\n"
"        const float *x, int n_embd, int eff, const float *scale_ptr) {accum+=(size_t)blockIdx.y*n_embd; x+=(size_t)blockIdx.y*eff; scale_ptr+=blockIdx.y;\n"
"    int warp_id = threadIdx.x / 32; int lane = threadIdx.x % 32;\n"
"    int row = blockIdx.x * 8 + warp_id; if (row >= n_embd) return;\n"
"    int nb = eff / 256; int row_bytes = nb * 210;\n"
"    const unsigned char *row_ptr = dw + (size_t)row * row_bytes;\n"
"    int G = nb * 64;\n"
"    float sum = 0.0f;\n"
"    for (int g = lane; g < G; g += 32) {\n"
"        int b = g >> 6; int rem = g & 63; int half = rem >> 5; int l = rem & 31;\n"
"        const unsigned char *bp = row_ptr + b * 210;\n"
"        const unsigned char *ql = bp + half * 64;\n"
"        const unsigned char *qh = bp + 128 + half * 32;\n"
"        const signed char *sc = (const signed char *)(bp + 192 + half * 8);\n"
"        float d = half_to_float(*(const half_raw *)(bp + 208));\n"
"        const float *xb = x + b * 256 + half * 128;\n"
"        int hi = (l < 16) ? 0 : 1;\n"
"        float sA = d * (float)sc[0 + hi], sB = d * (float)sc[2 + hi];\n"
"        float sC = d * (float)sc[4 + hi], sD = d * (float)sc[6 + hi];\n"
"        int q1 = (int)((ql[l]    & 0xF) | (((qh[l]>>0)&3)<<4)) - 32;\n"
"        int q2 = (int)((ql[l+32] & 0xF) | (((qh[l]>>2)&3)<<4)) - 32;\n"
"        int q3 = (int)((ql[l]    >> 4)  | (((qh[l]>>4)&3)<<4)) - 32;\n"
"        int q4 = (int)((ql[l+32] >> 4)  | (((qh[l]>>6)&3)<<4)) - 32;\n"
"        sum += sA*q1*xb[l] + sB*q2*xb[l+32] + sC*q3*xb[l+64] + sD*q4*xb[l+96];\n"
"    }\n"
"    for (int o = 16; o > 0; o >>= 1) sum += __shfl_down(sum, o);\n"
"    if (lane == 0) accum[row] += scale_ptr[0] * sum;\n"
"}\n"
"__global__ void shexp_gateup_silu_q8_batch(float *out,const unsigned char *gw,const unsigned char *uw,\n"
"        const float *x,int eff,int n_cols){out+=(size_t)blockIdx.y*eff; x+=(size_t)blockIdx.y*n_cols;int warp=threadIdx.x/32,lane=threadIdx.x%32;\n"
"    int row=blockIdx.x*4+warp;if(row>=eff)return;int nb=n_cols/32,rb=nb*36;float sg=0,su=0;\n"
"    const unsigned char *gr=gw+(size_t)row*rb,*ur=uw+(size_t)row*rb;\n"
"    for(int b=lane;b<nb;b+=32){const unsigned char *gb=gr+b*36,*ub=ur+b*36;const float *xb=x+b*32;\n"
"        const signed char *gq=(const signed char *)(gb+4),*uq=(const signed char *)(ub+4);float ag=0,au=0;\n"
"        #pragma unroll\n"
"        for(int j=0;j<32;j++){ag+=(float)gq[j]*xb[j];au+=(float)uq[j]*xb[j];}\n"
"        sg+=ag*half_to_float(*(const half_raw *)gb);su+=au*half_to_float(*(const half_raw *)ub);}\n"
"    for(int o=16;o>0;o>>=1){sg+=__shfl_down(sg,o);su+=__shfl_down(su,o);}\n"
"    if(lane==0)out[row]=(sg/(1.0f+expf(-sg)))*su;}\n"
"__global__ void shexp_down_accum_q8_batch(float *accum,const unsigned char *dw,const float *x,\n"
"        int n_embd,int eff,const float *scale_ptr){accum+=(size_t)blockIdx.y*n_embd; x+=(size_t)blockIdx.y*eff; scale_ptr+=blockIdx.y;int warp=threadIdx.x/32,lane=threadIdx.x%32;\n"
"    int row=blockIdx.x*4+warp;if(row>=n_embd)return;int nb=eff/32,rb=nb*36;float sum=0;\n"
"    const unsigned char *rp=dw+(size_t)row*rb;for(int b=lane;b<nb;b+=32){const unsigned char *bp=rp+b*36;\n"
"        const signed char *q=(const signed char *)(bp+4);const float *xb=x+b*32;float s=0;\n"
"        #pragma unroll\n"
"        for(int j=0;j<32;j++)s+=(float)q[j]*xb[j];sum+=s*half_to_float(*(const half_raw *)bp);}\n"
"    for(int o=16;o>0;o>>=1)sum+=__shfl_down(sum,o);if(lane==0)accum[row]+=scale_ptr[0]*sum;}\n"
