/* Q2_0 grouped prefill: each assignment owns one output row tile. The
 * expert map selects either resident cache slots or a staging-bank slot. */
"__global__ void qwen4_gateup_silu_q2_grouped(float *dst,\n"
"        const unsigned char *gate,const unsigned char *up,const float *in,\n"
"        const int *task_e,const int *task_p,const int *map,int rows,int cols,\n"
"        long long gs,long long us){\n"
"    int warp=threadIdx.x/32,lane=threadIdx.x&31,row=blockIdx.x*(blockDim.x/32)+warp;\n"
"    int task=blockIdx.y;if(row>=rows)return;int e=task_e[task],p=task_p[task],slot=map[e];\n"
"    if(slot<0)return;int rb=(cols/64)*18;\n"
"    const unsigned char *gr=gate+(long long)slot*gs+(size_t)row*rb;\n"
"    const unsigned char *ur=up+(long long)slot*us+(size_t)row*rb;\n"
"    const float *x=in+(size_t)p*cols;float g=0.0f,u=0.0f;\n"
"    for(int qi=lane;qi<cols/4;qi+=32){int b=qi/16,z=qi&15;\n"
"        const unsigned char *gb=gr+b*18,*ub=ur+b*18;\n"
"        float gd=half_to_float(*(const half_raw *)gb),ud=half_to_float(*(const half_raw *)ub);\n"
"        int gq=gb[2+z],uq=ub[2+z];const float *xp=x+qi*4;\n"
"        #pragma unroll\n"
"        for(int j=0;j<4;j++){float xv=xp[j];\n"
"            g+=(float)(((gq>>(2*j))&3)-1)*gd*xv;\n"
"            u+=(float)(((uq>>(2*j))&3)-1)*ud*xv;}\n"
"    }\n"
"    for(int o=16;o>0;o>>=1){g+=__shfl_down(g,o);u+=__shfl_down(u,o);}\n"
"    if(lane==0)dst[(size_t)p*rows+row]=(g/(1.0f+expf(-g)))*u;\n"
"}\n"
"__global__ void qwen4_down_q2_grouped(float *out,const unsigned char *down,\n"
"        const float *act,const int *task_e,const int *task_p,const int *map,\n"
"        int rows,int cols,long long ds){\n"
"    int warp=threadIdx.x/32,lane=threadIdx.x&31,row=blockIdx.x*(blockDim.x/32)+warp;\n"
"    int task=blockIdx.y;if(row>=rows)return;int e=task_e[task],p=task_p[task],slot=map[e];\n"
"    if(slot<0)return;int rb=(cols/64)*18;\n"
"    const unsigned char *rp=down+(long long)slot*ds+(size_t)row*rb;\n"
"    const float *x=act+(size_t)p*cols;float sum=0.0f;\n"
"    for(int qi=lane;qi<cols/4;qi+=32){int b=qi/16,z=qi&15;\n"
"        const unsigned char *bp=rp+b*18;float d=half_to_float(*(const half_raw *)bp);\n"
"        int q=bp[2+z];const float *xp=x+qi*4;\n"
"        #pragma unroll\n"
"        for(int j=0;j<4;j++)sum+=(float)(((q>>(2*j))&3)-1)*d*xp[j];\n"
"    }\n"
"    for(int o=16;o>0;o>>=1)sum+=__shfl_down(sum,o);\n"
"    if(lane==0)out[(size_t)p*rows+row]=sum;\n"
"}\n"
/* A tile contains up to eight consecutive assignments for one expert. The
 * quantized row is fetched once; each token retains the original summation
 * order. This is opt-in until the full prefill path has parity. */
"__global__ void qwen4_gateup_silu_q2_tiled(float *dst,\n"
"        const unsigned char *gate,const unsigned char *up,const float *in,\n"
"        const int *task_p,const int *tile_e,const int *tile_start,\n"
"        const int *tile_n,const int *map,int rows,int cols,long long gs,long long us){\n"
"    int warp=threadIdx.x/32,lane=threadIdx.x&31,row=blockIdx.x*(blockDim.x/32)+warp;\n"
"    int tile=blockIdx.y;if(row>=rows)return;int e=tile_e[tile],slot=map[e];\n"
"    if(slot<0)return;int start=tile_start[tile],nt=tile_n[tile],rb=(cols/64)*18;\n"
"    const unsigned char *gr=gate+(long long)slot*gs+(size_t)row*rb;\n"
"    const unsigned char *ur=up+(long long)slot*us+(size_t)row*rb;\n"
"    float g[8]={0},u[8]={0};\n"
"    for(int qi=lane;qi<cols/4;qi+=32){int b=qi/16,z=qi&15;\n"
"        const unsigned char *gb=gr+b*18,*ub=ur+b*18;\n"
"        float gd=half_to_float(*(const half_raw *)gb),ud=half_to_float(*(const half_raw *)ub);\n"
"        int gq=gb[2+z],uq=ub[2+z];\n"
"        #pragma unroll\n"
"        for(int t=0;t<8;t++)if(t<nt){const float *xp=in+(size_t)task_p[start+t]*cols+qi*4;\n"
"            #pragma unroll\n"
"            for(int j=0;j<4;j++){float xv=xp[j];\n"
"                g[t]+=(float)(((gq>>(2*j))&3)-1)*gd*xv;\n"
"                u[t]+=(float)(((uq>>(2*j))&3)-1)*ud*xv;}\n"
"        }\n"
"    }\n"
"    #pragma unroll\n"
"    for(int t=0;t<8;t++)if(t<nt){float gv=g[t],uv=u[t];\n"
"        for(int o=16;o>0;o>>=1){gv+=__shfl_down(gv,o);uv+=__shfl_down(uv,o);}\n"
"        if(lane==0)dst[(size_t)task_p[start+t]*rows+row]=(gv/(1.0f+expf(-gv)))*uv;\n"
"    }\n"
"}\n"
"__global__ void qwen4_down_q2_tiled(float *out,const unsigned char *down,\n"
"        const float *act,const int *task_p,const int *tile_e,\n"
"        const int *tile_start,const int *tile_n,const int *map,\n"
"        int rows,int cols,long long ds){\n"
"    int warp=threadIdx.x/32,lane=threadIdx.x&31,row=blockIdx.x*(blockDim.x/32)+warp;\n"
"    int tile=blockIdx.y;if(row>=rows)return;int e=tile_e[tile],slot=map[e];\n"
"    if(slot<0)return;int start=tile_start[tile],nt=tile_n[tile],rb=(cols/64)*18;\n"
"    const unsigned char *rp=down+(long long)slot*ds+(size_t)row*rb;float sum[8]={0};\n"
"    for(int qi=lane;qi<cols/4;qi+=32){int b=qi/16,z=qi&15;\n"
"        const unsigned char *bp=rp+b*18;float d=half_to_float(*(const half_raw *)bp);\n"
"        int q=bp[2+z];\n"
"        #pragma unroll\n"
"        for(int t=0;t<8;t++)if(t<nt){const float *xp=act+(size_t)task_p[start+t]*cols+qi*4;\n"
"            #pragma unroll\n"
"            for(int j=0;j<4;j++)sum[t]+=(float)(((q>>(2*j))&3)-1)*d*xp[j];\n"
"        }\n"
"    }\n"
"    #pragma unroll\n"
"    for(int t=0;t<8;t++)if(t<nt){float v=sum[t];\n"
"        for(int o=16;o>0;o>>=1)v+=__shfl_down(v,o);\n"
"        if(lane==0)out[(size_t)task_p[start+t]*rows+row]=v;\n"
"    }\n"
"}\n"
