/* Preserve scalar fused Q8/F16/F32 SSM projection reduction order. */
"__global__ void ssm_matvec4_q8_batch_f32(float *qkv,float *z,float *alpha,float *beta,\n"
"        const unsigned char *wq,const unsigned char *wz,const float *wa,const float *wb,\n"
"        const float *x,int qrows,int zrows,int dt_rank,int qcols,int fcols,int aux_f16){\n"
"    qkv+=(size_t)blockIdx.y*qrows; z+=(size_t)blockIdx.y*zrows;\n"
"    alpha+=(size_t)blockIdx.y*dt_rank; beta+=(size_t)blockIdx.y*dt_rank; x+=(size_t)blockIdx.y*qcols;\n"
"    int row=blockIdx.x,tid=threadIdx.x;if(row>=qrows+zrows+2*dt_rank)return;\n"
"    float sum=0.0f;\n"
"    if(row<qrows+zrows){\n"
"        int r=row<qrows?row:row-qrows;const unsigned char *mat=row<qrows?wq:wz;\n"
"        const unsigned char *rp=mat+(size_t)r*(qcols/32)*36;\n"
"        for(int b=tid;b<qcols/32;b+=blockDim.x){const unsigned char *bp=rp+b*36;\n"
"            const signed char *q=(const signed char *)(bp+4);const float *xb=x+b*32;float s=0.0f;\n"
"            #pragma unroll\n"
"            for(int j=0;j<32;j++)s+=(float)q[j]*xb[j];sum+=s*half_to_float(*(const half_raw *)bp);}\n"
"    } else {\n"
"        int r=row-qrows-zrows;const unsigned char *mat=(const unsigned char *)(r<dt_rank?wa:wb);\n"
"        int rr=r<dt_rank?r:r-dt_rank;size_t stride=(size_t)fcols*(aux_f16?2:4);\n"
"        const float *rp=(const float *)(mat+(size_t)rr*stride);\n"
"        if(aux_f16){const half_raw *hp=(const half_raw *)(mat+(size_t)rr*stride);\n"
"            for(int j=tid;j<fcols;j+=blockDim.x)sum+=half_to_float(hp[j])*x[j];}\n"
"        else for(int j=tid;j<fcols;j+=blockDim.x)sum+=rp[j]*x[j];\n"
"    }\n"
"    for(int o=16;o>0;o>>=1)sum+=__shfl_down(sum,o);__shared__ float ws[8];\n"
"    int warp=tid/32,lane=tid&31;if(lane==0)ws[warp]=sum;__syncthreads();\n"
"    if(tid==0){float total=0.0f;for(int w=0;w<blockDim.x/32;w++)total+=ws[w];\n"
"        if(row<qrows)qkv[row]=total;else if(row<qrows+zrows)z[row-qrows]=total;\n"
"        else if(row-qrows-zrows<dt_rank)alpha[row-qrows-zrows]=total;\n"
"        else beta[row-qrows-zrows-dt_rank]=total;}\n"
"}\n"
