/* Native HC batch kernels retain the scalar per-output operations. */
"__global__ void qwen4_hc_down_silu_q8_batch(float *dst,const unsigned char *mat,\n"
"        const float *x,int n_rows,int n_cols,float scale){\n"
"    dst+=(size_t)blockIdx.y*n_rows; x+=(size_t)blockIdx.y*n_cols;\n"
"    int row_in_block=threadIdx.x/64,warp_in_row=(threadIdx.x&63)/32,lane=threadIdx.x&31;\n"
"    int row=blockIdx.x*4+row_in_block;\n"
"    if(row>=n_rows)return;int nb=n_cols/32,rb=nb*36;const unsigned char *rp=mat+(size_t)row*rb;float sum=0.0f;\n"
"    for(int b=(threadIdx.x&63);b<nb;b+=64){const unsigned char *bp=rp+b*36;const signed char *q=(const signed char *)(bp+4);\n"
"        const float *xb=x+b*32;float z=0.0f;\n"
"        #pragma unroll\n"
"        for(int j=0;j<32;j++)z+=(float)q[j]*xb[j];\n"
"        sum+=z*half_to_float(*(const half_raw *)bp);}\n"
"    for(int o=16;o>0;o>>=1)sum+=__shfl_down(sum,o);\n"
"    __shared__ float ws[8];\n"
"    if(lane==0)ws[row_in_block*2+warp_in_row]=sum;__syncthreads();\n"
"    if((threadIdx.x&63)==0){float v=(ws[row_in_block*2]+ws[row_in_block*2+1])*scale;\n"
"        dst[row]=v/(1.0f+expf(-v));}\n"
"}\n"
"__global__ void qwen4_hc_up_mix_q8_batch(float *mixed,float *gate,const float *low,const float *xn,\n"
"        const unsigned char *mat,int n_embd,int n_stream,int n_cols){\n"
"    mixed+=(size_t)blockIdx.y*n_embd; gate+=(size_t)blockIdx.y*n_embd*n_stream; low+=(size_t)blockIdx.y*n_cols; xn+=(size_t)blockIdx.y*n_embd*n_stream;\n"
"    int group=threadIdx.x/8,lane=threadIdx.x&7;int i=blockIdx.x*8+group/4,s=group&3;\n"
"    if(i>=n_embd||s>=n_stream)return;int row=s*n_embd+i,nb=n_cols/32,rb=nb*36;\n"
"    const unsigned char *rp=mat+(size_t)row*rb;const float *x=low;float sum=0.0f;\n"
"    for(int b=lane;b<nb;b+=8){const unsigned char *bp=rp+b*36;\n"
"        const signed char *q=(const signed char *)(bp+4);const float *xb=x+b*32;float z=0.0f;\n"
"        #pragma unroll\n"
"        for(int j=0;j<32;j++)z+=(float)q[j]*xb[j];\n"
"        sum+=z*half_to_float(*(const half_raw *)bp);}\n"
"    for(int o=4;o>0;o>>=1)sum+=__shfl_down(sum,o,8);\n"
"    if(lane==0)gate[row]=sum;__syncthreads();\n"
"    if(lane==0&&s==0){float v=0.0f;for(int q=0;q<4;q++){int j=q*n_embd+i;\n"
"        v+=xn[j]/(1.0f+expf(-gate[j]));}mixed[i]=v/(float)n_stream;}\n"
"}\n"
"__global__ void matvec_f32_mw_f32_batch(float *dst, const float *mat, const float *x,\n"
"                                   int n_rows, int n_cols) {\n"
"    dst+=(size_t)blockIdx.y*n_rows; x+=(size_t)blockIdx.y*n_cols;\n"
"    int lane = threadIdx.x & 31;\n"
"    int warp = threadIdx.x >> 5;\n"
"    int row = blockIdx.x * 8 + warp;\n"
"    if (row >= n_rows) return;\n"
"    const float *rp = mat + (size_t)row * n_cols;\n"
"    float sum = 0.0f;\n"
"    for (int j = lane; j < n_cols; j += 32) sum += rp[j] * x[j];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset);\n"
"    if (lane == 0) dst[row] = sum;\n"
"}\n"
"__global__ void matvec_f16_f32_batch(float *dst, const half_raw *mat, const float *x,\n"
"                                int n_rows, int n_cols) {\n"
"    dst+=(size_t)blockIdx.y*n_rows; x+=(size_t)blockIdx.y*n_cols;\n"
"    int row = blockIdx.x;\n"
"    if (row >= n_rows) return;\n"
"    int tid = threadIdx.x;\n"
"    int nthreads = blockDim.x;\n"
"\n"
"    const half_raw *row_ptr = mat + (size_t)row * n_cols;\n"
"    float sum = 0.0f;\n"
"    for (int j = tid; j < n_cols; j += nthreads) {\n"
"        sum += half_to_float(row_ptr[j]) * x[j];\n"
"    }\n"
"\n"
"    /* Warp shuffle reduction */\n"
"    for (int offset = 16; offset > 0; offset >>= 1) {\n"
"        sum += __shfl_down(sum, offset);\n"
"    }\n"
"\n"
"    /* First thread per warp writes to shared memory, then reduce warps */\n"
"    __shared__ float warp_sums[8]; /* up to 256 threads = 8 warps */\n"
"    int warp_id = tid / 32;\n"
"    int lane = tid % 32;\n"
"    if (lane == 0) warp_sums[warp_id] = sum;\n"
"    __syncthreads();\n"
"\n"
"    if (tid == 0) {\n"
"        float total = 0.0f;\n"
"        int n_warps = (nthreads + 31) / 32;\n"
"        for (int w = 0; w < n_warps; w++) total += warp_sums[w];\n"
"        dst[row] = total;\n"
"    }\n"
"}\n"
"\n"
