"""Anthropic Messages API translation regressions (CPU only)."""
import json
import unittest

import anthropic_api
from codex_server import chat_prompt
from qwen_chat import decode_raw, split_generation
from qwen_tools import parse_calls, tool_registry

TOOLS = [{"name": "Bash", "description": "Run a command.",
          "input_schema": {"type": "object",
                           "properties": {"command": {"type": "string"},
                                          "timeout": {"type": "number"}},
                           "required": ["command"]}},
         {"type": "web_search_20250305", "name": "web_search"}]


class MessagesTranslationTest(unittest.TestCase):
    def setUp(self):
        self.registry = tool_registry(anthropic_api.tool_definitions(TOOLS))

    def test_server_tools_are_not_exposed(self):
        self.assertEqual(list(self.registry), ["Bash"])

    def test_tool_turn_replays_exact_generated_bytes(self):
        req = {"system": [{"type": "text", "text": "You are an agent."},
                          {"type": "text", "text": "Be brief."}],
               "messages": [{"role": "user", "content": "list files"}]}
        first = chat_prompt(anthropic_api.request_messages(req), self.registry, True, "medium")
        generated = ("Use ls.\n</think>\n\n<tool_call>\n<function=Bash>\n<parameter=command>\n"
                     "ls  -la\n</parameter>\n</function>\n</tool_call>")
        reasoning, answer = split_generation(generated, True)
        text, calls = parse_calls(answer, self.registry)
        content = anthropic_api.response_content(reasoning, "<think>\n" + generated, text, calls)
        self.assertEqual(content[0]["type"], "thinking")
        self.assertEqual(decode_raw(content[0]["signature"]), "<think>\n" + generated)
        self.assertEqual(content[-1]["type"], "tool_use")
        self.assertEqual(content[-1]["input"], {"command": "ls  -la"})
        self.assertEqual(anthropic_api.stop_reason(calls, "stop"), "tool_use")
        follow = dict(req, messages=req["messages"] + [
            {"role": "assistant", "content": content},
            {"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": content[-1]["id"],
                 "content": [{"type": "text", "text": "a.c"}]},
                {"type": "text", "text": "<system-reminder>x</system-reminder>"}]}])
        second = chat_prompt(anthropic_api.request_messages(follow), self.registry, True, "medium")
        self.assertTrue(second.startswith(first + generated + "<|im_end|>\n"))
        self.assertIn("<|im_start|>user\n<tool_response>\na.c\n</tool_response><|im_end|>\n"
                      "<|im_start|>user\n<system-reminder>x</system-reminder><|im_end|>",
                      second)

    def test_turn_without_thinking_block_replays_from_server_memory(self):
        """Claude Code drops thinking blocks on a resumed session's first request."""
        from qwen_chat import RawTurnCache
        cache = RawTurnCache()
        generated = ("Look.\n</think>\n\n<tool_call>\n<function=Bash>\n<parameter=command>\n"
                     "ls  -la\n</parameter>\n</function>\n</tool_call>")
        reasoning, answer = split_generation(generated, True)
        text, calls = parse_calls(answer, self.registry)
        content = anthropic_api.response_content(reasoning, "<think>\n" + generated, text, calls)
        cache.remember("<think>\n" + generated, text, calls,
                       [b["id"] for b in content if b["type"] == "tool_use"])
        stripped = [b for b in content if b["type"] != "thinking"]
        messages = anthropic_api.request_messages({"messages": [
            {"role": "user", "content": "list"},
            {"role": "assistant", "content": stripped},
            {"role": "user", "content": [{"type": "tool_result",
                                          "tool_use_id": stripped[-1]["id"], "content": "x"}]}]})
        cache.resolve(messages)
        self.assertIn(generated + "<|im_end|>", chat_prompt(messages, self.registry, True))
        # Filled-in default arguments still replay the generated bytes ...
        filled = anthropic_api.request_messages({"messages": [
            {"role": "user", "content": "list"},
            {"role": "assistant", "content": [
                dict(stripped[-1], input={"command": "ls  -la", "timeout": 120000})]}]})
        cache.resolve(filled)
        self.assertEqual(filled[1]["raw"], "<think>\n" + generated)
        # ... but a different tool or changed text does not.
        renamed = anthropic_api.request_messages({"messages": [
            {"role": "user", "content": "list"},
            {"role": "assistant", "content": [dict(stripped[-1], name="Read")]}]})
        cache.resolve(renamed)
        self.assertNotIn("raw", renamed[1])

    def test_foreign_thinking_is_rendered_as_reasoning(self):
        messages = anthropic_api.request_messages({"messages": [
            {"role": "user", "content": "hi"},
            {"role": "assistant", "content": [
                {"type": "thinking", "thinking": "greet", "signature": "EqAB..."},
                {"type": "text", "text": "hello"}]},
            {"role": "user", "content": "bye"}]})
        self.assertIn("<think>\ngreet\n</think>\n\nhello<|im_end|>",
                      chat_prompt(messages))

    def test_thinking_budget_maps_to_effort(self):
        self.assertEqual(anthropic_api.thinking_request({}), (False, None))
        self.assertEqual(anthropic_api.thinking_request(
            {"thinking": {"type": "enabled", "budget_tokens": 2048}}), (True, "low"))
        self.assertEqual(anthropic_api.thinking_request(
            {"thinking": {"type": "enabled", "budget_tokens": 31999}}), (True, "xhigh"))

    def test_stream_event_order(self):
        content = anthropic_api.response_content("r", "<think>\nr</think>\n\nok", "ok", [])
        use = anthropic_api.usage(100, 90, 5)
        self.assertEqual(use["input_tokens"], 10)
        events = [e for e, _ in anthropic_api.stream_events(content, "end_turn", use)]
        self.assertEqual(events, ["content_block_start", "content_block_delta",
                                  "content_block_delta", "content_block_stop",
                                  "content_block_start", "content_block_delta",
                                  "content_block_stop", "message_delta", "message_stop"])
        payloads = [p for _, p in anthropic_api.stream_events(content, "end_turn", use)]
        self.assertEqual(payloads[2]["delta"]["type"], "signature_delta")
        json.dumps(payloads)


if __name__ == "__main__":
    unittest.main()
