/*
 * HIPRTC kernels for the DS4F dense FP8 path.
 *
 * The matvec and batched GEMM kernels share one host-side weight contract:
 * row-major FP8 E4M3FN with 128x128 E8M0 block scales. The BF16 GEMM sibling
 * retains the RDNA4 16x64 tile geometry while converting BF16 bits correctly.
 */
#ifndef HIP_DS4F_KERNELS_H
#define HIP_DS4F_KERNELS_H

static const char hip_ds4f_dense_kernels_src[] =
"typedef unsigned char u8;\n"
"typedef unsigned int u32;\n"
"\n"
"__device__ __forceinline__ float bits_to_f32(u32 bits) {\n"
"    return __int_as_float(bits);\n"
"}\n"
"\n"
"/* DeepSeek dense weights use float8_e4m3fn: exp=15 is finite except\n"
" * S.1111.111, which is the sole NaN code.  The host reference uses the\n"
" * same bit construction, so no device half conversion is involved. */\n"
"__device__ __forceinline__ float fp8_e4m3fn_to_f32(u8 v) {\n"
"    u32 sign = ((u32)v >> 7) & 1u;\n"
"    u32 exp = ((u32)v >> 3) & 15u;\n"
"    u32 mant = (u32)v & 7u;\n"
"    if (exp == 0u) {\n"
"        if (mant == 0u) return bits_to_f32(sign << 31);\n"
"        int sh = 0;\n"
"        while ((mant & 4u) == 0u) { mant <<= 1; ++sh; }\n"
"        mant &= 3u;\n"
"        return bits_to_f32((sign << 31) | ((u32)(120 - sh) << 23) | (mant << 20));\n"
"    }\n"
"    if (exp == 15u && mant == 7u)\n"
"        return bits_to_f32((sign << 31) | (255u << 23) | (1u << 22));\n"
"    return bits_to_f32((sign << 31) | ((exp + 120u) << 23) | (mant << 20));\n"
"}\n"
"\n"
"__device__ __forceinline__ float e8m0_to_f32(u8 v) {\n"
"    return bits_to_f32((u32)v << 23);\n"
"}\n"
"\n"
"/* w: [rows, cols] FP8 row-major\n"
" * s: [(rows+127)/128, (cols+127)/128] E8M0 row-major\n"
" * x: [cols] and y: [rows], both F32. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_matvec(\n"
"        const u8 *w, const u8 *s, const float *x, float *y,\n"
"        int rows, int cols, int scale_cols) {\n"
"    int row = (int)blockIdx.x;\n"
"    int tid = (int)threadIdx.x;\n"
"    if (row >= rows) return;\n"
"\n"
"    float sum = 0.0f;\n"
"    const u8 *wr = w + (size_t)row * (size_t)cols;\n"
"    const u8 *sr = s + (size_t)(row >> 7) * (size_t)scale_cols;\n"
"    for (int col = tid; col < cols; col += (int)blockDim.x) {\n"
"        float v = fp8_e4m3fn_to_f32(wr[col]);\n"
"        float scale = e8m0_to_f32(sr[col >> 7]);\n"
"        sum += (v * scale) * x[col];\n"
"    }\n"
"\n"
"    /* gfx12 is wave32. Reduce inside each wave, then combine the eight wave\n"
"     * totals. Using shuffle reduction avoids the eight full-block barriers of\n"
"     * the scalar shared-memory tree while remaining valid on wave64 devices\n"
"     * because width=32 explicitly partitions each wave into 32-lane groups. */\n"
"    __shared__ float partial[8];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if ((tid & 31) == 0) partial[tid >> 5] = sum;\n"
"    __syncthreads();\n"
"    if (tid < 32) {\n"
"        int waves = ((int)blockDim.x + 31) >> 5;\n"
"        sum = tid < waves ? partial[tid] : 0.0f;\n"
"        for (int offset = 16; offset > 0; offset >>= 1)\n"
"            sum += __shfl_down(sum, offset, 32);\n"
"        if (tid == 0) y[row] = sum;\n"
"    }\n"
"}\n"
"\n"
"/* Block-diagonal o-projection variant. Each output row selects the input\n"
" * group from the flattened activation buffer; the full wo_a weight bank is\n"
" * read once in one launch instead of eight host-synchronized matvecs. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_blockdiag(\n"
"        const u8 *w, const u8 *s, const float *x, float *y,\n"
"        int rows, int cols, int scale_cols, int gin, int glora, int goff) {\n"
"    int row = (int)blockIdx.x;\n"
"    int tid = (int)threadIdx.x;\n"
"    if (row >= rows) return;\n"
"    int group = (goff + row) / glora;\n"
"    const float *xg = x + (size_t)group * (size_t)gin;\n"
"    float sum = 0.0f;\n"
"    const u8 *wr = w + (size_t)row * (size_t)cols;\n"
"    const u8 *sr = s + (size_t)(row >> 7) * (size_t)scale_cols;\n"
"    for (int col = tid; col < cols; col += (int)blockDim.x) {\n"
"        float v = fp8_e4m3fn_to_f32(wr[col]);\n"
"        float scale = e8m0_to_f32(sr[col >> 7]);\n"
"        sum += (v * scale) * xg[col];\n"
"    }\n"
"    __shared__ float partial[8];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if ((tid & 31) == 0) partial[tid >> 5] = sum;\n"
"    __syncthreads();\n"
"    if (tid < 32) {\n"
"        int waves = ((int)blockDim.x + 31) >> 5;\n"
"        sum = tid < waves ? partial[tid] : 0.0f;\n"
"        for (int offset = 16; offset > 0; offset >>= 1)\n"
"            sum += __shfl_down(sum, offset, 32);\n"
"        if (tid == 0) y[row] = sum;\n"
"    }\n"
"}\n"
"/* Flat row-major BF16 matvec. Keep the argument list identical to the FP8\n"
" * kernel so the host can select the function without another launch shape.\n"
" * The scale pointer and scale_cols are unused. */\n"
"extern \"C\" __global__ void ds4f_dense_bf16_matvec(\n"
"        const unsigned short *w, const u8 *unused_s, const float *x, float *y,\n"
"        int rows, int cols, int unused_scale_cols) {\n"
"    (void)unused_s; (void)unused_scale_cols;\n"
"    int row = (int)blockIdx.x;\n"
"    int tid = (int)threadIdx.x;\n"
"    if (row >= rows) return;\n"
"    float sum = 0.0f;\n"
"    const unsigned short *wr = w + (size_t)row * (size_t)cols;\n"
"    for (int col = tid; col < cols; col += (int)blockDim.x)\n"
"        sum += bits_to_f32((u32)wr[col] << 16) * x[col];\n"
"    __shared__ float partial[8];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if ((tid & 31) == 0) partial[tid >> 5] = sum;\n"
"    __syncthreads();\n"
"    if (tid < 32) {\n"
"        int waves = ((int)blockDim.x + 31) >> 5;\n"
"        sum = tid < waves ? partial[tid] : 0.0f;\n"
"        for (int offset = 16; offset > 0; offset >>= 1)\n"
"            sum += __shfl_down(sum, offset, 32);\n"
"        if (tid == 0) y[row] = sum;\n"
"    }\n"
"}\n"
"/* Flat row-major FP16 matvec used by the exact FP8->FP16 resident path. */\n"
"extern \"C\" __global__ void ds4f_dense_f16_matvec(\n"
"        const unsigned short *w, const u8 *unused_s, const float *x, float *y,\n"
"        int rows, int cols, int unused_scale_cols) {\n"
"    (void)unused_s; (void)unused_scale_cols;\n"
"    int row = (int)blockIdx.x;\n"
"    int tid = (int)threadIdx.x;\n"
"    if (row >= rows) return;\n"
"    float sum = 0.0f;\n"
"    const unsigned short *wr = w + (size_t)row * (size_t)cols;\n"
"    for (int col = tid; col < cols; col += (int)blockDim.x)\n"
"        sum += half_to_float(wr[col]) * x[col];\n"
"    __shared__ float partial[8];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if ((tid & 31) == 0) partial[tid >> 5] = sum;\n"
"    __syncthreads();\n"
"    if (tid < 32) {\n"
"        int waves = ((int)blockDim.x + 31) >> 5;\n"
"        sum = tid < waves ? partial[tid] : 0.0f;\n"
"        for (int offset = 16; offset > 0; offset >>= 1)\n"
"            sum += __shfl_down(sum, offset, 32);\n"
"        if (tid == 0) y[row] = sum;\n"
"    }\n"
"}\n"
"/* FP8/E8M0 prefill GEMM uses the same 16x64 tile geometry as the shared\n"
" * RDNA4 gemm_tiled_f16_f32 kernel. X/Y are token-major F32; weights remain\n"
" * compact FP8 and are dequantized while filling LDS. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_gemm(\n"
"        float *Y, const u8 *W, const u8 *S, const float *X,\n"
"        int n_out, int n_in, int n_tok, int scale_cols) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.0f, acc1 = 0.0f, acc2 = 0.0f, acc3 = 0.0f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base + ty < n_tok && k + tx < n_in)\n"
"            ? X[(size_t)(tok_base + ty) * n_in + k + tx] : 0.0f;\n"
"        __syncthreads();\n"
"        { int wr = out_base + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? fp8_e4m3fn_to_f32(W[(size_t)wr * n_in + k + ty]) *\n"
"              e8m0_to_f32(S[(size_t)(wr >> 7) * scale_cols + ((k + ty) >> 7)])\n"
"            : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 16 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? fp8_e4m3fn_to_f32(W[(size_t)wr * n_in + k + ty]) *\n"
"              e8m0_to_f32(S[(size_t)(wr >> 7) * scale_cols + ((k + ty) >> 7)])\n"
"            : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 32 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? fp8_e4m3fn_to_f32(W[(size_t)wr * n_in + k + ty]) *\n"
"              e8m0_to_f32(S[(size_t)(wr >> 7) * scale_cols + ((k + ty) >> 7)])\n"
"            : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 48 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? fp8_e4m3fn_to_f32(W[(size_t)wr * n_in + k + ty]) *\n"
"              e8m0_to_f32(S[(size_t)(wr >> 7) * scale_cols + ((k + ty) >> 7)])\n"
"            : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base +    tx < n_out) Y[(size_t)row*n_out + out_base +    tx] = acc0;\n"
"        if (out_base + 16 + tx < n_out) Y[(size_t)row*n_out + out_base + 16 + tx] = acc1;\n"
"        if (out_base + 32 + tx < n_out) Y[(size_t)row*n_out + out_base + 32 + tx] = acc2;\n"
"        if (out_base + 48 + tx < n_out) Y[(size_t)row*n_out + out_base + 48 + tx] = acc3;\n"
"    }\n"
"}\n"
"/* BF16-weight sibling of the shared RDNA4 16x64 GEMM tile. The common\n"
" * gemm_tiled_f16_f32 kernel is deliberately not used here: half_raw is\n"
" * IEEE FP16, whereas DS4F stores BF16 bits and needs a <<16 conversion. */\n"
"extern \"C\" __global__ void ds4f_dense_bf16_gemm(\n"
"        float *Y, const unsigned short *W, const float *X,\n"
"        const float *bias, int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.0f, acc1 = 0.0f, acc2 = 0.0f, acc3 = 0.0f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base + ty < n_tok && k + tx < n_in)\n"
"            ? X[(size_t)(tok_base + ty) * n_in + k + tx] : 0.0f;\n"
"        __syncthreads();\n"
"        { int wr = out_base + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 16 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 32 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 48 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base +    tx < n_out) Y[(size_t)row*n_out + out_base +    tx] = acc0 + (bias ? bias[out_base +    tx] : 0.0f);\n"
"        if (out_base + 16 + tx < n_out) Y[(size_t)row*n_out + out_base + 16 + tx] = acc1 + (bias ? bias[out_base + 16 + tx] : 0.0f);\n"
"        if (out_base + 32 + tx < n_out) Y[(size_t)row*n_out + out_base + 32 + tx] = acc2 + (bias ? bias[out_base + 32 + tx] : 0.0f);\n"
"        if (out_base + 48 + tx < n_out) Y[(size_t)row*n_out + out_base + 48 + tx] = acc3 + (bias ? bias[out_base + 48 + tx] : 0.0f);\n"
"    }\n"
"}\n";

#endif /* HIP_DS4F_KERNELS_H */
