/*
 * HIPRTC kernels for the DS4F dense FP8 path.
 *
 * The matvec and batched GEMM kernels share one host-side weight contract:
 * row-major FP8 E4M3FN with 128x128 E8M0 block scales. The BF16 GEMM sibling
 * retains the RDNA4 16x64 tile geometry while converting BF16 bits correctly.
 */
#ifndef HIP_DS4F_KERNELS_H
#define HIP_DS4F_KERNELS_H

static const char hip_ds4f_dense_kernels_src[] =
"typedef unsigned char u8;\n"
"typedef unsigned short u16;\n"
"typedef unsigned int u32;\n"
"typedef _Float16 ds4f_f16x8 __attribute__((ext_vector_type(8)));\n"
"typedef float ds4f_float8 __attribute__((ext_vector_type(8)));\n"
"\n"
"__device__ __forceinline__ float bits_to_f32(u32 bits) {\n"
"    return __int_as_float(bits);\n"
"}\n"
"\n"
"/* DeepSeek dense weights use float8_e4m3fn: exp=15 is finite except\n"
" * S.1111.111, which is the sole NaN code.  The host reference uses the\n"
" * same bit construction, so no device half conversion is involved. */\n"
"__device__ __forceinline__ float fp8_e4m3fn_to_f32(u8 v) {\n"
"    u32 sign = ((u32)v >> 7) & 1u;\n"
"    u32 exp = ((u32)v >> 3) & 15u;\n"
"    u32 mant = (u32)v & 7u;\n"
"    if (exp == 0u) {\n"
"        if (mant == 0u) return bits_to_f32(sign << 31);\n"
"        int sh = 0;\n"
"        while ((mant & 4u) == 0u) { mant <<= 1; ++sh; }\n"
"        mant &= 3u;\n"
"        return bits_to_f32((sign << 31) | ((u32)(120 - sh) << 23) | (mant << 20));\n"
"    }\n"
"    if (exp == 15u && mant == 7u)\n"
"        return bits_to_f32((sign << 31) | (255u << 23) | (1u << 22));\n"
"    return bits_to_f32((sign << 31) | ((exp + 120u) << 23) | (mant << 20));\n"
"}\n"
"\n"
"__device__ __forceinline__ float e8m0_to_f32(u8 v) {\n"
"    return bits_to_f32((u32)v << 23);\n"
"}\n"
"\n"
"/* w: [rows, cols] FP8 row-major\n"
" * s: [(rows+127)/128, (cols+127)/128] E8M0 row-major\n"
" * x: [cols] and y: [rows], both F32. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_matvec(\n"
"        const u8 *w, const u8 *s, const float *x, float *y,\n"
"        int rows, int cols, int scale_cols) {\n"
"    /* One wave32 per row, blockDim.x/32 rows per block.  The previous shape\n"
"     * gave every row a whole 128-thread block, which left half the lanes idle\n"
"     * whenever cols/16 < blockDim.x (cols=1024 for wq_b) and paid a shared\n"
"     * memory tree plus __syncthreads for a reduction a single wave can do. */\n"
"    int tid = (int)threadIdx.x;\n"
"    int lane = tid & 31, wave = tid >> 5;\n"
"    int row = (int)blockIdx.x * ((int)blockDim.x >> 5) + wave;\n"
"    if (row >= rows) return;\n"
"\n"
"    float sum = 0.0f;\n"
"    const u8 *wr = w + (size_t)row * (size_t)cols;\n"
"    const u8 *sr = s + (size_t)(row >> 7) * (size_t)scale_cols;\n"
"    /* One byte per lane per step wastes ~3/4 of every memory request.  Take\n"
"     * 16 consecutive weights per lane instead.  A 16-aligned run never\n"
"     * straddles a 128-column E8M0 block, so the block scale factors out of\n"
"     * the run and is applied once. */\n"
"    int nvec = cols >> 4;\n"
"    for (int c = lane; c < nvec; c += 32) {\n"
"        int col = c << 4;\n"
"        uint4 wv = *(const uint4 *)(wr + col);\n"
"        const u8 *wb = (const u8 *)&wv;\n"
"        float acc = 0.0f;\n"
"        for (int j = 0; j < 16; j++)\n"
"            acc = fmaf(fp8_e4m3fn_to_f32(wb[j]), x[col + j], acc);\n"
"        sum += acc * e8m0_to_f32(sr[col >> 7]);\n"
"    }\n"
"    for (int col = (nvec << 4) + lane; col < cols; col += 32) {\n"
"        float v = fp8_e4m3fn_to_f32(wr[col]);\n"
"        float scale = e8m0_to_f32(sr[col >> 7]);\n"
"        sum += (v * scale) * x[col];\n"
"    }\n"
"\n"
"    /* gfx12 is wave32, and one row now lives entirely in one wave, so the\n"
"     * row total is a single shuffle reduction -- no shared memory, no\n"
"     * __syncthreads.  width=32 keeps this valid on wave64 devices. */\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if (lane == 0) y[row] = sum;\n"
"}\n"
"\n"
"/* Block-diagonal o-projection variant. Each output row selects the input\n"
" * group from the flattened activation buffer; the full wo_a weight bank is\n"
" * read once in one launch instead of eight host-synchronized matvecs. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_blockdiag(\n"
"        const u8 *w, const u8 *s, const float *x, float *y,\n"
"        int rows, int cols, int scale_cols, int gin, int glora, int goff) {\n"
"    int tid = (int)threadIdx.x;\n"
"    int lane = tid & 31, wave = tid >> 5;\n"
"    int row = (int)blockIdx.x * ((int)blockDim.x >> 5) + wave;\n"
"    if (row >= rows) return;\n"
"    int group = (goff + row) / glora;\n"
"    const float *xg = x + (size_t)group * (size_t)gin;\n"
"    float sum = 0.0f;\n"
"    const u8 *wr = w + (size_t)row * (size_t)cols;\n"
"    const u8 *sr = s + (size_t)(row >> 7) * (size_t)scale_cols;\n"
"    int nvec = cols >> 4;\n"
"    for (int c = lane; c < nvec; c += 32) {\n"
"        int col = c << 4;\n"
"        uint4 wv = *(const uint4 *)(wr + col);\n"
"        const u8 *wb = (const u8 *)&wv;\n"
"        float acc = 0.0f;\n"
"        for (int j = 0; j < 16; j++)\n"
"            acc = fmaf(fp8_e4m3fn_to_f32(wb[j]), xg[col + j], acc);\n"
"        sum += acc * e8m0_to_f32(sr[col >> 7]);\n"
"    }\n"
"    for (int col = (nvec << 4) + lane; col < cols; col += 32) {\n"
"        float v = fp8_e4m3fn_to_f32(wr[col]);\n"
"        float scale = e8m0_to_f32(sr[col >> 7]);\n"
"        sum += (v * scale) * xg[col];\n"
"    }\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if (lane == 0) y[row] = sum;\n"
"}\n"
"/* Flat row-major BF16 matvec. Keep the argument list identical to the FP8\n"
" * kernel so the host can select the function without another launch shape.\n"
" * The scale pointer and scale_cols are unused. */\n"
"extern \"C\" __global__ void ds4f_dense_bf16_matvec(\n"
"        const unsigned short *w, const u8 *unused_s, const float *x, float *y,\n"
"        int rows, int cols, int unused_scale_cols) {\n"
"    (void)unused_s; (void)unused_scale_cols;\n"
"    int tid = (int)threadIdx.x;\n"
"    int lane = tid & 31, wave = tid >> 5;\n"
"    int row = (int)blockIdx.x * ((int)blockDim.x >> 5) + wave;\n"
"    if (row >= rows) return;\n"
"    float sum = 0.0f;\n"
"    const unsigned short *wr = w + (size_t)row * (size_t)cols;\n"
"    for (int col = lane; col < cols; col += 32)\n"
"        sum += bits_to_f32((u32)wr[col] << 16) * x[col];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if (lane == 0) y[row] = sum;\n"
"}\n"
"/* Flat row-major FP16 matvec used by the exact FP8->FP16 resident path. */\n"
"extern \"C\" __global__ void ds4f_dense_f16_matvec(\n"
"        const unsigned short *w, const u8 *unused_s, const float *x, float *y,\n"
"        int rows, int cols, int unused_scale_cols) {\n"
"    (void)unused_s; (void)unused_scale_cols;\n"
"    int tid = (int)threadIdx.x;\n"
"    int lane = tid & 31, wave = tid >> 5;\n"
"    int row = (int)blockIdx.x * ((int)blockDim.x >> 5) + wave;\n"
"    if (row >= rows) return;\n"
"    float sum = 0.0f;\n"
"    const unsigned short *wr = w + (size_t)row * (size_t)cols;\n"
"    for (int col = lane; col < cols; col += 32)\n"
"        sum += half_to_float(wr[col]) * x[col];\n"
"    for (int offset = 16; offset > 0; offset >>= 1)\n"
"        sum += __shfl_down(sum, offset, 32);\n"
"    if (lane == 0) y[row] = sum;\n"
"}\n"
"/* FP8/E8M0 prefill GEMM uses the same 16x64 tile geometry as the shared\n"
" * RDNA4 gemm_tiled_f16_f32 kernel. X/Y are token-major F32; weights remain\n"
" * compact FP8 and are dequantized while filling LDS. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_gemm(\n"
"        float *Y, const u8 *W, const u8 *S, const float *X, const u32 *LUT,\n"
"        int n_out, int n_in, int n_tok, int scale_cols) {\n"
"    /* Stage all 64 weight columns of the tile in one pass.  The previous\n"
"     * form filled smB[16][16] four separate times and paid eight\n"
"     * __syncthreads per 16 columns of K; this pays two. */\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][64];\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.0f, acc1 = 0.0f, acc2 = 0.0f, acc3 = 0.0f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (row < n_tok && k + tx < n_in)\n"
"            ? X[(size_t)row * n_in + k + tx] : 0.0f;\n"
"        for (int q = 0; q < 4; q++) {\n"
"            int wr = out_base + q * 16 + tx;\n"
"            smB[ty][q * 16 + tx] = (wr < n_out && k + ty < n_in)\n"
"                ? bits_to_f32(LUT[W[(size_t)wr * n_in + k + ty]]) *\n"
"                  e8m0_to_f32(S[(size_t)(wr >> 7) * scale_cols + ((k + ty) >> 7)])\n"
"                : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) {\n"
"            float av = smA[ty][i];\n"
"            acc0 = fmaf(av, smB[i][tx], acc0);\n"
"            acc1 = fmaf(av, smB[i][16 + tx], acc1);\n"
"            acc2 = fmaf(av, smB[i][32 + tx], acc2);\n"
"            acc3 = fmaf(av, smB[i][48 + tx], acc3);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base +    tx < n_out) Y[(size_t)row*n_out + out_base +    tx] = acc0;\n"
"        if (out_base + 16 + tx < n_out) Y[(size_t)row*n_out + out_base + 16 + tx] = acc1;\n"
"        if (out_base + 32 + tx < n_out) Y[(size_t)row*n_out + out_base + 32 + tx] = acc2;\n"
"        if (out_base + 48 + tx < n_out) Y[(size_t)row*n_out + out_base + 48 + tx] = acc3;\n"
"    }\n"
"}\n"
"/* gfx12 native-WMMA prefill path. Compact FP8 weights are widened into a\n"
" * 32-column LDS panel with their exact E8M0 scale; activations are rounded\n"
" * to FP16. This avoids expanding the persistent 6.7 GB dense bank. */\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"extern \"C\" __global__ void ds4f_dense_fp8_wmma_f16_gemm(\n"
"        float *Y, const u8 *W, const u8 *S, const float *X,\n"
"        int n_out, int n_in, int n_tok, int scale_cols) {\n"
"    int tid=(int)threadIdx.x, wid=tid>>5, lane=tid&31;\n"
"    int wm=wid&1, wn=wid>>1, half=lane>>4, ix=lane&15;\n"
"    int m0=(int)blockIdx.y*128, n0=(int)blockIdx.x*128;\n"
"    __shared__ _Float16 A[128*32];\n"
"    __shared__ _Float16 B[128*32];\n"
"    ds4f_float8 z={0,0,0,0,0,0,0,0};\n"
"    ds4f_float8 c00=z,c01=z,c10=z,c11=z,c20=z,c21=z,c30=z,c31=z;\n"
"    for (int k=0;k<n_in;k+=32) {\n"
"        for (int it=0;it<16;it++) {\n"
"            int e=tid*16+it, er=e>>5, ek=e&31;\n"
"            int mr=m0+er, kp=k+ek;\n"
"            A[e]=(mr<n_tok&&kp<n_in)?(_Float16)X[(size_t)mr*n_in+kp]:(_Float16)0;\n"
"            int nr=n0+er;\n"
"            float wv=0.f;\n"
"            if (nr<n_out&&kp<n_in) {\n"
"                wv=fp8_e4m3fn_to_f32(W[(size_t)nr*n_in+kp]);\n"
"                wv*=e8m0_to_f32(S[(size_t)(nr>>7)*scale_cols+(kp>>7)]);\n"
"            }\n"
"            B[e]=(_Float16)wv;\n"
"        }\n"
"        __syncthreads();\n"
"        int ab=wm*64, bb=wn*32, ko=half*8;\n"
"        for (int kk=0;kk<32;kk+=16) {\n"
"            ds4f_f16x8 a0,a1,a2,a3,b0,b1;\n"
"            for(int i=0;i<8;i++){\n"
"                a0[i]=A[(ab+ix)*32+kk+ko+i]; a1[i]=A[(ab+16+ix)*32+kk+ko+i];\n"
"                a2[i]=A[(ab+32+ix)*32+kk+ko+i]; a3[i]=A[(ab+48+ix)*32+kk+ko+i];\n"
"                b0[i]=B[(bb+ix)*32+kk+ko+i]; b1[i]=B[(bb+16+ix)*32+kk+ko+i];\n"
"            }\n"
"            c00=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,c00);\n"
"            c01=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b1,c01);\n"
"            c10=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a1,b0,c10);\n"
"            c11=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a1,b1,c11);\n"
"            c20=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a2,b0,c20);\n"
"            c21=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a2,b1,c21);\n"
"            c30=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a3,b0,c30);\n"
"            c31=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a3,b1,c31);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    int mr0=m0+wm*64, nr0=n0+wn*32;\n"
"    ds4f_float8 *cv[8]={&c00,&c01,&c10,&c11,&c20,&c21,&c30,&c31};\n"
"    int mo[8]={0,0,16,16,32,32,48,48}; int no[8]={0,16,0,16,0,16,0,16};\n"
"    for(int t=0;t<8;t++){ int nr=nr0+no[t]+ix; if(nr>=n_out)continue;\n"
"        ds4f_float8 v=*cv[t]; for(int i=0;i<8;i++){ int mr=mr0+mo[t]+half*8+i;\n"
"            if(mr<n_tok)Y[(size_t)mr*n_out+nr]=v[i]; }}\n"
"}\n"
"#endif\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"extern \"C\" __global__ void ds4f_dense_fp8_wmma_f16_gemm64(float *Y,const u8 *W,const u8 *S,const float *X,int n_out,int n_in,int n_tok,int scale_cols){\n"
" int tid=(int)threadIdx.x,wid=tid>>5,lane=tid&31,wm=wid&3,wn=wid>>2,half=lane>>4,ix=lane&15;int m0=(int)blockIdx.y*64,n0=(int)blockIdx.x*64;__shared__ _Float16 A[64*32],B[64*32];ds4f_float8 z={0,0,0,0,0,0,0,0},c00=z,c01=z,c10=z,c11=z;\n"
" for(int k=0;k<n_in;k+=32){for(int it=0;it<8;it++){int e=tid*8+it,er=e>>5,ek=e&31,mr=m0+er,kp=k+ek;A[e]=(mr<n_tok&&kp<n_in)?(_Float16)X[(size_t)mr*n_in+kp]:(_Float16)0;int nr=n0+er;float v=0.f;if(nr<n_out&&kp<n_in){v=fp8_e4m3fn_to_f32(W[(size_t)nr*n_in+kp])*e8m0_to_f32(S[(size_t)(nr>>7)*scale_cols+(kp>>7)]);}B[e]=(_Float16)v;}__syncthreads();int ab=wm*16,bb=wn*32,ko=half*8;for(int kk=0;kk<32;kk+=16){ds4f_f16x8 a0,b0,b1;for(int i=0;i<8;i++){a0[i]=A[(ab+ix)*32+kk+ko+i];b0[i]=B[(bb+ix)*32+kk+ko+i];b1[i]=B[(bb+16+ix)*32+kk+ko+i];}c00=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,c00);c01=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b1,c01);}__syncthreads();}\n"
" int mr0=m0+wm*16,nr0=n0+wn*32;ds4f_float8 *cv[2]={&c00,&c01};for(int t=0;t<2;t++){int nr=nr0+t*16+ix;if(nr>=n_out)continue;ds4f_float8 v=*cv[t];for(int i=0;i<8;i++){int mr=mr0+half*8+i;if(mr<n_tok)Y[(size_t)mr*n_out+nr]=v[i];}}\n"
"}\n"
"#endif\n"
"/* Optional gfx12 BF16-weight WMMA path. Activations and BF16 weights are\n"
" * converted to FP16 for the native 16x16x16 instruction; it is opt-in\n"
" * because the conversion changes the reduction precision versus the exact\n"
" * scalar BF16 kernel. */\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"extern \"C\" __global__ void ds4f_dense_bf16_wmma_gemm(\n"
"        float *Y, const unsigned short *W, const float *X,\n"
"        int n_out, int n_in, int n_tok) {\n"
"    int tid=(int)threadIdx.x, wid=tid>>5, lane=tid&31;\n"
"    int wm=wid&1, wn=wid>>1, half=lane>>4, ix=lane&15;\n"
"    int m0=(int)blockIdx.y*128, n0=(int)blockIdx.x*128;\n"
"    __shared__ _Float16 A[128*32];\n"
"    __shared__ _Float16 B[128*32];\n"
"    ds4f_float8 z={0,0,0,0,0,0,0,0};\n"
"    ds4f_float8 c00=z,c01=z,c10=z,c11=z,c20=z,c21=z,c30=z,c31=z;\n"
"    for (int k=0;k<n_in;k+=32) {\n"
"        for (int it=0;it<16;it++) {\n"
"            int e=tid*16+it, er=e>>5, ek=e&31;\n"
"            int mr=m0+er, kp=k+ek;\n"
"            A[e]=(mr<n_tok&&kp<n_in)?(_Float16)X[(size_t)mr*n_in+kp]:(_Float16)0;\n"
"            int nr=n0+er;\n"
"            B[e]=(nr<n_out&&kp<n_in)?(_Float16)bits_to_f32((u32)W[(size_t)nr*n_in+kp]<<16):(_Float16)0;\n"
"        }\n"
"        __syncthreads();\n"
"        int ab=wm*64, bb=wn*32, ko=half*8;\n"
"        for(int kk=0;kk<32;kk+=16) {\n"
"            ds4f_f16x8 a0,a1,a2,a3,b0,b1;\n"
"            for(int i=0;i<8;i++){\n"
"                a0[i]=A[(ab+ix)*32+kk+ko+i]; a1[i]=A[(ab+16+ix)*32+kk+ko+i];\n"
"                a2[i]=A[(ab+32+ix)*32+kk+ko+i]; a3[i]=A[(ab+48+ix)*32+kk+ko+i];\n"
"                b0[i]=B[(bb+ix)*32+kk+ko+i]; b1[i]=B[(bb+16+ix)*32+kk+ko+i];\n"
"            }\n"
"            c00=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,c00);\n"
"            c01=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b1,c01);\n"
"            c10=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a1,b0,c10);\n"
"            c11=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a1,b1,c11);\n"
"            c20=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a2,b0,c20);\n"
"            c21=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a2,b1,c21);\n"
"            c30=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a3,b0,c30);\n"
"            c31=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a3,b1,c31);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    int mr0=m0+wm*64,nr0=n0+wn*32;\n"
"    ds4f_float8 *cv[8]={&c00,&c01,&c10,&c11,&c20,&c21,&c30,&c31};\n"
"    int mo[8]={0,0,16,16,32,32,48,48},no[8]={0,16,0,16,0,16,0,16};\n"
"    for(int t=0;t<8;t++){ int nr=nr0+no[t]+ix; if(nr>=n_out)continue; ds4f_float8 v=*cv[t];\n"
"        for(int i=0;i<8;i++){ int mr=mr0+mo[t]+half*8+i; if(mr<n_tok)Y[(size_t)mr*n_out+nr]=v[i]; }}\n"
"}\n"
"#endif\n"
"/* CPU-compatible FP8 prefill GEMM. The x86 reference accumulates eight\n"
" * lanes inside each 128-column E8M0 block, reduces that block, then applies\n"
" * the block scale. This keeps the normal 16x64 tile and shared staging,\n"
" * but retains those eight partial sums per output for BF16 KV stability. */\n"
"extern \"C\" __global__ void ds4f_dense_fp8_ordered_gemm(\n"
"        float *Y, const u8 *W, const u8 *S, const float *X, const u32 *LUT,\n"
"        int n_out, int n_in, int n_tok, int scale_cols) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][64];\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float a0[8] = {0,0,0,0,0,0,0,0}, a1[8] = {0,0,0,0,0,0,0,0};\n"
"    float a2[8] = {0,0,0,0,0,0,0,0}, a3[8] = {0,0,0,0,0,0,0,0};\n"
"    float c0[8] = {0,0,0,0,0,0,0,0}, c1[8] = {0,0,0,0,0,0,0,0};\n"
"    float c2[8] = {0,0,0,0,0,0,0,0}, c3[8] = {0,0,0,0,0,0,0,0};\n"
"    for (int kb = 0; kb < n_in; kb += 128) {\n"
"        for (int k = kb; k < kb + 128; k += 16) {\n"
"            smA[ty][tx] = (row < n_tok && k + tx < n_in)\n"
"                ? X[(size_t)row * n_in + k + tx] : 0.0f;\n"
"            for (int q = 0; q < 4; q++) {\n"
"                int wr = out_base + q * 16 + tx;\n"
"                smB[ty][q * 16 + tx] = (wr < n_out && k + ty < n_in)\n"
"                    ? bits_to_f32(LUT[W[(size_t)wr * n_in + k + ty]]) : 0.0f;\n"
"            }\n"
"            __syncthreads();\n"
"            /* k - kb always steps by 16 and 16 %% 8 == 0, so the AVX2 lane\n"
"             * index (k - kb + i) & 7 is identically i & 7 -- a compile-time\n"
"             * constant under this unroll.  Accumulation order per output is\n"
"             * unchanged from the four-staging form. */\n"
"            for (int i = 0; i < 16; i++) {\n"
"                int lane = i & 7;\n"
"                float av = smA[ty][i];\n"
"                a0[lane] = fmaf(av, smB[i][tx], a0[lane]);\n"
"                a1[lane] = fmaf(av, smB[i][16 + tx], a1[lane]);\n"
"                a2[lane] = fmaf(av, smB[i][32 + tx], a2[lane]);\n"
"                a3[lane] = fmaf(av, smB[i][48 + tx], a3[lane]);\n"
"            }\n"
"            __syncthreads();\n"
"        }\n"
"        float s = e8m0_to_f32(S[(size_t)(out_base >> 7) * scale_cols + (kb >> 7)]);\n"
"        for (int i = 0; i < 8; i++) {\n"
"            c0[i] = fmaf(a0[i], s, c0[i]); c1[i] = fmaf(a1[i], s, c1[i]);\n"
"            c2[i] = fmaf(a2[i], s, c2[i]); c3[i] = fmaf(a3[i], s, c3[i]);\n"
"            a0[i] = a1[i] = a2[i] = a3[i] = 0.0f;\n"
"        }\n"
"    }\n"
"    /* Match ds4f_avx2_hsum: [0+4,1+5,2+6,3+7], then\n"
"     * (0+4+2+6) + (1+5+3+7). */\n"
"    float r0 = ((c0[0] + c0[4]) + (c0[2] + c0[6])) + ((c0[1] + c0[5]) + (c0[3] + c0[7]));\n"
"    float r1 = ((c1[0] + c1[4]) + (c1[2] + c1[6])) + ((c1[1] + c1[5]) + (c1[3] + c1[7]));\n"
"    float r2 = ((c2[0] + c2[4]) + (c2[2] + c2[6])) + ((c2[1] + c2[5]) + (c2[3] + c2[7]));\n"
"    float r3 = ((c3[0] + c3[4]) + (c3[2] + c3[6])) + ((c3[1] + c3[5]) + (c3[3] + c3[7]));\n"
"    if (row < n_tok) {\n"
"        if (out_base +    tx < n_out) Y[(size_t)row*n_out + out_base +    tx] = r0;\n"
"        if (out_base + 16 + tx < n_out) Y[(size_t)row*n_out + out_base + 16 + tx] = r1;\n"
"        if (out_base + 32 + tx < n_out) Y[(size_t)row*n_out + out_base + 32 + tx] = r2;\n"
"        if (out_base + 48 + tx < n_out) Y[(size_t)row*n_out + out_base + 48 + tx] = r3;\n"
"    }\n"
"}\n"
"typedef struct { const u8 *w; const u8 *s; const float *x; float *y;\n"
"                 int n_out; int n_in; int n_tok; int x_stride; int y_stride; int x_off; int y_off; } ds4f_mxfp4_task;\n"
"__device__ __forceinline__ float ds4f_mxfp4_lane_dot(\n"
"        const u8 *wr, const u8 *sr, const float *x, int n_in) {\n"
"    int lane = (int)threadIdx.x & 31;\n"
"    const float lut[16] = { 0.f,1.f,2.f,3.f,4.f,6.f,8.f,12.f,\n"
"                            0.f,-1.f,-2.f,-3.f,-4.f,-6.f,-8.f,-12.f };\n"
"    float sum = 0.f;\n"
"    for (int b = 0; b < (n_in >> 5); ++b) {\n"
"        u8 packed = wr[(size_t)b * 16 + (lane >> 1)];\n"
"        int q = (lane & 1) ? (packed >> 4) : (packed & 15);\n"
"        u8 se = sr[b];\n"
"        float scale = bits_to_f32(se ? (u32)(se - 1) << 23 : 0u);\n"
"        sum = fmaf(lut[q] * scale, x[(size_t)b * 32 + lane], sum);\n"
"    }\n"
"    for (int d = 16; d; d >>= 1) sum += __shfl_down(sum, d, 32);\n"
"    return sum;\n"
"}\n"
"/* Decode-only wave-per-row kernel. Unlike the 16x64 prefill tile, all eight\n"
" * waves do useful work for M=1 and consume each MXFP4 block coalesced. */\n"
"extern \"C\" __global__ void ds4f_dense_mxfp4_matvec(\n"
"        float *y, const u8 *w, const u8 *s, const float *x,\n"
"        int n_out, int n_in) {\n"
"    int wave = (int)threadIdx.x >> 5, lane = (int)threadIdx.x & 31;\n"
"    int row = (int)blockIdx.x * 8 + wave;\n"
"    if (row >= n_out) return;\n"
"    float v = ds4f_mxfp4_lane_dot(w + (size_t)row * (n_in >> 1),\n"
"        s + (size_t)row * (n_in >> 5), x, n_in);\n"
"    if (lane == 0) y[row] = v;\n"
"}\n"
"extern \"C\" __global__ void ds4f_dense_mxfp4_grouped_matvec(\n"
"        const ds4f_mxfp4_task *tasks, int ntasks) {\n"
"    int ti = (int)blockIdx.y;\n"
"    if (ti >= ntasks) return;\n"
"    ds4f_mxfp4_task t = tasks[ti];\n"
"    int wave = (int)threadIdx.x >> 5, lane = (int)threadIdx.x & 31;\n"
"    int row = (int)blockIdx.x * 8 + wave;\n"
"    if (row >= t.n_out || t.n_tok != 1) return;\n"
"    float v = ds4f_mxfp4_lane_dot(t.w + (size_t)row * (t.n_in >> 1),\n"
"        t.s + (size_t)row * (t.n_in >> 5), t.x, t.n_in);\n"
"    if (lane == 0) t.y[row] = v;\n"
"}\n"
"/* Grouped raw-MXFP4 GEMM. Each z slice is one routed expert bucket; one\n"
" * dispatch replaces the serial per-expert launches while preserving the\n"
" * exact same tile arithmetic and output layout as ds4f_dense_mxfp4_gemm. */\n"
"extern \"C\" __global__ void ds4f_dense_mxfp4_grouped_gemm(\n"
"        const ds4f_mxfp4_task *tasks, int ntasks) {\n"
"    int ti = (int)blockIdx.z;\n"
"    if (ti >= ntasks) return;\n"
"    ds4f_mxfp4_task t = tasks[ti];\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][64];\n"
"    const float lut[16] = { 0.f,1.f,2.f,3.f,4.f,6.f,8.f,12.f,\n"
"                            0.f,-1.f,-2.f,-3.f,-4.f,-6.f,-8.f,-12.f };\n"
"    float a0=0.f,a1=0.f,a2=0.f,a3=0.f;\n"
"    for (int k0 = 0; k0 < t.n_in; k0 += 16) {\n"
"        smA[ty][tx] = (row < t.n_tok && k0 + tx < t.n_in)\n"
"            ? t.x[(size_t)row*t.n_in + k0 + tx] : 0.f;\n"
"        for (int q = 0; q < 4; ++q) {\n"
"            int col=q*16+tx, wr=out_base+col, k=k0+ty, b=k>>5, j=k&31;\n"
"            int off=j>>1;\n"
"            int nib=(j&1) ? (t.w[(size_t)wr*(t.n_in>>1)+(size_t)b*16+off]>>4)\n"
"                          : (t.w[(size_t)wr*(t.n_in>>1)+(size_t)b*16+off]&15);\n"
"            u8 se = t.s[(size_t)wr*(t.n_in>>5)+b];\n"
"            float sc = __int_as_float(se ? (u32)(se-1)<<23 : 0u);\n"
"            smB[ty][col] = (wr<t.n_out && k<t.n_in) ? lut[nib]*sc : 0.f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int i=0;i<16;i++) { float av=smA[ty][i];\n"
"            a0=fmaf(av,smB[i][tx],a0); a1=fmaf(av,smB[i][16+tx],a1);\n"
"            a2=fmaf(av,smB[i][32+tx],a2); a3=fmaf(av,smB[i][48+tx],a3); }\n"
"        __syncthreads();\n"
"    }\n"
"    if (row<t.n_tok) {\n"
"        if (out_base+tx<t.n_out) t.y[(size_t)row*t.n_out+out_base+tx]=a0;\n"
"        if (out_base+16+tx<t.n_out) t.y[(size_t)row*t.n_out+out_base+16+tx]=a1;\n"
"        if (out_base+32+tx<t.n_out) t.y[(size_t)row*t.n_out+out_base+32+tx]=a2;\n"
"        if (out_base+48+tx<t.n_out) t.y[(size_t)row*t.n_out+out_base+48+tx]=a3; }\n"
"}\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"extern \"C\" __global__ void ds4f_dense_mxfp4_grouped_wmma(const ds4f_mxfp4_task *tasks,int ntasks){\n"
" int ti=(int)blockIdx.z;if(ti>=ntasks)return;ds4f_mxfp4_task t=tasks[ti];int lane=(int)threadIdx.x&31;\n"
" int r0=(int)blockIdx.y*16,c0=(int)blockIdx.x*16;if(r0>=t.n_tok||c0>=t.n_out)return;\n"
" __shared__ _Float16 A[16*16],B[16*16];ds4f_float8 acc={0,0,0,0,0,0,0,0};\n"
" const float lut[16]={0.f,1.f,2.f,3.f,4.f,6.f,8.f,12.f,0.f,-1.f,-2.f,-3.f,-4.f,-6.f,-8.f,-12.f};\n"
" for(int kb=0;kb<t.n_in;kb+=16){\n"
"  for(int z=lane;z<256;z+=32){int r=z/16,k=z&15;int rr=r0+r,kk=kb+k;A[z]=(rr<t.n_tok&&kk<t.n_in)?(_Float16)t.x[(size_t)rr*t.n_in+kk]:(_Float16)0;\n"
"   int wr=c0+r;u8 q=0;float v=0.f;if(wr<t.n_out&&kk<t.n_in){q=t.w[(size_t)wr*(t.n_in>>1)+(kk>>1)];int n=(kk&1)?(q>>4):(q&15);u8 se=t.s[(size_t)wr*(t.n_in>>5)+(kk>>5)];v=lut[n]*bits_to_f32(se?(u32)(se-1)<<23:0u);}B[z]=(_Float16)v;}\n"
"  __syncthreads();int half=lane>>4,ix=lane&15;ds4f_f16x8 a0,b0;for(int i=0;i<8;i++){a0[i]=A[ix*16+half*8+i];b0[i]=B[(half*8+i)*16+ix];}\n"
"  acc=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,acc);__syncthreads();}\n"
" int half=lane>>4,ix=lane&15;for(int i=0;i<8;i++){int rr=r0+half*8+i,cc=c0+ix;if(rr<t.n_tok&&cc<t.n_out)t.y[(size_t)rr*t.n_out+cc]=acc[i];}\n"
"}\n"
"#endif\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"extern \"C\" __global__ void ds4f_dense_mxfp4_grouped_wmma32(const ds4f_mxfp4_task *tasks,int ntasks){\n"
" int ti=(int)blockIdx.z;if(ti>=ntasks)return;ds4f_mxfp4_task t=tasks[ti];int tid=(int)threadIdx.x,lane=tid&31,warp=tid>>5;int r0=(int)blockIdx.y*16,c0=(int)blockIdx.x*32;if(r0>=t.n_tok||c0>=t.n_out)return;\n"
" __shared__ _Float16 A[16*16],B[16*32];ds4f_float8 acc={0,0,0,0,0,0,0,0};\n"
" for(int kb=0;kb<t.n_in;kb+=16){for(int z=tid;z<256;z+=64){int r=z/16,k=z&15,rr=r0+r,kk=kb+k;A[z]=(rr<t.n_tok&&kk<t.n_in)?(_Float16)t.x[(size_t)rr*t.n_in+kk]:(_Float16)0;}for(int z=tid;z<512;z+=64){int r=z/32,c=z&31,rr=r0+r,cc=c0+c,kk=kb+r;float v=0.f;if(cc<t.n_out&&kk<t.n_in){u8 q=t.w[(size_t)cc*(t.n_in>>1)+(kk>>1)];int n=(kk&1)?q>>4:q&15;u8 se=t.s[(size_t)cc*(t.n_in>>5)+(kk>>5)];const float lut[16]={0.f,1.f,2.f,3.f,4.f,6.f,8.f,12.f,0.f,-1.f,-2.f,-3.f,-4.f,-6.f,-8.f,-12.f};v=lut[n]*bits_to_f32(se?(u32)(se-1)<<23:0u);}B[z]=(_Float16)v;}__syncthreads();int half=lane>>4,ix=lane&15;ds4f_f16x8 a0,b0;for(int i=0;i<8;i++){a0[i]=A[ix*16+half*8+i];b0[i]=B[(half*8+i)*32+warp*16+ix];}acc=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,acc);__syncthreads();}\n"
" int half=lane>>4,ix=lane&15;for(int i=0;i<8;i++){int rr=r0+half*8+i,cc=c0+warp*16+ix;if(rr<t.n_tok&&cc<t.n_out)t.y[(size_t)rr*t.n_out+cc]=acc[i];}\n"
"}\n"
"#endif\n"
"/* LUT-style MXFP4 widening GEMM for RDNA4. Decode raw e2m1 nibbles and\n"
" * E8M0 scales during tile staging; RDNA4 has no native MXFP4 instruction. */\n"
"extern \"C\" __global__ void ds4f_dense_mxfp4_gemm(\n"
"        float *Y, const u8 *W, const u8 *S, const float *X,\n"
"        int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][64];\n"
"    const float lut[16] = { 0.f,1.f,2.f,3.f,4.f,6.f,8.f,12.f,\n"
"                            0.f,-1.f,-2.f,-3.f,-4.f,-6.f,-8.f,-12.f };\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float a0=0.f,a1=0.f,a2=0.f,a3=0.f;\n"
"    for (int k0 = 0; k0 < n_in; k0 += 16) {\n"
"        smA[ty][tx] = (row < n_tok && k0 + tx < n_in)\n"
"            ? X[(size_t)row*n_in + k0 + tx] : 0.f;\n"
"        for (int q = 0; q < 4; q++) {\n"
"            int col=q*16+tx, wr=out_base+col, k=k0+ty, b=k>>5, j=k&31;\n"
"            int off=j>>1;\n"
"            int nib=(j&1) ? (W[(size_t)wr*(n_in>>1)+(size_t)b*16+off]>>4)\n"
"                          : (W[(size_t)wr*(n_in>>1)+(size_t)b*16+off]&15);\n"
"            u8 se = S[(size_t)wr*(n_in>>5)+b];\n"
"            float sc = __int_as_float(se ? (u32)(se-1)<<23 : 0u);\n"
"            smB[ty][col] = (wr<n_out && k<n_in) ? lut[nib]*sc : 0.f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int i=0;i<16;i++) { float av=smA[ty][i];\n"
"            a0=fmaf(av,smB[i][tx],a0); a1=fmaf(av,smB[i][16+tx],a1);\n"
"            a2=fmaf(av,smB[i][32+tx],a2); a3=fmaf(av,smB[i][48+tx],a3); }\n"
"        __syncthreads();\n"
"    }\n"
"    if (row<n_tok) {\n"
"        if (out_base+tx<n_out) Y[(size_t)row*n_out+out_base+tx]=a0;\n"
"        if (out_base+16+tx<n_out) Y[(size_t)row*n_out+out_base+16+tx]=a1;\n"
"        if (out_base+32+tx<n_out) Y[(size_t)row*n_out+out_base+32+tx]=a2;\n"
"        if (out_base+48+tx<n_out) Y[(size_t)row*n_out+out_base+48+tx]=a3; }\n"
"}\n"
"/* BF16-weight sibling of the shared RDNA4 16x64 GEMM tile. The common\n"
" * gemm_tiled_f16_f32 kernel is deliberately not used here: half_raw is\n"
" * IEEE FP16, whereas DS4F stores BF16 bits and needs a <<16 conversion. */\n"
"extern \"C\" __global__ void ds4f_dense_bf16_gemm(\n"
"        float *Y, const unsigned short *W, const float *X,\n"
"        const float *bias, int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = (int)threadIdx.x, ty = (int)threadIdx.y;\n"
"    int tok_base = (int)blockIdx.y * 16, out_base = (int)blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.0f, acc1 = 0.0f, acc2 = 0.0f, acc3 = 0.0f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base + ty < n_tok && k + tx < n_in)\n"
"            ? X[(size_t)(tok_base + ty) * n_in + k + tx] : 0.0f;\n"
"        __syncthreads();\n"
"        { int wr = out_base + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 16 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 32 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int wr = out_base + 48 + tx;\n"
"          smB[ty][tx] = (wr < n_out && k + ty < n_in)\n"
"            ? bits_to_f32((u32)W[(size_t)wr * n_in + k + ty] << 16) : 0.0f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base +    tx < n_out) Y[(size_t)row*n_out + out_base +    tx] = acc0 + (bias ? bias[out_base +    tx] : 0.0f);\n"
"        if (out_base + 16 + tx < n_out) Y[(size_t)row*n_out + out_base + 16 + tx] = acc1 + (bias ? bias[out_base + 16 + tx] : 0.0f);\n"
"        if (out_base + 32 + tx < n_out) Y[(size_t)row*n_out + out_base + 32 + tx] = acc2 + (bias ? bias[out_base + 32 + tx] : 0.0f);\n"
"        if (out_base + 48 + tx < n_out) Y[(size_t)row*n_out + out_base + 48 + tx] = acc3 + (bias ? bias[out_base + 48 + tx] : 0.0f);\n"
"    }\n"
"}\n"

/* FP8 widened from MXFP4: row-major E8M0 scales preserve the source
 * per-row MXFP4 scale semantics. */
"extern \"C\" __global__ void ds4f_dense_fp8_rowscale_gemm(\n"
"        float *Y, const u8 *W, const u8 *S, const float *X, const u32 *LUT,\n"
"        int n_out, int n_in, int n_tok, int scale_cols) {\n"
"    __shared__ float smA[16][16]; __shared__ float smB[16][16];\n"
"    int tx=(int)threadIdx.x, ty=(int)threadIdx.y;\n"
"    int tb=(int)blockIdx.y*16, ob=(int)blockIdx.x*64, row=tb+ty;\n"
"    float a0=0.f,a1=0.f,a2=0.f,a3=0.f;\n"
"    for (int k=0;k<n_in;k+=16) {\n"
"      smA[ty][tx]=(row<n_tok && k+tx<n_in)?X[(size_t)row*n_in+k+tx]:0.f;\n"
"      __syncthreads();\n"
"      for (int q=0;q<4;q++) { int wr=ob+q*16+tx, kk=k+ty;\n"
"        smB[ty][tx]=(wr<n_out && kk<n_in) ? bits_to_f32(LUT[W[(size_t)wr*n_in+kk]]) * e8m0_to_f32(S[(size_t)wr*scale_cols+(kk>>7)]) : 0.f;\n"
"        __syncthreads();\n"
"        for (int i=0;i<16;i++) { float av=smA[ty][i]; if(q==0) a0=fmaf(av,smB[i][tx],a0); else if(q==1) a1=fmaf(av,smB[i][tx],a1); else if(q==2) a2=fmaf(av,smB[i][tx],a2); else a3=fmaf(av,smB[i][tx],a3); }\n"
"        __syncthreads(); }\n"
"    }\n"
"    if(row<n_tok) { if(ob+tx<n_out) Y[(size_t)row*n_out+ob+tx]=a0; if(ob+16+tx<n_out) Y[(size_t)row*n_out+ob+16+tx]=a1; if(ob+32+tx<n_out) Y[(size_t)row*n_out+ob+32+tx]=a2; if(ob+48+tx<n_out) Y[(size_t)row*n_out+ob+48+tx]=a3; }\n"
"}\n"
"/* Exact-layout batched sliding-window attention. Eight warps share one\n"
" * token/group: each warp owns one query head and accumulates BF16 K/V. */\n"
"extern \"C\" __global__ void ds4f_dense_prefill_attn(\n"
"        float *Y, const u16 *KV, const float *Q, const float *sink,\n"
"        int M, int pos0, int n_heads, int head_dim, int kv_dim,\n"
"        int kv_slots, int window, float scale) {\n"
"    int group = (int)blockIdx.x, warp = (int)threadIdx.x >> 5;\n"
"    int lane = (int)threadIdx.x & 31;\n"
"    int groups = (n_heads + 7) >> 3;\n"
"    if (group >= M * groups || warp >= 8) return;\n"
"    int mm = group / groups, h = (group % groups) * 8 + warp;\n"
"    if (h >= n_heads) return;\n"
"    int pos = pos0 + mm, lo = pos - window + 1;\n"
"    if (lo < 0) lo = 0;\n"
"    int np = pos - lo + 1;\n"
"    __shared__ float score[8][128];\n"
"    const float *q = Q + ((size_t)mm * n_heads + h) * head_dim;\n"
"    for (int j = 0; j < np; ++j) {\n"
"        int slot = (lo + j) % kv_slots;\n"
"        const u16 *k = KV + (size_t)slot * kv_dim;\n"
"        float dot = 0.0f;\n"
"        for (int d = lane; d < kv_dim; d += 32)\n"
"            dot = fmaf(q[d], bits_to_f32((u32)k[d] << 16), dot);\n"
"        for (int off = 16; off > 0; off >>= 1) dot += __shfl_down(dot, off, 32);\n"
"        if (lane == 0) score[warp][j] = dot * scale;\n"
"    }\n"
"    __syncthreads();\n"
"    float mx = -1.0e30f;\n"
"    for (int j = 0; j < np; ++j) if (score[warp][j] > mx) mx = score[warp][j];\n"
"    float den = expf(sink[h] - mx);\n"
"    for (int j = 0; j < np; ++j) { score[warp][j] = expf(score[warp][j] - mx); den += score[warp][j]; }\n"
"    float inv = 1.0f / den;\n"
"    for (int d = lane; d < head_dim; d += 32) {\n"
"        float out = 0.0f;\n"
"        if (d < kv_dim) for (int j = 0; j < np; ++j) {\n"
"            int slot = (lo + j) % kv_slots;\n"
"            out = fmaf(score[warp][j] * inv, bits_to_f32((u32)KV[(size_t)slot * kv_dim + d] << 16), out);\n"
"        }\n"
"        Y[((size_t)mm * n_heads + h) * head_dim + d] = out;\n"
"    }\n"
"}\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"/* Opt-in gfx12 WMMA attention. One wave owns one head and a 16-token tile;\n"
" * QK^T uses native FP16-input/FP32-accumulator WMMA while V remains scalar in\n"
" * this first architecture slice. */\n"
"extern \"C\" __global__ void ds4f_dense_prefill_attn_wmma(\n"
"        float *Y, const u16 *KV, const float *Q, const float *sink,\n"
"        int M, int pos0, int n_heads, int head_dim, int kv_dim,\n"
"        int kv_slots, int window, float scale) {\n"
"    int lane=(int)threadIdx.x&31, warp=(int)threadIdx.x>>5, tile=(int)blockIdx.x, tiles=(M+15)/16;\n"
"    int m0=(tile%tiles)*16, h=tile/tiles; if(h>=n_heads)return;\n"
"    __shared__ _Float16 qsh[16*512], ksh[512*16];\n"
"    __shared__ float score[16*144]; __shared__ _Float16 wsh[16*16],vsh[16*16];\n"
"    for(int z=lane;z<16*512;z+=32){int r=z/512,d=z%512,m=m0+r;\n"
"        qsh[z]=(m<M&&d<head_dim)?(_Float16)Q[((size_t)m*n_heads+h)*head_dim+d]:(_Float16)0;}\n"
"    int pos_last=pos0+m0+15,kbase=pos0+m0-window+1;if(kbase<0)kbase=0;\n"
"    int kend=pos_last+1;if(kend>kv_slots)kend=kv_slots;int nk=kend-kbase;if(nk<1)nk=1;\n"
"    int kt=(nk+15)/16;if(kt>9)kt=9;\n"
"    for(int t=0;t<kt;t++){int kb=kbase+t*16;\n"
"        for(int z=lane;z<512*16;z+=32){int d=z/16,j=z%16,k=kb+j;\n"
"            ksh[z]=(d<kv_dim&&k<kv_slots)?(_Float16)bits_to_f32((u32)KV[(size_t)k*kv_dim+d]<<16):(_Float16)0;}\n"
"        __syncthreads();\n"
"        if(warp==0){int half=lane>>4,ix=lane&15; ds4f_float8 acc={0,0,0,0,0,0,0,0};\n"
"            for(int k=0;k<512;k+=16){ds4f_f16x8 a0,b0;\n"
"                for(int i=0;i<8;i++){a0[i]=qsh[ix*512+k+half*8+i];b0[i]=ksh[(k+half*8+i)*16+ix];}\n"
"                acc=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,acc);}\n"
"            for(int i=0;i<8;i++)score[(half*8+i)*144+t*16+ix]=acc[i];}\n"
"        __syncthreads();\n"
"    }\n"
"    if(warp==0&&lane<16){int r=lane,pos=pos0+m0+r;float mx=-1.e30f;\n"
"        for(int j=0;j<kt*16;j++){int kp=kbase+j;float v=(j<nk&&kp<=pos&&kp>=pos-window+1)?score[r*144+j]*scale:-1.e30f;if(v>mx)mx=v;}\n"
"        float den=expf(sink[h]-mx);for(int j=0;j<kt*16;j++){int kp=kbase+j;float v=(j<nk&&kp<=pos&&kp>=pos-window+1)?expf(score[r*144+j]*scale-mx):0.f;score[r*144+j]=v;den+=v;}\n"
"        float inv=1.f/den;for(int j=0;j<kt*16;j++)score[r*144+j]*=inv;}\n"
"    __syncthreads();\n"
"    int half=lane>>4,ix=lane&15;\n"
"    for(int ot=warp;ot<32;ot+=8){ds4f_float8 acc={0,0,0,0,0,0,0,0};\n"
"        for(int t=0;t<kt;t++){int kb=kbase+t*16;\n"
"            for(int z=(int)threadIdx.x;z<16*16;z+=256){int r=z/16,c=z&15;wsh[z]=(t*16+c<kt*16)?(_Float16)score[r*144+t*16+c]:(_Float16)0;}\n"
"            for(int z=(int)threadIdx.x;z<16*16;z+=256){int o=z/16,k=z&15;int kp=kb+k;u16 vv=0;if(kp<kv_slots&&ot*16+o<kv_dim)vv=KV[(size_t)kp*kv_dim+ot*16+o];vsh[z]=(_Float16)bits_to_f32((u32)vv<<16);}\n"
"            __syncthreads();\n"
"            ds4f_f16x8 a0,b0;for(int i=0;i<8;i++){a0[i]=wsh[ix*16+half*8+i];b0[i]=vsh[ix*16+half*8+i];}\n"
"            acc=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,acc);\n"
"            __syncthreads();}\n"
"        for(int i=0;i<8;i++){int r=half*8+i,m=m0+r,o=ot*16+ix;if(m<M&&o<head_dim)Y[((size_t)m*n_heads+h)*head_dim+o]=acc[i];}}\n"
"}\n"
"#endif\n"
"extern \"C\" __global__ void ds4f_apply_rope(float *x,const float *co,const float *si,int M,int width,int stride,int off,int pairs){\n"
" size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)M*pairs;if(i>=n)return;int r=i/pairs,p=i%pairs,j=off+2*p;\n"
" float a=x[(size_t)r*stride+j],b=x[(size_t)r*stride+j+1],c=co[(size_t)r*pairs+p],s=si[(size_t)r*pairs+p];\n"
" x[(size_t)r*stride+j]=a*c-b*s;x[(size_t)r*stride+j+1]=a*s+b*c;\n"
"}\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"extern \"C\" __global__ void ds4f_dense_fp8_grouped_wmma(const ds4f_mxfp4_task *tasks,int ntasks,int scale_cols){\n"
" int ti=(int)blockIdx.z;if(ti>=ntasks)return;ds4f_mxfp4_task t=tasks[ti];int lane=(int)threadIdx.x&31;int r0=(int)blockIdx.y*16,c0=(int)blockIdx.x*16;if(r0>=t.n_tok||c0>=t.n_out)return;\n"
" __shared__ _Float16 A[16*16],B[16*16];ds4f_float8 acc={0,0,0,0,0,0,0,0};\n"
" for(int kb=0;kb<t.n_in;kb+=16){for(int z=lane;z<256;z+=32){int r=z/16,k=z&15,rr=r0+r,kk=kb+k;A[z]=(rr<t.n_tok&&kk<t.n_in)?(_Float16)t.x[(size_t)rr*t.x_stride+t.x_off+kk]:(_Float16)0;int wr=c0+r;float v=0.f;if(wr<t.n_out&&kk<t.n_in)v=fp8_e4m3fn_to_f32(t.w[(size_t)wr*t.n_in+kk])*e8m0_to_f32(t.s[(size_t)(wr>>7)*scale_cols+(kk>>7)]);B[z]=(_Float16)v;}__syncthreads();int half=lane>>4,ix=lane&15;ds4f_f16x8 a0,b0;for(int i=0;i<8;i++){a0[i]=A[ix*16+half*8+i];b0[i]=B[(half*8+i)*16+ix];}acc=__builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a0,b0,acc);__syncthreads();}\n"
" int half=lane>>4,ix=lane&15;for(int i=0;i<8;i++){int rr=r0+half*8+i,cc=c0+ix;if(rr<t.n_tok&&cc<t.n_out)t.y[(size_t)rr*t.y_stride+t.y_off+cc]=acc[i];}\n"
"}\n"
"#endif\n"
"extern \"C\" __global__ void ds4f_gather_group(float *dst,const float *src,int M,int width,int stride,int off){\n"
"    size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)M*width;\n"
"    if(i<n){int r=(int)(i/width),c=(int)(i%width);dst[i]=src[(size_t)r*stride+off+c];}\n"
"}\n"
"extern \"C\" __global__ void ds4f_scatter_group(float *dst,const float *src,int M,int width,int stride,int off){\n"
"    size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)M*width;\n"
"    if(i<n){int r=(int)(i/width),c=(int)(i%width);dst[(size_t)r*stride+off+c]=src[i];}\n"
"}\n";

/* Fused shared-expert SwiGLU in its OWN HIPRTC module, always compiled precise
 * (no -ffast-math).  clang's -ffast-math replaces the SiLU's / with an
 * approximate reciprocal (even through __fdiv_rn / __frcp_rn / double div), so
 * this kernel must not ride in the fast-compiled dense module.  Compiling it
 * separately leaves the dense module's math mode (and thus its GEMM results)
 * untouched, so the fused shared FFN is bit-exact in any dense configuration.
 *
 * The expf is a port of glibc 2.39's __expf (e_expf.c + __exp2f_data).
 * Validated bit-identical to glibc expf() for every float in [-12,20] (the
 * whole SiLU gate range, where expf(-gv) is evaluated).  rint() replaces
 * glibc's (z + SHIFT) - SHIFT trick because -fassociative-math collapses that
 * pair; rint rounds ties to even the same way, and explicit fma() keeps the
 * degree-3 polynomial from being contracted or reassociated. */
static const char hip_ds4f_swiglu_kernels_src[] =
"typedef unsigned char u8;\n"
"typedef unsigned short u16;\n"
"typedef unsigned int u32;\n"
"typedef unsigned long long u64;\n"
"\n"
"static const u64 exp2f_tab[32] = {\n"
"0x3ff0000000000000ULL, 0x3fefd9b0d3158574ULL, 0x3fefb5586cf9890fULL, 0x3fef9301d0125b51ULL,\n"
"0x3fef72b83c7d517bULL, 0x3fef54873168b9aaULL, 0x3fef387a6e756238ULL, 0x3fef1e9df51fdee1ULL,\n"
"0x3fef06fe0a31b715ULL, 0x3feef1a7373aa9cbULL, 0x3feedea64c123422ULL, 0x3feece086061892dULL,\n"
"0x3feebfdad5362a27ULL, 0x3feeb42b569d4f82ULL, 0x3feeab07dd485429ULL, 0x3feea47eb03a5585ULL,\n"
"0x3feea09e667f3bcdULL, 0x3fee9f75e8ec5f74ULL, 0x3feea11473eb0187ULL, 0x3feea589994cce13ULL,\n"
"0x3feeace5422aa0dbULL, 0x3feeb737b0cdc5e5ULL, 0x3feec49182a3f090ULL, 0x3feed503b23e255dULL,\n"
"0x3feee89f995ad3adULL, 0x3feeff76f2fb5e47ULL, 0x3fef199bdd85529cULL, 0x3fef3720dcef9069ULL,\n"
"0x3fef5818dcfba487ULL, 0x3fef7c97337b9b5fULL, 0x3fefa4afa2a490daULL, 0x3fefd0765b6e4540ULL,\n"
"};\n"
"__device__ __forceinline__ float ds4f_expf_bitexact(float x) {\n"
"    u32 abstop = (__float_as_uint(x) >> 20) & 0x7ffu;\n"
"    if (abstop >= 0x42bu) {\n"
"        if (__float_as_uint(x) == 0xff800000u) return 0.0f;\n"
"        if (abstop >= 0x7f8u) return x + x;\n"
"        if (x > 0x1.62e42ep6f) return __uint_as_float(0x7f800000u);\n"
"        if (x < -0x1.9fe368ep6f) return 0.0f;\n"
"    }\n"
"    double xd = (double)x;\n"
"    double z = 0x1.71547652b82fep+5 * xd;\n"
"    double kr = rint(z);\n"
"    long long ki = (long long)kr;\n"
"    double r = z - kr;\n"
"    u64 t = exp2f_tab[(u64)ki % 32u];\n"
"    t += (u64)ki << 47;\n"
"    double s = __longlong_as_double((long long)t);\n"
"    double z2 = fma(0x1.c6af84b912394p-20, r, 0x1.ebfce50fac4f3p-13);\n"
"    double r2 = r * r;\n"
"    double y  = fma(0x1.62e42ff0c52d6p-6, r, 1.0);\n"
"    y = fma(z2, r2, y);\n"
"    y = y * s;\n"
"    return (float)y;\n"
"}\n"
"/* Fused shared-expert SwiGLU, device-side.  Mirrors ds4f_pf_swiglu_worker\n"
" * exactly: g = silu(min(g, lim)) * clamp(u, -lim, lim), silu(x) = x/(1+e^-x).\n"
" * Keeping it on the device lets w1/w3 -> swiglu -> w2 run without sending the\n"
" * two [M, inter] intermediates back to the host and the product forward. */\n"
"extern \"C\" __global__ void ds4f_swiglu_inplace(\n"
"        float *g, const float *u, int n, float lim) {\n"
"    int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);\n"
"    if (i >= n) return;\n"
"    float gv = g[i];\n"
"    gv = gv > lim ? lim : gv;\n"
"    float uv = u[i];\n"
"    uv = uv < -lim ? -lim : (uv > lim ? lim : uv);\n"
"    float e = ds4f_expf_bitexact(-gv);\n"
"    float d = 1.0f + e;\n"
"    g[i] = (gv / d) * uv;\n"
"}\n";

#endif /* HIP_DS4F_KERNELS_H */
