/*
 * verify_preprocess_image — self-driven preprocessing pipeline diff.
 *
 * Loads a clean reference generated by ref/sam3d-body/gen_preprocess_ref.py:
 *   raw_image.npy            (H, W, 3) u8
 *   bbox_xyxy.npy            (4,)      f32
 *   bbox_center_expect.npy   (2,)      f32
 *   bbox_scale_expect.npy    (2,)      f32
 *   warp_mat_expect.npy      (2, 3)    f32
 *   preprocess_expect.npy    (3, H, W) f32
 *
 * Checks in sequence:
 *   1. GetBBoxCenterScale + 2× fix_aspect_ratio → bbox_center, bbox_scale
 *   2. get_warp_matrix                           → warp_mat
 *   3. cv2.warpAffine + ImageNet norm + HWC→CHW  → preprocess
 *
 * Usage:
 *   verify_preprocess_image --refdir /tmp/sam3d_body_ref_pp [--threshold F]
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define SAM3D_BODY_DECODER_IMPLEMENTATION
#include "sam3d_body_decoder.h"
#include "npy_io.h"

static int diff_pair(const char *label, const float *a, const float *b,
                     size_t n, float thresh)
{
    double sum = 0.0; float mx = 0.0f; size_t mxi = 0;
    for (size_t i = 0; i < n; i++) {
        float d = fabsf(a[i] - b[i]);
        if (d > mx) { mx = d; mxi = i; }
        sum += d;
    }
    double mean = sum / (double)n;
    int fail = (mx >= thresh);
    fprintf(stderr, "[verify_preprocess_image] %-32s max_abs=%.4e (i=%zu) "
                    "mean_abs=%.4e (max=%.1e) %s\n",
            label, mx, mxi, mean, thresh, fail ? "FAIL" : "OK");
    return fail ? 1 : 0;
}

int main(int argc, char **argv)
{
    const char *refdir = NULL;
    /* cv2.warpAffine uses fixed-point INTER_TAB_SIZE=32 subpixel quantization
     * which can differ from us by up to ~a couple of uint8 units on rare pixels
     * (≤ ~3/255/min_std ≈ 0.06 after normalize). That's below bf16 precision,
     * so we set a generous threshold here. */
    float threshold = 1e-1f;
    for (int i = 1; i < argc; i++) {
        if      (!strcmp(argv[i], "--refdir") && i+1 < argc) refdir = argv[++i];
        else if (!strcmp(argv[i], "--threshold") && i+1 < argc) threshold = strtof(argv[++i], NULL);
        else { fprintf(stderr, "unknown arg: %s\n", argv[i]); return 2; }
    }
    if (!refdir) {
        fprintf(stderr, "Usage: %s --refdir <dir> [--threshold F]\n", argv[0]);
        return 2;
    }

    char path[1024];
    int nd, dims[8], is_f32;

    snprintf(path, sizeof(path), "%s/raw_image.npy", refdir);
    uint8_t *img = (uint8_t *)npy_load(path, &nd, dims, &is_f32);
    if (!img || is_f32 || nd != 3 || dims[2] != 3) {
        fprintf(stderr, "bad %s\n", path); free(img); return 3;
    }
    const int H_in = dims[0], W_in = dims[1];

    snprintf(path, sizeof(path), "%s/bbox_xyxy.npy", refdir);
    float *bbox = (float *)npy_load(path, &nd, dims, &is_f32);
    if (!bbox || !is_f32) { fprintf(stderr, "bad %s\n", path); free(img); free(bbox); return 3; }

    snprintf(path, sizeof(path), "%s/bbox_center_expect.npy", refdir);
    float *c_ref = (float *)npy_load(path, &nd, dims, &is_f32);
    snprintf(path, sizeof(path), "%s/bbox_scale_expect.npy", refdir);
    float *s_ref = (float *)npy_load(path, &nd, dims, &is_f32);
    snprintf(path, sizeof(path), "%s/warp_mat_expect.npy", refdir);
    float *w_ref = (float *)npy_load(path, &nd, dims, &is_f32);
    snprintf(path, sizeof(path), "%s/preprocess_expect.npy", refdir);
    float *p_ref = (float *)npy_load(path, &nd, dims, &is_f32);
    if (!c_ref || !s_ref || !w_ref || !p_ref) {
        fprintf(stderr, "missing expect files\n");
        free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref);
        return 3;
    }
    const int C_out = dims[0], H_out = dims[1], W_out = dims[2];

    fprintf(stderr, "[verify_preprocess_image] in=%dx%d out=%dx%dx%d "
                    "bbox=[%.1f %.1f %.1f %.1f]\n",
            W_in, H_in, C_out, H_out, W_out,
            bbox[0], bbox[1], bbox[2], bbox[3]);

    int rc_total = 0;

    /* --- bbox_center + bbox_scale + warp --- */
    float center_ours[2], scale_ours[2], warp_ours[6];
    sam3d_body_compute_bbox_affine(bbox,
                                   /*padding=*/1.25f,
                                   /*aspect_ratio_pre=*/0.75f,
                                   W_out, H_out,
                                   center_ours, scale_ours, warp_ours);
    rc_total |= diff_pair("bbox_center (2,)", center_ours, c_ref, 2, 1e-4f);
    rc_total |= diff_pair("bbox_scale (2,)",  scale_ours,  s_ref, 2, 1e-3f);
    rc_total |= diff_pair("warp_mat (2,3)",   warp_ours,   w_ref, 6, 1e-3f);

    /* --- preprocess (diff vs cv2 bilinear + imagenet norm) --- */
    float *ours = (float *)malloc((size_t)3 * H_out * W_out * sizeof(float));
    int rc = sam3d_body_preprocess_image(img, W_in, H_in, w_ref,
                                         W_out, H_out, ours);
    if (rc != SAM3D_BODY_DECODER_E_OK) {
        fprintf(stderr, "preprocess rc=%d\n", rc);
        free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref); free(ours);
        return 4;
    }
    rc_total |= diff_pair("preprocess (3,H,W) f32",
                          ours, p_ref, (size_t)3 * H_out * W_out, threshold);

    free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref); free(ours);
    return rc_total;
}
