/*
 * verify_preprocess_image — self-driven preprocessing pipeline diff.
 *
 * Loads a clean reference generated by ref/sam3d-body/gen_preprocess_ref.py:
 *   raw_image.npy            (H, W, 3) u8
 *   bbox_xyxy.npy            (4,)      f32
 *   bbox_center_expect.npy   (2,)      f32
 *   bbox_scale_expect.npy    (2,)      f32
 *   warp_mat_expect.npy      (2, 3)    f32
 *   preprocess_expect.npy    (3, H, W) f32
 *
 * It also accepts the full pipeline dumps from gen_image_ref.py:
 *   input_image.npy
 *   decoder_batch__{bbox_center,bbox_scale,affine_trans}.npy
 *   dinov3_input.npy
 *
 * Checks in sequence:
 *   1. GetBBoxCenterScale + 2× fix_aspect_ratio → bbox_center, bbox_scale
 *   2. get_warp_matrix                           → warp_mat
 *   3. cv2.warpAffine + ImageNet norm + HWC→CHW  → preprocess
 *
 * Usage:
 *   verify_preprocess_image --refdir /tmp/sam3d_body_ref_pp [--threshold F]
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define SAM3D_BODY_DECODER_IMPLEMENTATION
#include "sam3d_body_decoder.h"
#include "npy_io.h"

static void *load_npy_try(const char *refdir, const char *name,
                          int *nd, int dims[8], int *is_f32)
{
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s.npy", refdir, name);
    return npy_load(path, nd, dims, is_f32);
}

static int diff_pair(const char *label, const float *a, const float *b,
                     size_t n, float thresh)
{
    double sum = 0.0; float mx = 0.0f; size_t mxi = 0;
    for (size_t i = 0; i < n; i++) {
        float d = fabsf(a[i] - b[i]);
        if (d > mx) { mx = d; mxi = i; }
        sum += d;
    }
    double mean = sum / (double)n;
    int fail = (mx >= thresh);
    fprintf(stderr, "[verify_preprocess_image] %-32s max_abs=%.4e (i=%zu) "
                    "mean_abs=%.4e (max=%.1e) %s\n",
            label, mx, mxi, mean, thresh, fail ? "FAIL" : "OK");
    return fail ? 1 : 0;
}

int main(int argc, char **argv)
{
    const char *refdir = NULL;
    /* cv2.warpAffine uses fixed-point INTER_TAB_SIZE=32 subpixel quantization
     * which can differ from us by up to ~a couple of uint8 units on rare pixels
     * (≤ ~3/255/min_std ≈ 0.06 after normalize). That's below bf16 precision,
     * so we set a generous threshold here. */
    float threshold = 1e-1f;
    for (int i = 1; i < argc; i++) {
        if      (!strcmp(argv[i], "--refdir") && i+1 < argc) refdir = argv[++i];
        else if (!strcmp(argv[i], "--threshold") && i+1 < argc) threshold = strtof(argv[++i], NULL);
        else { fprintf(stderr, "unknown arg: %s\n", argv[i]); return 2; }
    }
    if (!refdir) {
        fprintf(stderr, "Usage: %s --refdir <dir> [--threshold F]\n", argv[0]);
        return 2;
    }

    int nd, dims[8], is_f32;

    uint8_t *img = (uint8_t *)load_npy_try(refdir, "raw_image", &nd, dims, &is_f32);
    if (!img)
        img = (uint8_t *)load_npy_try(refdir, "input_image", &nd, dims, &is_f32);
    if (!img || is_f32 || nd != 3 || dims[2] != 3) {
        fprintf(stderr, "bad/missing raw_image.npy or input_image.npy\n");
        free(img); return 3;
    }
    const int H_in = dims[0], W_in = dims[1];

    float *bbox = (float *)load_npy_try(refdir, "bbox_xyxy", &nd, dims, &is_f32);
    const int has_bbox = (bbox && is_f32);

    float *c_ref = (float *)load_npy_try(refdir, "bbox_center_expect",
                                         &nd, dims, &is_f32);
    if (!c_ref)
        c_ref = (float *)load_npy_try(refdir, "decoder_batch__bbox_center",
                                      &nd, dims, &is_f32);
    float *s_ref = (float *)load_npy_try(refdir, "bbox_scale_expect",
                                         &nd, dims, &is_f32);
    if (!s_ref)
        s_ref = (float *)load_npy_try(refdir, "decoder_batch__bbox_scale",
                                      &nd, dims, &is_f32);
    float *w_ref = (float *)load_npy_try(refdir, "warp_mat_expect",
                                         &nd, dims, &is_f32);
    if (!w_ref)
        w_ref = (float *)load_npy_try(refdir, "decoder_batch__affine_trans",
                                      &nd, dims, &is_f32);
    int p_ref_is_dinov3 = 0;
    float *p_ref = (float *)load_npy_try(refdir, "preprocess_expect",
                                         &nd, dims, &is_f32);
    if (!p_ref) {
        p_ref = (float *)load_npy_try(refdir, "dinov3_input",
                                      &nd, dims, &is_f32);
        p_ref_is_dinov3 = (p_ref != NULL);
    }
    if (!c_ref || !s_ref || !w_ref || !p_ref || !is_f32) {
        fprintf(stderr, "missing/non-f32 expect files\n");
        free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref);
        return 3;
    }
    int C_out = 0, H_out = 0, W_out = 0;
    if (nd == 3) {
        C_out = dims[0]; H_out = dims[1]; W_out = dims[2];
    } else if (nd == 4 && dims[0] == 1) {
        C_out = dims[1]; H_out = dims[2]; W_out = dims[3];
    }
    if (C_out != 3 || H_out <= 0 || W_out <= 0) {
        fprintf(stderr, "bad preprocess ref shape rank=%d [%d,%d,%d,%d]\n",
                nd, dims[0], dims[1], dims[2], dims[3]);
        free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref);
        return 3;
    }

    fprintf(stderr, "[verify_preprocess_image] in=%dx%d out=%dx%dx%d "
                    "bbox=%s\n",
            W_in, H_in, C_out, H_out, W_out,
            has_bbox ? "provided" : "not provided");

    int rc_total = 0;

    /* --- bbox_center + bbox_scale + warp --- */
    float center_ours[2], scale_ours[2], warp_ours[6];
    if (has_bbox) {
        float aspect_ratio_pre = 0.75f;
        if (p_ref_is_dinov3 && H_out != W_out)
            aspect_ratio_pre = (float)W_out / (float)H_out;
        sam3d_body_compute_bbox_affine(bbox,
                                       /*padding=*/1.25f,
                                       aspect_ratio_pre,
                                       W_out, H_out,
                                       center_ours, scale_ours, warp_ours);
        rc_total |= diff_pair("bbox_center (2,)", center_ours, c_ref, 2, 1e-4f);
        rc_total |= diff_pair("bbox_scale (2,)",  scale_ours,  s_ref, 2, 1e-3f);
        rc_total |= diff_pair("warp_mat (2,3)",   warp_ours,   w_ref, 6, 1e-3f);
    }

    /* --- preprocess (diff vs cv2 bilinear + imagenet norm) --- */
    float *ours = (float *)malloc((size_t)3 * H_out * W_out * sizeof(float));
    int rc = sam3d_body_preprocess_image(img, W_in, H_in, w_ref,
                                         W_out, H_out, ours);
    if (rc != SAM3D_BODY_DECODER_E_OK) {
        fprintf(stderr, "preprocess rc=%d\n", rc);
        free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref); free(ours);
        return 4;
    }
    rc_total |= diff_pair("preprocess (3,H,W) f32",
                          ours, p_ref, (size_t)3 * H_out * W_out, threshold);

    free(img); free(bbox); free(c_ref); free(s_ref); free(w_ref); free(p_ref); free(ours);
    return rc_total;
}
