#!/usr/bin/env python3
"""From-scratch generator for the DTVB+SIA3 mm0 BF16 kernel.

Three modes (--mode flag):

    baseline     pass through `mm0_bf16_asm_barriersig_early.s` verbatim,
                 wrapped in a generator-attribution header. Validates the
                 build pipeline end-to-end. Should match baseline 142 TFLOP/s.

    drop-b-lds   structurally remove B's LDS-staging instructions (B prologue
                 prefetch + B in-loop ds_loads + B in-loop ds_stores), but
                 do NOT replace them with direct-VGPR loads. Resulting
                 kernel will fail correctness — useful only as an
                 intermediate sanity check that the surgical removal
                 lines up with what we annotated.

    dtvb         (NOT IMPLEMENTED) full DTVB substitution. Requires the
                 N-row offset address arithmetic for our WG=128x1x1 layout,
                 which is structurally different from hipBLASLt's WG=32x4x1.
                 See module docstring of patch_dtva.py for the analysis of
                 why single-set DTV regresses in this layout, and
                 rdna4_gemm_optimization_log.md "Final conclusion" for
                 why closing the gap requires the WG-dim fork.

Status: scaffolding + Phase 1 ground truth + baseline replicator complete.

----------------------------------------------------------------------
Path to ≥160 TFLOP/s (carried forward from the original plan)
----------------------------------------------------------------------

The 17% perf gap to hipBLASLt's algo-73624 (166 TFLOP/s) requires:

  (1) DTVB: B-direct-to-VGPR with two register banks (B_DIR_A v[182:213],
      B_DIR_B v[214:245]) for software-pipelined 2× outer-K unrolled body
      (single-set DTVB regresses to ~115; verified via patch_dtva.py).

  (2) WG=32x4x1 decomposition: hipBLASLt distributes the M/N tile across
      4 waves with 32 lanes each, instead of 1 wave×32 lanes×4 work-items.
      This changes every per-thread offset compute. Verified 2026-04-30
      via kernel name decode (algo 73840: WG32_4_1). NOT patchable onto
      our WG=128x1x1 baseline.

(1) and (2) are coupled — (1) alone would still leave ~3-5 TFLOP/s on
the table; (2) alone is structurally orthogonal. The realistic plan is
a multi-day greenfield rewrite. This generator's `dtvb` mode is the
landing pad; until then, `baseline` mode validates the infrastructure.

----------------------------------------------------------------------
Files in this generator's foundation
----------------------------------------------------------------------

  dtvb_emit/regalloc.py   - VGPR/SGPR window definitions, non-overlap asserts
  dtvb_emit/isa.py        - gfx1201 mnemonic builders, waitcnt encoder
  dtvb_emit/scheduler.py  - VMEM/LDS issue tracker with auto-waitcnt
  dtvb_emit/__init__.py
  hipblaslt_mm0_alik_bljk_dtvb_groundtruth.s.annot   - Phase 1 ground truth
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

from dtvb_emit import regalloc

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_BASELINE = REPO_ROOT / "generated" / "mm0_bf16_asm_barriersig_early.s"


def emit_baseline(baseline_path: Path) -> str:
    """Mode `baseline`: read baseline .s and re-emit verbatim with a header.

    Validates the generator → assemble → bench pipeline end-to-end.
    Output should be functionally identical to the input.
    """
    text = baseline_path.read_text()
    header = (
        "; Auto-generated by gen_mm0_dtvb.py --mode baseline.\n"
        f"; Source: {baseline_path.name}\n"
        f"; VGPR window check: {regalloc.total_vgpr_count()} total, no overlap.\n"
        ";\n"
        "; This is a verbatim pass-through of the 142 TFLOP/s baseline.\n"
        "; To switch to DTVB, re-run with --mode dtvb (not yet implemented).\n"
    )
    return header + text


def emit_drop_b_lds(baseline_path: Path) -> str:
    """Mode `drop-b-lds`: remove B's LDS staging — prologue B prefetch
    (4 global_load), prologue B ds_store (4 ds_store), in-loop B ds_load
    (8), in-loop B ds_store (4 ds_store + the 4 prefetch global_loads
    that feed them). Produces an INCORRECT kernel (B is never materialized)
    but validates that surgical removal aligns with the annotation.

    Specifically removes (matched by regex on the baseline file):

      Prologue B prefetch  : 4 lines
        global_load_b128 v[145:148], v[163:164], off
        global_load_b128 v[149:152], v[163:164], off offset:16
        global_load_b128 v[153:156], v[163:164], off offset:32
        global_load_b128 v[157:160], v[163:164], off offset:48

      Prologue B ds_store  : 8 lines (4 wait + 4 ds_store at LDS+18432..)
        s_wait_loadcnt 0x3 + ds_store_b128 v166, v[145:148] offset:18432
        ... (3 more pairs at offsets 20736 / 23040 / 25344)

      In-loop B prefetch   : 5 lines (s_clause + 4 global_load)
        s_clause 0x3
        global_load_b128 v[157:160], v[145:146], off offset:64
        global_load_b128 v[153:156], v[145:146], off offset:80
        global_load_b128 v[149:152], v[145:146], off offset:96
        global_load_b128 v[145:148], v[145:146], off offset:112

      In-loop B ds_load    : 8 lines
        ds_load_b128 v[178:181], v230
        ds_load_b128 v[182:185], v230 offset:256
        ds_load_b128 v[186:189], v230 offset:512
        ds_load_b128 v[190:193], v234
        ds_load_b128 v[222:225], v230 offset:4608
        ds_load_b128 v[226:229], v230 offset:4864
        ds_load_b128 v[230:233], v230 offset:5120
        ds_load_b128 v[234:237], v234 offset:4608

      In-loop B ds_store   : 8 lines (4 wait + 4 ds_store using v175)
        s_wait_loadcnt 0x3 + ds_store_b128 v175, v[157:160]
        ... 3 more pairs at offsets 2304/4608/6912 ...
    """
    lines = baseline_path.read_text().splitlines()

    # Patterns for each removal class. Each pattern matches a single
    # full asm line (after leading tab/whitespace).
    REMOVE_EXACT = {
        # prologue B prefetch
        "\tglobal_load_b128 v[145:148], v[163:164], off",
        "\tglobal_load_b128 v[149:152], v[163:164], off offset:16",
        "\tglobal_load_b128 v[153:156], v[163:164], off offset:32",
        "\tglobal_load_b128 v[157:160], v[163:164], off offset:48",
        # prologue B ds_store (paired with their wait)
        "\tds_store_b128 v166, v[145:148] offset:18432",
        "\tds_store_b128 v166, v[149:152] offset:20736",
        "\tds_store_b128 v166, v[153:156] offset:23040",
        "\tds_store_b128 v166, v[157:160] offset:25344",
        # in-loop B prefetch
        "\tglobal_load_b128 v[157:160], v[145:146], off offset:64",
        "\tglobal_load_b128 v[153:156], v[145:146], off offset:80",
        "\tglobal_load_b128 v[149:152], v[145:146], off offset:96",
        "\tglobal_load_b128 v[145:148], v[145:146], off offset:112",
        # in-loop B ds_load
        "\tds_load_b128 v[178:181], v230",
        "\tds_load_b128 v[182:185], v230 offset:256",
        "\tds_load_b128 v[186:189], v230 offset:512",
        "\tds_load_b128 v[190:193], v234",
        "\tds_load_b128 v[222:225], v230 offset:4608",
        "\tds_load_b128 v[226:229], v230 offset:4864",
        "\tds_load_b128 v[230:233], v230 offset:5120",
        "\tds_load_b128 v[234:237], v234 offset:4608",
        # in-loop B ds_store
        "\tds_store_b128 v175, v[157:160]",
        "\tds_store_b128 v175, v[153:156] offset:2304",
        "\tds_store_b128 v175, v[149:152] offset:4608",
        "\tds_store_b128 v175, v[145:148] offset:6912",
    }

    # Sanity: count how many we expected to find.
    expected_count = len(REMOVE_EXACT)
    matched = 0

    out = []
    for line in lines:
        if line in REMOVE_EXACT:
            matched += 1
            out.append(f"\t; [DROP-B-LDS] {line.lstrip()}")
            continue
        out.append(line)

    if matched != expected_count:
        sys.stderr.write(
            f"warning: drop-b-lds expected to match {expected_count} lines, "
            f"matched {matched}. Check baseline format.\n"
        )

    header = (
        "; Auto-generated by gen_mm0_dtvb.py --mode drop-b-lds.\n"
        f"; Source: {baseline_path.name}\n"
        f"; Removed {matched} B-LDS-staging asm lines (commented out in place).\n"
        ";\n"
        "; THIS KERNEL WILL FAIL CORRECTNESS — B is never materialized.\n"
        "; Use only as a structural sanity check, not for benchmarks.\n"
        ";\n"
    )
    return header + "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--mode", choices=("baseline", "drop-b-lds", "dtvb"),
                    default="baseline",
                    help="emission mode (default: baseline pass-through)")
    ap.add_argument("--baseline-s", type=Path, default=DEFAULT_BASELINE,
                    help=f"baseline .s template (default: {DEFAULT_BASELINE.name})")
    ap.add_argument("--out", type=Path, default=None,
                    help="output .s path (default: stdout)")
    ap.add_argument("--check-regalloc", action="store_true",
                    help="verify VGPR window non-overlap and exit")
    args = ap.parse_args()

    if args.check_regalloc:
        regalloc.assert_no_overlap()
        print(f"regalloc OK: {regalloc.total_vgpr_count()} VGPRs total, no overlap")
        return 0

    if not args.baseline_s.exists():
        print(f"error: baseline .s not found at {args.baseline_s}", file=sys.stderr)
        print("       run `make -C rdna4/vlm generated/mm0_bf16_asm_barriersig_early.s`",
              file=sys.stderr)
        return 1

    if args.mode == "baseline":
        text = emit_baseline(args.baseline_s)
    elif args.mode == "drop-b-lds":
        text = emit_drop_b_lds(args.baseline_s)
    elif args.mode == "dtvb":
        print("error: --mode dtvb not yet implemented; see module docstring "
              "Path to ≥160 TFLOP/s for required work.", file=sys.stderr)
        return 2
    else:
        raise AssertionError(f"unhandled mode {args.mode}")

    if args.out is None:
        sys.stdout.write(text)
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(text):,} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
