"""Wrinkle maps from the subject's expression portraits (exprdata.py).

Per expression: the expression portrait is warped back onto the neutral one
along the dense flow, so skin pixels line up; the high-passed log-luminance
change is the new creases' shading. It is read as a height field (darker =
deeper) and its slope is baked into the skin atlas in tangent space: per
texel, the neutral surface point is projected into the portrait and the
image-space gradient is carried onto the texel's tangent and bitangent
through the camera. Expressions are combined into GROUPS (largest slope
wins). The viewer adds a group's slopes to the skin normal map, weighted by
its driver controls per side of the face (left/right split in the front UV
chart).

Maps: wm_<group>.png, RG = 0.5 + 0.5 * the normal perturbation (-dh/dt, -dh/db)
in the skin's tangent frame; flat = 128, 128.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
from PIL import Image

from .exprdata import consistent_flow, sample

GROUPS = {
    "brow_up": {"browInnerUp": 1.0, "browOuterUpLeft": 1.0, "browOuterUpRight": 1.0},
    "brow_down": {"browDownLeft": 1.0, "browDownRight": 1.0, "noseSneerLeft": 1.0, "noseSneerRight": 1.0},
    "smile": {"mouthSmileLeft": 1.0, "mouthSmileRight": 1.0, "cheekSquintLeft": 1.0, "cheekSquintRight": 1.0,
              "eyeSquintLeft": 0.7, "eyeSquintRight": 0.7},
    "mouth": {"mouthPucker": 1.0, "mouthFunnel": 0.8, "mouthFrownLeft": 1.0, "mouthFrownRight": 1.0,
              "mouthStretchLeft": 1.0, "mouthStretchRight": 1.0, "mouthPressLeft": 1.0, "mouthPressRight": 1.0,
              "jawOpen": 0.6, "cheekPuff": 0.6},
}
SLOPE_P99 = 0.45          # the group maps are scaled so their 99th-percentile slope is this


def _gauss(img, sigma):
    import cv2
    return cv2.GaussianBlur(img, (0, 0), sigma)


def shading_detail(n_img: np.ndarray, e_img: np.ndarray, alpha: np.ndarray):
    """Band-passed log-luminance change of the expression, registered onto the
    neutral portrait, and its confidence.

    The warp uses a smoothed flow (sigma FLOW_SMOOTH px): the fine flow partly
    tracks the new creases themselves and would warp them away. Where features
    move (brow hair, nostrils, lids) the smoothed warp leaves misalignment
    edges; those vanish under the fine flow while real creases only weaken, so
    the detail is capped at CAP x the fine-flow detail."""
    import cv2
    F, conf = consistent_flow(n_img, e_img)
    h, w = F.shape[:2]
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    lum = lambda a: np.log(a.astype(np.float32) @ np.array([0.2126, 0.7152, 0.0722], np.float32) / 255 + 0.02)  # noqa
    ln = lum(n_img)

    def detail(f):
        warped = cv2.remap(e_img, xx + f[..., 0], yy + f[..., 1], cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT)
        L = lum(warped) - ln
        return _gauss(L, 1.5) - _gauss(L, 8.0)

    d_s = detail(_gauss(F, FLOW_SMOOTH))
    d_r = detail(F)
    D = np.sign(d_s) * np.minimum(np.abs(d_s), CAP * np.abs(d_r))
    # soft threshold at the noise floor (stubble, pores regenerated by the edit)
    tau = NOISE_FLOOR * float(np.median(np.abs(D[alpha > 0.9]))) if (alpha > 0.9).any() else 0.0
    D = np.sign(D) * np.maximum(np.abs(D) - tau, 0.0)
    mask = cv2.erode((alpha > 0.9).astype(np.uint8), np.ones((9, 9), np.uint8)).astype(np.float32)
    # no round-trip confidence gate: DIS is inconsistent exactly where new creases
    # appear; the cap above already removes misalignment
    return (D * mask).astype(np.float32), mask


FLOW_SMOOTH = 12.0
CAP = 2.0
NOISE_FLOOR = 2.0


def bake(tmpl, skin_part, pos, subj, folder: Path, out_dir: Path, res: int = 1024, log=print, brow_y=None) -> dict:
    """Group wrinkle maps (PNG) in the skin atlas; returns the rig.json entry."""
    import cv2
    from ..head.camera import PixalCamera
    from .bake import rasterize_uv
    from .common import normalize
    manifest = json.loads((folder / "manifest.json").read_text())
    n_img = np.asarray(Image.open(folder / manifest["ref"]).convert("RGB"))
    alpha = np.asarray(Image.open(subj.portrait).convert("RGBA"))[..., 3].astype(np.float32) / 255
    imported = tmpl.info.get('model') is not None
    if imported:
        from ..face_parsing import FaceParser
        alpha *= np.isin(FaceParser()(n_img), [1, 10])
    cam = PixalCamera.from_portrait(subj.portrait, math.radians(subj.fit["camera"]["fov_deg"]))
    # texels -> neutral surface points, tangent frames, portrait pixels
    tid, bary = rasterize_uv(skin_part.uv, skin_part.tris, res)
    ys, xs = np.nonzero(tid >= 0)
    corners = skin_part.tris[tid[ys, xs]]
    bc = bary[ys, xs].astype(np.float64)
    P = pos[skin_part.vmap]
    p = (bc[:, :, None] * P[corners]).sum(1)
    n = normalize((bc[:, :, None] * skin_part.normals[corners]).sum(1))
    t = (bc[:, :, None] * skin_part.tangents[corners, :3]).sum(1)
    t = normalize(t - (t * n).sum(1, keepdims=True) * n)
    b = np.cross(n, t) * np.sign(skin_part.tangents[corners[:, 0], 3])[:, None]
    to_px = lambda q: cam.project(subj.frame.to_glb(q))          # noqa: E731
    px = to_px(p)
    eps = 1e-4
    dt = (to_px(p + eps * t) - px) / eps                          # pixels per metre along t
    db = (to_px(p + eps * b) - px) / eps
    view = normalize(subj.frame.to_h(cam.origin) - p)
    facing = np.clip(((n * view).sum(1) - 0.2) / 0.3, 0, 1)
    # lid margins and the lips' inner rings show the eyeball / mouth moving: no wrinkle data
    wv = skin_part.vmap[corners]
    grp, ring = tmpl.group[wv], tmpl.ring[wv]
    edge = (((grp <= 1) & (grp >= 0) & (ring <= 1)) | ((grp == 2) & (ring <= 2))).any(1)
    if not imported:
        facing = facing * ~edge
    if brow_y is not None:               # no creases in the hair: fade out 45-60 mm above the brows
        from .common import smoothstep
        facing = facing * smoothstep(brow_y + 0.060, brow_y + 0.045, p[:, 1])
    per_group: dict[str, np.ndarray] = {}
    stats = {}
    expression_maps = []
    for name, spec in manifest["expressions"].items():
        f = folder / spec["file"]
        if not f.exists():
            continue
        e_img = np.asarray(Image.open(f).convert("RGB").resize(n_img.shape[1::-1]))
        D, conf = shading_detail(n_img, e_img, alpha)
        gx = cv2.Sobel(D, cv2.CV_32F, 1, 0, ksize=3) / 8
        gy = cv2.Sobel(D, cv2.CV_32F, 0, 1, ksize=3) / 8
        g = sample(np.stack([gx, gy], -1), px)                   # d(detail)/d(pixel)
        c = sample(conf[..., None], px)[:, 0] * facing
        # height ~ detail (brighter = raised); slope along t = grad . (pixels per metre along t) / (pixels per metre)
        scale = max(float(np.linalg.norm(dt, axis=1).mean()), 1e-9)
        st = (g * dt).sum(1) / scale
        sb = (g * db).sum(1) / scale
        slope = -np.stack([st, sb], 1) * c[:, None]              # a height field's normal: (-dh/dt, -dh/db, 1)
        # Preserve each observed expression's appearance and slope separately.
        from .exprdata import EXPRESSIONS
        if name in EXPRESSIONS:
            magnitude = np.linalg.norm(slope, axis=1)
            k_expr = SLOPE_P99 / max(float(np.percentile(magnitude[magnitude > 0], 99)), 1e-9) if (magnitude > 0).any() else 0
            normal = np.full((res, res, 3), 128, np.uint8)
            normal[..., 2] = 255
            normal[ys, xs, :2] = np.round(127.5 + 127.5*np.clip(slope*k_expr, -.95, .95)).astype(np.uint8)
            Image.fromarray(normal).save(out_dir/f'wm_expr_{name}.png')
            F, _ = consistent_flow(n_img, e_img)
            appearance = sample(e_img, px + sample(F, px))
            atlas = np.zeros((res, res, 4), np.uint8)
            atlas[ys, xs, :3] = np.clip(appearance, 0, 255).astype(np.uint8)
            atlas[ys, xs, 3] = np.round(np.clip(c, 0, 1)*255).astype(np.uint8)
            Image.fromarray(atlas).save(out_dir/f'appearance_{name}.png')
            expression_maps.append({'name': name, 'normal': f'wm_expr_{name}.png',
                'appearance': f'appearance_{name}.png', 'drivers': spec.get('controls', {}),
                'scale': k_expr, 'interpretation': 'registered lit appearance; shading-derived normals'})
        grp = spec.get("wrinkle_group", "mouth")
        prev = per_group.get(grp)
        if prev is None:
            per_group[grp] = slope
        else:
            take = np.linalg.norm(slope, axis=1) > np.linalg.norm(prev, axis=1)
            prev[take] = slope[take]
        valid = np.abs(D[conf > 0.5])
        stats[name] = {"group": grp, "p99_detail": round(float(np.percentile(valid, 99)), 4) if len(valid) else 0}
    maps = []
    for grp, slope in per_group.items():
        mag = np.linalg.norm(slope, axis=1)
        hi = float(np.percentile(mag[mag > 0], 99.5)) if (mag > 0).any() else 0.0
        slope = slope * np.minimum(1.0, hi / np.maximum(mag, 1e-12))[:, None]      # clamp the few hotspots
        mag = np.linalg.norm(slope, axis=1)
        k = SLOPE_P99 / max(float(np.percentile(mag[mag > 0], 99)), 1e-9) if (mag > 0).any() else 0
        s = np.clip(slope * k, -0.95, 0.95)
        img = np.full((res, res, 3), 128, np.float32)
        img[..., 2] = 255
        img[ys, xs, 0] = 127.5 + 127.5 * s[:, 0]
        img[ys, xs, 1] = 127.5 + 127.5 * s[:, 1]
        img = cv2.GaussianBlur(img, (0, 0), 0.7)
        fn = f"wm_{grp}.png"
        Image.fromarray(np.clip(np.round(img), 0, 255).astype(np.uint8)).save(out_dir / fn)
        maps.append({"name": grp, "file": fn, "drivers": GROUPS[grp], "scale": round(k, 4)})
        if log:
            log(f"wrinkle map {grp}: scale {k:.3f}")
    from .template import UV_FRONT
    extra = {}
    if imported:
        side = np.full((res, res), 128, np.uint8)
        side[ys, xs] = np.round(np.clip(.5 + p[:, 0]/.012, 0, 1)*255).astype(np.uint8)
        Image.fromarray(side).save(out_dir/'wm_side.png')
        extra['side_file'] = 'wm_side.png'
    return {"maps": maps, "expression_maps": expression_maps, **extra, "u_center": UV_FRONT[0], "side_width": 0.006,
            "blend": "tangent-space slopes (rg * 2 - 1) added to the skin normal map's xy, times the group weight "
                     "for the texel's side (u > u_center: the subject's left); weight = clamp(sum of driver "
                     "control * factor) with left/right controls counting for their side",
            "expressions": stats}
