// Generated by make_kernels.py; SPDX-License-Identifier: MIT
#pragma once
namespace video_rocm {
inline const char *gemm_source=R"HIP(// SPDX-License-Identifier: MIT
#include <hip/hip_runtime.h>
typedef float vf8 __attribute__((ext_vector_type(8)));
typedef unsigned short vbf8 __attribute__((ext_vector_type(8)));
typedef _Float16 vh8 __attribute__((ext_vector_type(8)));
typedef _Float16 vh16 __attribute__((ext_vector_type(16)));
typedef int vi8 __attribute__((ext_vector_type(8)));
typedef unsigned vu2 __attribute__((ext_vector_type(2)));
typedef unsigned char vb8 __attribute__((ext_vector_type(8)));
typedef unsigned char vb16 __attribute__((ext_vector_type(16)));
__device__ float video_bfloat(float x) {
    unsigned u = __float_as_uint(x);
    if ((u & 0x7f800000u) != 0x7f800000u)
        u += 0x7fff + ((u >> 16) & 1);
    return __uint_as_float(u & 0xffff0000u);
}
// Transposed 8-byte LDS slots and a three-stage operand pipeline. Every wave
// retains a 64x64 output tile; vector global loads are guarded for M/N tails.
// K must be a multiple of 32 (the ConvRot checkpoints use multiples of 256).
__device__ __forceinline__ void video_signal() { asm volatile("s_barrier_signal -1" ::: "memory"); }
__device__ __forceinline__ void video_wait() { asm volatile("s_barrier_wait 0xffff" ::: "memory"); }
__device__ __forceinline__ vu2 video_words(vb8 bytes) {
    union {
        vb8 bytes;
        vu2 words;
    } u;
    u.bytes = bytes;
    return u.words;
}
__device__ __forceinline__ void video_store_i8(float *y, int *raw, vi8 acc, const float *xs,
                                               const float *ws, int row, int col, int m, int n,
                                               int rounded) {
    if (col >= n)
        return;
#pragma unroll
    for (int j = 0; j < 8; j++)
        if (row + j < m) {
            long at = (long)(row + j) * n + col;
            if (raw)
                raw[at] = acc[j];
            if (y) {
                float v = float(acc[j]) * (xs[row + j] * ws[col]);
                y[at] = rounded ? video_bfloat(v) : v;
            }
        }
}
extern "C" __global__ __launch_bounds__(128, 1) void video_gemm_i8_pipeline(
    float *y, const signed char *x, const signed char *w, const float *xs, const float *ws, int m,
    int n, int k, int rounded, int *raw) {
    int tid = threadIdx.x, lane = tid & 31, wave = tid >> 5, half = lane >> 4, col = lane & 15;
    int row0 = blockIdx.y * 128, col0 = blockIdx.x * 128, wr = (wave & 1) * 64,
        wc = (wave >> 1) * 64;
    __shared__ vb8 ax[3 * 4 * 128], bw[3 * 4 * 128];
#define VP_LOAD(a0, a1, b0, b1, base)                                                              \
    do {                                                                                           \
        a0 = (row0 + tid < m)                                                                      \
                 ? *reinterpret_cast<const vb16 *>(x + (long)(row0 + tid) * k + (base))            \
                 : vb16{};                                                                         \
        a1 = (row0 + tid < m)                                                                      \
                 ? *reinterpret_cast<const vb16 *>(x + (long)(row0 + tid) * k + (base) + 16)       \
                 : vb16{};                                                                         \
        b0 = (col0 + tid < n)                                                                      \
                 ? *reinterpret_cast<const vb16 *>(w + (long)(col0 + tid) * k + (base))            \
                 : vb16{};                                                                         \
        b1 = (col0 + tid < n)                                                                      \
                 ? *reinterpret_cast<const vb16 *>(w + (long)(col0 + tid) * k + (base) + 16)       \
                 : vb16{};                                                                         \
    } while (0)
#define VP_LO(v) __builtin_shufflevector(v, v, 0, 1, 2, 3, 4, 5, 6, 7)
#define VP_HI(v) __builtin_shufflevector(v, v, 8, 9, 10, 11, 12, 13, 14, 15)
#define VP_STORE(buffer, a0, a1, b0, b1)                                                           \
    do {                                                                                           \
        int at = (buffer) * 512 + tid;                                                             \
        ax[at] = VP_LO(a0);                                                                        \
        ax[at + 128] = VP_HI(a0);                                                                  \
        ax[at + 256] = VP_LO(a1);                                                                  \
        ax[at + 384] = VP_HI(a1);                                                                  \
        bw[at] = VP_LO(b0);                                                                        \
        bw[at + 128] = VP_HI(b0);                                                                  \
        bw[at + 256] = VP_LO(b1);                                                                  \
        bw[at + 384] = VP_HI(b1);                                                                  \
    } while (0)
    vb16 a0, a1, b0, b1;
    VP_LOAD(a0, a1, b0, b1, 0);
    VP_STORE(0, a0, a1, b0, b1);
    if (k > 32) {
        VP_LOAD(a0, a1, b0, b1, 32);
        VP_STORE(1, a0, a1, b0, b1);
    }
    video_signal();
    video_wait();
    vi8 z = {0, 0, 0, 0, 0, 0, 0, 0};
    vi8 c00 = z, c01 = z, c02 = z, c03 = z, c10 = z, c11 = z, c12 = z, c13 = z, c20 = z, c21 = z,
        c22 = z, c23 = z, c30 = z, c31 = z, c32 = z, c33 = z;
    int read = 0, write = 2;
    for (int base = 0; base < k; base += 32) {
        vb16 na0, na1, nb0, nb1;
        bool far = base + 64 < k;
        if (far)
            VP_LOAD(na0, na1, nb0, nb1, base + 64);
#pragma unroll
        for (int step = 0; step < 32; step += 16) {
            int slot = read * 512 + (step / 8 + half) * 128;
            vu2 aa0 = video_words(ax[slot + wr + col]), aa1 = video_words(ax[slot + wr + 16 + col]),
                aa2 = video_words(ax[slot + wr + 32 + col]),
                aa3 = video_words(ax[slot + wr + 48 + col]);
            vu2 bb0 = video_words(bw[slot + wc + col]), bb1 = video_words(bw[slot + wc + 16 + col]),
                bb2 = video_words(bw[slot + wc + 32 + col]),
                bb3 = video_words(bw[slot + wc + 48 + col]);
#define VP_MMA(a, b, c)                                                                            \
    c = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a, true, b, c, false)
            VP_MMA(aa0, bb0, c00);
            VP_MMA(aa0, bb1, c01);
            VP_MMA(aa0, bb2, c02);
            VP_MMA(aa0, bb3, c03);
            VP_MMA(aa1, bb0, c10);
            VP_MMA(aa1, bb1, c11);
            VP_MMA(aa1, bb2, c12);
            VP_MMA(aa1, bb3, c13);
            VP_MMA(aa2, bb0, c20);
            VP_MMA(aa2, bb1, c21);
            VP_MMA(aa2, bb2, c22);
            VP_MMA(aa2, bb3, c23);
            VP_MMA(aa3, bb0, c30);
            VP_MMA(aa3, bb1, c31);
            VP_MMA(aa3, bb2, c32);
            VP_MMA(aa3, bb3, c33);
#undef VP_MMA
        }
        if (far) {
            VP_STORE(write, na0, na1, nb0, nb1);
            write = (write + 1) % 3;
        }
        if (base + 32 < k) {
            video_signal();
            read = (read + 1) % 3;
            video_wait();
        }
    }
#undef VP_LOAD
#undef VP_STORE
#undef VP_LO
#undef VP_HI
    int r = row0 + wr + half * 8, c = col0 + wc + col;
#define VP_OUTPUT(acc, rr, cc) video_store_i8(y, raw, acc, xs, ws, r + rr, c + cc, m, n, rounded)
    VP_OUTPUT(c00, 0, 0);
    VP_OUTPUT(c01, 0, 16);
    VP_OUTPUT(c02, 0, 32);
    VP_OUTPUT(c03, 0, 48);
    VP_OUTPUT(c10, 16, 0);
    VP_OUTPUT(c11, 16, 16);
    VP_OUTPUT(c12, 16, 32);
    VP_OUTPUT(c13, 16, 48);
    VP_OUTPUT(c20, 32, 0);
    VP_OUTPUT(c21, 32, 16);
    VP_OUTPUT(c22, 32, 32);
    VP_OUTPUT(c23, 32, 48);
    VP_OUTPUT(c30, 48, 0);
    VP_OUTPUT(c31, 48, 16);
    VP_OUTPUT(c32, 48, 32);
    VP_OUTPUT(c33, 48, 48);
#undef VP_OUTPUT
}
extern "C" __global__ void video_gemm_f16(float *y, const _Float16 *x, const _Float16 *w, int m,
                                          int n, int k) {
    int lane = threadIdx.x & 31, wave = threadIdx.x >> 5, half = lane >> 4, col = lane & 15;
    int r0 = blockIdx.y * 32 + (wave & 1) * 16, c0 = blockIdx.x * 32 + (wave >> 1) * 16;
    x += (long)blockIdx.z * m * k;
    w += (long)blockIdx.z * n * k;
    y += (long)blockIdx.z * m * n;
    vf8 acc = {0, 0, 0, 0, 0, 0, 0, 0};
    for (int a = 0; a < k; a += 16) {
        vh8 av, bv;
        for (int j = 0; j < 8; j++) {
            int p = a + half * 8 + j;
            av[j] = (r0 + col < m && p < k) ? x[(long)(r0 + col) * k + p] : (_Float16)0;
            bv[j] = (c0 + col < n && p < k) ? w[(long)(c0 + col) * k + p] : (_Float16)0;
        }
        acc = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(av, bv, acc);
    }
    for (int j = 0; j < 8; j++)
        if (r0 + half * 8 + j < m && c0 + col < n)
            y[(long)(r0 + half * 8 + j) * n + c0 + col] = acc[j];
}

// Two 16-K LDS stages reuse operands across a 128x128 output tile. The
// accumulator visits K in the same order as the small FP16 WMMA kernel.
// Callers pad K to 16; vector loads guard complete M/N rows.
extern "C" __global__ __launch_bounds__(128, 1) void video_gemm_f16_tiled(float *y,
                                                                          const _Float16 *x,
                                                                          const _Float16 *w, int m,
                                                                          int n, int k) {
    int tid = threadIdx.x, lane = tid & 31, wave = tid >> 5, half = lane >> 4, col = lane & 15;
    int row0 = blockIdx.y * 128, col0 = blockIdx.x * 128;
    int wr = (wave & 1) * 64, wc = (wave >> 1) * 64;
    __shared__ vh8 ax[2 * 2 * 128], bw[2 * 2 * 128];
#define VF_LOAD(a, b, base)                                                                        \
    do {                                                                                           \
        a = row0 + tid < m ? *reinterpret_cast<const vh16 *>(x + (long)(row0 + tid) * k + base)    \
                           : vh16{};                                                               \
        b = col0 + tid < n ? *reinterpret_cast<const vh16 *>(w + (long)(col0 + tid) * k + base)    \
                           : vh16{};                                                               \
    } while (0)
#define VF_STORE(buffer, a, b)                                                                     \
    do {                                                                                           \
        int at = (buffer) * 256 + tid;                                                             \
        ax[at] = __builtin_shufflevector(a, a, 0, 1, 2, 3, 4, 5, 6, 7);                            \
        ax[at + 128] = __builtin_shufflevector(a, a, 8, 9, 10, 11, 12, 13, 14, 15);                \
        bw[at] = __builtin_shufflevector(b, b, 0, 1, 2, 3, 4, 5, 6, 7);                            \
        bw[at + 128] = __builtin_shufflevector(b, b, 8, 9, 10, 11, 12, 13, 14, 15);                \
    } while (0)
    vh16 a, b;
    VF_LOAD(a, b, 0);
    VF_STORE(0, a, b);
    __syncthreads();
    vf8 zero = {};
    vf8 c00 = zero, c01 = zero, c02 = zero, c03 = zero;
    vf8 c10 = zero, c11 = zero, c12 = zero, c13 = zero;
    vf8 c20 = zero, c21 = zero, c22 = zero, c23 = zero;
    vf8 c30 = zero, c31 = zero, c32 = zero, c33 = zero;
    int read = 0;
    for (int base = 0; base < k; base += 16) {
        vh16 next_a, next_b;
        bool next = base + 16 < k;
        if (next)
            VF_LOAD(next_a, next_b, base + 16);
        int slot = read * 256 + half * 128;
        vh8 aa0 = ax[slot + wr + col], aa1 = ax[slot + wr + 16 + col];
        vh8 aa2 = ax[slot + wr + 32 + col], aa3 = ax[slot + wr + 48 + col];
        vh8 bb0 = bw[slot + wc + col], bb1 = bw[slot + wc + 16 + col];
        vh8 bb2 = bw[slot + wc + 32 + col], bb3 = bw[slot + wc + 48 + col];
#define VF_MMA(a, b, c) c = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a, b, c)
        VF_MMA(aa0, bb0, c00);
        VF_MMA(aa0, bb1, c01);
        VF_MMA(aa0, bb2, c02);
        VF_MMA(aa0, bb3, c03);
        VF_MMA(aa1, bb0, c10);
        VF_MMA(aa1, bb1, c11);
        VF_MMA(aa1, bb2, c12);
        VF_MMA(aa1, bb3, c13);
        VF_MMA(aa2, bb0, c20);
        VF_MMA(aa2, bb1, c21);
        VF_MMA(aa2, bb2, c22);
        VF_MMA(aa2, bb3, c23);
        VF_MMA(aa3, bb0, c30);
        VF_MMA(aa3, bb1, c31);
        VF_MMA(aa3, bb2, c32);
        VF_MMA(aa3, bb3, c33);
#undef VF_MMA
        if (next) {
            VF_STORE(read ^ 1, next_a, next_b);
            __syncthreads();
            read ^= 1;
        }
    }
#undef VF_LOAD
#undef VF_STORE
    int r = row0 + wr + half * 8, c = col0 + wc + col;
#define VF_OUTPUT(acc, rr, cc)                                                                     \
    do {                                                                                           \
        for (int j = 0; j < 8; j++)                                                                \
            if (r + rr + j < m && c + cc < n)                                                      \
                y[(long)(r + rr + j) * n + c + cc] = acc[j];                                       \
    } while (0)
    VF_OUTPUT(c00, 0, 0);
    VF_OUTPUT(c01, 0, 16);
    VF_OUTPUT(c02, 0, 32);
    VF_OUTPUT(c03, 0, 48);
    VF_OUTPUT(c10, 16, 0);
    VF_OUTPUT(c11, 16, 16);
    VF_OUTPUT(c12, 16, 32);
    VF_OUTPUT(c13, 16, 48);
    VF_OUTPUT(c20, 32, 0);
    VF_OUTPUT(c21, 32, 16);
    VF_OUTPUT(c22, 32, 32);
    VF_OUTPUT(c23, 32, 48);
    VF_OUTPUT(c30, 48, 0);
    VF_OUTPUT(c31, 48, 16);
    VF_OUTPUT(c32, 48, 32);
    VF_OUTPUT(c33, 48, 48);
#undef VF_OUTPUT
}
__device__ unsigned video_pack(const signed char *p, int row, int k, int base, int count) {
    unsigned u = 0;
    for (int j = 0; j < 4; j++)
        if (base + j < count)
            u |= (unsigned)(unsigned char)p[(long)row * k + base + j] << (j * 8);
    return u;
}
extern "C" __global__ void video_gemm_bf16(float *y, const float *x, const unsigned short *w, int m,
                                           int n, int k) {
    int lane = threadIdx.x & 31, wave = threadIdx.x >> 5, half = lane >> 4, col = lane & 15;
    int r0 = blockIdx.y * 32 + (wave & 1) * 16, c0 = blockIdx.x * 32 + (wave >> 1) * 16;
    x += (long)blockIdx.z * m * k;
    w += (long)blockIdx.z * n * k;
    y += (long)blockIdx.z * m * n;
    vf8 acc = {0, 0, 0, 0, 0, 0, 0, 0};
    for (int a = 0; a < k; a += 16) {
        vbf8 av, bv;
        for (int j = 0; j < 8; j++) {
            int p = a + half * 8 + j;
            float input = (r0 + col < m && p < k) ? x[(long)(r0 + col) * k + p] : 0.f;
            av[j] = __float_as_uint(video_bfloat(input)) >> 16;
            bv[j] = (c0 + col < n && p < k) ? w[(long)(c0 + col) * k + p] : 0;
        }
        acc = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(av, bv, acc);
    }
    for (int j = 0; j < 8; j++)
        if (r0 + half * 8 + j < m && c0 + col < n)
            y[(long)(r0 + half * 8 + j) * n + c0 + col] = acc[j];
}
extern "C" __global__ void video_gemm_i8(float *y, const signed char *x, const signed char *w,
                                         const float *xs, const float *ws, int m, int n, int k,
                                         int rounded, int *raw) {
    int lane = threadIdx.x & 31, wave = threadIdx.x >> 5, half = lane >> 4, col = lane & 15;
    int r0 = blockIdx.y * 32 + (wave & 1) * 16, c0 = blockIdx.x * 32 + (wave >> 1) * 16;
    vi8 acc = {0, 0, 0, 0, 0, 0, 0, 0};
    for (int a = 0; a < k; a += 16) {
        vu2 av, bv;
        for (int j = 0; j < 2; j++) {
            int p = a + half * 8 + j * 4;
            av[j] = (r0 + col < m) ? video_pack(x, r0 + col, k, p, k) : 0;
            bv[j] = (c0 + col < n) ? video_pack(w, c0 + col, k, p, k) : 0;
        }
        acc = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, av, true, bv, acc, false);
    }
    for (int j = 0; j < 8; j++)
        if (r0 + half * 8 + j < m && c0 + col < n) {
            int row = r0 + half * 8 + j;
            long at = (long)row * n + c0 + col;
            if (raw)
                raw[at] = acc[j];
            if (y) {
                float v = (float)acc[j] * (xs[row] * ws[c0 + col]);
                y[at] = rounded ? video_bfloat(v) : v;
            }
        }
}
// Eight waves compute a 128x128 output tile. Cooperative contiguous transfers
// reuse each input tile across output fragments; tails retain exact zero padding.
extern "C" __global__ void video_gemm_i8_tiled(float *y, const signed char *x, const signed char *w,
                                               const float *xs, const float *ws, int m, int n,
                                               int k, int rounded, int *raw) {
    int tid = threadIdx.x, lane = tid & 31, wave = tid >> 5, half = lane >> 4, col = lane & 15;
    int row0 = blockIdx.y * 128, col0 = blockIdx.x * 128, wr = (wave & 1) * 64,
        wc = (wave >> 1) * 32;
    // A 17-word pitch avoids the bank conflicts of a 64-byte row stride.
    __shared__ unsigned ax[128 * 17], bw[128 * 17];
    vi8 zero = {0, 0, 0, 0, 0, 0, 0, 0};
    vi8 c00 = zero, c01 = zero, c10 = zero, c11 = zero, c20 = zero, c21 = zero, c30 = zero,
        c31 = zero;
    for (int base = 0; base < k; base += 64) {
#pragma unroll
        for (int it = 0; it < 8; it++) {
            int i = tid + it * 256, row = i / 16, p = base + (i % 16) * 4;
            ax[row * 17 + i % 16] =
                (row0 + row < m)
                    ? ((k % 4 == 0 && p + 4 <= k)
                           ? reinterpret_cast<const unsigned *>(x + (long)(row0 + row) * k + p)[0]
                           : video_pack(x, row0 + row, k, p, k))
                    : 0;
            bw[row * 17 + i % 16] =
                (col0 + row < n)
                    ? ((k % 4 == 0 && p + 4 <= k)
                           ? reinterpret_cast<const unsigned *>(w + (long)(col0 + row) * k + p)[0]
                           : video_pack(w, col0 + row, k, p, k))
                    : 0;
        }
        __syncthreads();
#pragma unroll
        for (int a = 0; a < 64; a += 16) {
            vu2 a0, a1, a2, a3, b0, b1;
#pragma unroll
            for (int j = 0; j < 2; j++) {
                int p = a / 4 + half * 2 + j;
                a0[j] = ax[(wr + col) * 17 + p];
                a1[j] = ax[(wr + 16 + col) * 17 + p];
                a2[j] = ax[(wr + 32 + col) * 17 + p];
                a3[j] = ax[(wr + 48 + col) * 17 + p];
                b0[j] = bw[(wc + col) * 17 + p];
                b1[j] = bw[(wc + 16 + col) * 17 + p];
            }
            c00 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a0, true, b0, c00, false);
            c01 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a0, true, b1, c01, false);
            c10 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a1, true, b0, c10, false);
            c11 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a1, true, b1, c11, false);
            c20 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a2, true, b0, c20, false);
            c21 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a2, true, b1, c21, false);
            c30 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a3, true, b0, c30, false);
            c31 = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, a3, true, b1, c31, false);
        }
        __syncthreads();
    }
    vi8 acc[8] = {c00, c01, c10, c11, c20, c21, c30, c31};
#pragma unroll
    for (int tile = 0; tile < 8; tile++) {
#pragma unroll
        for (int j = 0; j < 8; j++) {
            int row = row0 + wr + (tile / 2) * 16 + half * 8 + j,
                outcol = col0 + wc + (tile % 2) * 16 + col;
            if (row < m && outcol < n) {
                long at = (long)row * n + outcol;
                if (raw)
                    raw[at] = acc[tile][j];
                if (y) {
                    float v = float(acc[tile][j]) * (xs[row] * ws[outcol]);
                    y[at] = rounded ? video_bfloat(v) : v;
                }
            }
        }
    }
}
)HIP";
inline const char *precision_source=R"HIP(// SPDX-License-Identifier: MIT
// Explicit upstream FP16 boundaries, in F32 storage for the native graph.
// Custom RMSNorm rounds before its affine multiply. Autocast LayerNorm
// stays FP32; modulation rounds only the Half scale-plus-one expression.
// Gate products are Half; residual addition follows the residual dtype.
__device__ float hv15_half_value(float x) { return __half2float(__float2half(x)); }
// Eager RMSNorm rsqrt is correctly rounded; retain the FP32 multiply before Half.
__device__ float hv15_rms_inverse(float value) {
    float inverse = rsqrtf(value);
    float square = inverse * inverse;
    float low = fmaf(inverse, inverse, -square);
    float error = fmaf(-value, square, 1.f) - value * low;
    return fmaf(.5f * inverse, error, inverse);
}
__device__ float hv15_rms_half(float value, float inverse) {
    float normalized = value * inverse;
    // Prevent combining FP32 multiplication and Half conversion at tie boundaries.
    asm volatile("" : "+v"(normalized));
    return hv15_half_value(normalized);
}
// Match PyTorch ROCm vectorized Welford reduction, including FMA and reciprocal.
struct hv15_wf_state {
    float mean, square, count;
};
__device__ hv15_wf_state hv15_wf_add(hv15_wf_state state, float value) {
    float delta = value - state.mean;
    float count = state.count + 1.f;
    float mean = fmaf(delta, __builtin_amdgcn_rcpf(count), state.mean);
    return {mean, fmaf(delta, value - mean, state.square), count};
}
__device__ hv15_wf_state hv15_wf_join(hv15_wf_state first, hv15_wf_state second) {
    float count = first.count + second.count;
    if (count == 0.f)
        return {0, 0, 0};
    float reciprocal = __builtin_amdgcn_rcpf(count);
    float na = second.count * reciprocal, nb = first.count * reciprocal;
    float delta = first.mean - second.mean;
    float mean = fmaf(nb, first.mean, na * second.mean);
    float square = fmaf(delta * delta * second.count, nb, second.square + first.square);
    return {mean, square, count};
}
__device__ void hv15_layer_stats(const float *input, int channels, float &mean, float &inverse,
                                 float eps) {
    int row = blockIdx.x, tid = threadIdx.x, lane = tid & 31, wave = tid >> 5;
    __shared__ float means[8], squares[8], counts[8];
    hv15_wf_state state{0, 0, 0};
    for (int group = tid; group < channels / 4; group += 256)
        for (int j = 0; j < 4; ++j)
            state = hv15_wf_add(state, input[row * channels + group * 4 + j]);
    for (int offset = 16; offset; offset >>= 1) {
        hv15_wf_state peer{__shfl_down(state.mean, offset), __shfl_down(state.square, offset),
                           __shfl_down(state.count, offset)};
        state = hv15_wf_join(state, peer);
    }
    for (int offset = 4; offset; offset >>= 1) {
        if (lane == 0 && wave >= offset && wave < 2 * offset) {
            means[wave - offset] = state.mean;
            squares[wave - offset] = state.square;
            counts[wave - offset] = state.count;
        }
        __syncthreads();
        if (lane == 0 && wave < offset)
            state = hv15_wf_join(state, {means[wave], squares[wave], counts[wave]});
        __syncthreads();
    }
    if (tid == 0) {
        means[0] = state.mean;
        squares[0] = state.square / float(channels);
    }
    __syncthreads();
    mean = means[0];
    inverse = rsqrtf(squares[0] + eps);
}
extern "C" {
__global__ void hv15_autocast_norm(float *y, const float *x, const float *w, const float *b,
                                   int rows, int channels, int mode, float eps) {
    float mean, inverse;
    hv15_layer_stats(x, channels, mean, inverse, eps);
    int row = blockIdx.x, tid = threadIdx.x;
    for (int c = tid; c < channels; c += 256) {
        float normalized = (x[row * channels + c] - mean) * inverse;
        y[row * channels + c] = w ? fmaf(normalized, w[c], b ? b[c] : 0.f) : normalized;
    }
}

__global__ void hv15_half_element(float *y, const float *x, const float *z, const float *b,
                                  int count, int channels, int mode, float scale, float offset) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= count)
        return;
    float v = x[i];
    if (mode == 0)
        v = v * scale + offset;
    if (mode == 1)
        v = v + z[i] * scale;
    if (mode == 2)
        v = v * z[i];
    if (mode == 3)
        v = v / (1.f + expf(-v));
    if (mode == 4)
        v = 0.5f * v * (1.f + tanhf(0.7978845608f * (v + 0.044715f * v * v * v)));
    if (mode == 5)
        v = 0.5f * v * (1.f + erff(v * 0.7071067812f));
    if (mode == 6)
        v += b[i % channels];
    if (mode == 7)
        v = hv15_half_value(v * hv15_half_value(1.f + z[i % channels])) + b[i % channels];
    if (mode == 8)
        v = v * z[i % channels];
    if (mode == 9)
        v = fmaxf(v, 0.f);
    y[i] = hv15_half_value(v);
}
__global__ void hv15_round_half(float *x, int count) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < count)
        x[i] = hv15_half_value(x[i]);
}
__global__ void hv15_half_norm(float *y, const float *x, const float *w, const float *b, int rows,
                               int channels, int rms, float eps) {
    int row = blockIdx.x, tid = threadIdx.x;
    if (row >= rows)
        return;
    if (channels == 128 && rms == 1) {
        __shared__ float inverse;
        if (tid < 32) {
            float square = 0.f;
            for (int i = 0; i < 4; ++i) {
                float value = x[row * 128 + tid * 4 + i];
                square += value * value;
            }
            for (int offset = 1; offset < 32; offset <<= 1)
                square += __shfl_down(square, offset);
            if (tid == 0)
                inverse = hv15_rms_inverse(square / 128.f + eps);
        }
        __syncthreads();
        if (tid < 128) {
            float value = hv15_rms_half(x[row * 128 + tid], inverse);
            y[row * 128 + tid] = hv15_half_value(value * (w ? w[tid] : 1.f) + (b ? b[tid] : 0.f));
        }
        return;
    }
    __shared__ float s[256], q[256];
    float sum = 0.f, sq = 0.f;
    for (int c = tid; c < channels; c += 256) {
        float v = x[row * channels + c];
        sum += v;
        sq += v * v;
    }
    s[tid] = sum;
    q[tid] = sq;
    __syncthreads();
    for (int n = 128; n; n >>= 1) {
        if (tid < n) {
            s[tid] += s[tid + n];
            q[tid] += q[tid + n];
        }
        __syncthreads();
    }
    float mean = rms ? 0.f : s[0] / channels;
    float inverse = rms == 2 ? sqrtf(float(channels)) / fmaxf(sqrtf(q[0]), 1.e-12f)
                             : rsqrtf(fmaxf(q[0] / channels - mean * mean, 0.f) + eps);
    for (int c = tid; c < channels; c += 256) {
        float v = (x[row * channels + c] - mean) * inverse;
        if (rms)
            v = hv15_half_value(v);
        y[row * channels + c] = hv15_half_value(v * (w ? w[c] : 1.f) + (b ? b[c] : 0.f));
    }
}
__global__ void hv15_autocast_modulate(float *y, const float *x, const float *mod, int rows, int c,
                                       int start) {
    int row = blockIdx.x, tid = threadIdx.x;
    float mean, inverse;
    hv15_layer_stats(x, c, mean, inverse, 1.e-6f);
    for (int j = tid; j < c; j += 256)
        y[row * c + j] =
            (x[row * c + j] - mean) * inverse * hv15_half_value(1.f + mod[start + c + j]) +
            mod[start + j];
}
__global__ void hv15_half_gate(float *y, const float *x, const float *z, const float *mod,
                               int count, int c, int start) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < count)
        y[i] = hv15_half_value(x[i] + hv15_half_value(z[i] * mod[start + i % c]));
}
__global__ void hv15_float_gate_half(float *y, const float *x, const float *z, const float *mod,
                                     int count, int c, int start) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < count)
        y[i] = x[i] + hv15_half_value(z[i] * mod[start + i % c]);
}
__global__ void hv15_modulate_values(float *y, const float *x, const float *scale,
                                     const float *shift, int count, int c) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < count)
        y[i] = x[i] * hv15_half_value(1.f + scale[i % c]) + shift[i % c];
}
__global__ void hv15_half_qkv(half *q, half *k, half *v, const float *packed, const float *qw,
                              const float *kw, int rows, int height, int width, int image) {
    int row = blockIdx.x, head = blockIdx.y, d = threadIdx.x;
    __shared__ float qa[128], ka[128], qs[128], ks[128];
    int base = row * 6144 + head * 128;
    float a = packed[base + d], b = packed[base + 2048 + d];
    if (d < 32) {
        float qsum = 0.f, ksum = 0.f;
        for (int i = 0; i < 4; ++i) {
            float qvalue = packed[base + d * 4 + i];
            float kvalue = packed[base + 2048 + d * 4 + i];
            qsum += qvalue * qvalue;
            ksum += kvalue * kvalue;
        }
        for (int offset = 1; offset < 32; offset <<= 1) {
            qsum += __shfl_down(qsum, offset);
            ksum += __shfl_down(ksum, offset);
        }
        if (d == 0) {
            qs[0] = hv15_rms_inverse(qsum / 128.f + 1.e-6f);
            ks[0] = hv15_rms_inverse(ksum / 128.f + 1.e-6f);
        }
    }
    __syncthreads();
    qa[d] = hv15_half_value(hv15_rms_half(a, qs[0]) * qw[d]);
    ka[d] = hv15_half_value(hv15_rms_half(b, ks[0]) * kw[d]);
    __syncthreads();
    if (image) {
        int first = d & ~1,
            axis = first < 16   ? 0
                   : first < 72 ? 1
                                : 2,
            axisdim = axis == 0 ? 16 : 56;
        int frequency = (first - (axis == 0 ? 0 : axis == 1 ? 16 : 72)) / 2;
        int position = axis == 0   ? row / (height * width)
                       : axis == 1 ? (row / width) % height
                                   : row % width;
        float angle = position * powf(256.f, -2.f * frequency / axisdim), c = cosf(angle),
              s = sinf(angle);
        a = (d & 1) ? qa[d] * c + qa[d - 1] * s : qa[d] * c - qa[d + 1] * s;
        b = (d & 1) ? ka[d] * c + ka[d - 1] * s : ka[d] * c - ka[d + 1] * s;
    } else {
        a = qa[d];
        b = ka[d];
    }
    int out = (head * rows + row) * 128 + d;
    q[out] = __float2half(a);
    k[out] = __float2half(b);
    v[out] = __float2half(packed[base + 4096 + d]);
}
}

// Use the fixed CPU FP32 frequency basis and GPU libm, as the upstream embedder.
extern "C" __global__ void hv15_time_embedding(float *out, const float *frequency, float time) {
    int i = threadIdx.x;
    if (i < 128) {
        float phase = time * frequency[i];
        out[i] = cosf(phase);
        out[i + 128] = sinf(phase);
    }
}
)HIP";
inline const char *attention_source=R"HIP(#include <hip/hip_runtime.h>
extern "C" {
#if defined(__gfx1200__) || defined(__gfx1201__)
__global__ void video_attention_f16(float *__restrict__ out,
    const float *__restrict__ Q, const float *__restrict__ K,
    const float *__restrict__ V,
    int N, int n_heads, int head_dim, float scale) {
    (void)head_dim;
    int h = blockIdx.x;
    int cta_q0 = blockIdx.y * 64;
    int tid = threadIdx.x;
    int wave = tid >> 5;
    int lane = tid & 31;
    int half = lane >> 4;
    int idx  = lane & 15;
    int dim = n_heads * 128;
    /* K_STRIDE=132 (66 dw -> 16 unique banks), V_STRIDE=18 (9 dw -> 16 banks). */
    enum { K_STRIDE = 132, V_STRIDE = 18 };
    __shared__ _Float16 smK[2*16*K_STRIDE];
    __shared__ _Float16 smVt[2*128*V_STRIDE];
    __shared__ _Float16 smP[4*16*16];
    _Float16 *myP = smP + wave * (16*16);
    typedef float float8 __attribute__((ext_vector_type(8)));
    typedef _Float16 half8 __attribute__((ext_vector_type(8)));
    int wq0 = cta_q0 + wave * 16;
    /* Persistent Q in registers: q_reg[kt] is the WMMA A-fragment for head-dim
     * sub-tile kt; element i = bf16(Q[row=wq0+idx][d=kt*16+half*8+i]). Loaded
     * once and fed to the QK-WMMA straight from VGPRs — no smQ, no per-tile LDS
     * Q reads. Unscaled (scale is applied to the scores below, as in v1). */
    half8 q_reg[8];
    {
        int qi = wq0 + idx;
        for (int kt = 0; kt < 8; kt++) {
            for (int i = 0; i < 8; i++) {
                int d = kt*16 + half*8 + i;
                float qv = (qi < N) ? Q[(long)qi*dim + h*128 + d] : 0.f;
                float b = qv;
                q_reg[kt][i] = (_Float16)b;
            }
        }
    }
    float8 O0 = {0,0,0,0,0,0,0,0};
    float8 O1 = O0, O2 = O0, O3 = O0, O4 = O0, O5 = O0, O6 = O0, O7 = O0;
    float m_i[8], l_i[8];
    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }
    int n_kv = (N + 15) / 16;
    /* Prefetch tile 0 -> buffer 0. */
    {
        for (int it = 0; it < 16; it++) {
            int e = tid + it * 128;
            int r = e >> 7;
            int d = e & 127;
            float vk = (r < N) ? K[(long)r*dim + h*128 + d] : 0.f;
            float vv = (r < N) ? V[(long)r*dim + h*128 + d] : 0.f;
            float bk = vk;
            float bv = vv;
            smK[r*K_STRIDE + d]  = (_Float16)bk;
            smVt[d*V_STRIDE + r] = (_Float16)bv;
        }
    }
    __syncthreads();
    for (int kv = 0; kv < n_kv; kv++) {
        int cur = kv & 1;
        int nxt = cur ^ 1;
        _Float16 *curK  = smK  + cur * (16*K_STRIDE);
        _Float16 *curVt = smVt + cur * (128*V_STRIDE);
        if (kv + 1 < n_kv) {
            int kv_base_n = (kv + 1) * 16;
            _Float16 *nxtK  = smK  + nxt * (16*K_STRIDE);
            _Float16 *nxtVt = smVt + nxt * (128*V_STRIDE);
            for (int it = 0; it < 16; it++) {
                int e = tid + it * 128;
                int r = e >> 7;
                int d = e & 127;
                int kvi = kv_base_n + r;
                float vk = (kvi < N) ? K[(long)kvi*dim + h*128 + d] : 0.f;
                float vv = (kvi < N) ? V[(long)kvi*dim + h*128 + d] : 0.f;
                float bk = vk;
                float bv = vv;
                nxtK[r*K_STRIDE + d]  = (_Float16)bk;
                nxtVt[d*V_STRIDE + r] = (_Float16)bv;
            }
        }
        int kv_base = kv * 16;
        float8 S = {0,0,0,0,0,0,0,0};
        for (int kt = 0; kt < 8; kt++) {
            int k_off = kt * 16 + half * 8;
            half8 kb;
            for (int i = 0; i < 8; i++) kb[i] = curK[idx*K_STRIDE + k_off + i];
            S = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(q_reg[kt], kb, S);
        }
        float row_max[8];
        for (int i = 0; i < 8; i++) {
            float s = S[i] * scale;
            int kvi_col = kv_base + idx;
            if (kvi_col >= N) s = -1e30f;
            S[i] = s;
            float m = s;
            m = fmaxf(m, __shfl_xor(m, 1));
            m = fmaxf(m, __shfl_xor(m, 2));
            m = fmaxf(m, __shfl_xor(m, 4));
            m = fmaxf(m, __shfl_xor(m, 8));
            row_max[i] = m;
        }
        float alpha[8];
        for (int i = 0; i < 8; i++) {
            float m_new = fmaxf(m_i[i], row_max[i]);
            alpha[i] = __expf(m_i[i] - m_new);
            float p = __expf(S[i] - m_new);
            S[i] = p;
            float rs = p;
            rs += __shfl_xor(rs, 1);
            rs += __shfl_xor(rs, 2);
            rs += __shfl_xor(rs, 4);
            rs += __shfl_xor(rs, 8);
            l_i[i] = l_i[i] * alpha[i] + rs;
            m_i[i] = m_new;
        }
        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
        for (int t = 0; t < 8; t++)
            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];
        for (int i = 0; i < 8; i++) {
            int row = half*8 + i;
            float pv = S[i];
            float b = pv;
            myP[row*16 + idx] = (_Float16)b;
        }
        __builtin_amdgcn_s_waitcnt(0);
        half8 pa;
        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half*8 + i];
        for (int t = 0; t < 8; t++) {
            int hd_base = t * 16;
            half8 vb;
            for (int i = 0; i < 8; i++) vb[i] = curVt[(hd_base + idx)*V_STRIDE + half*8 + i];
            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(pa, vb, *Os[t]);
        }
        __syncthreads();
    }
    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
    float inv_l[8];
    for (int i = 0; i < 8; i++)
        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;
    for (int t = 0; t < 8; t++) {
        int col = t*16 + idx;
        for (int i = 0; i < 8; i++) {
            int qi = wq0 + half*8 + i;
            if (qi < N)
                out[(long)qi*dim + h*128 + col] = (*Os[t])[i] * inv_l[i];
        }
    }
}
#endif

#if defined(__gfx1200__) || defined(__gfx1201__)
__global__ void video_attention_bf16(float *__restrict__ out,
    const float *__restrict__ Q, const float *__restrict__ K,
    const float *__restrict__ V,
    int N, int n_heads, int head_dim, float scale, int kv_heads, int causal) {
    (void)head_dim;
    int h = blockIdx.x;
    int cta_q0 = blockIdx.y * 64;
    int tid = threadIdx.x;
    int wave = tid >> 5;
    int lane = tid & 31;
    int half = lane >> 4;
    int idx  = lane & 15;
    int dim = n_heads * 128;
    /* K_STRIDE=132 (66 dw -> 16 unique banks), V_STRIDE=18 (9 dw -> 16 banks). */
    enum { K_STRIDE = 132, V_STRIDE = 18 };
    __shared__ short smK[2*16*K_STRIDE];
    __shared__ short smVt[2*128*V_STRIDE];
    __shared__ short smP[4*16*16];
    short *myP = smP + wave * (16*16);
    typedef float float8 __attribute__((ext_vector_type(8)));
    typedef short bf16x8 __attribute__((ext_vector_type(8)));
    int wq0 = cta_q0 + wave * 16;
    /* Persistent Q in registers: q_reg[kt] is the WMMA A-fragment for head-dim
     * sub-tile kt; element i = bf16(Q[row=wq0+idx][d=kt*16+half*8+i]). Loaded
     * once and fed to the QK-WMMA straight from VGPRs — no smQ, no per-tile LDS
     * Q reads. Unscaled (scale is applied to the scores below, as in v1). */
    bf16x8 q_reg[8];
    {
        int qi = wq0 + idx;
        for (int kt = 0; kt < 8; kt++) {
            for (int i = 0; i < 8; i++) {
                int d = kt*16 + half*8 + i;
                float qv = (qi < N) ? Q[(long)qi*dim + h*128 + d] : 0.f;
                unsigned int b; __builtin_memcpy(&b, &qv, 4);
                q_reg[kt][i] = (short)((b + 0x7fffU + ((b >> 16) & 1U)) >> 16);
            }
        }
    }
    float8 O0 = {0,0,0,0,0,0,0,0};
    float8 O1 = O0, O2 = O0, O3 = O0, O4 = O0, O5 = O0, O6 = O0, O7 = O0;
    float m_i[8], l_i[8];
    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }
    int n_kv = (N + 15) / 16;
    /* Prefetch tile 0 -> buffer 0. */
    {
        for (int it = 0; it < 16; it++) {
            int e = tid + it * 128;
            int r = e >> 7;
            int d = e & 127;
            float vk = (r < N) ? K[(long)r*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
            float vv = (r < N) ? V[(long)r*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
            unsigned int bk; __builtin_memcpy(&bk, &vk, 4);
            unsigned int bv; __builtin_memcpy(&bv, &vv, 4);
            smK[r*K_STRIDE + d]  = (short)((bk + 0x7fffU + ((bk >> 16) & 1U)) >> 16);
            smVt[d*V_STRIDE + r] = (short)((bv + 0x7fffU + ((bv >> 16) & 1U)) >> 16);
        }
    }
    __syncthreads();
    for (int kv = 0; kv < n_kv; kv++) {
        int cur = kv & 1;
        int nxt = cur ^ 1;
        short *curK  = smK  + cur * (16*K_STRIDE);
        short *curVt = smVt + cur * (128*V_STRIDE);
        if (kv + 1 < n_kv) {
            int kv_base_n = (kv + 1) * 16;
            short *nxtK  = smK  + nxt * (16*K_STRIDE);
            short *nxtVt = smVt + nxt * (128*V_STRIDE);
            for (int it = 0; it < 16; it++) {
                int e = tid + it * 128;
                int r = e >> 7;
                int d = e & 127;
                int kvi = kv_base_n + r;
                float vk = (kvi < N) ? K[(long)kvi*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
                float vv = (kvi < N) ? V[(long)kvi*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
                unsigned int bk; __builtin_memcpy(&bk, &vk, 4);
                unsigned int bv; __builtin_memcpy(&bv, &vv, 4);
                nxtK[r*K_STRIDE + d]  = (short)((bk + 0x7fffU + ((bk >> 16) & 1U)) >> 16);
                nxtVt[d*V_STRIDE + r] = (short)((bv + 0x7fffU + ((bv >> 16) & 1U)) >> 16);
            }
        }
        int kv_base = kv * 16;
        float8 S = {0,0,0,0,0,0,0,0};
        for (int kt = 0; kt < 8; kt++) {
            int k_off = kt * 16 + half * 8;
            bf16x8 kb;
            for (int i = 0; i < 8; i++) kb[i] = curK[idx*K_STRIDE + k_off + i];
            S = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(q_reg[kt], kb, S);
        }
        float row_max[8];
        for (int i = 0; i < 8; i++) {
            float s = S[i] * scale;
            int kvi_col = kv_base + idx;
            if (kvi_col >= N || (causal && kvi_col > wq0 + half*8 + i)) s = -1e30f;
            S[i] = s;
            float m = s;
            m = fmaxf(m, __shfl_xor(m, 1));
            m = fmaxf(m, __shfl_xor(m, 2));
            m = fmaxf(m, __shfl_xor(m, 4));
            m = fmaxf(m, __shfl_xor(m, 8));
            row_max[i] = m;
        }
        float alpha[8];
        for (int i = 0; i < 8; i++) {
            float m_new = fmaxf(m_i[i], row_max[i]);
            alpha[i] = __expf(m_i[i] - m_new);
            float p = __expf(S[i] - m_new);
            S[i] = p;
            float rs = p;
            rs += __shfl_xor(rs, 1);
            rs += __shfl_xor(rs, 2);
            rs += __shfl_xor(rs, 4);
            rs += __shfl_xor(rs, 8);
            l_i[i] = l_i[i] * alpha[i] + rs;
            m_i[i] = m_new;
        }
        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
        for (int t = 0; t < 8; t++)
            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];
        for (int i = 0; i < 8; i++) {
            int row = half*8 + i;
            float pv = S[i];
            unsigned int b; __builtin_memcpy(&b, &pv, 4);
            myP[row*16 + idx] = (short)((b + 0x7fffU + ((b >> 16) & 1U)) >> 16);
        }
        __builtin_amdgcn_s_waitcnt(0);
        bf16x8 pa;
        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half*8 + i];
        for (int t = 0; t < 8; t++) {
            int hd_base = t * 16;
            bf16x8 vb;
            for (int i = 0; i < 8; i++) vb[i] = curVt[(hd_base + idx)*V_STRIDE + half*8 + i];
            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(pa, vb, *Os[t]);
        }
        __syncthreads();
    }
    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
    float inv_l[8];
    for (int i = 0; i < 8; i++)
        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;
    for (int t = 0; t < 8; t++) {
        int col = t*16 + idx;
        for (int i = 0; i < 8; i++) {
            int qi = wq0 + half*8 + i;
            if (qi < N)
                out[(long)qi*dim + h*128 + col] = (*Os[t])[i] * inv_l[i];
        }
    }
}
#endif

#if defined(__gfx1200__) || defined(__gfx1201__)
__global__ void video_attention_bf16_64(float *__restrict__ out,
    const float *__restrict__ Q, const float *__restrict__ K,
    const float *__restrict__ V,
    int N, int n_heads, int head_dim, float scale, int kv_heads, int causal) {
    (void)head_dim;
    int h = blockIdx.x;
    int cta_q0 = blockIdx.y * 64;
    int tid = threadIdx.x;
    int wave = tid >> 5;
    int lane = tid & 31;
    int half = lane >> 4;
    int idx  = lane & 15;
    int dim = n_heads * 64;
    /* K_STRIDE=132 (66 dw -> 16 unique banks), V_STRIDE=18 (9 dw -> 16 banks). */
    enum { K_STRIDE = 132, V_STRIDE = 18 };
    __shared__ short smK[2*16*K_STRIDE];
    __shared__ short smVt[2*64*V_STRIDE];
    __shared__ short smP[4*16*16];
    short *myP = smP + wave * (16*16);
    typedef float float8 __attribute__((ext_vector_type(8)));
    typedef short bf16x8 __attribute__((ext_vector_type(8)));
    int wq0 = cta_q0 + wave * 16;
    /* Persistent Q in registers: q_reg[kt] is the WMMA A-fragment for head-dim
     * sub-tile kt; element i = bf16(Q[row=wq0+idx][d=kt*16+half*8+i]). Loaded
     * once and fed to the QK-WMMA straight from VGPRs — no smQ, no per-tile LDS
     * Q reads. Unscaled (scale is applied to the scores below, as in v1). */
    bf16x8 q_reg[8];
    {
        int qi = wq0 + idx;
        for (int kt = 0; kt < 4; kt++) {
            for (int i = 0; i < 8; i++) {
                int d = kt*16 + half*8 + i;
                float qv = (qi < N) ? Q[(long)qi*dim + h*64 + d] : 0.f;
                unsigned int b; __builtin_memcpy(&b, &qv, 4);
                q_reg[kt][i] = (short)((b + 0x7fffU + ((b >> 16) & 1U)) >> 16);
            }
        }
    }
    float8 O0 = {0,0,0,0,0,0,0,0};
    float8 O1 = O0, O2 = O0, O3 = O0, O4 = O0, O5 = O0, O6 = O0, O7 = O0;
    float m_i[8], l_i[8];
    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }
    int n_kv = (N + 15) / 16;
    /* Prefetch tile 0 -> buffer 0. */
    {
        for (int it = 0; it < 8; it++) {
            int e = tid + it * 128;
            int r = e >> 6;
            int d = e & 63;
            float vk = (r < N) ? K[(long)r*kv_heads*64 + (h/(n_heads/kv_heads))*64 + d] : 0.f;
            float vv = (r < N) ? V[(long)r*kv_heads*64 + (h/(n_heads/kv_heads))*64 + d] : 0.f;
            unsigned int bk; __builtin_memcpy(&bk, &vk, 4);
            unsigned int bv; __builtin_memcpy(&bv, &vv, 4);
            smK[r*K_STRIDE + d]  = (short)((bk + 0x7fffU + ((bk >> 16) & 1U)) >> 16);
            smVt[d*V_STRIDE + r] = (short)((bv + 0x7fffU + ((bv >> 16) & 1U)) >> 16);
        }
    }
    __syncthreads();
    for (int kv = 0; kv < n_kv; kv++) {
        int cur = kv & 1;
        int nxt = cur ^ 1;
        short *curK  = smK  + cur * (16*K_STRIDE);
        short *curVt = smVt + cur * (64*V_STRIDE);
        if (kv + 1 < n_kv) {
            int kv_base_n = (kv + 1) * 16;
            short *nxtK  = smK  + nxt * (16*K_STRIDE);
            short *nxtVt = smVt + nxt * (64*V_STRIDE);
            for (int it = 0; it < 8; it++) {
                int e = tid + it * 128;
                int r = e >> 6;
                int d = e & 63;
                int kvi = kv_base_n + r;
                float vk = (kvi < N) ? K[(long)kvi*kv_heads*64 + (h/(n_heads/kv_heads))*64 + d] : 0.f;
                float vv = (kvi < N) ? V[(long)kvi*kv_heads*64 + (h/(n_heads/kv_heads))*64 + d] : 0.f;
                unsigned int bk; __builtin_memcpy(&bk, &vk, 4);
                unsigned int bv; __builtin_memcpy(&bv, &vv, 4);
                nxtK[r*K_STRIDE + d]  = (short)((bk + 0x7fffU + ((bk >> 16) & 1U)) >> 16);
                nxtVt[d*V_STRIDE + r] = (short)((bv + 0x7fffU + ((bv >> 16) & 1U)) >> 16);
            }
        }
        int kv_base = kv * 16;
        float8 S = {0,0,0,0,0,0,0,0};
        for (int kt = 0; kt < 4; kt++) {
            int k_off = kt * 16 + half * 8;
            bf16x8 kb;
            for (int i = 0; i < 8; i++) kb[i] = curK[idx*K_STRIDE + k_off + i];
            S = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(q_reg[kt], kb, S);
        }
        float row_max[8];
        for (int i = 0; i < 8; i++) {
            float s = S[i] * scale;
            int kvi_col = kv_base + idx;
            if (kvi_col >= N || (causal && kvi_col > wq0 + half*8 + i)) s = -1e30f;
            S[i] = s;
            float m = s;
            m = fmaxf(m, __shfl_xor(m, 1));
            m = fmaxf(m, __shfl_xor(m, 2));
            m = fmaxf(m, __shfl_xor(m, 4));
            m = fmaxf(m, __shfl_xor(m, 8));
            row_max[i] = m;
        }
        float alpha[8];
        for (int i = 0; i < 8; i++) {
            float m_new = fmaxf(m_i[i], row_max[i]);
            alpha[i] = __expf(m_i[i] - m_new);
            float p = __expf(S[i] - m_new);
            S[i] = p;
            float rs = p;
            rs += __shfl_xor(rs, 1);
            rs += __shfl_xor(rs, 2);
            rs += __shfl_xor(rs, 4);
            rs += __shfl_xor(rs, 8);
            l_i[i] = l_i[i] * alpha[i] + rs;
            m_i[i] = m_new;
        }
        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
        for (int t = 0; t < 4; t++)
            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];
        for (int i = 0; i < 8; i++) {
            int row = half*8 + i;
            float pv = S[i];
            unsigned int b; __builtin_memcpy(&b, &pv, 4);
            myP[row*16 + idx] = (short)((b + 0x7fffU + ((b >> 16) & 1U)) >> 16);
        }
        __builtin_amdgcn_s_waitcnt(0);
        bf16x8 pa;
        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half*8 + i];
        for (int t = 0; t < 4; t++) {
            int hd_base = t * 16;
            bf16x8 vb;
            for (int i = 0; i < 8; i++) vb[i] = curVt[(hd_base + idx)*V_STRIDE + half*8 + i];
            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(pa, vb, *Os[t]);
        }
        __syncthreads();
    }
    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
    float inv_l[8];
    for (int i = 0; i < 8; i++)
        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;
    for (int t = 0; t < 4; t++) {
        int col = t*16 + idx;
        for (int i = 0; i < 8; i++) {
            int qi = wq0 + half*8 + i;
            if (qi < N)
                out[(long)qi*dim + h*64 + col] = (*Os[t])[i] * inv_l[i];
        }
    }
}
#endif

#if defined(__gfx1200__) || defined(__gfx1201__)
__global__ void video_attention_bf16_exp2(float *__restrict__ out,
    const float *__restrict__ Q, const float *__restrict__ K,
    const float *__restrict__ V,
    int N, int n_heads, int head_dim, float scale, int kv_heads, int causal) {
    (void)head_dim;
    int h = blockIdx.x;
    int cta_q0 = blockIdx.y * 64;
    int tid = threadIdx.x;
    int wave = tid >> 5;
    int lane = tid & 31;
    int half = lane >> 4;
    int idx  = lane & 15;
    int dim = n_heads * 128;
    /* K_STRIDE=132 (66 dw -> 16 unique banks), V_STRIDE=18 (9 dw -> 16 banks). */
    enum { K_STRIDE = 132, V_STRIDE = 18 };
    __shared__ short smK[2*16*K_STRIDE];
    __shared__ short smVt[2*128*V_STRIDE];
    __shared__ short smP[4*16*16];
    short *myP = smP + wave * (16*16);
    typedef float float8 __attribute__((ext_vector_type(8)));
    typedef short bf16x8 __attribute__((ext_vector_type(8)));
    int wq0 = cta_q0 + wave * 16;
    /* Persistent Q in registers: q_reg[kt] is the WMMA A-fragment for head-dim
     * sub-tile kt; element i = bf16(Q[row=wq0+idx][d=kt*16+half*8+i]). Loaded
     * once and fed to the QK-WMMA straight from VGPRs — no smQ, no per-tile LDS
     * Q reads. Unscaled (scale is applied to the scores below, as in v1). */
    bf16x8 q_reg[8];
    {
        int qi = wq0 + idx;
        for (int kt = 0; kt < 8; kt++) {
            for (int i = 0; i < 8; i++) {
                int d = kt*16 + half*8 + i;
                float qv = (qi < N) ? Q[(long)qi*dim + h*128 + d] : 0.f;
                unsigned int b; __builtin_memcpy(&b, &qv, 4);
                q_reg[kt][i] = (short)((b + 0x7fffU + ((b >> 16) & 1U)) >> 16);
            }
        }
    }
    float8 O0 = {0,0,0,0,0,0,0,0};
    float8 O1 = O0, O2 = O0, O3 = O0, O4 = O0, O5 = O0, O6 = O0, O7 = O0;
    float m_i[8], l_i[8];
    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }
    int n_kv = (N + 15) / 16;
    /* Prefetch tile 0 -> buffer 0. */
    {
        for (int it = 0; it < 16; it++) {
            int e = tid + it * 128;
            int r = e >> 7;
            int d = e & 127;
            float vk = (r < N) ? K[(long)r*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
            float vv = (r < N) ? V[(long)r*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
            unsigned int bk; __builtin_memcpy(&bk, &vk, 4);
            unsigned int bv; __builtin_memcpy(&bv, &vv, 4);
            smK[r*K_STRIDE + d]  = (short)((bk + 0x7fffU + ((bk >> 16) & 1U)) >> 16);
            smVt[d*V_STRIDE + r] = (short)((bv + 0x7fffU + ((bv >> 16) & 1U)) >> 16);
        }
    }
    __syncthreads();
    for (int kv = 0; kv < n_kv; kv++) {
        int cur = kv & 1;
        int nxt = cur ^ 1;
        short *curK  = smK  + cur * (16*K_STRIDE);
        short *curVt = smVt + cur * (128*V_STRIDE);
        if (kv + 1 < n_kv) {
            int kv_base_n = (kv + 1) * 16;
            short *nxtK  = smK  + nxt * (16*K_STRIDE);
            short *nxtVt = smVt + nxt * (128*V_STRIDE);
            for (int it = 0; it < 16; it++) {
                int e = tid + it * 128;
                int r = e >> 7;
                int d = e & 127;
                int kvi = kv_base_n + r;
                float vk = (kvi < N) ? K[(long)kvi*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
                float vv = (kvi < N) ? V[(long)kvi*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d] : 0.f;
                unsigned int bk; __builtin_memcpy(&bk, &vk, 4);
                unsigned int bv; __builtin_memcpy(&bv, &vv, 4);
                nxtK[r*K_STRIDE + d]  = (short)((bk + 0x7fffU + ((bk >> 16) & 1U)) >> 16);
                nxtVt[d*V_STRIDE + r] = (short)((bv + 0x7fffU + ((bv >> 16) & 1U)) >> 16);
            }
        }
        int kv_base = kv * 16;
        float8 S = {0,0,0,0,0,0,0,0};
        for (int kt = 0; kt < 8; kt++) {
            int k_off = kt * 16 + half * 8;
            bf16x8 kb;
            for (int i = 0; i < 8; i++) kb[i] = curK[idx*K_STRIDE + k_off + i];
            S = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(q_reg[kt], kb, S);
        }
        float row_max[8];
        for (int i = 0; i < 8; i++) {
            float s = S[i] * (scale * 1.4426950408889634f);
            int kvi_col = kv_base + idx;
            if (kvi_col >= N || (causal && kvi_col > wq0 + half*8 + i)) s = -1e30f;
            S[i] = s;
            float m = s;
            m = fmaxf(m, __shfl_xor(m, 1));
            m = fmaxf(m, __shfl_xor(m, 2));
            m = fmaxf(m, __shfl_xor(m, 4));
            m = fmaxf(m, __shfl_xor(m, 8));
            row_max[i] = m;
        }
        float alpha[8];
        for (int i = 0; i < 8; i++) {
            float m_new = fmaxf(m_i[i], row_max[i]);
            alpha[i] = __builtin_amdgcn_exp2f(m_i[i] - m_new);
            float p = __builtin_amdgcn_exp2f(S[i] - m_new);
            S[i] = p;
            float rs = p;
            rs += __shfl_xor(rs, 8);
            rs += __shfl_xor(rs, 4);
            rs += __shfl_xor(rs, 2);
            rs += __shfl_xor(rs, 1);
            l_i[i] = fmaf(l_i[i], alpha[i], rs);
            m_i[i] = m_new;
        }
        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
        for (int t = 0; t < 8; t++)
            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];
        for (int i = 0; i < 8; i++) {
            int row = half*8 + i;
            float pv = S[i];
            unsigned int b; __builtin_memcpy(&b, &pv, 4);
            myP[row*16 + idx] = (short)((b + 0x7fffU + ((b >> 16) & 1U)) >> 16);
        }
        __builtin_amdgcn_s_waitcnt(0);
        bf16x8 pa;
        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half*8 + i];
        for (int t = 0; t < 8; t++) {
            int hd_base = t * 16;
            bf16x8 vb;
            for (int i = 0; i < 8; i++) vb[i] = curVt[(hd_base + idx)*V_STRIDE + half*8 + i];
            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(pa, vb, *Os[t]);
        }
        __syncthreads();
    }
    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};
    float inv_l[8];
    for (int i = 0; i < 8; i++)
        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;
    for (int t = 0; t < 8; t++) {
        int col = t*16 + idx;
        for (int i = 0; i < 8; i++) {
            int qi = wq0 + half*8 + i;
            if (qi < N)
                out[(long)qi*dim + h*128 + col] = (*Os[t])[i] * inv_l[i];
        }
    }
}
#endif


}
// SPDX-License-Identifier: MIT
// Bounded online softmax, 128 query rows x 64 keys. Transposed vector LDS slots
// keep WMMA fragments contiguous; Q remains in registers throughout the loop.
#include <hip/hip_runtime.h>
typedef float va_f8 __attribute__((ext_vector_type(8)));
typedef short va_b8 __attribute__((ext_vector_type(8)));
typedef _Float16 va_h8 __attribute__((ext_vector_type(8)));
template <bool BF> struct va_type;
template <> struct va_type<true> {
    using scalar = short;
    using vector = va_b8;
};
template <> struct va_type<false> {
    using scalar = _Float16;
    using vector = va_h8;
};
template <bool BF> __device__ __forceinline__ typename va_type<BF>::scalar va_cast(float v) {
    if constexpr (BF) {
        unsigned u = __float_as_uint(v);
        if ((u & 0x7f800000u) != 0x7f800000u)
            u += 0x7fff + ((u >> 16) & 1);
        return short(u >> 16);
    } else
        return _Float16(v);
}
template <bool BF>
__device__ __forceinline__ va_f8 va_mma(typename va_type<BF>::vector a,
                                        typename va_type<BF>::vector b, va_f8 c) {
    if constexpr (BF)
        return __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a, b, c);
    else
        return __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a, b, c);
}
template <bool BF, int HD, bool BASE2 = false>
__device__ __forceinline__ void va_attention(float *out, const float *q, const float *k,
                                             const float *v, int rows, int heads, float scale,
                                             int kv_heads, int causal) {
    if constexpr (BASE2)
        scale *= 1.4426950408889634f;
    using element = typename va_type<BF>::scalar;
    using fragment = typename va_type<BF>::vector;
    constexpr int BK = 64, WAVES = 8, BQ = WAVES * 16;
    int tid = threadIdx.x, lane = tid & 31, wave = tid >> 5, half = lane >> 4, col = lane & 15;
    int head = blockIdx.x, q0 = blockIdx.y * BQ + wave * 16, kh = head / (heads / kv_heads);
    __shared__ fragment keys[(HD / 8) * BK];
    __shared__ element values[HD * (BK + 4)];
    __shared__ element probabilities[WAVES * 16 * (BK + 4)];
    element *prob = probabilities + wave * 16 * (BK + 4);
    fragment qr[HD / 16];
#pragma unroll
    for (int a = 0; a < HD / 16; a++) {
#pragma unroll
        for (int j = 0; j < 8; j++) {
            int row = q0 + col, d = a * 16 + half * 8 + j;
            qr[a][j] = va_cast<BF>(row < rows ? q[((long)row * heads + head) * HD + d] : 0.f);
        }
    }
    va_f8 acc[HD / 16];
#pragma unroll
    for (int a = 0; a < HD / 16; a++)
        acc[a] = va_f8{};
    float maximum[8], denominator[8];
#pragma unroll
    for (int j = 0; j < 8; j++) {
        maximum[j] = -1e30f;
        denominator[j] = 0.f;
    }
    for (int base = 0; base < rows; base += BK) {
        for (int i = tid; i < BK * (HD / 8); i += 256) {
            int r = i / (HD / 8), d = (i % (HD / 8)) * 8, row = base + r;
            fragment key;
#pragma unroll
            for (int j = 0; j < 8; j++) {
                long at = ((long)row * kv_heads + kh) * HD + d + j;
                key[j] = va_cast<BF>(row < rows ? k[at] : 0.f);
                values[(d + j) * (BK + 4) + r] = va_cast<BF>(row < rows ? v[at] : 0.f);
            }
            keys[(d / 8) * BK + r] = key;
        }
        __syncthreads();
        va_f8 score[BK / 16];
#pragma unroll
        for (int b = 0; b < BK / 16; b++)
            score[b] = va_f8{};
#pragma unroll
        for (int a = 0; a < HD / 16; a++) {
#pragma unroll
            for (int b = 0; b < BK / 16; b++)
                score[b] = va_mma<BF>(qr[a], keys[(a * 2 + half) * BK + b * 16 + col], score[b]);
        }
        float alpha[8];
#pragma unroll
        for (int j = 0; j < 8; j++) {
            float mx = -1e30f;
#pragma unroll
            for (int b = 0; b < BK / 16; b++) {
                int row = base + b * 16 + col;
                float s = score[b][j] * scale;
                if (row >= rows || (causal && row > q0 + half * 8 + j))
                    s = -1e30f;
                score[b][j] = s;
                mx = fmaxf(mx, s);
            }
            mx = fmaxf(mx, __shfl_xor(mx, 1));
            mx = fmaxf(mx, __shfl_xor(mx, 2));
            mx = fmaxf(mx, __shfl_xor(mx, 4));
            mx = fmaxf(mx, __shfl_xor(mx, 8));
            float next = fmaxf(maximum[j], mx);
            alpha[j] =
                BASE2 ? __builtin_amdgcn_exp2f(maximum[j] - next) : __expf(maximum[j] - next);
            float sum = 0;
#pragma unroll
            for (int b = 0; b < BK / 16; b++) {
                int row = base + b * 16 + col;
                float p = (row >= rows || (causal && row > q0 + half * 8 + j))
                              ? 0.f
                              : (BASE2 ? __builtin_amdgcn_exp2f(score[b][j] - next)
                                       : __expf(score[b][j] - next));
                sum += p;
                prob[(half * 8 + j) * (BK + 4) + b * 16 + col] = va_cast<BF>(p);
            }
            if constexpr (BASE2) {
                // Match the reference online denominator: reduce each key tile
                // from widest shuffle to narrowest before its fused rescaling.
                sum += __shfl_xor(sum, 8);
                sum += __shfl_xor(sum, 4);
                sum += __shfl_xor(sum, 2);
                sum += __shfl_xor(sum, 1);
                denominator[j] = fmaf(denominator[j], alpha[j], sum);
            } else {
                denominator[j] = denominator[j] * alpha[j] + sum;
            }
            maximum[j] = next;
        }
#pragma unroll
        for (int a = 0; a < HD / 16; a++) {
#pragma unroll
            for (int j = 0; j < 8; j++)
                acc[a][j] *= alpha[j];
        }
        __syncthreads();
#pragma unroll
        for (int b = 0; b < BK / 16; b++) {
            fragment p;
#pragma unroll
            for (int j = 0; j < 8; j++)
                p[j] = prob[col * (BK + 4) + b * 16 + half * 8 + j];
#pragma unroll
            for (int a = 0; a < HD / 16; a++) {
                fragment value;
#pragma unroll
                for (int j = 0; j < 8; j++)
                    value[j] = values[(a * 16 + col) * (BK + 4) + b * 16 + half * 8 + j];
                acc[a] = va_mma<BF>(p, value, acc[a]);
            }
        }
        __syncthreads();
    }
#pragma unroll
    for (int j = 0; j < 8; j++) {
        float sum = denominator[j];
        if constexpr (!BASE2) {
            sum += __shfl_xor(sum, 1);
            sum += __shfl_xor(sum, 2);
            sum += __shfl_xor(sum, 4);
            sum += __shfl_xor(sum, 8);
        }
        int row = q0 + half * 8 + j;
#pragma unroll
        for (int a = 0; a < HD / 16; a++)
            if (row < rows)
                out[((long)row * heads + head) * HD + a * 16 + col] =
                    sum > 0 ? (BASE2 ? acc[a][j] * (1.f / sum) : acc[a][j] / sum) : 0.f;
    }
}
#define VA_WRAPPER(name, bf, hd)                                                                   \
    extern "C" __global__ __launch_bounds__(256, 1) void name(                                     \
        float *o, const float *q, const float *k, const float *v, int n, int h, int d, float s,    \
        int kh, int causal) {                                                                      \
        (void)d;                                                                                   \
        va_attention<bf, hd>(o, q, k, v, n, h, s, kh, causal);                                     \
    }
VA_WRAPPER(video_attention_tile_bf16, true, 128)
VA_WRAPPER(video_attention_tile_bf16_64, true, 64)
VA_WRAPPER(video_attention_tile_f16, false, 128)
VA_WRAPPER(video_attention_tile_f16_64, false, 64)
#undef VA_WRAPPER

// H3 uses the base-2 path; keep Hunyuan and FP16 arithmetic unchanged.
extern "C" __global__ __launch_bounds__(256, 1) void video_attention_tile_bf16_exp2(
    float *o, const float *q, const float *k, const float *v, int n, int h, int d, float s, int kh,
    int causal) {
    (void)d;
    va_attention<true, 128, true>(o, q, k, v, n, h, s, kh, causal);
}
// SPDX-License-Identifier: MIT
// WMMA implementation of the pinned FlexAttention forward schedule.
// Unlike the normal tile, QK is transposed so each lane owns 32 consecutive
// score registers for one query, matching the reference's row reduction.
extern "C" __global__ __launch_bounds__(256, 1) void video_attention_flex_f16(
    float *out, const float *q, const float *k, const float *v, int rows, int heads,
    int dim, float scale, int kv_heads, int causal) {
    (void)dim;
    constexpr int HD = 128, BK = 64;
    int tid = threadIdx.x, lane = tid & 31, wave = tid >> 5;
    int half_lane = lane >> 4, col = lane & 15;
    int head = blockIdx.x, q0 = blockIdx.y * 128 + wave * 16;
    int kh = head / (heads / kv_heads);
    __shared__ va_h8 keys[16 * BK];
    __shared__ _Float16 values[HD * (BK + 4)];
    __shared__ _Float16 probabilities[8 * 16 * (BK + 4)];
    auto *prob = probabilities + wave * 16 * (BK + 4);
    va_h8 qr[8];
    va_f8 acc[8];
#pragma unroll
    for (int a = 0; a < 8; ++a) {
        acc[a] = va_f8{};
#pragma unroll
        for (int j = 0; j < 8; ++j) {
            int row = q0 + col, d = a * 16 + half_lane * 8 + j;
            qr[a][j] = _Float16(row < rows ? q[((long)row * heads + head) * HD + d] : 0.f);
        }
    }
    float maximum = -__builtin_inff(), denominator = 0.f;
    for (int base = 0; base < rows; base += BK) {
        for (int i = tid; i < BK * 16; i += 256) {
            int r = i / 16, d = (i % 16) * 8, row = base + r;
            va_h8 key;
#pragma unroll
            for (int j = 0; j < 8; ++j) {
                long at = ((long)row * kv_heads + kh) * HD + d + j;
                key[j] = _Float16(row < rows ? k[at] : 0.f);
                values[(d + j) * (BK + 4) + r] = _Float16(row < rows ? v[at] : 0.f);
            }
            keys[(d / 8) * BK + r] = key;
        }
        __syncthreads();
        va_f8 scores[4];
#pragma unroll
        for (int b = 0; b < 4; ++b)
            scores[b] = va_f8{};
#pragma unroll
        for (int a = 0; a < 8; ++a) {
#pragma unroll
            for (int b = 0; b < 4; ++b)
                scores[b] = va_mma<false>(keys[(a * 2 + half_lane) * BK + b * 16 + col],
                                         qr[a], scores[b]);
        }
        float next = maximum;
#pragma unroll
        for (int b = 0; b < 4; ++b) {
#pragma unroll
            for (int j = 0; j < 8; ++j) {
                int key_row = base + b * 16 + half_lane * 8 + j;
                float score = scores[b][j] * scale;
                score *= 1.4426950408889634f;
                if (key_row >= rows || (causal && key_row > q0 + col))
                    score = -__builtin_inff();
                scores[b][j] = score;
                next = fmaxf(next, score);
            }
        }
        next = fmaxf(next, __shfl_xor(next, 16));
        float alpha = __builtin_amdgcn_exp2f(maximum - next);
        float sum = 0.f;
#pragma unroll
        for (int b = 0; b < 4; ++b) {
#pragma unroll
            for (int j = 0; j < 8; ++j) {
                float p = __builtin_amdgcn_exp2f(scores[b][j] - next);
                sum += p;
                prob[col * (BK + 4) + b * 16 + half_lane * 8 + j] = _Float16(p);
            }
        }
        sum += __shfl_xor(sum, 16);
        denominator = fmaf(denominator, alpha, sum);
        maximum = next;
#pragma unroll
        for (int a = 0; a < 8; ++a) {
#pragma unroll
            for (int j = 0; j < 8; ++j)
                acc[a][j] *= __shfl(alpha, half_lane * 8 + j);
        }
        __syncthreads();
#pragma unroll
        for (int b = 0; b < 4; ++b) {
            va_h8 p;
#pragma unroll
            for (int j = 0; j < 8; ++j)
                p[j] = prob[col * (BK + 4) + b * 16 + half_lane * 8 + j];
#pragma unroll
            for (int a = 0; a < 8; ++a) {
                va_h8 value;
#pragma unroll
                for (int j = 0; j < 8; ++j)
                    value[j] = values[(a * 16 + col) * (BK + 4) + b * 16 + half_lane * 8 + j];
                acc[a] = va_mma<false>(p, value, acc[a]);
            }
        }
        __syncthreads();
    }
#pragma unroll
    for (int j = 0; j < 8; ++j) {
        int row = q0 + half_lane * 8 + j;
        float sum = __shfl(denominator, half_lane * 8 + j);
#pragma unroll
        for (int a = 0; a < 8; ++a)
            if (row < rows)
                out[((long)row * heads + head) * HD + a * 16 + col] =
                    sum > 0.f ? acc[a][j] / sum : 0.f;
    }
}
)HIP";
}
