"""Generate private HIP kernels from repository-owned WMMA attention.
The shared source remains unchanged. Output is a host C++ HIPRTC source header.
"""
import ast
import os
from pathlib import Path
import re
import sys
root = Path(__file__).resolve().parents[2]
s = (root / 'rdna4/qimg/hip_qimg_kernels.h').read_text()
s = s.split('/* ---- flash_attn_sa_wmma_pq_f32:', 1)[1].split('/* ---- flash_attn_sa_wmma_sp_f32:', 1)[0]
body = ''.join(ast.literal_eval(m.group(1)) for line in s.splitlines()
               if (m := re.match(r'\s*("(?:[^"\\]|\\.)*")', line)))
body = body.replace('int N, int n_heads, int head_dim)', 'int N, int n_heads, int head_dim, float scale)')
body = body.replace('    float scale = rsqrtf(128.f);\n', '')
# Stable online softmax uses the hardware exponential approximation. Inputs
# are nonpositive after subtracting the maximum; BF16/FP16 probability rounding
# dominates its error. GPU tests compare against double-precision CPU softmax.
body = body.replace('expf(', '__expf(')
body = body.replace('flash_attn_sa_wmma_pq_f32', 'flash_attn_sa_wmma_f32')
# Cooperatively load adjacent head dimensions, keeping global reads coalesced.
body = body.replace('tid * 16 + it', 'tid + it * 128')
# FP16 path retains Hunyuan's activation precision; BF16 uses nearest-even.
f16 = body.replace('flash_attn_sa_wmma_f32','video_attention_f16')
f16 = f16.replace('short','_Float16').replace('bf16x8','half8').replace('_bf16_w32_gfx12','_f16_w32_gfx12')
f16 = re.sub(r'unsigned int (\w+); memcpy\(&\1, &(\w+), 4\);', r'float \1 = \2;', f16)
f16 = re.sub(r'\(_Float16\)\((\w+) >> 16\)', r'(_Float16)\1', f16)
bf16 = body.replace('flash_attn_sa_wmma_f32','video_attention_bf16')
bf16 = re.sub(r'\(short\)\((\w+) >> 16\)', r'(short)((\1 + 0x7fffU + ((\1 >> 16) & 1U)) >> 16)', bf16)
bf16 = bf16.replace('float scale)', 'float scale, int kv_heads, int causal)')
bf16 = bf16.replace('K[(long)kvi*dim + h*128 + d]','K[(long)kvi*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d]')
bf16 = bf16.replace('V[(long)kvi*dim + h*128 + d]','V[(long)kvi*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d]')
bf16 = bf16.replace('K[(long)r*dim + h*128 + d]','K[(long)r*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d]')
bf16 = bf16.replace('V[(long)r*dim + h*128 + d]','V[(long)r*kv_heads*128 + (h/(n_heads/kv_heads))*128 + d]')
bf16 = bf16.replace('if (kvi_col >= N) s = -1e30f;', 'if (kvi_col >= N || (causal && kvi_col > wq0 + half*8 + i)) s = -1e30f;')
small = bf16.replace('video_attention_bf16','video_attention_bf16_64')
small = small.replace('128','64').replace('e >> 7','e >> 6').replace('e & 127','e & 63')
small = small.replace('lane * 64 + it','lane * 32 + it').replace('it < 64','it < 32')
small = small.replace('tid * 16 + it','tid * 8 + it').replace('it < 16','it < 8')
small = small.replace('tid + it * 64', 'tid + it * 128')
small = small.replace('kt < 8','kt < 4')
small = re.sub(r'\bt < 8', 't < 4', small)
# AOTriton 0.11.2b uses a base-2 softmax. Keep a separate BF16 variant
# so H3 can match its arithmetic without changing Hunyuan/FP16 execution.
base2 = bf16.replace('video_attention_bf16', 'video_attention_bf16_exp2')
base2 = base2.replace('__expf(', '__builtin_amdgcn_exp2f(')
base2 = base2.replace('float s = S[i] * scale;',
                      'float s = S[i] * (scale * 1.4426950408889634f);')
# Triton's row sum reduces from the widest shuffle to the narrowest, and
# fuses the online denominator rescaling. Both affect BF16 tie boundaries.
base2 = base2.replace('rs += __shfl_xor(rs, 1);\n'
                      '            rs += __shfl_xor(rs, 2);\n'
                      '            rs += __shfl_xor(rs, 4);\n'
                      '            rs += __shfl_xor(rs, 8);',
                      'rs += __shfl_xor(rs, 8);\n'
                      '            rs += __shfl_xor(rs, 4);\n'
                      '            rs += __shfl_xor(rs, 2);\n'
                      '            rs += __shfl_xor(rs, 1);')
base2 = base2.replace('l_i[i] = l_i[i] * alpha[i] + rs;',
                      'l_i[i] = fmaf(l_i[i], alpha[i], rs);')

# Common conversion helpers and compact WMMA matrix kernels.
gemm = (Path(__file__).parent/'gemm.hip').read_text()
precision = (Path(__file__).parent/'precision.hip').read_text()
attention = '#include <hip/hip_runtime.h>\nextern "C" {\n'+(f16+bf16+small+base2).replace('memcpy(', '__builtin_memcpy(')+'\n}\n'
attention += (Path(__file__).parent/'attention.hip').read_text()
attention += (Path(__file__).parent/'flex_attention.hip').read_text()
out = Path(sys.argv[1]);out.parent.mkdir(parents=True,exist_ok=True)
stage = out.with_name(out.name + f'.{os.getpid()}.partial')
try:
    stage.write_text('// Generated by make_kernels.py; SPDX-License-Identifier: MIT\n#pragma once\nnamespace video_rocm {\ninline const char *gemm_source=R"HIP('+gemm+')HIP";\ninline const char *precision_source=R"HIP('+precision+')HIP";\ninline const char *attention_source=R"HIP('+attention+')HIP";\n}\n')
    stage.replace(out)
finally:
    stage.unlink(missing_ok=True)
