/* Native editing primitives. Host-side joint_layout.h validates every map.
 * Kept separate during bring-up; not yet selected by the denoiser runner. */
static const char *q21_edit_src =
"extern \"C\" {\n"
"__device__ float edit_rb(float x){unsigned u=__float_as_uint(x);return __uint_as_float((u+0x7fff+((u>>16)&1))&0xffff0000);}\n"
"__global__ void edit_scatter(float*y,const float*text,const float*image,const int*ti,const int*ii,int N,int D){\n"
" int z=blockIdx.x*blockDim.x+threadIdx.x;if(z>=N*D)return;int t=z/D,d=z%D;\n"
" y[z]=ii[t]>=0?image[ii[t]*D+d]:text[ti[t]*D+d];\n"
"}\n"
"__global__ void edit_qk_rope(float*q,float*k,const float*qw,const float*kw,const int*pos,int N,int H){\n"
" int t=blockIdx.x,h=blockIdx.y,j=threadIdx.x,D=H*128,base=t*D+h*128;\n"
" __shared__ float sq[128],sk[128];float x=q[base+j],y=k[base+j];sq[j]=x*x;sk[j]=y*y;__syncthreads();\n"
" for(int s=64;s;s>>=1){if(j<s){sq[j]+=sq[j+s];sk[j]+=sk[j+s];}__syncthreads();}\n"
" float iq=rsqrtf(sq[0]/128.f+1e-6f),ik=rsqrtf(sk[0]/128.f+1e-6f);if(j&1)return;\n"
" int axis=j<16?0:(j<72?1:2),off=j<16?0:(j<72?16:72),dim=axis==0?16:56;\n"
" float angle=pos[t*3+axis]*exp2f(-log2f(10000.f)*(float)(j-off)/(float)dim),c=cosf(angle),s=sinf(angle);\n"
" float a=edit_rb(edit_rb(q[base+j]*iq)*qw[j]),b=edit_rb(edit_rb(q[base+j+1]*iq)*qw[j+1]);\n"
" float e=edit_rb(edit_rb(k[base+j]*ik)*kw[j]),f=edit_rb(edit_rb(k[base+j+1]*ik)*kw[j+1]);\n"
" q[base+j]=edit_rb(a*c-b*s);q[base+j+1]=edit_rb(a*s+b*c);\n"
" k[base+j]=edit_rb(e*c-f*s);k[base+j+1]=edit_rb(e*s+f*c);\n"
"}\n"
"__global__ void edit_attention(float*y,const float*q,const float*k,const float*v,const int*ids,int N,int H){\n"
" int h=blockIdx.x,t=blockIdx.y,l=threadIdx.x,D=H*128;float qr[4],out[4]={0,0,0,0};\n"
" for(int e=0;e<4;e++)qr[e]=q[t*D+h*128+l*4+e];float mx=-1e30f;\n"
" for(int s=0;s<N;s++){if(s>t && !(ids[t]>=0 && ids[t]==ids[s]))continue;float dot=0;\n"
"  for(int e=0;e<4;e++)dot+=qr[e]*k[s*D+h*128+l*4+e];\n"
"  for(int d=16;d;d>>=1)dot+=__shfl_xor_sync(0xffffffff,dot,d);mx=fmaxf(mx,dot*0.08838834764831845f);}\n"
" float sum=0;for(int s=0;s<N;s++){if(s>t && !(ids[t]>=0 && ids[t]==ids[s]))continue;float dot=0;\n"
"  for(int e=0;e<4;e++)dot+=qr[e]*k[s*D+h*128+l*4+e];\n"
"  for(int d=16;d;d>>=1)dot+=__shfl_xor_sync(0xffffffff,dot,d);float p=expf(dot*0.08838834764831845f-mx);sum+=p;\n"
"  for(int e=0;e<4;e++)out[e]+=p*v[s*D+h*128+l*4+e];}\n"
" for(int e=0;e<4;e++)y[t*D+h*128+l*4+e]=edit_rb(out[e]/sum);\n"
"}\n"
"}\n";
