/* Qwen3-VL text-only, batch-one kernels. All three MRoPE coordinates are
 * identical for text, so interleaving reduces to ordinary split-half RoPE.
 * Float storage represents BF16 values; explicitly round framework ops. */
static const char *q21_text_src =
"extern \"C\" {\n"
"__device__ float rb(float x) { unsigned u=__float_as_uint(x); return __uint_as_float((u+0x7fff+((u>>16)&1))&0xffff0000); }\n"
"__global__ void text_rms(float* y,const float* x,const float* w,int D) {\n"
"  int t=blockIdx.x,j=threadIdx.x; __shared__ float s[256]; float sum=0;\n"
"  for(int d=j;d<D;d+=256) { float v=x[t*D+d]; sum+=v*v; }\n"
"  s[j]=sum; __syncthreads(); for(int k=128;k;k>>=1) { if(j<k)s[j]+=s[j+k]; __syncthreads(); }\n"
"  float inv=rsqrtf(s[0]/D+1e-6f);\n"
"  for(int d=j;d<D;d+=256)y[t*D+d]=rb(rb(x[t*D+d]*inv)*w[d]);\n"
"}\n"
"__global__ void text_rms128(float* y,const float* x,const float* w,int D) {\n"
"  int t=blockIdx.x,j=threadIdx.x; __shared__ float s[32]; int b=t*128+j*4;\n"
"  float v0=x[b],v1=x[b+1],v2=x[b+2],v3=x[b+3];\n"
"  s[j]=((v0*v0+v1*v1)+v2*v2)+v3*v3; __syncthreads();\n"
"  for(int k=16;k;k>>=1) { if(j<k)s[j]+=s[j+k]; __syncthreads(); }\n"
"  float inv=rsqrtf(s[0]/128.f+1e-6f);\n"
"  y[b]=rb(rb(v0*inv)*w[j*4]); y[b+1]=rb(rb(v1*inv)*w[j*4+1]);\n"
"  y[b+2]=rb(rb(v2*inv)*w[j*4+2]); y[b+3]=rb(rb(v3*inv)*w[j*4+3]);\n"
"}\n"
"__global__ void text_rms4(float* y,const float* x,const float* w,int D) {\n"
"  int t=blockIdx.x,j=threadIdx.x; __shared__ float s[256]; float sum=0;\n"
"  for(int b=j*4;b<D;b+=1024) { float v=x[t*D+b]; sum+=v*v;\n"
"    v=x[t*D+b+1];sum+=v*v;v=x[t*D+b+2];sum+=v*v;v=x[t*D+b+3];sum+=v*v; }\n"
"  s[j]=sum; __syncthreads(); for(int k=128;k;k>>=1) { if(j<k)s[j]+=s[j+k]; __syncthreads(); }\n"
"  float inv=rsqrtf(s[0]/D+1e-6f);\n"
"  for(int d=j;d<D;d+=256)y[t*D+d]=rb(rb(x[t*D+d]*inv)*w[d]);\n"
"}\n"
"__global__ void text_rope(float* x,int H) {\n"
"  int t=blockIdx.x,h=blockIdx.y,j=threadIdx.x; if(j>=64)return;\n"
"  int a=(t*H+h)*128+j,b=a+64; float v=x[a],w=x[b];\n"
"  float inv=1.f/powf(5000000.f,(float)(2*j)/128.f),angle=t*inv;\n"
"  float c=rb(cosf(angle)),s=rb(sinf(angle));\n"
"  x[a]=rb(rb(v*c)-rb(w*s)); x[b]=rb(rb(w*c)+rb(v*s));\n"
"}\n"
"__global__ void text_rope_table(float* x,const float* table,int H) {\n"
"  int t=blockIdx.x,h=blockIdx.y,j=threadIdx.x; if(j>=64)return;\n"
"  int a=(t*H+h)*128+j,b=a+64; float v=x[a],w=x[b];\n"
"  float c=table[(t*128+j)*2],s=table[(t*128+j)*2+1];\n"
"  x[a]=rb(rb(v*c)-rb(w*s)); x[b]=rb(rb(w*c)+rb(v*s));\n"
"}\n"
"__global__ void text_add(float* x,const float* y,int n) {\n"
"  int i=blockIdx.x*blockDim.x+threadIdx.x; if(i<n)x[i]=rb(x[i]+y[i]);\n"
"}\n"
"__global__ void text_add_visual(float* x,const float* y,const int* rows,int n,int D) {\n"
"  int i=blockIdx.x*blockDim.x+threadIdx.x; if(i<n)x[(size_t)rows[i/D]*D+i%D]=rb(x[(size_t)rows[i/D]*D+i%D]+y[i]);\n"
"}\n"
"__global__ void text_mul_silu(float* y,const float* a,const float* b,int n) {\n"
"  int i=blockIdx.x*blockDim.x+threadIdx.x; if(i>=n)return;\n"
"  double v=(double)a[i]; float z=rb((float)(v/(1.0+exp(-v))));\n"
"  y[i]=rb(z*b[i]);\n"
"}\n"
/* One warp per (query, head). Two-pass softmax with F32 accumulation,
 * causal keys and GQA mapping (32 query heads / 8 KV heads). */
"__global__ void text_attn(float* o,const float* q,const float* k,const float* v,int N) {\n"
"  int h=blockIdx.x,t=blockIdx.y,l=threadIdx.x,kh=h/4;\n"
"  float qr[4],acc[4]={0,0,0,0}; for(int e=0;e<4;e++)qr[e]=q[t*4096+h*128+l+32*e];\n"
"  float mx=-1e30f;\n"
"  for(int s=0;s<=t;s++) { float dot=0;\n"
"    for(int e=0;e<4;e++)dot+=qr[e]*k[s*1024+kh*128+l+32*e];\n"
"    for(int d=16;d;d>>=1)dot+=__shfl_xor_sync(0xffffffff,dot,d);\n"
"    mx=fmaxf(mx,dot*0.08838834764831845f);\n"
"  }\n"
"  float den=0;\n"
"  for(int s=0;s<=t;s++) { float dot=0;\n"
"    for(int e=0;e<4;e++)dot+=qr[e]*k[s*1024+kh*128+l+32*e];\n"
"    for(int d=16;d;d>>=1)dot+=__shfl_xor_sync(0xffffffff,dot,d);\n"
"    float p=expf(dot*0.08838834764831845f-mx); den+=p; p=rb(p);\n"
"    for(int e=0;e<4;e++)acc[e]+=p*v[s*1024+kh*128+l+32*e];\n"
"  }\n"
"  for(int e=0;e<4;e++)o[t*4096+h*128+l+32*e]=rb(acc[e]/den);\n"
"}\n"
"}\n";
