/*
 * cuda_paint_vae_kernels.h - F32 NVRTC kernels for SD-2.1 paint VAE
 * (Hunyuan3D-2.1 hy3dpaint stock diffusers AutoencoderKL).
 *
 * Topology shared with the Flux2 VAE — the kernels are functionally the
 * same. Kept here as a self-contained header so the paint VAE runner does
 * not have to depend on the Flux2 runner translation unit.
 */
#ifndef CUDA_PAINT_VAE_KERNELS_H
#define CUDA_PAINT_VAE_KERNELS_H

static const char cuda_paint_vae_kernels_src[] =
"extern \"C\" {\n"
"\n"
"/* GroupNorm. Optional fused SiLU. CHW layout, one block per group. */\n"
"#define PVAE_GN_THREADS 128\n"
"__global__ void vae_groupnorm_f32(float *__restrict__ out,\n"
"    const float *__restrict__ in, const float *__restrict__ gamma,\n"
"    const float *__restrict__ beta, int C, int spatial,\n"
"    int num_groups, int do_silu) {\n"
"    int g = blockIdx.x;\n"
"    if (g >= num_groups) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    int group_size = C / num_groups;\n"
"    int c0 = g * group_size;\n"
"    int n = group_size * spatial;\n"
"    float sum = 0.f;\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int ch = c0 + i / spatial;\n"
"        int s = i - (i / spatial) * spatial;\n"
"        sum += in[(long)ch * spatial + s];\n"
"    }\n"
"    sdata[tid] = sum;\n"
"    __syncthreads();\n"
"    for (int r = blockDim.x >> 1; r > 0; r >>= 1) {\n"
"        if (tid < r) sdata[tid] += sdata[tid + r];\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = sdata[0] / (float)n;\n"
"    __syncthreads();\n"
"    float var = 0.f;\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int ch = c0 + i / spatial;\n"
"        int s = i - (i / spatial) * spatial;\n"
"        float d = in[(long)ch * spatial + s] - mean;\n"
"        var += d * d;\n"
"    }\n"
"    sdata[tid] = var;\n"
"    __syncthreads();\n"
"    for (int r = blockDim.x >> 1; r > 0; r >>= 1) {\n"
"        if (tid < r) sdata[tid] += sdata[tid + r];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv = rsqrtf(sdata[0] / (float)n + 1e-6f);\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int ch = c0 + i / spatial;\n"
"        int s = i - (i / spatial) * spatial;\n"
"        float v = (in[(long)ch * spatial + s] - mean) * inv;\n"
"        v = v * gamma[ch] + beta[ch];\n"
"        if (do_silu) v = v / (1.f + expf(-v));\n"
"        out[(long)ch * spatial + s] = v;\n"
"    }\n"
"}\n"
"\n"
"/* Generic conv2d on CHW with same-padding (caller chooses pad). */\n"
"__global__ void vae_conv2d_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co, int kh, int kw, int pad) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * h * w;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / (h * w);\n"
"    int rem = idx - oc * (h * w);\n"
"    int oy = rem / w, ox = rem - oy * w;\n"
"    float sum = bias ? bias[oc] : 0.f;\n"
"    for (int ic = 0; ic < ci; ic++) {\n"
"        for (int fy = 0; fy < kh; fy++) {\n"
"            int iy = oy + fy - pad;\n"
"            if (iy < 0 || iy >= h) continue;\n"
"            for (int fx = 0; fx < kw; fx++) {\n"
"                int ix = ox + fx - pad;\n"
"                if (ix < 0 || ix >= w) continue;\n"
"                sum += inp[(long)ic * h * w + iy * w + ix] *\n"
"                       weight[(((long)oc * ci + ic) * kh + fy) * kw + fx];\n"
"            }\n"
"        }\n"
"    }\n"
"    out[idx] = sum;\n"
"}\n"
"\n"
"/* Diffusers-style stride-2 downsample conv2d. Asymmetric pad: only the\n"
" * right and bottom edges are padded with zero (F.pad(x,(0,1,0,1))) before\n"
" * the 3x3 conv runs with stride=2. Input H,W must be even; output is\n"
" * H/2, W/2. */\n"
"__global__ void vae_conv2d_down_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co) {\n"
"    int oh = h >> 1, ow = w >> 1;\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * oh * ow;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / (oh * ow);\n"
"    int rem = idx - oc * (oh * ow);\n"
"    int oy = rem / ow, ox = rem - oy * ow;\n"
"    float sum = bias ? bias[oc] : 0.f;\n"
"    for (int ic = 0; ic < ci; ic++) {\n"
"        for (int fy = 0; fy < 3; fy++) {\n"
"            int iy = oy * 2 + fy;\n"
"            if (iy >= h) continue;\n"
"            for (int fx = 0; fx < 3; fx++) {\n"
"                int ix = ox * 2 + fx;\n"
"                if (ix >= w) continue;\n"
"                sum += inp[((long)ic * h + iy) * w + ix] *\n"
"                       weight[(((long)oc * ci + ic) * 3 + fy) * 3 + fx];\n"
"            }\n"
"        }\n"
"    }\n"
"    out[idx] = sum;\n"
"}\n"
"\n"
"/* Nearest-neighbour 2x upsample. CHW. */\n"
"__global__ void vae_upsample2x_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oH = H * 2, oW = W * 2;\n"
"    int total = C * oH * oW;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (oH * oW);\n"
"    int rem = idx - c * (oH * oW);\n"
"    int oy = rem / oW, ox = rem - oy * oW;\n"
"    int iy = oy >> 1, ix = ox >> 1;\n"
"    out[idx] = inp[(long)c * H * W + iy * W + ix];\n"
"}\n"
"\n"
"/* Element-wise residual add: out = a + b. */\n"
"__global__ void vae_add_f32(float *out, const float *a, const float *b, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) out[i] = a[i] + b[i];\n"
"}\n"
"\n"
"/* CHW -> NC transpose: in[C, N] -> out[N, C]. */\n"
"__global__ void vae_chw_to_nc_f32(float *out, const float *in, int C, int N) {\n"
"    int n = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int c = blockIdx.y;\n"
"    if (n >= N || c >= C) return;\n"
"    out[(long)n * C + c] = in[(long)c * N + n];\n"
"}\n"
"\n"
"/* NC -> CHW transpose: in[N, C] -> out[C, N]. */\n"
"__global__ void vae_nc_to_chw_f32(float *out, const float *in, int C, int N) {\n"
"    int n = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int c = blockIdx.y;\n"
"    if (n >= N || c >= C) return;\n"
"    out[(long)c * N + n] = in[(long)n * C + c];\n"
"}\n"
"\n"
"/* Single-head VAE attention (mid-block self-attn). Q/K/V format [N, dim].\n"
" * One warp per query row; flash-attention online softmax. dim must be a\n"
" * multiple of 32*EPT (EPT=16 covers dim<=512). */\n"
"#define PVAE_ATT_WARPS 4\n"
"#define PVAE_ATT_BKV   8\n"
"#define PVAE_ATT_EPT  16\n"
"__global__ void vae_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V, int N, int dim, float scale) {\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem;\n"
"    float *smV = smem + PVAE_ATT_BKV * dim;\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int lane = threadIdx.x & 31;\n"
"    int qi = blockIdx.x * PVAE_ATT_WARPS + warp_id;\n"
"    float qr[PVAE_ATT_EPT];\n"
"    if (qi < N) {\n"
"        for (int e = 0; e < PVAE_ATT_EPT; e++)\n"
"            qr[e] = Q[(long)qi * dim + lane * PVAE_ATT_EPT + e];\n"
"    }\n"
"    float m_prev = -1e30f, l_prev = 0.f;\n"
"    float o[PVAE_ATT_EPT];\n"
"    for (int e = 0; e < PVAE_ATT_EPT; e++) o[e] = 0.f;\n"
"    int n_tiles = (N + PVAE_ATT_BKV - 1) / PVAE_ATT_BKV;\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int kv_base = t * PVAE_ATT_BKV;\n"
"        int tid = threadIdx.x, nt = blockDim.x;\n"
"        int total = PVAE_ATT_BKV * dim;\n"
"        for (int idx = tid; idx < total; idx += nt) {\n"
"            int row = idx / dim, col = idx - row * dim;\n"
"            int gi = kv_base + row;\n"
"            smK[idx] = (gi < N) ? K[(long)gi * dim + col] : 0.f;\n"
"            smV[idx] = (gi < N) ? V[(long)gi * dim + col] : 0.f;\n"
"        }\n"
"        __syncthreads();\n"
"        if (qi < N) {\n"
"            for (int ki = 0; ki < PVAE_ATT_BKV; ki++) {\n"
"                if (kv_base + ki >= N) continue;\n"
"                float dot = 0.f;\n"
"                for (int e = 0; e < PVAE_ATT_EPT; e++)\n"
"                    dot += qr[e] * smK[ki * dim + lane * PVAE_ATT_EPT + e];\n"
"                for (int m = 16; m > 0; m >>= 1)\n"
"                    dot += __shfl_xor_sync(0xFFFFFFFF, dot, m);\n"
"                dot *= scale;\n"
"                float m_new = fmaxf(m_prev, dot);\n"
"                float ep = expf(m_prev - m_new);\n"
"                float ec = expf(dot - m_new);\n"
"                float l_new = l_prev * ep + ec;\n"
"                for (int e = 0; e < PVAE_ATT_EPT; e++)\n"
"                    o[e] = o[e] * ep + ec * smV[ki * dim + lane * PVAE_ATT_EPT + e];\n"
"                m_prev = m_new; l_prev = l_new;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (qi < N && l_prev > 0.f) {\n"
"        float inv = 1.f / l_prev;\n"
"        for (int e = 0; e < PVAE_ATT_EPT; e++)\n"
"            out[(long)qi * dim + lane * PVAE_ATT_EPT + e] = o[e] * inv;\n"
"    }\n"
"}\n"
"\n"
"} /* extern C */\n"
;

#endif /* CUDA_PAINT_VAE_KERNELS_H */
