/*
 * cuda_paint_raster_kernels.h - Native CUDA triangle rasterization for
 * Hunyuan3D-2.1 texture generation. Replacement for the upstream
 * custom_rasterizer PyTorch extension (torch::Tensor-free).
 *
 * Kernels (NVRTC-compiled source string):
 *
 *   rasterize_faces_f32(V, F, zbuffer, num_faces, W, H)
 *     One thread per face; for each pixel in the triangle's clip-space bbox,
 *     packs (depth_quantized, face_id+1) into an int64 and atomicMin's it
 *     into zbuffer. Uses the same encoding as upstream:
 *
 *       depth_q = int(z * (2<<17))
 *       token   = (int64)depth_q * INT32_MAX + (int64)(face_id + 1)
 *
 *     V is [num_vertices, 4] homogeneous clip-space. F is [num_faces, 3] i32.
 *
 *   resolve_bary_f32(V, F, zbuffer, findices, bary, num_faces, W, H)
 *     One thread per pixel; extracts face_id from zbuffer (mod INT32_MAX),
 *     recomputes 2D barycentric at the pixel center, then perspective-
 *     corrects by dividing each coord by the corresponding vertex w and
 *     renormalizing. Writes:
 *       findices[H,W]        int32 (1-indexed; 0 = empty)
 *       bary    [H,W,3]      float32 perspective-corrected barycentric
 *
 * SPDX-License-Identifier: MIT (wrapper); rasterization core derived from
 * Tencent Hunyuan3D-2.1 custom_rasterizer (non-commercial use only).
 */
#ifndef CUDA_PAINT_RASTER_KERNELS_H
#define CUDA_PAINT_RASTER_KERNELS_H

static const char cuda_paint_raster_kernels_src[] =
"#define MAXINT32 2147483647\n"
"\n"
"extern \"C\" {\n"
"\n"
"__device__ inline float signed_area2(const float *a, const float *b, const float *c) {\n"
"    return ((c[0] - a[0]) * (b[1] - a[1]) - (b[0] - a[0]) * (c[1] - a[1]));\n"
"}\n"
"\n"
"__device__ inline void barycentric2d(const float *a, const float *b, const float *c,\n"
"                                      const float *p, float *out) {\n"
"    float area  = signed_area2(a, b, c);\n"
"    if (area == 0.f) { out[0]=-1.f; out[1]=-1.f; out[2]=-1.f; return; }\n"
"    float beta  = signed_area2(a, p, c) / area;\n"
"    float gamma = signed_area2(a, b, p) / area;\n"
"    out[0] = 1.0f - beta - gamma;\n"
"    out[1] = beta;\n"
"    out[2] = gamma;\n"
"}\n"
"\n"
"__device__ inline bool bary_in_bounds(const float *b) {\n"
"    return b[0] >= 0.f && b[0] <= 1.f &&\n"
"           b[1] >= 0.f && b[1] <= 1.f &&\n"
"           b[2] >= 0.f && b[2] <= 1.f;\n"
"}\n"
"\n"
"/* Main rasterization. One thread per face. Writes packed\n"
" * (depth_quant, face_id+1) tokens into int64 zbuffer via atomicMin. */\n"
"__global__ void rasterize_faces_f32(const float *V, const int *F,\n"
"                                      unsigned long long *zbuffer,\n"
"                                      int num_faces, int width, int height) {\n"
"    int f = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (f >= num_faces) return;\n"
"\n"
"    const float *vt0p = V + (size_t)F[f*3+0] * 4;\n"
"    const float *vt1p = V + (size_t)F[f*3+1] * 4;\n"
"    const float *vt2p = V + (size_t)F[f*3+2] * 4;\n"
"\n"
"    float vt0[3] = { (vt0p[0] / vt0p[3] * 0.5f + 0.5f) * (width - 1) + 0.5f,\n"
"                     (0.5f + 0.5f * vt0p[1] / vt0p[3]) * (height - 1) + 0.5f,\n"
"                     vt0p[2] / vt0p[3] * 0.49999f + 0.5f };\n"
"    float vt1[3] = { (vt1p[0] / vt1p[3] * 0.5f + 0.5f) * (width - 1) + 0.5f,\n"
"                     (0.5f + 0.5f * vt1p[1] / vt1p[3]) * (height - 1) + 0.5f,\n"
"                     vt1p[2] / vt1p[3] * 0.49999f + 0.5f };\n"
"    float vt2[3] = { (vt2p[0] / vt2p[3] * 0.5f + 0.5f) * (width - 1) + 0.5f,\n"
"                     (0.5f + 0.5f * vt2p[1] / vt2p[3]) * (height - 1) + 0.5f,\n"
"                     vt2p[2] / vt2p[3] * 0.49999f + 0.5f };\n"
"\n"
"    float xmin = fminf(vt0[0], fminf(vt1[0], vt2[0]));\n"
"    float xmax = fmaxf(vt0[0], fmaxf(vt1[0], vt2[0]));\n"
"    float ymin = fminf(vt0[1], fminf(vt1[1], vt2[1]));\n"
"    float ymax = fmaxf(vt0[1], fmaxf(vt1[1], vt2[1]));\n"
"\n"
"    int ix0 = (int)fmaxf(0.f, floorf(xmin));\n"
"    int ix1 = (int)fminf((float)(width-1), floorf(xmax + 1.f));\n"
"    int iy0 = (int)fmaxf(0.f, floorf(ymin));\n"
"    int iy1 = (int)fminf((float)(height-1), floorf(ymax + 1.f));\n"
"\n"
"    for (int py = iy0; py <= iy1; py++) {\n"
"        for (int px = ix0; px <= ix1; px++) {\n"
"            float p[2] = { (float)px + 0.5f, (float)py + 0.5f };\n"
"            float bary[3];\n"
"            barycentric2d(vt0, vt1, vt2, p, bary);\n"
"            if (!bary_in_bounds(bary)) continue;\n"
"\n"
"            float depth = bary[0]*vt0[2] + bary[1]*vt1[2] + bary[2]*vt2[2];\n"
"            /* Reject depths behind the near plane (matches upstream that\n"
"             * truncates at depth < 0). */\n"
"            if (depth < 0.f) continue;\n"
"            int depth_q = (int)(depth * (float)(2 << 17));\n"
"            unsigned long long token =\n"
"                (unsigned long long)depth_q * (unsigned long long)MAXINT32\n"
"                + (unsigned long long)(f + 1);\n"
"            atomicMin(&zbuffer[py * width + px], token);\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* Resolve per-pixel barycentric from the packed zbuffer. Writes\n"
" *   findices [H*W]   int32  (1-indexed; 0 means empty)\n"
" *   bary     [H*W*3] float  (perspective-corrected) */\n"
"__global__ void resolve_bary_f32(const float *V, const int *F,\n"
"                                   const unsigned long long *zbuffer,\n"
"                                   int *findices, float *bary_out,\n"
"                                   int width, int height) {\n"
"    int pix = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = width * height;\n"
"    if (pix >= total) return;\n"
"\n"
"    unsigned long long zv = zbuffer[pix];\n"
"    long long f = (long long)(zv % (unsigned long long)MAXINT32);\n"
"    if (f == (long long)(MAXINT32 - 1) || f == 0) {\n"
"        findices[pix] = 0;\n"
"        bary_out[pix*3+0] = 0.f;\n"
"        bary_out[pix*3+1] = 0.f;\n"
"        bary_out[pix*3+2] = 0.f;\n"
"        return;\n"
"    }\n"
"    findices[pix] = (int)f;\n"
"    f -= 1;\n"
"\n"
"    const float *vt0p = V + (size_t)F[f*3+0] * 4;\n"
"    const float *vt1p = V + (size_t)F[f*3+1] * 4;\n"
"    const float *vt2p = V + (size_t)F[f*3+2] * 4;\n"
"\n"
"    float vt0[2] = { (vt0p[0] / vt0p[3] * 0.5f + 0.5f) * (width - 1) + 0.5f,\n"
"                     (0.5f + 0.5f * vt0p[1] / vt0p[3]) * (height - 1) + 0.5f };\n"
"    float vt1[2] = { (vt1p[0] / vt1p[3] * 0.5f + 0.5f) * (width - 1) + 0.5f,\n"
"                     (0.5f + 0.5f * vt1p[1] / vt1p[3]) * (height - 1) + 0.5f };\n"
"    float vt2[2] = { (vt2p[0] / vt2p[3] * 0.5f + 0.5f) * (width - 1) + 0.5f,\n"
"                     (0.5f + 0.5f * vt2p[1] / vt2p[3]) * (height - 1) + 0.5f };\n"
"    float p[2] = { (float)(pix % width) + 0.5f, (float)(pix / width) + 0.5f };\n"
"    float bary[3];\n"
"    barycentric2d(vt0, vt1, vt2, p, bary);\n"
"    /* Perspective-correct by dividing each barycentric coord by the\n"
"     * corresponding vertex w and renormalising so the three sum to 1. */\n"
"    bary[0] /= vt0p[3];\n"
"    bary[1] /= vt1p[3];\n"
"    bary[2] /= vt2p[3];\n"
"    float w = 1.f / (bary[0] + bary[1] + bary[2]);\n"
"    bary_out[pix*3+0] = bary[0] * w;\n"
"    bary_out[pix*3+1] = bary[1] * w;\n"
"    bary_out[pix*3+2] = bary[2] * w;\n"
"}\n"
"\n"
"/* Per-pixel barycentric interpolation of a per-vertex attribute.\n"
" *   attr      [num_vertices, C]  float32, vertex-indexed\n"
" *   F         [num_faces, 3]     int32\n"
" *   findices  [H*W]              int32, 1-indexed (0 = empty)\n"
" *   bary      [H*W*3]            float32 (perspective-corrected)\n"
" *   bg        [C]                float32 per-channel background colour\n"
" *   out       [H*W*C]            float32 interpolated per pixel; empty\n"
" *                                pixels get copied from bg. */\n"
"__global__ void interpolate_attr_f32(const float *attr, const int *F,\n"
"                                       const int *findices, const float *bary,\n"
"                                       const float *bg, float *out,\n"
"                                       int width, int height, int C) {\n"
"    int pix = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = width * height;\n"
"    if (pix >= total) return;\n"
"    int f = findices[pix];\n"
"    if (f <= 0) {\n"
"        for (int c = 0; c < C; c++) out[pix * C + c] = bg[c];\n"
"        return;\n"
"    }\n"
"    f -= 1;\n"
"    int i0 = F[f*3+0], i1 = F[f*3+1], i2 = F[f*3+2];\n"
"    float b0 = bary[pix*3+0], b1 = bary[pix*3+1], b2 = bary[pix*3+2];\n"
"    for (int c = 0; c < C; c++) {\n"
"        float a0 = attr[i0 * C + c];\n"
"        float a1 = attr[i1 * C + c];\n"
"        float a2 = attr[i2 * C + c];\n"
"        out[pix * C + c] = b0 * a0 + b1 * a1 + b2 * a2;\n"
"    }\n"
"}\n"
"\n"
"/* Per-pixel lookup of a per-face attribute (face-shader path).\n"
" *   face_attr [num_faces, C]  float32, one value per triangle\n"
" *   findices  [H*W]           int32, 1-indexed (0 = empty)\n"
" *   bg        [C]             float32 background (used for empty pixels)\n"
" *   out       [H*W*C]         float32 */\n"
"__global__ void lookup_face_attr_f32(const float *face_attr,\n"
"                                       const int *findices,\n"
"                                       const float *bg, float *out,\n"
"                                       int width, int height, int C) {\n"
"    int pix = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = width * height;\n"
"    if (pix >= total) return;\n"
"    int f = findices[pix];\n"
"    if (f <= 0) {\n"
"        for (int c = 0; c < C; c++) out[pix * C + c] = bg[c];\n"
"        return;\n"
"    }\n"
"    f -= 1;\n"
"    for (int c = 0; c < C; c++) out[pix * C + c] = face_attr[f * C + c];\n"
"}\n"
"\n"
"/* Compute one (normalized) face normal per triangle.\n"
" *   V         [num_verts, 3]   world-space vertex positions\n"
" *   F         [num_faces, 3]   int32 vertex indices\n"
" *   out       [num_faces, 3]   float32 normalized cross-product */\n"
"__global__ void compute_face_normals_f32(const float *V, const int *F,\n"
"                                          float *out, int num_faces) {\n"
"    int f = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (f >= num_faces) return;\n"
"    int i0 = F[f*3+0], i1 = F[f*3+1], i2 = F[f*3+2];\n"
"    float p0x=V[i0*3+0], p0y=V[i0*3+1], p0z=V[i0*3+2];\n"
"    float p1x=V[i1*3+0], p1y=V[i1*3+1], p1z=V[i1*3+2];\n"
"    float p2x=V[i2*3+0], p2y=V[i2*3+1], p2z=V[i2*3+2];\n"
"    float e1x=p1x-p0x, e1y=p1y-p0y, e1z=p1z-p0z;\n"
"    float e2x=p2x-p0x, e2y=p2y-p0y, e2z=p2z-p0z;\n"
"    float nx = e1y*e2z - e1z*e2y;\n"
"    float ny = e1z*e2x - e1x*e2z;\n"
"    float nz = e1x*e2y - e1y*e2x;\n"
"    float l = sqrtf(nx*nx + ny*ny + nz*nz);\n"
"    if (l > 1e-20f) { nx/=l; ny/=l; nz/=l; }\n"
"    out[f*3+0] = nx; out[f*3+1] = ny; out[f*3+2] = nz;\n"
"}\n"
"\n"
"/* Back-projection bake (single view).\n"
" *\n"
" * Ports the 'back_sample' path of hy3dpaint MeshRender.back_project.\n"
" * One thread per UV texel. For each covered texel:\n"
" *   1. read the texel's world-space position from tex_pos\n"
" *   2. transform through world->camera matrix (w2c) to camera space\n"
" *   3. apply projection (ortho: x *= proj00, y *= proj11, z passes\n"
" *      through) to produce v_proj in [-1, 1] NDC + camera-space z\n"
" *   4. reject if outside [-1, 1]^2\n"
" *   5. compute image pixel center and bilinear weights\n"
" *   6. reject if abs(v_z - sampled_depth[int_pix]) >= depth_thres\n"
" *      (matches upstream 3e-3 default) or the view's visible/cos mask is 0\n"
" *   7. bilinear sample RGB + read cos weight\n"
" *   8. write bilinear-sampled RGB to out_tex[texel, :] and the view's\n"
" *      cos weight to out_cos[texel].\n"
" *\n"
" * Inputs:\n"
" *   tex_pos     [Htex*Wtex*3]   world-space xyz per UV texel\n"
" *   tex_cov     [Htex*Wtex]     int32 coverage (0 = texel not on any face)\n"
" *   image       [Himg*Wimg*C]   RGB (or RGBA) float\n"
" *   depth_img   [Himg*Wimg]     camera-space z per image pixel\n"
" *   visible_img [Himg*Wimg]     float mask (>0 if covered)\n"
" *   cos_img     [Himg*Wimg]     cos(view angle) per image pixel\n"
" *   w2c         [16]            4x4 world->camera, column-major\n"
" *   proj00, proj11              projection diagonal (ortho: 2/w, 2/h)\n"
" *   depth_thres                 upstream uses 3e-3\n"
" * Outputs (accumulated per view, caller zeros before the first call):\n"
" *   out_tex     [Htex*Wtex*C]   sampled view color\n"
" *   out_cos     [Htex*Wtex]     view cos weight (0 for unsampled texels) */\n"
"__global__ void back_project_sample_f32(\n"
"    const float *tex_pos, const int *tex_cov,\n"
"    const float *image, const float *depth_img,\n"
"    const float *visible_img, const float *cos_img,\n"
"    const float *w2c, float proj00, float proj11, float depth_thres,\n"
"    int Htex, int Wtex, int Himg, int Wimg, int C,\n"
"    float *out_tex, float *out_cos)\n"
"{\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = Htex * Wtex;\n"
"    if (idx >= total) return;\n"
"    if (tex_cov[idx] == 0) { out_cos[idx] = 0.f; return; }\n"
"\n"
"    float x = tex_pos[idx*3+0];\n"
"    float y = tex_pos[idx*3+1];\n"
"    float z = tex_pos[idx*3+2];\n"
"    /* w2c is column-major 4x4 applied to a row vector */\n"
"    float cx = w2c[0]*x + w2c[4]*y + w2c[8] *z + w2c[12];\n"
"    float cy = w2c[1]*x + w2c[5]*y + w2c[9] *z + w2c[13];\n"
"    float cz = w2c[2]*x + w2c[6]*y + w2c[10]*z + w2c[14];\n"
"\n"
"    float px = cx * proj00;   /* in [-1, 1] for ortho */\n"
"    float py = cy * proj11;\n"
"    float pz = cz;            /* pass-through depth */\n"
"\n"
"    if (px < -1.f || px > 1.f || py < -1.f || py > 1.f) {\n"
"        out_cos[idx] = 0.f;\n"
"        return;\n"
"    }\n"
"\n"
"    /* Fractional pixel coords in [0, Wimg) x [0, Himg) */\n"
"    float fx = (px * 0.5f + 0.5f) * (float)Wimg;\n"
"    float fy = (py * 0.5f + 0.5f) * (float)Himg;\n"
"    int   ix = (int)fx;\n"
"    int   iy = (int)fy;\n"
"    float wx = fx - (float)ix;\n"
"    float wy = fy - (float)iy;\n"
"    if (ix < 0) ix = 0; if (ix >= Wimg) ix = Wimg - 1;\n"
"    if (iy < 0) iy = 0; if (iy >= Himg) iy = Himg - 1;\n"
"    int ix1 = ix + 1; if (ix1 >= Wimg) ix1 = Wimg - 1;\n"
"    int iy1 = iy + 1; if (iy1 >= Himg) iy1 = Himg - 1;\n"
"\n"
"    int i00 = iy  * Wimg + ix;\n"
"    int i01 = iy  * Wimg + ix1;\n"
"    int i10 = iy1 * Wimg + ix;\n"
"    int i11 = iy1 * Wimg + ix1;\n"
"\n"
"    /* Depth + visibility test on the nearest pixel, matching upstream. */\n"
"    float d = depth_img[i00];\n"
"    if (visible_img[i00] <= 0.f) { out_cos[idx] = 0.f; return; }\n"
"    if (fabsf(pz - d) >= depth_thres) { out_cos[idx] = 0.f; return; }\n"
"\n"
"    float cos_w = cos_img[i00];\n"
"    if (cos_w <= 0.f) { out_cos[idx] = 0.f; return; }\n"
"\n"
"    for (int c = 0; c < C; c++) {\n"
"        float c00 = image[i00 * C + c];\n"
"        float c01 = image[i01 * C + c];\n"
"        float c10 = image[i10 * C + c];\n"
"        float c11 = image[i11 * C + c];\n"
"        float v = (c00 * (1.f - wx) + c01 * wx) * (1.f - wy)\n"
"                + (c10 * (1.f - wx) + c11 * wx) * wy;\n"
"        out_tex[idx * C + c] = v;\n"
"    }\n"
"    out_cos[idx] = cos_w;\n"
"}\n"
"\n"
"} /* extern C */\n"
;

#endif /* CUDA_PAINT_RASTER_KERNELS_H */
