/*
 * cuda_paint_unet_kernels.h - F32 NVRTC kernels for SD-2.1 paint UNet
 * (Hunyuan3D-2.1 hy3dpaint stock UNet2DConditionModel skeleton).
 *
 * Phase 3: stock attention only (no MDA / RA / MA / DINO custom processors).
 * Self-contained header so the paint UNet runner needs no external kernel
 * file beyond the common cuew/runner helpers.
 */
#ifndef CUDA_PAINT_UNET_KERNELS_H
#define CUDA_PAINT_UNET_KERNELS_H

static const char cuda_paint_unet_kernels_src[] =
"extern \"C\" {\n"
"\n"
"/* Diffusers get_timestep_embedding: dim=320, flip_sin_to_cos=True,\n"
" * downscale_freq_shift=0, max_period=10000. Output [B, dim].\n"
" * One block per batch element, one thread per output channel. */\n"
"__global__ void unet_timestep_embed_f32(float *__restrict__ out,\n"
"    const long long *__restrict__ timesteps, int B, int dim) {\n"
"    int b = blockIdx.x;\n"
"    int c = threadIdx.x + blockIdx.y * blockDim.x;\n"
"    if (b >= B || c >= dim) return;\n"
"    int half = dim >> 1;\n"
"    float t = (float)timesteps[b];\n"
"    /* Output is [cos(ang_0..half-1), sin(ang_0..half-1)] (flip_sin_to_cos). */\n"
"    int idx = c < half ? c : c - half;\n"
"    float exponent = -logf(10000.f) * (float)idx / (float)half;\n"
"    float ang = t * expf(exponent);\n"
"    out[b * dim + c] = (c < half) ? cosf(ang) : sinf(ang);\n"
"}\n"
"\n"
"/* y = x @ Wt + b. x:[M,K] W:[N,K] b:[N] y:[M,N]. One thread per (m,n). */\n"
"__global__ void unet_linear_f32(float *__restrict__ y,\n"
"    const float *__restrict__ x, const float *__restrict__ W,\n"
"    const float *__restrict__ b, int M, int K, int N) {\n"
"    int m = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int n = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (m >= M || n >= N) return;\n"
"    float s = b ? b[n] : 0.f;\n"
"    for (int k = 0; k < K; k++) s += x[m*K + k] * W[n*K + k];\n"
"    y[m*N + n] = s;\n"
"}\n"
"\n"
"/* SiLU in-place. */\n"
"__global__ void unet_silu_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) { float v = x[i]; x[i] = v / (1.f + expf(-v)); }\n"
"}\n"
"\n"
"/* Generic conv2d on CHW with same-padding (3x3 pad=1 typical). */\n"
"__global__ void unet_conv2d_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias,\n"
"    int ci, int h, int w, int co, int kh, int kw, int pad) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * h * w;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / (h * w);\n"
"    int rem = idx - oc * (h * w);\n"
"    int oy = rem / w, ox = rem - oy * w;\n"
"    float sum = bias ? bias[oc] : 0.f;\n"
"    for (int ic = 0; ic < ci; ic++) {\n"
"        for (int fy = 0; fy < kh; fy++) {\n"
"            int iy = oy + fy - pad;\n"
"            if (iy < 0 || iy >= h) continue;\n"
"            for (int fx = 0; fx < kw; fx++) {\n"
"                int ix = ox + fx - pad;\n"
"                if (ix < 0 || ix >= w) continue;\n"
"                sum += inp[(long)ic * h * w + iy * w + ix] *\n"
"                       weight[(((long)oc * ci + ic) * kh + fy) * kw + fx];\n"
"            }\n"
"        }\n"
"    }\n"
"    out[idx] = sum;\n"
"}\n"
"\n"
"/* im2col for 3x3, pad=1, stride=1. Input [ci,h,w] -> xcol [hw, ci*9].\n"
" * Layout: xcol row index = oy*w+ox, columns = (ic*9 + fy*3 + fx). One thread\n"
" * per (xcol_row, xcol_col). Out-of-bounds taps emit 0. */\n"
"__global__ void unet_im2col_3x3_p1_f32(float *__restrict__ xcol,\n"
"    const float *__restrict__ inp, int ci, int h, int w) {\n"
"    int hw = h * w;\n"
"    int row = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int col = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int K = ci * 9;\n"
"    if (row >= hw || col >= K) return;\n"
"    int oy = row / w, ox = row - oy * w;\n"
"    int ic = col / 9;\n"
"    int kk = col - ic * 9;\n"
"    int fy = kk / 3, fx = kk - fy * 3;\n"
"    int iy = oy + fy - 1, ix = ox + fx - 1;\n"
"    float v = 0.f;\n"
"    if ((unsigned)iy < (unsigned)h && (unsigned)ix < (unsigned)w)\n"
"        v = inp[(long)ic * hw + iy * w + ix];\n"
"    xcol[(long)row * K + col] = v;\n"
"}\n"
"\n"
"/* im2col for 3x3, pad=1, stride=2. Input [ci,h,w] -> xcol [oh*ow, ci*9],\n"
" * where oh=h/2, ow=w/2. Same column layout as the stride=1 variant. */\n"
"__global__ void unet_im2col_3x3_p1_s2_f32(float *__restrict__ xcol,\n"
"    const float *__restrict__ inp, int ci, int h, int w) {\n"
"    int oh = h >> 1, ow = w >> 1;\n"
"    int ohw = oh * ow;\n"
"    int row = blockIdx.y * blockDim.y + threadIdx.y;\n"
"    int col = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int K = ci * 9;\n"
"    if (row >= ohw || col >= K) return;\n"
"    int oy = row / ow, ox = row - oy * ow;\n"
"    int ic = col / 9;\n"
"    int kk = col - ic * 9;\n"
"    int fy = kk / 3, fx = kk - fy * 3;\n"
"    int iy = oy * 2 + fy - 1, ix = ox * 2 + fx - 1;\n"
"    float v = 0.f;\n"
"    if ((unsigned)iy < (unsigned)h && (unsigned)ix < (unsigned)w)\n"
"        v = inp[((long)ic * h + iy) * w + ix];\n"
"    xcol[(long)row * K + col] = v;\n"
"}\n"
"\n"
"/* Transpose [hw, co] -> [co, h, w] (i.e. add row-major bias-stride flip). */\n"
"__global__ void unet_t_hwc_to_chw_f32(float *__restrict__ out,\n"
"    const float *__restrict__ yt, int co, int hw) {\n"
"    int row = blockIdx.y * blockDim.y + threadIdx.y; /* hw index */\n"
"    int col = blockIdx.x * blockDim.x + threadIdx.x; /* co index */\n"
"    if (row >= hw || col >= co) return;\n"
"    out[(long)col * hw + row] = yt[(long)row * co + col];\n"
"}\n"
"\n"
"\n"
"/* GroupNorm. Optional fused SiLU. CHW layout, one block per group. */\n"
"#define PUNET_GN_THREADS 128\n"
"__global__ void unet_groupnorm_f32(float *__restrict__ out,\n"
"    const float *__restrict__ in, const float *__restrict__ gamma,\n"
"    const float *__restrict__ beta, int C, int spatial,\n"
"    int num_groups, int do_silu, float eps) {\n"
"    int g = blockIdx.x;\n"
"    if (g >= num_groups) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    int group_size = C / num_groups;\n"
"    int c0 = g * group_size;\n"
"    int n = group_size * spatial;\n"
"    float sum = 0.f;\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int ch = c0 + i / spatial;\n"
"        int s = i - (i / spatial) * spatial;\n"
"        sum += in[(long)ch * spatial + s];\n"
"    }\n"
"    sdata[tid] = sum;\n"
"    __syncthreads();\n"
"    for (int r = blockDim.x >> 1; r > 0; r >>= 1) {\n"
"        if (tid < r) sdata[tid] += sdata[tid + r];\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = sdata[0] / (float)n;\n"
"    __syncthreads();\n"
"    float var = 0.f;\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int ch = c0 + i / spatial;\n"
"        int s = i - (i / spatial) * spatial;\n"
"        float d = in[(long)ch * spatial + s] - mean;\n"
"        var += d * d;\n"
"    }\n"
"    sdata[tid] = var;\n"
"    __syncthreads();\n"
"    for (int r = blockDim.x >> 1; r > 0; r >>= 1) {\n"
"        if (tid < r) sdata[tid] += sdata[tid + r];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv = rsqrtf(sdata[0] / (float)n + eps);\n"
"    for (int i = tid; i < n; i += blockDim.x) {\n"
"        int ch = c0 + i / spatial;\n"
"        int s = i - (i / spatial) * spatial;\n"
"        float v = (in[(long)ch * spatial + s] - mean) * inv;\n"
"        v = v * gamma[ch] + beta[ch];\n"
"        if (do_silu) v = v / (1.f + expf(-v));\n"
"        out[(long)ch * spatial + s] = v;\n"
"    }\n"
"}\n"
"\n"
"/* Broadcast-add a per-channel time embedding into a CHW activation map.\n"
" * out[c, s] = a[c, s] + temb[c]. One thread per element. */\n"
"__global__ void unet_add_chan_f32(float *__restrict__ out,\n"
"    const float *__restrict__ a, const float *__restrict__ temb,\n"
"    int C, int spatial) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * spatial;\n"
"    if (idx >= total) return;\n"
"    int c = idx / spatial;\n"
"    out[idx] = a[idx] + temb[c];\n"
"}\n"
"\n"
"/* Element-wise add: out = a + b. */\n"
"__global__ void unet_add_f32(float *out, const float *a, const float *b, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) out[i] = a[i] + b[i];\n"
"}\n"
"\n"
"\n"
"/* LayerNorm. One block per row [N], reduce across C. eps=1e-5. */\n"
"__global__ void unet_layernorm_f32(float *__restrict__ out,\n"
"    const float *__restrict__ in, const float *__restrict__ gamma,\n"
"    const float *__restrict__ beta, int N, int C, float eps) {\n"
"    int row = blockIdx.x; if (row >= N) return;\n"
"    extern __shared__ float sd[];\n"
"    int tid = threadIdx.x;\n"
"    float sum = 0.f;\n"
"    for (int i = tid; i < C; i += blockDim.x) sum += in[(long)row * C + i];\n"
"    sd[tid] = sum; __syncthreads();\n"
"    for (int r = blockDim.x >> 1; r > 0; r >>= 1) {\n"
"        if (tid < r) sd[tid] += sd[tid + r]; __syncthreads();\n"
"    }\n"
"    float mean = sd[0] / (float)C;\n"
"    __syncthreads();\n"
"    float var = 0.f;\n"
"    for (int i = tid; i < C; i += blockDim.x) {\n"
"        float d = in[(long)row * C + i] - mean; var += d * d;\n"
"    }\n"
"    sd[tid] = var; __syncthreads();\n"
"    for (int r = blockDim.x >> 1; r > 0; r >>= 1) {\n"
"        if (tid < r) sd[tid] += sd[tid + r]; __syncthreads();\n"
"    }\n"
"    float inv = rsqrtf(sd[0] / (float)C + eps);\n"
"    for (int i = tid; i < C; i += blockDim.x) {\n"
"        float v = (in[(long)row * C + i] - mean) * inv;\n"
"        out[(long)row * C + i] = v * gamma[i] + beta[i];\n"
"    }\n"
"}\n"
"\n"
"/* CHW -> [N=H*W, C] layout flip used by Transformer2DModel. */\n"
"__global__ void unet_chw_to_nc_f32(float *out, const float *in, int C, int N) {\n"
"    int n = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int c = blockIdx.y;\n"
"    if (n >= N || c >= C) return;\n"
"    out[(long)n * C + c] = in[(long)c * N + n];\n"
"}\n"
"\n"
"/* [N, C] -> CHW. */\n"
"__global__ void unet_nc_to_chw_f32(float *out, const float *in, int C, int N) {\n"
"    int n = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int c = blockIdx.y;\n"
"    if (n >= N || c >= C) return;\n"
"    out[(long)c * N + n] = in[(long)n * C + c];\n"
"}\n"
"\n"
"/* Multi-head scaled dot-product attention with online softmax.\n"
" * Q : [B, N, heads*head_dim]\n"
" * K : [B, M, heads*head_dim]\n"
" * V : [B, M, heads*head_dim]\n"
" * out: [B, N, heads*head_dim]\n"
" * head_dim must be <= PUNET_HEAD_DIM_MAX (currently 64).\n"
" * One thread per (batch, head, query_row); grid: (B*heads, ceil(N/T)). */\n"
"#define PUNET_HEAD_DIM_MAX 64\n"
"__global__ void unet_mha_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int B, int N, int M, int heads, int head_dim, float scale) {\n"
"    int bh = blockIdx.x;\n"
"    int b = bh / heads, h = bh % heads;\n"
"    int qi = blockIdx.y * blockDim.x + threadIdx.x;\n"
"    if (b >= B || qi >= N) return;\n"
"    int C = heads * head_dim;\n"
"    long q_off = ((long)b * N + qi) * C + (long)h * head_dim;\n"
"    float qr[PUNET_HEAD_DIM_MAX];\n"
"    for (int i = 0; i < head_dim; i++) qr[i] = Q[q_off + i];\n"
"    float m_prev = -1e30f, l_prev = 0.f;\n"
"    float o[PUNET_HEAD_DIM_MAX];\n"
"    for (int i = 0; i < head_dim; i++) o[i] = 0.f;\n"
"    long kv_base = (long)b * M * C + (long)h * head_dim;\n"
"    for (int j = 0; j < M; j++) {\n"
"        const float *kj = K + kv_base + (long)j * C;\n"
"        const float *vj = V + kv_base + (long)j * C;\n"
"        float dot = 0.f;\n"
"        for (int i = 0; i < head_dim; i++) dot += qr[i] * kj[i];\n"
"        dot *= scale;\n"
"        float m_new = fmaxf(m_prev, dot);\n"
"        float ep = expf(m_prev - m_new), ec = expf(dot - m_new);\n"
"        float l_new = l_prev * ep + ec;\n"
"        for (int i = 0; i < head_dim; i++) o[i] = o[i] * ep + ec * vj[i];\n"
"        m_prev = m_new; l_prev = l_new;\n"
"    }\n"
"    float inv = 1.f / l_prev;\n"
"    long o_off = ((long)b * N + qi) * C + (long)h * head_dim;\n"
"    for (int i = 0; i < head_dim; i++) out[o_off + i] = o[i] * inv;\n"
"}\n"
"\n"
"/* GEGLU activation: gh:[N, 2H] -> out:[N, H], out = gh[:,:H] * GELU(gh[:,H:])\n"
" * Exact (erf) GELU. */\n"
"__global__ void unet_geglu_f32(float *out, const float *gh, int N, int H) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * H;\n"
"    if (idx >= total) return;\n"
"    int n = idx / H, h = idx - n * H;\n"
"    float x = gh[(long)n * 2 * H + h];\n"
"    float g = gh[(long)n * 2 * H + H + h];\n"
"    float gel = g * 0.5f * (1.f + erff(g * 0.7071067811865475f));\n"
"    out[idx] = x * gel;\n"
"}\n"
"\n"
"\n"
"/* 3x3 stride-2 conv with symmetric padding (diffusers Downsample2D with\n"
" * downsample_padding=1). Output H/2 x W/2. */\n"
"__global__ void unet_conv2d_stride2_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, const float *__restrict__ weight,\n"
"    const float *__restrict__ bias, int ci, int h, int w, int co) {\n"
"    int oh = h >> 1, ow = w >> 1;\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * oh * ow;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / (oh * ow);\n"
"    int rem = idx - oc * (oh * ow);\n"
"    int oy = rem / ow, ox = rem - oy * ow;\n"
"    float sum = bias ? bias[oc] : 0.f;\n"
"    for (int ic = 0; ic < ci; ic++) {\n"
"        for (int fy = 0; fy < 3; fy++) {\n"
"            int iy = oy * 2 + fy - 1;\n"
"            if (iy < 0 || iy >= h) continue;\n"
"            for (int fx = 0; fx < 3; fx++) {\n"
"                int ix = ox * 2 + fx - 1;\n"
"                if (ix < 0 || ix >= w) continue;\n"
"                sum += inp[((long)ic * h + iy) * w + ix] *\n"
"                       weight[(((long)oc * ci + ic) * 3 + fy) * 3 + fx];\n"
"            }\n"
"        }\n"
"    }\n"
"    out[idx] = sum;\n"
"}\n"
"\n"
"/* Nearest-neighbour 2x upsample (CHW). */\n"
"__global__ void unet_upsample2x_f32(float *__restrict__ out,\n"
"    const float *__restrict__ inp, int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int oH = H * 2, oW = W * 2;\n"
"    int total = C * oH * oW;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (oH * oW);\n"
"    int rem = idx - c * (oH * oW);\n"
"    int oy = rem / oW, ox = rem - oy * oW;\n"
"    int iy = oy >> 1, ix = ox >> 1;\n"
"    out[idx] = inp[(long)c * H * W + iy * W + ix];\n"
"}\n"
"\n"
"/* Channel-wise concat of [Ca, H, W] and [Cb, H, W] -> [Ca+Cb, H, W]. */\n"
"__global__ void unet_concat_chan_f32(float *__restrict__ out,\n"
"    const float *__restrict__ a, const float *__restrict__ b,\n"
"    int Ca, int Cb, int spatial) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = (Ca + Cb) * spatial;\n"
"    if (idx >= total) return;\n"
"    int c = idx / spatial, s = idx - c * spatial;\n"
"    out[idx] = (c < Ca) ? a[(long)c * spatial + s]\n"
"                         : b[(long)(c - Ca) * spatial + s];\n"
"}\n"
"\n"
"\n"
"/* In-place 3D RoPE (PoseRoPE) for multi-head Q or K.\n"
" *   in/out : [B, N, heads*head_dim]\n"
" *   cos/sin: [B, N, head_dim]   (broadcast over heads)\n"
" * Rotation pairs (p, p+1) for even p:\n"
" *   out[..p..]   = in[..p..]   * cos[p]   - in[..p+1..] * sin[p]\n"
" *   out[..p+1..] = in[..p+1..] * cos[p+1] + in[..p..]   * sin[p+1]\n"
" * (cos[p]==cos[p+1] because the freq table was built with repeat_interleave(2),\n"
" * but we look up both anyway to stay generic.) One thread per (b, n, h, pair). */\n"
"__global__ void unet_rope_apply_f32(float *__restrict__ out,\n"
"    const float *__restrict__ in, const float *__restrict__ cos_,\n"
"    const float *__restrict__ sin_, int B, int N, int heads, int head_dim) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int half = head_dim >> 1;\n"
"    int total = B * N * heads * half;\n"
"    if (idx >= total) return;\n"
"    int pair = idx % half;\n"
"    int bnh  = idx / half;\n"
"    int bn   = bnh / heads;\n"
"    long base    = (long)bnh * head_dim + (long)pair * 2;\n"
"    long basecos = (long)bn  * head_dim + (long)pair * 2;\n"
"    float x0 = in[base], x1 = in[base + 1];\n"
"    float c0 = cos_[basecos], s0 = sin_[basecos];\n"
"    float c1 = cos_[basecos + 1], s1 = sin_[basecos + 1];\n"
"    out[base]     = x0 * c0 - x1 * s0;\n"
"    out[base + 1] = x1 * c1 + x0 * s1;\n"
"}\n"
"\n"
"/* Build interleaved V_lower / V_upper for the cat-V RefAttn scheme.\n"
" * V_total[m, x] = V_a[m, x] for x in [0, C) else V_m[m, x-C]; reshape into\n"
" * [M, H, 2D]; V_lower = [..., 0:D], V_upper = [..., D:2D]. Each output is\n"
" * [B*M, H*D] = [B*M, C]. Launch with one thread per (b*M*C) element. */\n"
"__global__ void unet_ra_split_v_f32(float *__restrict__ V_lower,\n"
"    float *__restrict__ V_upper, const float *__restrict__ V_a,\n"
"    const float *__restrict__ V_m, int BM, int H, int D) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int C = H * D;\n"
"    int total = BM * C;\n"
"    if (idx >= total) return;\n"
"    int m = idx / C;\n"
"    int hd = idx - m * C;\n"
"    int h = hd / D;\n"
"    int d = hd - h * D;\n"
"    int xL = 2 * h * D + d;\n"
"    int xU = 2 * h * D + D + d;\n"
"    long base = (long)m * C;\n"
"    /* xL/xU range: [0, 2C). xL < C => V_a, else V_m at xL-C. */\n"
"    V_lower[base + hd] = (xL < C) ? V_a[(long)m * C + xL] : V_m[(long)m * C + (xL - C)];\n"
"    V_upper[base + hd] = (xU < C) ? V_a[(long)m * C + xU] : V_m[(long)m * C + (xU - C)];\n"
"}\n"
"} /* extern C */\n"
;

#endif /* CUDA_PAINT_UNET_KERNELS_H */
