/* Native FP8 v7 fused GEMM for paint UNet (PAINT_FP8_V7=1).
 * Source extracted verbatim from cuda/flux2/cuda_flux2_runner.h:2197-2365.
 * Concatenated into the NVRTC build of paint_stage_unet.c.
 *
 * Two variants:
 *   gemm_fp8_v7_fused      -- 4x4 panel swizzle (per_panel_=16). Original.
 *   gemm_fp8_v7_fused_p2   -- 2x2 panel swizzle (per_panel_=4). Halves the
 *                             grid pad-to-multiple from 4 to 2, reducing
 *                             wave-quantization waste on N=640/1280 paint
 *                             UNet shapes. Bit-identical to v7. Default ON
 *                             (PAINT_FP8_V7_P2=0 to disable).
 *
 * Helper kernels (quantize_to_fp8_e4m3, reduce_max_abs_f32) come from the
 * existing cuda_fp8_mma_kernels.h source already in the build. */
#ifndef PAINT_FP8_V7_KERNELS_H_
#define PAINT_FP8_V7_KERNELS_H_

static const char k_paint_fp8_v7_src[] =
"typedef unsigned char fp8_raw;\n"
"extern \"C\" __global__ void gemm_fp8_v7_fused(float *Y,\n"
"                                                const fp8_raw *X,\n"
"                                                const fp8_raw *W,\n"
"                                                const float *bias,\n"
"                                                const float *x_scale_ptr,\n"
"                                                float w_scale,\n"
"                                                int has_bias,\n"
"                                                int accumulate,\n"
"                                                int M, int N, int K) {\n"
"    extern __shared__ __align__(16) unsigned short smem_v7fp8f[];\n"
"    unsigned short *sA0 = smem_v7fp8f;\n"
"    unsigned short *sB0 = smem_v7fp8f + 2048;\n"
"    unsigned short *sA1 = smem_v7fp8f + 6144;\n"
"    unsigned short *sB1 = smem_v7fp8f + 8192;\n"
"    int tid = threadIdx.x;\n"
"    int wid = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int gid  = lane >> 2;\n"
"    int tid4 = lane & 3;\n"
"    int warp_m = wid >> 1;\n"
"    int warp_n = wid & 1;\n"
"    int blk_lin = blockIdx.y * gridDim.x + blockIdx.x;\n"
"    int npx_ = gridDim.x;\n"
"    int npy_ = gridDim.y;\n"
"    int panels_m_ = (npy_ + 3) >> 2;\n"
"    int per_panel_ = 16;\n"
"    int panel_id_ = blk_lin / per_panel_;\n"
"    int in_panel_ = blk_lin - panel_id_ * per_panel_;\n"
"    int panel_m_id_ = panel_id_ - (panel_id_ / panels_m_) * panels_m_;\n"
"    int panel_n_id_ = panel_id_ / panels_m_;\n"
"    int m_in_ = in_panel_ & 3;\n"
"    int n_in_ = in_panel_ >> 2;\n"
"    int tile_m_ = (panel_m_id_ << 2) + m_in_;\n"
"    int tile_n_ = (panel_n_id_ << 2) + n_in_;\n"
"    if (tile_m_ >= npy_ || tile_n_ >= npx_) return;\n"
"    int cta_m  = tile_m_ * 64;\n"
"    int cta_n  = tile_n_ * 128;\n"
"    int wm_row = warp_m * 16;\n"
"    int wn_col = warp_n * 64;\n"
"    if (cta_m >= M) return;\n"
"    float d0[8], d1[8], d2[8], d3[8];\n"
"    #pragma unroll\n"
"    for (int i = 0; i < 8; i++) { d0[i]=0; d1[i]=0; d2[i]=0; d3[i]=0; }\n"
"    int row_a    = tid >> 2;\n"
"    int col_a_b  = (tid & 3) * 8;\n"
"    int col_a_g  = (tid & 3) * 16;\n"
"    int g_row_a  = cta_m + row_a;\n"
"    int sw_a     = (row_a & 3) * 8;\n"
"    int swz_a    = row_a * 32 + (col_a_b ^ sw_a);\n"
"    int row_b0   = tid >> 2;\n"
"    int col_b0_b = (tid & 3) * 8;\n"
"    int col_b0_g = (tid & 3) * 16;\n"
"    int g_row_b0 = cta_n + row_b0;\n"
"    int sw_b0    = (row_b0 & 3) * 8;\n"
"    int swz_b0   = row_b0 * 32 + (col_b0_b ^ sw_b0);\n"
"    int vid_b1   = tid + 256;\n"
"    int row_b1   = vid_b1 >> 2;\n"
"    int col_b1_b = (vid_b1 & 3) * 8;\n"
"    int col_b1_g = (vid_b1 & 3) * 16;\n"
"    int g_row_b1 = cta_n + row_b1;\n"
"    int sw_b1    = (row_b1 & 3) * 8;\n"
"    int swz_b1   = row_b1 * 32 + (col_b1_b ^ sw_b1);\n"
"    {\n"
"        unsigned int dA = __cvta_generic_to_shared(&sA0[swz_a]);\n"
"        if (g_row_a < M) {\n"
"            const fp8_raw *src = &X[(size_t)g_row_a * K + 0 + col_a_g];\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dA), \"l\"(src));\n"
"        } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dA)); }\n"
"        unsigned int dB0 = __cvta_generic_to_shared(&sB0[swz_b0]);\n"
"        if (g_row_b0 < N) {\n"
"            const fp8_raw *src = &W[(size_t)g_row_b0 * K + 0 + col_b0_g];\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB0), \"l\"(src));\n"
"        } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB0)); }\n"
"        unsigned int dB1 = __cvta_generic_to_shared(&sB0[swz_b1]);\n"
"        if (g_row_b1 < N) {\n"
"            const fp8_raw *src = &W[(size_t)g_row_b1 * K + 0 + col_b1_g];\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB1), \"l\"(src));\n"
"        } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB1)); }\n"
"    }\n"
"    asm volatile(\"cp.async.commit_group;\\n\");\n"
"    int num_k = K >> 6;\n"
"    int la_row     = wm_row + (lane & 15);\n"
"    int la_col_off = (lane >> 4) * 8;\n"
"    int la_sw      = (la_row & 3) * 8;\n"
"    int lb_row     = lane & 15;\n"
"    int lb_col_off = (lane >> 4) * 8;\n"
"    for (int ki = 0; ki < num_k; ki++) {\n"
"        int stage = ki & 1;\n"
"        int next_stage = stage ^ 1;\n"
"        int next_k = (ki + 1) << 6;\n"
"        asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        __syncthreads();\n"
"        if (next_k < K) {\n"
"            unsigned short *sA_next = (next_stage == 0) ? sA0 : sA1;\n"
"            unsigned short *sB_next = (next_stage == 0) ? sB0 : sB1;\n"
"            unsigned int dA = __cvta_generic_to_shared(&sA_next[swz_a]);\n"
"            if (g_row_a < M) {\n"
"                const fp8_raw *src = &X[(size_t)g_row_a * K + next_k + col_a_g];\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dA), \"l\"(src));\n"
"            } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dA)); }\n"
"            unsigned int dB0 = __cvta_generic_to_shared(&sB_next[swz_b0]);\n"
"            if (g_row_b0 < N) {\n"
"                const fp8_raw *src = &W[(size_t)g_row_b0 * K + next_k + col_b0_g];\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB0), \"l\"(src));\n"
"            } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB0)); }\n"
"            unsigned int dB1 = __cvta_generic_to_shared(&sB_next[swz_b1]);\n"
"            if (g_row_b1 < N) {\n"
"                const fp8_raw *src = &W[(size_t)g_row_b1 * K + next_k + col_b1_g];\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB1), \"l\"(src));\n"
"            } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB1)); }\n"
"        }\n"
"        asm volatile(\"cp.async.commit_group;\\n\");\n"
"        unsigned short *sAp = (stage == 0) ? sA0 : sA1;\n"
"        unsigned short *sBp = (stage == 0) ? sB0 : sB1;\n"
"        #pragma unroll\n"
"        for (int kg = 0; kg < 2; kg++) {\n"
"            int k_off = kg * 16;\n"
"            int a_off = la_row * 32 + ((k_off + la_col_off) ^ la_sw);\n"
"            unsigned int a0,a1,a2,a3;\n"
"            unsigned int p_a = __cvta_generic_to_shared(&sAp[a_off]);\n"
"            asm volatile(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\\n\"\n"
"                : \"=r\"(a0), \"=r\"(a1), \"=r\"(a2), \"=r\"(a3) : \"r\"(p_a));\n"
"            #pragma unroll\n"
"            for (int s = 0; s < 4; s++) {\n"
"                int sn_base = wn_col + s * 16;\n"
"                int b_brow  = sn_base + lb_row;\n"
"                int b_sw    = (b_brow & 3) * 8;\n"
"                int b_off   = b_brow * 32 + ((k_off + lb_col_off) ^ b_sw);\n"
"                unsigned int b0,b1,b2,b3;\n"
"                unsigned int p_b = __cvta_generic_to_shared(&sBp[b_off]);\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\\n\"\n"
"                    : \"=r\"(b0), \"=r\"(b1), \"=r\"(b2), \"=r\"(b3) : \"r\"(p_b));\n"
"                int nt0 = s * 2 + 0;\n"
"                int nt1 = s * 2 + 1;\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[nt0]), \"=f\"(d1[nt0]), \"=f\"(d2[nt0]), \"=f\"(d3[nt0])\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b2),\n"
"                      \"f\"(d0[nt0]), \"f\"(d1[nt0]), \"f\"(d2[nt0]), \"f\"(d3[nt0])\n"
"                );\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[nt1]), \"=f\"(d1[nt1]), \"=f\"(d2[nt1]), \"=f\"(d3[nt1])\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b1), \"r\"(b3),\n"
"                      \"f\"(d0[nt1]), \"f\"(d1[nt1]), \"f\"(d2[nt1]), \"f\"(d3[nt1])\n"
"                );\n"
"            }\n"
"        }\n"
"    }\n"
"    asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"    float ds = w_scale * x_scale_ptr[0];\n"
"    int yr0 = cta_m + wm_row + gid;\n"
"    int yr1 = cta_m + wm_row + gid + 8;\n"
"    #pragma unroll\n"
"    for (int nt = 0; nt < 8; nt++) {\n"
"        int yc0 = cta_n + wn_col + nt*8 + tid4*2;\n"
"        int yc1 = yc0 + 1;\n"
"        float b0_v = (has_bias && yc0 < N) ? bias[yc0] : 0.0f;\n"
"        float b1_v = (has_bias && yc1 < N) ? bias[yc1] : 0.0f;\n"
"        if (yr0 < M && yc0 < N) { size_t idx = (size_t)yr0 * N + yc0; float v = d0[nt] * ds + b0_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"        if (yr0 < M && yc1 < N) { size_t idx = (size_t)yr0 * N + yc1; float v = d1[nt] * ds + b1_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"        if (yr1 < M && yc0 < N) { size_t idx = (size_t)yr1 * N + yc0; float v = d2[nt] * ds + b0_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"        if (yr1 < M && yc1 < N) { size_t idx = (size_t)yr1 * N + yc1; float v = d3[nt] * ds + b1_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"    }\n"
"}\n"
"extern \"C\" __global__ void gemm_fp8_v7_fused_p2(float *Y,\n"
"                                                const fp8_raw *X,\n"
"                                                const fp8_raw *W,\n"
"                                                const float *bias,\n"
"                                                const float *x_scale_ptr,\n"
"                                                float w_scale,\n"
"                                                int has_bias,\n"
"                                                int accumulate,\n"
"                                                int M, int N, int K) {\n"
"    extern __shared__ __align__(16) unsigned short smem_v7fp8f[];\n"
"    unsigned short *sA0 = smem_v7fp8f;\n"
"    unsigned short *sB0 = smem_v7fp8f + 2048;\n"
"    unsigned short *sA1 = smem_v7fp8f + 6144;\n"
"    unsigned short *sB1 = smem_v7fp8f + 8192;\n"
"    int tid = threadIdx.x;\n"
"    int wid = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int gid  = lane >> 2;\n"
"    int tid4 = lane & 3;\n"
"    int warp_m = wid >> 1;\n"
"    int warp_n = wid & 1;\n"
"    int blk_lin = blockIdx.y * gridDim.x + blockIdx.x;\n"
"    int npx_ = gridDim.x;\n"
"    int npy_ = gridDim.y;\n"
"    int panels_m_ = (npy_ + 1) >> 1;\n"
"    int per_panel_ = 4;\n"
"    int panel_id_ = blk_lin / per_panel_;\n"
"    int in_panel_ = blk_lin - panel_id_ * per_panel_;\n"
"    int panel_m_id_ = panel_id_ - (panel_id_ / panels_m_) * panels_m_;\n"
"    int panel_n_id_ = panel_id_ / panels_m_;\n"
"    int m_in_ = in_panel_ & 1;\n"
"    int n_in_ = in_panel_ >> 1;\n"
"    int tile_m_ = (panel_m_id_ << 1) + m_in_;\n"
"    int tile_n_ = (panel_n_id_ << 1) + n_in_;\n"
"    if (tile_m_ >= npy_ || tile_n_ >= npx_) return;\n"
"    int cta_m  = tile_m_ * 64;\n"
"    int cta_n  = tile_n_ * 128;\n"
"    int wm_row = warp_m * 16;\n"
"    int wn_col = warp_n * 64;\n"
"    if (cta_m >= M) return;\n"
"    float d0[8], d1[8], d2[8], d3[8];\n"
"    #pragma unroll\n"
"    for (int i = 0; i < 8; i++) { d0[i]=0; d1[i]=0; d2[i]=0; d3[i]=0; }\n"
"    int row_a    = tid >> 2;\n"
"    int col_a_b  = (tid & 3) * 8;\n"
"    int col_a_g  = (tid & 3) * 16;\n"
"    int g_row_a  = cta_m + row_a;\n"
"    int sw_a     = (row_a & 3) * 8;\n"
"    int swz_a    = row_a * 32 + (col_a_b ^ sw_a);\n"
"    int row_b0   = tid >> 2;\n"
"    int col_b0_b = (tid & 3) * 8;\n"
"    int col_b0_g = (tid & 3) * 16;\n"
"    int g_row_b0 = cta_n + row_b0;\n"
"    int sw_b0    = (row_b0 & 3) * 8;\n"
"    int swz_b0   = row_b0 * 32 + (col_b0_b ^ sw_b0);\n"
"    int vid_b1   = tid + 256;\n"
"    int row_b1   = vid_b1 >> 2;\n"
"    int col_b1_b = (vid_b1 & 3) * 8;\n"
"    int col_b1_g = (vid_b1 & 3) * 16;\n"
"    int g_row_b1 = cta_n + row_b1;\n"
"    int sw_b1    = (row_b1 & 3) * 8;\n"
"    int swz_b1   = row_b1 * 32 + (col_b1_b ^ sw_b1);\n"
"    {\n"
"        unsigned int dA = __cvta_generic_to_shared(&sA0[swz_a]);\n"
"        if (g_row_a < M) {\n"
"            const fp8_raw *src = &X[(size_t)g_row_a * K + 0 + col_a_g];\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dA), \"l\"(src));\n"
"        } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dA)); }\n"
"        unsigned int dB0 = __cvta_generic_to_shared(&sB0[swz_b0]);\n"
"        if (g_row_b0 < N) {\n"
"            const fp8_raw *src = &W[(size_t)g_row_b0 * K + 0 + col_b0_g];\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB0), \"l\"(src));\n"
"        } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB0)); }\n"
"        unsigned int dB1 = __cvta_generic_to_shared(&sB0[swz_b1]);\n"
"        if (g_row_b1 < N) {\n"
"            const fp8_raw *src = &W[(size_t)g_row_b1 * K + 0 + col_b1_g];\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB1), \"l\"(src));\n"
"        } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB1)); }\n"
"    }\n"
"    asm volatile(\"cp.async.commit_group;\\n\");\n"
"    int num_k = K >> 6;\n"
"    int la_row     = wm_row + (lane & 15);\n"
"    int la_col_off = (lane >> 4) * 8;\n"
"    int la_sw      = (la_row & 3) * 8;\n"
"    int lb_row     = lane & 15;\n"
"    int lb_col_off = (lane >> 4) * 8;\n"
"    for (int ki = 0; ki < num_k; ki++) {\n"
"        int stage = ki & 1;\n"
"        int next_stage = stage ^ 1;\n"
"        int next_k = (ki + 1) << 6;\n"
"        asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        __syncthreads();\n"
"        if (next_k < K) {\n"
"            unsigned short *sA_next = (next_stage == 0) ? sA0 : sA1;\n"
"            unsigned short *sB_next = (next_stage == 0) ? sB0 : sB1;\n"
"            unsigned int dA = __cvta_generic_to_shared(&sA_next[swz_a]);\n"
"            if (g_row_a < M) {\n"
"                const fp8_raw *src = &X[(size_t)g_row_a * K + next_k + col_a_g];\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dA), \"l\"(src));\n"
"            } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dA)); }\n"
"            unsigned int dB0 = __cvta_generic_to_shared(&sB_next[swz_b0]);\n"
"            if (g_row_b0 < N) {\n"
"                const fp8_raw *src = &W[(size_t)g_row_b0 * K + next_k + col_b0_g];\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB0), \"l\"(src));\n"
"            } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB0)); }\n"
"            unsigned int dB1 = __cvta_generic_to_shared(&sB_next[swz_b1]);\n"
"            if (g_row_b1 < N) {\n"
"                const fp8_raw *src = &W[(size_t)g_row_b1 * K + next_k + col_b1_g];\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16;\\n\" :: \"r\"(dB1), \"l\"(src));\n"
"            } else { asm volatile(\"st.shared.v4.b32 [%0], {0,0,0,0};\\n\" :: \"r\"(dB1)); }\n"
"        }\n"
"        asm volatile(\"cp.async.commit_group;\\n\");\n"
"        unsigned short *sAp = (stage == 0) ? sA0 : sA1;\n"
"        unsigned short *sBp = (stage == 0) ? sB0 : sB1;\n"
"        #pragma unroll\n"
"        for (int kg = 0; kg < 2; kg++) {\n"
"            int k_off = kg * 16;\n"
"            int a_off = la_row * 32 + ((k_off + la_col_off) ^ la_sw);\n"
"            unsigned int a0,a1,a2,a3;\n"
"            unsigned int p_a = __cvta_generic_to_shared(&sAp[a_off]);\n"
"            asm volatile(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\\n\"\n"
"                : \"=r\"(a0), \"=r\"(a1), \"=r\"(a2), \"=r\"(a3) : \"r\"(p_a));\n"
"            #pragma unroll\n"
"            for (int s = 0; s < 4; s++) {\n"
"                int sn_base = wn_col + s * 16;\n"
"                int b_brow  = sn_base + lb_row;\n"
"                int b_sw    = (b_brow & 3) * 8;\n"
"                int b_off   = b_brow * 32 + ((k_off + lb_col_off) ^ b_sw);\n"
"                unsigned int b0,b1,b2,b3;\n"
"                unsigned int p_b = __cvta_generic_to_shared(&sBp[b_off]);\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\\n\"\n"
"                    : \"=r\"(b0), \"=r\"(b1), \"=r\"(b2), \"=r\"(b3) : \"r\"(p_b));\n"
"                int nt0 = s * 2 + 0;\n"
"                int nt1 = s * 2 + 1;\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[nt0]), \"=f\"(d1[nt0]), \"=f\"(d2[nt0]), \"=f\"(d3[nt0])\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b2),\n"
"                      \"f\"(d0[nt0]), \"f\"(d1[nt0]), \"f\"(d2[nt0]), \"f\"(d3[nt0])\n"
"                );\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[nt1]), \"=f\"(d1[nt1]), \"=f\"(d2[nt1]), \"=f\"(d3[nt1])\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b1), \"r\"(b3),\n"
"                      \"f\"(d0[nt1]), \"f\"(d1[nt1]), \"f\"(d2[nt1]), \"f\"(d3[nt1])\n"
"                );\n"
"            }\n"
"        }\n"
"    }\n"
"    asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"    float ds = w_scale * x_scale_ptr[0];\n"
"    int yr0 = cta_m + wm_row + gid;\n"
"    int yr1 = cta_m + wm_row + gid + 8;\n"
"    #pragma unroll\n"
"    for (int nt = 0; nt < 8; nt++) {\n"
"        int yc0 = cta_n + wn_col + nt*8 + tid4*2;\n"
"        int yc1 = yc0 + 1;\n"
"        float b0_v = (has_bias && yc0 < N) ? bias[yc0] : 0.0f;\n"
"        float b1_v = (has_bias && yc1 < N) ? bias[yc1] : 0.0f;\n"
"        if (yr0 < M && yc0 < N) { size_t idx = (size_t)yr0 * N + yc0; float v = d0[nt] * ds + b0_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"        if (yr0 < M && yc1 < N) { size_t idx = (size_t)yr0 * N + yc1; float v = d1[nt] * ds + b1_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"        if (yr1 < M && yc0 < N) { size_t idx = (size_t)yr1 * N + yc0; float v = d2[nt] * ds + b0_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"        if (yr1 < M && yc1 < N) { size_t idx = (size_t)yr1 * N + yc1; float v = d3[nt] * ds + b1_v; Y[idx] = accumulate ? Y[idx] + v : v; }\n"
"    }\n"
"}\n"
;
#endif
