/*
 * test_paint_unet_stage.c - Smoke harness for paint_stage_unet (Phase 4.12).
 *
 * Mirrors test_paint_unet --stage out_loop but drives only the opaque API
 * declared in paint_stages.h, so it exercises the per-stage TU split end-to-
 * end. Loads pyref dumps from <ref_dir> (generated by
 * ref/hy3d/dump_paint_unet_wrapper.py --stage out_loop), runs N UniPC steps
 * via paint_stage_unet_run_step, validates each per-step noise prediction
 * vs loop_model_out_<i>.npy and the cumulative latent vs loop_x_after_<i>.npy.
 *
 * Usage:
 *   ./test_paint_unet_stage <unet.safetensors> <ref_dir> [--save-final out.npy]
 *
 * Dumps consumed:
 *   in_embeds_normal.npy      [N_gen, 4, H0, W0]
 *   in_embeds_position.npy    [N_gen, 4, H0, W0]
 *   in_encoder_hidden_states.npy [N_pbr, 1, M_text, cross_dim]
 *   in_ref_latents.npy        [N_ref, 4, H0, W0]
 *   in_dino_hidden_states.npy [1, T_dino, C_dino_in]
 *   loop_x0.npy               [Beff_main, 4, H0, W0]
 *   loop_timesteps.npy        [N_steps] int64
 *   loop_model_out_<i>.npy    per-step noise pred reference
 *   loop_x_after_<i>.npy      per-step latent reference
 */

#include "../cuew.h"
#include "paint_stages.h"
#include "cuda_paint_unipc.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>

static void *read_npy(const char *path, int *out_nd, uint64_t *out_shape,
                       size_t *out_n, char *out_dt) {
    FILE *f = fopen(path, "rb"); if (!f) return NULL;
    char magic[6];
    if (fread(magic, 1, 6, f) != 6 || memcmp(magic, "\x93NUMPY", 6)) { fclose(f); return NULL; }
    uint8_t ver[2]; if (fread(ver, 1, 2, f) != 2) { fclose(f); return NULL; }
    uint16_t hlen; if (fread(&hlen, 2, 1, f) != 1) { fclose(f); return NULL; }
    char hdr[1024]; if (hlen >= sizeof(hdr) || fread(hdr, 1, hlen, f) != hlen) { fclose(f); return NULL; }
    hdr[hlen] = 0;
    const char *dp = strstr(hdr, "'descr':");
    /* hdr layout: `'descr': '<f4'` — value char at dp+11 is the byte-order
     * mark, dp+12 is the type code, dp+13 is the size. */
    if (dp) { out_dt[0] = dp[11]; out_dt[1] = dp[12]; out_dt[2] = dp[13]; out_dt[3] = 0; }
    else    { out_dt[0] = '<'; out_dt[1] = 'f'; out_dt[2] = '4'; out_dt[3] = 0; }
    const char *p = strstr(hdr, "'shape': ("); if (!p) { fclose(f); return NULL; }
    p += strlen("'shape': (");
    int nd = 0; uint64_t shape[8]; size_t total = 1;
    while (*p && *p != ')') {
        while (*p == ' ' || *p == ',') p++;
        if (*p == ')') break;
        char *end; uint64_t v = strtoull(p, &end, 10);
        shape[nd++] = v; total *= v; p = end;
    }
    *out_nd = nd;
    for (int i = 0; i < nd; i++) out_shape[i] = shape[i];
    *out_n = total;
    int elsz = (out_dt[0] == 'i' && out_dt[1] == '8') ? 8 : 4;  /* int64 vs f32 */
    void *buf = malloc(total * elsz);
    if (fread(buf, elsz, total, f) != total) { free(buf); fclose(f); return NULL; }
    fclose(f); return buf;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <unet.safetensors> <ref_dir> [--save-final out.npy]\n", argv[0]);
        return 1;
    }
    const char *unet_path = argv[1];
    const char *ref_dir = argv[2];
    const char *save_final = NULL;
    for (int i = 3; i < argc; i++)
        if (!strcmp(argv[i], "--save-final") && i + 1 < argc) save_final = argv[++i];

    if (cuewInit(CUEW_INIT_CUDA | CUEW_INIT_NVRTC) != CUEW_SUCCESS) return 1;
    cuInit(0);
    CUdevice dev; cuDeviceGet(&dev, 0);
    CUcontext ctx; cuCtxCreate(&ctx, 0, dev);

    char path[512]; int nd; uint64_t sh[8]; size_t n; char dt[8];
    snprintf(path, sizeof(path), "%s/in_embeds_normal.npy", ref_dir);
    float *en = (float *)read_npy(path, &nd, sh, &n, dt); if (!en) { fprintf(stderr, "missing %s\n", path); return 1; }
    snprintf(path, sizeof(path), "%s/in_embeds_position.npy", ref_dir);
    float *ep = (float *)read_npy(path, &nd, sh, &n, dt); if (!ep) { fprintf(stderr, "missing %s\n", path); return 1; }
    snprintf(path, sizeof(path), "%s/in_encoder_hidden_states.npy", ref_dir);
    float *text_in = (float *)read_npy(path, &nd, sh, &n, dt); if (!text_in) return 1;
    int M_text = (int)sh[2], cross_dim = (int)sh[3];
    snprintf(path, sizeof(path), "%s/in_ref_latents.npy", ref_dir);
    float *ref_latents = (float *)read_npy(path, &nd, sh, &n, dt); if (!ref_latents) return 1;
    snprintf(path, sizeof(path), "%s/in_dino_hidden_states.npy", ref_dir);
    float *dino_in = (float *)read_npy(path, &nd, sh, &n, dt); if (!dino_in) return 1;
    int T_dino = (int)sh[1], C_dino_in = (int)sh[2];

    snprintf(path, sizeof(path), "%s/loop_x0.npy", ref_dir);
    float *x0 = (float *)read_npy(path, &nd, sh, &n, dt); if (!x0) return 1;
    snprintf(path, sizeof(path), "%s/loop_timesteps.npy", ref_dir);
    int64_t *ts_loop = (int64_t *)read_npy(path, &nd, sh, &n, dt); if (!ts_loop) return 1;
    int N_steps = (int)n;

    paint_unet_config cfg = {
        .B_outer = 1, .N_pbr = 2, .N_gen = 2, .N_ref = 1,
        .H0 = 64, .W0 = 64,
        .M_text = M_text, .cross_dim = cross_dim,
        .T_dino = T_dino, .C_dino_in = C_dino_in,
    };
    int Beff_main = cfg.B_outer * cfg.N_pbr * cfg.N_gen;
    size_t x_n = (size_t)Beff_main * 4 * cfg.H0 * cfg.W0;

    fprintf(stderr, "out_loop: Beff_main=%d N_steps=%d M_text=%d cross=%d T_dino=%d\n",
            Beff_main, N_steps, M_text, cross_dim, T_dino);

    paint_stage_unet *u = paint_stage_unet_create(dev, unet_path, &cfg);
    if (!u) return 1;
    paint_stage_unet_set_conditioning(u, en, ep, text_in, ref_latents, dino_in);
    paint_stage_unet_run_dual(u);

    float *x_host = (float *)malloc(x_n * sizeof(float));
    float *noise_pred = (float *)malloc(x_n * sizeof(float));
    memcpy(x_host, x0, x_n * sizeof(float));

    pu_unipc sch; pu_unipc_init(&sch, N_steps, x_n);

    int all_ok = 1;
    for (int i = 0; i < N_steps; i++) {
        int64_t ts_v = ts_loop[i];
        paint_stage_unet_run_step(u, (long long)ts_v, x_host, noise_pred);

        char p2[512]; int nd2; uint64_t s2[8]; size_t n2; char dt2[8];
        snprintf(p2, sizeof(p2), "%s/loop_model_out_%d.npy", ref_dir, i);
        float *mo_ref = (float *)read_npy(p2, &nd2, s2, &n2, dt2);
        double mo_max = 0.0;
        if (mo_ref && n2 == x_n)
            for (size_t k = 0; k < x_n; k++) {
                double d = fabs((double)noise_pred[k] - (double)mo_ref[k]);
                if (d > mo_max) mo_max = d;
            }
        free(mo_ref);

        pu_unipc_step(&sch, noise_pred, x_host);

        snprintf(p2, sizeof(p2), "%s/loop_x_after_%d.npy", ref_dir, i);
        float *xa_ref = (float *)read_npy(p2, &nd2, s2, &n2, dt2);
        double x_max = 0.0, x_sum = 0.0;
        if (xa_ref && n2 == x_n)
            for (size_t k = 0; k < x_n; k++) {
                double d = fabs((double)x_host[k] - (double)xa_ref[k]);
                x_sum += d; if (d > x_max) x_max = d;
            }
        double x_mae = x_sum / (double)x_n;
        int ok = (x_max < 5e-2) && (mo_max < 5e-2);
        if (!ok) all_ok = 0;
        fprintf(stderr, "  step %2d  t=%4lld  mo_max=%.3e  x_mae=%.3e  x_max=%.3e  %s\n",
                i, (long long)ts_v, mo_max, x_mae, x_max, ok ? "OK" : "**MISMATCH**");
        free(xa_ref);
    }

    if (save_final) {
        const float vae_inv_scale = 1.0f / 0.18215f;
        for (size_t k = 0; k < x_n; k++) x_host[k] *= vae_inv_scale;
        FILE *fp = fopen(save_final, "wb");
        uint8_t magic[6] = {0x93,'N','U','M','P','Y'}; uint8_t ver[2] = {1,0};
        char hdr[256];
        int hdrlen = snprintf(hdr, sizeof(hdr),
            "{'descr': '<f4', 'fortran_order': False, 'shape': (%d, 4, %d, %d), }",
            Beff_main, cfg.H0, cfg.W0);
        int total = 10 + hdrlen; int pad = 64 - (total % 64);
        for (int i = 0; i < pad - 1; i++) hdr[hdrlen + i] = ' ';
        hdr[hdrlen + pad - 1] = '\n';
        uint16_t hl = (uint16_t)(hdrlen + pad);
        fwrite(magic, 1, 6, fp); fwrite(ver, 1, 2, fp);
        fwrite(&hl, 2, 1, fp);   fwrite(hdr, 1, hl, fp);
        fwrite(x_host, sizeof(float), x_n, fp);
        fclose(fp);
        fprintf(stderr, "wrote final latent -> %s\n", save_final);
    }

    pu_unipc_free(&sch);
    free(x_host); free(noise_pred);
    free(en); free(ep); free(text_in); free(ref_latents);
    free(dino_in); free(x0); free(ts_loop);
    paint_stage_unet_destroy(u);
    cuCtxDestroy(ctx);

    fprintf(stderr, "\nout_loop result: %s\n", all_ok ? "PASS" : "FAIL");
    return all_ok ? 0 : 1;
}
