/*
 * hip_hy3d_kernels.h - HIP kernel source strings for Hunyuan3D-2.1
 *
 * Contains all HY3D-specific HIP kernels as a C string literal for
 * HIPRTC runtime compilation. Concatenated after hip_kernels_common_src
 * (which opens extern "C" {) and closes it at the end.
 *
 * Port of cuda_hy3d_kernels.h for AMD ROCm/HIP (RDNA4, gfx1201).
 * All 15 kernels are pure CUDA C with no PTX ASM, so they work
 * unchanged under HIP/HIPRTC.
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_HY3D_KERNELS_H
#define HIP_HY3D_KERNELS_H

static const char hip_hy3d_specific_kernels[] =
"\n"

/* -------------------------------------------------------------------- */
/* gelu_exact_f32: exact GELU using erf (matches nn.GELU default).      */
/* nn.GELU() uses approximate='none': 0.5*x*(1+erf(x/sqrt(2))).         */
/* common/gelu_f32 uses tanh approximation — Hy3D DiT needs exact.      */
/* -------------------------------------------------------------------- */
"__global__ void gelu_exact_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) {\n"
"        float v = x[i];\n"
"        x[i] = 0.5f * v * (1.0f + erff(v * 0.70710678118654752f));\n"
"    }\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* rms_norm_f32: per-head RMSNorm (for DiT QK normalization)            */
/* One thread per (token, head). Normalizes head_dim elements in-place. */
/* -------------------------------------------------------------------- */
"/* ---- rms_norm_f32: per-head RMSNorm (for QK normalization) ---- */\n"
"/* One thread per (token, head). Normalizes head_dim elements in-place. */\n"
"__global__ void rms_norm_f32(float *data, const float *w,\n"
"                              int n_tok, int n_heads, int head_dim,\n"
"                              int stride, float eps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = n_tok * n_heads;\n"
"    if (idx >= total) return;\n"
"    int tok = idx / n_heads;\n"
"    int h = idx % n_heads;\n"
"    float *base = data + tok * stride + h * head_dim;\n"
"    float sum_sq = 0.0f;\n"
"    for (int i = 0; i < head_dim; i++) sum_sq += base[i] * base[i];\n"
"    float inv = rsqrtf(sum_sq / (float)head_dim + eps);\n"
"    for (int i = 0; i < head_dim; i++)\n"
"        base[i] = base[i] * inv * w[i];\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* qk_layernorm_f32: per-head LayerNorm (for ShapeVAE QK norm)          */
/* -------------------------------------------------------------------- */
"/* ---- qk_layernorm_f32: per-head LayerNorm (for ShapeVAE QK norm) ---- */\n"
"__global__ void qk_layernorm_f32(float *data, const float *w, const float *b,\n"
"                                   int n_tok, int n_heads, int head_dim,\n"
"                                   int stride, float eps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = n_tok * n_heads;\n"
"    if (idx >= total) return;\n"
"    int tok = idx / n_heads;\n"
"    int h = idx % n_heads;\n"
"    float *base = data + tok * stride + h * head_dim;\n"
"    float sum = 0.0f;\n"
"    for (int i = 0; i < head_dim; i++) sum += base[i];\n"
"    float mean = sum / (float)head_dim;\n"
"    float var_sum = 0.0f;\n"
"    for (int i = 0; i < head_dim; i++) { float d = base[i] - mean; var_sum += d*d; }\n"
"    float inv = rsqrtf(var_sum / (float)head_dim + eps);\n"
"    for (int i = 0; i < head_dim; i++)\n"
"        base[i] = (base[i] - mean) * inv * w[i] + (b ? b[i] : 0.0f);\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* layerscale_add_f32: LayerScale residual for DINOv2                    */
/* dst[i] += src[i] * scale[i % dim]                                    */
/* -------------------------------------------------------------------- */
"/* ---- layerscale_add_f32: LayerScale residual for DINOv2 ---- */\n"
"/* dst[i] += src[i] * scale[i % dim] */\n"
"__global__ void layerscale_add_f32(float *dst, const float *src,\n"
"                                     const float *scale, int n, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    dst[i] += src[i] * scale[i % dim];\n"
"}\n"
"\n"
"/* ---- layerscale_add_f16: f16 in/out, f32 scale vector ---- */\n"
"__global__ void layerscale_add_f16(__half *dst, const __half *src,\n"
"                                     const float *scale, int n, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    float d = __half2float(dst[i]);\n"
"    float s = __half2float(src[i]);\n"
"    d += s * scale[i % dim];\n"
"    dst[i] = __float2half(d);\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* cross_attn_f32: cross-attention with different Q/KV lengths           */
/* One block per (head, query_token). Handles Q_len != KV_len.           */
/* -------------------------------------------------------------------- */
"/* ---- cross_attn_f32: cross-attention with different Q/KV lengths ---- */\n"
"/* One block per (head, query_token). Handles Q_len != KV_len.          */\n"
"__global__ void cross_attn_f32(float *out,\n"
"                                const float *Q, const float *K, const float *V,\n"
"                                int q_len, int kv_len, int dim,\n"
"                                int n_heads, int head_dim, float scale) {\n"
"    int h = blockIdx.x;\n"
"    int qi = blockIdx.y;\n"
"    if (h >= n_heads || qi >= q_len) return;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    const float *q = Q + qi * dim + h * head_dim;\n"
"    extern __shared__ float sdata[];\n"
"    float *scores = sdata;\n"
"    float *rbuf = sdata + kv_len;\n"
"\n"
"    /* Phase 1: Q @ K^T */\n"
"    for (int ki = tid; ki < kv_len; ki += nt) {\n"
"        const float *k = K + ki * dim + h * head_dim;\n"
"        float dot = 0.0f;\n"
"        for (int d = 0; d < head_dim; d++) dot += q[d] * k[d];\n"
"        scores[ki] = dot * scale;\n"
"    }\n"
"    __syncthreads();\n"
"\n"
"    /* Phase 2: Softmax -- find max */\n"
"    float lmax = -1e30f;\n"
"    for (int ki = tid; ki < kv_len; ki += nt)\n"
"        lmax = fmaxf(lmax, scores[ki]);\n"
"    rbuf[tid] = lmax;\n"
"    __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] = fmaxf(rbuf[tid], rbuf[tid+r]);\n"
"        __syncthreads();\n"
"    }\n"
"    float mx = rbuf[0];\n"
"    __syncthreads();\n"
"\n"
"    /* Exp + sum */\n"
"    float lsum = 0.0f;\n"
"    for (int ki = tid; ki < kv_len; ki += nt) {\n"
"        scores[ki] = expf(scores[ki] - mx);\n"
"        lsum += scores[ki];\n"
"    }\n"
"    rbuf[tid] = lsum;\n"
"    __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] += rbuf[tid+r];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv_sum = (rbuf[0] > 0) ? 1.0f / rbuf[0] : 0.0f;\n"
"    for (int ki = tid; ki < kv_len; ki += nt)\n"
"        scores[ki] *= inv_sum;\n"
"    __syncthreads();\n"
"\n"
"    /* Phase 3: Weighted sum of V */\n"
"    for (int d = tid; d < head_dim; d += nt) {\n"
"        float acc = 0.0f;\n"
"        for (int ki = 0; ki < kv_len; ki++)\n"
"            acc += scores[ki] * V[ki * dim + h * head_dim + d];\n"
"        out[qi * dim + h * head_dim + d] = acc;\n"
"    }\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* fourier_embed_3d_f32: 3D coordinate Fourier embedding                 */
/* input: [N, 3], output: [N, out_dim] where out_dim = 3*(2*nf+1)       */
/* Layout: [x,y,z, sin(f0*x),...sin(fn*x), sin(f0*y),..., cos(...)...]   */
/* -------------------------------------------------------------------- */
"/* ---- fourier_embed_3d_f32: 3D coordinate Fourier embedding ---- */\n"
"/* input: [N, 3], output: [N, out_dim] where out_dim = 3*(2*nf+1)  */\n"
"/* Layout: [x,y,z, sin(f0*x),...sin(fn*x), sin(f0*y),..., cos(...)...] */\n"
"__global__ void fourier_embed_3d_f32(float *out, const float *coords,\n"
"                                      const float *freqs, int N,\n"
"                                      int num_freqs, int out_dim) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= N) return;\n"
"    const float *in = coords + idx * 3;\n"
"    float *o = out + idx * out_dim;\n"
"    int p = 0;\n"
"    /* Include raw input */\n"
"    o[p++] = in[0]; o[p++] = in[1]; o[p++] = in[2];\n"
"    /* Sin embeddings */\n"
"    for (int d = 0; d < 3; d++)\n"
"        for (int f = 0; f < num_freqs; f++)\n"
"            o[p++] = sinf(in[d] * freqs[f]);\n"
"    /* Cos embeddings */\n"
"    for (int d = 0; d < 3; d++)\n"
"        for (int f = 0; f < num_freqs; f++)\n"
"            o[p++] = cosf(in[d] * freqs[f]);\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* timestep_embed_f32: sinusoidal timestep embedding                     */
/* -------------------------------------------------------------------- */
"/* ---- timestep_embed_f32: sinusoidal timestep embedding ---- */\n"
"/* Matches PyTorch Timesteps class: no 1000x scaling. */\n"
"__global__ void timestep_embed_f32(float *out, float t, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int half = dim / 2;\n"
"    if (i >= half) return;\n"
"    float exponent = -logf(10000.0f) * (float)i / (float)half;\n"
"    float emb = expf(exponent) * t;\n"
"    out[i] = sinf(emb);\n"
"    out[half + i] = cosf(emb);\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* euler_step_f32: x_new = x - dt * v                                    */
/* -------------------------------------------------------------------- */
"/* ---- euler_step_f32: x_new = x - dt * v ---- */\n"
"__global__ void euler_step_f32(float *x, const float *v, float dt, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    x[i] = x[i] - dt * v[i];\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* cfg_combine_f32: out = uncond + scale * (cond - uncond)               */
/* -------------------------------------------------------------------- */
"/* ---- cfg_combine_f32: out = uncond + scale * (cond - uncond) ---- */\n"
"__global__ void cfg_combine_f32(float *out, const float *cond,\n"
"                                  const float *uncond,\n"
"                                  float scale, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    out[i] = uncond[i] + scale * (cond[i] - uncond[i]);\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* split_qkv_interleaved_f32: split [N, 3*W] with interleaved heads      */
/* Input:  [N, H, 3, HD] (3*W = H*3*HD)                                 */
/* Output: Q[N, W], K[N, W], V[N, W] (W = H*HD)                         */
/* -------------------------------------------------------------------- */
"/* ---- split_qkv_interleaved_f32: split [N, 3*W] interleaved heads ---- */\n"
"/* Input:  [N, H, 3, HD] (3*W = H*3*HD) */\n"
"/* Output: Q[N, W], K[N, W], V[N, W] (W = H*HD) */\n"
"__global__ void split_qkv_interleaved_f32(\n"
"    float *Q, float *K, float *V,\n"
"    const float *qkv, int N, int H, int HD) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int W = H * HD;\n"
"    int total = N * W;\n"
"    if (idx >= total) return;\n"
"    int n = idx / W;\n"
"    int rem = idx % W;\n"
"    int h = rem / HD;\n"
"    int d = rem % HD;\n"
"    int base = n * 3 * W + h * 3 * HD;\n"
"    Q[idx] = qkv[base + d];\n"
"    K[idx] = qkv[base + HD + d];\n"
"    V[idx] = qkv[base + 2*HD + d];\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* split_kv_interleaved_f32: split [M, 2*W] with interleaved heads       */
/* Input:  [M, H, 2, HD] (2*W = H*2*HD)                                 */
/* Output: K[M, W], V[M, W] (W = H*HD)                                  */
/* -------------------------------------------------------------------- */
"/* ---- split_kv_interleaved_f32: split [M, 2*W] interleaved heads ---- */\n"
"/* Input:  [M, H, 2, HD] (2*W = H*2*HD) */\n"
"/* Output: K[M, W], V[M, W] (W = H*HD) */\n"
"__global__ void split_kv_interleaved_f32(\n"
"    float *K, float *V,\n"
"    const float *kv, int M, int H, int HD) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int W = H * HD;\n"
"    int total = M * W;\n"
"    if (idx >= total) return;\n"
"    int m = idx / W;\n"
"    int rem = idx % W;\n"
"    int h = rem / HD;\n"
"    int d = rem % HD;\n"
"    int base = m * 2 * W + h * 2 * HD;\n"
"    K[idx] = kv[base + d];\n"
"    V[idx] = kv[base + HD + d];\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* broadcast_add_f32: dst[i] += src[i % dim]                             */
/* Broadcasts a [dim] bias vector across an [N, dim] matrix.             */
/* -------------------------------------------------------------------- */
"/* ---- broadcast_add_f32: dst[i] += src[i % dim] ---- */\n"
"/* Broadcasts a [dim] vector across [N, dim] matrix. */\n"
"__global__ void broadcast_add_f32(float *dst, const float *src,\n"
"                                    int n, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    dst[i] += src[i % dim];\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* concat_token_f32: prepend a token to a sequence                       */
/* Given token [dim] and seq [N, dim], output [(N+1), dim]               */
/* First row is token, remaining rows are seq.                           */
/* -------------------------------------------------------------------- */
"/* ---- concat_token_f32: prepend a token to a sequence ---- */\n"
"/* token [dim] + seq [N, dim] -> out [(N+1), dim], first row is token */\n"
"__global__ void concat_token_f32(float *out, const float *token,\n"
"                                   const float *seq,\n"
"                                   int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = (N + 1) * dim;\n"
"    if (i >= total) return;\n"
"    if (i < dim) {\n"
"        out[i] = token[i];\n"
"    } else {\n"
"        out[i] = seq[i - dim];\n"
"    }\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* moe_gate_f32: MoE gating with top-k selection                         */
/* -------------------------------------------------------------------- */
"/* ---- moe_gate_f32: MoE gating with top-k selection ---- */\n"
"/* logits [n_experts], outputs top_k indices + softmax weights. */\n"
"/* Single-threaded: n_experts is small (4-8). */\n"
"__global__ void moe_gate_f32(int *indices, float *weights,\n"
"                               const float *logits,\n"
"                               int n_experts, int top_k) {\n"
"    if (threadIdx.x != 0 || blockIdx.x != 0) return;\n"
"\n"
"    /* Find top-k indices by repeated argmax with masking */\n"
"    float used[32]; /* assume n_experts <= 32 */\n"
"    for (int e = 0; e < n_experts && e < 32; e++)\n"
"        used[e] = logits[e];\n"
"\n"
"    for (int k = 0; k < top_k; k++) {\n"
"        int best = -1;\n"
"        float best_val = -1e30f;\n"
"        for (int e = 0; e < n_experts; e++) {\n"
"            if (used[e] > best_val) {\n"
"                best_val = used[e];\n"
"                best = e;\n"
"            }\n"
"        }\n"
"        indices[k] = best;\n"
"        weights[k] = best_val;\n"
"        if (best >= 0) used[best] = -1e30f; /* mask out selected */\n"
"    }\n"
"\n"
"    /* Softmax over the selected top-k weights */\n"
"    float mx = -1e30f;\n"
"    for (int k = 0; k < top_k; k++)\n"
"        mx = fmaxf(mx, weights[k]);\n"
"    float sum = 0.0f;\n"
"    for (int k = 0; k < top_k; k++) {\n"
"        weights[k] = expf(weights[k] - mx);\n"
"        sum += weights[k];\n"
"    }\n"
"    float inv = (sum > 0.0f) ? 1.0f / sum : 0.0f;\n"
"    for (int k = 0; k < top_k; k++)\n"
"        weights[k] *= inv;\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* concat_f32: concatenate two [N, dim] tensors along last dimension     */
/* Given a [N, dim] and b [N, dim], output c [N, 2*dim]                  */
/* -------------------------------------------------------------------- */
"/* ---- concat_f32: concat two [N, dim] tensors along last dim ---- */\n"
"/* a [N, dim] + b [N, dim] -> c [N, 2*dim] */\n"
"__global__ void concat_f32(float *c, const float *a, const float *b,\n"
"                             int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * 2 * dim;\n"
"    if (i >= total) return;\n"
"    int row = i / (2 * dim);\n"
"    int col = i % (2 * dim);\n"
"    if (col < dim) {\n"
"        c[i] = a[row * dim + col];\n"
"    } else {\n"
"        c[i] = b[row * dim + (col - dim)];\n"
"    }\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* strip_first_token_f32: drop first token from sequence                  */
/* Copy src[1:, :] to dst. [N+1, dim] -> [N, dim]                        */
/* -------------------------------------------------------------------- */
"/* ---- strip_first_token_f32: drop first token ---- */\n"
"/* src [N+1, dim] -> dst [N, dim], skipping first row */\n"
"__global__ void strip_first_token_f32(float *dst, const float *src,\n"
"                                        int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * dim;\n"
"    if (i >= total) return;\n"
"    dst[i] = src[i + dim];\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* gemm_f32_f32: pure F32 tiled GEMM (no F16 conversion)                 */
/* Same interface as gemm_tiled_f16_f32 but weights are float, not half.  */
/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16)               */
/* -------------------------------------------------------------------- */
"/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */\n"
"__global__ void gemm_f32_f32(float *Y, const float *W, const float *X,\n"
"                              const float *bias,\n"
"                              int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w_out = out_base + tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? W[(size_t)w_out*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w_out = out_base+16+tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? W[(size_t)w_out*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w_out = out_base+32+tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? W[(size_t)w_out*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w_out = out_base+48+tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? W[(size_t)w_out*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- gemm_f16w_bf16a_wmma_t: F16-weight × F32-act GEMM via BF16 WMMA (gfx12) */
/* Layout matches gemm_tiled_f16_f32: Y[n_tok, n_out] = X[n_tok, n_in] * W[n_out, n_in]^T + bias.
 * W is F16 (half_raw); X/Y/bias are F32. Weights and activations are converted to
 * BF16 at SMEM load (F16 -> F32 via __half2float -> top-16-bits as BF16).
 * CTA tile 128x128, 256 threads = 8 waves in 2x4 (M x N). Each wave does 4x2 = 8
 * WMMA ops. Requires n_in % 16 == 0; n_out and n_tok are bounds-checked. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_f16w_bf16a_wmma_t(float *Y, const half_raw *W, const float *X,\n"
"                                         const float *bias, int n_out, int n_in, int n_tok) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;\n"
"    int lane    = tid & 31;\n"
"    int wM = wave_id & 1;\n"
"    int wN = wave_id >> 1;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];\n"
"    __shared__ short smB[128*16];\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int row = cta_m0 + er;\n"
"            int kp  = k + ek;\n"
"            float xv = (row < n_tok && kp < n_in) ? X[(long)row * n_in + kp] : 0.f;\n"
"            unsigned int xbits; memcpy(&xbits, &xv, 4);\n"
"            smA[er * 16 + ek] = (short)(xbits >> 16);\n"
"        }\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int col = cta_n0 + er;\n"
"            int kp  = k + ek;\n"
"            float wv = (col < n_out && kp < n_in)\n"
"                     ? half_to_float(W[(long)col * n_in + kp]) : 0.f;\n"
"            unsigned int wbits; memcpy(&wbits, &wv, 4);\n"
"            smB[er * 16 + ek] = (short)(wbits >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        int a_base_row = wM * 64;\n"
"        int b_base_row = wN * 32;\n"
"        bf16x8 a0, a1, a2, a3, b0, b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row + 0  + idx) * 16 + k_off + i];\n"
"            a1[i] = smA[(a_base_row + 16 + idx) * 16 + k_off + i];\n"
"            a2[i] = smA[(a_base_row + 32 + idx) * 16 + k_off + i];\n"
"            a3[i] = smA[(a_base_row + 48 + idx) * 16 + k_off + i];\n"
"            b0[i] = smB[(b_base_row + 0  + idx) * 16 + k_off + i];\n"
"            b1[i] = smB[(b_base_row + 16 + idx) * 16 + k_off + i];\n"
"        }\n"
"        cv00 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b0, cv00);\n"
"        cv01 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b1, cv01);\n"
"        cv10 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b0, cv10);\n"
"        cv11 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b1, cv11);\n"
"        cv20 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b0, cv20);\n"
"        cv21 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b1, cv21);\n"
"        cv30 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b0, cv30);\n"
"        cv31 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b1, cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int ms[8]       = {0,   0,  16, 16, 32, 32, 48, 48};\n"
"    int ns[8]       = {0,  16,   0, 16,  0, 16,  0, 16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + ns[t] + idx;\n"
"        if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + ms[t] + half * 8 + i;\n"
"            if (row < n_tok)\n"
"                Y[(long)row * n_out + col] = acc[i] + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#else\n"
"__global__ void gemm_f16w_bf16a_wmma_t(float *Y, const half_raw *W, const float *X,\n"
"                                         const float *bias, int n_out, int n_in, int n_tok) {\n"
"    /* non-gfx12 fallback: unused (host dispatches to gemm_tiled_f16_f32) */\n"
"}\n"
"#endif\n\n"

/* -------------------------------------------------------------------- */
/* F16 variants: residual stream stays in fp16 (matches PyTorch fp16     */
/* DiT inference). All reductions/intermediates are still f32. Inputs    */
/* and outputs use the existing `half_raw` (unsigned short) typedef.     */
/* -------------------------------------------------------------------- */
"__device__ __forceinline__ half_raw float_to_half_raw(float f) {\n"
"    __half h = __float2half(f);\n"
"    half_raw r; *((__half *)&r) = h; return r;\n"
"}\n"
"\n"
"/* ---- qk_layernorm_f16: same op, f16 data (f32 reduction). ---- */\n"
"__global__ void qk_layernorm_f16(half_raw *data, const float *w, const float *b,\n"
"                                   int n_tok, int n_heads, int head_dim,\n"
"                                   int stride, float eps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = n_tok * n_heads;\n"
"    if (idx >= total) return;\n"
"    int tok = idx / n_heads;\n"
"    int h = idx % n_heads;\n"
"    half_raw *base = data + tok * stride + h * head_dim;\n"
"    float sum = 0.0f;\n"
"    for (int i = 0; i < head_dim; i++) sum += half_to_float(base[i]);\n"
"    float mean = sum / (float)head_dim;\n"
"    float var_sum = 0.0f;\n"
"    for (int i = 0; i < head_dim; i++) {\n"
"        float d = half_to_float(base[i]) - mean;\n"
"        var_sum += d * d;\n"
"    }\n"
"    float inv = rsqrtf(var_sum / (float)head_dim + eps);\n"
"    for (int i = 0; i < head_dim; i++) {\n"
"        float v = (half_to_float(base[i]) - mean) * inv * w[i] + (b ? b[i] : 0.0f);\n"
"        base[i] = float_to_half_raw(v);\n"
"    }\n"
"}\n"
"\n"

"/* ---- gelu_exact_f16: f16 in/out, f32 compute (matches nn.GELU exact) ---- */\n"
"__global__ void gelu_exact_f16(half_raw *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) {\n"
"        float v = half_to_float(x[i]);\n"
"        float y = 0.5f * v * (1.0f + erff(v * 0.70710678118654752f));\n"
"        x[i] = float_to_half_raw(y);\n"
"    }\n"
"}\n"
"\n"

"/* ---- add_f16: dst[i] += src[i] (both f16) ---- */\n"
"__global__ void add_f16(half_raw *dst, const half_raw *src, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) {\n"
"        float a = half_to_float(dst[i]);\n"
"        float b = half_to_float(src[i]);\n"
"        dst[i] = float_to_half_raw(a + b);\n"
"    }\n"
"}\n"
"\n"

"/* ---- rms_norm_f16: per-head RMSNorm on fp16 data, f32 reduction ---- */\n"
"/*       One warp per row; head_dim must be a multiple of 32. */\n"
"__global__ void rms_norm_f16(half_raw *data, const float *w,\n"
"                              int n_tok, int n_heads, int head_dim,\n"
"                              int stride, float eps) {\n"
"    int lane = threadIdx.x & 31;\n"
"    int warp_in_blk = threadIdx.x >> 5;\n"
"    int warps_per_blk = blockDim.x >> 5;\n"
"    int row = blockIdx.x * warps_per_blk + warp_in_blk;\n"
"    int total = n_tok * n_heads;\n"
"    if (row >= total) return;\n"
"    int tok = row / n_heads;\n"
"    int h = row % n_heads;\n"
"    half_raw *base = data + tok * stride + h * head_dim;\n"
"    int per_lane = head_dim >> 5;\n"
"    float sum_sq = 0.0f;\n"
"    float vals[8];\n"
"    for (int i = 0; i < per_lane; i++) {\n"
"        float v = half_to_float(base[i*32 + lane]);\n"
"        vals[i] = v;\n"
"        sum_sq += v * v;\n"
"    }\n"
"    /* warp reduce */\n"
"    for (int off = 16; off > 0; off >>= 1) {\n"
"        sum_sq += __shfl_xor(sum_sq, off);\n"
"    }\n"
"    float inv = rsqrtf(sum_sq / (float)head_dim + eps);\n"
"    for (int i = 0; i < per_lane; i++) {\n"
"        int d = i*32 + lane;\n"
"        base[d] = float_to_half_raw(vals[i] * inv * w[d]);\n"
"    }\n"
"}\n"
"\n"

"/* ---- layernorm_f16: f16 in/out, f32 reduction. w/b are f32. ---- */\n"
"__global__ void layernorm_f16(half_raw *dst, const half_raw *src,\n"
"                               const float *w, const float *b,\n"
"                               int dim, float eps) {\n"
"    extern __shared__ float sdata[];\n"
"    int tok = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    const half_raw *x = src + tok * dim;\n"
"    half_raw *y = dst + tok * dim;\n"
"    float s = 0.0f;\n"
"    for (int i = tid; i < dim; i += nt) s += half_to_float(x[i]);\n"
"    sdata[tid] = s;\n"
"    __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    s = 0.0f;\n"
"    for (int i = tid; i < dim; i += nt) {\n"
"        float d = half_to_float(x[i]) - mean;\n"
"        s += d*d;\n"
"    }\n"
"    sdata[tid] = s;\n"
"    __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + eps);\n"
"    for (int i = tid; i < dim; i += nt) {\n"
"        float v = (half_to_float(x[i]) - mean) * inv * w[i] + (b ? b[i] : 0.0f);\n"
"        y[i] = float_to_half_raw(v);\n"
"    }\n"
"}\n"
"\n"

"/* ---- F16 layout helpers (token concat / strip / qkv split) ---- */\n"
"__global__ void split_qkv_interleaved_f16(\n"
"    half_raw *Q, half_raw *K, half_raw *V,\n"
"    const half_raw *qkv, int N, int H, int HD) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int W = H * HD;\n"
"    int total = N * W;\n"
"    if (idx >= total) return;\n"
"    int n = idx / W;\n"
"    int rem = idx % W;\n"
"    int h = rem / HD;\n"
"    int d = rem % HD;\n"
"    int base = n * 3 * W + h * 3 * HD;\n"
"    Q[idx] = qkv[base + d];\n"
"    K[idx] = qkv[base + HD + d];\n"
"    V[idx] = qkv[base + 2*HD + d];\n"
"}\n"
"\n"

"__global__ void split_kv_interleaved_f16(\n"
"    half_raw *K, half_raw *V,\n"
"    const half_raw *kv, int M, int H, int HD) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int W = H * HD;\n"
"    int total = M * W;\n"
"    if (idx >= total) return;\n"
"    int m = idx / W;\n"
"    int rem = idx % W;\n"
"    int h = rem / HD;\n"
"    int d = rem % HD;\n"
"    int base = m * 2 * W + h * 2 * HD;\n"
"    K[idx] = kv[base + d];\n"
"    V[idx] = kv[base + HD + d];\n"
"}\n"
"\n"

"__global__ void concat_token_f16(half_raw *out, const half_raw *token,\n"
"                                   const half_raw *seq,\n"
"                                   int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = (N + 1) * dim;\n"
"    if (i >= total) return;\n"
"    if (i < dim) out[i] = token[i];\n"
"    else out[i] = seq[i - dim];\n"
"}\n"
"\n"

"__global__ void strip_first_token_f16(half_raw *dst, const half_raw *src,\n"
"                                        int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * dim;\n"
"    if (i >= total) return;\n"
"    dst[i] = src[i + dim];\n"
"}\n"
"\n"

"/* concat_last_dim_f16: dst [N, 2*dim] = [a [N, dim] || b [N, dim]] */\n"
"__global__ void concat_last_dim_f16(half_raw *dst,\n"
"                                     const half_raw *a, const half_raw *b,\n"
"                                     int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * 2 * dim;\n"
"    if (i >= total) return;\n"
"    int n = i / (2 * dim);\n"
"    int r = i % (2 * dim);\n"
"    if (r < dim) dst[i] = a[n * dim + r];\n"
"    else dst[i] = b[n * dim + (r - dim)];\n"
"}\n"
"\n"

"/* ---- moe_gate_softmax_topk_f32 ----\n"
" * In : logits [N_tok, n_experts] (f32, raw gate output)\n"
" * Out: weights [N_tok, n_experts] (f32, only top-K entries non-zero)\n"
" * One thread per token. Computes per-row softmax then top-K mask.\n"
" * MoEGate has norm_topk_prob=False — uses raw softmax probs as weights. */\n"
"__global__ void moe_gate_softmax_topk_f32(const float *__restrict__ logits,\n"
"                                            float *__restrict__ weights,\n"
"                                            int N_tok, int n_experts, int top_k) {\n"
"    int t = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (t >= N_tok) return;\n"
"    const float *row = logits + (long)t * n_experts;\n"
"    float *wrow = weights + (long)t * n_experts;\n"
"    float local[16];\n"
"    /* n_experts is small (8 typical, MAX 16). */\n"
"    float mx = row[0];\n"
"    for (int e = 1; e < n_experts; e++) if (row[e] > mx) mx = row[e];\n"
"    float sum = 0.f;\n"
"    for (int e = 0; e < n_experts; e++) {\n"
"        float v = __expf(row[e] - mx);\n"
"        local[e] = v;\n"
"        sum += v;\n"
"    }\n"
"    float inv = (sum > 0.f) ? 1.f / sum : 0.f;\n"
"    for (int e = 0; e < n_experts; e++) {\n"
"        local[e] *= inv;\n"
"        wrow[e] = 0.f;\n"
"    }\n"
"    /* Top-K selection by repeated argmax. */\n"
"    for (int k = 0; k < top_k; k++) {\n"
"        int best = -1; float best_v = -1e30f;\n"
"        for (int e = 0; e < n_experts; e++) {\n"
"            if (local[e] > best_v) { best_v = local[e]; best = e; }\n"
"        }\n"
"        if (best < 0) break;\n"
"        wrow[best] = best_v;\n"
"        local[best] = -1e30f;\n"
"    }\n"
"}\n"
"\n"

"/* ---- moe_weighted_add_f32 ----\n"
" * acc[t,j] += weights[t, expert_idx] * src[t,j].  One thread per element. */\n"
"__global__ void moe_weighted_add_f32(float *__restrict__ acc,\n"
"                                      const float *__restrict__ src,\n"
"                                      const float *__restrict__ weights,\n"
"                                      int expert_idx, int n_experts,\n"
"                                      int N_tok, int H_dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    long total = (long)N_tok * H_dim;\n"
"    if (i >= total) return;\n"
"    int t = i / H_dim;\n"
"    float w = weights[(long)t * n_experts + expert_idx];\n"
"    if (w == 0.f) return;\n"
"    acc[i] += w * src[i];\n"
"}\n"
"\n"
"/* ---- moe_dispatch_build_f32 ----\n"
" * Build per-expert token permutations.\n"
" * In : weights [N_tok, n_experts] (only top-K entries non-zero)\n"
" * Out: counts  [n_experts] — number of tokens that picked each expert\n"
" *      perm    [n_experts, N_tok] — token indices per expert (first counts[e] entries valid)\n"
" * One thread per token.  Atomic add into counts[e] yields the slot index. */\n"
"__global__ void moe_dispatch_build_f32(const float *__restrict__ weights,\n"
"                                         int *__restrict__ counts,\n"
"                                         int *__restrict__ perm,\n"
"                                         int N_tok, int n_experts) {\n"
"    int t = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (t >= N_tok) return;\n"
"    for (int e = 0; e < n_experts; e++) {\n"
"        if (weights[(long)t * n_experts + e] != 0.f) {\n"
"            int pos = atomicAdd(&counts[e], 1);\n"
"            perm[(long)e * N_tok + pos] = t;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* ---- moe_gather_f16 ----\n"
" * dst[k, :] = src[perm[k], :]  for k in 0..n_rows-1.\n"
" * Grid: (ceil(dim/256), n_rows). Block: 256. */\n"
"__global__ void moe_gather_f16(half_raw *__restrict__ dst,\n"
"                                 const half_raw *__restrict__ src,\n"
"                                 const int *__restrict__ perm,\n"
"                                 int n_rows, int dim) {\n"
"    int row = blockIdx.y;\n"
"    if (row >= n_rows) return;\n"
"    int j = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (j >= dim) return;\n"
"    int t = perm[row];\n"
"    dst[(long)row * dim + j] = src[(long)t * dim + j];\n"
"}\n"
"\n"
"/* ---- moe_scatter_weighted_add_f16_to_f32 ----\n"
" * acc[perm[k], j] += weights[perm[k], expert_idx] * f32(src[k, j])\n"
" * No atomics needed: distinct experts run sequentially in the stream;\n"
" * within one expert each row k maps to a unique token t. */\n"
"__global__ void moe_scatter_weighted_add_f16_to_f32(\n"
"    float *__restrict__ acc, const half_raw *__restrict__ src,\n"
"    const int *__restrict__ perm, const float *__restrict__ weights,\n"
"    int expert_idx, int n_experts, int n_rows, int H_dim) {\n"
"    int row = blockIdx.y;\n"
"    if (row >= n_rows) return;\n"
"    int j = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (j >= H_dim) return;\n"
"    int t = perm[row];\n"
"    float w = weights[(long)t * n_experts + expert_idx];\n"
"    float v = half_to_float(src[(long)row * H_dim + j]);\n"
"    acc[(long)t * H_dim + j] += w * v;\n"
"}\n"
"\n"

"/* ---- cast helpers (f32 <-> f16) for boundary conversions ---- */\n"
"__global__ void cast_f32_to_f16(half_raw *dst, const float *src, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] = float_to_half_raw(src[i]);\n"
"}\n"
"\n"
"__global__ void cast_f16_to_f32(float *dst, const half_raw *src, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] = half_to_float(src[i]);\n"
"}\n"
"\n"

/* -------------------------------------------------------------------- */
/* Flash-attention WMMA on gfx12 (fp16 in/out, f32 softmax accum).       */
/* Uses the f16 WMMA intrinsic so PyTorch's fp16 SDPA rounding is        */
/* matched (no bf16 truncation). Algorithm mirrors                       */
/* trellis2/flash_attn_sa_wmma_f32 / cross_attn_wmma_f32.                */
/* -------------------------------------------------------------------- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"#define HY3D_SWZ(v, MASK) (__extension__ ({                            \\\n"
"    int _b; __builtin_memcpy(&_b, &(v), 4);                            \\\n"
"    int _r = __builtin_amdgcn_ds_swizzle(_b, ((MASK) << 10) | 0x1F);   \\\n"
"    float _vr; __builtin_memcpy(&_vr, &_r, 4); _vr; }))\n"
"#else\n"
"#define HY3D_SWZ(v, MASK) __shfl_xor((v), (MASK))\n"
"#endif\n\n"

/* Self-attention: head_dim=128, q_len=N, k_len=N. Q/K/V/out all fp16
 * row-major [N, n_heads*128]. Grid: (n_heads, ceil(N/64)). Block: 128 (4 waves). */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void flash_attn_sa_f16_wmma(half_raw *__restrict__ out,\n"
"    const half_raw *__restrict__ Q, const half_raw *__restrict__ K,\n"
"    const half_raw *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    (void)head_dim;\n"
"    int h = blockIdx.x;\n"
"    int cta_q0 = blockIdx.y * 64;\n"
"    int tid = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int half2_ = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int dim = n_heads * 128;\n"
"    float scale = rsqrtf(128.f);\n"
"    enum { K_STRIDE = 132, Q_STRIDE = 132, V_STRIDE = 18 };\n"
"    __shared__ short smK[16*K_STRIDE];\n"
"    __shared__ short smVt[128*V_STRIDE];\n"
"    __shared__ short smQ[4*16*Q_STRIDE];\n"
"    __shared__ short smP[4*16*16];\n"
"    short *myQ = smQ + wave * (16*Q_STRIDE);\n"
"    short *myP = smP + wave * (16*16);\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short f16x8 __attribute__((ext_vector_type(8)));\n"
"    int wq0 = cta_q0 + wave * 16;\n"
"    /* Load my Q rows (16x128) into LDS as fp16 (direct copy of shorts). */\n"
"    for (int it = 0; it < 64; it++) {\n"
"        int e = lane * 64 + it;\n"
"        int r = e >> 7;\n"
"        int d = e & 127;\n"
"        int qi = wq0 + r;\n"
"        myQ[r*Q_STRIDE + d] = (qi < N) ? (short)Q[(long)qi*dim + h*128 + d] : (short)0;\n"
"    }\n"
"    float8 O0={0,0,0,0,0,0,0,0}, O1=O0,O2=O0,O3=O0,O4=O0,O5=O0,O6=O0,O7=O0;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv = (N + 15) / 16;\n"
"    for (int kv = 0; kv < n_kv; kv++) {\n"
"        int kv_base = kv * 16;\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            smK[r*K_STRIDE + d] = (kvi < N) ? (short)K[(long)kvi*dim + h*128 + d] : (short)0;\n"
"        }\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            smVt[d*V_STRIDE + r] = (kvi < N) ? (short)V[(long)kvi*dim + h*128 + d] : (short)0;\n"
"        }\n"
"        __syncthreads();\n"
"        float8 S = {0,0,0,0,0,0,0,0};\n"
"        for (int kt = 0; kt < 8; kt++) {\n"
"            int k_off = kt * 16 + half2_ * 8;\n"
"            f16x8 qa, kb;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                qa[i] = myQ[idx*Q_STRIDE + k_off + i];\n"
"                kb[i] = smK[idx*K_STRIDE + k_off + i];\n"
"            }\n"
"            S = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(qa, kb, S);\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float s = S[i] * scale;\n"
"            int kvi_col = kv_base + idx;\n"
"            if (kvi_col >= N) s = -1e30f;\n"
"            S[i] = s;\n"
"            float m = s;\n"
"            m = fmaxf(m, HY3D_SWZ(m, 1));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 2));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 4));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 8));\n"
"            row_max[i] = m;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float m_new = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = __expf(m_i[i] - m_new);\n"
"            float p = __expf(S[i] - m_new);\n"
"            S[i] = p;\n"
"            float rs = p;\n"
"            rs += HY3D_SWZ(rs, 1);\n"
"            rs += HY3D_SWZ(rs, 2);\n"
"            rs += HY3D_SWZ(rs, 4);\n"
"            rs += HY3D_SWZ(rs, 8);\n"
"            l_i[i] = l_i[i] * alpha[i] + rs;\n"
"            m_i[i] = m_new;\n"
"        }\n"
"        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"        for (int t = 0; t < 8; t++)\n"
"            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = half2_*8 + i;\n"
"            myP[row*16 + idx] = (short)float_to_half_raw(S[i]);\n"
"        }\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        f16x8 pa;\n"
"        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half2_*8 + i];\n"
"        for (int t = 0; t < 8; t++) {\n"
"            int hd_base = t * 16;\n"
"            f16x8 vb;\n"
"            for (int i = 0; i < 8; i++) vb[i] = smVt[(hd_base + idx)*V_STRIDE + half2_*8 + i];\n"
"            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(pa, vb, *Os[t]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"    float inv_l[8];\n"
"    for (int i = 0; i < 8; i++)\n"
"        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = t*16 + idx;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int qi = wq0 + half2_*8 + i;\n"
"            if (qi < N)\n"
"                out[(long)qi*dim + h*128 + col] = float_to_half_raw((*Os[t])[i] * inv_l[i]);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n\n"

/* Cross-attention (asymmetric q_len/kv_len). dim = n_heads * head_dim,
 * head_dim must be 128. q_len must be a multiple of 64 (CTA Br); set blockIdx.y
 * to ceil(q_len/64). kv_len arbitrary; last partial KV tile is masked. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void cross_attn_f16_wmma(half_raw *__restrict__ out,\n"
"    const half_raw *__restrict__ Q, const half_raw *__restrict__ K,\n"
"    const half_raw *__restrict__ V,\n"
"    int q_len, int kv_len, int dim, int n_heads, int head_dim, float scale) {\n"
"    (void)head_dim;\n"
"    int h = blockIdx.x;\n"
"    int cta_q0 = blockIdx.y * 64;\n"
"    int tid = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int half2_ = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    enum { K_STRIDE = 132, V_STRIDE = 18 };\n"
"    __shared__ short smK[16*K_STRIDE];\n"
"    __shared__ short smVt[128*V_STRIDE];\n"
"    __shared__ short smQ[4*16*128];\n"
"    __shared__ short smP[4*16*16];\n"
"    short *myQ = smQ + wave * (16*128);\n"
"    short *myP = smP + wave * (16*16);\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short f16x8 __attribute__((ext_vector_type(8)));\n"
"    int wq0 = cta_q0 + wave * 16;\n"
"    for (int it = 0; it < 64; it++) {\n"
"        int e = lane * 64 + it;\n"
"        int r = e >> 7;\n"
"        int d = e & 127;\n"
"        int qi = wq0 + r;\n"
"        myQ[r*128 + d] = (qi < q_len) ? (short)Q[(long)qi*dim + h*128 + d] : (short)0;\n"
"    }\n"
"    float8 O0={0,0,0,0,0,0,0,0}, O1=O0,O2=O0,O3=O0,O4=O0,O5=O0,O6=O0,O7=O0;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv_tiles = (kv_len + 15) / 16;\n"
"    for (int kv = 0; kv < n_kv_tiles; kv++) {\n"
"        int kv_base = kv * 16;\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            smK[r*K_STRIDE + d] = (kvi < kv_len) ? (short)K[(long)kvi*dim + h*128 + d] : (short)0;\n"
"        }\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            smVt[d*V_STRIDE + r] = (kvi < kv_len) ? (short)V[(long)kvi*dim + h*128 + d] : (short)0;\n"
"        }\n"
"        __syncthreads();\n"
"        float8 S = {0,0,0,0,0,0,0,0};\n"
"        for (int kt = 0; kt < 8; kt++) {\n"
"            int k_off = kt * 16 + half2_ * 8;\n"
"            f16x8 qa, kb;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                qa[i] = myQ[idx*128 + k_off + i];\n"
"                kb[i] = smK[idx*K_STRIDE + k_off + i];\n"
"            }\n"
"            S = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(qa, kb, S);\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float s = S[i] * scale;\n"
"            int kvi_col = kv_base + idx;\n"
"            if (kvi_col >= kv_len) s = -1e30f;\n"
"            S[i] = s;\n"
"            float m = s;\n"
"            m = fmaxf(m, HY3D_SWZ(m, 1));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 2));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 4));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 8));\n"
"            row_max[i] = m;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float m_new = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = __expf(m_i[i] - m_new);\n"
"            float p = __expf(S[i] - m_new);\n"
"            S[i] = p;\n"
"            float rs = p;\n"
"            rs += HY3D_SWZ(rs, 1);\n"
"            rs += HY3D_SWZ(rs, 2);\n"
"            rs += HY3D_SWZ(rs, 4);\n"
"            rs += HY3D_SWZ(rs, 8);\n"
"            l_i[i] = l_i[i] * alpha[i] + rs;\n"
"            m_i[i] = m_new;\n"
"        }\n"
"        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"        for (int t = 0; t < 8; t++)\n"
"            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = half2_*8 + i;\n"
"            myP[row*16 + idx] = (short)float_to_half_raw(S[i]);\n"
"        }\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        f16x8 pa;\n"
"        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half2_*8 + i];\n"
"        for (int t = 0; t < 8; t++) {\n"
"            int hd_base = t * 16;\n"
"            f16x8 vb;\n"
"            for (int i = 0; i < 8; i++) vb[i] = smVt[(hd_base + idx)*V_STRIDE + half2_*8 + i];\n"
"            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(pa, vb, *Os[t]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"    float inv_l[8];\n"
"    for (int i = 0; i < 8; i++)\n"
"        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = t*16 + idx;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int qi = wq0 + half2_*8 + i;\n"
"            if (qi < q_len)\n"
"                out[(long)qi*dim + h*128 + col] = float_to_half_raw((*Os[t])[i] * inv_l[i]);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n\n"

/* -------------------------------------------------------------------- */
/* hd=64 variants for ShapeVAE (self+cross). Same online-softmax pattern.*/
/* -------------------------------------------------------------------- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void flash_attn_sa_f16_wmma_hd64(half_raw *__restrict__ out,\n"
"    const half_raw *__restrict__ Q, const half_raw *__restrict__ K,\n"
"    const half_raw *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    (void)head_dim;\n"
"    int h = blockIdx.x;\n"
"    int cta_q0 = blockIdx.y * 64;\n"
"    int tid = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int half2_ = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int dim = n_heads * 64;\n"
"    float scale = rsqrtf(64.f);\n"
"    enum { K_STRIDE = 68 };\n"
"    __shared__ short smK[16*K_STRIDE];\n"
"    __shared__ short smVt[64*16];\n"
"    __shared__ short smQ[4*16*64];\n"
"    __shared__ short smP[4*16*16];\n"
"    short *myQ = smQ + wave * (16*64);\n"
"    short *myP = smP + wave * (16*16);\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short f16x8 __attribute__((ext_vector_type(8)));\n"
"    int wq0 = cta_q0 + wave * 16;\n"
"    /* Q [16x64] per wave. 32 lanes × 32 elems = 1024. */\n"
"    for (int it = 0; it < 32; it++) {\n"
"        int e = lane * 32 + it;\n"
"        int r = e >> 6;\n"
"        int d = e & 63;\n"
"        int qi = wq0 + r;\n"
"        myQ[r*64 + d] = (qi < N) ? (short)Q[(long)qi*dim + h*64 + d] : (short)0;\n"
"    }\n"
"    float8 O0={0,0,0,0,0,0,0,0}, O1=O0, O2=O0, O3=O0;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv = (N + 15) / 16;\n"
"    for (int kv = 0; kv < n_kv; kv++) {\n"
"        int kv_base = kv * 16;\n"
"        /* K/V [16x64] = 1024 elems per matrix. 128 threads × 8 = 1024. */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int r = e >> 6;\n"
"            int d = e & 63;\n"
"            int kvi = kv_base + r;\n"
"            smK[r*K_STRIDE + d] = (kvi < N) ? (short)K[(long)kvi*dim + h*64 + d] : (short)0;\n"
"        }\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int r = e >> 6;\n"
"            int d = e & 63;\n"
"            int kvi = kv_base + r;\n"
"            smVt[d*16 + r] = (kvi < N) ? (short)V[(long)kvi*dim + h*64 + d] : (short)0;\n"
"        }\n"
"        __syncthreads();\n"
"        float8 S = {0,0,0,0,0,0,0,0};\n"
"        for (int kt = 0; kt < 4; kt++) {\n"
"            int k_off = kt * 16 + half2_ * 8;\n"
"            f16x8 qa, kb;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                qa[i] = myQ[idx*64 + k_off + i];\n"
"                kb[i] = smK[idx*K_STRIDE + k_off + i];\n"
"            }\n"
"            S = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(qa, kb, S);\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float s = S[i] * scale;\n"
"            int kvi_col = kv_base + idx;\n"
"            if (kvi_col >= N) s = -1e30f;\n"
"            S[i] = s;\n"
"            float m = s;\n"
"            m = fmaxf(m, HY3D_SWZ(m, 1));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 2));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 4));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 8));\n"
"            row_max[i] = m;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float m_new = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = __expf(m_i[i] - m_new);\n"
"            float p = __expf(S[i] - m_new);\n"
"            S[i] = p;\n"
"            float rs = p;\n"
"            rs += HY3D_SWZ(rs, 1);\n"
"            rs += HY3D_SWZ(rs, 2);\n"
"            rs += HY3D_SWZ(rs, 4);\n"
"            rs += HY3D_SWZ(rs, 8);\n"
"            l_i[i] = l_i[i] * alpha[i] + rs;\n"
"            m_i[i] = m_new;\n"
"        }\n"
"        float8 *Os[4] = {&O0,&O1,&O2,&O3};\n"
"        for (int t = 0; t < 4; t++)\n"
"            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = half2_*8 + i;\n"
"            myP[row*16 + idx] = (short)float_to_half_raw(S[i]);\n"
"        }\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        f16x8 pa;\n"
"        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half2_*8 + i];\n"
"        for (int t = 0; t < 4; t++) {\n"
"            int hd_base = t * 16;\n"
"            f16x8 vb;\n"
"            for (int i = 0; i < 8; i++) vb[i] = smVt[(hd_base + idx)*16 + half2_*8 + i];\n"
"            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(pa, vb, *Os[t]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float8 *Os[4] = {&O0,&O1,&O2,&O3};\n"
"    float inv_l[8];\n"
"    for (int i = 0; i < 8; i++)\n"
"        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;\n"
"    for (int t = 0; t < 4; t++) {\n"
"        int col = t*16 + idx;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int qi = wq0 + half2_*8 + i;\n"
"            if (qi < N)\n"
"                out[(long)qi*dim + h*64 + col] = float_to_half_raw((*Os[t])[i] * inv_l[i]);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n\n"

"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void cross_attn_f16_wmma_hd64(half_raw *__restrict__ out,\n"
"    const half_raw *__restrict__ Q, const half_raw *__restrict__ K,\n"
"    const half_raw *__restrict__ V,\n"
"    int q_len, int kv_len, int dim, int n_heads, int head_dim, float scale) {\n"
"    (void)head_dim;\n"
"    int h = blockIdx.x;\n"
"    int cta_q0 = blockIdx.y * 64;\n"
"    int tid = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int half2_ = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    enum { K_STRIDE = 68, V_STRIDE = 18 };\n"
"    __shared__ short smK[16*K_STRIDE];\n"
"    __shared__ short smVt[64*V_STRIDE];\n"
"    __shared__ short smQ[4*16*64];\n"
"    __shared__ short smP[4*16*16];\n"
"    short *myQ = smQ + wave * (16*64);\n"
"    short *myP = smP + wave * (16*16);\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short f16x8 __attribute__((ext_vector_type(8)));\n"
"    int wq0 = cta_q0 + wave * 16;\n"
"    for (int it = 0; it < 32; it++) {\n"
"        int e = lane * 32 + it;\n"
"        int r = e >> 6;\n"
"        int d = e & 63;\n"
"        int qi = wq0 + r;\n"
"        myQ[r*64 + d] = (qi < q_len) ? (short)Q[(long)qi*dim + h*64 + d] : (short)0;\n"
"    }\n"
"    float8 O0={0,0,0,0,0,0,0,0}, O1=O0, O2=O0, O3=O0;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv_tiles = (kv_len + 15) / 16;\n"
"    for (int kv = 0; kv < n_kv_tiles; kv++) {\n"
"        int kv_base = kv * 16;\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int r = e >> 6;\n"
"            int d = e & 63;\n"
"            int kvi = kv_base + r;\n"
"            smK[r*K_STRIDE + d] = (kvi < kv_len) ? (short)K[(long)kvi*dim + h*64 + d] : (short)0;\n"
"        }\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int r = e >> 6;\n"
"            int d = e & 63;\n"
"            int kvi = kv_base + r;\n"
"            smVt[d*V_STRIDE + r] = (kvi < kv_len) ? (short)V[(long)kvi*dim + h*64 + d] : (short)0;\n"
"        }\n"
"        __syncthreads();\n"
"        float8 S = {0,0,0,0,0,0,0,0};\n"
"        for (int kt = 0; kt < 4; kt++) {\n"
"            int k_off = kt * 16 + half2_ * 8;\n"
"            f16x8 qa, kb;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                qa[i] = myQ[idx*64 + k_off + i];\n"
"                kb[i] = smK[idx*K_STRIDE + k_off + i];\n"
"            }\n"
"            S = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(qa, kb, S);\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float s = S[i] * scale;\n"
"            int kvi_col = kv_base + idx;\n"
"            if (kvi_col >= kv_len) s = -1e30f;\n"
"            S[i] = s;\n"
"            float m = s;\n"
"            m = fmaxf(m, HY3D_SWZ(m, 1));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 2));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 4));\n"
"            m = fmaxf(m, HY3D_SWZ(m, 8));\n"
"            row_max[i] = m;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float m_new = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = __expf(m_i[i] - m_new);\n"
"            float p = __expf(S[i] - m_new);\n"
"            S[i] = p;\n"
"            float rs = p;\n"
"            rs += HY3D_SWZ(rs, 1);\n"
"            rs += HY3D_SWZ(rs, 2);\n"
"            rs += HY3D_SWZ(rs, 4);\n"
"            rs += HY3D_SWZ(rs, 8);\n"
"            l_i[i] = l_i[i] * alpha[i] + rs;\n"
"            m_i[i] = m_new;\n"
"        }\n"
"        float8 *Os[4] = {&O0,&O1,&O2,&O3};\n"
"        for (int t = 0; t < 4; t++)\n"
"            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = half2_*8 + i;\n"
"            myP[row*16 + idx] = (short)float_to_half_raw(S[i]);\n"
"        }\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        f16x8 pa;\n"
"        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half2_*8 + i];\n"
"        for (int t = 0; t < 4; t++) {\n"
"            int hd_base = t * 16;\n"
"            f16x8 vb;\n"
"            for (int i = 0; i < 8; i++) vb[i] = smVt[(hd_base + idx)*V_STRIDE + half2_*8 + i];\n"
"            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(pa, vb, *Os[t]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float8 *Os[4] = {&O0,&O1,&O2,&O3};\n"
"    float inv_l[8];\n"
"    for (int i = 0; i < 8; i++)\n"
"        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;\n"
"    for (int t = 0; t < 4; t++) {\n"
"        int col = t*16 + idx;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int qi = wq0 + half2_*8 + i;\n"
"            if (qi < q_len)\n"
"                out[(long)qi*dim + h*64 + col] = float_to_half_raw((*Os[t])[i] * inv_l[i]);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n\n"

/* Close the extern "C" block opened by hip_kernels_common_src */
"} /* extern C */\n"
;

#endif /* HIP_HY3D_KERNELS_H */
