/*
 * hip_kernels_common.h - Shared HIP kernel source string for DA3/PPD runners
 *
 * Contains shared kernels as a C string literal for HIPRTC compilation.
 * Each runner concatenates this with its model-specific kernels before HIPRTC.
 *
 * Includes extern "C" { at start. The runner's specific kernel string
 * must include the closing } at its end.
 *
 * Port of cuda_kernels_common.h for ROCm/HIP (RDNA4, gfx1201).
 * Key differences from CUDA version:
 *   - PTX inline ASM replaced with HIP builtins (__half2float, etc.)
 *   - MMA/tensor core kernels removed (RDNA4 has no MMA)
 *   - gemm_tiled_f16_f32 is the PRIMARY GEMM kernel
 *   - __shfl_xor_sync -> __shfl_xor (no sync mask on HIP)
 *   - __shfl_down_sync -> __shfl_down
 *   - FP8 GEMM removed (no hardware FP8 MMA on RDNA4)
 */
#ifndef HIP_KERNELS_COMMON_H
#define HIP_KERNELS_COMMON_H

static const char hip_kernels_common_src[] =
"typedef unsigned short half_raw;\n"
"__device__ __forceinline__ float half_to_float(half_raw h) {\n"
"    __half hv;\n"
"    *((unsigned short*)&hv) = h;\n"
"    return __half2float(hv);\n"
"}\n"
"\n"
"extern \"C\" {\n"
"\n"
"/* ---- layernorm_f32 ---- */\n"
"__global__ void layernorm_f32(float *dst, const float *src, const float *w,\n"
"                               const float *b, int dim, float eps) {\n"
"    extern __shared__ float sdata[];\n"
"    int tok = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    const float *x = src + tok * dim;\n"
"    float *y = dst + tok * dim;\n"
"    float s = 0.0f;\n"
"    for (int i = tid; i < dim; i += nt) s += x[i];\n"
"    sdata[tid] = s;\n"
"    __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    s = 0.0f;\n"
"    for (int i = tid; i < dim; i += nt) { float d = x[i] - mean; s += d*d; }\n"
"    sdata[tid] = s;\n"
"    __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + eps);\n"
"    for (int i = tid; i < dim; i += nt)\n"
"        y[i] = (x[i] - mean) * inv * w[i] + b[i];\n"
"}\n"
"\n"
"/* ---- gemm_tiled_f16_f32: shared-memory tiled GEMM (PRIMARY GEMM for RDNA4) ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16)=256 threads           */\n"
"__global__ void gemm_tiled_f16_f32(float *Y, const half_raw *W, const float *X,\n"
"                                    const float *bias,\n"
"                                    int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w_out = out_base + tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? half_to_float(W[(size_t)w_out*n_in + k+ty]) : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w_out = out_base+16+tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? half_to_float(W[(size_t)w_out*n_in + k+ty]) : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w_out = out_base+32+tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? half_to_float(W[(size_t)w_out*n_in + k+ty]) : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w_out = out_base+48+tx;\n"
"          smB[ty][tx] = (w_out < n_out && k+ty < n_in)\n"
"                        ? half_to_float(W[(size_t)w_out*n_in + k+ty]) : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"
"/* ---- add_bias_f32 ---- */\n"
"__global__ void add_bias_f32(float *Y, const float *bias, int n_out, int n_tok) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n_out * n_tok) Y[i] += bias[i % n_out];\n"
"}\n"
"\n"
"/* ---- attn_prefill_f32: Tiled FlashAttention for prefill (no MMA, RDNA4) ---- */\n"
"/* Uses flash_attn_tiled_f32 below instead of MMA-based version */\n"
"\n"
"/* ---- gelu_f32 ---- */\n"
"__global__ void gelu_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) {\n"
"        float v = x[i];\n"
"        x[i] = 0.5f * v * (1.0f + tanhf(0.7978845608f * (v + 0.044715f * v*v*v)));\n"
"    }\n"
"}\n"
"\n"
"/* ---- add_f32 ---- */\n"
"__global__ void add_f32(float *dst, const float *src, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] += src[i];\n"
"}\n"
"\n"
"/* ---- silu_f32 ---- */\n"
"__global__ void silu_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) {\n"
"        float v = x[i];\n"
"        x[i] = v / (1.0f + expf(-v));\n"
"    }\n"
"}\n"
"\n"
"/* ---- relu_f32 ---- */\n"
"__global__ void relu_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] = x[i] > 0 ? x[i] : 0;\n"
"}\n"
"\n"
"/* ---- flash_attn_tiled_f32: tiled FlashAttention (no MMA) ---- */\n"
"/* Grid: (n_heads, ceil(n_tok/FA_BQ)), blockDim=(FA_BQ=64)       */\n"
"#ifndef FA_BQ\n"
"#define FA_BQ       64\n"
"#define FA_BKV      16\n"
"#define FA_HEAD_DIM 64\n"
"#endif\n"
"__global__ void flash_attn_tiled_f32(float *out, const float *qkv,\n"
"                                      const float *K_t, const float *V_t,\n"
"                                      int n_tok, int dim, int n_heads,\n"
"                                      int head_dim, float scale) {\n"
"    int h  = blockIdx.x;\n"
"    int qi = blockIdx.y * FA_BQ + threadIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int dim3 = 3 * dim;\n"
"    const float *qt   = qkv + (qi < n_tok ? qi : 0) * dim3 + h * head_dim;\n"
"    const float *kt_h = K_t + (size_t)h * n_tok * head_dim;\n"
"    const float *vt_h = V_t + (size_t)h * n_tok * head_dim;\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem;\n"
"    float *smV = smem + FA_BKV * FA_HEAD_DIM;\n"
"    float q_reg[FA_HEAD_DIM];\n"
"    for (int d = 0; d < FA_HEAD_DIM; d++)\n"
"        q_reg[d] = (qi < n_tok) ? qt[d] : 0.0f;\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_i[FA_HEAD_DIM];\n"
"    for (int d = 0; d < FA_HEAD_DIM; d++) O_i[d] = 0.0f;\n"
"    int tid = threadIdx.x;\n"
"    int kv_tiles = (n_tok + FA_BKV - 1) / FA_BKV;\n"
"    for (int tile = 0; tile < kv_tiles; tile++) {\n"
"        int kv = tile * FA_BKV;\n"
"        for (int idx = tid; idx < FA_BKV * FA_HEAD_DIM; idx += FA_BQ) {\n"
"            int kj = idx / FA_HEAD_DIM, d = idx % FA_HEAD_DIM;\n"
"            int kv_tok = kv + kj;\n"
"            smK[idx] = (kv_tok < n_tok) ? kt_h[(size_t)kv_tok * FA_HEAD_DIM + d] : 0.0f;\n"
"            smV[idx] = (kv_tok < n_tok) ? vt_h[(size_t)kv_tok * FA_HEAD_DIM + d] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        float sc[FA_BKV];\n"
"        for (int kj = 0; kj < FA_BKV; kj++) sc[kj] = 0.0f;\n"
"        for (int d = 0; d < FA_HEAD_DIM; d++) {\n"
"            float qd = q_reg[d];\n"
"            for (int kj = 0; kj < FA_BKV; kj++)\n"
"                sc[kj] += qd * smK[kj * FA_HEAD_DIM + d];\n"
"        }\n"
"        float mx_tile = -1e30f;\n"
"        for (int kj = 0; kj < FA_BKV; kj++) {\n"
"            sc[kj] = (kv + kj < n_tok) ? sc[kj] * scale : -1e30f;\n"
"            if (sc[kj] > mx_tile) mx_tile = sc[kj];\n"
"        }\n"
"        float mn_i  = fmaxf(m_i, mx_tile);\n"
"        float alpha = expf(m_i - mn_i);\n"
"        l_i *= alpha;\n"
"        for (int d = 0; d < FA_HEAD_DIM; d++) O_i[d] *= alpha;\n"
"        m_i = mn_i;\n"
"        float ej[FA_BKV];\n"
"        for (int kj = 0; kj < FA_BKV; kj++) {\n"
"            ej[kj] = (kv + kj < n_tok) ? expf(sc[kj] - m_i) : 0.0f;\n"
"            l_i += ej[kj];\n"
"        }\n"
"        for (int kj = 0; kj < FA_BKV; kj++) {\n"
"            float e = ej[kj];\n"
"            for (int d = 0; d < FA_HEAD_DIM; d++) O_i[d] += e * smV[kj * FA_HEAD_DIM + d];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (qi < n_tok) {\n"
"        float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        float *out_qi = out + (size_t)qi * dim + h * head_dim;\n"
"        for (int d = 0; d < FA_HEAD_DIM; d++)\n"
"            out_qi[d] = O_i[d] * inv_l;\n"
"    }\n"
"}\n"
"\n"
"/* ---- resize_normalize: bilinear resize + ImageNet normalize ---- */\n"
"__global__ void resize_normalize(float *dst, const unsigned char *src,\n"
"                                  int src_w, int src_h, int dst_w, int dst_h,\n"
"                                  float mean0, float mean1, float mean2,\n"
"                                  float istd0, float istd1, float istd2) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = dst_h * dst_w;\n"
"    if (idx >= total) return;\n"
"    int oh = idx / dst_w, ow = idx % dst_w;\n"
"    float fy = (dst_h > 1) ? (float)oh * (src_h-1) / (dst_h-1) : 0.0f;\n"
"    float fx = (dst_w > 1) ? (float)ow * (src_w-1) / (dst_w-1) : 0.0f;\n"
"    int y0 = (int)fy, x0 = (int)fx;\n"
"    int y1 = (y0+1 < src_h) ? y0+1 : y0;\n"
"    int x1 = (x0+1 < src_w) ? x0+1 : x0;\n"
"    float dy = fy - y0, dx = fx - x0;\n"
"    float mean[3] = {mean0, mean1, mean2};\n"
"    float istd[3] = {istd0, istd1, istd2};\n"
"    for (int c = 0; c < 3; c++) {\n"
"        float v = (float)src[(y0*src_w+x0)*3+c] * (1-dy)*(1-dx)\n"
"                + (float)src[(y0*src_w+x1)*3+c] * (1-dy)*dx\n"
"                + (float)src[(y1*src_w+x0)*3+c] * dy*(1-dx)\n"
"                + (float)src[(y1*src_w+x1)*3+c] * dy*dx;\n"
"        dst[c * total + idx] = (v / 255.0f - mean[c]) * istd[c];\n"
"    }\n"
"}\n"
"\n"
"/* ---- patch_embed_conv2d ---- */\n"
"__global__ void patch_embed_conv2d(float *out, const float *img, const float *w,\n"
"                                    const float *bias, int gw, int dim, int ps,\n"
"                                    int img_w) {\n"
"    int patch = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    int py = patch / gw, px = patch % gw;\n"
"    int tok = 1 + patch;\n"
"    for (int co = tid; co < dim; co += blockDim.x) {\n"
"        float sum = bias ? bias[co] : 0.0f;\n"
"        for (int ci = 0; ci < 3; ci++)\n"
"            for (int kh = 0; kh < ps; kh++)\n"
"                for (int kw = 0; kw < ps; kw++)\n"
"                    sum += w[((co*3+ci)*ps+kh)*ps+kw]\n"
"                         * img[ci * img_w * img_w + (py*ps+kh) * img_w + (px*ps+kw)];\n"
"        out[tok * dim + co] = sum;\n"
"    }\n"
"}\n"
"\n"
"/* ---- cls_pos_embed ---- */\n"
"__global__ void cls_pos_embed(float *hidden, const float *cls, const float *pos,\n"
"                               int n_tok, int dim) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= n_tok * dim) return;\n"
"    int t = idx / dim;\n"
"    if (t == 0)\n"
"        hidden[idx] = cls[idx] + pos[idx];\n"
"    else\n"
"        hidden[idx] += pos[idx];\n"
"}\n"
"\n"
"/* ---- bilinear_upsample_f32 ---- */\n"
"__global__ void bilinear_upsample_f32(float *dst, const float *src,\n"
"                                       int C, int Hi, int Wi, int Ho, int Wo) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * Ho * Wo;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (Ho * Wo);\n"
"    int rem = idx % (Ho * Wo);\n"
"    int oh = rem / Wo, ow = rem % Wo;\n"
"    float fy = (Ho > 1) ? (float)oh * (Hi-1) / (Ho-1) : 0.0f;\n"
"    float fx = (Wo > 1) ? (float)ow * (Wi-1) / (Wo-1) : 0.0f;\n"
"    int y0 = (int)fy, x0 = (int)fx;\n"
"    int y1 = (y0+1 < Hi) ? y0+1 : y0;\n"
"    int x1 = (x0+1 < Wi) ? x0+1 : x0;\n"
"    float dy = fy - y0, dx = fx - x0;\n"
"    const float *s = src + c * Hi * Wi;\n"
"    dst[idx] = s[y0*Wi+x0]*(1-dy)*(1-dx) + s[y0*Wi+x1]*(1-dy)*dx\n"
"             + s[y1*Wi+x0]*dy*(1-dx) + s[y1*Wi+x1]*dy*dx;\n"
"}\n"
"\n"
"/* ---- kv_transpose: deinterleave K,V from QKV to contiguous per-head layout ---- */\n"
"__global__ void kv_transpose(float *K_t, float *V_t, const float *qkv,\n"
"                              int n_tok, int dim, int n_heads, int head_dim) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = n_tok * dim;\n"
"    if (idx >= total) return;\n"
"    int tok = idx / dim;\n"
"    int hd_idx = idx % dim;\n"
"    int h = hd_idx / head_dim;\n"
"    int d = hd_idx % head_dim;\n"
"    int dim3 = 3 * dim;\n"
"    int dst_idx = h * n_tok * head_dim + tok * head_dim + d;\n"
"    K_t[dst_idx] = qkv[tok * dim3 + dim + hd_idx];\n"
"    V_t[dst_idx] = qkv[tok * dim3 + 2*dim + hd_idx];\n"
"}\n"
"\n"
/* NOTE: No closing extern "C" brace here.
 * Each runner's specific kernel string must end with: } */
;

#endif /* HIP_KERNELS_COMMON_H */
