/*
 * hip_flux2_kernels.h - HIP kernel source strings for Flux.2 Klein 4B
 *
 * Contains all Flux2-specific HIP kernels as a C string literal for
 * HIPRTC runtime compilation. Concatenated after hip_kernels_common_src
 * (which opens extern "C" {) and closes it at the end.
 *
 * Port of cuda_flux2_runner.h kernels for AMD ROCm/HIP (RDNA4, gfx1201).
 * Key differences from CUDA version:
 *   - __shfl_xor_sync -> __shfl_xor (no sync mask on HIP)
 *   - __shfl_down_sync -> __shfl_down
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_FLUX2_KERNELS_H
#define HIP_FLUX2_KERNELS_H

static const char hip_flux2_specific_kernels[] =
"\n"

/* ---- FP8 LUT for weight dequantization (populated from host) ---- */
"__device__ __constant__ float d_fp8_to_f32_lut[256];\n"
"\n"

/* ---- Helpers for FP8 WMMA path (gfx12/RDNA4 only) ---- */
"static __device__ __forceinline__ unsigned char f32_to_fp8e4m3_rtne(float f) {\n"
"    if (f != f) return 0x7F;\n"
"    /* Clamp to FP8 E4M3 max (448) */\n"
"    const float FP8_MAX = 448.0f;\n"
"    if (f >  FP8_MAX) f =  FP8_MAX;\n"
"    if (f < -FP8_MAX) f = -FP8_MAX;\n"
"    unsigned int bits; memcpy(&bits, &f, 4);\n"
"    unsigned int sign = (bits >> 31) & 1u;\n"
"    int exp = (int)((bits >> 23) & 0xFFu) - 127;\n"
"    unsigned int mant23 = bits & 0x7FFFFFu;\n"
"    /* Denormal zero */\n"
"    if (exp < -9)   return (unsigned char)(sign << 7);\n"
"    if (exp <= -7) {\n"
"        /* subnormal range [-9..-7] -> shift mantissa */\n"
"        unsigned int m_with_implicit = mant23 | 0x800000u;\n"
"        int shift = 20 + (-6 - exp); /* align so top 3 bits end at bit 2..0 */\n"
"        unsigned int mant3 = (m_with_implicit + (1u << (shift - 1))) >> shift;\n"
"        return (unsigned char)((sign << 7) | (mant3 & 0x7u));\n"
"    }\n"
"    int new_exp = exp + 7;\n"
"    if (new_exp >= 15) {\n"
"        /* clamp to max finite 0bS_1111_110 = 448 */\n"
"        return (unsigned char)((sign << 7) | (15u << 3) | 0x6u);\n"
"    }\n"
"    /* normal: take top 3 bits of mantissa with round-to-nearest-even */\n"
"    unsigned int round_bit = (mant23 >> 19) & 1u;\n"
"    unsigned int sticky = mant23 & 0x7FFFFu;\n"
"    unsigned int mant3 = (mant23 >> 20) & 0x7u;\n"
"    if (round_bit && (sticky || (mant3 & 1u))) {\n"
"        mant3 += 1u;\n"
"        if (mant3 == 8u) { mant3 = 0u; new_exp += 1; if (new_exp >= 15) return (unsigned char)((sign << 7) | (15u << 3) | 0x6u); }\n"
"    }\n"
"    return (unsigned char)((sign << 7) | ((unsigned int)new_exp << 3) | mant3);\n"
"}\n"
"\n"

/* ---- gemm_fp8_wmma: FP8 WMMA GEMM on gfx12 (RDNA4). Tile 16x16x16.
 *
 * Y[M,N] = (X[M,K] @ W[N,K]^T) * w_scale + bias
 * W is raw FP8 E4M3 bytes [n_out, n_in] row-major.
 * X is F32 [n_tok, n_in] — quantized to FP8 E4M3 on-the-fly.
 *
 * Lane layout (determined empirically on gfx1201 via wmma_selftest):
 *   Input A fragment (M=16, K=16, fp8): lane L in [0,16) holds A[row=L,  k=0..7],
 *                                       lane L in [16,32) holds A[row=L-16, k=8..15]
 *   Input B fragment (N=16, K=16, fp8): lane L in [0,16) holds B[col=L,   k=0..7],
 *                                       lane L in [16,32) holds B[col=L-16, k=8..15]
 *   Output C fragment (M=16, N=16, f32):
 *     lane L in [0,16):  holds C[m=0..7 (8 rows, i=0..7), n=L]
 *     lane L in [16,32): holds C[m=8..15, n=L-16]
 *   i.e. each lane owns ONE column N and 8 consecutive M values from its half.
 *
 * Grid: (ceil(N/16), ceil(M/16)). Block: 32 threads (one wave). */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_fp8_wmma(float *Y, const unsigned char *W, const float *X,\n"
"                               const float *bias,\n"
"                               int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int lane = threadIdx.x;\n"
"    int m0 = blockIdx.y * 16;\n"
"    int n0 = blockIdx.x * 16;\n"
"    int half = lane >> 4;            /* 0 or 1 */\n"
"    int idx  = lane & 15;            /* 0..15 */\n"
"    int k_off = half * 8;            /* 0 or 8 */\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef int   int2_t __attribute__((ext_vector_type(2)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        /* A fragment: lane L loads row=idx, k=k_off..k_off+7 */\n"
"        unsigned int a0 = 0, a1 = 0;\n"
"        {\n"
"            int row = m0 + idx;\n"
"            const float *Xr = (row < n_tok) ? (X + (long)row * n_in) : 0;\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + i;\n"
"                float v = (Xr && kp < n_in) ? Xr[kp] : 0.f;\n"
"                a0 |= ((unsigned int)f32_to_fp8e4m3_rtne(v)) << (i * 8);\n"
"            }\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + 4 + i;\n"
"                float v = (Xr && kp < n_in) ? Xr[kp] : 0.f;\n"
"                a1 |= ((unsigned int)f32_to_fp8e4m3_rtne(v)) << (i * 8);\n"
"            }\n"
"        }\n"
"        /* B fragment: lane L loads col=idx, k=k_off..k_off+7 (W stored [N,K] row-major) */\n"
"        unsigned int b0 = 0, b1 = 0;\n"
"        {\n"
"            int col = n0 + idx;\n"
"            const unsigned char *Wr = (col < n_out) ? (W + (long)col * n_in) : 0;\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + i;\n"
"                unsigned char v = (Wr && kp < n_in) ? Wr[kp] : 0;\n"
"                b0 |= ((unsigned int)v) << (i * 8);\n"
"            }\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + 4 + i;\n"
"                unsigned char v = (Wr && kp < n_in) ? Wr[kp] : 0;\n"
"                b1 |= ((unsigned int)v) << (i * 8);\n"
"            }\n"
"        }\n"
"        int2_t a_vec, b_vec;\n"
"        a_vec.x = (int)a0; a_vec.y = (int)a1;\n"
"        b_vec.x = (int)b0; b_vec.y = (int)b1;\n"
"        cv = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(a_vec, b_vec, cv);\n"
"    }\n"
"    /* Store C: lane L owns C[m = half*8 + i, n = idx] for i=0..7 */\n"
"    int col = n0 + idx;\n"
"    if (col < n_out) {\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = m0 + half * 8 + i;\n"
"            if (row < n_tok) {\n"
"                Y[(long)row * n_out + col] = cv[i] * w_scale + bv;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- gemm_fp8w_bf16a_wmma: BF16 activations × FP8 LUT weights WMMA (gfx12)
 *
 * Matrix cores with BF16 inputs: X is converted F32→BF16 on the fly,
 * FP8 weights are dequanted via LUT and truncated to BF16. Accumulator F32.
 * Output = (A_bf16 @ B_bf16^T) * w_scale + bias.
 *
 * BF16 activations preserve ~3x more mantissa precision than FP8 (7-bit vs
 * 3-bit), so the per-element quant error is ~1% instead of ~12%; the sum
 * over large K does not blow up accuracy. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_fp8w_bf16a_wmma(float *Y, const unsigned char *W, const float *X,\n"
"                                      const float *bias,\n"
"                                      int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int lane = threadIdx.x;\n"
"    int m0 = blockIdx.y * 16;\n"
"    int n0 = blockIdx.x * 16;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        bf16x8 a_vec, b_vec;\n"
"        int row = m0 + idx;\n"
"        int col = n0 + idx;\n"
"        const float *Xr = (row < n_tok) ? (X + (long)row * n_in) : 0;\n"
"        const unsigned char *Wr = (col < n_out) ? (W + (long)col * n_in) : 0;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int kp = k + k_off + i;\n"
"            float xv = (Xr && kp < n_in) ? Xr[kp] : 0.f;\n"
"            float wv = (Wr && kp < n_in) ? d_fp8_to_f32_lut[Wr[kp]] : 0.f;\n"
"            unsigned int xbits, wbits;\n"
"            memcpy(&xbits, &xv, 4);\n"
"            memcpy(&wbits, &wv, 4);\n"
"            /* Round-to-nearest-even BF16 truncation */\n"
"            xbits += 0x7FFFu + ((xbits >> 16) & 1u);\n"
"            wbits += 0x7FFFu + ((wbits >> 16) & 1u);\n"
"            a_vec[i] = (short)(xbits >> 16);\n"
"            b_vec[i] = (short)(wbits >> 16);\n"
"        }\n"
"        cv = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a_vec, b_vec, cv);\n"
"    }\n"
"    int col = n0 + idx;\n"
"    if (col < n_out) {\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = m0 + half * 8 + i;\n"
"            if (row < n_tok) {\n"
"                Y[(long)row * n_out + col] = cv[i] * w_scale + bv;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- gemm_fp8w_bf16a_wmma_t: tiled BF16xFP8 WMMA — 64×64 per CTA
 *
 * 4 waves per CTA in a 2×2 M/N layout. Each wave owns a 32×32 sub-tile
 * computed as 4 WMMA ops (2 M sub-tiles × 2 N sub-tiles). CTA covers 64×64
 * output. Per K slab, 128 threads cooperatively load A[64,16] and B[64,16]
 * BF16 tiles into shared memory; each wave fetches its 32 rows and does 4
 * WMMA instructions.
 *
 * Shared memory per CTA: 2 × 64 × 16 × sizeof(short) = 4 KB.
 * Register footprint per lane: 4 × float8 accumulators + fragments = ~200 bytes.
 * Grid: (ceil(N/64), ceil(M/64)), Block: 128 threads. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
/* 256 threads = 8 waves per CTA, 2×4 (M×N) wave layout, CTA tile 128×128.
 * Each wave computes a 64×32 sub-tile via 4×2 = 8 WMMA ops, reusing SMEM. */
"__global__ void gemm_fp8w_bf16a_wmma_t(float *Y, const unsigned char *W, const float *X,\n"
"                                        const float *bias,\n"
"                                        int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;       /* 0..7 */\n"
"    int lane    = tid & 31;\n"
"    int wM = wave_id & 1;         /* 0 or 1 */\n"
"    int wN = wave_id >> 1;        /* 0..3 */\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];  /* 4 KB */\n"
"    __shared__ short smB[128*16];  /* 4 KB */\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    /* 4×2 = 8 accumulators: cv[m_sub=0..3][n_sub=0..1] */\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        /* Load A[128,16] cooperatively: 2048 elements / 256 threads = 8 per thread */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;       /* 0..127 */\n"
"            int ek = e & 15;\n"
"            int row = cta_m0 + er;\n"
"            int kp  = k + ek;\n"
"            float xv = (row < n_tok && kp < n_in) ? X[(long)row * n_in + kp] : 0.f;\n"
"            unsigned int xbits; memcpy(&xbits, &xv, 4);\n"
"            smA[er * 16 + ek] = (short)(xbits >> 16);\n"
"        }\n"
"        /* Load B[128,16] via FP8 LUT */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int col = cta_n0 + er;\n"
"            int kp  = k + ek;\n"
"            float wv = (col < n_out && kp < n_in) ? d_fp8_to_f32_lut[W[(long)col * n_in + kp]] : 0.f;\n"
"            unsigned int wbits; memcpy(&wbits, &wv, 4);\n"
"            smB[er * 16 + ek] = (short)(wbits >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        /* Each wave: 64 rows M (4 sub), 32 rows N (2 sub) */\n"
"        int a_base_row = wM * 64;\n"
"        int b_base_row = wN * 32;\n"
"        bf16x8 a0, a1, a2, a3, b0, b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row + 0  + idx) * 16 + k_off + i];\n"
"            a1[i] = smA[(a_base_row + 16 + idx) * 16 + k_off + i];\n"
"            a2[i] = smA[(a_base_row + 32 + idx) * 16 + k_off + i];\n"
"            a3[i] = smA[(a_base_row + 48 + idx) * 16 + k_off + i];\n"
"            b0[i] = smB[(b_base_row + 0  + idx) * 16 + k_off + i];\n"
"            b1[i] = smB[(b_base_row + 16 + idx) * 16 + k_off + i];\n"
"        }\n"
"        cv00 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b0, cv00);\n"
"        cv01 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b1, cv01);\n"
"        cv10 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b0, cv10);\n"
"        cv11 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b1, cv11);\n"
"        cv20 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b0, cv20);\n"
"        cv21 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b1, cv21);\n"
"        cv30 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b0, cv30);\n"
"        cv31 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b1, cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int ms[8]       = {0,   0,  16, 16, 32, 32, 48, 48};\n"
"    int ns[8]       = {0,  16,   0, 16,  0, 16,  0, 16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + ns[t] + idx;\n"
"        if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + ms[t] + half * 8 + i;\n"
"            if (row < n_tok)\n"
"                Y[(long)row * n_out + col] = acc[i] * w_scale + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- gemm_fp8_scaled_opt: 128x128 tiled FP8 LUT GEMM with per-tensor scale ----
 *
 * Ported from rdna4/qimg/hip_qimg_kernels.h::gemm_opt_fp8 with added w_scale.
 * W[N,K] is raw FP8 E4M3 bytes, X[M,K] is F32, Y[M,N] is F32 (no BF16 trunc).
 * Y = (X @ W^T) * w_scale + bias
 * 256 threads, each computes 8x8 outputs; 128x128 tile per CTA.
 * Grid: (ceil(N/128), ceil(M/128)), Block: (256) */
"__global__ void gemm_fp8_scaled_opt(float *Y, const unsigned char *W, const float *X,\n"
"                                     const float *bias, int N, int K, int M, float w_scale) {\n"
"#define OPT_BM 128\n"
"#define OPT_BN 128\n"
"#define OPT_BK 16\n"
"#define OPT_TM 8\n"
"#define OPT_TN 8\n"
"    __shared__ float smA[OPT_BK][OPT_BM];\n"
"    __shared__ float smB[OPT_BK][OPT_BN];\n"
"    int tid = threadIdx.x;\n"
"    int bm = blockIdx.y * OPT_BM, bn = blockIdx.x * OPT_BN;\n"
"    int tr = tid / 16, tc = tid % 16;\n"
"    float acc[OPT_TM][OPT_TN];\n"
"    for (int i = 0; i < OPT_TM; i++)\n"
"        for (int j = 0; j < OPT_TN; j++) acc[i][j] = 0.0f;\n"
"    for (int k = 0; k < K; k += OPT_BK) {\n"
"        for (int _i = tid; _i < OPT_BM*OPT_BK; _i += 256) {\n"
"            int _r = _i % OPT_BM, _c = _i / OPT_BM;\n"
"            int gr = bm+_r, gk = k+_c;\n"
"            smA[_c][_r] = (gr<M&&gk<K) ? X[(long)gr*K+gk] : 0.0f;\n"
"        }\n"
"        for (int _i = tid; _i < OPT_BN*OPT_BK; _i += 256) {\n"
"            int _r = _i % OPT_BN, _c = _i / OPT_BN;\n"
"            int gn = bn+_r, gk = k+_c;\n"
"            smB[_c][_r] = (gn<N&&gk<K) ? d_fp8_to_f32_lut[W[(long)gn*K+gk]] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int kk = 0; kk < OPT_BK; kk++) {\n"
"            float af[OPT_TM], bf[OPT_TN];\n"
"            for (int i=0;i<OPT_TM;i++) af[i] = smA[kk][tr*OPT_TM+i];\n"
"            for (int j=0;j<OPT_TN;j++) bf[j] = smB[kk][tc*OPT_TN+j];\n"
"            for (int i=0;i<OPT_TM;i++)\n"
"                for (int j=0;j<OPT_TN;j++) acc[i][j] += af[i]*bf[j];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    for (int i=0;i<OPT_TM;i++) {\n"
"        int gr = bm+tr*OPT_TM+i; if(gr>=M) continue;\n"
"        for (int j=0;j<OPT_TN;j++) {\n"
"            int gn = bn+tc*OPT_TN+j;\n"
"            if(gn<N) Y[(long)gr*N+gn] = acc[i][j] * w_scale + (bias?bias[gn]:0.0f);\n"
"        }\n"
"    }\n"
"#undef OPT_BM\n"
"#undef OPT_BN\n"
"#undef OPT_BK\n"
"#undef OPT_TM\n"
"#undef OPT_TN\n"
"}\n"
"\n"

/* ---- gemm_fp8_scaled_f32: FP8 LUT GEMM with per-tensor weight scale ---- */
/* Same tile shape as gemm_f32_f32 (16x16 block, 64 out per CTA).
 * W is raw FP8 E4M3 bytes [n_out, n_in], dequanted via constant-memory LUT.
 * Output: Y = (X @ W^T) * w_scale + bias
 * Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */
"__global__ void gemm_fp8_scaled_f32(float *Y, const unsigned char *W, const float *X,\n"
"                                     const float *bias,\n"
"                                     int n_out, int n_in, int n_tok, float w_scale) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[(long)row*n_out+out_base+   tx] = acc0*w_scale + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[(long)row*n_out+out_base+16+tx] = acc1*w_scale + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[(long)row*n_out+out_base+32+tx] = acc2*w_scale + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[(long)row*n_out+out_base+48+tx] = acc3*w_scale + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */
"/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */\n"
"__global__ void gemm_f32_f32(float *Y, const float *W, const float *X,\n"
"                              const float *bias,\n"
"                              int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[(long)row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[(long)row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[(long)row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[(long)row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- SwiGLU: [n_tok, 2*mlp_h] -> [n_tok, mlp_h] ---- */
"/* ---- flux2_swiglu ---- */\n"
"__global__ void flux2_swiglu(float *out, const float *in,\n"
"                              int n_tok, int mlp_h) {\n"
"    int tok = blockIdx.x, i = threadIdx.x + blockIdx.y * blockDim.x;\n"
"    if (tok >= n_tok || i >= mlp_h) return;\n"
"    float gate = in[(long)tok * 2 * mlp_h + i];\n"
"    float val  = in[(long)tok * 2 * mlp_h + mlp_h + i];\n"
"    out[(long)tok * mlp_h + i] = (gate / (1.0f + expf(-gate))) * val;\n"
"}\n"
"\n"

/* ---- Per-head RMSNorm: x[N, dim], w[head_dim], n_heads, head_dim ---- */
"/* ---- rmsnorm_per_head_f32 ---- */\n"
"__global__ void rmsnorm_per_head_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int n_heads, int head_dim) {\n"
"    int tok = blockIdx.x, h = blockIdx.y;\n"
"    if (tok >= N || h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    float *hd = x + (long)tok * dim + h * head_dim;\n"
"    float ss = 0.0f;\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        ss += hd[i] * hd[i];\n"
"    for (int m = 16; m > 0; m >>= 1)\n"
"        ss += __shfl_xor(ss, m);\n"
"    float inv = rsqrtf(ss / (float)head_dim + 1e-6f);\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        hd[i] *= inv * w[i];\n"
"}\n"
"\n"

/* ---- adaLN: out = LN(x) * (1 + scale) + shift ---- */
"/* ---- adaln_modulate_f32 ---- */\n"
"__global__ void adaln_modulate_f32(float *__restrict__ out,\n"
"    const float *__restrict__ x, const float *__restrict__ shift,\n"
"    const float *__restrict__ scale, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) s += x[(long)tok*dim+i];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) { float d = x[(long)tok*dim+i] - mean; s += d*d; }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        out[(long)tok*dim+i] = ((x[(long)tok*dim+i] - mean) * inv) * (1.0f + scale[i]) + shift[i];\n"
"}\n"
"\n"

/* ---- Gated residual: x += gate * proj ---- */
"/* ---- gated_add_f32 ---- */\n"
"__global__ void gated_add_f32(float *__restrict__ x,\n"
"    const float *__restrict__ proj, const float *__restrict__ gate,\n"
"    int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N * dim) return;\n"
"    x[i] += gate[i % dim] * proj[i];\n"
"}\n"
"\n"

/* ---- BF16 truncation ---- */
"/* ---- truncate_bf16_f32 ---- */\n"
"__global__ void truncate_bf16_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &x[i], 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&x[i], &bits, 4);\n"
"}\n"
"\n"

/* ---- RoPE for image tokens: 2D spatial (row/col), theta=2000 ---- */
"/* ---- flux2_rope_img_f32 ---- */\n"
"__global__ void flux2_rope_img_f32(float *x, int n_tok, int n_heads,\n"
"    int head_dim, int lat_w, float theta) {\n"
"    int tok = blockIdx.z, head = blockIdx.y;\n"
"    int pair = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads || pair >= head_dim / 2) return;\n"
"    int axis_dim = head_dim / 4;\n"
"    int n_pairs = axis_dim / 2;\n"
"    int ax = -1, p_in_ax = -1;\n"
"    if (pair >= n_pairs && pair < 2 * n_pairs) { ax = 1; p_in_ax = pair - n_pairs; }\n"
"    else if (pair >= 2 * n_pairs && pair < 3 * n_pairs) { ax = 2; p_in_ax = pair - 2 * n_pairs; }\n"
"    if (ax < 0) return;\n"
"    int row = tok / lat_w, col = tok % lat_w;\n"
"    float pos = (ax == 1) ? (float)row : (float)col;\n"
"    float freq = pos / powf(theta, (float)(2 * p_in_ax) / (float)axis_dim);\n"
"    float cos_f = cosf(freq), sin_f = sinf(freq);\n"
"    long idx = (long)tok * n_heads * head_dim + head * head_dim + pair * 2;\n"
"    float a = x[idx], b = x[idx + 1];\n"
"    x[idx]     = a * cos_f - b * sin_f;\n"
"    x[idx + 1] = a * sin_f + b * cos_f;\n"
"}\n"
"\n"

/* ---- RoPE for text tokens: 1D sequence position ---- */
"/* ---- flux2_rope_txt_f32 ---- */\n"
"__global__ void flux2_rope_txt_f32(float *x, int n_tok, int n_heads,\n"
"    int head_dim, float theta) {\n"
"    int tok = blockIdx.z, head = blockIdx.y;\n"
"    int pair = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads || pair >= head_dim / 2) return;\n"
"    int axis_dim = head_dim / 4;\n"
"    int n_pairs = axis_dim / 2;\n"
"    if (pair < 3 * n_pairs) return;\n"
"    int p_in_ax = pair - 3 * n_pairs;\n"
"    float freq = (float)tok / powf(theta, (float)(2 * p_in_ax) / (float)axis_dim);\n"
"    float cos_f = cosf(freq), sin_f = sinf(freq);\n"
"    long idx = (long)tok * n_heads * head_dim + head * head_dim + pair * 2;\n"
"    float a = x[idx], b = x[idx + 1];\n"
"    x[idx]     = a * cos_f - b * sin_f;\n"
"    x[idx + 1] = a * sin_f + b * cos_f;\n"
"}\n"
"\n"

/* ---- Flash attention with separate Q/K/V: warp-cooperative FA2 ---- */
"/* ---- flash_attn_f32: separate Q/K/V, warp-cooperative ---- */\n"
"#define FA2_WARPS   4\n"
"#define FA2_BKV    16\n"
"#define FA2_HD    128\n"
"#define FA2_EPT     4\n"
"\n"
"__global__ void flash_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    int h = blockIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    /* RDNA4 wave32: warp_size=32, same as NVIDIA */\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int lane    = threadIdx.x % 32;\n"
"    int qi = blockIdx.y * FA2_WARPS + warp_id;\n"
"    float scale = rsqrtf((float)head_dim);\n"
"    float q_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) {\n"
"        int d = lane * FA2_EPT + e;\n"
"        q_r[e] = (qi < N && d < head_dim) ? Q[(long)qi * dim + h * head_dim + d] : 0.0f;\n"
"    }\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) O_r[e] = 0.0f;\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem, *smV = smem + FA2_BKV * FA2_HD;\n"
"    int n_tiles = (N + FA2_BKV - 1) / FA2_BKV;\n"
"    int n_threads = FA2_WARPS * 32;\n"
"    for (int tile = 0; tile < n_tiles; tile++) {\n"
"        int kv_base = tile * FA2_BKV;\n"
"        for (int idx = threadIdx.x; idx < FA2_BKV * FA2_HD; idx += n_threads) {\n"
"            int kj = idx / FA2_HD, d = idx % FA2_HD;\n"
"            int kv_tok = kv_base + kj;\n"
"            smK[idx] = (kv_tok < N) ? K[(long)kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"            smV[idx] = (kv_tok < N) ? V[(long)kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int kj = 0; kj < FA2_BKV; kj++) {\n"
"            float dot = 0.0f;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                dot += q_r[e] * smK[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            for (int off = 16; off > 0; off >>= 1)\n"
"                dot += __shfl_xor(dot, off);\n"
"            float score = (kv_base + kj < N) ? dot * scale : -1e30f;\n"
"            float new_max = fmaxf(m_i, score);\n"
"            float alpha = expf(m_i - new_max);\n"
"            float p = expf(score - new_max);\n"
"            l_i = l_i * alpha + p;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                O_r[e] = O_r[e] * alpha + p * smV[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            m_i = new_max;\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (qi < N) {\n"
"        float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        for (int e = 0; e < FA2_EPT; e++) {\n"
"            int d = lane * FA2_EPT + e;\n"
"            if (d < head_dim)\n"
"                out[(long)qi * dim + h * head_dim + d] = O_r[e] * inv_l;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

/* ================================================================ */
/* VAE decoder kernels                                              */
/* ================================================================ */

/* ---- im2col: [ci,H,W] -> [H*W, ci*9] for 3x3 same-padding conv ---- */
/* Grid: ceil(H*W*ci*9 / 256), Block: 256 */
"/* ---- vae_im2col_3x3: extract 3x3 patches for output pixels [s0, s0+ns) into\n"
" * col[ns, ci*9]. s0=0, ns=H*W processes the whole image (single tile). ---- */\n"
"__global__ void vae_im2col_3x3(float *col, const float *in,\n"
"    int ci, int H, int W, int s0, int ns) {\n"
"    int col_w = ci * 9;\n"
"    long idx = (long)blockIdx.x * blockDim.x + threadIdx.x;\n"
"    long total = (long)ns * col_w;\n"
"    if (idx >= total) return;\n"
"    int s = s0 + (int)(idx / col_w);\n"  /* global spatial position */
"    int k = (int)(idx % col_w);\n"       /* column index = ic * 9 + ky * 3 + kx */
"    int ic = k / 9;\n"
"    int rem = k % 9;\n"
"    int ky = rem / 3, kx = rem % 3;\n"
"    int y = s / W, x = s % W;\n"
"    int iy = y + ky - 1, ix = x + kx - 1;\n"
"    col[idx] = (iy >= 0 && iy < H && ix >= 0 && ix < W)\n"
"              ? in[(long)ic * H * W + iy * W + ix] : 0.0f;\n"
"}\n"
"\n"

/* ---- transpose_tile: in[ns, co] -> out[co, spatial] at column offset s0:\n"
" * out[c*spatial + s0 + i] = in[i*co + c]. Writes one spatial tile. ---- */
"__global__ void vae_transpose_tile(float *out, const float *in,\n"
"    int ns, int co, int s0, int spatial) {\n"
"    long idx = (long)blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= (long)ns * co) return;\n"
"    int i = (int)(idx / co), c = (int)(idx % co);\n"
"    out[(long)c * spatial + s0 + i] = in[idx];\n"
"}\n"
"\n"

/* ---- transpose_2d: in[rows, cols] -> out[cols, rows] ---- */
"/* ---- vae_transpose_2d ---- */\n"
"__global__ void vae_transpose_2d(float *out, const float *in,\n"
"    int rows, int cols) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= rows * cols) return;\n"
"    int r = idx / cols, c = idx % cols;\n"
"    out[c * rows + r] = in[idx];\n"
"}\n"
"\n"

/* ---- add_bias_broadcast: out[i] += bias[i % co] ---- */
"/* ---- vae_add_bias: out[i] += bias[i % co] ---- */\n"
"__global__ void vae_add_bias(float *out, const float *bias,\n"
"    int co, int spatial) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * spatial;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / spatial;\n"
"    out[idx] += bias[oc];\n"
"}\n"
"\n"

/* ---- Conv2D 1x1: [ci,H,W] -> [co,H,W] ---- */
"/* ---- vae_conv2d_1x1: [ci,H,W] -> [co,H,W] ---- */\n"
"__global__ void vae_conv2d_1x1(float *out, const float *in,\n"
"    const float *w, const float *bias,\n"
"    int ci, int spatial, int co) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= co * spatial) return;\n"
"    int oc = idx / spatial;\n"
"    int s  = idx % spatial;\n"
"    float sum = bias ? bias[oc] : 0.0f;\n"
"    for (int ic = 0; ic < ci; ic++)\n"
"        sum += in[(long)ic * spatial + s] * w[(long)oc * ci + ic];\n"
"    out[idx] = sum;\n"
"}\n"
"\n"

/* ---- GroupNorm + SiLU fused: [C,H,W] -> [C,H,W] ---- */
/* One block per group. Shared-memory reduction for mean/var. */
"/* ---- vae_groupnorm_silu: [C,H,W] -> [C,H,W] ---- */\n"
"__global__ void vae_groupnorm_silu(float *out, const float *in,\n"
"    const float *gamma, const float *beta,\n"
"    int C, int spatial, int num_groups, int apply_silu) {\n"
"    int g = blockIdx.x;\n"
"    if (g >= num_groups) return;\n"
"    int group_size = C / num_groups;\n"
"    int c0 = g * group_size;\n"
"    int ne = group_size * spatial;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    extern __shared__ float sdata[];\n"
"    /* Mean */\n"
"    float s = 0.0f;\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        s += in[(long)ch * spatial + sp];\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)ne;\n"
"    __syncthreads();\n"
"    /* Var */\n"
"    s = 0.0f;\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float d = in[(long)ch * spatial + sp] - mean;\n"
"        s += d * d;\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)ne + 1e-6f);\n"
"    /* Normalize + scale + shift + optional SiLU */\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float v = (in[(long)ch * spatial + sp] - mean) * inv;\n"
"        float gv = gamma ? gamma[ch] : 1.0f;\n"
"        float bv = beta  ? beta[ch]  : 0.0f;\n"
"        v = v * gv + bv;\n"
"        if (apply_silu) v = v / (1.0f + expf(-v));\n"
"        out[(long)ch * spatial + sp] = v;\n"
"    }\n"
"}\n"
"\n"

/* ---- Nearest-neighbor 2x upsample: [C,H,W] -> [C,2H,2W] ---- */
"/* ---- vae_upsample2x: [C,H,W] -> [C,2H,2W] ---- */\n"
"__global__ void vae_upsample2x(float *out, const float *in,\n"
"    int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * H * W;\n"
"    if (idx >= total) return;\n"
"    int ch = idx / (H * W);\n"
"    int rem = idx % (H * W);\n"
"    int y = rem / W, x = rem % W;\n"
"    float v = in[idx];\n"
"    int oH = 2*H, oW = 2*W;\n"
"    long base = (long)ch * oH * oW;\n"
"    out[base + (2*y)   * oW + 2*x]     = v;\n"
"    out[base + (2*y)   * oW + 2*x + 1] = v;\n"
"    out[base + (2*y+1) * oW + 2*x]     = v;\n"
"    out[base + (2*y+1) * oW + 2*x + 1] = v;\n"
"}\n"
"\n"

/* ---- VAE self-attention (single-head, mid block) ---- */
/* Input: [C, H*W], output: [C, H*W]. One block per query spatial position. */
"/* ---- vae_self_attn: single-head attention for VAE mid-block ---- */\n"
"/* Q/K/V computed externally. This kernel does the softmax+V weighted sum. */\n"
"/* Grid: (spatial,), Block: (256). Each block handles one query. */\n"
"__global__ void vae_self_attn(float *out,\n"
"    const float *Q, const float *K, const float *V,\n"
"    int spatial, int channels, float scale) {\n"
"    int qi = blockIdx.x;\n"
"    if (qi >= spatial) return;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    extern __shared__ float sdata[];\n"
"    float *scores = sdata;\n"
"    float *rbuf = sdata + spatial;\n"
"    /* Phase 1: Q[qi,:] @ K^T -> scores[spatial] */\n"
"    for (int ki = tid; ki < spatial; ki += nt) {\n"
"        float dot = 0.0f;\n"
"        for (int d = 0; d < channels; d++)\n"
"            dot += Q[qi * channels + d] * K[ki * channels + d];\n"
"        scores[ki] = dot * scale;\n"
"    }\n"
"    __syncthreads();\n"
"    /* Phase 2: Softmax */\n"
"    float lmax = -1e30f;\n"
"    for (int ki = tid; ki < spatial; ki += nt)\n"
"        lmax = fmaxf(lmax, scores[ki]);\n"
"    rbuf[tid] = lmax; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] = fmaxf(rbuf[tid], rbuf[tid+r]);\n"
"        __syncthreads();\n"
"    }\n"
"    float mx = rbuf[0]; __syncthreads();\n"
"    float lsum = 0.0f;\n"
"    for (int ki = tid; ki < spatial; ki += nt) {\n"
"        scores[ki] = expf(scores[ki] - mx);\n"
"        lsum += scores[ki];\n"
"    }\n"
"    rbuf[tid] = lsum; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] += rbuf[tid+r];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv_sum = (rbuf[0] > 0) ? 1.0f / rbuf[0] : 0.0f;\n"
"    for (int ki = tid; ki < spatial; ki += nt)\n"
"        scores[ki] *= inv_sum;\n"
"    __syncthreads();\n"
"    /* Phase 3: Weighted sum of V */\n"
"    for (int d = tid; d < channels; d += nt) {\n"
"        float acc = 0.0f;\n"
"        for (int ki = 0; ki < spatial; ki++)\n"
"            acc += scores[ki] * V[ki * channels + d];\n"
"        out[qi * channels + d] = acc;\n"
"    }\n"
"}\n"
"\n"

/* ---- Batch-norm denormalize: x[c] = x[c] * sqrt(var[c] + eps) + mean[c] ---- */
"/* ---- vae_bn_denorm: per-channel scale+shift in patchified space ---- */\n"
"__global__ void vae_bn_denorm(float *out, const float *in,\n"
"    const float *bn_mean, const float *bn_var, float eps,\n"
"    int lc, int lat_h, int lat_w, int ps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = lc * lat_h * lat_w;\n"
"    if (idx >= total) return;\n"
"    int ch = idx / (lat_h * lat_w);\n"
"    int rem = idx % (lat_h * lat_w);\n"
"    int sh = rem / lat_w, sw = rem % lat_w;\n"
"    int pr = sh % ps, pc_ = sw % ps;\n"
"    int bn_ch = ch * (ps * ps) + pr * ps + pc_;\n"
"    float mn = bn_mean[bn_ch];\n"
"    float sd = sqrtf(bn_var[bn_ch] + eps);\n"
"    out[idx] = in[idx] * sd + mn;\n"
"}\n"
"\n"

/* Close the extern "C" block opened by hip_kernels_common_src */

/* ---- Ported pipe32 FP8xFP8 WMMA (from qimg gemm_fp8_fp8w_perrow_pgr2) +
 * clamp activation quantizer with per-tensor w_scale folded into the
 * per-row writeback scale. ~143 TF/s class vs the naive gemm_fp8_wmma. ---- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"typedef unsigned char f2_u8;\n"
"typedef unsigned int  f2_u32;\n"
"typedef f2_u32 f2_u32x2 __attribute__((ext_vector_type(2)));\n"
"typedef f2_u8  f2_u8x8  __attribute__((ext_vector_type(8)));\n"
"typedef f2_u8  f2_u8x16 __attribute__((ext_vector_type(16)));\n"
"typedef float    f2_f8    __attribute__((ext_vector_type(8)));\n"

"__device__ __forceinline__ f2_u32x2 f2_pack_a8(f2_u8x8 v) {\n"
"    union { f2_u8x8 b; f2_u32x2 w; } u; u.b = v; return u.w;\n"
"}\n"

"__device__ __forceinline__ void f2_lds_signal(void) {\n"
"    __asm__ __volatile__(\"s_barrier_signal -1\" ::: \"memory\");\n"
"}\n"
"__device__ __forceinline__ void f2_lds_wait(void) {\n"
"    __asm__ __volatile__(\"s_barrier_wait 0xffff\" ::: \"memory\");\n"
"}\n"
"__device__ __forceinline__ void f2_lds_barrier(void) { f2_lds_signal(); f2_lds_wait(); }\n"

"#define F2_WMMA_FP8(A,B,C) C = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(A, B, C)\n"

/* F32 -> FP8 E4M3 (round-nearest, saturate at ±448). Mirrors the rounding
 * scheme used in quantize_fp8_roundtrip_f32 above; output is the raw byte. */
"__device__ __forceinline__ f2_u8 f2_f32_to_fp8_e4m3(float f) {\n"
"    if (f > 448.0f) f = 448.0f;\n"
"    if (f < -448.0f) f = -448.0f;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &f, 4);\n"
"    unsigned int sign = bits >> 31;\n"
"    int e = (int)((bits >> 23) & 0xFFu) - 127;\n"
"    unsigned int mant = bits & 0x7FFFFFu;\n"
"    int fp8_exp = e + 7;\n"
"    if (e < -9) return (f2_u8)(sign << 7);\n"
"    if (fp8_exp <= 0) {\n"
"        unsigned int full_mant = mant | 0x800000u;\n"
"        int shift = 1 - fp8_exp + 20;\n"
"        if (shift >= 24) return (f2_u8)(sign << 7);\n"
"        unsigned int fp8_mant = (full_mant + (1u << (shift-1))) >> shift;\n"
"        if (fp8_mant > 7) fp8_mant = 7;\n"
"        return (f2_u8)((sign << 7) | (fp8_mant & 7u));\n"
"    }\n"
"    if (fp8_exp >= 15) return (f2_u8)((sign << 7) | (15u << 3) | 6u);\n"
"    unsigned int fp8_mant = (mant + (1u << 19)) >> 20;\n"
"    if (fp8_mant > 7) { fp8_mant = 0; fp8_exp++; }\n"
"    if (fp8_exp >= 15) return (f2_u8)((sign << 7) | (15u << 3) | 6u);\n"
"    return (f2_u8)((sign << 7) | ((unsigned int)fp8_exp << 3) | (fp8_mant & 7u));\n"
"}\n"

"__global__ __launch_bounds__(256, 1)\n"
"void flux2_quant_act_clamp(const float *X, f2_u8 *X_fp8, float *scales,\n"
"                                 int n_tok, int K, int M_pad, float w_scale) {\n"
"    int m = blockIdx.x;\n"
"    int tid = threadIdx.x;\n"
"    if (m >= M_pad) return;\n"
"    if (m >= n_tok) {\n"
"        for (int k = tid; k < K; k += 256) X_fp8[(size_t)m * K + k] = (f2_u8)0;\n"
"        if (tid == 0) scales[m] = w_scale;\n"
"        return;\n"
"    }\n"
"    float local_max = 0.f;\n"
"    for (int k = tid; k < K; k += 256) {\n"
"        float v = fabsf(X[(size_t)m * K + k]);\n"
"        if (v > local_max) local_max = v;\n"
"    }\n"
"    for (int off = 16; off > 0; off >>= 1) {\n"
"        float other = __shfl_xor(local_max, off, 32);\n"
"        if (other > local_max) local_max = other;\n"
"    }\n"
"    __shared__ float wave_max[8];\n"
"    int wid = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    if (lane == 0) wave_max[wid] = local_max;\n"
"    __syncthreads();\n"
"    float row_max = 0.f;\n"
"    for (int i = 0; i < 8; i++) if (wave_max[i] > row_max) row_max = wave_max[i];\n"
"    float s = row_max > 448.0f ? (row_max / 448.0f) : 1.0f;\n"
"    float inv_s = 1.0f / s;\n"
"    if (tid == 0) scales[m] = s * w_scale;\n"
"    for (int k = tid; k < K; k += 256) {\n"
"        float v = X[(size_t)m * K + k] * inv_s;\n"
"        if (v > 448.0f) v = 448.0f;\n"
"        if (v < -448.0f) v = -448.0f;\n"
"        X_fp8[(size_t)m * K + k] = f2_f32_to_fp8_e4m3(v);\n"
"    }\n"
"}\n"


"__device__ __forceinline__ void f2_store_acc8_pr(\n"
"    float *Y, const float *bias, const float *scales,\n"
"    f2_f8 acc, int row0, int col, int N, int n_tok, int n_out) {\n"
"    if (col >= n_out) return;\n"
"    float bv = bias ? bias[col] : 0.0f;\n"
"    if (row0 + 0 < n_tok) Y[(size_t)(row0+0)*N + col] = acc[0] * scales[row0+0] + bv;\n"
"    if (row0 + 1 < n_tok) Y[(size_t)(row0+1)*N + col] = acc[1] * scales[row0+1] + bv;\n"
"    if (row0 + 2 < n_tok) Y[(size_t)(row0+2)*N + col] = acc[2] * scales[row0+2] + bv;\n"
"    if (row0 + 3 < n_tok) Y[(size_t)(row0+3)*N + col] = acc[3] * scales[row0+3] + bv;\n"
"    if (row0 + 4 < n_tok) Y[(size_t)(row0+4)*N + col] = acc[4] * scales[row0+4] + bv;\n"
"    if (row0 + 5 < n_tok) Y[(size_t)(row0+5)*N + col] = acc[5] * scales[row0+5] + bv;\n"
"    if (row0 + 6 < n_tok) Y[(size_t)(row0+6)*N + col] = acc[6] * scales[row0+6] + bv;\n"
"    if (row0 + 7 < n_tok) Y[(size_t)(row0+7)*N + col] = acc[7] * scales[row0+7] + bv;\n"
"}\n"

"#define F2_SPLIT_HI(v) __builtin_shufflevector(v, v, 8,9,10,11,12,13,14,15)\n"
"#define F2_SPLIT_LO(v) __builtin_shufflevector(v, v, 0,1,2,3,4,5,6,7)\n"

"__global__ __launch_bounds__(128, 1)\n"
"void flux2_gemm_fp8_pgr2(float *Y, const f2_u8 *W, const f2_u8 *X,\n"
"                                const float *bias, const float *act_scales,\n"
"                                int n_out, int n_in, int n_tok, int M_pad) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int wM = wave_id & 1;\n"
"    int wN = wave_id >> 1;\n"
"    int half = lane >> 4;\n"
"    int idx = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    int K = n_in;\n"
"    int N = n_out;\n"
"    int e0 = tid * 2 + 0;\n"
"    int e1 = tid * 2 + 1;\n"
"    int r0 = e0 >> 1, r1 = e1 >> 1;\n"
"    int c0 = (e0 & 1) * 16, c1 = (e1 & 1) * 16;\n"
"    __shared__ f2_u8x8 smA8[3 * 128 * 4];\n"
"    __shared__ f2_u8x8 smB8[3 * 128 * 4];\n"
"    #define F2_LOAD(na0,na1,nb0,nb1, kk) do { \\\n"
"        na0 = *((const f2_u8x16 *)(X + (size_t)(cta_m0 + r0) * K + (kk) + c0)); \\\n"
"        na1 = *((const f2_u8x16 *)(X + (size_t)(cta_m0 + r1) * K + (kk) + c1)); \\\n"
"        nb0 = *((const f2_u8x16 *)(W + (size_t)(cta_n0 + r0) * K + (kk) + c0)); \\\n"
"        nb1 = *((const f2_u8x16 *)(W + (size_t)(cta_n0 + r1) * K + (kk) + c1)); \\\n"
"    } while(0)\n"
"    #define F2_WRITE_LDS(buf_idx, na0,na1,nb0,nb1) do { \\\n"
"        int nbase = (buf_idx) * (128 * 4); \\\n"
"        smA8[nbase + (c0>>3)*128 + r0]     = F2_SPLIT_LO(na0); \\\n"
"        smA8[nbase + ((c0>>3)+1)*128 + r0] = F2_SPLIT_HI(na0); \\\n"
"        smA8[nbase + (c1>>3)*128 + r1]     = F2_SPLIT_LO(na1); \\\n"
"        smA8[nbase + ((c1>>3)+1)*128 + r1] = F2_SPLIT_HI(na1); \\\n"
"        smB8[nbase + (c0>>3)*128 + r0]     = F2_SPLIT_LO(nb0); \\\n"
"        smB8[nbase + ((c0>>3)+1)*128 + r0] = F2_SPLIT_HI(nb0); \\\n"
"        smB8[nbase + (c1>>3)*128 + r1]     = F2_SPLIT_LO(nb1); \\\n"
"        smB8[nbase + ((c1>>3)+1)*128 + r1] = F2_SPLIT_HI(nb1); \\\n"
"    } while(0)\n"
"    f2_u8x16 g0a0,g0a1,g0b0,g0b1; F2_LOAD(g0a0,g0a1,g0b0,g0b1, 0);\n"
"    F2_WRITE_LDS(0, g0a0,g0a1,g0b0,g0b1);\n"
"    f2_u8x16 g1a0,g1a1,g1b0,g1b1;\n"
"    int has_k1 = (32 < K);\n"
"    if (has_k1) { F2_LOAD(g1a0,g1a1,g1b0,g1b1, 32); F2_WRITE_LDS(1, g1a0,g1a1,g1b0,g1b1); }\n"
"    f2_lds_barrier();\n"
"    f2_f8 z = {0,0,0,0,0,0,0,0};\n"
"    f2_f8 cv00=z,cv01=z,cv02=z,cv03=z;\n"
"    f2_f8 cv10=z,cv11=z,cv12=z,cv13=z;\n"
"    f2_f8 cv20=z,cv21=z,cv22=z,cv23=z;\n"
"    f2_f8 cv30=z,cv31=z,cv32=z,cv33=z;\n"
"    int rd_buf = 0;\n"
"    int wr_buf = 2;\n"
"    for (int k = 0; k < K; k += 32) {\n"
"        f2_u8x16 na0,na1,nb0,nb1;\n"
"        int has_far = (k + 64 < K);\n"
"        if (has_far) F2_LOAD(na0,na1,nb0,nb1, k + 64);\n"
"        int base = rd_buf * (128 * 4);\n"
"        int a_base = wM * 64;\n"
"        int b_base = wN * 64;\n"
"        for (int kk0 = 0; kk0 < 32; kk0 += 16) {\n"
"            int kslot = (kk0 + k_off) >> 3;\n"
"            f2_u8x8 a0 = smA8[base + kslot * 128 + (a_base + 0  + idx)];\n"
"            f2_u8x8 a1 = smA8[base + kslot * 128 + (a_base + 16 + idx)];\n"
"            f2_u8x8 a2 = smA8[base + kslot * 128 + (a_base + 32 + idx)];\n"
"            f2_u8x8 a3 = smA8[base + kslot * 128 + (a_base + 48 + idx)];\n"
"            f2_u8x8 b0 = smB8[base + kslot * 128 + (b_base + 0  + idx)];\n"
"            f2_u8x8 b1 = smB8[base + kslot * 128 + (b_base + 16 + idx)];\n"
"            f2_u8x8 b2 = smB8[base + kslot * 128 + (b_base + 32 + idx)];\n"
"            f2_u8x8 b3 = smB8[base + kslot * 128 + (b_base + 48 + idx)];\n"
"            f2_u32x2 ra0 = f2_pack_a8(a0), ra1 = f2_pack_a8(a1);\n"
"            f2_u32x2 ra2 = f2_pack_a8(a2), ra3 = f2_pack_a8(a3);\n"
"            f2_u32x2 rb0 = f2_pack_a8(b0), rb1 = f2_pack_a8(b1);\n"
"            f2_u32x2 rb2 = f2_pack_a8(b2), rb3 = f2_pack_a8(b3);\n"
"            F2_WMMA_FP8(ra0, rb0, cv00); F2_WMMA_FP8(ra0, rb1, cv01);\n"
"            F2_WMMA_FP8(ra0, rb2, cv02); F2_WMMA_FP8(ra0, rb3, cv03);\n"
"            F2_WMMA_FP8(ra1, rb0, cv10); F2_WMMA_FP8(ra1, rb1, cv11);\n"
"            F2_WMMA_FP8(ra1, rb2, cv12); F2_WMMA_FP8(ra1, rb3, cv13);\n"
"            F2_WMMA_FP8(ra2, rb0, cv20); F2_WMMA_FP8(ra2, rb1, cv21);\n"
"            F2_WMMA_FP8(ra2, rb2, cv22); F2_WMMA_FP8(ra2, rb3, cv23);\n"
"            F2_WMMA_FP8(ra3, rb0, cv30); F2_WMMA_FP8(ra3, rb1, cv31);\n"
"            F2_WMMA_FP8(ra3, rb2, cv32); F2_WMMA_FP8(ra3, rb3, cv33);\n"
"        }\n"
"        if (has_far) {\n"
"            F2_WRITE_LDS(wr_buf, na0,na1,nb0,nb1);\n"
"            f2_lds_signal();\n"
"            wr_buf = (wr_buf + 1) % 3;\n"
"            rd_buf = (rd_buf + 1) % 3;\n"
"            f2_lds_wait();\n"
"        } else if (k + 32 < K) {\n"
"            f2_lds_signal();\n"
"            rd_buf = (rd_buf + 1) % 3;\n"
"            f2_lds_wait();\n"
"        }\n"
"    }\n"
"    #undef F2_LOAD\n"
"    #undef F2_WRITE_LDS\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 64;\n"
"    int row = wave_m0 + half * 8;\n"
"    if (row >= n_tok) return;\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv00, row +  0, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv01, row +  0, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv02, row +  0, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv03, row +  0, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv10, row + 16, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv11, row + 16, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv12, row + 16, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv13, row + 16, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv20, row + 32, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv21, row + 32, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv22, row + 32, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv23, row + 32, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv30, row + 48, wave_n0 +  0 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv31, row + 48, wave_n0 + 16 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv32, row + 48, wave_n0 + 32 + idx, N, n_tok, n_out);\n"
"    f2_store_acc8_pr(Y, bias, act_scales, cv33, row + 48, wave_n0 + 48 + idx, N, n_tok, n_out);\n"
"}\n"
"#endif\n"

"\n"
/* ================= INT8 W8A8 (ported verbatim from rdna4/qimg) =================
 * Per-token int8 activation quant (smooth=NULL) x per-output-channel int8 weights;
 * int8 x int8 -> int32 WMMA + fused dequant (xscale[t]*wscale[o]) + bias. ModelOpt
 * klein int8 = plain per-row W8A8 (input_scale ignored; dynamic per-token preferred).
 * Self-contained qimg_ and wm_ helpers (no collision with flux2 f2_ ). ============= */
"__device__ __forceinline__ int dp4a_s8(int a, int b, int c) {\n"
"    signed char *av = (signed char*)&a; signed char *bv = (signed char*)&b;\n"
"    c += (int)av[0]*(int)bv[0]; c += (int)av[1]*(int)bv[1];\n"
"    c += (int)av[2]*(int)bv[2]; c += (int)av[3]*(int)bv[3]; return c;\n"
"}\n"
/* Per-token int8 quant. One block (256 threads = 8 wave32 warps) per token-row;
 * scale = max(|x/smooth|)/127; writes Xq int8 + xscale[row]. smooth may be NULL. */
"__global__ void quant_act_perrow_int8(const float *X, const float *smooth,\n"
"                                      signed char *Xq, float *xscale, int n_tok, int n_in) {\n"
"    int row = blockIdx.x; if (row >= n_tok) return;\n"
"    const float *xr = X + (long)row*n_in; signed char *qr = Xq + (long)row*n_in;\n"
"    float v = 0.0f;\n"
"    for (int i = threadIdx.x; i < n_in; i += blockDim.x) { float xe = smooth ? (xr[i]/smooth[i]) : xr[i]; float a = fabsf(xe); if (a>v) v=a; }\n"
"    for (int off=16; off>0; off>>=1) { float o=__shfl_xor(v,off,32); if (o>v) v=o; }\n"   /* width 32: correct on wave32 AND wave64 */
"    __shared__ float warp_max[8]; int wid = threadIdx.x>>5;\n"
"    if ((threadIdx.x&31)==0) warp_max[wid]=v; __syncthreads();\n"
"    __shared__ float s_scale;\n"
"    if (wid==0) { v = (threadIdx.x < (blockDim.x>>5)) ? warp_max[threadIdx.x] : 0.0f;\n"
"        for (int off=16; off>0; off>>=1) { float o=__shfl_xor(v,off,32); if (o>v) v=o; }\n"
"        if (threadIdx.x==0) { float sc = (v>1e-30f) ? (v/127.0f) : 1.0f; xscale[row]=sc; s_scale=sc; } }\n"
"    __syncthreads(); float sc = s_scale;\n"
"    for (int i = threadIdx.x; i < n_in; i += blockDim.x) { float xe = smooth ? (xr[i]/smooth[i]) : xr[i];\n"
"        float q = rintf(xe/sc); if (q>127.0f) q=127.0f; else if (q<-127.0f) q=-127.0f; qr[i]=(signed char)q; }\n"
"}\n"
/* W8A8 GEMM, one thread per output (o,t); int32 dp4a k-reduction (n_in % 4 == 0
 * for qimg linears), fused dequant + bias -> f32. */
"__global__ void gemm_w8a8_perrow_f32(float *Y, const signed char *Wq, const float *wscale,\n"
"        const signed char *Xq, const float *xscale, const float *bias, int n_out, int n_in, int n_tok) {\n"
"    int o = blockIdx.x*blockDim.x + threadIdx.x; int t = blockIdx.y;\n"
"    if (o >= n_out || t >= n_tok) return;\n"
"    const int *w4 = (const int *)(Wq + (long)o*n_in); const int *x4 = (const int *)(Xq + (long)t*n_in);\n"
"    int acc = 0, n4 = n_in>>2;\n"
"    for (int i=0;i<n4;i++) acc = dp4a_s8(w4[i], x4[i], acc);\n"
"    for (int i=n4<<2;i<n_in;i++) acc += (int)Wq[(long)o*n_in+i]*(int)Xq[(long)t*n_in+i];\n"
"    float y = (float)acc * (xscale[t]*wscale[o]); if (bias) y += bias[o];\n"
"    Y[(long)t*n_out + o] = y;\n"
"}\n"
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"typedef int wm_i32x8 __attribute__((ext_vector_type(8)));\n"
"typedef unsigned int wm_u32x2 __attribute__((ext_vector_type(2)));\n"
"__device__ __forceinline__ unsigned int wm_pack4_i8(signed char a, signed char b, signed char c, signed char d) {\n"
"    return (unsigned)(unsigned char)a | ((unsigned)(unsigned char)b<<8) | ((unsigned)(unsigned char)c<<16) | ((unsigned)(unsigned char)d<<24);\n"
"}\n"
"typedef unsigned char qimg_u8;\n"
"typedef unsigned int  qimg_u32;\n"
"typedef qimg_u32 qimg_u32x2 __attribute__((ext_vector_type(2)));\n"
"typedef qimg_u8  qimg_u8x8  __attribute__((ext_vector_type(8)));\n"
"typedef qimg_u8  qimg_u8x16 __attribute__((ext_vector_type(16)));\n"
"__device__ __forceinline__ qimg_u32x2 qimg_pack_a8(qimg_u8x8 v) {\n"
"    union { qimg_u8x8 b; qimg_u32x2 w; } u; u.b = v; return u.w;\n"
"}\n"

"__device__ __forceinline__ void qimg_lds_signal(void) {\n"
"    __asm__ __volatile__(\"s_barrier_signal -1\" ::: \"memory\");\n"
"}\n"
"__device__ __forceinline__ void qimg_lds_wait(void) {\n"
"    __asm__ __volatile__(\"s_barrier_wait 0xffff\" ::: \"memory\");\n"
"}\n"
"__device__ __forceinline__ void qimg_lds_barrier(void) { qimg_lds_signal(); qimg_lds_wait(); }\n"
"#define QIMG_SPLIT_HI(v) __builtin_shufflevector(v, v, 8,9,10,11,12,13,14,15)\n"
"#define QIMG_SPLIT_LO(v) __builtin_shufflevector(v, v, 0,1,2,3,4,5,6,7)\n"
"__global__ void gemm_w8a8_wmma(float *Y, const signed char *Wq, const float *wscale,\n"
"        const signed char *Xq, const float *xscale, const float *bias, int n_out, int n_in, int n_tok) {\n"
"    int tid=threadIdx.x, wave_id=tid>>5, lane=tid&31, wM=wave_id&1, wN=wave_id>>1;\n"
"    int half=lane>>4, idx=lane&15, k_off=half*8, cta_m0=blockIdx.y*128, cta_n0=blockIdx.x*128;\n"
"    __shared__ signed char smA[128*16]; __shared__ signed char smB[128*16];\n"
"    wm_i32x8 z={0,0,0,0,0,0,0,0}; wm_i32x8 cv00=z,cv01=z,cv10=z,cv11=z,cv20=z,cv21=z,cv30=z,cv31=z;\n"
"    for (int k=0;k<n_in;k+=16){\n"
"        for (int it=0;it<8;it++){int e=tid*8+it,er=e>>4,ek=e&15,row=cta_m0+er,kp=k+ek; smA[e]=(row<n_tok&&kp<n_in)?Xq[(long)row*n_in+kp]:(signed char)0;}\n"
"        for (int it=0;it<8;it++){int e=tid*8+it,er=e>>4,ek=e&15,col=cta_n0+er,kp=k+ek; smB[e]=(col<n_out&&kp<n_in)?Wq[(long)col*n_in+kp]:(signed char)0;}\n"
"        __syncthreads();\n"
"        int a_base=wM*64,b_base=wN*32; wm_u32x2 a0,a1,a2,a3,b0,b1;\n"
"        a0[0]=wm_pack4_i8(smA[(a_base+0+idx)*16+k_off+0],smA[(a_base+0+idx)*16+k_off+1],smA[(a_base+0+idx)*16+k_off+2],smA[(a_base+0+idx)*16+k_off+3]); a0[1]=wm_pack4_i8(smA[(a_base+0+idx)*16+k_off+4],smA[(a_base+0+idx)*16+k_off+5],smA[(a_base+0+idx)*16+k_off+6],smA[(a_base+0+idx)*16+k_off+7]);\n"
"        a1[0]=wm_pack4_i8(smA[(a_base+16+idx)*16+k_off+0],smA[(a_base+16+idx)*16+k_off+1],smA[(a_base+16+idx)*16+k_off+2],smA[(a_base+16+idx)*16+k_off+3]); a1[1]=wm_pack4_i8(smA[(a_base+16+idx)*16+k_off+4],smA[(a_base+16+idx)*16+k_off+5],smA[(a_base+16+idx)*16+k_off+6],smA[(a_base+16+idx)*16+k_off+7]);\n"
"        a2[0]=wm_pack4_i8(smA[(a_base+32+idx)*16+k_off+0],smA[(a_base+32+idx)*16+k_off+1],smA[(a_base+32+idx)*16+k_off+2],smA[(a_base+32+idx)*16+k_off+3]); a2[1]=wm_pack4_i8(smA[(a_base+32+idx)*16+k_off+4],smA[(a_base+32+idx)*16+k_off+5],smA[(a_base+32+idx)*16+k_off+6],smA[(a_base+32+idx)*16+k_off+7]);\n"
"        a3[0]=wm_pack4_i8(smA[(a_base+48+idx)*16+k_off+0],smA[(a_base+48+idx)*16+k_off+1],smA[(a_base+48+idx)*16+k_off+2],smA[(a_base+48+idx)*16+k_off+3]); a3[1]=wm_pack4_i8(smA[(a_base+48+idx)*16+k_off+4],smA[(a_base+48+idx)*16+k_off+5],smA[(a_base+48+idx)*16+k_off+6],smA[(a_base+48+idx)*16+k_off+7]);\n"
"        b0[0]=wm_pack4_i8(smB[(b_base+0+idx)*16+k_off+0],smB[(b_base+0+idx)*16+k_off+1],smB[(b_base+0+idx)*16+k_off+2],smB[(b_base+0+idx)*16+k_off+3]); b0[1]=wm_pack4_i8(smB[(b_base+0+idx)*16+k_off+4],smB[(b_base+0+idx)*16+k_off+5],smB[(b_base+0+idx)*16+k_off+6],smB[(b_base+0+idx)*16+k_off+7]);\n"
"        b1[0]=wm_pack4_i8(smB[(b_base+16+idx)*16+k_off+0],smB[(b_base+16+idx)*16+k_off+1],smB[(b_base+16+idx)*16+k_off+2],smB[(b_base+16+idx)*16+k_off+3]); b1[1]=wm_pack4_i8(smB[(b_base+16+idx)*16+k_off+4],smB[(b_base+16+idx)*16+k_off+5],smB[(b_base+16+idx)*16+k_off+6],smB[(b_base+16+idx)*16+k_off+7]);\n"
"        cv00=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a0,true,b0,cv00,false); cv01=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a0,true,b1,cv01,false); cv10=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a1,true,b0,cv10,false); cv11=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a1,true,b1,cv11,false);\n"
"        cv20=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a2,true,b0,cv20,false); cv21=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a2,true,b1,cv21,false); cv30=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a3,true,b0,cv30,false); cv31=__builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true,a3,true,b1,cv31,false);\n"
"        __syncthreads();\n"
"    }\n"
"    int wm0=cta_m0+wM*64,wn0=cta_n0+wN*32; wm_i32x8 *ac[8]={&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31}; int ms[8]={0,0,16,16,32,32,48,48},ns[8]={0,16,0,16,0,16,0,16};\n"
"    for(int t=0;t<8;t++){int col=wn0+ns[t]+idx; if(col>=n_out)continue; float wsc=wscale[col],bv=bias?bias[col]:0.f; wm_i32x8 acc=*ac[t]; for(int i=0;i<8;i++){int row=wm0+ms[t]+half*8+i; if(row<n_tok)Y[(long)row*n_out+col]=(float)acc[i]*xscale[row]*wsc+bv;}}\n"
"}\n"
"#define QIMG_WMMA_I8(A,B,C) C = __builtin_amdgcn_wmma_i32_16x16x16_iu8_w32_gfx12(true, A, true, B, C, false)\n"
"__device__ __forceinline__ void qimg_store_acc8_i8(float *Y, const float *bias, const float *xscale,\n"
"    const float *wscale, wm_i32x8 acc, int row0, int col, int N, int n_tok, int n_out) {\n"
"    if (col >= n_out) return; float bv = bias ? bias[col] : 0.0f; float wsc = wscale[col];\n"
"    for (int i = 0; i < 8; i++) if (row0+i < n_tok) Y[(size_t)(row0+i)*N + col] = (float)acc[i]*xscale[row0+i]*wsc + bv;\n"
"}\n"
"__global__ __launch_bounds__(128, 1)\n"
"void gemm_w8a8_pgr2(float *Y, const signed char *Wq, const signed char *Xq, const float *bias,\n"
"                    const float *xscale, const float *wscale, int n_out, int n_in, int n_tok, int M_pad) {\n"
"    int tid=threadIdx.x, wave_id=tid>>5, lane=tid&31, wM=wave_id&1, wN=wave_id>>1;\n"
"    int half=lane>>4, idx=lane&15, k_off=half*8, cta_m0=blockIdx.y*128, cta_n0=blockIdx.x*128;\n"
"    int K=n_in, N=n_out;\n"
"    int e0=tid*2+0, e1=tid*2+1; int r0=e0>>1, r1=e1>>1; int c0=(e0&1)*16, c1=(e1&1)*16;\n"
"    __shared__ qimg_u8x8 smA8[3*128*4]; __shared__ qimg_u8x8 smB8[3*128*4];\n"
"    #define I8_LOAD(na0,na1,nb0,nb1,kk) do { \\\n"
"        na0=*((const qimg_u8x16*)(Xq+(size_t)(cta_m0+r0)*K+(kk)+c0)); na1=*((const qimg_u8x16*)(Xq+(size_t)(cta_m0+r1)*K+(kk)+c1)); \\\n"
"        nb0=*((const qimg_u8x16*)(Wq+(size_t)(cta_n0+r0)*K+(kk)+c0)); nb1=*((const qimg_u8x16*)(Wq+(size_t)(cta_n0+r1)*K+(kk)+c1)); } while(0)\n"
"    #define I8_WRLDS(bi,na0,na1,nb0,nb1) do { int nb=(bi)*(128*4); \\\n"
"        smA8[nb+(c0>>3)*128+r0]=QIMG_SPLIT_LO(na0); smA8[nb+((c0>>3)+1)*128+r0]=QIMG_SPLIT_HI(na0); \\\n"
"        smA8[nb+(c1>>3)*128+r1]=QIMG_SPLIT_LO(na1); smA8[nb+((c1>>3)+1)*128+r1]=QIMG_SPLIT_HI(na1); \\\n"
"        smB8[nb+(c0>>3)*128+r0]=QIMG_SPLIT_LO(nb0); smB8[nb+((c0>>3)+1)*128+r0]=QIMG_SPLIT_HI(nb0); \\\n"
"        smB8[nb+(c1>>3)*128+r1]=QIMG_SPLIT_LO(nb1); smB8[nb+((c1>>3)+1)*128+r1]=QIMG_SPLIT_HI(nb1); } while(0)\n"
"    qimg_u8x16 g0a0,g0a1,g0b0,g0b1; I8_LOAD(g0a0,g0a1,g0b0,g0b1,0); I8_WRLDS(0,g0a0,g0a1,g0b0,g0b1);\n"
"    qimg_u8x16 g1a0,g1a1,g1b0,g1b1; int has_k1=(32<K); if(has_k1){I8_LOAD(g1a0,g1a1,g1b0,g1b1,32); I8_WRLDS(1,g1a0,g1a1,g1b0,g1b1);}\n"
"    qimg_lds_barrier();\n"
"    wm_i32x8 z={0,0,0,0,0,0,0,0};\n"
"    wm_i32x8 cv00=z,cv01=z,cv02=z,cv03=z,cv10=z,cv11=z,cv12=z,cv13=z,cv20=z,cv21=z,cv22=z,cv23=z,cv30=z,cv31=z,cv32=z,cv33=z;\n"
"    int rd_buf=0, wr_buf=2;\n"
"    for (int k=0;k<K;k+=32){\n"
"        qimg_u8x16 na0,na1,nb0,nb1; int has_far=(k+64<K); if(has_far) I8_LOAD(na0,na1,nb0,nb1,k+64);\n"
"        int base=rd_buf*(128*4), a_base=wM*64, b_base=wN*64;\n"
"        for (int kk0=0;kk0<32;kk0+=16){ int kslot=(kk0+k_off)>>3;\n"
"            qimg_u8x8 a0=smA8[base+kslot*128+(a_base+0+idx)],a1=smA8[base+kslot*128+(a_base+16+idx)],a2=smA8[base+kslot*128+(a_base+32+idx)],a3=smA8[base+kslot*128+(a_base+48+idx)];\n"
"            qimg_u8x8 b0=smB8[base+kslot*128+(b_base+0+idx)],b1=smB8[base+kslot*128+(b_base+16+idx)],b2=smB8[base+kslot*128+(b_base+32+idx)],b3=smB8[base+kslot*128+(b_base+48+idx)];\n"
"            qimg_u32x2 ra0=qimg_pack_a8(a0),ra1=qimg_pack_a8(a1),ra2=qimg_pack_a8(a2),ra3=qimg_pack_a8(a3);\n"
"            qimg_u32x2 rb0=qimg_pack_a8(b0),rb1=qimg_pack_a8(b1),rb2=qimg_pack_a8(b2),rb3=qimg_pack_a8(b3);\n"
"            QIMG_WMMA_I8(ra0,rb0,cv00);QIMG_WMMA_I8(ra0,rb1,cv01);QIMG_WMMA_I8(ra0,rb2,cv02);QIMG_WMMA_I8(ra0,rb3,cv03);\n"
"            QIMG_WMMA_I8(ra1,rb0,cv10);QIMG_WMMA_I8(ra1,rb1,cv11);QIMG_WMMA_I8(ra1,rb2,cv12);QIMG_WMMA_I8(ra1,rb3,cv13);\n"
"            QIMG_WMMA_I8(ra2,rb0,cv20);QIMG_WMMA_I8(ra2,rb1,cv21);QIMG_WMMA_I8(ra2,rb2,cv22);QIMG_WMMA_I8(ra2,rb3,cv23);\n"
"            QIMG_WMMA_I8(ra3,rb0,cv30);QIMG_WMMA_I8(ra3,rb1,cv31);QIMG_WMMA_I8(ra3,rb2,cv32);QIMG_WMMA_I8(ra3,rb3,cv33);\n"
"        }\n"
"        if(has_far){ I8_WRLDS(wr_buf,na0,na1,nb0,nb1); qimg_lds_signal(); wr_buf=(wr_buf+1)%3; rd_buf=(rd_buf+1)%3; qimg_lds_wait(); }\n"
"        else if(k+32<K){ qimg_lds_signal(); rd_buf=(rd_buf+1)%3; qimg_lds_wait(); }\n"
"    }\n"
"    #undef I8_LOAD\n"
"    #undef I8_WRLDS\n"
"    int wave_m0=cta_m0+wM*64, wave_n0=cta_n0+wN*64; int row=wave_m0+half*8; if(row>=n_tok) return;\n"
"    qimg_store_acc8_i8(Y,bias,xscale,wscale,cv00,row+0, wave_n0+0+idx, N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv01,row+0, wave_n0+16+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv02,row+0, wave_n0+32+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv03,row+0, wave_n0+48+idx,N,n_tok,n_out);\n"
"    qimg_store_acc8_i8(Y,bias,xscale,wscale,cv10,row+16,wave_n0+0+idx, N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv11,row+16,wave_n0+16+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv12,row+16,wave_n0+32+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv13,row+16,wave_n0+48+idx,N,n_tok,n_out);\n"
"    qimg_store_acc8_i8(Y,bias,xscale,wscale,cv20,row+32,wave_n0+0+idx, N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv21,row+32,wave_n0+16+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv22,row+32,wave_n0+32+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv23,row+32,wave_n0+48+idx,N,n_tok,n_out);\n"
"    qimg_store_acc8_i8(Y,bias,xscale,wscale,cv30,row+48,wave_n0+0+idx, N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv31,row+48,wave_n0+16+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv32,row+48,wave_n0+32+idx,N,n_tok,n_out); qimg_store_acc8_i8(Y,bias,xscale,wscale,cv33,row+48,wave_n0+48+idx,N,n_tok,n_out);\n"
"}\n"
"#endif\n"
"\n"

"\n"
/* ================= INT4 W4A16 RTN g16 (ported verbatim from rdna4/qimg) ============
 * Simple RTN int4 g16 weight (signed nibble [-7,7], per-(out, group-of-16) bf16 scale),
 * bf16 activation, F32 accum via WMMA. No SVDQuant LoRA / no smooth / no calibration
 * the minimal-risk int4 path that "renders clean" in qimg. Adds ~70 lines, self-contained. */
/* ---- gemm_int4w_g16_bf16a_wmma_t: BF16-act × simple-RTN-int4-g16-wt WMMA.
 * Identical tiling/lane layout to gemm_fp8w_bf16a_wmma_t; ONLY the B-load
 * differs. Weight is plain RTN int4 (NO swizzle / LoRA / smoothing):
 *   qint4  : packed nibbles row-major [n_out, n_in/2], two weights/byte
 *            (kp even -> low nibble, kp odd -> high), signed 4-bit (-8..7).
 *   scales : bf16 per (out, group16) [n_out, n_in/16].
 *   w(col,kp) = signed_nibble * bf16_to_f32(scales[col*(n_in/16) + kp/16]).
 * Requires n_in % 16 == 0 (all DiT linears are). */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_int4w_g16_bf16a_wmma_t(float *Y, const unsigned char *qint4,\n"
"        const unsigned short *scales, const float *X, const float *bias,\n"
"        int n_out, int n_in, int n_tok) {\n"
"    int tid = threadIdx.x; int wave_id = tid >> 5; int lane = tid & 31;\n"
"    int wM = wave_id & 1; int wN = wave_id >> 1; int half = lane >> 4; int idx = lane & 15; int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128; int cta_n0 = blockIdx.x * 128;\n"
"    int n_in_h = n_in >> 1; int n_in_g = n_in >> 4;\n"
"    __shared__ short smA[128*16]; __shared__ short smB[128*16];\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it; int er = e >> 4; int ek = e & 15;\n"
"            int row = cta_m0 + er; int kp = k + ek;\n"
"            float xv = (row < n_tok && kp < n_in) ? X[(long)row * n_in + kp] : 0.f;\n"
"            unsigned int xbits; memcpy(&xbits, &xv, 4); smA[er * 16 + ek] = (short)(xbits >> 16);\n"
"        }\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it; int er = e >> 4; int ek = e & 15;\n"
"            int col = cta_n0 + er; int kp = k + ek;\n"
"            float wv = 0.f;\n"
"            if (col < n_out && kp < n_in) {\n"
"                unsigned char byte = qint4[(long)col * n_in_h + (kp >> 1)];\n"
"                int nib = (kp & 1) ? (byte >> 4) : (byte & 0xF);\n"
"                int q = (nib >= 8) ? nib - 16 : nib;\n"
"                unsigned int sb = ((unsigned int)scales[(long)col * n_in_g + (kp >> 4)]) << 16;\n"
"                float sc; memcpy(&sc, &sb, 4);\n"
"                wv = (float)q * sc;\n"
"            }\n"
"            unsigned int wbits; memcpy(&wbits, &wv, 4); smB[er * 16 + ek] = (short)(wbits >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        int a_base_row = wM * 64; int b_base_row = wN * 32;\n"
"        bf16x8 a0, a1, a2, a3, b0, b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row + 0  + idx) * 16 + k_off + i];\n"
"            a1[i] = smA[(a_base_row + 16 + idx) * 16 + k_off + i];\n"
"            a2[i] = smA[(a_base_row + 32 + idx) * 16 + k_off + i];\n"
"            a3[i] = smA[(a_base_row + 48 + idx) * 16 + k_off + i];\n"
"            b0[i] = smB[(b_base_row + 0  + idx) * 16 + k_off + i];\n"
"            b1[i] = smB[(b_base_row + 16 + idx) * 16 + k_off + i];\n"
"        }\n"
"        cv00 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b0, cv00);\n"
"        cv01 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b1, cv01);\n"
"        cv10 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b0, cv10);\n"
"        cv11 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b1, cv11);\n"
"        cv20 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b0, cv20);\n"
"        cv21 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b1, cv21);\n"
"        cv30 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b0, cv30);\n"
"        cv31 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b1, cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM * 64; int wave_n0 = cta_n0 + wN * 32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int ms[8] = {0,0,16,16,32,32,48,48}; int ns[8] = {0,16,0,16,0,16,0,16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + ns[t] + idx; if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f; float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + ms[t] + half * 8 + i;\n"
"            if (row < n_tok) Y[(long)row * n_out + col] = acc[i] + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- BF16 WMMA self-attention (head_dim=128), ported from qimg
 * flash_attn_sa_wmma_f32. Replaces the scalar flash_attn_f32 — same math
 * (BF16 inputs, F32 accum, online softmax) so quality is preserved. ---- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void flash_attn_sa_wmma_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    (void)head_dim;\n"
"    int h = blockIdx.x;\n"
"    int cta_q0 = blockIdx.y * 64;\n"
"    int tid = threadIdx.x;\n"
"    int wave = tid >> 5;\n"
"    int lane = tid & 31;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int dim = n_heads * 128;\n"
"    float scale = rsqrtf(128.f);\n"
"    __shared__ short smK[16*128];\n"
"    __shared__ short smVt[128*16];\n"
"    __shared__ short smQ[4*16*128];\n"
"    __shared__ short smP[4*16*16];\n"
"    short *myQ = smQ + wave * (16*128);\n"
"    short *myP = smP + wave * (16*16);\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8 __attribute__((ext_vector_type(8)));\n"
"    int wq0 = cta_q0 + wave * 16;\n"
"    for (int it = 0; it < 64; it++) {\n"
"        int e = lane * 64 + it;\n"
"        int r = e >> 7;\n"
"        int d = e & 127;\n"
"        int qi = wq0 + r;\n"
"        float qv = (qi < N) ? Q[(long)qi*dim + h*128 + d] : 0.f;\n"
"        unsigned int b; memcpy(&b, &qv, 4);\n"
"        myQ[r*128 + d] = (short)(b >> 16);\n"
"    }\n"
"    float8 O0 = {0,0,0,0,0,0,0,0};\n"
"    float8 O1 = O0, O2 = O0, O3 = O0, O4 = O0, O5 = O0, O6 = O0, O7 = O0;\n"
"    float m_i[8], l_i[8];\n"
"    for (int i = 0; i < 8; i++) { m_i[i] = -1e30f; l_i[i] = 0.f; }\n"
"    int n_kv = (N + 15) / 16;\n"
"    for (int kv = 0; kv < n_kv; kv++) {\n"
"        int kv_base = kv * 16;\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            float v = (kvi < N) ? K[(long)kvi*dim + h*128 + d] : 0.f;\n"
"            unsigned int b; memcpy(&b, &v, 4);\n"
"            smK[r*128 + d] = (short)(b >> 16);\n"
"        }\n"
"        for (int it = 0; it < 16; it++) {\n"
"            int e = tid * 16 + it;\n"
"            int r = e >> 7;\n"
"            int d = e & 127;\n"
"            int kvi = kv_base + r;\n"
"            float v = (kvi < N) ? V[(long)kvi*dim + h*128 + d] : 0.f;\n"
"            unsigned int b; memcpy(&b, &v, 4);\n"
"            smVt[d*16 + r] = (short)(b >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        float8 S = {0,0,0,0,0,0,0,0};\n"
"        for (int kt = 0; kt < 8; kt++) {\n"
"            int k_off = kt * 16 + half * 8;\n"
"            bf16x8 qa, kb;\n"
"            for (int i = 0; i < 8; i++) {\n"
"                qa[i] = myQ[idx*128 + k_off + i];\n"
"                kb[i] = smK[idx*128 + k_off + i];\n"
"            }\n"
"            S = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(qa, kb, S);\n"
"        }\n"
"        float row_max[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float s = S[i] * scale;\n"
"            int kvi_col = kv_base + idx;\n"
"            if (kvi_col >= N) s = -1e30f;\n"
"            S[i] = s;\n"
"            float m = s;\n"
"            m = fmaxf(m, __shfl_xor(m, 1));\n"
"            m = fmaxf(m, __shfl_xor(m, 2));\n"
"            m = fmaxf(m, __shfl_xor(m, 4));\n"
"            m = fmaxf(m, __shfl_xor(m, 8));\n"
"            row_max[i] = m;\n"
"        }\n"
"        float alpha[8];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            float m_new = fmaxf(m_i[i], row_max[i]);\n"
"            alpha[i] = expf(m_i[i] - m_new);\n"
"            float p = expf(S[i] - m_new);\n"
"            S[i] = p;\n"
"            float rs = p;\n"
"            rs += __shfl_xor(rs, 1);\n"
"            rs += __shfl_xor(rs, 2);\n"
"            rs += __shfl_xor(rs, 4);\n"
"            rs += __shfl_xor(rs, 8);\n"
"            l_i[i] = l_i[i] * alpha[i] + rs;\n"
"            m_i[i] = m_new;\n"
"        }\n"
"        float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"        for (int t = 0; t < 8; t++)\n"
"            for (int i = 0; i < 8; i++) (*Os[t])[i] *= alpha[i];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = half*8 + i;\n"
"            float pv = S[i];\n"
"            unsigned int b; memcpy(&b, &pv, 4);\n"
"            myP[row*16 + idx] = (short)(b >> 16);\n"
"        }\n"
"        __builtin_amdgcn_s_waitcnt(0);\n"
"        bf16x8 pa;\n"
"        for (int i = 0; i < 8; i++) pa[i] = myP[idx*16 + half*8 + i];\n"
"        for (int t = 0; t < 8; t++) {\n"
"            int hd_base = t * 16;\n"
"            bf16x8 vb;\n"
"            for (int i = 0; i < 8; i++) vb[i] = smVt[(hd_base + idx)*16 + half*8 + i];\n"
"            *Os[t] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(pa, vb, *Os[t]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float8 *Os[8] = {&O0,&O1,&O2,&O3,&O4,&O5,&O6,&O7};\n"
"    float inv_l[8];\n"
"    for (int i = 0; i < 8; i++)\n"
"        inv_l[i] = (l_i[i] > 0.f) ? (1.f / l_i[i]) : 0.f;\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = t*16 + idx;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int qi = wq0 + half*8 + i;\n"
"            if (qi < N)\n"
"                out[(long)qi*dim + h*128 + col] = (*Os[t])[i] * inv_l[i];\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"


/* ---- gemm_bf16w_bf16a_wmma_t: F32-weight variant of the above (BF16 act ×
 * BF16 wt, F32 accum). For the VAE 3x3-conv im2col GEMMs (currently scalar
 * gemm_f32_f32, large M=spatial) — accurate (bf16 truncation, F32 accum). ---- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
/* 256 threads = 8 waves per CTA, 2×4 (M×N) wave layout, CTA tile 128×128.
 * Each wave computes a 64×32 sub-tile via 4×2 = 8 WMMA ops, reusing SMEM. */
"__global__ void gemm_bf16w_bf16a_wmma_t(float *Y, const float *W, const float *X,\n"
"                                        const float *bias,\n"
"                                        int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;       /* 0..7 */\n"
"    int lane    = tid & 31;\n"
"    int wM = wave_id & 1;         /* 0 or 1 */\n"
"    int wN = wave_id >> 1;        /* 0..3 */\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];  /* 4 KB */\n"
"    __shared__ short smB[128*16];  /* 4 KB */\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    /* 4×2 = 8 accumulators: cv[m_sub=0..3][n_sub=0..1] */\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        /* Load A[128,16] cooperatively: 2048 elements / 256 threads = 8 per thread */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;       /* 0..127 */\n"
"            int ek = e & 15;\n"
"            int row = cta_m0 + er;\n"
"            int kp  = k + ek;\n"
"            float xv = (row < n_tok && kp < n_in) ? X[(long)row * n_in + kp] : 0.f;\n"
"            unsigned int xbits; memcpy(&xbits, &xv, 4);\n"
"            smA[er * 16 + ek] = (short)(xbits >> 16);\n"
"        }\n"
"        /* Load B[128,16] via FP8 LUT */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int col = cta_n0 + er;\n"
"            int kp  = k + ek;\n"
"            float wv = (col < n_out && kp < n_in) ? W[(long)col * n_in + kp] : 0.f;\n"
"            unsigned int wbits; memcpy(&wbits, &wv, 4);\n"
"            smB[er * 16 + ek] = (short)(wbits >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        /* Each wave: 64 rows M (4 sub), 32 rows N (2 sub) */\n"
"        int a_base_row = wM * 64;\n"
"        int b_base_row = wN * 32;\n"
"        bf16x8 a0, a1, a2, a3, b0, b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row + 0  + idx) * 16 + k_off + i];\n"
"            a1[i] = smA[(a_base_row + 16 + idx) * 16 + k_off + i];\n"
"            a2[i] = smA[(a_base_row + 32 + idx) * 16 + k_off + i];\n"
"            a3[i] = smA[(a_base_row + 48 + idx) * 16 + k_off + i];\n"
"            b0[i] = smB[(b_base_row + 0  + idx) * 16 + k_off + i];\n"
"            b1[i] = smB[(b_base_row + 16 + idx) * 16 + k_off + i];\n"
"        }\n"
"        cv00 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b0, cv00);\n"
"        cv01 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b1, cv01);\n"
"        cv10 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b0, cv10);\n"
"        cv11 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b1, cv11);\n"
"        cv20 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b0, cv20);\n"
"        cv21 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b1, cv21);\n"
"        cv30 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b0, cv30);\n"
"        cv31 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b1, cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int ms[8]       = {0,   0,  16, 16, 32, 32, 48, 48};\n"
"    int ns[8]       = {0,  16,   0, 16,  0, 16,  0, 16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + ns[t] + idx;\n"
"        if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + ms[t] + half * 8 + i;\n"
"            if (row < n_tok)\n"
"                Y[(long)row * n_out + col] = acc[i] * w_scale + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"


/* ---- vae_conv3x3_wmma: FUSED 3x3 conv = im2col gather + BF16 WMMA GEMM +
 * transposed store in ONE kernel. Eliminates the materialized im2col matrix
 * (~19 GB at 1024^2) AND the separate transpose. in[ci,H,W] channel-major,
 * W[co, ci*9] F32 weights, out[co, H*W]. Grid (ceil(co/128), ceil(H*W/128)),
 * block 256. Same 2x4-wave 128x128 tiling as gemm_bf16w_bf16a_wmma_t. ---- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void vae_conv3x3_wmma(float *out, const float *W, const float *in,\n"
"                                  const float *bias, int co, int ci, int H, int Wimg) {\n"
"    int n_out = co; int n_in = ci * 9; int spatial = H * Wimg; int n_tok = spatial;\n"
"    int tid = threadIdx.x; int wave_id = tid >> 5; int lane = tid & 31;\n"
"    int wM = wave_id & 1; int wN = wave_id >> 1;\n"
"    int half = lane >> 4; int idx = lane & 15; int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128; int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];\n"
"    __shared__ short smB[128*16];\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it; int er = e >> 4; int ek = e & 15;\n"
"            int row = cta_m0 + er; int kp = k + ek; float xv = 0.f;\n"
"            if (row < n_tok && kp < n_in) {\n"
"                int ic = kp / 9; int rem = kp % 9; int ky = rem / 3; int kx = rem % 3;\n"
"                int y = row / Wimg; int x = row % Wimg; int iy = y + ky - 1; int ix = x + kx - 1;\n"
"                if (iy >= 0 && iy < H && ix >= 0 && ix < Wimg)\n"
"                    xv = in[(long)ic * spatial + (long)iy * Wimg + ix];\n"
"            }\n"
"            unsigned int xb; memcpy(&xb, &xv, 4); smA[er*16+ek] = (short)(xb >> 16);\n"
"        }\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it; int er = e >> 4; int ek = e & 15;\n"
"            int col = cta_n0 + er; int kp = k + ek;\n"
"            float wv = (col < n_out && kp < n_in) ? W[(long)col * n_in + kp] : 0.f;\n"
"            unsigned int wb; memcpy(&wb, &wv, 4); smB[er*16+ek] = (short)(wb >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        int a_base_row = wM * 64; int b_base_row = wN * 32;\n"
"        bf16x8 a0,a1,a2,a3,b0,b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row+0 +idx)*16+k_off+i];\n"
"            a1[i] = smA[(a_base_row+16+idx)*16+k_off+i];\n"
"            a2[i] = smA[(a_base_row+32+idx)*16+k_off+i];\n"
"            a3[i] = smA[(a_base_row+48+idx)*16+k_off+i];\n"
"            b0[i] = smB[(b_base_row+0 +idx)*16+k_off+i];\n"
"            b1[i] = smB[(b_base_row+16+idx)*16+k_off+i];\n"
"        }\n"
"        cv00=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0,b0,cv00);\n"
"        cv01=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0,b1,cv01);\n"
"        cv10=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1,b0,cv10);\n"
"        cv11=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1,b1,cv11);\n"
"        cv20=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2,b0,cv20);\n"
"        cv21=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2,b1,cv21);\n"
"        cv30=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3,b0,cv30);\n"
"        cv31=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3,b1,cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM*64; int wave_n0 = cta_n0 + wN*32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int msa[8] = {0,0,16,16,32,32,48,48}; int nsa[8] = {0,16,0,16,0,16,0,16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + nsa[t] + idx; if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f; float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + msa[t] + half*8 + i;\n"
"            if (row < n_tok) out[(long)col * spatial + row] = acc[i] + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"


/* ---- vae_conv1x1_wmma: 1x1 conv as a fused BF16 WMMA GEMM with transposed
 * store. out[co,spatial] = w[co,ci] @ in[ci,spatial] (+bias). Replaces the
 * scalar vae_conv2d_1x1. A[row,k] = in[k,row] = in[k*spatial+row]. ---- */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void vae_conv1x1_wmma(float *out, const float *W, const float *in,\n"
"                                  const float *bias, int co, int ci, int spatial) {\n"
"    int n_out = co; int n_in = ci; int n_tok = spatial;\n"
"    int tid = threadIdx.x; int wave_id = tid >> 5; int lane = tid & 31;\n"
"    int wM = wave_id & 1; int wN = wave_id >> 1;\n"
"    int half = lane >> 4; int idx = lane & 15; int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128; int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];\n"
"    __shared__ short smB[128*16];\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it; int er = e >> 4; int ek = e & 15;\n"
"            int row = cta_m0 + er; int kp = k + ek; float xv = 0.f;\n"
"            if (row < n_tok && kp < n_in) xv = in[(long)kp * spatial + row];\n"
"            unsigned int xb; memcpy(&xb, &xv, 4); smA[er*16+ek] = (short)(xb >> 16);\n"
"        }\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it; int er = e >> 4; int ek = e & 15;\n"
"            int col = cta_n0 + er; int kp = k + ek;\n"
"            float wv = (col < n_out && kp < n_in) ? W[(long)col * n_in + kp] : 0.f;\n"
"            unsigned int wb; memcpy(&wb, &wv, 4); smB[er*16+ek] = (short)(wb >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        int a_base_row = wM * 64; int b_base_row = wN * 32;\n"
"        bf16x8 a0,a1,a2,a3,b0,b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row+0 +idx)*16+k_off+i];\n"
"            a1[i] = smA[(a_base_row+16+idx)*16+k_off+i];\n"
"            a2[i] = smA[(a_base_row+32+idx)*16+k_off+i];\n"
"            a3[i] = smA[(a_base_row+48+idx)*16+k_off+i];\n"
"            b0[i] = smB[(b_base_row+0 +idx)*16+k_off+i];\n"
"            b1[i] = smB[(b_base_row+16+idx)*16+k_off+i];\n"
"        }\n"
"        cv00=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0,b0,cv00);\n"
"        cv01=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0,b1,cv01);\n"
"        cv10=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1,b0,cv10);\n"
"        cv11=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1,b1,cv11);\n"
"        cv20=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2,b0,cv20);\n"
"        cv21=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2,b1,cv21);\n"
"        cv30=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3,b0,cv30);\n"
"        cv31=__builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3,b1,cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM*64; int wave_n0 = cta_n0 + wN*32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int msa[8] = {0,0,16,16,32,32,48,48}; int nsa[8] = {0,16,0,16,0,16,0,16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + nsa[t] + idx; if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f; float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + msa[t] + half*8 + i;\n"
"            if (row < n_tok) out[(long)col * spatial + row] = acc[i] + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

"} /* extern C */\n"
;

#endif /* HIP_FLUX2_KERNELS_H */
