/*
 * hip_flux2_kernels.h - HIP kernel source strings for Flux.2 Klein 4B
 *
 * Contains all Flux2-specific HIP kernels as a C string literal for
 * HIPRTC runtime compilation. Concatenated after hip_kernels_common_src
 * (which opens extern "C" {) and closes it at the end.
 *
 * Port of cuda_flux2_runner.h kernels for AMD ROCm/HIP (RDNA4, gfx1201).
 * Key differences from CUDA version:
 *   - __shfl_xor_sync -> __shfl_xor (no sync mask on HIP)
 *   - __shfl_down_sync -> __shfl_down
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_FLUX2_KERNELS_H
#define HIP_FLUX2_KERNELS_H

static const char hip_flux2_specific_kernels[] =
"\n"

/* ---- FP8 LUT for weight dequantization (populated from host) ---- */
"__device__ __constant__ float d_fp8_to_f32_lut[256];\n"
"\n"

/* ---- Helpers for FP8 WMMA path (gfx12/RDNA4 only) ---- */
"static __device__ __forceinline__ unsigned char f32_to_fp8e4m3_rtne(float f) {\n"
"    if (f != f) return 0x7F;\n"
"    /* Clamp to FP8 E4M3 max (448) */\n"
"    const float FP8_MAX = 448.0f;\n"
"    if (f >  FP8_MAX) f =  FP8_MAX;\n"
"    if (f < -FP8_MAX) f = -FP8_MAX;\n"
"    unsigned int bits; memcpy(&bits, &f, 4);\n"
"    unsigned int sign = (bits >> 31) & 1u;\n"
"    int exp = (int)((bits >> 23) & 0xFFu) - 127;\n"
"    unsigned int mant23 = bits & 0x7FFFFFu;\n"
"    /* Denormal zero */\n"
"    if (exp < -9)   return (unsigned char)(sign << 7);\n"
"    if (exp <= -7) {\n"
"        /* subnormal range [-9..-7] -> shift mantissa */\n"
"        unsigned int m_with_implicit = mant23 | 0x800000u;\n"
"        int shift = 20 + (-6 - exp); /* align so top 3 bits end at bit 2..0 */\n"
"        unsigned int mant3 = (m_with_implicit + (1u << (shift - 1))) >> shift;\n"
"        return (unsigned char)((sign << 7) | (mant3 & 0x7u));\n"
"    }\n"
"    int new_exp = exp + 7;\n"
"    if (new_exp >= 15) {\n"
"        /* clamp to max finite 0bS_1111_110 = 448 */\n"
"        return (unsigned char)((sign << 7) | (15u << 3) | 0x6u);\n"
"    }\n"
"    /* normal: take top 3 bits of mantissa with round-to-nearest-even */\n"
"    unsigned int round_bit = (mant23 >> 19) & 1u;\n"
"    unsigned int sticky = mant23 & 0x7FFFFu;\n"
"    unsigned int mant3 = (mant23 >> 20) & 0x7u;\n"
"    if (round_bit && (sticky || (mant3 & 1u))) {\n"
"        mant3 += 1u;\n"
"        if (mant3 == 8u) { mant3 = 0u; new_exp += 1; if (new_exp >= 15) return (unsigned char)((sign << 7) | (15u << 3) | 0x6u); }\n"
"    }\n"
"    return (unsigned char)((sign << 7) | ((unsigned int)new_exp << 3) | mant3);\n"
"}\n"
"\n"

/* ---- gemm_fp8_wmma: FP8 WMMA GEMM on gfx12 (RDNA4). Tile 16x16x16.
 *
 * Y[M,N] = (X[M,K] @ W[N,K]^T) * w_scale + bias
 * W is raw FP8 E4M3 bytes [n_out, n_in] row-major.
 * X is F32 [n_tok, n_in] — quantized to FP8 E4M3 on-the-fly.
 *
 * Lane layout (determined empirically on gfx1201 via wmma_selftest):
 *   Input A fragment (M=16, K=16, fp8): lane L in [0,16) holds A[row=L,  k=0..7],
 *                                       lane L in [16,32) holds A[row=L-16, k=8..15]
 *   Input B fragment (N=16, K=16, fp8): lane L in [0,16) holds B[col=L,   k=0..7],
 *                                       lane L in [16,32) holds B[col=L-16, k=8..15]
 *   Output C fragment (M=16, N=16, f32):
 *     lane L in [0,16):  holds C[m=0..7 (8 rows, i=0..7), n=L]
 *     lane L in [16,32): holds C[m=8..15, n=L-16]
 *   i.e. each lane owns ONE column N and 8 consecutive M values from its half.
 *
 * Grid: (ceil(N/16), ceil(M/16)). Block: 32 threads (one wave). */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_fp8_wmma(float *Y, const unsigned char *W, const float *X,\n"
"                               const float *bias,\n"
"                               int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int lane = threadIdx.x;\n"
"    int m0 = blockIdx.y * 16;\n"
"    int n0 = blockIdx.x * 16;\n"
"    int half = lane >> 4;            /* 0 or 1 */\n"
"    int idx  = lane & 15;            /* 0..15 */\n"
"    int k_off = half * 8;            /* 0 or 8 */\n"
"    typedef float float8 __attribute__((ext_vector_type(8)));\n"
"    typedef int   int2_t __attribute__((ext_vector_type(2)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        /* A fragment: lane L loads row=idx, k=k_off..k_off+7 */\n"
"        unsigned int a0 = 0, a1 = 0;\n"
"        {\n"
"            int row = m0 + idx;\n"
"            const float *Xr = (row < n_tok) ? (X + (long)row * n_in) : 0;\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + i;\n"
"                float v = (Xr && kp < n_in) ? Xr[kp] : 0.f;\n"
"                a0 |= ((unsigned int)f32_to_fp8e4m3_rtne(v)) << (i * 8);\n"
"            }\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + 4 + i;\n"
"                float v = (Xr && kp < n_in) ? Xr[kp] : 0.f;\n"
"                a1 |= ((unsigned int)f32_to_fp8e4m3_rtne(v)) << (i * 8);\n"
"            }\n"
"        }\n"
"        /* B fragment: lane L loads col=idx, k=k_off..k_off+7 (W stored [N,K] row-major) */\n"
"        unsigned int b0 = 0, b1 = 0;\n"
"        {\n"
"            int col = n0 + idx;\n"
"            const unsigned char *Wr = (col < n_out) ? (W + (long)col * n_in) : 0;\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + i;\n"
"                unsigned char v = (Wr && kp < n_in) ? Wr[kp] : 0;\n"
"                b0 |= ((unsigned int)v) << (i * 8);\n"
"            }\n"
"            for (int i = 0; i < 4; i++) {\n"
"                int kp = k + k_off + 4 + i;\n"
"                unsigned char v = (Wr && kp < n_in) ? Wr[kp] : 0;\n"
"                b1 |= ((unsigned int)v) << (i * 8);\n"
"            }\n"
"        }\n"
"        int2_t a_vec, b_vec;\n"
"        a_vec.x = (int)a0; a_vec.y = (int)a1;\n"
"        b_vec.x = (int)b0; b_vec.y = (int)b1;\n"
"        cv = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12(a_vec, b_vec, cv);\n"
"    }\n"
"    /* Store C: lane L owns C[m = half*8 + i, n = idx] for i=0..7 */\n"
"    int col = n0 + idx;\n"
"    if (col < n_out) {\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = m0 + half * 8 + i;\n"
"            if (row < n_tok) {\n"
"                Y[(long)row * n_out + col] = cv[i] * w_scale + bv;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- gemm_fp8w_bf16a_wmma: BF16 activations × FP8 LUT weights WMMA (gfx12)
 *
 * Matrix cores with BF16 inputs: X is converted F32→BF16 on the fly,
 * FP8 weights are dequanted via LUT and truncated to BF16. Accumulator F32.
 * Output = (A_bf16 @ B_bf16^T) * w_scale + bias.
 *
 * BF16 activations preserve ~3x more mantissa precision than FP8 (7-bit vs
 * 3-bit), so the per-element quant error is ~1% instead of ~12%; the sum
 * over large K does not blow up accuracy. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
"__global__ void gemm_fp8w_bf16a_wmma(float *Y, const unsigned char *W, const float *X,\n"
"                                      const float *bias,\n"
"                                      int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int lane = threadIdx.x;\n"
"    int m0 = blockIdx.y * 16;\n"
"    int n0 = blockIdx.x * 16;\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    float8 cv = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        bf16x8 a_vec, b_vec;\n"
"        int row = m0 + idx;\n"
"        int col = n0 + idx;\n"
"        const float *Xr = (row < n_tok) ? (X + (long)row * n_in) : 0;\n"
"        const unsigned char *Wr = (col < n_out) ? (W + (long)col * n_in) : 0;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int kp = k + k_off + i;\n"
"            float xv = (Xr && kp < n_in) ? Xr[kp] : 0.f;\n"
"            float wv = (Wr && kp < n_in) ? d_fp8_to_f32_lut[Wr[kp]] : 0.f;\n"
"            unsigned int xbits, wbits;\n"
"            memcpy(&xbits, &xv, 4);\n"
"            memcpy(&wbits, &wv, 4);\n"
"            /* Round-to-nearest-even BF16 truncation */\n"
"            xbits += 0x7FFFu + ((xbits >> 16) & 1u);\n"
"            wbits += 0x7FFFu + ((wbits >> 16) & 1u);\n"
"            a_vec[i] = (short)(xbits >> 16);\n"
"            b_vec[i] = (short)(wbits >> 16);\n"
"        }\n"
"        cv = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a_vec, b_vec, cv);\n"
"    }\n"
"    int col = n0 + idx;\n"
"    if (col < n_out) {\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = m0 + half * 8 + i;\n"
"            if (row < n_tok) {\n"
"                Y[(long)row * n_out + col] = cv[i] * w_scale + bv;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- gemm_fp8w_bf16a_wmma_t: tiled BF16xFP8 WMMA — 64×64 per CTA
 *
 * 4 waves per CTA in a 2×2 M/N layout. Each wave owns a 32×32 sub-tile
 * computed as 4 WMMA ops (2 M sub-tiles × 2 N sub-tiles). CTA covers 64×64
 * output. Per K slab, 128 threads cooperatively load A[64,16] and B[64,16]
 * BF16 tiles into shared memory; each wave fetches its 32 rows and does 4
 * WMMA instructions.
 *
 * Shared memory per CTA: 2 × 64 × 16 × sizeof(short) = 4 KB.
 * Register footprint per lane: 4 × float8 accumulators + fragments = ~200 bytes.
 * Grid: (ceil(N/64), ceil(M/64)), Block: 128 threads. */
"#if defined(__gfx1200__) || defined(__gfx1201__)\n"
/* 256 threads = 8 waves per CTA, 2×4 (M×N) wave layout, CTA tile 128×128.
 * Each wave computes a 64×32 sub-tile via 4×2 = 8 WMMA ops, reusing SMEM. */
"__global__ void gemm_fp8w_bf16a_wmma_t(float *Y, const unsigned char *W, const float *X,\n"
"                                        const float *bias,\n"
"                                        int n_out, int n_in, int n_tok, float w_scale) {\n"
"    int tid = threadIdx.x;\n"
"    int wave_id = tid >> 5;       /* 0..7 */\n"
"    int lane    = tid & 31;\n"
"    int wM = wave_id & 1;         /* 0 or 1 */\n"
"    int wN = wave_id >> 1;        /* 0..3 */\n"
"    int half = lane >> 4;\n"
"    int idx  = lane & 15;\n"
"    int k_off = half * 8;\n"
"    int cta_m0 = blockIdx.y * 128;\n"
"    int cta_n0 = blockIdx.x * 128;\n"
"    __shared__ short smA[128*16];  /* 4 KB */\n"
"    __shared__ short smB[128*16];  /* 4 KB */\n"
"    typedef float float8  __attribute__((ext_vector_type(8)));\n"
"    typedef short bf16x8  __attribute__((ext_vector_type(8)));\n"
"    /* 4×2 = 8 accumulators: cv[m_sub=0..3][n_sub=0..1] */\n"
"    float8 cv00 = {0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f};\n"
"    float8 cv01 = cv00, cv10 = cv00, cv11 = cv00, cv20 = cv00, cv21 = cv00, cv30 = cv00, cv31 = cv00;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        /* Load A[128,16] cooperatively: 2048 elements / 256 threads = 8 per thread */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;       /* 0..127 */\n"
"            int ek = e & 15;\n"
"            int row = cta_m0 + er;\n"
"            int kp  = k + ek;\n"
"            float xv = (row < n_tok && kp < n_in) ? X[(long)row * n_in + kp] : 0.f;\n"
"            unsigned int xbits; memcpy(&xbits, &xv, 4);\n"
"            smA[er * 16 + ek] = (short)(xbits >> 16);\n"
"        }\n"
"        /* Load B[128,16] via FP8 LUT */\n"
"        for (int it = 0; it < 8; it++) {\n"
"            int e = tid * 8 + it;\n"
"            int er = e >> 4;\n"
"            int ek = e & 15;\n"
"            int col = cta_n0 + er;\n"
"            int kp  = k + ek;\n"
"            float wv = (col < n_out && kp < n_in) ? d_fp8_to_f32_lut[W[(long)col * n_in + kp]] : 0.f;\n"
"            unsigned int wbits; memcpy(&wbits, &wv, 4);\n"
"            smB[er * 16 + ek] = (short)(wbits >> 16);\n"
"        }\n"
"        __syncthreads();\n"
"        /* Each wave: 64 rows M (4 sub), 32 rows N (2 sub) */\n"
"        int a_base_row = wM * 64;\n"
"        int b_base_row = wN * 32;\n"
"        bf16x8 a0, a1, a2, a3, b0, b1;\n"
"        for (int i = 0; i < 8; i++) {\n"
"            a0[i] = smA[(a_base_row + 0  + idx) * 16 + k_off + i];\n"
"            a1[i] = smA[(a_base_row + 16 + idx) * 16 + k_off + i];\n"
"            a2[i] = smA[(a_base_row + 32 + idx) * 16 + k_off + i];\n"
"            a3[i] = smA[(a_base_row + 48 + idx) * 16 + k_off + i];\n"
"            b0[i] = smB[(b_base_row + 0  + idx) * 16 + k_off + i];\n"
"            b1[i] = smB[(b_base_row + 16 + idx) * 16 + k_off + i];\n"
"        }\n"
"        cv00 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b0, cv00);\n"
"        cv01 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a0, b1, cv01);\n"
"        cv10 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b0, cv10);\n"
"        cv11 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a1, b1, cv11);\n"
"        cv20 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b0, cv20);\n"
"        cv21 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a2, b1, cv21);\n"
"        cv30 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b0, cv30);\n"
"        cv31 = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32_gfx12(a3, b1, cv31);\n"
"        __syncthreads();\n"
"    }\n"
"    int wave_m0 = cta_m0 + wM * 64;\n"
"    int wave_n0 = cta_n0 + wN * 32;\n"
"    float8 *accs[8] = {&cv00,&cv01,&cv10,&cv11,&cv20,&cv21,&cv30,&cv31};\n"
"    int ms[8]       = {0,   0,  16, 16, 32, 32, 48, 48};\n"
"    int ns[8]       = {0,  16,   0, 16,  0, 16,  0, 16};\n"
"    for (int t = 0; t < 8; t++) {\n"
"        int col = wave_n0 + ns[t] + idx;\n"
"        if (col >= n_out) continue;\n"
"        float bv = bias ? bias[col] : 0.f;\n"
"        float8 acc = *accs[t];\n"
"        for (int i = 0; i < 8; i++) {\n"
"            int row = wave_m0 + ms[t] + half * 8 + i;\n"
"            if (row < n_tok)\n"
"                Y[(long)row * n_out + col] = acc[i] * w_scale + bv;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"
"\n"

/* ---- gemm_fp8_scaled_opt: 128x128 tiled FP8 LUT GEMM with per-tensor scale ----
 *
 * Ported from rdna4/qimg/hip_qimg_kernels.h::gemm_opt_fp8 with added w_scale.
 * W[N,K] is raw FP8 E4M3 bytes, X[M,K] is F32, Y[M,N] is F32 (no BF16 trunc).
 * Y = (X @ W^T) * w_scale + bias
 * 256 threads, each computes 8x8 outputs; 128x128 tile per CTA.
 * Grid: (ceil(N/128), ceil(M/128)), Block: (256) */
"__global__ void gemm_fp8_scaled_opt(float *Y, const unsigned char *W, const float *X,\n"
"                                     const float *bias, int N, int K, int M, float w_scale) {\n"
"#define OPT_BM 128\n"
"#define OPT_BN 128\n"
"#define OPT_BK 16\n"
"#define OPT_TM 8\n"
"#define OPT_TN 8\n"
"    __shared__ float smA[OPT_BK][OPT_BM];\n"
"    __shared__ float smB[OPT_BK][OPT_BN];\n"
"    int tid = threadIdx.x;\n"
"    int bm = blockIdx.y * OPT_BM, bn = blockIdx.x * OPT_BN;\n"
"    int tr = tid / 16, tc = tid % 16;\n"
"    float acc[OPT_TM][OPT_TN];\n"
"    for (int i = 0; i < OPT_TM; i++)\n"
"        for (int j = 0; j < OPT_TN; j++) acc[i][j] = 0.0f;\n"
"    for (int k = 0; k < K; k += OPT_BK) {\n"
"        for (int _i = tid; _i < OPT_BM*OPT_BK; _i += 256) {\n"
"            int _r = _i % OPT_BM, _c = _i / OPT_BM;\n"
"            int gr = bm+_r, gk = k+_c;\n"
"            smA[_c][_r] = (gr<M&&gk<K) ? X[(long)gr*K+gk] : 0.0f;\n"
"        }\n"
"        for (int _i = tid; _i < OPT_BN*OPT_BK; _i += 256) {\n"
"            int _r = _i % OPT_BN, _c = _i / OPT_BN;\n"
"            int gn = bn+_r, gk = k+_c;\n"
"            smB[_c][_r] = (gn<N&&gk<K) ? d_fp8_to_f32_lut[W[(long)gn*K+gk]] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int kk = 0; kk < OPT_BK; kk++) {\n"
"            float af[OPT_TM], bf[OPT_TN];\n"
"            for (int i=0;i<OPT_TM;i++) af[i] = smA[kk][tr*OPT_TM+i];\n"
"            for (int j=0;j<OPT_TN;j++) bf[j] = smB[kk][tc*OPT_TN+j];\n"
"            for (int i=0;i<OPT_TM;i++)\n"
"                for (int j=0;j<OPT_TN;j++) acc[i][j] += af[i]*bf[j];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    for (int i=0;i<OPT_TM;i++) {\n"
"        int gr = bm+tr*OPT_TM+i; if(gr>=M) continue;\n"
"        for (int j=0;j<OPT_TN;j++) {\n"
"            int gn = bn+tc*OPT_TN+j;\n"
"            if(gn<N) Y[(long)gr*N+gn] = acc[i][j] * w_scale + (bias?bias[gn]:0.0f);\n"
"        }\n"
"    }\n"
"#undef OPT_BM\n"
"#undef OPT_BN\n"
"#undef OPT_BK\n"
"#undef OPT_TM\n"
"#undef OPT_TN\n"
"}\n"
"\n"

/* ---- gemm_fp8_scaled_f32: FP8 LUT GEMM with per-tensor weight scale ---- */
/* Same tile shape as gemm_f32_f32 (16x16 block, 64 out per CTA).
 * W is raw FP8 E4M3 bytes [n_out, n_in], dequanted via constant-memory LUT.
 * Output: Y = (X @ W^T) * w_scale + bias
 * Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */
"__global__ void gemm_fp8_scaled_f32(float *Y, const unsigned char *W, const float *X,\n"
"                                     const float *bias,\n"
"                                     int n_out, int n_in, int n_tok, float w_scale) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? d_fp8_to_f32_lut[W[(long)w*n_in + k+ty]] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[(long)row*n_out+out_base+   tx] = acc0*w_scale + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[(long)row*n_out+out_base+16+tx] = acc1*w_scale + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[(long)row*n_out+out_base+32+tx] = acc2*w_scale + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[(long)row*n_out+out_base+48+tx] = acc3*w_scale + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */
"/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */\n"
"__global__ void gemm_f32_f32(float *Y, const float *W, const float *X,\n"
"                              const float *bias,\n"
"                              int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[(long)row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[(long)row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[(long)row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[(long)row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- SwiGLU: [n_tok, 2*mlp_h] -> [n_tok, mlp_h] ---- */
"/* ---- flux2_swiglu ---- */\n"
"__global__ void flux2_swiglu(float *out, const float *in,\n"
"                              int n_tok, int mlp_h) {\n"
"    int tok = blockIdx.x, i = threadIdx.x + blockIdx.y * blockDim.x;\n"
"    if (tok >= n_tok || i >= mlp_h) return;\n"
"    float gate = in[(long)tok * 2 * mlp_h + i];\n"
"    float val  = in[(long)tok * 2 * mlp_h + mlp_h + i];\n"
"    out[(long)tok * mlp_h + i] = (gate / (1.0f + expf(-gate))) * val;\n"
"}\n"
"\n"

/* ---- Per-head RMSNorm: x[N, dim], w[head_dim], n_heads, head_dim ---- */
"/* ---- rmsnorm_per_head_f32 ---- */\n"
"__global__ void rmsnorm_per_head_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int n_heads, int head_dim) {\n"
"    int tok = blockIdx.x, h = blockIdx.y;\n"
"    if (tok >= N || h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    float *hd = x + (long)tok * dim + h * head_dim;\n"
"    float ss = 0.0f;\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        ss += hd[i] * hd[i];\n"
"    for (int m = 16; m > 0; m >>= 1)\n"
"        ss += __shfl_xor(ss, m);\n"
"    float inv = rsqrtf(ss / (float)head_dim + 1e-6f);\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        hd[i] *= inv * w[i];\n"
"}\n"
"\n"

/* ---- adaLN: out = LN(x) * (1 + scale) + shift ---- */
"/* ---- adaln_modulate_f32 ---- */\n"
"__global__ void adaln_modulate_f32(float *__restrict__ out,\n"
"    const float *__restrict__ x, const float *__restrict__ shift,\n"
"    const float *__restrict__ scale, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) s += x[(long)tok*dim+i];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) { float d = x[(long)tok*dim+i] - mean; s += d*d; }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        out[(long)tok*dim+i] = ((x[(long)tok*dim+i] - mean) * inv) * (1.0f + scale[i]) + shift[i];\n"
"}\n"
"\n"

/* ---- Gated residual: x += gate * proj ---- */
"/* ---- gated_add_f32 ---- */\n"
"__global__ void gated_add_f32(float *__restrict__ x,\n"
"    const float *__restrict__ proj, const float *__restrict__ gate,\n"
"    int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N * dim) return;\n"
"    x[i] += gate[i % dim] * proj[i];\n"
"}\n"
"\n"

/* ---- BF16 truncation ---- */
"/* ---- truncate_bf16_f32 ---- */\n"
"__global__ void truncate_bf16_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &x[i], 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&x[i], &bits, 4);\n"
"}\n"
"\n"

/* ---- RoPE for image tokens: 2D spatial (row/col), theta=2000 ---- */
"/* ---- flux2_rope_img_f32 ---- */\n"
"__global__ void flux2_rope_img_f32(float *x, int n_tok, int n_heads,\n"
"    int head_dim, int lat_w, float theta) {\n"
"    int tok = blockIdx.z, head = blockIdx.y;\n"
"    int pair = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads || pair >= head_dim / 2) return;\n"
"    int axis_dim = head_dim / 4;\n"
"    int n_pairs = axis_dim / 2;\n"
"    int ax = -1, p_in_ax = -1;\n"
"    if (pair >= n_pairs && pair < 2 * n_pairs) { ax = 1; p_in_ax = pair - n_pairs; }\n"
"    else if (pair >= 2 * n_pairs && pair < 3 * n_pairs) { ax = 2; p_in_ax = pair - 2 * n_pairs; }\n"
"    if (ax < 0) return;\n"
"    int row = tok / lat_w, col = tok % lat_w;\n"
"    float pos = (ax == 1) ? (float)row : (float)col;\n"
"    float freq = pos / powf(theta, (float)(2 * p_in_ax) / (float)axis_dim);\n"
"    float cos_f = cosf(freq), sin_f = sinf(freq);\n"
"    long idx = (long)tok * n_heads * head_dim + head * head_dim + pair * 2;\n"
"    float a = x[idx], b = x[idx + 1];\n"
"    x[idx]     = a * cos_f - b * sin_f;\n"
"    x[idx + 1] = a * sin_f + b * cos_f;\n"
"}\n"
"\n"

/* ---- RoPE for text tokens: 1D sequence position ---- */
"/* ---- flux2_rope_txt_f32 ---- */\n"
"__global__ void flux2_rope_txt_f32(float *x, int n_tok, int n_heads,\n"
"    int head_dim, float theta) {\n"
"    int tok = blockIdx.z, head = blockIdx.y;\n"
"    int pair = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads || pair >= head_dim / 2) return;\n"
"    int axis_dim = head_dim / 4;\n"
"    int n_pairs = axis_dim / 2;\n"
"    if (pair < 3 * n_pairs) return;\n"
"    int p_in_ax = pair - 3 * n_pairs;\n"
"    float freq = (float)tok / powf(theta, (float)(2 * p_in_ax) / (float)axis_dim);\n"
"    float cos_f = cosf(freq), sin_f = sinf(freq);\n"
"    long idx = (long)tok * n_heads * head_dim + head * head_dim + pair * 2;\n"
"    float a = x[idx], b = x[idx + 1];\n"
"    x[idx]     = a * cos_f - b * sin_f;\n"
"    x[idx + 1] = a * sin_f + b * cos_f;\n"
"}\n"
"\n"

/* ---- Flash attention with separate Q/K/V: warp-cooperative FA2 ---- */
"/* ---- flash_attn_f32: separate Q/K/V, warp-cooperative ---- */\n"
"#define FA2_WARPS   4\n"
"#define FA2_BKV    16\n"
"#define FA2_HD    128\n"
"#define FA2_EPT     4\n"
"\n"
"__global__ void flash_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    int h = blockIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    /* RDNA4 wave32: warp_size=32, same as NVIDIA */\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int lane    = threadIdx.x % 32;\n"
"    int qi = blockIdx.y * FA2_WARPS + warp_id;\n"
"    float scale = rsqrtf((float)head_dim);\n"
"    float q_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) {\n"
"        int d = lane * FA2_EPT + e;\n"
"        q_r[e] = (qi < N && d < head_dim) ? Q[(long)qi * dim + h * head_dim + d] : 0.0f;\n"
"    }\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) O_r[e] = 0.0f;\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem, *smV = smem + FA2_BKV * FA2_HD;\n"
"    int n_tiles = (N + FA2_BKV - 1) / FA2_BKV;\n"
"    int n_threads = FA2_WARPS * 32;\n"
"    for (int tile = 0; tile < n_tiles; tile++) {\n"
"        int kv_base = tile * FA2_BKV;\n"
"        for (int idx = threadIdx.x; idx < FA2_BKV * FA2_HD; idx += n_threads) {\n"
"            int kj = idx / FA2_HD, d = idx % FA2_HD;\n"
"            int kv_tok = kv_base + kj;\n"
"            smK[idx] = (kv_tok < N) ? K[(long)kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"            smV[idx] = (kv_tok < N) ? V[(long)kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int kj = 0; kj < FA2_BKV; kj++) {\n"
"            float dot = 0.0f;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                dot += q_r[e] * smK[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            for (int off = 16; off > 0; off >>= 1)\n"
"                dot += __shfl_xor(dot, off);\n"
"            float score = (kv_base + kj < N) ? dot * scale : -1e30f;\n"
"            float new_max = fmaxf(m_i, score);\n"
"            float alpha = expf(m_i - new_max);\n"
"            float p = expf(score - new_max);\n"
"            l_i = l_i * alpha + p;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                O_r[e] = O_r[e] * alpha + p * smV[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            m_i = new_max;\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (qi < N) {\n"
"        float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        for (int e = 0; e < FA2_EPT; e++) {\n"
"            int d = lane * FA2_EPT + e;\n"
"            if (d < head_dim)\n"
"                out[(long)qi * dim + h * head_dim + d] = O_r[e] * inv_l;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

/* ================================================================ */
/* VAE decoder kernels                                              */
/* ================================================================ */

/* ---- im2col: [ci,H,W] -> [H*W, ci*9] for 3x3 same-padding conv ---- */
/* Grid: ceil(H*W*ci*9 / 256), Block: 256 */
"/* ---- vae_im2col_3x3: extract 3x3 patches into column matrix ---- */\n"
"__global__ void vae_im2col_3x3(float *col, const float *in,\n"
"    int ci, int H, int W) {\n"
"    int spatial = H * W;\n"
"    int col_w = ci * 9;\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = spatial * col_w;\n"
"    if (idx >= total) return;\n"
"    int s = idx / col_w;\n"  /* spatial position */
"    int k = idx % col_w;\n"  /* column index = ic * 9 + ky * 3 + kx */
"    int ic = k / 9;\n"
"    int rem = k % 9;\n"
"    int ky = rem / 3, kx = rem % 3;\n"
"    int y = s / W, x = s % W;\n"
"    int iy = y + ky - 1, ix = x + kx - 1;\n"
"    col[idx] = (iy >= 0 && iy < H && ix >= 0 && ix < W)\n"
"              ? in[(long)ic * H * W + iy * W + ix] : 0.0f;\n"
"}\n"
"\n"

/* ---- transpose_2d: in[rows, cols] -> out[cols, rows] ---- */
"/* ---- vae_transpose_2d ---- */\n"
"__global__ void vae_transpose_2d(float *out, const float *in,\n"
"    int rows, int cols) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= rows * cols) return;\n"
"    int r = idx / cols, c = idx % cols;\n"
"    out[c * rows + r] = in[idx];\n"
"}\n"
"\n"

/* ---- add_bias_broadcast: out[i] += bias[i % co] ---- */
"/* ---- vae_add_bias: out[i] += bias[i % co] ---- */\n"
"__global__ void vae_add_bias(float *out, const float *bias,\n"
"    int co, int spatial) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * spatial;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / spatial;\n"
"    out[idx] += bias[oc];\n"
"}\n"
"\n"

/* ---- Conv2D 1x1: [ci,H,W] -> [co,H,W] ---- */
"/* ---- vae_conv2d_1x1: [ci,H,W] -> [co,H,W] ---- */\n"
"__global__ void vae_conv2d_1x1(float *out, const float *in,\n"
"    const float *w, const float *bias,\n"
"    int ci, int spatial, int co) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= co * spatial) return;\n"
"    int oc = idx / spatial;\n"
"    int s  = idx % spatial;\n"
"    float sum = bias ? bias[oc] : 0.0f;\n"
"    for (int ic = 0; ic < ci; ic++)\n"
"        sum += in[(long)ic * spatial + s] * w[(long)oc * ci + ic];\n"
"    out[idx] = sum;\n"
"}\n"
"\n"

/* ---- GroupNorm + SiLU fused: [C,H,W] -> [C,H,W] ---- */
/* One block per group. Shared-memory reduction for mean/var. */
"/* ---- vae_groupnorm_silu: [C,H,W] -> [C,H,W] ---- */\n"
"__global__ void vae_groupnorm_silu(float *out, const float *in,\n"
"    const float *gamma, const float *beta,\n"
"    int C, int spatial, int num_groups, int apply_silu) {\n"
"    int g = blockIdx.x;\n"
"    if (g >= num_groups) return;\n"
"    int group_size = C / num_groups;\n"
"    int c0 = g * group_size;\n"
"    int ne = group_size * spatial;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    extern __shared__ float sdata[];\n"
"    /* Mean */\n"
"    float s = 0.0f;\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        s += in[(long)ch * spatial + sp];\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)ne;\n"
"    __syncthreads();\n"
"    /* Var */\n"
"    s = 0.0f;\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float d = in[(long)ch * spatial + sp] - mean;\n"
"        s += d * d;\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)ne + 1e-6f);\n"
"    /* Normalize + scale + shift + optional SiLU */\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float v = (in[(long)ch * spatial + sp] - mean) * inv;\n"
"        float gv = gamma ? gamma[ch] : 1.0f;\n"
"        float bv = beta  ? beta[ch]  : 0.0f;\n"
"        v = v * gv + bv;\n"
"        if (apply_silu) v = v / (1.0f + expf(-v));\n"
"        out[(long)ch * spatial + sp] = v;\n"
"    }\n"
"}\n"
"\n"

/* ---- Nearest-neighbor 2x upsample: [C,H,W] -> [C,2H,2W] ---- */
"/* ---- vae_upsample2x: [C,H,W] -> [C,2H,2W] ---- */\n"
"__global__ void vae_upsample2x(float *out, const float *in,\n"
"    int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * H * W;\n"
"    if (idx >= total) return;\n"
"    int ch = idx / (H * W);\n"
"    int rem = idx % (H * W);\n"
"    int y = rem / W, x = rem % W;\n"
"    float v = in[idx];\n"
"    int oH = 2*H, oW = 2*W;\n"
"    long base = (long)ch * oH * oW;\n"
"    out[base + (2*y)   * oW + 2*x]     = v;\n"
"    out[base + (2*y)   * oW + 2*x + 1] = v;\n"
"    out[base + (2*y+1) * oW + 2*x]     = v;\n"
"    out[base + (2*y+1) * oW + 2*x + 1] = v;\n"
"}\n"
"\n"

/* ---- VAE self-attention (single-head, mid block) ---- */
/* Input: [C, H*W], output: [C, H*W]. One block per query spatial position. */
"/* ---- vae_self_attn: single-head attention for VAE mid-block ---- */\n"
"/* Q/K/V computed externally. This kernel does the softmax+V weighted sum. */\n"
"/* Grid: (spatial,), Block: (256). Each block handles one query. */\n"
"__global__ void vae_self_attn(float *out,\n"
"    const float *Q, const float *K, const float *V,\n"
"    int spatial, int channels, float scale) {\n"
"    int qi = blockIdx.x;\n"
"    if (qi >= spatial) return;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    extern __shared__ float sdata[];\n"
"    float *scores = sdata;\n"
"    float *rbuf = sdata + spatial;\n"
"    /* Phase 1: Q[qi,:] @ K^T -> scores[spatial] */\n"
"    for (int ki = tid; ki < spatial; ki += nt) {\n"
"        float dot = 0.0f;\n"
"        for (int d = 0; d < channels; d++)\n"
"            dot += Q[qi * channels + d] * K[ki * channels + d];\n"
"        scores[ki] = dot * scale;\n"
"    }\n"
"    __syncthreads();\n"
"    /* Phase 2: Softmax */\n"
"    float lmax = -1e30f;\n"
"    for (int ki = tid; ki < spatial; ki += nt)\n"
"        lmax = fmaxf(lmax, scores[ki]);\n"
"    rbuf[tid] = lmax; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] = fmaxf(rbuf[tid], rbuf[tid+r]);\n"
"        __syncthreads();\n"
"    }\n"
"    float mx = rbuf[0]; __syncthreads();\n"
"    float lsum = 0.0f;\n"
"    for (int ki = tid; ki < spatial; ki += nt) {\n"
"        scores[ki] = expf(scores[ki] - mx);\n"
"        lsum += scores[ki];\n"
"    }\n"
"    rbuf[tid] = lsum; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] += rbuf[tid+r];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv_sum = (rbuf[0] > 0) ? 1.0f / rbuf[0] : 0.0f;\n"
"    for (int ki = tid; ki < spatial; ki += nt)\n"
"        scores[ki] *= inv_sum;\n"
"    __syncthreads();\n"
"    /* Phase 3: Weighted sum of V */\n"
"    for (int d = tid; d < channels; d += nt) {\n"
"        float acc = 0.0f;\n"
"        for (int ki = 0; ki < spatial; ki++)\n"
"            acc += scores[ki] * V[ki * channels + d];\n"
"        out[qi * channels + d] = acc;\n"
"    }\n"
"}\n"
"\n"

/* ---- Batch-norm denormalize: x[c] = x[c] * sqrt(var[c] + eps) + mean[c] ---- */
"/* ---- vae_bn_denorm: per-channel scale+shift in patchified space ---- */\n"
"__global__ void vae_bn_denorm(float *out, const float *in,\n"
"    const float *bn_mean, const float *bn_var, float eps,\n"
"    int lc, int lat_h, int lat_w, int ps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = lc * lat_h * lat_w;\n"
"    if (idx >= total) return;\n"
"    int ch = idx / (lat_h * lat_w);\n"
"    int rem = idx % (lat_h * lat_w);\n"
"    int sh = rem / lat_w, sw = rem % lat_w;\n"
"    int pr = sh % ps, pc_ = sw % ps;\n"
"    int bn_ch = ch * (ps * ps) + pr * ps + pc_;\n"
"    float mn = bn_mean[bn_ch];\n"
"    float sd = sqrtf(bn_var[bn_ch] + eps);\n"
"    out[idx] = in[idx] * sd + mn;\n"
"}\n"
"\n"

/* Close the extern "C" block opened by hip_kernels_common_src */
"} /* extern C */\n"
;

#endif /* HIP_FLUX2_KERNELS_H */
