/*
 * hip_flux2_kernels.h - HIP kernel source strings for Flux.2 Klein 4B
 *
 * Contains all Flux2-specific HIP kernels as a C string literal for
 * HIPRTC runtime compilation. Concatenated after hip_kernels_common_src
 * (which opens extern "C" {) and closes it at the end.
 *
 * Port of cuda_flux2_runner.h kernels for AMD ROCm/HIP (RDNA4, gfx1201).
 * Key differences from CUDA version:
 *   - __shfl_xor_sync -> __shfl_xor (no sync mask on HIP)
 *   - __shfl_down_sync -> __shfl_down
 *
 * SPDX-License-Identifier: MIT
 * Copyright 2025 - Present, Light Transport Entertainment Inc.
 */
#ifndef HIP_FLUX2_KERNELS_H
#define HIP_FLUX2_KERNELS_H

static const char hip_flux2_specific_kernels[] =
"\n"

/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */
"/* ---- gemm_f32_f32: pure F32 tiled GEMM ---- */\n"
"/* Grid: (ceil(n_out/64), ceil(n_tok/16)), blockDim=(16,16) */\n"
"__global__ void gemm_f32_f32(float *Y, const float *W, const float *X,\n"
"                              const float *bias,\n"
"                              int n_out, int n_in, int n_tok) {\n"
"    __shared__ float smA[16][16];\n"
"    __shared__ float smB[16][16];\n"
"    int tx = threadIdx.x, ty = threadIdx.y;\n"
"    int tok_base = blockIdx.y * 16;\n"
"    int out_base = blockIdx.x * 64;\n"
"    int row = tok_base + ty;\n"
"    float acc0 = 0.f, acc1 = 0.f, acc2 = 0.f, acc3 = 0.f;\n"
"    for (int k = 0; k < n_in; k += 16) {\n"
"        smA[ty][tx] = (tok_base+ty < n_tok && k+tx < n_in)\n"
"                      ? X[(long)(tok_base+ty)*n_in + k+tx] : 0.f;\n"
"        __syncthreads();\n"
"        { int w = out_base + tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc0 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+16+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc1 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+32+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc2 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"        { int w = out_base+48+tx;\n"
"          smB[ty][tx] = (w < n_out && k+ty < n_in)\n"
"                        ? W[(long)w*n_in + k+ty] : 0.f; }\n"
"        __syncthreads();\n"
"        for (int i = 0; i < 16; i++) acc3 += smA[ty][i] * smB[i][tx];\n"
"        __syncthreads();\n"
"    }\n"
"    if (row < n_tok) {\n"
"        if (out_base+   tx < n_out) Y[(long)row*n_out+out_base+   tx] = acc0 + (bias?bias[out_base+   tx]:0.f);\n"
"        if (out_base+16+tx < n_out) Y[(long)row*n_out+out_base+16+tx] = acc1 + (bias?bias[out_base+16+tx]:0.f);\n"
"        if (out_base+32+tx < n_out) Y[(long)row*n_out+out_base+32+tx] = acc2 + (bias?bias[out_base+32+tx]:0.f);\n"
"        if (out_base+48+tx < n_out) Y[(long)row*n_out+out_base+48+tx] = acc3 + (bias?bias[out_base+48+tx]:0.f);\n"
"    }\n"
"}\n"
"\n"

/* ---- SwiGLU: [n_tok, 2*mlp_h] -> [n_tok, mlp_h] ---- */
"/* ---- flux2_swiglu ---- */\n"
"__global__ void flux2_swiglu(float *out, const float *in,\n"
"                              int n_tok, int mlp_h) {\n"
"    int tok = blockIdx.x, i = threadIdx.x + blockIdx.y * blockDim.x;\n"
"    if (tok >= n_tok || i >= mlp_h) return;\n"
"    float gate = in[(long)tok * 2 * mlp_h + i];\n"
"    float val  = in[(long)tok * 2 * mlp_h + mlp_h + i];\n"
"    out[(long)tok * mlp_h + i] = (gate / (1.0f + expf(-gate))) * val;\n"
"}\n"
"\n"

/* ---- Per-head RMSNorm: x[N, dim], w[head_dim], n_heads, head_dim ---- */
"/* ---- rmsnorm_per_head_f32 ---- */\n"
"__global__ void rmsnorm_per_head_f32(float *__restrict__ x,\n"
"    const float *__restrict__ w, int N, int n_heads, int head_dim) {\n"
"    int tok = blockIdx.x, h = blockIdx.y;\n"
"    if (tok >= N || h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    float *hd = x + (long)tok * dim + h * head_dim;\n"
"    float ss = 0.0f;\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        ss += hd[i] * hd[i];\n"
"    for (int m = 16; m > 0; m >>= 1)\n"
"        ss += __shfl_xor(ss, m);\n"
"    float inv = rsqrtf(ss / (float)head_dim + 1e-6f);\n"
"    for (int i = threadIdx.x; i < head_dim; i += blockDim.x)\n"
"        hd[i] *= inv * w[i];\n"
"}\n"
"\n"

/* ---- adaLN: out = LN(x) * (1 + scale) + shift ---- */
"/* ---- adaln_modulate_f32 ---- */\n"
"__global__ void adaln_modulate_f32(float *__restrict__ out,\n"
"    const float *__restrict__ x, const float *__restrict__ shift,\n"
"    const float *__restrict__ scale, int N, int dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    extern __shared__ float sdata[];\n"
"    int tid = threadIdx.x;\n"
"    float s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) s += x[(long)tok*dim+i];\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)dim;\n"
"    __syncthreads();\n"
"    s = 0;\n"
"    for (int i = tid; i < dim; i += blockDim.x) { float d = x[(long)tok*dim+i] - mean; s += d*d; }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = blockDim.x/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)dim + 1e-6f);\n"
"    for (int i = tid; i < dim; i += blockDim.x)\n"
"        out[(long)tok*dim+i] = ((x[(long)tok*dim+i] - mean) * inv) * (1.0f + scale[i]) + shift[i];\n"
"}\n"
"\n"

/* ---- Gated residual: x += gate * proj ---- */
"/* ---- gated_add_f32 ---- */\n"
"__global__ void gated_add_f32(float *__restrict__ x,\n"
"    const float *__restrict__ proj, const float *__restrict__ gate,\n"
"    int N, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N * dim) return;\n"
"    x[i] += gate[i % dim] * proj[i];\n"
"}\n"
"\n"

/* ---- BF16 truncation ---- */
"/* ---- truncate_bf16_f32 ---- */\n"
"__global__ void truncate_bf16_f32(float *__restrict__ x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    unsigned int bits;\n"
"    memcpy(&bits, &x[i], 4);\n"
"    unsigned int rounding = 0x7FFFu + ((bits >> 16) & 1u);\n"
"    bits += rounding;\n"
"    bits &= 0xFFFF0000u;\n"
"    memcpy(&x[i], &bits, 4);\n"
"}\n"
"\n"

/* ---- RoPE for image tokens: 2D spatial (row/col), theta=2000 ---- */
"/* ---- flux2_rope_img_f32 ---- */\n"
"__global__ void flux2_rope_img_f32(float *x, int n_tok, int n_heads,\n"
"    int head_dim, int lat_w, float theta) {\n"
"    int tok = blockIdx.z, head = blockIdx.y;\n"
"    int pair = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads || pair >= head_dim / 2) return;\n"
"    int axis_dim = head_dim / 4;\n"
"    int n_pairs = axis_dim / 2;\n"
"    int ax = -1, p_in_ax = -1;\n"
"    if (pair >= n_pairs && pair < 2 * n_pairs) { ax = 1; p_in_ax = pair - n_pairs; }\n"
"    else if (pair >= 2 * n_pairs && pair < 3 * n_pairs) { ax = 2; p_in_ax = pair - 2 * n_pairs; }\n"
"    if (ax < 0) return;\n"
"    int row = tok / lat_w, col = tok % lat_w;\n"
"    float pos = (ax == 1) ? (float)row : (float)col;\n"
"    float freq = pos / powf(theta, (float)(2 * p_in_ax) / (float)axis_dim);\n"
"    float cos_f = cosf(freq), sin_f = sinf(freq);\n"
"    long idx = (long)tok * n_heads * head_dim + head * head_dim + pair * 2;\n"
"    float a = x[idx], b = x[idx + 1];\n"
"    x[idx]     = a * cos_f - b * sin_f;\n"
"    x[idx + 1] = a * sin_f + b * cos_f;\n"
"}\n"
"\n"

/* ---- RoPE for text tokens: 1D sequence position ---- */
"/* ---- flux2_rope_txt_f32 ---- */\n"
"__global__ void flux2_rope_txt_f32(float *x, int n_tok, int n_heads,\n"
"    int head_dim, float theta) {\n"
"    int tok = blockIdx.z, head = blockIdx.y;\n"
"    int pair = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (tok >= n_tok || head >= n_heads || pair >= head_dim / 2) return;\n"
"    int axis_dim = head_dim / 4;\n"
"    int n_pairs = axis_dim / 2;\n"
"    if (pair < 3 * n_pairs) return;\n"
"    int p_in_ax = pair - 3 * n_pairs;\n"
"    float freq = (float)tok / powf(theta, (float)(2 * p_in_ax) / (float)axis_dim);\n"
"    float cos_f = cosf(freq), sin_f = sinf(freq);\n"
"    long idx = (long)tok * n_heads * head_dim + head * head_dim + pair * 2;\n"
"    float a = x[idx], b = x[idx + 1];\n"
"    x[idx]     = a * cos_f - b * sin_f;\n"
"    x[idx + 1] = a * sin_f + b * cos_f;\n"
"}\n"
"\n"

/* ---- Flash attention with separate Q/K/V: warp-cooperative FA2 ---- */
"/* ---- flash_attn_f32: separate Q/K/V, warp-cooperative ---- */\n"
"#define FA2_WARPS   4\n"
"#define FA2_BKV    16\n"
"#define FA2_HD    128\n"
"#define FA2_EPT     4\n"
"\n"
"__global__ void flash_attn_f32(float *__restrict__ out,\n"
"    const float *__restrict__ Q, const float *__restrict__ K,\n"
"    const float *__restrict__ V,\n"
"    int N, int n_heads, int head_dim) {\n"
"    int h = blockIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int dim = n_heads * head_dim;\n"
"    /* RDNA4 wave32: warp_size=32, same as NVIDIA */\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int lane    = threadIdx.x % 32;\n"
"    int qi = blockIdx.y * FA2_WARPS + warp_id;\n"
"    float scale = rsqrtf((float)head_dim);\n"
"    float q_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) {\n"
"        int d = lane * FA2_EPT + e;\n"
"        q_r[e] = (qi < N && d < head_dim) ? Q[(long)qi * dim + h * head_dim + d] : 0.0f;\n"
"    }\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_r[FA2_EPT];\n"
"    for (int e = 0; e < FA2_EPT; e++) O_r[e] = 0.0f;\n"
"    extern __shared__ float smem[];\n"
"    float *smK = smem, *smV = smem + FA2_BKV * FA2_HD;\n"
"    int n_tiles = (N + FA2_BKV - 1) / FA2_BKV;\n"
"    int n_threads = FA2_WARPS * 32;\n"
"    for (int tile = 0; tile < n_tiles; tile++) {\n"
"        int kv_base = tile * FA2_BKV;\n"
"        for (int idx = threadIdx.x; idx < FA2_BKV * FA2_HD; idx += n_threads) {\n"
"            int kj = idx / FA2_HD, d = idx % FA2_HD;\n"
"            int kv_tok = kv_base + kj;\n"
"            smK[idx] = (kv_tok < N) ? K[(long)kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"            smV[idx] = (kv_tok < N) ? V[(long)kv_tok * dim + h * head_dim + d] : 0.0f;\n"
"        }\n"
"        __syncthreads();\n"
"        for (int kj = 0; kj < FA2_BKV; kj++) {\n"
"            float dot = 0.0f;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                dot += q_r[e] * smK[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            for (int off = 16; off > 0; off >>= 1)\n"
"                dot += __shfl_xor(dot, off);\n"
"            float score = (kv_base + kj < N) ? dot * scale : -1e30f;\n"
"            float new_max = fmaxf(m_i, score);\n"
"            float alpha = expf(m_i - new_max);\n"
"            float p = expf(score - new_max);\n"
"            l_i = l_i * alpha + p;\n"
"            for (int e = 0; e < FA2_EPT; e++)\n"
"                O_r[e] = O_r[e] * alpha + p * smV[kj * FA2_HD + lane * FA2_EPT + e];\n"
"            m_i = new_max;\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    if (qi < N) {\n"
"        float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        for (int e = 0; e < FA2_EPT; e++) {\n"
"            int d = lane * FA2_EPT + e;\n"
"            if (d < head_dim)\n"
"                out[(long)qi * dim + h * head_dim + d] = O_r[e] * inv_l;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

/* ================================================================ */
/* VAE decoder kernels                                              */
/* ================================================================ */

/* ---- im2col: [ci,H,W] -> [H*W, ci*9] for 3x3 same-padding conv ---- */
/* Grid: ceil(H*W*ci*9 / 256), Block: 256 */
"/* ---- vae_im2col_3x3: extract 3x3 patches into column matrix ---- */\n"
"__global__ void vae_im2col_3x3(float *col, const float *in,\n"
"    int ci, int H, int W) {\n"
"    int spatial = H * W;\n"
"    int col_w = ci * 9;\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = spatial * col_w;\n"
"    if (idx >= total) return;\n"
"    int s = idx / col_w;\n"  /* spatial position */
"    int k = idx % col_w;\n"  /* column index = ic * 9 + ky * 3 + kx */
"    int ic = k / 9;\n"
"    int rem = k % 9;\n"
"    int ky = rem / 3, kx = rem % 3;\n"
"    int y = s / W, x = s % W;\n"
"    int iy = y + ky - 1, ix = x + kx - 1;\n"
"    col[idx] = (iy >= 0 && iy < H && ix >= 0 && ix < W)\n"
"              ? in[(long)ic * H * W + iy * W + ix] : 0.0f;\n"
"}\n"
"\n"

/* ---- transpose_2d: in[rows, cols] -> out[cols, rows] ---- */
"/* ---- vae_transpose_2d ---- */\n"
"__global__ void vae_transpose_2d(float *out, const float *in,\n"
"    int rows, int cols) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= rows * cols) return;\n"
"    int r = idx / cols, c = idx % cols;\n"
"    out[c * rows + r] = in[idx];\n"
"}\n"
"\n"

/* ---- add_bias_broadcast: out[i] += bias[i % co] ---- */
"/* ---- vae_add_bias: out[i] += bias[i % co] ---- */\n"
"__global__ void vae_add_bias(float *out, const float *bias,\n"
"    int co, int spatial) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = co * spatial;\n"
"    if (idx >= total) return;\n"
"    int oc = idx / spatial;\n"
"    out[idx] += bias[oc];\n"
"}\n"
"\n"

/* ---- Conv2D 1x1: [ci,H,W] -> [co,H,W] ---- */
"/* ---- vae_conv2d_1x1: [ci,H,W] -> [co,H,W] ---- */\n"
"__global__ void vae_conv2d_1x1(float *out, const float *in,\n"
"    const float *w, const float *bias,\n"
"    int ci, int spatial, int co) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= co * spatial) return;\n"
"    int oc = idx / spatial;\n"
"    int s  = idx % spatial;\n"
"    float sum = bias ? bias[oc] : 0.0f;\n"
"    for (int ic = 0; ic < ci; ic++)\n"
"        sum += in[(long)ic * spatial + s] * w[(long)oc * ci + ic];\n"
"    out[idx] = sum;\n"
"}\n"
"\n"

/* ---- GroupNorm + SiLU fused: [C,H,W] -> [C,H,W] ---- */
/* One block per group. Shared-memory reduction for mean/var. */
"/* ---- vae_groupnorm_silu: [C,H,W] -> [C,H,W] ---- */\n"
"__global__ void vae_groupnorm_silu(float *out, const float *in,\n"
"    const float *gamma, const float *beta,\n"
"    int C, int spatial, int num_groups, int apply_silu) {\n"
"    int g = blockIdx.x;\n"
"    if (g >= num_groups) return;\n"
"    int group_size = C / num_groups;\n"
"    int c0 = g * group_size;\n"
"    int ne = group_size * spatial;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    extern __shared__ float sdata[];\n"
"    /* Mean */\n"
"    float s = 0.0f;\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        s += in[(long)ch * spatial + sp];\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float mean = sdata[0] / (float)ne;\n"
"    __syncthreads();\n"
"    /* Var */\n"
"    s = 0.0f;\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float d = in[(long)ch * spatial + sp] - mean;\n"
"        s += d * d;\n"
"    }\n"
"    sdata[tid] = s; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) { if (tid < r) sdata[tid] += sdata[tid+r]; __syncthreads(); }\n"
"    float inv = rsqrtf(sdata[0] / (float)ne + 1e-6f);\n"
"    /* Normalize + scale + shift + optional SiLU */\n"
"    for (int i = tid; i < ne; i += nt) {\n"
"        int ch = c0 + i / spatial;\n"
"        int sp = i % spatial;\n"
"        float v = (in[(long)ch * spatial + sp] - mean) * inv;\n"
"        float gv = gamma ? gamma[ch] : 1.0f;\n"
"        float bv = beta  ? beta[ch]  : 0.0f;\n"
"        v = v * gv + bv;\n"
"        if (apply_silu) v = v / (1.0f + expf(-v));\n"
"        out[(long)ch * spatial + sp] = v;\n"
"    }\n"
"}\n"
"\n"

/* ---- Nearest-neighbor 2x upsample: [C,H,W] -> [C,2H,2W] ---- */
"/* ---- vae_upsample2x: [C,H,W] -> [C,2H,2W] ---- */\n"
"__global__ void vae_upsample2x(float *out, const float *in,\n"
"    int C, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = C * H * W;\n"
"    if (idx >= total) return;\n"
"    int ch = idx / (H * W);\n"
"    int rem = idx % (H * W);\n"
"    int y = rem / W, x = rem % W;\n"
"    float v = in[idx];\n"
"    int oH = 2*H, oW = 2*W;\n"
"    long base = (long)ch * oH * oW;\n"
"    out[base + (2*y)   * oW + 2*x]     = v;\n"
"    out[base + (2*y)   * oW + 2*x + 1] = v;\n"
"    out[base + (2*y+1) * oW + 2*x]     = v;\n"
"    out[base + (2*y+1) * oW + 2*x + 1] = v;\n"
"}\n"
"\n"

/* ---- VAE self-attention (single-head, mid block) ---- */
/* Input: [C, H*W], output: [C, H*W]. One block per query spatial position. */
"/* ---- vae_self_attn: single-head attention for VAE mid-block ---- */\n"
"/* Q/K/V computed externally. This kernel does the softmax+V weighted sum. */\n"
"/* Grid: (spatial,), Block: (256). Each block handles one query. */\n"
"__global__ void vae_self_attn(float *out,\n"
"    const float *Q, const float *K, const float *V,\n"
"    int spatial, int channels, float scale) {\n"
"    int qi = blockIdx.x;\n"
"    if (qi >= spatial) return;\n"
"    int tid = threadIdx.x;\n"
"    int nt = blockDim.x;\n"
"    extern __shared__ float sdata[];\n"
"    float *scores = sdata;\n"
"    float *rbuf = sdata + spatial;\n"
"    /* Phase 1: Q[qi,:] @ K^T -> scores[spatial] */\n"
"    for (int ki = tid; ki < spatial; ki += nt) {\n"
"        float dot = 0.0f;\n"
"        for (int d = 0; d < channels; d++)\n"
"            dot += Q[qi * channels + d] * K[ki * channels + d];\n"
"        scores[ki] = dot * scale;\n"
"    }\n"
"    __syncthreads();\n"
"    /* Phase 2: Softmax */\n"
"    float lmax = -1e30f;\n"
"    for (int ki = tid; ki < spatial; ki += nt)\n"
"        lmax = fmaxf(lmax, scores[ki]);\n"
"    rbuf[tid] = lmax; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] = fmaxf(rbuf[tid], rbuf[tid+r]);\n"
"        __syncthreads();\n"
"    }\n"
"    float mx = rbuf[0]; __syncthreads();\n"
"    float lsum = 0.0f;\n"
"    for (int ki = tid; ki < spatial; ki += nt) {\n"
"        scores[ki] = expf(scores[ki] - mx);\n"
"        lsum += scores[ki];\n"
"    }\n"
"    rbuf[tid] = lsum; __syncthreads();\n"
"    for (int r = nt/2; r > 0; r >>= 1) {\n"
"        if (tid < r) rbuf[tid] += rbuf[tid+r];\n"
"        __syncthreads();\n"
"    }\n"
"    float inv_sum = (rbuf[0] > 0) ? 1.0f / rbuf[0] : 0.0f;\n"
"    for (int ki = tid; ki < spatial; ki += nt)\n"
"        scores[ki] *= inv_sum;\n"
"    __syncthreads();\n"
"    /* Phase 3: Weighted sum of V */\n"
"    for (int d = tid; d < channels; d += nt) {\n"
"        float acc = 0.0f;\n"
"        for (int ki = 0; ki < spatial; ki++)\n"
"            acc += scores[ki] * V[ki * channels + d];\n"
"        out[qi * channels + d] = acc;\n"
"    }\n"
"}\n"
"\n"

/* ---- Batch-norm denormalize: x[c] = x[c] * sqrt(var[c] + eps) + mean[c] ---- */
"/* ---- vae_bn_denorm: per-channel scale+shift in patchified space ---- */\n"
"__global__ void vae_bn_denorm(float *out, const float *in,\n"
"    const float *bn_mean, const float *bn_var, float eps,\n"
"    int lc, int lat_h, int lat_w, int ps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = lc * lat_h * lat_w;\n"
"    if (idx >= total) return;\n"
"    int ch = idx / (lat_h * lat_w);\n"
"    int rem = idx % (lat_h * lat_w);\n"
"    int sh = rem / lat_w, sw = rem % lat_w;\n"
"    int pr = sh % ps, pc_ = sw % ps;\n"
"    int bn_ch = ch * (ps * ps) + pr * ps + pc_;\n"
"    float mn = bn_mean[bn_ch];\n"
"    float sd = sqrtf(bn_var[bn_ch] + eps);\n"
"    out[idx] = in[idx] * sd + mn;\n"
"}\n"
"\n"

/* Close the extern "C" block opened by hip_kernels_common_src */
"} /* extern C */\n"
;

#endif /* HIP_FLUX2_KERNELS_H */
