#define _GNU_SOURCE
#include <mpi.h>
#define Q38FN_TP_BLOB_IMPLEMENTATION
#include "../common/q38fn_tp_blob.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>

static uint64_t hash_bytes(const void*p,size_t n){const unsigned char*s=p;uint64_t h=UINT64_C(1469598103934665603);while(n--){h^=*s++;h*=UINT64_C(1099511628211);}return h;}
static int write_all(int fd,const void*p,size_t n){const unsigned char*s=p;while(n){ssize_t z=write(fd,s,n);if(z<=0)return-1;s+=z;n-=(size_t)z;}return 0;}
static float bf16_to_float(uint16_t v){uint32_t u=(uint32_t)v<<16;float x;memcpy(&x,&u,4);return x;}
static int selected(const char*n){const char*mode=getenv("Q38FN_TP_Q8_SELECT");int delta=strstr(n,".linear_attn.")!=NULL,delta_qkv=q38fn_tp_ends_with(n,".linear_attn.in_proj_qkv.weight"),delta_z=q38fn_tp_ends_with(n,".linear_attn.in_proj_z.weight"),delta_ab=q38fn_tp_ends_with(n,".linear_attn.in_proj_a.weight")||q38fn_tp_ends_with(n,".linear_attn.in_proj_b.weight"),delta_out=q38fn_tp_ends_with(n,".linear_attn.out_proj.weight"),gate=q38fn_tp_ends_with(n,".mlp.gate.weight"),moe_up=q38fn_tp_ends_with(n,".mlp.experts.gate_up_proj")||q38fn_tp_ends_with(n,".mlp.shared_expert.gate_proj.weight")||q38fn_tp_ends_with(n,".mlp.shared_expert.up_proj.weight"),hc_up=strstr(n,"_hyper_connection.input_mix_weight_up.weight")!=NULL,hc_down=strstr(n,"_hyper_connection.input_mix_weight_down.weight")!=NULL,hc=hc_up||hc_down;if(!mode||!*mode||!strcmp(mode,"all"))return delta||gate;if(!strcmp(mode,"gate"))return gate;if(!strcmp(mode,"delta"))return delta;if(!strcmp(mode,"delta_qkv"))return delta_qkv;if(!strcmp(mode,"delta_z"))return delta_z;if(!strcmp(mode,"delta_ab"))return delta_ab;if(!strcmp(mode,"delta_out"))return delta_out;if(!strcmp(mode,"moe_up"))return moe_up;if(!strcmp(mode,"hc"))return hc;if(!strcmp(mode,"hc_up"))return hc_up;if(!strcmp(mode,"hc_down"))return hc_down;if(!strcmp(mode,"delta_qkv_moe_up"))return delta_qkv||moe_up;if(!strcmp(mode,"delta_qkv_moe_up_gate"))return delta_qkv||moe_up||gate;if(!strcmp(mode,"delta_qkv_out_moe_up"))return delta_qkv||delta_out||moe_up;return 0;}
static void write_entry(FILE*f,const q38fn_tp_blob_entry*e,uint64_t off,uint64_t bytes,uint64_t hash){fprintf(f,"%llu %llu %016llx %d %d %d",(unsigned long long)off,(unsigned long long)bytes,(unsigned long long)hash,(int)e->kind,e->axis,e->ndims);for(int d=0;d<e->ndims;d++)fprintf(f," %llu",(unsigned long long)e->shape[d]);fprintf(f," %d",e->n_ranges);for(int r=0;r<e->n_ranges;r++)fprintf(f," %llu %llu",(unsigned long long)e->range[r].start,(unsigned long long)e->range[r].count);fprintf(f," %s\n",e->name);}
int main(int argc,char**argv){int rank,ranks,rc=1,fd=-1,count=0;char srcdir[4096],dstdir[4096],bp[8192],mp[8192],partial[8192];FILE*mf=NULL;q38fn_tp_blob b={0};uint64_t off=0;MPI_Init(&argc,&argv);MPI_Comm_rank(MPI_COMM_WORLD,&rank);MPI_Comm_size(MPI_COMM_WORLD,&ranks);if(argc!=3||ranks!=Q38FN_TP_RANKS)goto done;setenv("Q38FN_TP_FILE_BACKED","1",1);snprintf(srcdir,sizeof(srcdir),"%s/rank-%02d",argv[1],rank);snprintf(dstdir,sizeof(dstdir),"%s/rank-%02d",argv[2],rank);mkdir(argv[2],0700);mkdir(dstdir,0700);snprintf(bp,sizeof(bp),"%s/tp12-v%d.blob",dstdir,Q38FN_TP_LAYOUT_VERSION);snprintf(mp,sizeof(mp),"%s/tp12-v%d.manifest",dstdir,Q38FN_TP_LAYOUT_VERSION);snprintf(partial,sizeof(partial),"%s.partial",mp);if(q38fn_tp_blob_open(&b,srcdir,0)||(fd=open(bp,O_CREAT|O_TRUNC|O_WRONLY,0600))<0||!(mf=fopen(partial,"w")))goto done;fprintf(mf,"# Q38FNTP layout=%d rank=%d ranks=%d layers=0 q8_overlay=1\n",Q38FN_TP_LAYOUT_VERSION,rank,ranks);
 for(int ei=0;ei<b.n_entries;ei++){q38fn_tp_blob_entry*e=&b.entries[ei];if((!e->q5_data&&!e->data)||!selected(e->name))continue;size_t cols=e->kind==Q38FN_TP_AXIS1?(size_t)e->range[0].count:(size_t)e->shape[e->ndims-1];if(!cols||cols%32)goto done;size_t rows=e->q5_data?e->q5_bytes/(sizeof(q38fn_q5_block)*(cols/32)):e->bytes/(cols*sizeof(uint16_t)),bytes=q38fn_q8_bytes(rows,cols);unsigned char*q=malloc(bytes);if(!q)goto done;int expert_blocks=e->kind==Q38FN_TP_EXPERT_GATE_UP;size_t block_rows=rows;if(expert_blocks){block_rows=0;for(int ri=0;ri<e->n_ranges;ri++)block_rows+=(size_t)e->range[ri].count;if(!block_rows||rows%block_rows){free(q);goto done;}}size_t block_bytes=q38fn_q8_bytes(block_rows,cols);int failed=0;
#ifdef _OPENMP
#pragma omp parallel for schedule(static) reduction(|:failed)
#endif
  for(size_t r=0;r<rows;r++){float*row=malloc(cols*sizeof(float));if(!row){failed=1;continue;}if(e->q5_data){if(q38fn_q5_dequantize_row(row,e->q5_data+r*(cols/32),cols)){failed=1;free(row);continue;}}else for(size_t c=0;c<cols;c++)row[c]=bf16_to_float(e->data[r*cols+c]);size_t block=expert_blocks?r/block_rows:0,rr=expert_blocks?r%block_rows:r;unsigned char*qb=q+block*block_bytes;int8_t*w=(int8_t*)qb+rr*cols;float*sc=(float*)(qb+block_rows*cols)+rr;float ma=0;for(size_t c=0;c<cols;c++)ma=fmaxf(ma,fabsf(row[c]));*sc=ma>0?ma/127:1;float inv=1/(*sc);for(size_t c=0;c<cols;c++){long z=lrintf(row[c]*inv);w[c]=(int8_t)(z<-127?-127:z>127?127:z);}free(row);}if(failed){free(q);goto done;}uint64_t aligned=(off+255u)&~UINT64_C(255);if(aligned>off){unsigned char pad[256]={0};if(write_all(fd,pad,(size_t)(aligned-off))){free(q);goto done;}off=aligned;}if(write_all(fd,q,bytes)){free(q);goto done;}write_entry(mf,e,off,bytes,hash_bytes(q,bytes));off+=bytes;count++;free(q);}
 fprintf(mf,"# COMPLETE blob_bytes=%llu tensors=%d q8_overlay=1\n",(unsigned long long)off,count);if(!count||fflush(mf)||fsync(fileno(mf))||fsync(fd))goto done;fclose(mf);mf=NULL;close(fd);fd=-1;q38fn_tp_blob_close(&b);MPI_Barrier(MPI_COMM_WORLD);if(rename(partial,mp))goto done;fprintf(stderr,"Q38FN_TP_Q8_OVERLAY rank=%d bytes=%llu tensors=%d\n",rank,(unsigned long long)off,count);rc=0;
done:if(mf)fclose(mf);if(fd>=0)close(fd);q38fn_tp_blob_close(&b);if(rc)MPI_Abort(MPI_COMM_WORLD,rc);MPI_Finalize();return rc;}
