/* cuda_fa_kernels.h — FlashAttention-forward device kernels for NVRTC.
 *
 * No cuda_fp16.h needed: f16 is `unsigned short` and we use cvt.f32.f16 PTX
 * inline (matches cuda/cuda_kernels_common.h convention).
 *
 * Math: O[b,h,i,d] = sum_j softmax_j(Q[b,h,i,:] · K[b,h,j,:] / sqrt(D)) * V[b,h,j,d]
 * Layout: Q,K,V,O all [B*H, S, D] row-major.
 */

#ifndef CUDA_FA_KERNELS_H
#define CUDA_FA_KERNELS_H

static const char *k_fa_common_prelude =
"typedef unsigned short half_raw;\n"
"__device__ __forceinline__ float h2f(half_raw h) {\n"
"    float f; asm(\"cvt.f32.f16 %0, %1;\" : \"=f\"(f) : \"h\"(h)); return f;\n"
"}\n"
"__device__ __forceinline__ half_raw f2h(float f) {\n"
"    half_raw h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n";

/* v1: scalar fma, online softmax, K/V tiled to SMEM (fp32). */
static const char *k_fa_f16_v1_src =
"typedef unsigned short half_raw;\n"
"__device__ __forceinline__ float h2f(half_raw h) {\n"
"    float f; asm(\"cvt.f32.f16 %0, %1;\" : \"=f\"(f) : \"h\"(h)); return f;\n"
"}\n"
"__device__ __forceinline__ half_raw f2h(float f) {\n"
"    half_raw h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"\n"
"#ifndef FA_BKV\n"
"#define FA_BKV 64\n"
"#endif\n"
"\n"
"extern \"C\" __global__\n"
"__launch_bounds__(128)\n"
"void fa_f16_v1(half_raw *O,\n"
"               const half_raw *Q,\n"
"               const half_raw *K,\n"
"               const half_raw *V,\n"
"               int S, int D, float scale) {\n"
"    int qi  = blockIdx.x;\n"
"    int bh  = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (tid >= D) return;\n"
"\n"
"    const half_raw *Qh = Q + (size_t)bh * S * D + (size_t)qi * D;\n"
"    const half_raw *Kh = K + (size_t)bh * S * D;\n"
"    const half_raw *Vh = V + (size_t)bh * S * D;\n"
"          half_raw *Oh = O + (size_t)bh * S * D + (size_t)qi * D;\n"
"\n"
"    float q_d = h2f(Qh[tid]);\n"
"\n"
"    extern __shared__ float smem[];\n"
"    float *sK    = smem;\n"
"    float *sV    = sK + FA_BKV * D;\n"
"    float *s_red = sV + FA_BKV * D;\n"
"\n"
"    float m_i = -1e30f;\n"
"    float l_i = 0.0f;\n"
"    float o_d = 0.0f;\n"
"\n"
"    int n_tiles = (S + FA_BKV - 1) / FA_BKV;\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int kv0 = t * FA_BKV;\n"
"        int total = FA_BKV * D;\n"
"        for (int idx = tid; idx < total; idx += blockDim.x) {\n"
"            int j = idx / D;\n"
"            int dd = idx - j * D;\n"
"            int kv = kv0 + j;\n"
"            if (kv < S) {\n"
"                sK[idx] = h2f(Kh[(size_t)kv * D + dd]);\n"
"                sV[idx] = h2f(Vh[(size_t)kv * D + dd]);\n"
"            } else {\n"
"                sK[idx] = 0.0f; sV[idx] = 0.0f;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* Compute all FA_BKV scores in parallel, with a single cross-warp\n"
"         * aggregation pass at the end (was: 2 syncs * FA_BKV inside loop). */\n"
"        __shared__ float warp_sums[4 * FA_BKV];\n"
"        int wid = tid >> 5;\n"
"        int lane = tid & 31;\n"
"        for (int j = 0; j < FA_BKV; j++) {\n"
"            float p = q_d * sK[(size_t)j * D + tid];\n"
"            for (int o = 16; o > 0; o >>= 1)\n"
"                p += __shfl_xor_sync(0xffffffff, p, o);\n"
"            if (lane == 0) warp_sums[wid * FA_BKV + j] = p;\n"
"        }\n"
"        __syncthreads();\n"
"        int n_warps = blockDim.x >> 5;\n"
"        if (tid < FA_BKV) {\n"
"            float s = 0.0f;\n"
"            for (int w = 0; w < n_warps; w++) s += warp_sums[w * FA_BKV + tid];\n"
"            s_red[tid] = s * scale;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        float mx_tile = -1e30f;\n"
"        for (int j = 0; j < FA_BKV; j++) {\n"
"            float s = s_red[j];\n"
"            int kv = kv0 + j;\n"
"            if (kv >= S) s = -1e30f;\n"
"            if (s > mx_tile) mx_tile = s;\n"
"        }\n"
"        float m_new = fmaxf(m_i, mx_tile);\n"
"        float alpha = expf(m_i - m_new);\n"
"        l_i *= alpha;\n"
"        o_d *= alpha;\n"
"        m_i  = m_new;\n"
"\n"
"        for (int j = 0; j < FA_BKV; j++) {\n"
"            int kv = kv0 + j;\n"
"            float s = (kv < S) ? s_red[j] : -1e30f;\n"
"            float e = expf(s - m_i);\n"
"            l_i += e;\n"
"            o_d += e * sV[(size_t)j * D + tid];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"    Oh[tid] = f2h(o_d * inv_l);\n"
"}\n";

/* v2: one warp per query row. All score reductions are warp-local (warp shuffle),
 *     no __syncthreads inside the j-loop. Each thread holds D/32 D-coords of Q
 *     and accumulates D/32 O-coords. K/V tile in SMEM (fp32) shared across warps.
 *
 *     CTA: 4 warps = 128 threads -> 4 query rows per CTA.
 *     Grid: ((S+3)/4, B*H).
 *     Restrictions: D divisible by 32 (so each thread holds whole #D-coords).
 *                   D <= 128 (DPT_MAX = 4 floats per thread).
 */
static const char *k_fa_f16_v2_src =
"typedef unsigned short half_raw;\n"
"__device__ __forceinline__ float h2f(half_raw h) {\n"
"    float f; asm(\"cvt.f32.f16 %0, %1;\" : \"=f\"(f) : \"h\"(h)); return f;\n"
"}\n"
"__device__ __forceinline__ half_raw f2h(float f) {\n"
"    half_raw h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"\n"
"#ifndef FA_BKV\n"
"#define FA_BKV 64\n"
"#endif\n"
"#ifndef FA_W\n"
"#define FA_W 8   /* warps per CTA = query rows per CTA */\n"
"#endif\n"
"#define FA_DPT_MAX 4   /* max D coords per thread = D_MAX/32 = 128/32 */\n"
"\n"
"extern \"C\" __global__\n"
"__launch_bounds__(256)\n"
"void fa_f16_v2(half_raw *O,\n"
"               const half_raw *Q,\n"
"               const half_raw *K,\n"
"               const half_raw *V,\n"
"               int S, int D, float scale) {\n"
"    int wid  = threadIdx.x >> 5;\n"
"    int lane = threadIdx.x & 31;\n"
"    int qi   = blockIdx.x * FA_W + wid;\n"
"    int bh   = blockIdx.y;\n"
"    int dpt  = D >> 5;        /* D / 32 */\n"
"\n"
"    const half_raw *Qh = Q + (size_t)bh * S * D;\n"
"    const half_raw *Kh = K + (size_t)bh * S * D;\n"
"    const half_raw *Vh = V + (size_t)bh * S * D;\n"
"          half_raw *Oh = O + (size_t)bh * S * D;\n"
"\n"
"    /* Q row in registers: this thread owns dpt contiguous D-coords. */\n"
"    float q_loc[FA_DPT_MAX];\n"
"    int d_base = lane * dpt;\n"
"    if (qi < S) {\n"
"        for (int k = 0; k < dpt; k++) q_loc[k] = h2f(Qh[(size_t)qi * D + d_base + k]);\n"
"    } else {\n"
"        for (int k = 0; k < dpt; k++) q_loc[k] = 0.0f;\n"
"    }\n"
"\n"
"    /* SMEM K/V tile in f16 (half SMEM bytes vs fp32, halves load BW). */\n"
"    extern __shared__ half_raw smem[];\n"
"    half_raw *sK = smem;\n"
"    half_raw *sV = sK + FA_BKV * D;\n"
"\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float o_loc[FA_DPT_MAX];\n"
"    for (int k = 0; k < dpt; k++) o_loc[k] = 0.0f;\n"
"\n"
"    int n_tiles = (S + FA_BKV - 1) / FA_BKV;\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int kv0 = t * FA_BKV;\n"
"        /* Cooperative K/V load (128 threads) */\n"
"        int total = FA_BKV * D;\n"
"        for (int idx = threadIdx.x; idx < total; idx += blockDim.x) {\n"
"            int j = idx / D, dd = idx - j * D;\n"
"            int kv = kv0 + j;\n"
"            if (kv < S) {\n"
"                sK[idx] = Kh[(size_t)kv * D + dd];\n"
"                sV[idx] = Vh[(size_t)kv * D + dd];\n"
"            } else {\n"
"                sK[idx] = 0; sV[idx] = 0;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* Per-warp score compute: warp owns row qi, FA_BKV scores. */\n"
"        float scores[FA_BKV];\n"
"        for (int j = 0; j < FA_BKV; j++) {\n"
"            float p = 0.0f;\n"
"            for (int k = 0; k < dpt; k++)\n"
"                p += q_loc[k] * h2f(sK[(size_t)j * D + d_base + k]);\n"
"            for (int o = 16; o > 0; o >>= 1)\n"
"                p += __shfl_xor_sync(0xffffffff, p, o);\n"
"            scores[j] = (kv0 + j < S) ? p * scale : -1e30f;\n"
"        }\n"
"\n"
"        /* Online softmax update — all warp-local. */\n"
"        float mx = -1e30f;\n"
"        for (int j = 0; j < FA_BKV; j++) if (scores[j] > mx) mx = scores[j];\n"
"        float m_new = fmaxf(m_i, mx);\n"
"        float alpha = expf(m_i - m_new);\n"
"        l_i *= alpha;\n"
"        for (int k = 0; k < dpt; k++) o_loc[k] *= alpha;\n"
"        m_i = m_new;\n"
"\n"
"        for (int j = 0; j < FA_BKV; j++) {\n"
"            float e = (kv0 + j < S) ? expf(scores[j] - m_i) : 0.0f;\n"
"            l_i += e;\n"
"            for (int k = 0; k < dpt; k++)\n"
"                o_loc[k] += e * h2f(sV[(size_t)j * D + d_base + k]);\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    if (qi < S) {\n"
"        float inv = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"        for (int k = 0; k < dpt; k++)\n"
"            Oh[(size_t)qi * D + d_base + k] = f2h(o_loc[k] * inv);\n"
"    }\n"
"}\n";

/* v3: tensor-core flash attention via mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32.
 *
 *   D = 128 fixed (compile-time).
 *   CTA: 4 warps = 128 threads. Each warp owns BR=16 query rows.
 *   Grid: ((S+63)/64, B*H).
 *   BC = 32 KV tile size.
 *   SMEM:  sK[BC, D] f16   (16*32*128*2 / 16 = 8 KiB)
 *          sVT[D, BC] f16  (V transposed during load, for B-frag contiguity in P@V)
 *
 * Per warp register accumulators:
 *   qfrag[D/16][4] b32  = 8 K-iters × 4 b32   = 32 b32 (Q held across K-tiles)
 *   ofrag[D/8][4]  fp32 = 16 N-tiles × 4 fp32 = 64 fp32 (O held across K-tiles)
 *   sfrag[BC/8][4] fp32 = 4 N-tiles × 4 fp32  = 16 fp32 (S transient per K-tile)
 *   pfrag[BC/16][4] b32 = 2 K-iters × 4 b32   = 8 b32  (P f16 transient)
 *   m_a, m_b, l_a, l_b: 4 fp32 (per the 2 rows owned by each thread in m16n8k16 layout)
 */
static const char *k_fa_f16_v3_src =
"typedef unsigned short half_raw;\n"
"typedef unsigned int   uint32_t;\n"
"__device__ __forceinline__ float h2f(half_raw h) {\n"
"    float f; asm(\"cvt.f32.f16 %0, %1;\" : \"=f\"(f) : \"h\"(h)); return f;\n"
"}\n"
"__device__ __forceinline__ half_raw f2h(float f) {\n"
"    half_raw h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"__device__ __forceinline__ uint32_t pack_h(float lo, float hi) {\n"
"    uint32_t r;\n"
"    asm(\"{ .reg .b16 a, b; cvt.rn.f16.f32 a, %1; cvt.rn.f16.f32 b, %2;\\n\"\n"
"        \"  mov.b32 %0, {a, b}; }\" : \"=r\"(r) : \"f\"(lo), \"f\"(hi));\n"
"    return r;\n"
"}\n"
"\n"
"#define V3_D    128\n"
"#define V3_BR   64\n"
"#define V3_BC   32\n"
"#define V3_DK   (V3_D / 16)   /* 8 K-iters of mma along D for Q@K^T   */\n"
"#define V3_BCN  (V3_BC / 8)   /* 4 N-tiles along BC for Q@K^T         */\n"
"#define V3_BCK  (V3_BC / 16)  /* 2 K-iters along BC for P@V           */\n"
"#define V3_DN   (V3_D  / 8)   /* 16 N-tiles along D for P@V           */\n"
"/* Pad sK row stride: D=128 -> stride 256B = 64 4B-words (0 mod 32, bad).\n"
"   Add 8 halves -> 272B = 68 4B-words (4 mod 32, good).                */\n"
"#define V3_DP   (V3_D + 8)\n"
"/* Pad sVT row stride: BC=32 -> 64B = 16 (16 mod 32, 2-way conflict).\n"
"   Add 8 halves -> 80B = 20 4B-words (20 mod 32, good).                */\n"
"#define V3_BCP  (V3_BC + 8)\n"
"\n"
"extern \"C\" __global__\n"
"__launch_bounds__(128)\n"
"void fa_f16_v3(half_raw *O,\n"
"               const half_raw *Q,\n"
"               const half_raw *K,\n"
"               const half_raw *V,\n"
"               int S, int D_in, float scale) {\n"
"    /* D_in must equal V3_D=128 (caller is responsible). */\n"
"    int bh   = blockIdx.y;\n"
"    int wid  = threadIdx.x >> 5;\n"
"    int lane = threadIdx.x & 31;\n"
"    int warp_q0 = blockIdx.x * V3_BR + wid * 16;\n"
"\n"
"    int row_a = lane >> 2;            /* 0..7 */\n"
"    int row_b = row_a + 8;            /* 8..15 */\n"
"    int col_g = (lane & 3) * 2;       /* 0,2,4,6 */\n"
"\n"
"    const half_raw *Qh = Q + (size_t)bh * S * V3_D;\n"
"    const half_raw *Kh = K + (size_t)bh * S * V3_D;\n"
"    const half_raw *Vh = V + (size_t)bh * S * V3_D;\n"
"          half_raw *Oh = O + (size_t)bh * S * V3_D;\n"
"\n"
"    /* ---- Load Q frag once (held across all K-tiles) ---- */\n"
"    uint32_t qfrag[V3_DK][4];\n"
"    int gqr_a = warp_q0 + row_a;\n"
"    int gqr_b = warp_q0 + row_b;\n"
"    int valid_a = (gqr_a < S);\n"
"    int valid_b = (gqr_b < S);\n"
"    for (int kk = 0; kk < V3_DK; kk++) {\n"
"        int kbase = kk * 16;\n"
"        const half_raw *qa_lo = Qh + (size_t)gqr_a * V3_D + kbase + col_g;\n"
"        const half_raw *qa_hi = qa_lo + 8;\n"
"        const half_raw *qb_lo = Qh + (size_t)gqr_b * V3_D + kbase + col_g;\n"
"        const half_raw *qb_hi = qb_lo + 8;\n"
"        qfrag[kk][0] = valid_a ? *(const uint32_t *)qa_lo : 0u;\n"
"        qfrag[kk][1] = valid_b ? *(const uint32_t *)qb_lo : 0u;\n"
"        qfrag[kk][2] = valid_a ? *(const uint32_t *)qa_hi : 0u;\n"
"        qfrag[kk][3] = valid_b ? *(const uint32_t *)qb_hi : 0u;\n"
"    }\n"
"\n"
"    /* ---- O accumulator ---- */\n"
"    float ofrag[V3_DN][4];\n"
"    for (int n = 0; n < V3_DN; n++) for (int i = 0; i < 4; i++) ofrag[n][i] = 0.0f;\n"
"\n"
"    /* ---- Per-row online-softmax stats (each thread owns 2 rows) ---- */\n"
"    float m_a = -1e30f, m_b = -1e30f, l_a = 0.0f, l_b = 0.0f;\n"
"\n"
"    /* ---- SMEM ---- */\n"
"    extern __shared__ half_raw smem_v3[];\n"
"    half_raw *sK  = smem_v3;                          /* [BC, V3_DP]  */\n"
"    half_raw *sVT = sK + V3_BC * V3_DP;                /* [D, V3_BCP] */\n"
"\n"
"    int n_tiles = (S + V3_BC - 1) / V3_BC;\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int kv0 = t * V3_BC;\n"
"\n"
"        /* Cooperative vectorized load of sK[BC,D] and sVT[D,BC] via uint4 (8 halves). */\n"
"        int total_u4 = (V3_BC * V3_D) / 8;     /* 512 uint4 per matrix */\n"
"        int row_u4   = V3_D / 8;               /* 16 uint4 per BC row  */\n"
"        for (int idx = threadIdx.x; idx < total_u4; idx += blockDim.x) {\n"
"            int j     = idx / row_u4;\n"
"            int dd_u4 = idx - j * row_u4;\n"
"            int dd    = dd_u4 * 8;\n"
"            int kv    = kv0 + j;\n"
"            uint4 kpack, vpack;\n"
"            if (kv < S) {\n"
"                kpack = *(const uint4 *)(Kh + (size_t)kv * V3_D + dd);\n"
"                vpack = *(const uint4 *)(Vh + (size_t)kv * V3_D + dd);\n"
"            } else {\n"
"                kpack.x = kpack.y = kpack.z = kpack.w = 0;\n"
"                vpack.x = vpack.y = vpack.z = vpack.w = 0;\n"
"            }\n"
"            *(uint4 *)(sK + j * V3_DP + dd) = kpack;\n"
"            half_raw vh[8];\n"
"            *(uint4 *)vh = vpack;\n"
"            #pragma unroll\n"
"            for (int i = 0; i < 8; i++) sVT[(dd + i) * V3_BCP + j] = vh[i];\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* ---- Q @ K^T -> S[16, BC=32] (warp-local) ---- */\n"
"        float sfrag[V3_BCN][4];\n"
"        for (int n = 0; n < V3_BCN; n++) for (int i = 0; i < 4; i++) sfrag[n][i] = 0.0f;\n"
"\n"
"        for (int kk = 0; kk < V3_DK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            for (int nn = 0; nn < V3_BCN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                int n_row = nbase + row_a;\n"
"                /* B[k,n] = K^T[k,n] = K[n,k]: thread t holds K[n_row, kbase+col_g..+1] (b0)\n"
"                 *                                       K[n_row, kbase+col_g+8..+9] (b1) */\n"
"                uint32_t b0 = *(const uint32_t *)(sK + n_row * V3_DP + kbase + col_g);\n"
"                uint32_t b1 = *(const uint32_t *)(sK + n_row * V3_DP + kbase + col_g + 8);\n"
"                uint32_t a0 = qfrag[kk][0], a1 = qfrag[kk][1], a2 = qfrag[kk][2], a3 = qfrag[kk][3];\n"
"                float c0 = sfrag[nn][0], c1 = sfrag[nn][1], c2 = sfrag[nn][2], c3 = sfrag[nn][3];\n"
"                asm(\"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\"\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                sfrag[nn][0] = c0; sfrag[nn][1] = c1; sfrag[nn][2] = c2; sfrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"\n"
"        /* ---- Apply scale + KV-OOB mask. sfrag layout per N-tile nn:\n"
"         *   c0 = (row_a, col=8*nn + col_g + 0)\n"
"         *   c1 = (row_a, col=8*nn + col_g + 1)\n"
"         *   c2 = (row_b, col=8*nn + col_g + 0)\n"
"         *   c3 = (row_b, col=8*nn + col_g + 1) ---- */\n"
"        for (int nn = 0; nn < V3_BCN; nn++) {\n"
"            int kv_c0 = kv0 + nn * 8 + col_g + 0;\n"
"            int kv_c1 = kv0 + nn * 8 + col_g + 1;\n"
"            sfrag[nn][0] = (kv_c0 < S) ? sfrag[nn][0] * scale : -1e30f;\n"
"            sfrag[nn][1] = (kv_c1 < S) ? sfrag[nn][1] * scale : -1e30f;\n"
"            sfrag[nn][2] = (kv_c0 < S) ? sfrag[nn][2] * scale : -1e30f;\n"
"            sfrag[nn][3] = (kv_c1 < S) ? sfrag[nn][3] * scale : -1e30f;\n"
"        }\n"
"\n"
"        /* ---- Row-wise max across the 4-thread row group (lane%4) ---- */\n"
"        float mx_a = -1e30f, mx_b = -1e30f;\n"
"        for (int nn = 0; nn < V3_BCN; nn++) {\n"
"            mx_a = fmaxf(mx_a, fmaxf(sfrag[nn][0], sfrag[nn][1]));\n"
"            mx_b = fmaxf(mx_b, fmaxf(sfrag[nn][2], sfrag[nn][3]));\n"
"        }\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 1));\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 2));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 1));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 2));\n"
"\n"
"        float m_new_a = fmaxf(m_a, mx_a);\n"
"        float m_new_b = fmaxf(m_b, mx_b);\n"
"        float alpha_a = expf(m_a - m_new_a);\n"
"        float alpha_b = expf(m_b - m_new_b);\n"
"        l_a *= alpha_a; l_b *= alpha_b;\n"
"        for (int n = 0; n < V3_DN; n++) {\n"
"            ofrag[n][0] *= alpha_a; ofrag[n][1] *= alpha_a;\n"
"            ofrag[n][2] *= alpha_b; ofrag[n][3] *= alpha_b;\n"
"        }\n"
"        m_a = m_new_a; m_b = m_new_b;\n"
"\n"
"        /* ---- exp(S - m) -> P (fp32 register frag), accumulate row-sum, pack to f16 pfrag.\n"
"         *   For mma A-frag of P@V K-iter kk (cols [16*kk, 16*kk+16) of P):\n"
"         *     a0 = (row_a, cols 16*kk + col_g + 0,1) -> sfrag[2*kk][0,1]\n"
"         *     a1 = (row_b, cols 16*kk + col_g + 0,1) -> sfrag[2*kk][2,3]\n"
"         *     a2 = (row_a, cols 16*kk + col_g + 8,9) -> sfrag[2*kk+1][0,1]\n"
"         *     a3 = (row_b, cols 16*kk + col_g + 8,9) -> sfrag[2*kk+1][2,3] ---- */\n"
"        uint32_t pfrag[V3_BCK][4];\n"
"        float row_sum_a = 0.0f, row_sum_b = 0.0f;\n"
"        for (int kk = 0; kk < V3_BCK; kk++) {\n"
"            float p0 = expf(sfrag[2*kk    ][0] - m_a);\n"
"            float p1 = expf(sfrag[2*kk    ][1] - m_a);\n"
"            float p2 = expf(sfrag[2*kk    ][2] - m_b);\n"
"            float p3 = expf(sfrag[2*kk    ][3] - m_b);\n"
"            float p4 = expf(sfrag[2*kk + 1][0] - m_a);\n"
"            float p5 = expf(sfrag[2*kk + 1][1] - m_a);\n"
"            float p6 = expf(sfrag[2*kk + 1][2] - m_b);\n"
"            float p7 = expf(sfrag[2*kk + 1][3] - m_b);\n"
"            row_sum_a += p0 + p1 + p4 + p5;\n"
"            row_sum_b += p2 + p3 + p6 + p7;\n"
"            pfrag[kk][0] = pack_h(p0, p1);\n"
"            pfrag[kk][1] = pack_h(p2, p3);\n"
"            pfrag[kk][2] = pack_h(p4, p5);\n"
"            pfrag[kk][3] = pack_h(p6, p7);\n"
"        }\n"
"        /* row_sum is per-thread partial; reduce across 4-thread row group. */\n"
"        row_sum_a += __shfl_xor_sync(0xffffffff, row_sum_a, 1);\n"
"        row_sum_a += __shfl_xor_sync(0xffffffff, row_sum_a, 2);\n"
"        row_sum_b += __shfl_xor_sync(0xffffffff, row_sum_b, 1);\n"
"        row_sum_b += __shfl_xor_sync(0xffffffff, row_sum_b, 2);\n"
"        l_a += row_sum_a;\n"
"        l_b += row_sum_b;\n"
"\n"
"        /* ---- P @ V via mma. V transposed in SMEM as sVT[d, bc].\n"
"         *   B-frag (col-major K-by-N=16x8) thread layout for P@V N-tile nn (D-cols [8*nn..8*nn+8)):\n"
"         *     b0_lo = V[bc=16*kk + col_g + 0, d=8*nn + row_a]\n"
"         *     b0_hi = V[bc=16*kk + col_g + 1, d=8*nn + row_a]\n"
"         *     b1_lo = V[bc=16*kk + col_g + 8, d=8*nn + row_a]\n"
"         *     b1_hi = V[bc=16*kk + col_g + 9, d=8*nn + row_a]\n"
"         *   In sVT[d * BC + bc] layout, b0 is two contiguous bytes -> single b32 load. ---- */\n"
"        for (int kk = 0; kk < V3_BCK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            for (int nn = 0; nn < V3_DN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                int v_d   = nbase + row_a;\n"
"                uint32_t b0 = *(const uint32_t *)(sVT + v_d * V3_BCP + kbase + col_g);\n"
"                uint32_t b1 = *(const uint32_t *)(sVT + v_d * V3_BCP + kbase + col_g + 8);\n"
"                uint32_t a0 = pfrag[kk][0], a1 = pfrag[kk][1], a2 = pfrag[kk][2], a3 = pfrag[kk][3];\n"
"                float c0 = ofrag[nn][0], c1 = ofrag[nn][1], c2 = ofrag[nn][2], c3 = ofrag[nn][3];\n"
"                asm(\"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\"\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                ofrag[nn][0] = c0; ofrag[nn][1] = c1; ofrag[nn][2] = c2; ofrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    /* ---- Epilogue: divide by l, store O. ofrag[nn][i] layout:\n"
"     *   ofrag[nn][0] = O[row_a, 8*nn + col_g + 0]\n"
"     *   ofrag[nn][1] = O[row_a, 8*nn + col_g + 1]\n"
"     *   ofrag[nn][2] = O[row_b, 8*nn + col_g + 0]\n"
"     *   ofrag[nn][3] = O[row_b, 8*nn + col_g + 1] ---- */\n"
"    float inv_a = (l_a > 0.0f) ? 1.0f / l_a : 0.0f;\n"
"    float inv_b = (l_b > 0.0f) ? 1.0f / l_b : 0.0f;\n"
"    for (int nn = 0; nn < V3_DN; nn++) {\n"
"        int d_col = nn * 8 + col_g;\n"
"        if (gqr_a < S) {\n"
"            Oh[(size_t)gqr_a * V3_D + d_col + 0] = f2h(ofrag[nn][0] * inv_a);\n"
"            Oh[(size_t)gqr_a * V3_D + d_col + 1] = f2h(ofrag[nn][1] * inv_a);\n"
"        }\n"
"        if (gqr_b < S) {\n"
"            Oh[(size_t)gqr_b * V3_D + d_col + 0] = f2h(ofrag[nn][2] * inv_b);\n"
"            Oh[(size_t)gqr_b * V3_D + d_col + 1] = f2h(ofrag[nn][3] * inv_b);\n"
"        }\n"
"    }\n"
"}\n";

/* v4 — cp.async double-buffered K/V load + sync transpose pass.
 *
 * Same compute structure as v3 (4 warps, BR=64, BC=32, D=128, register-resident
 * Q + O frags, online softmax over 4-thread row groups).
 *
 * SMEM layout (40 KB):
 *   sK [2][BC,D]    = 2 * 4096 halves = 16 KB   (cp.async target, double-buf)
 *   sVR[2][BC,D]    = 2 * 4096 halves = 16 KB   (cp.async target, double-buf, V row-major raw)
 *   sVT   [D,BC]    =     4096 halves =  8 KB   (transposed V for u32 b-frag loads)
 *
 * Pipeline: prologue issues tile 0; each iter issues tile (t+1) before compute,
 * then waits on tile t, transposes its sVR -> sVT, runs Q@K^T + P@V.
 */
static const char *k_fa_f16_v4_src =
"typedef unsigned short half_raw;\n"
"typedef unsigned int   uint32_t;\n"
"__device__ __forceinline__ float h2f(half_raw h) {\n"
"    float f; asm(\"cvt.f32.f16 %0, %1;\" : \"=f\"(f) : \"h\"(h)); return f;\n"
"}\n"
"__device__ __forceinline__ half_raw f2h(float f) {\n"
"    half_raw h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"__device__ __forceinline__ uint32_t pack_h(float lo, float hi) {\n"
"    uint32_t r;\n"
"    asm(\"{ .reg .b16 a, b; cvt.rn.f16.f32 a, %1; cvt.rn.f16.f32 b, %2;\\n\"\n"
"        \"  mov.b32 %0, {a, b}; }\" : \"=r\"(r) : \"f\"(lo), \"f\"(hi));\n"
"    return r;\n"
"}\n"
"\n"
"#define V4_D    128\n"
"#define V4_BR   64\n"
"#define V4_BC   32\n"
"#define V4_DK   (V4_D / 16)\n"
"#define V4_BCN  (V4_BC / 8)\n"
"#define V4_BCK  (V4_BC / 16)\n"
"#define V4_DN   (V4_D  / 8)\n"
"#define V4_DP   (V4_D + 8)\n"
"#define V4_BCP  (V4_BC + 8)\n"
"\n"
"extern \"C\" __global__\n"
"__launch_bounds__(128)\n"
"void fa_f16_v4(half_raw *O,\n"
"               const half_raw *Q,\n"
"               const half_raw *K,\n"
"               const half_raw *V,\n"
"               int S, int D_in, float scale) {\n"
"    int bh   = blockIdx.y;\n"
"    int wid  = threadIdx.x >> 5;\n"
"    int lane = threadIdx.x & 31;\n"
"    int warp_q0 = blockIdx.x * V4_BR + wid * 16;\n"
"\n"
"    int row_a = lane >> 2;\n"
"    int row_b = row_a + 8;\n"
"    int col_g = (lane & 3) * 2;\n"
"\n"
"    const half_raw *Qh = Q + (size_t)bh * S * V4_D;\n"
"    const half_raw *Kh = K + (size_t)bh * S * V4_D;\n"
"    const half_raw *Vh = V + (size_t)bh * S * V4_D;\n"
"          half_raw *Oh = O + (size_t)bh * S * V4_D;\n"
"\n"
"    /* ---- Q frag (held across all K-tiles) ---- */\n"
"    uint32_t qfrag[V4_DK][4];\n"
"    int gqr_a = warp_q0 + row_a;\n"
"    int gqr_b = warp_q0 + row_b;\n"
"    int valid_a = (gqr_a < S);\n"
"    int valid_b = (gqr_b < S);\n"
"    for (int kk = 0; kk < V4_DK; kk++) {\n"
"        int kbase = kk * 16;\n"
"        const half_raw *qa_lo = Qh + (size_t)gqr_a * V4_D + kbase + col_g;\n"
"        const half_raw *qa_hi = qa_lo + 8;\n"
"        const half_raw *qb_lo = Qh + (size_t)gqr_b * V4_D + kbase + col_g;\n"
"        const half_raw *qb_hi = qb_lo + 8;\n"
"        qfrag[kk][0] = valid_a ? *(const uint32_t *)qa_lo : 0u;\n"
"        qfrag[kk][1] = valid_b ? *(const uint32_t *)qb_lo : 0u;\n"
"        qfrag[kk][2] = valid_a ? *(const uint32_t *)qa_hi : 0u;\n"
"        qfrag[kk][3] = valid_b ? *(const uint32_t *)qb_hi : 0u;\n"
"    }\n"
"\n"
"    float ofrag[V4_DN][4];\n"
"    for (int n = 0; n < V4_DN; n++) for (int i = 0; i < 4; i++) ofrag[n][i] = 0.0f;\n"
"    float m_a = -1e30f, m_b = -1e30f, l_a = 0.0f, l_b = 0.0f;\n"
"\n"
"    /* ---- SMEM ---- */\n"
"    extern __shared__ half_raw smem_v4[];\n"
"    half_raw *sK0  = smem_v4;\n"
"    half_raw *sK1  = sK0  + V4_BC * V4_DP;\n"
"    half_raw *sVR0 = sK1  + V4_BC * V4_DP;\n"
"    half_raw *sVR1 = sVR0 + V4_BC * V4_DP;\n"
"    half_raw *sK_buf [2] = { sK0,  sK1  };\n"
"    half_raw *sVR_buf[2] = { sVR0, sVR1 };\n"
"\n"
"    int total_u4 = (V4_BC * V4_D) / 8;\n"
"    int row_u4   = V4_D / 8;\n"
"    int n_tiles  = (S + V4_BC - 1) / V4_BC;\n"
"\n"
"    /* ---- Prologue: cp.async issue tile 0 into buffer 0 ---- */\n"
"    {\n"
"        int kv0_ = 0;\n"
"        half_raw *dK_ = sK_buf [0];\n"
"        half_raw *dV_ = sVR_buf[0];\n"
"        for (int idx = threadIdx.x; idx < total_u4; idx += blockDim.x) {\n"
"            int j_ = idx / row_u4;\n"
"            int dd_ = (idx - j_ * row_u4) * 8;\n"
"            int kv_ = kv0_ + j_;\n"
"            unsigned dst_k = __cvta_generic_to_shared(dK_ + j_ * V4_DP + dd_);\n"
"            unsigned dst_v = __cvta_generic_to_shared(dV_ + j_ * V4_DP + dd_);\n"
"            const void *src_k = (const void *)(Kh + (size_t)kv_ * V4_D + dd_);\n"
"            const void *src_v = (const void *)(Vh + (size_t)kv_ * V4_D + dd_);\n"
"            int src_bytes = (kv_ < S) ? 16 : 0;\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_k), \"l\"(src_k), \"r\"(src_bytes));\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_v), \"l\"(src_v), \"r\"(src_bytes));\n"
"        }\n"
"    }\n"
"    asm volatile(\"cp.async.commit_group;\\n\" ::);\n"
"\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int cur = t & 1;\n"
"        int nxt = 1 - cur;\n"
"        int kv0 = t * V4_BC;\n"
"\n"
"        /* Issue next tile (if any) before waiting on current. */\n"
"        if (t + 1 < n_tiles) {\n"
"            int kv0_ = (t + 1) * V4_BC;\n"
"            half_raw *dK_ = sK_buf [nxt];\n"
"            half_raw *dV_ = sVR_buf[nxt];\n"
"            for (int idx = threadIdx.x; idx < total_u4; idx += blockDim.x) {\n"
"                int j_ = idx / row_u4;\n"
"                int dd_ = (idx - j_ * row_u4) * 8;\n"
"                int kv_ = kv0_ + j_;\n"
"                unsigned dst_k = __cvta_generic_to_shared(dK_ + j_ * V4_DP + dd_);\n"
"                unsigned dst_v = __cvta_generic_to_shared(dV_ + j_ * V4_DP + dd_);\n"
"                const void *src_k = (const void *)(Kh + (size_t)kv_ * V4_D + dd_);\n"
"                const void *src_v = (const void *)(Vh + (size_t)kv_ * V4_D + dd_);\n"
"                int src_bytes = (kv_ < S) ? 16 : 0;\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_k), \"l\"(src_k), \"r\"(src_bytes));\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_v), \"l\"(src_v), \"r\"(src_bytes));\n"
"            }\n"
"            asm volatile(\"cp.async.commit_group;\\n\" ::);\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\" ::);\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\" ::);\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        half_raw *sK = sK_buf[cur];\n"
"        half_raw *sV = sVR_buf[cur];\n"
"\n"
"        /* ---- Q @ K^T ---- */\n"
"        float sfrag[V4_BCN][4];\n"
"        for (int n = 0; n < V4_BCN; n++) for (int i = 0; i < 4; i++) sfrag[n][i] = 0.0f;\n"
"        /* ldmatrix.x2 lane addr: lanes 0..7 -> row=8*nn+(lane&7), col=kbase\n"
"           lanes 8..15 -> row=8*nn+(lane-8), col=kbase+8.  Result: {b0, b1}\n"
"           where thread t has b0=K[8nn+t/4, kbase+2*(t%4)..+1] (= mma B-frag .col view of K^T). */\n"
"        int ldm_row_off  = lane & 7;\n"
"        int ldm_col_xtra = (lane & 8) ? 8 : 0;\n"
"        for (int kk = 0; kk < V4_DK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            for (int nn = 0; nn < V4_BCN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                unsigned saddr = __cvta_generic_to_shared(\n"
"                    sK + (nbase + ldm_row_off) * V4_DP + kbase + ldm_col_xtra);\n"
"                uint32_t b0, b1;\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x2.shared.b16 {%0, %1}, [%2];\"\n"
"                    : \"=r\"(b0), \"=r\"(b1) : \"r\"(saddr));\n"
"                uint32_t a0 = qfrag[kk][0], a1 = qfrag[kk][1], a2 = qfrag[kk][2], a3 = qfrag[kk][3];\n"
"                float c0 = sfrag[nn][0], c1 = sfrag[nn][1], c2 = sfrag[nn][2], c3 = sfrag[nn][3];\n"
"                asm(\"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\"\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                sfrag[nn][0] = c0; sfrag[nn][1] = c1; sfrag[nn][2] = c2; sfrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"\n"
"        for (int nn = 0; nn < V4_BCN; nn++) {\n"
"            int kv_c0 = kv0 + nn * 8 + col_g + 0;\n"
"            int kv_c1 = kv0 + nn * 8 + col_g + 1;\n"
"            sfrag[nn][0] = (kv_c0 < S) ? sfrag[nn][0] * scale : -1e30f;\n"
"            sfrag[nn][1] = (kv_c1 < S) ? sfrag[nn][1] * scale : -1e30f;\n"
"            sfrag[nn][2] = (kv_c0 < S) ? sfrag[nn][2] * scale : -1e30f;\n"
"            sfrag[nn][3] = (kv_c1 < S) ? sfrag[nn][3] * scale : -1e30f;\n"
"        }\n"
"\n"
"        float mx_a = -1e30f, mx_b = -1e30f;\n"
"        for (int nn = 0; nn < V4_BCN; nn++) {\n"
"            mx_a = fmaxf(mx_a, fmaxf(sfrag[nn][0], sfrag[nn][1]));\n"
"            mx_b = fmaxf(mx_b, fmaxf(sfrag[nn][2], sfrag[nn][3]));\n"
"        }\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 1));\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 2));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 1));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 2));\n"
"\n"
"        float m_new_a = fmaxf(m_a, mx_a);\n"
"        float m_new_b = fmaxf(m_b, mx_b);\n"
"        float alpha_a = expf(m_a - m_new_a);\n"
"        float alpha_b = expf(m_b - m_new_b);\n"
"        l_a *= alpha_a; l_b *= alpha_b;\n"
"        for (int n = 0; n < V4_DN; n++) {\n"
"            ofrag[n][0] *= alpha_a; ofrag[n][1] *= alpha_a;\n"
"            ofrag[n][2] *= alpha_b; ofrag[n][3] *= alpha_b;\n"
"        }\n"
"        m_a = m_new_a; m_b = m_new_b;\n"
"\n"
"        uint32_t pfrag[V4_BCK][4];\n"
"        float row_sum_a = 0.0f, row_sum_b = 0.0f;\n"
"        for (int kk = 0; kk < V4_BCK; kk++) {\n"
"            float p0 = expf(sfrag[2*kk    ][0] - m_a);\n"
"            float p1 = expf(sfrag[2*kk    ][1] - m_a);\n"
"            float p2 = expf(sfrag[2*kk    ][2] - m_b);\n"
"            float p3 = expf(sfrag[2*kk    ][3] - m_b);\n"
"            float p4 = expf(sfrag[2*kk + 1][0] - m_a);\n"
"            float p5 = expf(sfrag[2*kk + 1][1] - m_a);\n"
"            float p6 = expf(sfrag[2*kk + 1][2] - m_b);\n"
"            float p7 = expf(sfrag[2*kk + 1][3] - m_b);\n"
"            row_sum_a += p0 + p1 + p4 + p5;\n"
"            row_sum_b += p2 + p3 + p6 + p7;\n"
"            pfrag[kk][0] = pack_h(p0, p1);\n"
"            pfrag[kk][1] = pack_h(p2, p3);\n"
"            pfrag[kk][2] = pack_h(p4, p5);\n"
"            pfrag[kk][3] = pack_h(p6, p7);\n"
"        }\n"
"        row_sum_a += __shfl_xor_sync(0xffffffff, row_sum_a, 1);\n"
"        row_sum_a += __shfl_xor_sync(0xffffffff, row_sum_a, 2);\n"
"        row_sum_b += __shfl_xor_sync(0xffffffff, row_sum_b, 1);\n"
"        row_sum_b += __shfl_xor_sync(0xffffffff, row_sum_b, 2);\n"
"        l_a += row_sum_a;\n"
"        l_b += row_sum_b;\n"
"\n"
"        /* ldmatrix.x2.trans on sV[bc, d] row-major.\n"
"           Lanes 0..7 -> ptr to V[bc=kbase+(lane&7),    d=8*nn..+7]\n"
"           Lanes 8..15-> ptr to V[bc=kbase+(lane&7)+8,  d=8*nn..+7]\n"
"           After .trans, thread t holds {b0=V[kbase+2*(t%4)..+1, 8nn+t/4],\n"
"                                         b1=V[kbase+2*(t%4)+8..+9, 8nn+t/4]}.\n"
"           Source row stride = V4_D = 128 halves = 256 B (16-byte aligned ✓). */\n"
"        for (int kk = 0; kk < V4_BCK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            int bc_row = kbase + ldm_row_off + ((lane & 8) ? 8 : 0);\n"
"            for (int nn = 0; nn < V4_DN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                unsigned saddr = __cvta_generic_to_shared(\n"
"                    sV + bc_row * V4_DP + nbase);\n"
"                uint32_t b0, b1;\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x2.trans.shared.b16 {%0, %1}, [%2];\"\n"
"                    : \"=r\"(b0), \"=r\"(b1) : \"r\"(saddr));\n"
"                uint32_t a0 = pfrag[kk][0], a1 = pfrag[kk][1], a2 = pfrag[kk][2], a3 = pfrag[kk][3];\n"
"                float c0 = ofrag[nn][0], c1 = ofrag[nn][1], c2 = ofrag[nn][2], c3 = ofrag[nn][3];\n"
"                asm(\"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\"\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                ofrag[nn][0] = c0; ofrag[nn][1] = c1; ofrag[nn][2] = c2; ofrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    float inv_a = (l_a > 0.0f) ? 1.0f / l_a : 0.0f;\n"
"    float inv_b = (l_b > 0.0f) ? 1.0f / l_b : 0.0f;\n"
"    for (int nn = 0; nn < V4_DN; nn++) {\n"
"        int d_col = nn * 8 + col_g;\n"
"        if (gqr_a < S) {\n"
"            Oh[(size_t)gqr_a * V4_D + d_col + 0] = f2h(ofrag[nn][0] * inv_a);\n"
"            Oh[(size_t)gqr_a * V4_D + d_col + 1] = f2h(ofrag[nn][1] * inv_a);\n"
"        }\n"
"        if (gqr_b < S) {\n"
"            Oh[(size_t)gqr_b * V4_D + d_col + 0] = f2h(ofrag[nn][2] * inv_b);\n"
"            Oh[(size_t)gqr_b * V4_D + d_col + 1] = f2h(ofrag[nn][3] * inv_b);\n"
"        }\n"
"    }\n"
"}\n";

/* ref: naive non-tiled, all S scores in SMEM. Correctness baseline. */
static const char *k_fa_f16_ref_src =
"typedef unsigned short half_raw;\n"
"__device__ __forceinline__ float h2f(half_raw h) {\n"
"    float f; asm(\"cvt.f32.f16 %0, %1;\" : \"=f\"(f) : \"h\"(h)); return f;\n"
"}\n"
"__device__ __forceinline__ half_raw f2h(float f) {\n"
"    half_raw h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"\n"
"extern \"C\" __global__\n"
"void fa_f16_ref(half_raw *O,\n"
"                const half_raw *Q,\n"
"                const half_raw *K,\n"
"                const half_raw *V,\n"
"                int S, int D, float scale) {\n"
"    int qi  = blockIdx.x;\n"
"    int bh  = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (tid >= D) return;\n"
"\n"
"    const half_raw *Qh = Q + (size_t)bh * S * D + (size_t)qi * D;\n"
"    const half_raw *Kh = K + (size_t)bh * S * D;\n"
"    const half_raw *Vh = V + (size_t)bh * S * D;\n"
"          half_raw *Oh = O + (size_t)bh * S * D + (size_t)qi * D;\n"
"\n"
"    float q_d = h2f(Qh[tid]);\n"
"    extern __shared__ float smem[];\n"
"    float *scores = smem;\n"
"\n"
"    for (int kv = 0; kv < S; kv++) {\n"
"        float partial = q_d * h2f(Kh[(size_t)kv * D + tid]);\n"
"        for (int o = 16; o > 0; o >>= 1)\n"
"            partial += __shfl_xor_sync(0xffffffff, partial, o);\n"
"        __shared__ float warp_sums[4];\n"
"        int wid = tid >> 5, lane = tid & 31;\n"
"        if (lane == 0) warp_sums[wid] = partial;\n"
"        __syncthreads();\n"
"        float s = 0.0f;\n"
"        int n_warps = blockDim.x >> 5;\n"
"        if (tid < n_warps) s = warp_sums[tid];\n"
"        for (int o = n_warps >> 1; o > 0; o >>= 1)\n"
"            s += __shfl_xor_sync(0xffffffff, s, o);\n"
"        if (tid == 0) scores[kv] = s * scale;\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    __shared__ float mx_sh, sum_sh;\n"
"    if (tid == 0) {\n"
"        float mx = -1e30f;\n"
"        for (int j = 0; j < S; j++) if (scores[j] > mx) mx = scores[j];\n"
"        float sum = 0.0f;\n"
"        for (int j = 0; j < S; j++) { scores[j] = expf(scores[j] - mx); sum += scores[j]; }\n"
"        mx_sh = mx; sum_sh = sum;\n"
"    }\n"
"    __syncthreads();\n"
"    float inv = 1.0f / sum_sh;\n"
"\n"
"    float acc = 0.0f;\n"
"    for (int j = 0; j < S; j++)\n"
"        acc += scores[j] * h2f(Vh[(size_t)j * D + tid]);\n"
"    Oh[tid] = f2h(acc * inv);\n"
"}\n";

#endif
