SWIN_EXTRA_FLAGS = -DSWIN_CUDA
SWIN_EXTRA_SRC = ../cuew.c
SWIN_EXTRA_LIBS = -ldl
SWIN_EXTRA_DEPS = ../gemm/cuda_linear_f32.h ../gemm/cuda_gemm_f32_kernels.h ../cuew.h ../cuda_runner_common.h
include ../../cpu/rmbg/Makefile
