/* SPDX-License-Identifier: MIT
 * Copyright 2026 - Present, Light Transport Entertainment Inc.
 *
 * qtts_cuda_kernels.h - NVRTC kernel source for the Qwen3-TTS CUDA backend.
 * Activations are F32; talker / code-predictor weights stay BF16 (unpacked in
 * registers), codec weights are F32. Compiled without fast-math so results track
 * the CPU reference.
 */
#ifndef QTTS_CUDA_KERNELS_H
#define QTTS_CUDA_KERNELS_H

static const char *qtts_cuda_kernel_src =
"#define INFINITY __int_as_float(0x7f800000)\n"
"typedef unsigned short u16;\n"
"typedef unsigned int u32;\n"
"__device__ __forceinline__ float bf(u16 v) { return __uint_as_float(((u32)v) << 16); }\n"
"__device__ __forceinline__ float warp_sum(float v) {\n"
"  for (int o = 16; o > 0; o >>= 1) v += __shfl_xor_sync(0xffffffffu, v, o);\n"
"  return v;\n"
"}\n"
"__device__ __forceinline__ float block_sum(float v, float *sh) {\n"
"  int lane = threadIdx.x & 31, w = threadIdx.x >> 5, nw = (blockDim.x + 31) >> 5;\n"
"  v = warp_sum(v);\n"
"  if (lane == 0) sh[w] = v;\n"
"  __syncthreads();\n"
"  float t = 0.f;\n"
"  for (int i = 0; i < nw; ++i) t += sh[i];\n"
"  __syncthreads();\n"
"  return t;\n"
"}\n"
"\n"
"/* y[m][n] (+)= sum_k x[m][k] * W[n][k] (+ bias[n]); one warp per output row n, M <= 4 */\n"
"extern \"C\" __global__ void gemv_bf16(const u16 *__restrict__ W, const float *__restrict__ x,\n"
"    float *__restrict__ y, const u16 *__restrict__ bias, int N, int K, int M, int accum) {\n"
"  int n = (blockIdx.x * blockDim.x + threadIdx.x) >> 5, lane = threadIdx.x & 31;\n"
"  if (n >= N) return;\n"
"  const uint4 *wr = (const uint4 *)(W + (size_t)n * K);\n"
"  float s0 = 0.f, s1 = 0.f, s2 = 0.f, s3 = 0.f;\n"
"  int K8 = K >> 3;\n"
"  for (int k8 = lane; k8 < K8; k8 += 32) {\n"
"    uint4 w = wr[k8];\n"
"    float wf[8];\n"
"    wf[0] = __uint_as_float(w.x << 16); wf[1] = __uint_as_float(w.x & 0xffff0000u);\n"
"    wf[2] = __uint_as_float(w.y << 16); wf[3] = __uint_as_float(w.y & 0xffff0000u);\n"
"    wf[4] = __uint_as_float(w.z << 16); wf[5] = __uint_as_float(w.z & 0xffff0000u);\n"
"    wf[6] = __uint_as_float(w.w << 16); wf[7] = __uint_as_float(w.w & 0xffff0000u);\n"
"    const float4 *xp = (const float4 *)(x + (size_t)k8 * 8);\n"
"    float4 a = xp[0], b = xp[1];\n"
"    s0 += wf[0]*a.x + wf[1]*a.y + wf[2]*a.z + wf[3]*a.w + wf[4]*b.x + wf[5]*b.y + wf[6]*b.z + wf[7]*b.w;\n"
"    if (M > 1) { xp = (const float4 *)(x + (size_t)K + (size_t)k8 * 8); a = xp[0]; b = xp[1];\n"
"      s1 += wf[0]*a.x + wf[1]*a.y + wf[2]*a.z + wf[3]*a.w + wf[4]*b.x + wf[5]*b.y + wf[6]*b.z + wf[7]*b.w; }\n"
"    if (M > 2) { xp = (const float4 *)(x + 2 * (size_t)K + (size_t)k8 * 8); a = xp[0]; b = xp[1];\n"
"      s2 += wf[0]*a.x + wf[1]*a.y + wf[2]*a.z + wf[3]*a.w + wf[4]*b.x + wf[5]*b.y + wf[6]*b.z + wf[7]*b.w; }\n"
"    if (M > 3) { xp = (const float4 *)(x + 3 * (size_t)K + (size_t)k8 * 8); a = xp[0]; b = xp[1];\n"
"      s3 += wf[0]*a.x + wf[1]*a.y + wf[2]*a.z + wf[3]*a.w + wf[4]*b.x + wf[5]*b.y + wf[6]*b.z + wf[7]*b.w; }\n"
"  }\n"
"  s0 = warp_sum(s0); s1 = warp_sum(s1); s2 = warp_sum(s2); s3 = warp_sum(s3);\n"
"  if (lane == 0) {\n"
"    float b0 = bias ? bf(bias[n]) : 0.f;\n"
"    float s[4] = {s0, s1, s2, s3};\n"
"    for (int m = 0; m < M; ++m) {\n"
"      float v = s[m] + b0;\n"
"      float *o = y + (size_t)m * N + n;\n"
"      *o = accum ? *o + v : v;\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"/* Tiled GEMM with an implicit causal-conv gather on A:\n"
" *   C[t][n] (+)= bias[n] + sum_kk A(t, kk) W[n][kk],  kk = j*Cin + ci,\n"
" *   A(t, kk) = X[(t + j*dil - pad) * Cin + ci] (0 outside [0, T)).  Linear: ks=1, pad=0.\n"
" * 64x64 tile, BK 16, 256 threads x 4x4 outputs. WBF16 selects BF16 or F32 weights. */\n"
"template <int WBF16>\n"
"__device__ void gemm_body(const float *__restrict__ X, int T, int Cin, int ks, int dil, int pad,\n"
"    const void *__restrict__ Wv, int N, const float *__restrict__ bias, const u16 *__restrict__ bias16,\n"
"    float *__restrict__ C, int ldc, int accum) {\n"
"  __shared__ float As[16][68];\n"
"  __shared__ float Bs[16][68];\n"
"  int K = ks * Cin;\n"
"  int tx = threadIdx.x & 15, ty = threadIdx.x >> 4;\n"
"  int m0 = blockIdx.y * 64, n0 = blockIdx.x * 64;\n"
"  float acc[4][4];\n"
"  for (int i = 0; i < 4; ++i) for (int j = 0; j < 4; ++j) acc[i][j] = 0.f;\n"
"  for (int k0 = 0; k0 < K; k0 += 16) {\n"
"    for (int i = threadIdx.x; i < 1024; i += 256) {\n"
"      int r = i >> 4, kk = i & 15, t = m0 + r, k = k0 + kk;\n"
"      float v = 0.f;\n"
"      if (t < T && k < K) {\n"
"        int j = ks == 1 ? 0 : k / Cin, ci = k - j * Cin, src = t + j * dil - pad;\n"
"        if (src >= 0 && src < T) v = X[(size_t)src * Cin + ci];\n"
"      }\n"
"      As[kk][r] = v;\n"
"      int n = n0 + r;\n"
"      float w = 0.f;\n"
"      if (n < N && k < K) w = WBF16 ? bf(((const u16 *)Wv)[(size_t)n * K + k]) : ((const float *)Wv)[(size_t)n * K + k];\n"
"      Bs[kk][r] = w;\n"
"    }\n"
"    __syncthreads();\n"
"#pragma unroll\n"
"    for (int kk = 0; kk < 16; ++kk) {\n"
"      float a[4], b[4];\n"
"#pragma unroll\n"
"      for (int i = 0; i < 4; ++i) { a[i] = As[kk][ty * 4 + i]; b[i] = Bs[kk][tx * 4 + i]; }\n"
"#pragma unroll\n"
"      for (int i = 0; i < 4; ++i)\n"
"#pragma unroll\n"
"        for (int j = 0; j < 4; ++j) acc[i][j] += a[i] * b[j];\n"
"    }\n"
"    __syncthreads();\n"
"  }\n"
"  for (int i = 0; i < 4; ++i) {\n"
"    int t = m0 + ty * 4 + i;\n"
"    if (t >= T) continue;\n"
"    for (int j = 0; j < 4; ++j) {\n"
"      int n = n0 + tx * 4 + j;\n"
"      if (n >= N) continue;\n"
"      float v = acc[i][j] + (bias ? bias[n] : 0.f) + (bias16 ? bf(bias16[n]) : 0.f);\n"
"      float *o = C + (size_t)t * ldc + n;\n"
"      *o = accum ? *o + v : v;\n"
"    }\n"
"  }\n"
"}\n"
"extern \"C\" __global__ void gemm_f32w(const float *X, int T, int Cin, int ks, int dil, int pad,\n"
"    const float *W, int N, const float *bias, float *C, int ldc, int accum) {\n"
"  gemm_body<0>(X, T, Cin, ks, dil, pad, W, N, bias, 0, C, ldc, accum);\n"
"}\n"
"extern \"C\" __global__ void gemm_bf16w(const float *X, int T, int K, const u16 *W, int N,\n"
"    const u16 *bias16, float *C, int ldc, int accum) {\n"
"  gemm_body<1>(X, T, K, 1, 1, 0, W, N, 0, bias16, C, ldc, accum);\n"
"}\n"
"\n"
"/* row-wise RMSNorm; weights BF16 (w16) or F32 (w32) */\n"
"extern \"C\" __global__ void rmsnorm(const float *x, float *y, const u16 *w16, const float *w32, int n, float eps) {\n"
"  __shared__ float sh[32];\n"
"  const float *xr = x + (size_t)blockIdx.x * n;\n"
"  float *yr = y + (size_t)blockIdx.x * n;\n"
"  float s = 0.f;\n"
"  for (int i = threadIdx.x; i < n; i += blockDim.x) s += xr[i] * xr[i];\n"
"  s = block_sum(s, sh);\n"
"  float r = rsqrtf(s / n + eps);\n"
"  for (int i = threadIdx.x; i < n; i += blockDim.x) yr[i] = xr[i] * r * (w16 ? bf(w16[i]) : (w32 ? w32[i] : 1.f));\n"
"}\n"
"\n"
"extern \"C\" __global__ void layernorm(const float *x, float *y, const float *w, const float *b, int n, float eps) {\n"
"  __shared__ float sh[32];\n"
"  const float *xr = x + (size_t)blockIdx.x * n;\n"
"  float *yr = y + (size_t)blockIdx.x * n;\n"
"  float s = 0.f;\n"
"  for (int i = threadIdx.x; i < n; i += blockDim.x) s += xr[i];\n"
"  float mu = block_sum(s, sh) / n;\n"
"  float v = 0.f;\n"
"  for (int i = threadIdx.x; i < n; i += blockDim.x) { float d = xr[i] - mu; v += d * d; }\n"
"  float r = rsqrtf(block_sum(v, sh) / n + eps);\n"
"  for (int i = threadIdx.x; i < n; i += blockDim.x) yr[i] = (xr[i] - mu) * r * w[i] + b[i];\n"
"}\n"
"\n"
"/* Per-head RMSNorm (optional, BF16 weights) + NeoX RoPE on the q and k parts of rows laid\n"
" * out [row][stride]: q heads at offset 0, k heads at offset qoff_k. grid (M, nh + nkv), warp. */\n"
"extern \"C\" __global__ void qk_norm_rope(float *qkv, int stride, int koff, int nh, int nkv, int hd,\n"
"    const u16 *qn, const u16 *kn, float eps, int pos0, float theta) {\n"
"  int row = blockIdx.x, hh = blockIdx.y, lane = threadIdx.x;\n"
"  float *v = qkv + (size_t)row * stride + (hh < nh ? hh * hd : koff + (hh - nh) * hd);\n"
"  const u16 *w = hh < nh ? qn : kn;\n"
"  if (w) {\n"
"    float s = 0.f;\n"
"    for (int e = lane; e < hd; e += 32) s += v[e] * v[e];\n"
"    s = warp_sum(s);\n"
"    float r = rsqrtf(s / hd + eps);\n"
"    for (int e = lane; e < hd; e += 32) v[e] = v[e] * r * bf(w[e]);\n"
"    __syncwarp();\n"
"  }\n"
"  int half = hd / 2, pos = pos0 + row;\n"
"  for (int e = lane; e < half; e += 32) {\n"
"    float inv = 1.0f / powf(theta, (float)(2 * e) / (float)hd);\n"
"    float ang = (float)pos * inv, cs = cosf(ang), sn = sinf(ang);\n"
"    float a = v[e], b = v[e + half];\n"
"    v[e] = a * cs - b * sn;\n"
"    v[e + half] = b * cs + a * sn;\n"
"  }\n"
"}\n"
"\n"
"/* copy k / v parts of rows [M][stride] into caches [pos][kd] at pos0 */\n"
"extern \"C\" __global__ void kv_store(const float *qkv, int stride, int koff, int voff, int kd,\n"
"    float *kc, float *vc, int pos0, int M) {\n"
"  size_t i = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (i >= (size_t)M * kd) return;\n"
"  int r = (int)(i / kd), c = (int)(i % kd);\n"
"  kc[(size_t)(pos0 + r) * kd + c] = qkv[(size_t)r * stride + koff + c];\n"
"  vc[(size_t)(pos0 + r) * kd + c] = qkv[(size_t)r * stride + voff + c];\n"
"}\n"
"\n"
"/* causal attention, one block (4 warps) per (query row, head); warps split keys with an\n"
" * online softmax, merged through shared memory. q rows have stride qstride. hd <= 128. */\n"
"extern \"C\" __global__ void attention(const float *q, int qstride, const float *kc, const float *vc,\n"
"    float *out, int pos0, int nh, int nkv, int hd, int window, float scale) {\n"
"  __shared__ float sm[4], sl[4], sacc[4][128];\n"
"  int i = blockIdx.x, h = blockIdx.y, w = threadIdx.x >> 5, lane = threadIdx.x & 31;\n"
"  int qp = pos0 + i, kv0 = (window > 0 && qp - window + 1 > 0) ? qp - window + 1 : 0;\n"
"  int kvh = h / (nh / nkv), kd = nkv * hd, per = hd / 32;\n"
"  float qv[4], acc[4];\n"
"  for (int e = 0; e < 4; ++e) { qv[e] = e < per ? q[(size_t)i * qstride + h * hd + lane + 32 * e] : 0.f; acc[e] = 0.f; }\n"
"  float m = -INFINITY, l = 0.f;\n"
"  for (int j = kv0 + w; j <= qp; j += 4) {\n"
"    const float *kr = kc + (size_t)j * kd + kvh * hd, *vr = vc + (size_t)j * kd + kvh * hd;\n"
"    float d = 0.f;\n"
"    for (int e = 0; e < per; ++e) d += qv[e] * kr[lane + 32 * e];\n"
"    d = warp_sum(d) * scale;\n"
"    float mn = fmaxf(m, d), c = expf(m - mn), p = expf(d - mn);\n"
"    l = l * c + p;\n"
"    for (int e = 0; e < per; ++e) acc[e] = acc[e] * c + p * vr[lane + 32 * e];\n"
"    m = mn;\n"
"  }\n"
"  if (lane == 0) { sm[w] = m; sl[w] = l; }\n"
"  for (int e = 0; e < per; ++e) sacc[w][lane + 32 * e] = acc[e];\n"
"  __syncthreads();\n"
"  if (w == 0) {\n"
"    float M = fmaxf(fmaxf(sm[0], sm[1]), fmaxf(sm[2], sm[3])), L = 0.f;\n"
"    float c[4];\n"
"    for (int k = 0; k < 4; ++k) { c[k] = sm[k] == -INFINITY ? 0.f : expf(sm[k] - M); L += sl[k] * c[k]; }\n"
"    for (int e = 0; e < per; ++e) {\n"
"      float s = 0.f;\n"
"      for (int k = 0; k < 4; ++k) s += sacc[k][lane + 32 * e] * c[k];\n"
"      out[((size_t)i * nh + h) * hd + lane + 32 * e] = s / L;\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"/* g[r][i] = silu(gu[r][i]) * gu[r][I + i] for rows of [gate | up] (width 2I) -> out[r][i] */\n"
"extern \"C\" __global__ void silu_mul(const float *gu, float *out, int I, int M) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= (size_t)M * I) return;\n"
"  int r = (int)(k / I), i = (int)(k % I);\n"
"  float g = gu[(size_t)r * 2 * I + i], u = gu[(size_t)r * 2 * I + I + i];\n"
"  out[k] = g / (1.f + expf(-g)) * u;\n"
"}\n"
"\n"
"/* x[t][c] += (s ? s[c] : 1) * y[t][c] */\n"
"extern \"C\" __global__ void add_scaled(float *x, const float *y, const float *s, int C, size_t n) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= n) return;\n"
"  x[k] += (s ? s[k % C] : 1.f) * y[k];\n"
"}\n"
"\n"
"/* dst[n] = (accum ? dst : 0) + table[row][n] (BF16 embedding row) */\n"
"extern \"C\" __global__ void embed_add(const u16 *table, int row, float *dst, int n, int accum) {\n"
"  int k = blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= n) return;\n"
"  float v = bf(table[(size_t)row * n + k]);\n"
"  dst[k] = accum ? dst[k] + v : v;\n"
"}\n"
"\n"
"extern \"C\" __global__ void gelu_bias(float *x, const float *b, int C, size_t n) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= n) return;\n"
"  float v = x[k] + b[k % C];\n"
"  x[k] = 0.5f * v * (1.f + erff(v * 0.70710678118654752f));\n"
"}\n"
"\n"
"/* SnakeBeta with precomputed a = exp(alpha), ib = 1 / (exp(beta) + 1e-9) */\n"
"extern \"C\" __global__ void snake(float *x, const float *a, const float *ib, int C, size_t n) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= n) return;\n"
"  int c = (int)(k % C);\n"
"  float s = sinf(x[k] * a[c]);\n"
"  x[k] += ib[c] * s * s;\n"
"}\n"
"\n"
"/* same, out of place */\n"
"extern \"C\" __global__ void snake_to(const float *x, float *y, const float *a, const float *ib, int C, size_t n) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= n) return;\n"
"  int c = (int)(k % C);\n"
"  float s = sinf(x[k] * a[c]);\n"
"  y[k] = x[k] + ib[c] * s * s;\n"
"}\n"
"\n"
"/* depthwise causal conv: y[t][c] = b[c] + sum_j w[c][j] x[t + j - (k-1)][c] */\n"
"extern \"C\" __global__ void dwconv(const float *x, float *y, const float *w, const float *b, int T, int C, int ks) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k >= (size_t)T * C) return;\n"
"  int t = (int)(k / C), c = (int)(k % C);\n"
"  float s = b ? b[c] : 0.f;\n"
"  for (int j = 0; j < ks; ++j) { int ti = t + j - (ks - 1); if (ti >= 0) s += w[c * ks + j] * x[(size_t)ti * C + c]; }\n"
"  y[k] = s;\n"
"}\n"
"\n"
"/* transposed-conv overlap-add: z[t][j*Cout + c] -> y[to][c], to = t*s + j, keep to < T*s */\n"
"extern \"C\" __global__ void convt_ola(const float *z, float *y, const float *b, int T, int Cout, int ks, int st) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  size_t To = (size_t)T * st;\n"
"  if (k >= To * Cout) return;\n"
"  int to = (int)(k / Cout), c = (int)(k % Cout);\n"
"  float s = b ? b[c] : 0.f;\n"
"  for (int j = to % st; j < ks; j += st) { int t = (to - j) / st; if (t >= 0 && t < T) s += z[((size_t)t * ks + j) * Cout + c]; }\n"
"  y[k] = s;\n"
"}\n"
"\n"
"extern \"C\" __global__ void clamp1(float *x, size_t n) {\n"
"  size_t k = (size_t)blockIdx.x * blockDim.x + threadIdx.x;\n"
"  if (k < n) x[k] = fminf(1.f, fmaxf(-1.f, x[k]));\n"
"}\n";

#endif /* QTTS_CUDA_KERNELS_H */
