#!/usr/bin/env python3
"""Generate the q38p prefill GEMM microkernels (int16 SDOT .d, A64FX SVE-512).

q38p_mk_r{R}t{T}(W, A, S, O, ngroups, steps)
  W  int16 weight tile, L1-resident: [steps][R vectors][8 rows][4 k]   (R*64 B per step)
  A  int16 activations, per token group: [steps][T][4]                 (T*8 B per step)
     groups follow each other (A += steps*T*8 per group)
  S  double activation block scales, [group][T]
  O  double accumulators, [group][R][T][8 lanes]; O += S_t * (int64 dot over the tile)
  Each call covers one K block (steps*4 columns) of R*8 rows for ngroups*T tokens.
The int64 accumulators are exact (|w| <= 11520, |a| <= 32767, K block <= 2048).
"""
import sys

def kernel(R, T, ilv=True, U=1, name=None, pf=0):
    name = name or f"q38p_mk_r{R}t{T}"
    acc = list(range(R * T))
    wr = list(range(R * T, R * T + R))
    ar = list(range(R * T + R, R * T + R + T))
    assert R * T + R + T <= 32
    o = []
    a = o.append
    a(f"    .globl {name}\n    .type {name},%function\n    .p2align 6\n{name}:")
    a("    stp d8, d9, [sp, #-64]!\n    stp d10, d11, [sp, #16]\n    stp d12, d13, [sp, #32]\n    stp d14, d15, [sp, #48]")
    a("    ptrue p0.b")
    # x0 W, x1 A, x2 S, x3 O, x4 ngroups, x5 steps
    a("1:")
    a("    mov x6, x0\n    mov x7, x5")
    for r in acc: a(f"    dup z{r}.d, #0")
    # prologue loads for step 0
    for r in range(R): a(f"    ld1h z{wr[r]}.h, p0/z, [x6, #{r}, mul vl]")
    for t in range(T): a(f"    ld1rd z{ar[t]}.d, p0/z, [x1, #{t*8}]")
    a("    addvl x6, x6, #%d\n    add x1, x1, #%d" % (R, T * 8))
    a("    subs x7, x7, #1\n    b.eq 3f")
    a("2:")
    for u in range(U):
        last = u == U - 1
        for r in range(R):
            for t in range(T):
                a(f"    sdot z{acc[r*T+t]}.d, z{wr[r]}.h, z{ar[t]}.h")
                if ilv:
                    if t == T - 1: a(f"    ld1h z{wr[r]}.h, p0/z, [x6, #{r}, mul vl]")
                    if r == R - 1: a(f"    ld1rd z{ar[t]}.d, p0/z, [x1, #{t*8}]")
        if not ilv:
            for r in range(R): a(f"    ld1h z{wr[r]}.h, p0/z, [x6, #{r}, mul vl]")
            for t in range(T): a(f"    ld1rd z{ar[t]}.d, p0/z, [x1, #{t*8}]")
        if pf:
            a(f"    prfm pldl1keep, [x6, #{pf}]")
            if R * 64 > 256: a(f"    prfm pldl1keep, [x6, #{pf + 256}]")
        a("    addvl x6, x6, #%d\n    add x1, x1, #%d" % (R, T * 8))
    a("    subs x7, x7, #%d\n    b.gt 2b" % U)
    a("3:")
    for r in range(R):
        for t in range(T):
            a(f"    sdot z{acc[r*T+t]}.d, z{wr[r]}.h, z{ar[t]}.h")
    # epilogue: O[r][t] += cvt(acc) * S[t]; sources are free now
    for t in range(T): a(f"    ld1rd z{ar[t]}.d, p0/z, [x2, #{t*8}]")
    for r in range(R):
        for t in range(T):
            i = r * T + t
            a(f"    scvtf z{acc[i]}.d, p0/m, z{acc[i]}.d")
    for r in range(R):
        for t in range(T):
            i = r * T + t
            w = wr[r]
            a(f"    ld1d z{w}.d, p0/z, [x3, #{t}, mul vl]")
            a(f"    fmla z{w}.d, p0/m, z{acc[i]}.d, z{ar[t]}.d")
            a(f"    st1d z{w}.d, p0, [x3, #{t}, mul vl]")
        a(f"    addvl x3, x3, #{T}")
    a("    add x2, x2, #%d" % (T * 8))
    a("    subs x4, x4, #1\n    b.gt 1b")
    a("    ldp d10, d11, [sp, #16]\n    ldp d12, d13, [sp, #32]\n    ldp d14, d15, [sp, #48]\n    ldp d8, d9, [sp], #64\n    ret")
    a(f"    .size {name}, .-{name}")
    return "\n".join(o) + "\n"

if __name__ == "__main__":
    cfgs = [(4, 5), (5, 4), (3, 7), (4, 4)]
    out = ["/* generated by gen_pf.py; do not edit */", "    .text"]
    for R, T in cfgs: out.append(kernel(R, T))
    # probe variants: L1 prefetch distance of the weight stream (bytes)
    for R, T in [(4, 5), (3, 7)]:
        for pf in (0, 1024, 2048, 4096):
            out.append(kernel(R, T, True, 1, f"q38p_mkp_r{R}t{T}_p{pf}", pf))
    open(sys.argv[1] if len(sys.argv) > 1 else "q38p_kern.S", "w").write("\n".join(out))
