/* Experimental reverse-64 BF16 MMA attention, derived from
 * cuda/cuda_fp8_mma_kernels.h flash_attn_bf16_xq. Standalone to avoid
 * changing other backends. PV loads cover all four 16-key fragments. */
#ifndef QIMG21_MMA64_KERNELS_H
#define QIMG21_MMA64_KERNELS_H
static const char *q21_mma64_src =
"#ifndef Q21_FLASH_SOFTMAX\n#define Q21_FLASH_SOFTMAX 0\n#endif\n"
"#ifndef Q21_FORWARD_KEYS\n#define Q21_FORWARD_KEYS 0\n#endif\n"
"#ifndef Q21_BKV\n#define Q21_BKV 64\n#endif\n"
"#ifndef Q21_SINGLE_BUFFER\n#define Q21_SINGLE_BUFFER 0\n#endif\n"
"#ifndef Q21_PRE_SCALE_SCORES\n#define Q21_PRE_SCALE_SCORES 0\n#endif\n"
"extern \"C\" {\n"
"#define FABF16_BKV Q21_BKV\n"
"#define FABF16_M 16\n"
"#define FABF16_NWARPS 4\n"
"#define FABF16_HDP 136\n"
"#define FABF16_NI (FABF16_BKV / 8)\n"
"#define FABF16_PV_KC (FABF16_BKV / 16)\n"
"__device__ unsigned short f32_to_bf16_bits(float x) {\n"
" unsigned u=__float_as_uint(x);return (unsigned short)((u+0x7fff+((u>>16)&1))>>16);\n"
"}\n"
"__global__ void q21_flash_reverse64(\n"
"    float *__restrict__ out,\n"
"    const unsigned short *__restrict__ Qb,\n"
"    const unsigned short *__restrict__ Kb,\n"
"    const unsigned short *__restrict__ Vb,\n"
"    int N_q, int N_kv, int n_heads, int head_dim) {\n"
"    int h = blockIdx.x;\n"
"    int warp = threadIdx.x / 32;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    int q_base = blockIdx.y * (FABF16_M * FABF16_NWARPS) + warp * FABF16_M;\n"
"    int dim = n_heads * head_dim;\n"
"\n"
"    unsigned int q_frag[8][4];\n"
"#pragma unroll\n"
"    for (int kc = 0; kc < 8; kc++) {\n"
"        int k0 = kc * 16;\n"
"        int row0 = q_base + gid;\n"
"        int row1 = q_base + gid + 8;\n"
"        const unsigned short *qbase0 = (row0 < N_q) ? Qb + (long)row0 * dim + h * head_dim : (const unsigned short *)0;\n"
"        const unsigned short *qbase1 = (row1 < N_q) ? Qb + (long)row1 * dim + h * head_dim : (const unsigned short *)0;\n"
"        unsigned int z = 0;\n"
"        q_frag[kc][0] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*2)     : z;\n"
"#if __CUDA_ARCH__ >= 1200\n"
"        q_frag[kc][1] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*2)     : z;\n"
"        q_frag[kc][2] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*2 + 8) : z;\n"
"#else\n"
"        q_frag[kc][1] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*2 + 8) : z;\n"
"        q_frag[kc][2] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*2)     : z;\n"
"#endif\n"
"        q_frag[kc][3] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*2 + 8) : z;\n"
"    }\n"
"\n"
"    float O[16][4];\n"
"#pragma unroll\n"
"    for (int i = 0; i < 16; i++) {\n"
"        O[i][0] = 0.0f; O[i][1] = 0.0f; O[i][2] = 0.0f; O[i][3] = 0.0f;\n"
"    }\n"
"    float m_state[2] = {-1e30f, -1e30f};\n"
"    float l_state[2] = {0.0f, 0.0f};\n"
"\n"
/* PyTorch constructs the scale on the host in double, then casts to float.
 * GPU approximate rsqrtf(128) is one ULP lower on sm_120. */
"    float qk_scale = (float)(1.0 / sqrt((double)head_dim));\n"
"    float scale_log2 = (float)((double)qk_scale * 1.4426950408889634);\n"
"#if Q21_FLASH_SOFTMAX\n"
"    qk_scale = 1.f;\n"
"#endif\n"
"\n"
"    extern __shared__ unsigned char fa_bf16_smem[];\n"
"    unsigned short *sK_buf[2];\n"
"    unsigned short *sV_buf[2];\n"
"    sK_buf[0] = (unsigned short *)fa_bf16_smem;\n"
"#if Q21_SINGLE_BUFFER\n"
"    sK_buf[1] = sK_buf[0];\n"
"    sV_buf[0] = sK_buf[0] + FABF16_BKV * FABF16_HDP;\n"
"    sV_buf[1] = sV_buf[0];\n"
"#else\n"
"    sK_buf[1] = sK_buf[0] + FABF16_BKV * FABF16_HDP;\n"
"    sV_buf[0] = sK_buf[1] + FABF16_BKV * FABF16_HDP;\n"
"    sV_buf[1] = sV_buf[0] + FABF16_BKV * FABF16_HDP;\n"
"#endif\n"
"\n"
"    int n_kv_tiles = (N_kv + FABF16_BKV - 1) / FABF16_BKV;\n"
"\n"
"#if !Q21_SINGLE_BUFFER\n"
"    {\n"
"        unsigned short *_sK = sK_buf[0];\n"
"        unsigned short *_sV = sV_buf[0];\n"
"#pragma unroll\n"
"        for (int _i = 0; _i < 8; _i++) {\n"
"            int _idx = (int)threadIdx.x + _i * 128;\n"
"            int _kr  = _idx >> 4;\n"
"            int _kd  = (_idx & 15) * 8;\n"
"            int _raw = (Q21_FORWARD_KEYS?0:n_kv_tiles-1)*FABF16_BKV+_kr;\n"
"            int _sr = (_raw < N_kv) ? _raw : 0;\n"
"            const unsigned short *_kp = Kb + (long)_sr * dim + h * head_dim + _kd;\n"
"            const unsigned short *_vp = Vb + (long)_sr * dim + h * head_dim + _kd;\n"
"            unsigned int _dk = (unsigned int)__cvta_generic_to_shared(_sK + _kr * FABF16_HDP + _kd);\n"
"            unsigned int _dv = (unsigned int)__cvta_generic_to_shared(_sV + _kr * FABF16_HDP + _kd);\n"
"            asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dk), \"l\"(_kp));\n"
"            asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dv), \"l\"(_vp));\n"
"        }\n"
"    }\n"
"    asm volatile(\"cp.async.commit_group;\\n\");\n"
"#endif\n"
"\n"
"    for (int kvt = 0; kvt < n_kv_tiles; kvt++) {\n"
"        int kv_base = (Q21_FORWARD_KEYS?kvt:n_kv_tiles-1-kvt) * FABF16_BKV;\n"
"        int cur = kvt & 1;\n"
"        int nxt = 1 - cur;\n"
"        unsigned short *smK = sK_buf[cur];\n"
"        unsigned short *smV = sV_buf[cur];\n"
"\n"
"#if Q21_SINGLE_BUFFER\n"
"#pragma unroll\n"
"        for (int _i = 0; _i < FABF16_BKV/8; _i++) {\n"
"            int _idx = (int)threadIdx.x + _i * 128;\n"
"            int _kr = _idx >> 4;\n"
"            int _kd = (_idx & 15) * 8;\n"
"            int _raw = kv_base + _kr;\n"
"            int _sr = (_raw < N_kv) ? _raw : 0;\n"
"            const unsigned short *_kp = Kb + (long)_sr * dim + h * head_dim + _kd;\n"
"            const unsigned short *_vp = Vb + (long)_sr * dim + h * head_dim + _kd;\n"
"            unsigned int _dk = (unsigned int)__cvta_generic_to_shared(smK + _kr * FABF16_HDP + _kd);\n"
"            unsigned int _dv = (unsigned int)__cvta_generic_to_shared(smV + _kr * FABF16_HDP + _kd);\n"
"            asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dk), \"l\"(_kp));\n"
"            asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dv), \"l\"(_vp));\n"
"        }\n"
"        asm volatile(\"cp.async.commit_group;\\n\");\n"
"        asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        __syncthreads();\n"
"#else\n"
"        if (kvt + 1 < n_kv_tiles) {\n"
"            int kv_next = (Q21_FORWARD_KEYS?kvt+1:n_kv_tiles-2-kvt) * FABF16_BKV;\n"
"            unsigned short *_sK = sK_buf[nxt];\n"
"            unsigned short *_sV = sV_buf[nxt];\n"
"#pragma unroll\n"
"            for (int _i = 0; _i < 8; _i++) {\n"
"                int _idx = (int)threadIdx.x + _i * 128;\n"
"                int _kr  = _idx >> 4;\n"
"                int _kd  = (_idx & 15) * 8;\n"
"                int _raw = kv_next + _kr;\n"
"                int _sr  = (_raw < N_kv) ? _raw : 0;\n"
"                const unsigned short *_kp = Kb + (long)_sr * dim + h * head_dim + _kd;\n"
"                const unsigned short *_vp = Vb + (long)_sr * dim + h * head_dim + _kd;\n"
"                unsigned int _dk = (unsigned int)__cvta_generic_to_shared(_sK + _kr * FABF16_HDP + _kd);\n"
"                unsigned int _dv = (unsigned int)__cvta_generic_to_shared(_sV + _kr * FABF16_HDP + _kd);\n"
"                asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dk), \"l\"(_kp));\n"
"                asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dv), \"l\"(_vp));\n"
"            }\n"
"            asm volatile(\"cp.async.commit_group;\\n\");\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\");\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        }\n"
"        __syncthreads();\n"
"#endif\n"
"\n"
"        float S[FABF16_NI][4];\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < FABF16_NI; ni++) {\n"
"            S[ni][0] = 0.0f; S[ni][1] = 0.0f; S[ni][2] = 0.0f; S[ni][3] = 0.0f;\n"
"        }\n"
"        int ldm_row_off  = lane & 7;\n"
"        int ldm_col_xtra = (lane & 8) ? 8 : 0;\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < FABF16_NI; ni++) {\n"
"            int n_base = ni * 8;\n"
"#pragma unroll\n"
"            for (int kc = 0; kc < 8; kc++) {\n"
"                int k_off = kc * 16;\n"
"                unsigned int b0, b1;\n"
"                unsigned int saddr = (unsigned int)__cvta_generic_to_shared(\n"
"                    smK + (n_base + ldm_row_off) * FABF16_HDP + k_off + ldm_col_xtra);\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x2.shared.b16 {%0,%1}, [%2];\\n\"\n"
"                    : \"=r\"(b0), \"=r\"(b1) : \"r\"(saddr));\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(S[ni][0]), \"=f\"(S[ni][1]), \"=f\"(S[ni][2]), \"=f\"(S[ni][3])\n"
"                    : \"r\"(q_frag[kc][0]), \"r\"(q_frag[kc][1]), \"r\"(q_frag[kc][2]), \"r\"(q_frag[kc][3]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(S[ni][0]), \"f\"(S[ni][1]), \"f\"(S[ni][2]), \"f\"(S[ni][3])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < FABF16_NI; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            int kvr0 = kv_base + col0;\n"
"            int kvr1 = kv_base + col1;\n"
"            S[ni][0] = (kvr0 < N_kv) ? S[ni][0] * qk_scale : -1e30f;\n"
"            S[ni][1] = (kvr1 < N_kv) ? S[ni][1] * qk_scale : -1e30f;\n"
"            S[ni][2] = (kvr0 < N_kv) ? S[ni][2] * qk_scale : -1e30f;\n"
"            S[ni][3] = (kvr1 < N_kv) ? S[ni][3] * qk_scale : -1e30f;\n"
"#if Q21_PRE_SCALE_SCORES\n"
"            S[ni][0] = __fmul_rn(S[ni][0], scale_log2);\n"
"            S[ni][1] = __fmul_rn(S[ni][1], scale_log2);\n"
"            S[ni][2] = __fmul_rn(S[ni][2], scale_log2);\n"
"            S[ni][3] = __fmul_rn(S[ni][3], scale_log2);\n"
"#endif\n"
"        }\n"
"\n"
"        float new_m[2], alpha[2];\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"            float my = -1e30f;\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < FABF16_NI; ni++) {\n"
"                my = fmaxf(my, S[ni][rp*2 + 0]);\n"
"                my = fmaxf(my, S[ni][rp*2 + 1]);\n"
"            }\n"
"            float o1 = __shfl_xor_sync(0xFFFFFFFF, my, 1); my = fmaxf(my, o1);\n"
"            float o2 = __shfl_xor_sync(0xFFFFFFFF, my, 2); my = fmaxf(my, o2);\n"
"            new_m[rp] = fmaxf(m_state[rp], my);\n"
"            alpha[rp] = expf(m_state[rp] - new_m[rp]);\n"
"#if Q21_FLASH_SOFTMAX\n"
"#if Q21_PRE_SCALE_SCORES\n"
"            alpha[rp] = exp2f(m_state[rp] - new_m[rp]);\n"
"#else\n"
"            alpha[rp] = exp2f((m_state[rp] - new_m[rp])*scale_log2);\n"
"#endif\n"
"#endif\n"
"        }\n"
"\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            O[ni][0] *= alpha[0]; O[ni][1] *= alpha[0];\n"
"            O[ni][2] *= alpha[1]; O[ni][3] *= alpha[1];\n"
"        }\n"
"        l_state[0] *= alpha[0]; l_state[1] *= alpha[1];\n"
"\n"
"        float P_data[FABF16_NI][4];\n"
"        float row_sum[2] = {0.0f, 0.0f};\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < FABF16_NI; ni++) {\n"
"                float p0 = expf(S[ni][rp*2 + 0] - new_m[rp]);\n"
"                float p1 = expf(S[ni][rp*2 + 1] - new_m[rp]);\n"
"#if Q21_FLASH_SOFTMAX\n"
"#if Q21_PRE_SCALE_SCORES\n"
"                p0 = exp2f(S[ni][rp*2] - new_m[rp]);\n"
"                p1 = exp2f(S[ni][rp*2+1] - new_m[rp]);\n"
"#else\n"
"                p0 = exp2f(__fmul_rn(S[ni][rp*2],scale_log2)-__fmul_rn(new_m[rp],scale_log2));\n"
"                p1 = exp2f(__fmul_rn(S[ni][rp*2+1],scale_log2)-__fmul_rn(new_m[rp],scale_log2));\n"
"#endif\n"
"#endif\n"
"                P_data[ni][rp*2 + 0] = p0;\n"
"                P_data[ni][rp*2 + 1] = p1;\n"
"                row_sum[rp] += p0 + p1;\n"
"#if Q21_FLASH_SOFTMAX && !Q21_PRE_SCALE_SCORES\n"
"                l_state[rp] += p0; l_state[rp] += p1;\n"
"#endif\n"
"            }\n"
"        }\n"
"        float r0a = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 1); row_sum[0] += r0a;\n"
"        float r0b = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 2); row_sum[0] += r0b;\n"
"        float r1a = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 1); row_sum[1] += r1a;\n"
"        float r1b = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 2); row_sum[1] += r1b;\n"
"#if !Q21_FLASH_SOFTMAX || Q21_PRE_SCALE_SCORES\n"
"        l_state[0] += row_sum[0]; l_state[1] += row_sum[1];\n"
"#endif\n"
"        m_state[0] = new_m[0]; m_state[1] = new_m[1];\n"
"\n"
"        unsigned int P_pack[FABF16_PV_KC][4];\n"
"#pragma unroll\n"
"        for (int kc = 0; kc < FABF16_PV_KC; kc++) {\n"
"            int ni_a = 2*kc;\n"
"            int ni_b = 2*kc + 1;\n"
"            unsigned int q00 = (unsigned int)f32_to_bf16_bits(P_data[ni_a][0])\n"
"                             | ((unsigned int)f32_to_bf16_bits(P_data[ni_a][1]) << 16);\n"
"            unsigned int q01 = (unsigned int)f32_to_bf16_bits(P_data[ni_a][2])\n"
"                             | ((unsigned int)f32_to_bf16_bits(P_data[ni_a][3]) << 16);\n"
"            unsigned int q10 = (unsigned int)f32_to_bf16_bits(P_data[ni_b][0])\n"
"                             | ((unsigned int)f32_to_bf16_bits(P_data[ni_b][1]) << 16);\n"
"            unsigned int q11 = (unsigned int)f32_to_bf16_bits(P_data[ni_b][2])\n"
"                             | ((unsigned int)f32_to_bf16_bits(P_data[ni_b][3]) << 16);\n"
"            P_pack[kc][0] = q00;\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            P_pack[kc][1] = q01;\n"
"            P_pack[kc][2] = q10;\n"
"#else\n"
"            P_pack[kc][1] = q10;\n"
"            P_pack[kc][2] = q01;\n"
"#endif\n"
"            P_pack[kc][3] = q11;\n"
"        }\n"
"\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            int n_base = ni * 8;\n"
"#pragma unroll\n"
"            for (int kc = 0; kc < FABF16_PV_KC; kc++) {\n"
"                unsigned int v_addr = (unsigned int)__cvta_generic_to_shared(\n"
"                    smV + ((kc/2)*32+lane) * FABF16_HDP + n_base);\n"
"                unsigned int vb0, vb1, vb2, vb3;\n"
"                asm(\"ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 {%0,%1,%2,%3}, [%4];\"\n"
"                    : \"=r\"(vb0), \"=r\"(vb1), \"=r\"(vb2), \"=r\"(vb3) : \"r\"(v_addr));\n"
"                unsigned int p0 = P_pack[kc][0];\n"
"                unsigned int p1 = P_pack[kc][1];\n"
"                unsigned int p2 = P_pack[kc][2];\n"
"                unsigned int p3 = P_pack[kc][3];\n"
"                unsigned int b0 = ((kc & 1) == 0) ? vb0 : vb2;\n"
"                unsigned int b1 = ((kc & 1) == 0) ? vb1 : vb3;\n"
"                float d0 = O[ni][0], d1 = O[ni][1], d2 = O[ni][2], d3 = O[ni][3];\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0), \"=f\"(d1), \"=f\"(d2), \"=f\"(d3)\n"
"                    : \"r\"(p0), \"r\"(p1), \"r\"(p2), \"r\"(p3),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0), \"f\"(d1), \"f\"(d2), \"f\"(d3)\n"
"                );\n"
"                O[ni][0] = d0; O[ni][1] = d1; O[ni][2] = d2; O[ni][3] = d3;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    int row0 = q_base + gid;\n"
"    int row1 = q_base + gid + 8;\n"
"#if Q21_FLASH_SOFTMAX && !Q21_PRE_SCALE_SCORES\n"
"    for(int rp=0;rp<2;rp++){l_state[rp]+=__shfl_xor_sync(0xffffffff,l_state[rp],2);l_state[rp]+=__shfl_xor_sync(0xffffffff,l_state[rp],1);}\n"
"#endif\n"
"    float inv_l0 = (l_state[0] > 0.0f) ? 1.0f / l_state[0] : 0.0f;\n"
"    float inv_l1 = (l_state[1] > 0.0f) ? 1.0f / l_state[1] : 0.0f;\n"
"#pragma unroll\n"
"    for (int ni = 0; ni < 16; ni++) {\n"
"        int col0 = ni * 8 + tid4 * 2;\n"
"        int col1 = col0 + 1;\n"
"        if (row0 < N_q && col0 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col0] = O[ni][0] * inv_l0;\n"
"        if (row0 < N_q && col1 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col1] = O[ni][1] * inv_l0;\n"
"        if (row1 < N_q && col0 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col0] = O[ni][2] * inv_l1;\n"
"        if (row1 < N_q && col1 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col1] = O[ni][3] * inv_l1;\n"
"    }\n"
"}\n"
"\n"
"}\n"
"\n";
#endif
