DA2_EXTRA_FLAGS = -DDA2_CUDA
DA2_EXTRA_SRC = ../cuew.c
DA2_EXTRA_LIBS = -ldl
DA2_EXTRA_DEPS = ../gemm/cuda_linear_f32.h cuda_da2_gemm.h ../gemm/cuda_gemm_f32_kernels.h ../cuew.h ../cuda_runner_common.h
include ../../cpu/da2/Makefile
