/*
 * cuda_trellis2_kernels.h - CUDA kernel source strings for TRELLIS.2
 *
 * Compiled at runtime via NVRTC (concatenated with cuda_kernels_common.h).
 * All kernels operate on F32 data with F16 weights (except where noted).
 */
#ifndef CUDA_TRELLIS2_KERNELS_H
#define CUDA_TRELLIS2_KERNELS_H

static const char cuda_trellis2_kernel_source[] =
/* ---- adaLN: y = LN_noaffine(x) * (1 + scale) + shift ---- */
/* x: [N, dim], shift: [dim], scale: [dim], y: [N, dim] */
/* Grid: N blocks, Block: 256 threads */
"__global__ void adaln_f32(\n"
"    float *y, const float *x, const float *shift, const float *scale,\n"
"    int dim, float eps) {\n"
"    int tok = blockIdx.x;\n"
"    const float *xi = x + tok * dim;\n"
"    float *yi = y + tok * dim;\n"
"    extern __shared__ float smem[];\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x) {\n"
"        float v = xi[i]; sum += v; sum2 += v * v;\n"
"    }\n"
"    smem[threadIdx.x] = sum; smem[threadIdx.x + 256] = sum2;\n"
"    __syncthreads();\n"
"    for (int s = 128; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            smem[threadIdx.x] += smem[threadIdx.x + s];\n"
"            smem[threadIdx.x + 256] += smem[threadIdx.x + 256 + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = smem[0] / dim;\n"
"    float var = smem[256] / dim - mean * mean;\n"
"    float inv = rsqrtf(var + eps);\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x) {\n"
"        float normed = (xi[i] - mean) * inv;\n"
"        yi[i] = normed * (1.0f + scale[i]) + shift[i];\n"
"    }\n"
"}\n\n"

/* ---- Gated residual: dst[i] += gate[i % dim] * src[i] ---- */
/* Grid: ceil(n/256), Block: 256 */
"__global__ void gated_add_f32(\n"
"    float *dst, const float *src, const float *gate, int n, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] += gate[i % dim] * src[i];\n"
"}\n\n"

/* ---- Modulation: out = SiLU(t_emb) @ W^T + bias + per_block_bias ---- */
/* t_emb: [dim], W: F16 [6*dim, dim], bias: [6*dim], blk_bias: [6*dim], out: [6*dim] */
/* Single block, 256 threads — small computation (one vector) */
"__global__ void modulation_f32(\n"
"    float *out, const float *t_emb, const float *mod_w, const float *mod_b,\n"
"    const float *blk_bias, int dim, int out_dim) {\n"
"    extern __shared__ float silu_emb[];\n"
"    /* Load t_emb into shared memory with SiLU applied */\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x)\n"
"        silu_emb[i] = t_emb[i] / (1.0f + expf(-t_emb[i]));\n"
"    __syncthreads();\n"
"    /* Each thread computes one output element */\n"
"    for (int r = threadIdx.x; r < out_dim; r += blockDim.x) {\n"
"        float sum = 0;\n"
"        const float *wr = mod_w + (size_t)r * dim;\n"
"        for (int j = 0; j < dim; j++) sum += wr[j] * silu_emb[j];\n"
"        sum += mod_b ? mod_b[r] : 0.0f;\n"
"        sum += blk_bias ? blk_bias[r] : 0.0f;\n"
"        out[r] = sum;\n"
"    }\n"
"}\n\n"

/* ---- 3D RoPE for dense grid (complex-pair convention) ---- */
/* Official TRELLIS.2: view_as_complex pairs (x[2k], x[2k+1]) then multiply by phase.
 * Phase layout: [n_freqs_z, n_freqs_y, n_freqs_x, padding] complex values.
 * rope_cos/sin: [N, 3, n_freqs] — per axis cos/sin of coord*freq.
 * Grid: N, Block: 256 (one thread per head) */
"__global__ void rope_3d_f32(\n"
"    float *data, const float *rope_cos, const float *rope_sin,\n"
"    int N, int dim, int n_heads, int head_dim,\n"
"    int n_freqs, int axis_dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    float *v = data + (size_t)tok * dim;\n"
"    const float *cs = rope_cos + (size_t)tok * 3 * n_freqs;\n"
"    const float *sn = rope_sin + (size_t)tok * 3 * n_freqs;\n"
"    for (int h = threadIdx.x; h < n_heads; h += blockDim.x) {\n"
"        float *vh = v + h * head_dim;\n"
"        /* Complex-pair rotation: (vh[2k], vh[2k+1]) * (cos+i*sin) */\n"
"        int pair = 0;\n"
"        for (int axis = 0; axis < 3; axis++) {\n"
"            const float *ca = cs + axis * n_freqs;\n"
"            const float *sa = sn + axis * n_freqs;\n"
"            for (int j = 0; j < n_freqs; j++, pair++) {\n"
"                int idx = pair * 2;\n"
"                float re = vh[idx];\n"
"                float im = vh[idx + 1];\n"
"                vh[idx]     = re * ca[j] - im * sa[j];\n"
"                vh[idx + 1] = re * sa[j] + im * ca[j];\n"
"            }\n"
"        }\n"
"        /* remaining pairs (if head_dim/2 > 3*n_freqs): identity (no rotation) */\n"
"    }\n"
"}\n\n"

/* ---- Per-head RMSNorm with per-head gamma [n_heads, head_dim] ---- */
/* data: [n_tok, stride], gamma: [n_heads * head_dim] */
/* Grid: ceil(total_heads/256), Block: 256 — one thread per (tok, head) */
"__global__ void rms_norm_perhead_f32(\n"
"    float *data, const float *gamma,\n"
"    int n_tok, int n_heads, int head_dim, int stride, float eps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = n_tok * n_heads;\n"
"    if (idx >= total) return;\n"
"    int tok = idx / n_heads;\n"
"    int h = idx % n_heads;\n"
"    float *v = data + (size_t)tok * stride + h * head_dim;\n"
"    const float *g = gamma + h * head_dim;\n"
"    float ss = 0;\n"
"    for (int i = 0; i < head_dim; i++) ss += v[i] * v[i];\n"
"    float rms = rsqrtf(ss / head_dim + eps);\n"
"    for (int i = 0; i < head_dim; i++) v[i] *= rms * g[i];\n"
"}\n\n"

/* ---- Dense Conv3D: k=3, pad=1, stride=1 ---- */
/* input: [Ci, D, H, W], weight: F32 [Co, Ci, 3, 3, 3], bias: [Co], output: [Co, D, H, W] */
/* Grid: (Co, D*H*W / 64), Block: 64 */
"__global__ void conv3d_k3_f32(\n"
"    float *out, const float *inp, const float *weight, const float *bias,\n"
"    int Ci, int Co, int D, int H, int W) {\n"
"    int co = blockIdx.x;\n"
"    int spatial_idx = blockIdx.y * blockDim.x + threadIdx.x;\n"
"    int spatial = D * H * W;\n"
"    if (co >= Co || spatial_idx >= spatial) return;\n"
"    int d = spatial_idx / (H * W);\n"
"    int h = (spatial_idx / W) % H;\n"
"    int w = spatial_idx % W;\n"
"    float sum = bias ? bias[co] : 0.0f;\n"
"    for (int ci = 0; ci < Ci; ci++) {\n"
"        const float *kern = weight + ((size_t)co * Ci + ci) * 27;\n"
"        for (int kd = 0; kd < 3; kd++) {\n"
"            int dd = d + kd - 1;\n"
"            if (dd < 0 || dd >= D) continue;\n"
"            for (int kh = 0; kh < 3; kh++) {\n"
"                int hh = h + kh - 1;\n"
"                if (hh < 0 || hh >= H) continue;\n"
"                for (int kw = 0; kw < 3; kw++) {\n"
"                    int ww = w + kw - 1;\n"
"                    if (ww < 0 || ww >= W) continue;\n"
"                    sum += kern[kd*9 + kh*3 + kw]\n"
"                         * inp[(size_t)ci * spatial + dd * H * W + hh * W + ww];\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    out[(size_t)co * spatial + spatial_idx] = sum;\n"
"}\n\n"

/* ---- GroupNorm 3D: [C, D, H, W] with G groups ---- */
/* Grid: G, Block: 256 */
"__global__ void groupnorm_3d_f32(\n"
"    float *dst, const float *src, const float *w, const float *b,\n"
"    int C, int spatial, int G) {\n"
"    int g = blockIdx.x;\n"
"    int cpg = C / G;\n"
"    int c_start = g * cpg;\n"
"    int n = cpg * spatial;\n"
"    float eps = 1e-5f;\n"
"    extern __shared__ float smem[];\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int i = threadIdx.x; i < n; i += blockDim.x) {\n"
"        int c = c_start + i / spatial;\n"
"        int s = i % spatial;\n"
"        float v = src[(size_t)c * spatial + s];\n"
"        sum += v; sum2 += v * v;\n"
"    }\n"
"    smem[threadIdx.x] = sum; smem[threadIdx.x + 256] = sum2;\n"
"    __syncthreads();\n"
"    for (int s = 128; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            smem[threadIdx.x] += smem[threadIdx.x + s];\n"
"            smem[threadIdx.x + 256] += smem[threadIdx.x + 256 + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = smem[0] / n;\n"
"    float var = smem[256] / n - mean * mean;\n"
"    float inv = rsqrtf(var + eps);\n"
"    for (int i = threadIdx.x; i < n; i += blockDim.x) {\n"
"        int c = c_start + i / spatial;\n"
"        int s = i % spatial;\n"
"        float normed = (src[(size_t)c * spatial + s] - mean) * inv;\n"
"        dst[(size_t)c * spatial + s] = normed * (w ? w[c] : 1.0f) + (b ? b[c] : 0.0f);\n"
"    }\n"
"}\n\n"

/* ---- SiLU in-place ---- */
"__global__ void silu_inplace_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] = x[i] / (1.0f + expf(-x[i]));\n"
"}\n\n"

/* ---- pixel_shuffle_3d: [C*8, D, H, W] -> [C, 2D, 2H, 2W] ---- */
/* Grid: ceil(total/256), Block: 256 — total = C * 2D * 2H * 2W */
"__global__ void pixel_shuffle_3d_f32(\n"
"    float *dst, const float *src,\n"
"    int C, int D, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int D2 = 2*D, H2 = 2*H, W2 = 2*W;\n"
"    int total = C * D2 * H2 * W2;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (D2 * H2 * W2);\n"
"    int rem = idx % (D2 * H2 * W2);\n"
"    int od = rem / (H2 * W2);\n"
"    rem = rem % (H2 * W2);\n"
"    int oh = rem / W2;\n"
"    int ow = rem % W2;\n"
"    int d = od / 2, sd = od % 2;\n"
"    int h = oh / 2, sh = oh % 2;\n"
"    int w = ow / 2, sw = ow % 2;\n"
"    int src_ch = c * 8 + (sd * 2 + sh) * 2 + sw;\n"
"    int spatial_in = D * H * W;\n"
"    dst[idx] = src[(size_t)src_ch * spatial_in + d * H * W + h * W + w];\n"
"}\n\n"

/* ---- LayerNorm (no affine): y = (x - mean) / sqrt(var + eps) ---- */
/* Grid: N, Block: 256 */
"__global__ void layernorm_noaffine_f32(\n"
"    float *y, const float *x, int dim, float eps) {\n"
"    int tok = blockIdx.x;\n"
"    const float *xi = x + tok * dim;\n"
"    float *yi = y + tok * dim;\n"
"    extern __shared__ float smem[];\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x) {\n"
"        float v = xi[i]; sum += v; sum2 += v * v;\n"
"    }\n"
"    smem[threadIdx.x] = sum; smem[threadIdx.x + 256] = sum2;\n"
"    __syncthreads();\n"
"    for (int s = 128; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            smem[threadIdx.x] += smem[threadIdx.x + s];\n"
"            smem[threadIdx.x + 256] += smem[threadIdx.x + 256 + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = smem[0] / dim;\n"
"    float var = smem[256] / dim - mean * mean;\n"
"    float inv = rsqrtf(var + eps);\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x)\n"
"        yi[i] = (xi[i] - mean) * inv;\n"
"}\n\n"

/* ---- split_qkv_chunk_f32: split [N, 3*W] by chunk (NOT interleaved) ---- */
/* Input: [N, 3*W] where first W = Q, next W = K, last W = V */
/* Output: Q[N, W], K[N, W], V[N, W] */
"__global__ void split_qkv_chunk_f32(\n"
"    float *Q, float *K, float *V,\n"
"    const float *qkv, int N, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * W;\n"
"    if (idx >= total) return;\n"
"    int n = idx / W;\n"
"    int d = idx % W;\n"
"    int base = n * 3 * W;\n"
"    Q[idx] = qkv[base + d];\n"
"    K[idx] = qkv[base + W + d];\n"
"    V[idx] = qkv[base + 2*W + d];\n"
"}\n\n"

/* ---- split_kv_chunk_f32: split [M, 2*W] by chunk ---- */
"__global__ void split_kv_chunk_f32(\n"
"    float *K, float *V,\n"
"    const float *kv, int M, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = M * W;\n"
"    if (idx >= total) return;\n"
"    int n = idx / W;\n"
"    int d = idx % W;\n"
"    int base = n * 2 * W;\n"
"    K[idx] = kv[base + d];\n"
"    V[idx] = kv[base + W + d];\n"
"}\n\n"

/* ---- timestep_embed_cossin_f32: sinusoidal embed with [cos, sin] order ---- */
/* TRELLIS.2 uses [cos, sin] while HY3D uses [sin, cos]. */
"__global__ void timestep_embed_cossin_f32(float *out, float t, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int half = dim / 2;\n"
"    if (i >= half) return;\n"
"    float exponent = -logf(10000.0f) * (float)i / (float)half;\n"
"    float emb = expf(exponent) * t;\n"
"    out[i] = cosf(emb);\n"
"    out[half + i] = sinf(emb);\n"
"}\n\n"

/* ---- Channel LayerNorm 3D: normalize across C at each spatial position ---- */
/* Input: [C, D, H, W] (NCDHW batch=1). Normalize over C with learnable w, b [C]. */
/* Grid: spatial (D*H*W), Block: 256 */
"__global__ void channel_layernorm_3d_f32(\n"
"    float *dst, const float *src, const float *w, const float *b,\n"
"    int C, int spatial) {\n"
"    int s = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (s >= spatial) return;\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int c = 0; c < C; c++) {\n"
"        float v = src[(size_t)c * spatial + s];\n"
"        sum += v; sum2 += v * v;\n"
"    }\n"
"    float mean = sum / C;\n"
"    float var = sum2 / C - mean * mean;\n"
"    float inv = rsqrtf(var + 1e-5f);\n"
"    for (int c = 0; c < C; c++) {\n"
"        float v = (src[(size_t)c * spatial + s] - mean) * inv;\n"
"        dst[(size_t)c * spatial + s] = v * (w ? w[c] : 1.0f) + (b ? b[c] : 0.0f);\n"
"    }\n"
"}\n\n"

/* ---- DINOv3 2D RoPE: rotate_half convention, patch tokens only ---- */
/* cos/sin: [n_patches, head_dim], Q/K: [seq, dim] where first n_prefix tokens skipped */
/* Grid: n_patches, Block: 256 */
"__global__ void rope_2d_dinov3_f32(\n"
"    float *Q, float *K,\n"
"    const float *cos_tab, const float *sin_tab,\n"
"    int n_patches, int n_prefix, int dim, int n_heads, int head_dim) {\n"
"    int p = blockIdx.x;\n"
"    if (p >= n_patches) return;\n"
"    int tok = n_prefix + p;  /* skip CLS + register tokens */\n"
"    int half_hd = head_dim / 2;\n"
"    const float *c = cos_tab + p * head_dim;\n"
"    const float *s = sin_tab + p * head_dim;\n"
"    for (int h = threadIdx.x; h < n_heads; h += blockDim.x) {\n"
"        /* rotate_half: [-x[d/2:], x[:d/2]] */\n"
"        float *q = Q + (size_t)tok * dim + h * head_dim;\n"
"        float *k = K + (size_t)tok * dim + h * head_dim;\n"
"        for (int d = 0; d < half_hd; d++) {\n"
"            float q0 = q[d], q1 = q[d + half_hd];\n"
"            q[d]           = q0 * c[d]           + (-q1) * s[d];\n"
"            q[d + half_hd] = q1 * c[d + half_hd] + q0 * s[d + half_hd];\n"
"            float k0 = k[d], k1 = k[d + half_hd];\n"
"            k[d]           = k0 * c[d]           + (-k1) * s[d];\n"
"            k[d + half_hd] = k1 * c[d + half_hd] + k0 * s[d + half_hd];\n"
"        }\n"
"    }\n"
"}\n\n"

/* ---- DINOv3 patch embedding: conv2d [3, ps, ps] -> [dim] per patch ---- */
/* image: [3, H, W] normalized float. Grid: n_patches, Block: 256 */
"__global__ void dinov3_patch_embed_f32(\n"
"    float *out, const float *image, const float *W, const float *bias,\n"
"    int grid_w, int dim, int ps, int img_w) {\n"
"    int pidx = blockIdx.x;\n"
"    int py = pidx / grid_w, px = pidx % grid_w;\n"
"    for (int co = threadIdx.x; co < dim; co += blockDim.x) {\n"
"        float sum = bias ? bias[co] : 0.0f;\n"
"        for (int ci = 0; ci < 3; ci++) {\n"
"            for (int kh = 0; kh < ps; kh++) {\n"
"                for (int kw = 0; kw < ps; kw++) {\n"
"                    int ih = py * ps + kh, iw = px * ps + kw;\n"
"                    sum += W[((co * 3 + ci) * ps + kh) * ps + kw]\n"
"                         * image[ci * img_w * img_w + ih * img_w + iw];\n"
"                }\n"
"            }\n"
"        }\n"
"        out[pidx * dim + co] = sum;\n"
"    }\n"
"}\n\n"

/* ---- DINOv3 prepend CLS + register tokens ---- */
/* patches: [n_patches, dim] at offset n_prefix in output */
/* cls: [1, dim], reg: [n_reg, dim] */
"__global__ void dinov3_prepend_tokens_f32(\n"
"    float *hidden, const float *patches, const float *cls, const float *reg,\n"
"    int n_patches, int n_reg, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int n_prefix = 1 + n_reg;\n"
"    int total = (n_prefix + n_patches) * dim;\n"
"    if (i >= total) return;\n"
"    int tok = i / dim, d = i % dim;\n"
"    if (tok == 0) hidden[i] = cls[d];\n"
"    else if (tok < n_prefix) hidden[i] = reg[(tok - 1) * dim + d];\n"
"    else hidden[i] = patches[(tok - n_prefix) * dim + d];\n"
"}\n\n"

/* ---- Tiled cross-attention for large N (online softmax, no smem score array) ---- */
/* Grid: (n_heads, q_len), Block: 128. Handles arbitrary kv_len. */
"__global__ void cross_attn_tiled_f32(float *out,\n"
"    const float *Q, const float *K, const float *V,\n"
"    int q_len, int kv_len, int dim, int n_heads, int head_dim, float scale) {\n"
"    int h = blockIdx.x; int qi = blockIdx.y;\n"
"    if (h >= n_heads || qi >= q_len) return;\n"
"    const float *q = Q + qi * dim + h * head_dim;\n"
"    /* Online softmax: process KV in tiles of 32 */\n"
"    float running_max = -1e30f, running_sum = 0.0f;\n"
"    /* Accumulator in registers (head_dim loop) */\n"
"    float acc[128];\n"  /* max head_dim=128 */
"    for (int d = 0; d < head_dim; d++) acc[d] = 0.0f;\n"
"    for (int ki_base = 0; ki_base < kv_len; ki_base += 32) {\n"
"        int tile_end = ki_base + 32; if (tile_end > kv_len) tile_end = kv_len;\n"
"        float tile_max = -1e30f;\n"
"        float scores[32];\n"
"        for (int j = 0; j < tile_end - ki_base; j++) {\n"
"            const float *k = K + (ki_base+j) * dim + h * head_dim;\n"
"            float dot = 0;\n"
"            for (int d = 0; d < head_dim; d++) dot += q[d] * k[d];\n"
"            scores[j] = dot * scale;\n"
"            if (scores[j] > tile_max) tile_max = scores[j];\n"
"        }\n"
"        float new_max = fmaxf(running_max, tile_max);\n"
"        float correction = expf(running_max - new_max);\n"
"        running_sum *= correction;\n"
"        for (int d = 0; d < head_dim; d++) acc[d] *= correction;\n"
"        for (int j = 0; j < tile_end - ki_base; j++) {\n"
"            float w = expf(scores[j] - new_max);\n"
"            running_sum += w;\n"
"            const float *v = V + (ki_base+j) * dim + h * head_dim;\n"
"            for (int d = 0; d < head_dim; d++) acc[d] += w * v[d];\n"
"        }\n"
"        running_max = new_max;\n"
"    }\n"
"    float inv = (running_sum > 0) ? 1.0f / running_sum : 0.0f;\n"
"    float *o = out + qi * dim + h * head_dim;\n"
"    for (int d = 0; d < head_dim; d++) o[d] = acc[d] * inv;\n"
"}\n\n"

/* ---- MMA attention for head_dim=128, separate Q/K/V ---- */
/* FlashAttention with online softmax using m16n8k16 tensor core MMA.
 * Q/K/V: [N, dim] where dim = n_heads * head_dim (interleaved heads).
 * Grid: (n_heads, ceil(q_len/64)), Block: 128 threads = 4 warps.
 * Each warp processes 16 query tokens. */
"__global__ void attn_mma_hd128_f32(\n"
"    float *out, const float *Q, const float *K, const float *V,\n"
"    int q_len, int kv_len, int dim, int n_heads, int head_dim, float scale) {\n"
"    int h = blockIdx.x;\n"
"    if (h >= n_heads) return;\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int qb = blockIdx.y * 64 + warp_id * 16;\n"
"    if (qb >= q_len) return;\n"
"    int lane = threadIdx.x % 32;\n"
"    int gid = lane / 4, tid4 = lane % 4;\n"
"    int qi0 = qb + gid, qi1 = qb + gid + 8;\n"
"\n"
"    /* Load Q fragments: 8 tiles of k=16 covering 128 dims */\n"
"    unsigned int qa0[8], qa1[8], qa2[8], qa3[8];\n"
"#pragma unroll\n"
"    for (int kk = 0; kk < 128; kk += 16) {\n"
"        int ks = kk / 16;\n"
"        int dc = h * 128 + kk + tid4 * 2;\n"
"        { float f0 = (qi0<q_len) ? Q[qi0*dim+dc] : 0, f1 = (qi0<q_len) ? Q[qi0*dim+dc+1] : 0;\n"
"          asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\" : \"=r\"(qa0[ks]) : \"f\"(f0), \"f\"(f1)); }\n"
"#if __CUDA_ARCH__ >= 1200\n"
"        { float f0 = (qi1<q_len) ? Q[qi1*dim+dc] : 0, f1 = (qi1<q_len) ? Q[qi1*dim+dc+1] : 0;\n"
"          asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\" : \"=r\"(qa1[ks]) : \"f\"(f0), \"f\"(f1)); }\n"
"        { float f0 = (qi0<q_len) ? Q[qi0*dim+dc+8] : 0, f1 = (qi0<q_len) ? Q[qi0*dim+dc+9] : 0;\n"
"          asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\" : \"=r\"(qa2[ks]) : \"f\"(f0), \"f\"(f1)); }\n"
"#else\n"
"        { float f0 = (qi0<q_len) ? Q[qi0*dim+dc+8] : 0, f1 = (qi0<q_len) ? Q[qi0*dim+dc+9] : 0;\n"
"          asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\" : \"=r\"(qa1[ks]) : \"f\"(f0), \"f\"(f1)); }\n"
"        { float f0 = (qi1<q_len) ? Q[qi1*dim+dc] : 0, f1 = (qi1<q_len) ? Q[qi1*dim+dc+1] : 0;\n"
"          asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\" : \"=r\"(qa2[ks]) : \"f\"(f0), \"f\"(f1)); }\n"
"#endif\n"
"        { float f0 = (qi1<q_len) ? Q[qi1*dim+dc+8] : 0, f1 = (qi1<q_len) ? Q[qi1*dim+dc+9] : 0;\n"
"          asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\" : \"=r\"(qa3[ks]) : \"f\"(f0), \"f\"(f1)); }\n"
"    }\n"
"\n"
"    /* Online softmax state and output accumulators (128 dims = 16 chunks of 8) */\n"
"    float m0 = -1e30f, l0 = 0.0f, m1 = -1e30f, l1 = 0.0f;\n"
"    float oc0[16]={0}, oc1[16]={0}, oc2[16]={0}, oc3[16]={0};\n"
"\n"
"    /* Iterate over KV tokens in tiles of 16 */\n"
"    for (int kv = 0; kv < kv_len; kv += 16) {\n"
"        /* Phase 1: Compute Q @ K^T scores via MMA */\n"
"        float s0[2]={0,0}, s1[2]={0,0}, s2[2]={0,0}, s3[2]={0,0};\n"
"#pragma unroll\n"
"        for (int kk = 0; kk < 128; kk += 16) {\n"
"            int ks = kk / 16;\n"
"            unsigned int a0=qa0[ks], a1=qa1[ks], a2=qa2[ks], a3=qa3[ks];\n"
"            for (int nh = 0; nh < 2; nh++) {\n"
"                int ki = kv + nh*8 + gid;\n"
"                unsigned int b0=0, b1=0;\n"
"                if (ki < kv_len) {\n"
"                    int koff = ki*dim + h*128 + kk;\n"
"                    float kf0=K[koff+tid4*2], kf1=K[koff+tid4*2+1];\n"
"                    asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(b0):\"f\"(kf0),\"f\"(kf1));\n"
"                    float kf2=K[koff+tid4*2+8], kf3=K[koff+tid4*2+9];\n"
"                    asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(b1):\"f\"(kf2),\"f\"(kf3));\n"
"                }\n"
"                asm volatile(\"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    :\"=f\"(s0[nh]),\"=f\"(s1[nh]),\"=f\"(s2[nh]),\"=f\"(s3[nh])\n"
"                    :\"r\"(a0),\"r\"(a1),\"r\"(a2),\"r\"(a3),\"r\"(b0),\"r\"(b1),\n"
"                     \"f\"(s0[nh]),\"f\"(s1[nh]),\"f\"(s2[nh]),\"f\"(s3[nh]));\n"
"            }\n"
"        }\n"
"        /* Scale and mask out-of-bounds */\n"
"        s0[0]*=scale; s1[0]*=scale; s2[0]*=scale; s3[0]*=scale;\n"
"        s0[1]*=scale; s1[1]*=scale; s2[1]*=scale; s3[1]*=scale;\n"
"        { int c0=kv+tid4*2, c1=c0+1;\n"
"          if(c0>=kv_len){s0[0]=-1e30f;s2[0]=-1e30f;} if(c1>=kv_len){s1[0]=-1e30f;s3[0]=-1e30f;}\n"
"          if(c0+8>=kv_len){s0[1]=-1e30f;s2[1]=-1e30f;} if(c1+8>=kv_len){s1[1]=-1e30f;s3[1]=-1e30f;} }\n"
"        if(qi0>=q_len){s0[0]=-1e30f;s1[0]=-1e30f;s0[1]=-1e30f;s1[1]=-1e30f;}\n"
"        if(qi1>=q_len){s2[0]=-1e30f;s3[0]=-1e30f;s2[1]=-1e30f;s3[1]=-1e30f;}\n"
"\n"
"        /* Phase 2: Online softmax for query rows 0 and 1 */\n"
"        float mx0 = fmaxf(fmaxf(s0[0],s1[0]),fmaxf(s0[1],s1[1]));\n"
"        mx0 = fmaxf(mx0, __shfl_xor_sync(0xFFFFFFFF, mx0, 1));\n"
"        mx0 = fmaxf(mx0, __shfl_xor_sync(0xFFFFFFFF, mx0, 2));\n"
"        float mn0 = fmaxf(m0, mx0);\n"
"        float al0 = expf(m0 - mn0);\n"
"        l0 *= al0; m0 = mn0;\n"
"        for (int c=0;c<16;c++) { oc0[c]*=al0; oc1[c]*=al0; }\n"
"        s0[0]=expf(s0[0]-mn0); s1[0]=expf(s1[0]-mn0);\n"
"        s0[1]=expf(s0[1]-mn0); s1[1]=expf(s1[1]-mn0);\n"
"        float rs0=s0[0]+s1[0]+s0[1]+s1[1];\n"
"        rs0+=__shfl_xor_sync(0xFFFFFFFF,rs0,1); rs0+=__shfl_xor_sync(0xFFFFFFFF,rs0,2);\n"
"        l0 += rs0;\n"
"        float mx1 = fmaxf(fmaxf(s2[0],s3[0]),fmaxf(s2[1],s3[1]));\n"
"        mx1 = fmaxf(mx1, __shfl_xor_sync(0xFFFFFFFF, mx1, 1));\n"
"        mx1 = fmaxf(mx1, __shfl_xor_sync(0xFFFFFFFF, mx1, 2));\n"
"        float mn1 = fmaxf(m1, mx1);\n"
"        float al1 = expf(m1 - mn1);\n"
"        l1 *= al1; m1 = mn1;\n"
"        for (int c=0;c<16;c++) { oc2[c]*=al1; oc3[c]*=al1; }\n"
"        s2[0]=expf(s2[0]-mn1); s3[0]=expf(s3[0]-mn1);\n"
"        s2[1]=expf(s2[1]-mn1); s3[1]=expf(s3[1]-mn1);\n"
"        float rs1=s2[0]+s3[0]+s2[1]+s3[1];\n"
"        rs1+=__shfl_xor_sync(0xFFFFFFFF,rs1,1); rs1+=__shfl_xor_sync(0xFFFFFFFF,rs1,2);\n"
"        l1 += rs1;\n"
"\n"
"        /* Phase 3: Weighted sum of V via MMA */\n"
"        unsigned int pa0,pa1,pa2,pa3;\n"
"        asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(pa0):\"f\"(s0[0]),\"f\"(s1[0]));\n"
"#if __CUDA_ARCH__ >= 1200\n"
"        asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(pa1):\"f\"(s2[0]),\"f\"(s3[0]));\n"
"        asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(pa2):\"f\"(s0[1]),\"f\"(s1[1]));\n"
"#else\n"
"        asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(pa1):\"f\"(s0[1]),\"f\"(s1[1]));\n"
"        asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(pa2):\"f\"(s2[0]),\"f\"(s3[0]));\n"
"#endif\n"
"        asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(pa3):\"f\"(s2[1]),\"f\"(s3[1]));\n"
"        for (int c = 0; c < 16; c++) {\n"
"            int vki0 = kv+tid4*2, vki1 = vki0+1, vki8 = vki0+8, vki9 = vki8+1;\n"
"            int voff = h*128 + c*8 + gid;\n"
"            unsigned int vb0=0, vb1=0;\n"
"            if (vki1 < kv_len) {\n"
"                float vf0=V[vki0*dim+voff], vf1=V[vki1*dim+voff];\n"
"                asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(vb0):\"f\"(vf0),\"f\"(vf1));\n"
"            } else if (vki0 < kv_len) {\n"
"                float vf0=V[vki0*dim+voff];\n"
"                asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(vb0):\"f\"(vf0),\"f\"(0.0f));\n"
"            }\n"
"            if (vki9 < kv_len) {\n"
"                float vf0=V[vki8*dim+voff], vf1=V[vki9*dim+voff];\n"
"                asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(vb1):\"f\"(vf0),\"f\"(vf1));\n"
"            } else if (vki8 < kv_len) {\n"
"                float vf0=V[vki8*dim+voff];\n"
"                asm(\"cvt.rn.f16x2.f32 %0, %2, %1;\":\"=r\"(vb1):\"f\"(vf0),\"f\"(0.0f));\n"
"            }\n"
"            asm volatile(\"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\\n\\t\"\n"
"                \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                :\"=f\"(oc0[c]),\"=f\"(oc1[c]),\"=f\"(oc2[c]),\"=f\"(oc3[c])\n"
"                :\"r\"(pa0),\"r\"(pa1),\"r\"(pa2),\"r\"(pa3),\"r\"(vb0),\"r\"(vb1),\n"
"                 \"f\"(oc0[c]),\"f\"(oc1[c]),\"f\"(oc2[c]),\"f\"(oc3[c]));\n"
"        }\n"
"    }\n"
"\n"
"    /* Phase 4: Normalize and write output */\n"
"    float il0 = (l0>0) ? 1.0f/l0 : 0.0f;\n"
"    float il1 = (l1>0) ? 1.0f/l1 : 0.0f;\n"
"    for (int c = 0; c < 16; c++) {\n"
"        int d0 = h*128 + c*8+tid4*2, d1 = d0+1;\n"
"        if (qi0<q_len) { out[qi0*dim+d0]=oc0[c]*il0; out[qi0*dim+d1]=oc1[c]*il0; }\n"
"        if (qi1<q_len) { out[qi1*dim+d0]=oc2[c]*il1; out[qi1*dim+d1]=oc3[c]*il1; }\n"
"    }\n"
"}\n\n"

/* ---- Sparse 3D convolution kernels ---- */

/* Build neighbor gather map: for each voxel, find indices of 27 neighbors.
 * coords: [N, 4] int32 (batch, z, y, x)
 * hash_keys: [capacity] uint64  hash_vals: [capacity] int32
 * out_map: [N, 27] int32 (-1 if neighbor absent)
 * Grid: ceil(N/256), Block: 256 */
"__global__ void sparse_build_gather_map_f32(\n"
"    int *out_map, const int *coords, int N,\n"
"    const unsigned long long *hash_keys, const int *hash_vals, int hash_cap) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= N) return;\n"
"    int b  = coords[i * 4];\n"
"    int cz = coords[i * 4 + 1];\n"
"    int cy = coords[i * 4 + 2];\n"
"    int cx = coords[i * 4 + 3];\n"
"    for (int kd = 0; kd < 3; kd++) {\n"
"        for (int kh = 0; kh < 3; kh++) {\n"
"            for (int kw = 0; kw < 3; kw++) {\n"
"                int nz = cz + kd - 1, ny = cy + kh - 1, nx = cx + kw - 1;\n"
"                unsigned long long key = ((unsigned long long)(unsigned short)b << 48)\n"
"                    | ((unsigned long long)(unsigned short)nz << 32)\n"
"                    | ((unsigned long long)(unsigned short)ny << 16)\n"
"                    | (unsigned long long)(unsigned short)nx;\n"
"                unsigned int slot = (unsigned int)((key * 0x9E3779B97F4A7C15ULL) >> 32)\n"
"                                  % (unsigned int)hash_cap;\n"
"                int result = -1;\n"
"                for (;;) {\n"
"                    unsigned long long sk = hash_keys[slot];\n"
"                    if (sk == key) { result = hash_vals[slot]; break; }\n"
"                    if (sk == 0xFFFFFFFFFFFFFFFFULL) break;\n"
"                    slot = (slot + 1) % (unsigned int)hash_cap;\n"
"                }\n"
"                out_map[i * 27 + kd * 9 + kh * 3 + kw] = result;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n\n"

/* Gather neighbor features for one kernel position.
 * gather_map: [N, 27] int32 neighbor indices
 * feats: [N, C] float32 input features
 * gathered: [N, C] float32 output (zero if neighbor absent)
 * k_idx: which of the 27 kernel positions to gather for
 * Grid: ceil(N*C/256), Block: 256 */
"__global__ void sparse_gather_f32(\n"
"    float *gathered, const float *feats, const int *gather_map,\n"
"    int N, int C, int k_idx) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= N * C) return;\n"
"    int i = idx / C;\n"
"    int c = idx % C;\n"
"    int ni = gather_map[i * 27 + k_idx];\n"
"    gathered[idx] = (ni >= 0) ? feats[(size_t)ni * C + c] : 0.0f;\n"
"}\n\n"

/* Scatter-add: dst[i] += src[i] for N*C elements.
 * Grid: ceil(N*C/256), Block: 256 */
"__global__ void scatter_add_f32(\n"
"    float *dst, const float *src, int count) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < count) dst[i] += src[i];\n"
"}\n\n"

/* Init buffer with broadcast bias: dst[i*C + c] = bias[c] for all i.
 * Grid: ceil(N*C/256), Block: 256 */
"__global__ void broadcast_bias_f32(\n"
"    float *dst, const float *bias, int N, int C) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= N * C) return;\n"
"    dst[idx] = bias ? bias[idx % C] : 0.0f;\n"
"}\n\n"

/* Residual add: dst[i] += src[i]. Grid: ceil(n/256), Block: 256 */
"__global__ void residual_add_f32(float *dst, const float *src, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] += src[i];\n"
"}\n\n"

/* GELU activation (in-place). Grid: ceil(n/256), Block: 256 */
"/* (gelu_f32 already in common kernels) */\n"

/* LayerNorm for sparse features: same as layernorm_f32 but just a reminder.
 * Already available as layernorm_f32 in common kernels. */

"} /* close extern C from cuda_kernels_common */\n"
; /* end of kernel source string */

#endif /* CUDA_TRELLIS2_KERNELS_H */
