/*
 * cuda_trellis2_kernels.h - CUDA kernel source strings for TRELLIS.2
 *
 * Compiled at runtime via NVRTC (concatenated with cuda_kernels_common.h).
 * All kernels operate on F32 data with F16 weights (except where noted).
 */
#ifndef CUDA_TRELLIS2_KERNELS_H
#define CUDA_TRELLIS2_KERNELS_H

static const char cuda_trellis2_kernel_source[] =
/* ---- adaLN: y = LN_noaffine(x) * (1 + scale) + shift ---- */
/* x: [N, dim], shift: [dim], scale: [dim], y: [N, dim] */
/* Grid: N blocks, Block: 256 threads */
"__global__ void adaln_f32(\n"
"    float *y, const float *x, const float *shift, const float *scale,\n"
"    int dim, float eps) {\n"
"    int tok = blockIdx.x;\n"
"    const float *xi = x + tok * dim;\n"
"    float *yi = y + tok * dim;\n"
"    extern __shared__ float smem[];\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x) {\n"
"        float v = xi[i]; sum += v; sum2 += v * v;\n"
"    }\n"
"    smem[threadIdx.x] = sum; smem[threadIdx.x + 256] = sum2;\n"
"    __syncthreads();\n"
"    for (int s = 128; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            smem[threadIdx.x] += smem[threadIdx.x + s];\n"
"            smem[threadIdx.x + 256] += smem[threadIdx.x + 256 + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = smem[0] / dim;\n"
"    float var = smem[256] / dim - mean * mean;\n"
"    float inv = rsqrtf(var + eps);\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x) {\n"
"        float normed = (xi[i] - mean) * inv;\n"
"        yi[i] = normed * (1.0f + scale[i]) + shift[i];\n"
"    }\n"
"}\n\n"

/* ---- Gated residual: dst[i] += gate[i % dim] * src[i] ---- */
/* Grid: ceil(n/256), Block: 256 */
"__global__ void gated_add_f32(\n"
"    float *dst, const float *src, const float *gate, int n, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) dst[i] += gate[i % dim] * src[i];\n"
"}\n\n"

/* ---- Modulation: out = SiLU(t_emb) @ W^T + bias + per_block_bias ---- */
/* t_emb: [dim], W: F16 [6*dim, dim], bias: [6*dim], blk_bias: [6*dim], out: [6*dim] */
/* Single block, 256 threads — small computation (one vector) */
"__global__ void modulation_f32(\n"
"    float *out, const float *t_emb, const float *mod_w, const float *mod_b,\n"
"    const float *blk_bias, int dim, int out_dim) {\n"
"    extern __shared__ float silu_emb[];\n"
"    /* Load t_emb into shared memory with SiLU applied */\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x)\n"
"        silu_emb[i] = t_emb[i] / (1.0f + expf(-t_emb[i]));\n"
"    __syncthreads();\n"
"    /* Each thread computes one output element */\n"
"    for (int r = threadIdx.x; r < out_dim; r += blockDim.x) {\n"
"        float sum = 0;\n"
"        const float *wr = mod_w + (size_t)r * dim;\n"
"        for (int j = 0; j < dim; j++) sum += wr[j] * silu_emb[j];\n"
"        sum += mod_b ? mod_b[r] : 0.0f;\n"
"        sum += blk_bias ? blk_bias[r] : 0.0f;\n"
"        out[r] = sum;\n"
"    }\n"
"}\n\n"

/* ---- 3D RoPE for dense grid (complex-pair convention) ---- */
/* Official TRELLIS.2: view_as_complex pairs (x[2k], x[2k+1]) then multiply by phase.
 * Phase layout: [n_freqs_z, n_freqs_y, n_freqs_x, padding] complex values.
 * rope_cos/sin: [N, 3, n_freqs] — per axis cos/sin of coord*freq.
 * Grid: N, Block: 256 (one thread per head) */
"__global__ void rope_3d_f32(\n"
"    float *data, const float *rope_cos, const float *rope_sin,\n"
"    int N, int dim, int n_heads, int head_dim,\n"
"    int n_freqs, int axis_dim) {\n"
"    int tok = blockIdx.x;\n"
"    if (tok >= N) return;\n"
"    float *v = data + (size_t)tok * dim;\n"
"    const float *cs = rope_cos + (size_t)tok * 3 * n_freqs;\n"
"    const float *sn = rope_sin + (size_t)tok * 3 * n_freqs;\n"
"    for (int h = threadIdx.x; h < n_heads; h += blockDim.x) {\n"
"        float *vh = v + h * head_dim;\n"
"        /* Complex-pair rotation: (vh[2k], vh[2k+1]) * (cos+i*sin) */\n"
"        int pair = 0;\n"
"        for (int axis = 0; axis < 3; axis++) {\n"
"            const float *ca = cs + axis * n_freqs;\n"
"            const float *sa = sn + axis * n_freqs;\n"
"            for (int j = 0; j < n_freqs; j++, pair++) {\n"
"                int idx = pair * 2;\n"
"                float re = vh[idx];\n"
"                float im = vh[idx + 1];\n"
"                vh[idx]     = re * ca[j] - im * sa[j];\n"
"                vh[idx + 1] = re * sa[j] + im * ca[j];\n"
"            }\n"
"        }\n"
"        /* remaining pairs (if head_dim/2 > 3*n_freqs): identity (no rotation) */\n"
"    }\n"
"}\n\n"

/* ---- Per-head RMSNorm with per-head gamma [n_heads, head_dim] ---- */
/* data: [n_tok, stride], gamma: [n_heads * head_dim] */
/* Grid: ceil(total_heads/256), Block: 256 — one thread per (tok, head) */
"__global__ void rms_norm_perhead_f32(\n"
"    float *data, const float *gamma,\n"
"    int n_tok, int n_heads, int head_dim, int stride, float eps) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = n_tok * n_heads;\n"
"    if (idx >= total) return;\n"
"    int tok = idx / n_heads;\n"
"    int h = idx % n_heads;\n"
"    float *v = data + (size_t)tok * stride + h * head_dim;\n"
"    const float *g = gamma + h * head_dim;\n"
"    float ss = 0;\n"
"    for (int i = 0; i < head_dim; i++) ss += v[i] * v[i];\n"
"    float rms = rsqrtf(ss / head_dim + eps);\n"
"    for (int i = 0; i < head_dim; i++) v[i] *= rms * g[i];\n"
"}\n\n"

/* ---- Dense Conv3D: k=3, pad=1, stride=1 ---- */
/* input: [Ci, D, H, W], weight: F32 [Co, Ci, 3, 3, 3], bias: [Co], output: [Co, D, H, W] */
/* Grid: (Co, D*H*W / 64), Block: 64 */
"__global__ void conv3d_k3_f32(\n"
"    float *out, const float *inp, const float *weight, const float *bias,\n"
"    int Ci, int Co, int D, int H, int W) {\n"
"    int co = blockIdx.x;\n"
"    int spatial_idx = blockIdx.y * blockDim.x + threadIdx.x;\n"
"    int spatial = D * H * W;\n"
"    if (co >= Co || spatial_idx >= spatial) return;\n"
"    int d = spatial_idx / (H * W);\n"
"    int h = (spatial_idx / W) % H;\n"
"    int w = spatial_idx % W;\n"
"    float sum = bias ? bias[co] : 0.0f;\n"
"    for (int ci = 0; ci < Ci; ci++) {\n"
"        const float *kern = weight + ((size_t)co * Ci + ci) * 27;\n"
"        for (int kd = 0; kd < 3; kd++) {\n"
"            int dd = d + kd - 1;\n"
"            if (dd < 0 || dd >= D) continue;\n"
"            for (int kh = 0; kh < 3; kh++) {\n"
"                int hh = h + kh - 1;\n"
"                if (hh < 0 || hh >= H) continue;\n"
"                for (int kw = 0; kw < 3; kw++) {\n"
"                    int ww = w + kw - 1;\n"
"                    if (ww < 0 || ww >= W) continue;\n"
"                    sum += kern[kd*9 + kh*3 + kw]\n"
"                         * inp[(size_t)ci * spatial + dd * H * W + hh * W + ww];\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    out[(size_t)co * spatial + spatial_idx] = sum;\n"
"}\n\n"

/* ---- GroupNorm 3D: [C, D, H, W] with G groups ---- */
/* Grid: G, Block: 256 */
"__global__ void groupnorm_3d_f32(\n"
"    float *dst, const float *src, const float *w, const float *b,\n"
"    int C, int spatial, int G) {\n"
"    int g = blockIdx.x;\n"
"    int cpg = C / G;\n"
"    int c_start = g * cpg;\n"
"    int n = cpg * spatial;\n"
"    float eps = 1e-5f;\n"
"    extern __shared__ float smem[];\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int i = threadIdx.x; i < n; i += blockDim.x) {\n"
"        int c = c_start + i / spatial;\n"
"        int s = i % spatial;\n"
"        float v = src[(size_t)c * spatial + s];\n"
"        sum += v; sum2 += v * v;\n"
"    }\n"
"    smem[threadIdx.x] = sum; smem[threadIdx.x + 256] = sum2;\n"
"    __syncthreads();\n"
"    for (int s = 128; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            smem[threadIdx.x] += smem[threadIdx.x + s];\n"
"            smem[threadIdx.x + 256] += smem[threadIdx.x + 256 + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = smem[0] / n;\n"
"    float var = smem[256] / n - mean * mean;\n"
"    float inv = rsqrtf(var + eps);\n"
"    for (int i = threadIdx.x; i < n; i += blockDim.x) {\n"
"        int c = c_start + i / spatial;\n"
"        int s = i % spatial;\n"
"        float normed = (src[(size_t)c * spatial + s] - mean) * inv;\n"
"        dst[(size_t)c * spatial + s] = normed * (w ? w[c] : 1.0f) + (b ? b[c] : 0.0f);\n"
"    }\n"
"}\n\n"

/* ---- SiLU in-place ---- */
"__global__ void silu_inplace_f32(float *x, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) x[i] = x[i] / (1.0f + expf(-x[i]));\n"
"}\n\n"

/* ---- pixel_shuffle_3d: [C*8, D, H, W] -> [C, 2D, 2H, 2W] ---- */
/* Grid: ceil(total/256), Block: 256 — total = C * 2D * 2H * 2W */
"__global__ void pixel_shuffle_3d_f32(\n"
"    float *dst, const float *src,\n"
"    int C, int D, int H, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int D2 = 2*D, H2 = 2*H, W2 = 2*W;\n"
"    int total = C * D2 * H2 * W2;\n"
"    if (idx >= total) return;\n"
"    int c = idx / (D2 * H2 * W2);\n"
"    int rem = idx % (D2 * H2 * W2);\n"
"    int od = rem / (H2 * W2);\n"
"    rem = rem % (H2 * W2);\n"
"    int oh = rem / W2;\n"
"    int ow = rem % W2;\n"
"    int d = od / 2, sd = od % 2;\n"
"    int h = oh / 2, sh = oh % 2;\n"
"    int w = ow / 2, sw = ow % 2;\n"
"    int src_ch = c * 8 + (sd * 2 + sh) * 2 + sw;\n"
"    int spatial_in = D * H * W;\n"
"    dst[idx] = src[(size_t)src_ch * spatial_in + d * H * W + h * W + w];\n"
"}\n\n"

/* ---- LayerNorm (no affine): y = (x - mean) / sqrt(var + eps) ---- */
/* Grid: N, Block: 256 */
"__global__ void layernorm_noaffine_f32(\n"
"    float *y, const float *x, int dim, float eps) {\n"
"    int tok = blockIdx.x;\n"
"    const float *xi = x + tok * dim;\n"
"    float *yi = y + tok * dim;\n"
"    extern __shared__ float smem[];\n"
"    float sum = 0, sum2 = 0;\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x) {\n"
"        float v = xi[i]; sum += v; sum2 += v * v;\n"
"    }\n"
"    smem[threadIdx.x] = sum; smem[threadIdx.x + 256] = sum2;\n"
"    __syncthreads();\n"
"    for (int s = 128; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            smem[threadIdx.x] += smem[threadIdx.x + s];\n"
"            smem[threadIdx.x + 256] += smem[threadIdx.x + 256 + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    float mean = smem[0] / dim;\n"
"    float var = smem[256] / dim - mean * mean;\n"
"    float inv = rsqrtf(var + eps);\n"
"    for (int i = threadIdx.x; i < dim; i += blockDim.x)\n"
"        yi[i] = (xi[i] - mean) * inv;\n"
"}\n\n"

/* ---- split_qkv_chunk_f32: split [N, 3*W] by chunk (NOT interleaved) ---- */
/* Input: [N, 3*W] where first W = Q, next W = K, last W = V */
/* Output: Q[N, W], K[N, W], V[N, W] */
"__global__ void split_qkv_chunk_f32(\n"
"    float *Q, float *K, float *V,\n"
"    const float *qkv, int N, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = N * W;\n"
"    if (idx >= total) return;\n"
"    int n = idx / W;\n"
"    int d = idx % W;\n"
"    int base = n * 3 * W;\n"
"    Q[idx] = qkv[base + d];\n"
"    K[idx] = qkv[base + W + d];\n"
"    V[idx] = qkv[base + 2*W + d];\n"
"}\n\n"

/* ---- split_kv_chunk_f32: split [M, 2*W] by chunk ---- */
"__global__ void split_kv_chunk_f32(\n"
"    float *K, float *V,\n"
"    const float *kv, int M, int W) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int total = M * W;\n"
"    if (idx >= total) return;\n"
"    int n = idx / W;\n"
"    int d = idx % W;\n"
"    int base = n * 2 * W;\n"
"    K[idx] = kv[base + d];\n"
"    V[idx] = kv[base + W + d];\n"
"}\n\n"

/* ---- timestep_embed_cossin_f32: sinusoidal embed with [cos, sin] order ---- */
/* TRELLIS.2 uses [cos, sin] while HY3D uses [sin, cos]. */
"__global__ void timestep_embed_cossin_f32(float *out, float t, int dim) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    int half = dim / 2;\n"
"    if (i >= half) return;\n"
"    float exponent = -logf(10000.0f) * (float)i / (float)half;\n"
"    float emb = expf(exponent) * t;\n"
"    out[i] = cosf(emb);\n"
"    out[half + i] = sinf(emb);\n"
"}\n\n"

"} /* close extern C from cuda_kernels_common */\n"
; /* end of kernel source string */

#endif /* CUDA_TRELLIS2_KERNELS_H */
