/* ============================================================================
 * cuda_fp8_mma_kernels.h -- Shared FP8 MMA GEMM + FP8 flash attention kernels
 * for hand-written PTX mma.sync on sm_89+ (with sm_120 a1/a2 fragment swap).
 *
 * Provides the following symbols inside the NVRTC module:
 *   fp8e4m3_to_f32         -- device helper (used by flash_attn_fp8_ref)
 *   gemm_fp8_scaled_f32    -- m16n8k32 FP8 MMA GEMM (F32 X, F32 Y), w_scale descale
 *   gemm_fp8_scaled_bf16   -- same, BF16 X pre-rounding (ComfyUI-matching)
 *   flash_attn_fp8         -- 4-warp CTA FP8 MMA flash attention (head_dim=128)
 *   flash_attn_fp8_ref     -- scalar reference for bisecting MMA bugs
 *   quantize_to_fp8_e4m3   -- per-tensor F32 -> e4m3 quantizer (with scale writeback)
 *   reduce_max_abs_f32     -- 1-pass atomic-max reduce to a single F32 slot
 *   zero_f32               -- small helper
 *
 * This file is duplicated from cuda/flux2/cuda_flux2_runner.h. Both copies must
 * stay in sync -- if a kernel changes in one place, update the other.
 *
 * Consumer pattern: include inside an extern "C" { ... } block in the NVRTC source
 * after a to_bf16(float) device fn has been declared (used by the _bf16 variant).
 * ============================================================================ */
#ifndef CUDA_FP8_MMA_KERNELS_H
#define CUDA_FP8_MMA_KERNELS_H

static const char *fp8_mma_kernels_src =
"\n/* ---- FP8 MMA kernels (shared by flux2 and qimg) ---- */\n"
"__device__ __forceinline__ float fp8e4m3_to_f32(unsigned char b) {\n"
"    int sign = (b >> 7) & 1;\n"
"    int exp  = (b >> 3) & 0xF;\n"
"    int mant = b & 0x7;\n"
"    float v;\n"
"    if (exp == 0 && mant == 0) return 0.0f;\n"
"    if (exp == 15 && mant == 7) return 0.0f;\n"  /* NaN -> 0 */
"    if (exp == 0) v = ((float)mant / 8.0f) * (1.0f / 64.0f);\n"  /* subnormal: 2^-6 */
"    else v = (1.0f + (float)mant / 8.0f) * exp2f((float)(exp - 7));\n"
"    return sign ? -v : v;\n"
"}\n"
"/* Truncate-toward-nearest-even f32 -> bf16 returning the raw 16-bit value.\n"
" * Defined here at the top of the source so all later kernels can use it. */\n"
"__device__ __forceinline__ unsigned short f32_to_bf16_bits(float f) {\n"
"    unsigned int b; memcpy(&b, &f, 4);\n"
"    if (((b >> 23) & 0xFF) == 0xFF && (b & 0x7FFFFF)) return 0x7FC0;\n"
"    unsigned int r = 0x7FFFu + ((b >> 16) & 1u);\n"
"    return (unsigned short)((b + r) >> 16);\n"
"}\n"

/* ============================================================
 * MMA-based FP8 GEMM (m16n8k32, sm_89+) with per-tensor weight scale.
 * Grid: (ceil(n_out/256), ceil(n_tok/16)), Block: 128 threads (4 warps).
 * Shared mem: 16 * 32 * sizeof(float) = 2048 bytes for X tile.
 * Each warp computes 16 rows x 64 cols of Y via 8 mma.sync issues.
 * sm_120 (Blackwell) has the a1/a2 fragment swap (same as cuda_kernels_common.h).
 * ============================================================ */
"#if __CUDA_ARCH__ >= 890\n"
"#define FP8_GEMM_NTILE 8\n"
"#define FP8_GEMM_MTILE 2   /* number of m16n8 M-tiles per CTA (32 rows) */\n"
"#define FP8_GEMM_NWARPS 4  /* warps per CTA (4 x 64 N = 256 N cols per CTA) */\n"
"__global__ void gemm_fp8_scaled_f32(float *Y, const unsigned char *W, const float *X,\n"
"                                     const float *bias, int n_out, int n_in, int n_tok,\n"
"                                     float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ float fp8_smem_x[];\n"
"    /* Per-tensor input scaling. If x_max_ptr is non-null, derive\n"
"     * x_scale = max(|X|) / 448 and divide X by x_scale at load time so\n"
"     * values fit in FP8 e4m3 range (+/-448) without saturating. Multiply\n"
"     * the F32 accumulator by x_scale at writeback to restore magnitude.\n"
"     * Matches torch._scaled_mm(input_fp8, weight_fp8, scale_input, 1). */\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) {\n"
"            x_scale     = mx / 448.0f;\n"
"            x_inv_scale = 448.0f / mx;\n"
"        }\n"
"    }\n"
"    /* sm_x: [FP8_GEMM_MTILE*16 rows x 32 K cols] = 1024 floats per iter */\n"
"    int tok_base = blockIdx.y * (16 * FP8_GEMM_MTILE);\n"
"    int warp_id = threadIdx.x / 32;\n"
"    /* Each warp covers NTILE x 8 N cols = 8*NTILE cols of output */\n"
"    int out_base = blockIdx.x * (8 * FP8_GEMM_NTILE * FP8_GEMM_NWARPS) + warp_id * (8 * FP8_GEMM_NTILE);\n"
"    int lane = threadIdx.x % 32;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane % 4;\n"
"    int tid = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    /* 2 M-tiles x 8 N-tiles x 4 f32 per thread = 64 f32 per lane */\n"
"    float d0[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d1[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d2[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d3[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < FP8_GEMM_NTILE; i++) {\n"
"            d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0;\n"
"        }\n"
"    }\n"
"\n"
"    int M_ROWS = 16 * FP8_GEMM_MTILE;\n"
"    for (int k = 0; k < n_in; k += 32) {\n"
"        /* Cooperative load M_ROWS x 32 K tile. 128 threads x 8 floats = 1024\n"
"         * floats per pass. For MTILE=2 (32 rows) one pass covers everything;\n"
"         * for MTILE=4 (64 rows) we iterate with a 32-row stride. */\n"
"        int scol = (tid & 3) * 8;\n"
"#pragma unroll\n"
"        for (int row_base = 0; row_base < M_ROWS; row_base += 32) {\n"
"            int srow = row_base + tid / 4;\n"
"            if (srow < M_ROWS) {\n"
"                int grow = tok_base + srow;\n"
"#pragma unroll\n"
"                for (int j = 0; j < 8; j++) {\n"
"                    float v = (grow < n_tok && k + scol + j < n_in)\n"
"                            ? X[(long)grow * n_in + k + scol + j] : 0.0f;\n"
"                    fp8_smem_x[srow * 32 + scol + j] = v * x_inv_scale;\n"
"                }\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"#define CVT_E4M3_PAIR(reg, r, c) \\\n"
"        { unsigned short lo, hi; \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)]), \"f\"(fp8_smem_x[(r)*32+(c)+1])); \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)+2]), \"f\"(fp8_smem_x[(r)*32+(c)+3])); \\\n"
"          reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"\n"
"        /* Load all A frags for each M-tile once (hoisted outside N-tile loop) */\n"
"        unsigned int a0[FP8_GEMM_MTILE], a1[FP8_GEMM_MTILE], a2[FP8_GEMM_MTILE], a3[FP8_GEMM_MTILE];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"            int mr = mt * 16;\n"
"            CVT_E4M3_PAIR(a0[mt], mr + gid,     tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid + 8, tid4*4)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid,     tid4*4 + 16)\n"
"#else\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid,     tid4*4 + 16)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid + 8, tid4*4)\n"
"#endif\n"
"            CVT_E4M3_PAIR(a3[mt], mr + gid + 8, tid4*4 + 16)\n"
"        }\n"
"#undef CVT_E4M3_PAIR\n"
"\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int bc = out_base + nt * 8 + gid;\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (bc < n_out && k + tid4*4 + 19 < n_in) {\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                b0 = *(const unsigned int *)(wp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(wp + tid4 * 4 + 16);\n"
"            } else if (bc < n_out) {\n"
"                unsigned char tmp[8] = {0,0,0,0,0,0,0,0};\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                for (int j = 0; j < 4; j++) {\n"
"                    int kk = k + tid4*4 + j;\n"
"                    if (kk < n_in) tmp[j] = wp[tid4*4 + j];\n"
"                    int kk2 = k + tid4*4 + 16 + j;\n"
"                    if (kk2 < n_in) tmp[4+j] = wp[tid4*4 + 16 + j];\n"
"                }\n"
"                b0 = ((unsigned int)tmp[0]) | ((unsigned int)tmp[1] << 8) | ((unsigned int)tmp[2] << 16) | ((unsigned int)tmp[3] << 24);\n"
"                b1 = ((unsigned int)tmp[4]) | ((unsigned int)tmp[5] << 8) | ((unsigned int)tmp[6] << 16) | ((unsigned int)tmp[7] << 24);\n"
"            }\n"
"\n"
"            /* Issue mma for each M-tile with shared B */\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            float sc = w_scale * x_scale;\n"
"            /* Fused BF16 truncation at writeback -- saves one full pass over\n"
"             * the output tensor (op_bf16_trunc) per GEMM. */\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] * sc + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] * sc + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] * sc + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] * sc + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* BF16-X sibling of gemm_fp8_scaled_f32.\n"
" *\n"
" * Mirrors the MTILE=2, 4-warp, per-tensor-input-scaled f32 kernel above with\n"
" * two differences:\n"
" *   (1) X is pre-rounded to BF16 at the smem load (match ComfyUI BF16 infer).\n"
" *   (2) Output is written as BF16-truncated F32 inline, saving the follow-on\n"
" *       op_bf16_trunc kernel launch.\n"
" *\n"
" * Same (Y, W, X, bias, n_out, n_in, n_tok, w_scale, x_max_ptr) signature as\n"
" * gemm_fp8_scaled_f32 so the runner can swap them 1:1. */\n"
"__global__ void gemm_fp8_scaled_bf16(float *Y, const unsigned char *W, const float *X,\n"
"                                      const float *bias, int n_out, int n_in, int n_tok,\n"
"                                      float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ float fp8_smem_x[];\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) {\n"
"            x_scale     = mx / 448.0f;\n"
"            x_inv_scale = 448.0f / mx;\n"
"        }\n"
"    }\n"
"    int tok_base = blockIdx.y * (16 * FP8_GEMM_MTILE);\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int out_base = blockIdx.x * (64 * FP8_GEMM_NWARPS) + warp_id * 64;\n"
"    int lane = threadIdx.x % 32;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane % 4;\n"
"    int tid = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    float d0[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d1[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d2[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d3[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < FP8_GEMM_NTILE; i++) {\n"
"            d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0;\n"
"        }\n"
"    }\n"
"\n"
"    int M_ROWS = 16 * FP8_GEMM_MTILE;\n"
"    for (int k = 0; k < n_in; k += 32) {\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        if (srow < M_ROWS) {\n"
"            int grow = tok_base + srow;\n"
"#pragma unroll\n"
"            for (int j = 0; j < 8; j++) {\n"
"                float v = (grow < n_tok && k + scol + j < n_in)\n"
"                        ? X[(long)grow * n_in + k + scol + j] : 0.0f;\n"
"                fp8_smem_x[srow * 32 + scol + j] = to_bf16(v * x_inv_scale);\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"#define CVT_E4M3_PAIR(reg, r, c) \\\n"
"        { unsigned short lo, hi; \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)]), \"f\"(fp8_smem_x[(r)*32+(c)+1])); \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)+2]), \"f\"(fp8_smem_x[(r)*32+(c)+3])); \\\n"
"          reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"\n"
"        unsigned int a0[FP8_GEMM_MTILE], a1[FP8_GEMM_MTILE], a2[FP8_GEMM_MTILE], a3[FP8_GEMM_MTILE];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"            int mr = mt * 16;\n"
"            CVT_E4M3_PAIR(a0[mt], mr + gid,     tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid + 8, tid4*4)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid,     tid4*4 + 16)\n"
"#else\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid,     tid4*4 + 16)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid + 8, tid4*4)\n"
"#endif\n"
"            CVT_E4M3_PAIR(a3[mt], mr + gid + 8, tid4*4 + 16)\n"
"        }\n"
"#undef CVT_E4M3_PAIR\n"
"\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int bc = out_base + nt * 8 + gid;\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (bc < n_out && k + tid4*4 + 19 < n_in) {\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                b0 = *(const unsigned int *)(wp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(wp + tid4 * 4 + 16);\n"
"            } else if (bc < n_out) {\n"
"                unsigned char tmp[8] = {0,0,0,0,0,0,0,0};\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                for (int j = 0; j < 4; j++) {\n"
"                    int kk = k + tid4*4 + j;\n"
"                    if (kk < n_in) tmp[j] = wp[tid4*4 + j];\n"
"                    int kk2 = k + tid4*4 + 16 + j;\n"
"                    if (kk2 < n_in) tmp[4+j] = wp[tid4*4 + 16 + j];\n"
"                }\n"
"                b0 = ((unsigned int)tmp[0]) | ((unsigned int)tmp[1] << 8) | ((unsigned int)tmp[2] << 16) | ((unsigned int)tmp[3] << 24);\n"
"                b1 = ((unsigned int)tmp[4]) | ((unsigned int)tmp[5] << 8) | ((unsigned int)tmp[6] << 16) | ((unsigned int)tmp[7] << 24);\n"
"            }\n"
"\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            float sc = w_scale * x_scale;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] * sc + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] * sc + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] * sc + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] * sc + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * Pipelined FP8 MMA GEMM -- same tile shape as gemm_fp8_scaled_f32
 * (MTILE=2 x NTILE=8 x 4 warps -> 32 rows x 256 N cols per CTA) but loads
 * W into shared memory via cp.async with a 2-stage double-buffered pipeline.
 *
 * The baseline kernel reads W directly from global memory on every MMA
 * iteration, which latency-stalls the tensor-core issue. Here each k-tile's
 * W slab (256 rows x 32 K bytes = 8 KB) is prefetched asynchronously into
 * smem while MMAs run on the current tile -- the GPU's load/store units and
 * tensor-core pipes run concurrently.
 *
 * Requires sm_80+ (cp.async). Requires n_in % 32 == 0, n_out % 256 == 0,
 * and n_tok >= 16 -- non-conforming shapes fall back to gemm_fp8_scaled_f32.
 * Signature matches the baseline so the runner can swap 1:1 at dispatch.
 * ============================================================================ */
"#if __CUDA_ARCH__ >= 800\n"
"__global__ __launch_bounds__(128, 5)\n"
"void gemm_fp8_scaled_f32_pipe(float *Y, const unsigned char *W, const float *X,\n"
"                               const float *bias, int n_out, int n_in, int n_tok,\n"
"                               float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ unsigned char fp8pipe_smem[];\n"
"    /* Layout: [X 32*32 e4m3 bytes = 1024 B][W stage 0 = 8192 B][W stage 1 = 8192 B]\n"
"     * Total 17408 B. X is pre-converted to e4m3 at load time so the MMA inner\n"
"     * loop reads FP8 bytes directly (no CVT). 3-stage buffering tried but hurt\n"
"     * perf (halved CTA/SM due to smem footprint). */\n"
"    unsigned char *smX  = fp8pipe_smem;\n"
"    unsigned char *smW0 = fp8pipe_smem + 1024;\n"
"    unsigned char *smW1 = fp8pipe_smem + 1024 + 8192;\n"
"\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) { x_scale = mx / 448.0f; x_inv_scale = 448.0f / mx; }\n"
"    }\n"
"    int tok_base = blockIdx.y * 32;    /* MTILE=2 -> 32 rows/CTA */\n"
"    int warp_id  = threadIdx.x / 32;\n"
"    int out_base_cta = blockIdx.x * 256;\n"
"    int out_base = out_base_cta + warp_id * 64;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid  = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    int tid  = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    float d0[2][8]; float d1[2][8]; float d2[2][8]; float d3[2][8];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < 2; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < 8; i++) { d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0; }\n"
"    }\n"
"\n"
"    int n_ktiles = n_in / 32;\n"
"\n"
"    /* Issue 4 cp.async.16 for one W tile (256 rows x 32 K bytes):\n"
"     * thread t -> 2 consecutive rows x 2 x 16-byte chunks. */\n"
"#define LOAD_W_TILE(smW_ptr, kt_val) do {\\\n"
"        int _k = (kt_val) * 32;\\\n"
"        int _r0 = 2 * tid;\\\n"
"        int _r1 = _r0 + 1;\\\n"
"        const unsigned char *_src0 = W + (size_t)(out_base_cta + _r0) * n_in + _k;\\\n"
"        const unsigned char *_src1 = W + (size_t)(out_base_cta + _r1) * n_in + _k;\\\n"
"        unsigned int _dst0 = (unsigned int)__cvta_generic_to_shared((smW_ptr) + _r0 * 32);\\\n"
"        unsigned int _dst1 = (unsigned int)__cvta_generic_to_shared((smW_ptr) + _r1 * 32);\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst0),      \"l\"(_src0));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst0 + 16), \"l\"(_src0 + 16));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst1),      \"l\"(_src1));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst1 + 16), \"l\"(_src1 + 16));\\\n"
"    } while (0)\n"
"\n"
"    /* Prologue: issue tile 0 (and tile 1 if it exists). */\n"
"    LOAD_W_TILE(smW0, 0);\n"
"    asm volatile(\"cp.async.commit_group;\\n\");\n"
"    if (n_ktiles > 1) {\n"
"        LOAD_W_TILE(smW1, 1);\n"
"        asm volatile(\"cp.async.commit_group;\\n\");\n"
"    }\n"
"\n"
"    for (int kt = 0; kt < n_ktiles; kt++) {\n"
"        int k = kt * 32;\n"
"        unsigned char *smW_cur = (kt & 1) ? smW1 : smW0;\n"
"\n"
"        /* Load X tile synchronously and pre-convert to e4m3 bytes in smem.\n"
"         * 128 threads x 8 floats = 1024 floats per pass. 2 x float4 loads per\n"
"         * lane -- n_in is divisible by 32 (gate), so the 16-byte alignment holds. */\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        int grow = tok_base + srow;\n"
"        float xv[8];\n"
"        if (grow < n_tok) {\n"
"            const float4 *xp = (const float4 *)&X[(long)grow * n_in + k + scol];\n"
"            float4 v0 = xp[0];\n"
"            float4 v1 = xp[1];\n"
"            xv[0] = v0.x * x_inv_scale; xv[1] = v0.y * x_inv_scale;\n"
"            xv[2] = v0.z * x_inv_scale; xv[3] = v0.w * x_inv_scale;\n"
"            xv[4] = v1.x * x_inv_scale; xv[5] = v1.y * x_inv_scale;\n"
"            xv[6] = v1.z * x_inv_scale; xv[7] = v1.w * x_inv_scale;\n"
"        } else {\n"
"            xv[0]=0; xv[1]=0; xv[2]=0; xv[3]=0; xv[4]=0; xv[5]=0; xv[6]=0; xv[7]=0;\n"
"        }\n"
"        unsigned short p0, p1, p2, p3;\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p0) : \"f\"(xv[0]), \"f\"(xv[1]));\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p1) : \"f\"(xv[2]), \"f\"(xv[3]));\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p2) : \"f\"(xv[4]), \"f\"(xv[5]));\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p3) : \"f\"(xv[6]), \"f\"(xv[7]));\n"
"        unsigned int pack0 = (unsigned int)p0 | ((unsigned int)p1 << 16);\n"
"        unsigned int pack1 = (unsigned int)p2 | ((unsigned int)p3 << 16);\n"
"        *(unsigned int *)(smX + srow * 32 + scol     ) = pack0;\n"
"        *(unsigned int *)(smX + srow * 32 + scol +  4) = pack1;\n"
"\n"
"        /* Wait for our W tile. Keep one ahead while possible. */\n"
"        if (n_ktiles - kt >= 2) {\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\");\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* Build A frags via ldmatrix.sync.aligned.m8n8.x4 -- hardware-accelerated\n"
"         * lane-permuted load that replaces 8 per-lane u32 smem reads with one\n"
"         * warp-wide instruction. The x4 variant loads 4 x 8x8 b16 sub-matrices\n"
"         * that together tile a 16x32 FP8 A fragment (= one MTILE). */\n"
"        unsigned int a0[2], a1[2], a2[2], a3[2];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < 2; mt++) {\n"
"            int mr = mt * 16;\n"
"            int row_in_A = ((lane & 16) ? 8 : 0) + (lane & 7);\n"
"            int col_in_A = (lane & 8) ? 16 : 0;\n"
"            unsigned int sa = (unsigned int)__cvta_generic_to_shared(\n"
"                smX + (mr + row_in_A) * 32 + col_in_A);\n"
"            unsigned int ra, rb, rc, rd;\n"
"            asm(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\"\n"
"                : \"=r\"(ra), \"=r\"(rb), \"=r\"(rc), \"=r\"(rd) : \"r\"(sa));\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            /* sm_120 fragment swap: mma wants {m00, m10, m01, m11}. */\n"
"            a0[mt] = ra; a1[mt] = rc; a2[mt] = rb; a3[mt] = rd;\n"
"#else\n"
"            a0[mt] = ra; a1[mt] = rb; a2[mt] = rc; a3[mt] = rd;\n"
"#endif\n"
"        }\n"
"\n"
"        /* N-tile loop reading B frags from smW_cur. */\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < 8; nt++) {\n"
"            int bc_local = warp_id * 64 + nt * 8 + gid;   /* 0..255 */\n"
"            const unsigned char *bp = smW_cur + bc_local * 32 + tid4 * 4;\n"
"            unsigned int b0 = *(const unsigned int *)bp;\n"
"            unsigned int b1 = *(const unsigned int *)(bp + 16);\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < 2; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"        /* Prefetch tile kt+2 (into the slot we just finished reading). */\n"
"        if (kt + 2 < n_ktiles) {\n"
"            unsigned char *smW_next = ((kt + 2) & 1) ? smW1 : smW0;\n"
"            LOAD_W_TILE(smW_next, kt + 2);\n"
"            asm volatile(\"cp.async.commit_group;\\n\");\n"
"        }\n"
"\n"
"        __syncthreads();\n"
"    }\n"
"#undef LOAD_W_TILE\n"
"\n"
"    /* Writeback -- identical to gemm_fp8_scaled_f32 with fused bf16 trunc. */\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < 2; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < 8; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            float sc = w_scale * x_scale;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] * sc + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] * sc + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] * sc + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] * sc + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * Per-row FP8 MMA pipelined GEMM. Same kernel structure as the per-tensor pipe
 * variant above, but each output row gets its own X scale. The caller passes
 * a [n_tok] float array of per-row max(|X|) values (computed via
 * reduce_max_abs_per_row_f32). Each row r uses inv_scale[r] = 448/max(|X[r]|)
 * during the X->FP8 quant, and scale[r] = max[r]/448 at writeback.
 *
 * Why this matters: the per-tensor variant compresses ALL rows to the global
 * max, which crushes precision in rows whose max is much smaller than the
 * outlier rows. Per-row scaling lets each row use its own dynamic range,
 * dropping the pixel_mean blur from ~1.81 (per-tensor) to ~1.0 (per-row) at
 * zero speed cost vs the per-tensor pipe (one extra reduce launch per call,
 * which is much faster than reading the full X tensor once for the MMA).
 *
 * The 32 row scales (one per row of the CTA's M-window) are loaded into
 * shared memory at kernel entry so any lane can read any row's scale at
 * writeback time without strided global loads.
 * ============================================================================ */
"#if __CUDA_ARCH__ >= 800\n"
"__global__ __launch_bounds__(128, 5)\n"
"void gemm_fp8_pipe_perrow_f32(float *Y, const unsigned char *W, const float *X,\n"
"                               const float *bias, int n_out, int n_in, int n_tok,\n"
"                               float w_scale, const float *row_max) {\n"
"    extern __shared__ unsigned char fp8perrow_smem[];\n"
"    /* Layout: smX 1 KB FP8 + smW stage 0 8 KB + smW stage 1 8 KB + smRowScale 256 B = 17.25 KB */\n"
"    unsigned char *smX  = fp8perrow_smem;\n"
"    unsigned char *smW0 = fp8perrow_smem + 1024;\n"
"    unsigned char *smW1 = fp8perrow_smem + 1024 + 8192;\n"
"    /* 32 row scales (per-row inv_scale = 448/max) and 32 fwd scales (max/448).\n"
"     * Stored as F32 = 32 * 4 = 128 B each = 256 B total. */\n"
"    float *smInvScale = (float *)(fp8perrow_smem + 1024 + 8192 + 8192);\n"
"    float *smFwdScale = smInvScale + 32;\n"
"\n"
"    int tok_base = blockIdx.y * 32;\n"
"    int warp_id  = threadIdx.x / 32;\n"
"    int out_base_cta = blockIdx.x * 256;\n"
"    int out_base = out_base_cta + warp_id * 64;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid  = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    int tid  = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    /* Cooperatively load 32 row scales for this CTA into smem. */\n"
"    if (tid < 32) {\n"
"        int r = tok_base + tid;\n"
"        float mx = (r < n_tok) ? row_max[r] : 0.0f;\n"
"        float fwd, inv;\n"
"        if (mx > 1e-6f) { fwd = mx / 448.0f; inv = 448.0f / mx; }\n"
"        else            { fwd = 1.0f;       inv = 1.0f;       }\n"
"        smInvScale[tid] = inv;\n"
"        smFwdScale[tid] = fwd;\n"
"    }\n"
"    __syncthreads();\n"
"\n"
"    float d0[2][8]; float d1[2][8]; float d2[2][8]; float d3[2][8];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < 2; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < 8; i++) { d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0; }\n"
"    }\n"
"\n"
"    int n_ktiles = n_in / 32;\n"
"\n"
"#define LOAD_W_TILE_PR(smW_ptr, kt_val) do {\\\n"
"        int _k = (kt_val) * 32;\\\n"
"        int _r0 = 2 * tid;\\\n"
"        int _r1 = _r0 + 1;\\\n"
"        const unsigned char *_src0 = W + (size_t)(out_base_cta + _r0) * n_in + _k;\\\n"
"        const unsigned char *_src1 = W + (size_t)(out_base_cta + _r1) * n_in + _k;\\\n"
"        unsigned int _dst0 = (unsigned int)__cvta_generic_to_shared((smW_ptr) + _r0 * 32);\\\n"
"        unsigned int _dst1 = (unsigned int)__cvta_generic_to_shared((smW_ptr) + _r1 * 32);\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst0),      \"l\"(_src0));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst0 + 16), \"l\"(_src0 + 16));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst1),      \"l\"(_src1));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst1 + 16), \"l\"(_src1 + 16));\\\n"
"    } while (0)\n"
"\n"
"    LOAD_W_TILE_PR(smW0, 0);\n"
"    asm volatile(\"cp.async.commit_group;\\n\");\n"
"    if (n_ktiles > 1) {\n"
"        LOAD_W_TILE_PR(smW1, 1);\n"
"        asm volatile(\"cp.async.commit_group;\\n\");\n"
"    }\n"
"\n"
"    for (int kt = 0; kt < n_ktiles; kt++) {\n"
"        int k = kt * 32;\n"
"        unsigned char *smW_cur = (kt & 1) ? smW1 : smW0;\n"
"\n"
"        /* Load X tile and pre-quant to FP8 with PER-ROW scale. */\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        int grow = tok_base + srow;\n"
"        float x_inv = smInvScale[srow];  /* per-row scale lookup */\n"
"        float xv[8];\n"
"        if (grow < n_tok) {\n"
"            const float4 *xp = (const float4 *)&X[(long)grow * n_in + k + scol];\n"
"            float4 v0 = xp[0]; float4 v1 = xp[1];\n"
"            xv[0]=v0.x*x_inv; xv[1]=v0.y*x_inv; xv[2]=v0.z*x_inv; xv[3]=v0.w*x_inv;\n"
"            xv[4]=v1.x*x_inv; xv[5]=v1.y*x_inv; xv[6]=v1.z*x_inv; xv[7]=v1.w*x_inv;\n"
"        } else {\n"
"            xv[0]=0;xv[1]=0;xv[2]=0;xv[3]=0;xv[4]=0;xv[5]=0;xv[6]=0;xv[7]=0;\n"
"        }\n"
"        unsigned short p0, p1, p2, p3;\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p0) : \"f\"(xv[0]), \"f\"(xv[1]));\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p1) : \"f\"(xv[2]), \"f\"(xv[3]));\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p2) : \"f\"(xv[4]), \"f\"(xv[5]));\n"
"        asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(p3) : \"f\"(xv[6]), \"f\"(xv[7]));\n"
"        unsigned int pack0 = (unsigned int)p0 | ((unsigned int)p1 << 16);\n"
"        unsigned int pack1 = (unsigned int)p2 | ((unsigned int)p3 << 16);\n"
"        *(unsigned int *)(smX + srow * 32 + scol     ) = pack0;\n"
"        *(unsigned int *)(smX + srow * 32 + scol +  4) = pack1;\n"
"\n"
"        if (n_ktiles - kt >= 2) {\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\");\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* A frags via ldmatrix from smX (FP8 bytes). */\n"
"        unsigned int a0[2], a1[2], a2[2], a3[2];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < 2; mt++) {\n"
"            int mr = mt * 16;\n"
"            int row_in_A = ((lane & 16) ? 8 : 0) + (lane & 7);\n"
"            int col_in_A = (lane & 8) ? 16 : 0;\n"
"            unsigned int sa = (unsigned int)__cvta_generic_to_shared(\n"
"                smX + (mr + row_in_A) * 32 + col_in_A);\n"
"            unsigned int ra, rb, rc, rd;\n"
"            asm(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\"\n"
"                : \"=r\"(ra), \"=r\"(rb), \"=r\"(rc), \"=r\"(rd) : \"r\"(sa));\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            a0[mt] = ra; a1[mt] = rc; a2[mt] = rb; a3[mt] = rd;\n"
"#else\n"
"            a0[mt] = ra; a1[mt] = rb; a2[mt] = rc; a3[mt] = rd;\n"
"#endif\n"
"        }\n"
"\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < 8; nt++) {\n"
"            int bc_local = warp_id * 64 + nt * 8 + gid;\n"
"            const unsigned char *bp = smW_cur + bc_local * 32 + tid4 * 4;\n"
"            unsigned int b0 = *(const unsigned int *)bp;\n"
"            unsigned int b1 = *(const unsigned int *)(bp + 16);\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < 2; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"        if (kt + 2 < n_ktiles) {\n"
"            unsigned char *smW_next = ((kt + 2) & 1) ? smW1 : smW0;\n"
"            LOAD_W_TILE_PR(smW_next, kt + 2);\n"
"            asm volatile(\"cp.async.commit_group;\\n\");\n"
"        }\n"
"\n"
"        __syncthreads();\n"
"    }\n"
"#undef LOAD_W_TILE_PR\n"
"\n"
"    /* Writeback with PER-ROW scale. Each lane reads its 2 row scales from smem. */\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < 2; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"        float sc0 = w_scale * smFwdScale[mr + gid];\n"
"        float sc1 = w_scale * smFwdScale[mr + gid + 8];\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < 8; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] * sc0 + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] * sc0 + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] * sc1 + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] * sc1 + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * 128x128 tiled FP8 MMA GEMM -- CUDA-C port of gemm_fp8_tc128_e4m3 from
 * cuda/fp8/fp8_gemm.c, adapted for qwen-image's transposed W layout
 * (Y[tok,n_out] = X[tok,n_in] @ W[n_out,n_in]^T).
 *
 * CTA tile: 128 rows x 128 cols, 16 warps (512 threads) arranged in a 4x4 grid.
 * Each warp computes 32 x 32 via 8 m16n8k32 MMAs (2 M-tiles x 4 N-tiles of 16x8).
 * Shared mem: 128 x 32 f32 = 16 KB for X tile (cvt to e4m3 at MMA load time).
 *
 * Feature parity with gemm_fp8_scaled_f32: bias, per-tensor w_scale,
 * per-tensor input scaling via x_max_ptr. Output is F32; downstream pipeline
 * applies op_bf16_trunc like the MTILE=2 sibling. Note: the sandbox kernel's
 * comment claims 128x128 but the 4 MMAs/warp only cover 32x16 per warp -> the
 * sandbox effective CTA is 128x64. This port fills in the missing 4 MMAs so
 * the CTA is actually 128x128 as advertised.
 * ============================================================================ */
"#if __CUDA_ARCH__ >= 890\n"
"#define TC128_MWARPS 4     /* warp grid M-dim */\n"
"#define TC128_NWARPS_N 4   /* warp grid N-dim */\n"
"#define TC128_WARP_M 2     /* M-tiles per warp */\n"
"#define TC128_WARP_N 4     /* N-tiles per warp */\n"
"__global__ void gemm_fp8_scaled_tc128_f32(float *Y, const unsigned char *W,\n"
"                                           const float *X, const float *bias,\n"
"                                           int n_out, int n_in, int n_tok,\n"
"                                           float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ float fp8_smem_x[];\n"
"    /* Per-tensor input scaling -- same as gemm_fp8_scaled_f32. */\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) {\n"
"            x_scale     = mx / 448.0f;\n"
"            x_inv_scale = 448.0f / mx;\n"
"        }\n"
"    }\n"
"    int tok_base = blockIdx.y * 128;\n"
"    int out_base = blockIdx.x * 128;\n"
"    int warp_id  = threadIdx.x / 32;\n"
"    int lane     = threadIdx.x % 32;\n"
"    int gid      = lane / 4;\n"
"    int tid4     = lane % 4;\n"
"    int tid      = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    /* Warp position in 4x4 grid: warp_m = warp_id & 3, warp_n = warp_id >> 2 */\n"
"    int warp_m_base = (warp_id & 3) * 32;\n"
"    int warp_n_base = (warp_id >> 2) * 32;\n"
"\n"
"    /* 2 M-tiles x 4 N-tiles x 4 f32 = 32 f32 accumulators per lane */\n"
"    float d0[TC128_WARP_M][TC128_WARP_N];\n"
"    float d1[TC128_WARP_M][TC128_WARP_N];\n"
"    float d2[TC128_WARP_M][TC128_WARP_N];\n"
"    float d3[TC128_WARP_M][TC128_WARP_N];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < TC128_WARP_N; nt++) {\n"
"            d0[mt][nt]=0; d1[mt][nt]=0; d2[mt][nt]=0; d3[mt][nt]=0;\n"
"        }\n"
"    }\n"
"\n"
"    for (int k = 0; k < n_in; k += 32) {\n"
"        /* Cooperative X load: 128 rows x 32 cols = 4096 f32.\n"
"         * 512 threads x 8 f32 = 4096. tid -> row = tid/4, col = (tid%4)*8. */\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        int grow = tok_base + srow;\n"
"#pragma unroll\n"
"        for (int j = 0; j < 8; j++) {\n"
"            float v = (grow < n_tok && k + scol + j < n_in)\n"
"                    ? X[(long)grow * n_in + k + scol + j] : 0.0f;\n"
"            fp8_smem_x[srow * 32 + scol + j] = v * x_inv_scale;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"#define CVT_E4M3_PAIR(reg, r, c) \\\n"
"        { unsigned short lo, hi; \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)]), \"f\"(fp8_smem_x[(r)*32+(c)+1])); \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)+2]), \"f\"(fp8_smem_x[(r)*32+(c)+3])); \\\n"
"          reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"\n"
"        /* Hoist A frags for this warp's 2 M-tiles */\n"
"        unsigned int a0[TC128_WARP_M], a1[TC128_WARP_M], a2[TC128_WARP_M], a3[TC128_WARP_M];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"            int mr = warp_m_base + mt * 16;\n"
"            CVT_E4M3_PAIR(a0[mt], mr + gid,     tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid + 8, tid4*4)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid,     tid4*4 + 16)\n"
"#else\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid,     tid4*4 + 16)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid + 8, tid4*4)\n"
"#endif\n"
"            CVT_E4M3_PAIR(a3[mt], mr + gid + 8, tid4*4 + 16)\n"
"        }\n"
"#undef CVT_E4M3_PAIR\n"
"\n"
"        /* For each N-tile: read B frags directly from W (global), then issue\n"
"         * MMA for all M-tiles with that shared B. */\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < TC128_WARP_N; nt++) {\n"
"            int bc = out_base + warp_n_base + nt * 8 + gid;\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (bc < n_out && k + tid4*4 + 19 < n_in) {\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                b0 = *(const unsigned int *)(wp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(wp + tid4 * 4 + 16);\n"
"            } else if (bc < n_out) {\n"
"                unsigned char tmp[8] = {0,0,0,0,0,0,0,0};\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                for (int j = 0; j < 4; j++) {\n"
"                    int kk = k + tid4*4 + j;\n"
"                    if (kk < n_in) tmp[j] = wp[tid4*4 + j];\n"
"                    int kk2 = k + tid4*4 + 16 + j;\n"
"                    if (kk2 < n_in) tmp[4+j] = wp[tid4*4 + 16 + j];\n"
"                }\n"
"                b0 = ((unsigned int)tmp[0]) | ((unsigned int)tmp[1] << 8) | ((unsigned int)tmp[2] << 16) | ((unsigned int)tmp[3] << 24);\n"
"                b1 = ((unsigned int)tmp[4]) | ((unsigned int)tmp[5] << 8) | ((unsigned int)tmp[6] << 16) | ((unsigned int)tmp[7] << 24);\n"
"            }\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    float sc = w_scale * x_scale;\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"        int mr = warp_m_base + mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < TC128_WARP_N; nt++) {\n"
"            int yc0 = out_base + warp_n_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = d0[mt][nt] * sc + bv0;\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = d1[mt][nt] * sc + bv1;\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = d2[mt][nt] * sc + bv0;\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = d3[mt][nt] * sc + bv1;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * FP8 Flash Attention helper: F32 -> e4m3 quantization with shared per-tensor
 * scale. Two-pass: caller pre-zeroes max_buf, then runs reduce_max_abs_f32 to
 * compute max, then quantize_to_fp8_e4m3 to write the FP8 buffer + scale.
 * ============================================================================ */
"__global__ void zero_f32(float *p, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) p[i] = 0.0f;\n"
"}\n"

"__global__ void reduce_max_abs_f32(float *out_max, const float *in, int n) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= n) return;\n"
"    float v = fabsf(in[idx]);\n"
"    /* warp reduce */\n"
"    for (int off = 16; off > 0; off >>= 1) {\n"
"        float other = __shfl_xor_sync(0xFFFFFFFF, v, off);\n"
"        if (other > v) v = other;\n"
"    }\n"
"    if ((threadIdx.x & 31) == 0 && v > 0.0f) {\n"
"        /* atomicMax on int interpretation works for non-negative IEEE f32 */\n"
"        int new_int; memcpy(&new_int, &v, 4);\n"
"        atomicMax((int*)out_max, new_int);\n"
"    }\n"
"}\n"

/* Per-row max(|X|) reducer. One CTA per row, 256 threads stride over the row.
 * Output: out_max[r] = max(|X[r, 0..n_in-1]|). Used by the per-row FP8 MMA
 * variant to compute one quantization scale per output row, eliminating the
 * outlier crush of the per-tensor scale. */
"__global__ void reduce_max_abs_per_row_f32(float *out_max, const float *X,\n"
"                                            int n_tok, int n_in) {\n"
"    int row = blockIdx.x;\n"
"    if (row >= n_tok) return;\n"
"    const float *xr = X + (long)row * n_in;\n"
"    float v = 0.0f;\n"
"    for (int i = threadIdx.x; i < n_in; i += blockDim.x) {\n"
"        float a = fabsf(xr[i]);\n"
"        if (a > v) v = a;\n"
"    }\n"
"    /* warp reduce */\n"
"    for (int off = 16; off > 0; off >>= 1) {\n"
"        float other = __shfl_xor_sync(0xFFFFFFFF, v, off);\n"
"        if (other > v) v = other;\n"
"    }\n"
"    /* cross-warp via shared mem */\n"
"    __shared__ float warp_max[8];\n"
"    int wid = threadIdx.x / 32;\n"
"    if ((threadIdx.x & 31) == 0) warp_max[wid] = v;\n"
"    __syncthreads();\n"
"    if (wid == 0) {\n"
"        v = (threadIdx.x < (blockDim.x / 32)) ? warp_max[threadIdx.x] : 0.0f;\n"
"        for (int off = 16; off > 0; off >>= 1) {\n"
"            float other = __shfl_xor_sync(0xFFFFFFFF, v, off);\n"
"            if (other > v) v = other;\n"
"        }\n"
"        if (threadIdx.x == 0) out_max[row] = v;\n"
"    }\n"
"}\n"

"__global__ void quantize_to_fp8_e4m3(unsigned char *out, float *out_scale,\n"
"                                      const float *in, const float *max_buf, int n) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    float max_abs = max_buf[0];\n"
"    float scale = (max_abs > 1e-30f) ? (max_abs / 448.0f) : 1.0f;\n"
"    if (idx == 0) *out_scale = scale;\n"
"    if (idx >= n) return;\n"
"    float v = in[idx] / scale;\n"
"    unsigned short pair;\n"
"    /* d=pair, a=0, b=v -> low byte = e4m3(v), high byte = e4m3(0) */\n"
"    asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %1, %2;\" : \"=h\"(pair) : \"f\"(0.0f), \"f\"(v));\n"
"    out[idx] = (unsigned char)(pair & 0xFF);\n"
"}\n"

/* ============================================================================
 * FP8 Flash Attention (mma.sync m16n8k32 e4m3, sm_89+).
 * 1 warp per CTA, 16 Q rows per CTA, BKV=32 KV tile.
 * Grid: (n_heads, ceil(N/16))
 * Block: 32 threads (1 warp)
 * Shared: K[32,128] + V_T[128,32] + P[16,32 f32] = 4KB+4KB+2KB = 10KB
 *
 * Q,K,V: [N, n_heads, head_dim] uint8 e4m3 with per-tensor scales sQ, sK, sV.
 * P scale = 1/448 (P after softmax is in (0,1], use full e4m3 range).
 * ============================================================================ */
/* Scalar reference: same FP8 buffers, scalar dot products. Used as a debug
 * cross-check for the MMA version. Same launch params. */
"__global__ void flash_attn_fp8_ref(\n"
"    float *__restrict__ out,\n"
"    const unsigned char *__restrict__ Qb,\n"
"    const unsigned char *__restrict__ Kb,\n"
"    const unsigned char *__restrict__ Vb,\n"
"    int N, int n_heads, int head_dim,\n"
"    const float *__restrict__ scales) {\n"
"    float sQ = scales[0], sK = scales[1], sV = scales[2];\n"
"    int h = blockIdx.x;\n"
"    int qi = blockIdx.y * 32 + threadIdx.x;  /* one Q row per thread */\n"
"    if (qi >= N) return;\n"
"    int dim = n_heads * head_dim;\n"
"    /* Dequantize Q row to local f32 (head_dim=128) */\n"
"    float q_loc[128];\n"
"    for (int d = 0; d < head_dim; d++)\n"
"        q_loc[d] = (float)Qb[(long)qi * dim + h * head_dim + d] * 0.0f;\n"
"    /* Above is just a placeholder; do real dequant via cvt */\n"
"    for (int d = 0; d < head_dim; d++) {\n"
"        unsigned char b = Qb[(long)qi * dim + h * head_dim + d];\n"
"        q_loc[d] = fp8e4m3_to_f32(b) * sQ;\n"
"    }\n"
"    float scale = rsqrtf((float)head_dim);\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_loc[128];\n"
"    for (int d = 0; d < head_dim; d++) O_loc[d] = 0.0f;\n"
"    for (int kj = 0; kj < N; kj++) {\n"
"        float dot = 0.0f;\n"
"        for (int d = 0; d < head_dim; d++) {\n"
"            unsigned char b = Kb[(long)kj * dim + h * head_dim + d];\n"
"            dot += q_loc[d] * (fp8e4m3_to_f32(b) * sK);\n"
"        }\n"
"        float score = dot * scale;\n"
"        float new_m = fmaxf(m_i, score);\n"
"        float alpha = expf(m_i - new_m);\n"
"        float p = expf(score - new_m);\n"
"        l_i = l_i * alpha + p;\n"
"        for (int d = 0; d < head_dim; d++) {\n"
"            unsigned char b = Vb[(long)kj * dim + h * head_dim + d];\n"
"            O_loc[d] = O_loc[d] * alpha + p * (fp8e4m3_to_f32(b) * sV);\n"
"        }\n"
"        m_i = new_m;\n"
"    }\n"
"    float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"    for (int d = 0; d < head_dim; d++)\n"
"        out[(long)qi * dim + h * head_dim + d] = O_loc[d] * inv_l;\n"
"}\n"

"#if __CUDA_ARCH__ >= 890\n"
"#define FAFP8_BKV    32\n"
"#define FAFP8_M      16\n"
"#define FAFP8_HD    128\n"
"#define FAFP8_NWARPS 4\n"
"__global__ void flash_attn_fp8(\n"
"    float *__restrict__ out,\n"
"    const unsigned char *__restrict__ Qb,\n"
"    const unsigned char *__restrict__ Kb,\n"
"    const unsigned char *__restrict__ Vb,\n"
"    int N, int n_heads, int head_dim,\n"
"    const float *__restrict__ scales) {\n"
"    float sQ = scales[0], sK = scales[1], sV = scales[2];\n"
"    int h = blockIdx.x;\n"
"    int warp = threadIdx.x / 32;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    /* Each warp owns its own 16 Q rows (block covers 64 Q rows total) */\n"
"    int q_base = blockIdx.y * (FAFP8_M * FAFP8_NWARPS) + warp * FAFP8_M;\n"
"    int dim = n_heads * head_dim;\n"
"\n"
"    /* ----- Load Q into A-fragment registers (4 K-chunks of 32) ----- */\n"
"    unsigned int q_frag[4][4];\n"
"#pragma unroll\n"
"    for (int kc = 0; kc < 4; kc++) {\n"
"        int k0 = kc * 32;\n"
"        int row0 = q_base + gid;\n"
"        int row1 = q_base + gid + 8;\n"
"        const unsigned char *qbase0 = (row0 < N) ? Qb + (long)row0 * dim + h * head_dim : (const unsigned char *)0;\n"
"        const unsigned char *qbase1 = (row1 < N) ? Qb + (long)row1 * dim + h * head_dim : (const unsigned char *)0;\n"
"        unsigned int z = 0;\n"
"        q_frag[kc][0] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*4)      : z;\n"
"#if __CUDA_ARCH__ >= 1200\n"
"        q_frag[kc][1] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*4)      : z;\n"
"        q_frag[kc][2] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*4 + 16) : z;\n"
"#else\n"
"        q_frag[kc][1] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*4 + 16) : z;\n"
"        q_frag[kc][2] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*4)      : z;\n"
"#endif\n"
"        q_frag[kc][3] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*4 + 16) : z;\n"
"    }\n"
"\n"
"    /* O accumulator: 16 N-iters (head_dim=128 / N=8) x 4 floats per thread per N-iter */\n"
"    float O[16][4];\n"
"#pragma unroll\n"
"    for (int i = 0; i < 16; i++) {\n"
"        O[i][0] = 0.0f; O[i][1] = 0.0f; O[i][2] = 0.0f; O[i][3] = 0.0f;\n"
"    }\n"
"    /* Per-row state (each thread has 2 row groups: gid, gid+8) */\n"
"    float m_state[2] = {-1e30f, -1e30f};\n"
"    float l_state[2] = {0.0f, 0.0f};\n"
"\n"
"    float qk_scale = sQ * sK * rsqrtf((float)head_dim);\n"
"\n"
"    extern __shared__ unsigned char fa_smem[];\n"
"    unsigned char *smK  = fa_smem;                                               /* [BKV, hd] */\n"
"    unsigned char *smVT = smK + FAFP8_BKV * FAFP8_HD;                            /* [hd, BKV] */\n"
"    float *smP_all = (float*)(smVT + FAFP8_HD * FAFP8_BKV);                      /* [NWARPS * 16 * BKV] */\n"
"    float *smP = smP_all + warp * 16 * FAFP8_BKV;                                /* this warp's slice */\n"
"\n"
"    int n_kv_tiles = (N + FAFP8_BKV - 1) / FAFP8_BKV;\n"
"    for (int kvt = 0; kvt < n_kv_tiles; kvt++) {\n"
"        int kv_base = kvt * FAFP8_BKV;\n"
"\n"
"        /* Cooperative load: K row-major [BKV, hd], V transposed [hd, BKV]. All 128 threads. */\n"
"        for (int idx = threadIdx.x; idx < FAFP8_BKV * FAFP8_HD; idx += FAFP8_NWARPS * 32) {\n"
"            int kr = idx / FAFP8_HD, kd = idx % FAFP8_HD;\n"
"            int row = kv_base + kr;\n"
"            unsigned char kk = (row < N) ? Kb[(long)row * dim + h * head_dim + kd] : 0;\n"
"            unsigned char vv = (row < N) ? Vb[(long)row * dim + h * head_dim + kd] : 0;\n"
"            smK[kr * FAFP8_HD + kd] = kk;\n"
"            smVT[kd * FAFP8_BKV + kr] = vv;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* S = Q . K^T : [16, BKV=32]. 4 N-iters of m16n8k32, 4 K-chunks per. */\n"
"        float S[4][4];\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            S[ni][0] = 0.0f; S[ni][1] = 0.0f; S[ni][2] = 0.0f; S[ni][3] = 0.0f;\n"
"        }\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int n_base = ni * 8;\n"
"            int b_col = n_base + gid;  /* col of mma B = row of K in smK */\n"
"#pragma unroll\n"
"            for (int kc = 0; kc < 4; kc++) {\n"
"                int k_off = kc * 32;\n"
"                unsigned int b0 = 0, b1 = 0;\n"
"                if (b_col < FAFP8_BKV) {\n"
"                    const unsigned char *kp = smK + b_col * FAFP8_HD + k_off;\n"
"                    b0 = *(const unsigned int *)(kp + tid4 * 4);\n"
"                    b1 = *(const unsigned int *)(kp + tid4 * 4 + 16);\n"
"                }\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(S[ni][0]), \"=f\"(S[ni][1]), \"=f\"(S[ni][2]), \"=f\"(S[ni][3])\n"
"                    : \"r\"(q_frag[kc][0]), \"r\"(q_frag[kc][1]), \"r\"(q_frag[kc][2]), \"r\"(q_frag[kc][3]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(S[ni][0]), \"f\"(S[ni][1]), \"f\"(S[ni][2]), \"f\"(S[ni][3])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"        /* Apply qk_scale and mask out-of-bounds KV cols. D-fragment col mapping:\n"
"         * d0=col tid4*2, d1=col tid4*2+1, d2=col tid4*2, d3=col tid4*2+1 (rows differ). */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            int kvr0 = kv_base + col0;\n"
"            int kvr1 = kv_base + col1;\n"
"            S[ni][0] = (kvr0 < N) ? S[ni][0] * qk_scale : -1e30f;\n"
"            S[ni][1] = (kvr1 < N) ? S[ni][1] * qk_scale : -1e30f;\n"
"            S[ni][2] = (kvr0 < N) ? S[ni][2] * qk_scale : -1e30f;\n"
"            S[ni][3] = (kvr1 < N) ? S[ni][3] * qk_scale : -1e30f;\n"
"        }\n"
"\n"
"        /* Online softmax: per-row max */\n"
"        float new_m[2], alpha[2];\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"            float my = -1e30f;\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < 4; ni++) {\n"
"                my = fmaxf(my, S[ni][rp*2 + 0]);\n"
"                my = fmaxf(my, S[ni][rp*2 + 1]);\n"
"            }\n"
"            /* Reduce across the 4 lanes that share gid (xor 1, 2 over tid4) */\n"
"            float o1 = __shfl_xor_sync(0xFFFFFFFF, my, 1); my = fmaxf(my, o1);\n"
"            float o2 = __shfl_xor_sync(0xFFFFFFFF, my, 2); my = fmaxf(my, o2);\n"
"            new_m[rp] = fmaxf(m_state[rp], my);\n"
"            alpha[rp] = expf(m_state[rp] - new_m[rp]);\n"
"        }\n"
"\n"
"        /* Rescale O and l */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            O[ni][0] *= alpha[0]; O[ni][1] *= alpha[0];\n"
"            O[ni][2] *= alpha[1]; O[ni][3] *= alpha[1];\n"
"        }\n"
"        l_state[0] *= alpha[0]; l_state[1] *= alpha[1];\n"
"\n"
"        /* P = exp(S - new_m). Scale up by 448 so e4m3 conversion uses full range. */\n"
"        float P_data[4][4];\n"
"        float row_sum[2] = {0.0f, 0.0f};\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < 4; ni++) {\n"
"                float p0 = expf(S[ni][rp*2 + 0] - new_m[rp]);\n"
"                float p1 = expf(S[ni][rp*2 + 1] - new_m[rp]);\n"
"                P_data[ni][rp*2 + 0] = p0;\n"
"                P_data[ni][rp*2 + 1] = p1;\n"
"                row_sum[rp] += p0 + p1;\n"
"            }\n"
"        }\n"
"        float r0a = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 1); row_sum[0] += r0a;\n"
"        float r0b = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 2); row_sum[0] += r0b;\n"
"        float r1a = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 1); row_sum[1] += r1a;\n"
"        float r1b = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 2); row_sum[1] += r1b;\n"
"        l_state[0] += row_sum[0]; l_state[1] += row_sum[1];\n"
"        m_state[0] = new_m[0]; m_state[1] = new_m[1];\n"
"\n"
"        /* Stash P (scaled by 448) into smP for re-read as A-fragment */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            smP[gid * FAFP8_BKV + col0]     = P_data[ni][0] * 448.0f;\n"
"            smP[gid * FAFP8_BKV + col1]     = P_data[ni][1] * 448.0f;\n"
"            smP[(gid+8) * FAFP8_BKV + col0] = P_data[ni][2] * 448.0f;\n"
"            smP[(gid+8) * FAFP8_BKV + col1] = P_data[ni][3] * 448.0f;\n"
"        }\n"
"        __syncwarp();  /* smP is per-warp, only warp-local barrier needed */\n"
"\n"
"        /* Convert P to FP8 A-fragment (1 K-chunk: BKV=32 = K) */\n"
"        unsigned int p_frag[4];\n"
"        {\n"
"            int row0 = gid;\n"
"            int row1 = gid + 8;\n"
"#define CVTPF(reg, row, c) { \\\n"
"                unsigned short lo, hi; \\\n"
"                asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) : \\\n"
"                    \"f\"(smP[(row)*FAFP8_BKV + (c)]), \"f\"(smP[(row)*FAFP8_BKV + (c)+1])); \\\n"
"                asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) : \\\n"
"                    \"f\"(smP[(row)*FAFP8_BKV + (c)+2]), \"f\"(smP[(row)*FAFP8_BKV + (c)+3])); \\\n"
"                reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"            CVTPF(p_frag[0], row0, tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVTPF(p_frag[1], row1, tid4*4)\n"
"            CVTPF(p_frag[2], row0, tid4*4 + 16)\n"
"#else\n"
"            CVTPF(p_frag[1], row0, tid4*4 + 16)\n"
"            CVTPF(p_frag[2], row1, tid4*4)\n"
"#endif\n"
"            CVTPF(p_frag[3], row1, tid4*4 + 16)\n"
"#undef CVTPF\n"
"        }\n"
"\n"
"        /* O += P . V via mma. 16 N-iters of m16n8 (head_dim=128/8). 1 K-iter (BKV=32). */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            int n_base = ni * 8;\n"
"            int b_col = n_base + gid;  /* head_dim col */\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (b_col < head_dim) {\n"
"                const unsigned char *vp = smVT + b_col * FAFP8_BKV;\n"
"                b0 = *(const unsigned int *)(vp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(vp + tid4 * 4 + 16);\n"
"            }\n"
"            float d0 = O[ni][0], d1 = O[ni][1], d2 = O[ni][2], d3 = O[ni][3];\n"
"            asm volatile(\n"
"                \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                : \"=f\"(d0), \"=f\"(d1), \"=f\"(d2), \"=f\"(d3)\n"
"                : \"r\"(p_frag[0]), \"r\"(p_frag[1]), \"r\"(p_frag[2]), \"r\"(p_frag[3]),\n"
"                  \"r\"(b0), \"r\"(b1),\n"
"                  \"f\"(d0), \"f\"(d1), \"f\"(d2), \"f\"(d3)\n"
"            );\n"
"            O[ni][0] = d0; O[ni][1] = d1; O[ni][2] = d2; O[ni][3] = d3;\n"
"        }\n"
"        __syncthreads();  /* before next tile overwrites shared smK/smVT */\n"
"    }\n"
"\n"
"    /* Final write: descale by sV/448 (P scale was 1/448), divide by l_state */\n"
"    int row0 = q_base + gid;\n"
"    int row1 = q_base + gid + 8;\n"
"    float inv_l0 = (l_state[0] > 0.0f) ? 1.0f / l_state[0] : 0.0f;\n"
"    float inv_l1 = (l_state[1] > 0.0f) ? 1.0f / l_state[1] : 0.0f;\n"
"    float fac = sV * (1.0f / 448.0f);\n"
"#pragma unroll\n"
"    for (int ni = 0; ni < 16; ni++) {\n"
"        int col0 = ni * 8 + tid4 * 2;\n"
"        int col1 = col0 + 1;\n"
"        if (row0 < N && col0 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col0] = O[ni][0] * fac * inv_l0;\n"
"        if (row0 < N && col1 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col1] = O[ni][1] * fac * inv_l0;\n"
"        if (row1 < N && col0 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col0] = O[ni][2] * fac * inv_l1;\n"
"        if (row1 < N && col1 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col1] = O[ni][3] * fac * inv_l1;\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * BF16 MMA pipelined GEMM -- port of gemm_fp8_scaled_f32_pipe to BF16 compute.
 * Reads FP8 weights from global memory, keeps the W tile as raw FP8 bytes in
 * shared memory, and dequants FP8 -> BF16 inline at MMA-load time via the
 * d_fp8_to_bf16_lut constant-memory LUT. X is pre-converted F32 -> BF16 at
 * smem-load time. No per-tensor X scaling (BF16 has F32 dynamic range).
 *
 * Outer loop step is K=32 (matching the FP8 pipe), so iteration count and
 * sync-point count are unchanged. Inside each outer iter, 2 m16n8k16 BF16
 * MMAs cover the same K=32 range that one m16n8k32 FP8 MMA covered.
 *
 * Smem: smX bf16 (32 x 32 = 2 KB) + smW_fp8 (256 x 32 = 8 KB) x 2 stages
 * = 18 KB. Same as the FP8 pipe -> 5 CTAs/SM.
 *
 * Requires: sm_80+, n_in % 32 == 0, n_out % 256 == 0, n_tok >= 16.
 * ============================================================================ */
"#if __CUDA_ARCH__ >= 800\n"
"__global__ __launch_bounds__(128, 5)\n"
"void gemm_bf16_pipe_f32(float *Y, const unsigned char *W, const float *X,\n"
"                        const float *bias, int n_out, int n_in, int n_tok) {\n"
"    extern __shared__ unsigned char bf16pipe_smem[];\n"
"    /* Layout: smX_bf16 (32x32 bf16 = 2048 B) + smW_fp8 stage 0 (8192 B) +\n"
"     * smW_fp8 stage 1 (8192 B) = 18432 B. */\n"
"    unsigned short *smX = (unsigned short *)bf16pipe_smem;\n"
"    unsigned char *smW_fp8_0 = bf16pipe_smem + 2048;\n"
"    unsigned char *smW_fp8_1 = bf16pipe_smem + 2048 + 8192;\n"
"\n"
"    int tok_base = blockIdx.y * 32;\n"
"    int warp_id  = threadIdx.x / 32;\n"
"    int out_base_cta = blockIdx.x * 256;\n"
"    int out_base = out_base_cta + warp_id * 64;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid  = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    int tid  = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    float d0[2][8]; float d1[2][8]; float d2[2][8]; float d3[2][8];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < 2; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < 8; i++) { d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0; }\n"
"    }\n"
"\n"
"    int n_ktiles = n_in / 32;\n"
"\n"
"    /* Issue 4 cp.async.16 for one 8 KB FP8 W tile (256 rows x 32 K bytes).\n"
"     * Same layout as gemm_fp8_scaled_f32_pipe LOAD_W_TILE: 2 rows per thread\n"
"     * x 2 issues per row. */\n"
"#define LOAD_W_TILE_FP8(smW_ptr, kt_val) do {\\\n"
"        int _k = (kt_val) * 32;\\\n"
"        int _r0 = 2 * tid;\\\n"
"        int _r1 = _r0 + 1;\\\n"
"        const unsigned char *_src0 = W + (size_t)(out_base_cta + _r0) * n_in + _k;\\\n"
"        const unsigned char *_src1 = W + (size_t)(out_base_cta + _r1) * n_in + _k;\\\n"
"        unsigned int _dst0 = (unsigned int)__cvta_generic_to_shared((smW_ptr) + _r0 * 32);\\\n"
"        unsigned int _dst1 = (unsigned int)__cvta_generic_to_shared((smW_ptr) + _r1 * 32);\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst0),      \"l\"(_src0));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst0 + 16), \"l\"(_src0 + 16));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst1),      \"l\"(_src1));\\\n"
"        asm volatile(\"cp.async.ca.shared.global [%0], [%1], 16;\\n\" :: \"r\"(_dst1 + 16), \"l\"(_src1 + 16));\\\n"
"    } while (0)\n"
"\n"
"    LOAD_W_TILE_FP8(smW_fp8_0, 0);\n"
"    asm volatile(\"cp.async.commit_group;\\n\");\n"
"    if (n_ktiles > 1) {\n"
"        LOAD_W_TILE_FP8(smW_fp8_1, 1);\n"
"        asm volatile(\"cp.async.commit_group;\\n\");\n"
"    }\n"
"\n"
"    for (int kt = 0; kt < n_ktiles; kt++) {\n"
"        int k = kt * 32;\n"
"        unsigned char *smW_fp8_cur = (kt & 1) ? smW_fp8_1 : smW_fp8_0;\n"
"\n"
"        /* Load X tile (32 rows x 32 K floats) and pre-convert to BF16.\n"
"         * 128 threads x 8 floats = 1024 floats per pass. */\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        int grow = tok_base + srow;\n"
"        float xv[8];\n"
"        if (grow < n_tok) {\n"
"            const float4 *xp = (const float4 *)&X[(long)grow * n_in + k + scol];\n"
"            float4 v0 = xp[0]; float4 v1 = xp[1];\n"
"            xv[0]=v0.x; xv[1]=v0.y; xv[2]=v0.z; xv[3]=v0.w;\n"
"            xv[4]=v1.x; xv[5]=v1.y; xv[6]=v1.z; xv[7]=v1.w;\n"
"        } else {\n"
"            xv[0]=0;xv[1]=0;xv[2]=0;xv[3]=0;xv[4]=0;xv[5]=0;xv[6]=0;xv[7]=0;\n"
"        }\n"
"        unsigned int x01 = (unsigned int)f32_to_bf16_bits(xv[0]) | ((unsigned int)f32_to_bf16_bits(xv[1]) << 16);\n"
"        unsigned int x23 = (unsigned int)f32_to_bf16_bits(xv[2]) | ((unsigned int)f32_to_bf16_bits(xv[3]) << 16);\n"
"        unsigned int x45 = (unsigned int)f32_to_bf16_bits(xv[4]) | ((unsigned int)f32_to_bf16_bits(xv[5]) << 16);\n"
"        unsigned int x67 = (unsigned int)f32_to_bf16_bits(xv[6]) | ((unsigned int)f32_to_bf16_bits(xv[7]) << 16);\n"
"        *(unsigned int *)(smX + srow * 32 + scol    ) = x01;\n"
"        *(unsigned int *)(smX + srow * 32 + scol + 2) = x23;\n"
"        *(unsigned int *)(smX + srow * 32 + scol + 4) = x45;\n"
"        *(unsigned int *)(smX + srow * 32 + scol + 6) = x67;\n"
"\n"
"        if (n_ktiles - kt >= 2) {\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\");\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\");\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* Build A fragments via ldmatrix from smX (BF16). Two halves: K=0..15\n"
"         * and K=16..31, separately ldmatrix'd into a_lo and a_hi. */\n"
"        unsigned int a_lo[2][4], a_hi[2][4];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < 2; mt++) {\n"
"            int mr = mt * 16;\n"
"            int row_in_A = ((lane & 16) ? 8 : 0) + (lane & 7);\n"
"            /* Low half: cols 0..15 */\n"
"            {\n"
"                int col_in_A = (lane & 8) ? 8 : 0;\n"
"                unsigned int sa = (unsigned int)__cvta_generic_to_shared(\n"
"                    smX + (mr + row_in_A) * 32 + col_in_A);\n"
"                unsigned int ra, rb, rc, rd;\n"
"                asm(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\"\n"
"                    : \"=r\"(ra), \"=r\"(rb), \"=r\"(rc), \"=r\"(rd) : \"r\"(sa));\n"
"#if __CUDA_ARCH__ >= 1200\n"
"                a_lo[mt][0] = ra; a_lo[mt][1] = rc; a_lo[mt][2] = rb; a_lo[mt][3] = rd;\n"
"#else\n"
"                a_lo[mt][0] = ra; a_lo[mt][1] = rb; a_lo[mt][2] = rc; a_lo[mt][3] = rd;\n"
"#endif\n"
"            }\n"
"            /* High half: cols 16..31 */\n"
"            {\n"
"                int col_in_A = 16 + ((lane & 8) ? 8 : 0);\n"
"                unsigned int sa = (unsigned int)__cvta_generic_to_shared(\n"
"                    smX + (mr + row_in_A) * 32 + col_in_A);\n"
"                unsigned int ra, rb, rc, rd;\n"
"                asm(\"ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\"\n"
"                    : \"=r\"(ra), \"=r\"(rb), \"=r\"(rc), \"=r\"(rd) : \"r\"(sa));\n"
"#if __CUDA_ARCH__ >= 1200\n"
"                a_hi[mt][0] = ra; a_hi[mt][1] = rc; a_hi[mt][2] = rb; a_hi[mt][3] = rd;\n"
"#else\n"
"                a_hi[mt][0] = ra; a_hi[mt][1] = rb; a_hi[mt][2] = rc; a_hi[mt][3] = rd;\n"
"#endif\n"
"            }\n"
"        }\n"
"\n"
"        /* N-tile loop. For each nt: load 8 FP8 bytes from smW (the same 8\n"
"         * bytes the FP8 pipe loaded as b0/b1), but split into 4 u16 reads\n"
"         * because the BF16 m16n8k16 B-operand needs sparse K positions. */\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < 8; nt++) {\n"
"            int bc_local = warp_id * 64 + nt * 8 + gid;\n"
"            const unsigned char *bp = smW_fp8_cur + bc_local * 32 + tid4 * 2;\n"
"            /* Read 4 u16 of FP8: pairs at offsets 0, 8, 16, 24 within the row. */\n"
"            unsigned short w0 = *(const unsigned short *)(bp + 0);\n"
"            unsigned short w1 = *(const unsigned short *)(bp + 8);\n"
"            unsigned short w2 = *(const unsigned short *)(bp + 16);\n"
"            unsigned short w3 = *(const unsigned short *)(bp + 24);\n"
"            unsigned int b0_lo = (unsigned int)d_fp8_to_bf16_lut[w0 & 0xFF]\n"
"                              | ((unsigned int)d_fp8_to_bf16_lut[w0 >> 8] << 16);\n"
"            unsigned int b1_lo = (unsigned int)d_fp8_to_bf16_lut[w1 & 0xFF]\n"
"                              | ((unsigned int)d_fp8_to_bf16_lut[w1 >> 8] << 16);\n"
"            unsigned int b0_hi = (unsigned int)d_fp8_to_bf16_lut[w2 & 0xFF]\n"
"                              | ((unsigned int)d_fp8_to_bf16_lut[w2 >> 8] << 16);\n"
"            unsigned int b1_hi = (unsigned int)d_fp8_to_bf16_lut[w3 & 0xFF]\n"
"                              | ((unsigned int)d_fp8_to_bf16_lut[w3 >> 8] << 16);\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < 2; mt++) {\n"
"                /* Low MMA: K = 0..15 of the 32-K window */\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a_lo[mt][0]), \"r\"(a_lo[mt][1]), \"r\"(a_lo[mt][2]), \"r\"(a_lo[mt][3]),\n"
"                      \"r\"(b0_lo), \"r\"(b1_lo),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"                /* High MMA: K = 16..31 */\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a_hi[mt][0]), \"r\"(a_hi[mt][1]), \"r\"(a_hi[mt][2]), \"r\"(a_hi[mt][3]),\n"
"                      \"r\"(b0_hi), \"r\"(b1_hi),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"        if (kt + 2 < n_ktiles) {\n"
"            unsigned char *smW_fp8_next = ((kt + 2) & 1) ? smW_fp8_1 : smW_fp8_0;\n"
"            LOAD_W_TILE_FP8(smW_fp8_next, kt + 2);\n"
"            asm volatile(\"cp.async.commit_group;\\n\");\n"
"        }\n"
"\n"
"        __syncthreads();\n"
"    }\n"
"#undef LOAD_W_TILE_FP8\n"
"\n"
"    /* Writeback -- fused bf16 trunc, optional bias. */\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < 2; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < 8; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * BF16 flash attention -- same tile shape as flash_attn_fp8 (BKV=32, 16 Q rows
 * per warp, 4 warps/CTA, head_dim=128) but with mma.sync.m16n8k16.bf16.bf16.f32
 * instead of m16n8k32.e4m3.e4m3.f32. Drops all FP8 per-tensor quantization
 * machinery (no scales, no max, no P*448 trick) -- Q/K/V are passed in as
 * BF16 (uint16_t) and consumed directly. F32 online softmax is unchanged.
 *
 * This matches ComfyUI's BF16 attention precision exactly (no quantization
 * loss across heads), eliminating the ~+4.4 pixel_mean error introduced by
 * the FP8 attention path.
 *
 * Sm_120 a1/a2 fragment swap is applied to both A operands (Q and P).
 * ============================================================================ */
"#if __CUDA_ARCH__ >= 800\n"
"#define FABF16_BKV    32\n"
"#define FABF16_M      16\n"
"#define FABF16_HD    128\n"
"#define FABF16_NWARPS 4\n"
"__global__ void flash_attn_bf16(\n"
"    float *__restrict__ out,\n"
"    const unsigned short *__restrict__ Qb,\n"
"    const unsigned short *__restrict__ Kb,\n"
"    const unsigned short *__restrict__ Vb,\n"
"    int N, int n_heads, int head_dim) {\n"
"    int h = blockIdx.x;\n"
"    int warp = threadIdx.x / 32;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    int q_base = blockIdx.y * (FABF16_M * FABF16_NWARPS) + warp * FABF16_M;\n"
"    int dim = n_heads * head_dim;\n"
"\n"
"    /* ----- Load Q into A-fragment registers. 8 K-chunks of k=16 BF16 each. ----- */\n"
"    /* Per lane per chunk: 4 u32 = 8 BF16 = 4 (row, col-pair) entries. */\n"
"    unsigned int q_frag[8][4];\n"
"#pragma unroll\n"
"    for (int kc = 0; kc < 8; kc++) {\n"
"        int k0 = kc * 16;\n"
"        int row0 = q_base + gid;\n"
"        int row1 = q_base + gid + 8;\n"
"        const unsigned short *qbase0 = (row0 < N) ? Qb + (long)row0 * dim + h * head_dim : (const unsigned short *)0;\n"
"        const unsigned short *qbase1 = (row1 < N) ? Qb + (long)row1 * dim + h * head_dim : (const unsigned short *)0;\n"
"        unsigned int z = 0;\n"
"        q_frag[kc][0] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*2)     : z;\n"
"#if __CUDA_ARCH__ >= 1200\n"
"        q_frag[kc][1] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*2)     : z;\n"
"        q_frag[kc][2] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*2 + 8) : z;\n"
"#else\n"
"        q_frag[kc][1] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*2 + 8) : z;\n"
"        q_frag[kc][2] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*2)     : z;\n"
"#endif\n"
"        q_frag[kc][3] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*2 + 8) : z;\n"
"    }\n"
"\n"
"    /* O accumulator: 16 N-iters (head_dim/8) x 4 floats per thread per N-iter */\n"
"    float O[16][4];\n"
"#pragma unroll\n"
"    for (int i = 0; i < 16; i++) {\n"
"        O[i][0] = 0.0f; O[i][1] = 0.0f; O[i][2] = 0.0f; O[i][3] = 0.0f;\n"
"    }\n"
"    float m_state[2] = {-1e30f, -1e30f};\n"
"    float l_state[2] = {0.0f, 0.0f};\n"
"\n"
"    float qk_scale = rsqrtf((float)head_dim);\n"
"\n"
"    extern __shared__ unsigned char fa_bf16_smem[];\n"
"    /* Layout: [smK: 32 x 128 bf16 = 8192 B][smV: 128 x 32 bf16 transposed = 8192 B][smP: NWARPS x 16 x 32 bf16 = 4096 B] */\n"
"    unsigned short *smK  = (unsigned short *)fa_bf16_smem;\n"
"    unsigned short *smVT = smK + FABF16_BKV * FABF16_HD;\n"
"    unsigned short *smP_all = smVT + FABF16_HD * FABF16_BKV;\n"
"    unsigned short *smP = smP_all + warp * 16 * FABF16_BKV;\n"
"\n"
"    int n_kv_tiles = (N + FABF16_BKV - 1) / FABF16_BKV;\n"
"    for (int kvt = 0; kvt < n_kv_tiles; kvt++) {\n"
"        int kv_base = kvt * FABF16_BKV;\n"
"\n"
"        /* Cooperative load: smK row-major [BKV, HD], smVT transposed [HD, BKV]. */\n"
"        for (int idx = threadIdx.x; idx < FABF16_BKV * FABF16_HD; idx += FABF16_NWARPS * 32) {\n"
"            int kr = idx / FABF16_HD, kd = idx % FABF16_HD;\n"
"            int row = kv_base + kr;\n"
"            unsigned short kk = (row < N) ? Kb[(long)row * dim + h * head_dim + kd] : 0;\n"
"            unsigned short vv = (row < N) ? Vb[(long)row * dim + h * head_dim + kd] : 0;\n"
"            smK[kr * FABF16_HD + kd] = kk;\n"
"            smVT[kd * FABF16_BKV + kr] = vv;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* S = Q . K^T : [16, BKV=32]. 4 N-iters of m16n8k16, 8 K-chunks per. */\n"
"        float S[4][4];\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            S[ni][0] = 0.0f; S[ni][1] = 0.0f; S[ni][2] = 0.0f; S[ni][3] = 0.0f;\n"
"        }\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int n_base = ni * 8;\n"
"            int b_col = n_base + gid;  /* K row index in smK */\n"
"#pragma unroll\n"
"            for (int kc = 0; kc < 8; kc++) {\n"
"                int k_off = kc * 16;\n"
"                unsigned int b0 = 0, b1 = 0;\n"
"                if (b_col < FABF16_BKV) {\n"
"                    const unsigned short *kp = smK + b_col * FABF16_HD + k_off;\n"
"                    b0 = *(const unsigned int *)(kp + tid4 * 2);\n"
"                    b1 = *(const unsigned int *)(kp + tid4 * 2 + 8);\n"
"                }\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(S[ni][0]), \"=f\"(S[ni][1]), \"=f\"(S[ni][2]), \"=f\"(S[ni][3])\n"
"                    : \"r\"(q_frag[kc][0]), \"r\"(q_frag[kc][1]), \"r\"(q_frag[kc][2]), \"r\"(q_frag[kc][3]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(S[ni][0]), \"f\"(S[ni][1]), \"f\"(S[ni][2]), \"f\"(S[ni][3])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"        /* Apply qk_scale and mask out-of-bounds KV cols. */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            int kvr0 = kv_base + col0;\n"
"            int kvr1 = kv_base + col1;\n"
"            S[ni][0] = (kvr0 < N) ? S[ni][0] * qk_scale : -1e30f;\n"
"            S[ni][1] = (kvr1 < N) ? S[ni][1] * qk_scale : -1e30f;\n"
"            S[ni][2] = (kvr0 < N) ? S[ni][2] * qk_scale : -1e30f;\n"
"            S[ni][3] = (kvr1 < N) ? S[ni][3] * qk_scale : -1e30f;\n"
"        }\n"
"\n"
"        /* Online softmax: per-row max */\n"
"        float new_m[2], alpha[2];\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"            float my = -1e30f;\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < 4; ni++) {\n"
"                my = fmaxf(my, S[ni][rp*2 + 0]);\n"
"                my = fmaxf(my, S[ni][rp*2 + 1]);\n"
"            }\n"
"            float o1 = __shfl_xor_sync(0xFFFFFFFF, my, 1); my = fmaxf(my, o1);\n"
"            float o2 = __shfl_xor_sync(0xFFFFFFFF, my, 2); my = fmaxf(my, o2);\n"
"            new_m[rp] = fmaxf(m_state[rp], my);\n"
"            alpha[rp] = expf(m_state[rp] - new_m[rp]);\n"
"        }\n"
"\n"
"        /* Rescale O and l */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            O[ni][0] *= alpha[0]; O[ni][1] *= alpha[0];\n"
"            O[ni][2] *= alpha[1]; O[ni][3] *= alpha[1];\n"
"        }\n"
"        l_state[0] *= alpha[0]; l_state[1] *= alpha[1];\n"
"\n"
"        /* P = exp(S - new_m). No 448 scaling -- BF16 has F32 dynamic range. */\n"
"        float P_data[4][4];\n"
"        float row_sum[2] = {0.0f, 0.0f};\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < 4; ni++) {\n"
"                float p0 = expf(S[ni][rp*2 + 0] - new_m[rp]);\n"
"                float p1 = expf(S[ni][rp*2 + 1] - new_m[rp]);\n"
"                P_data[ni][rp*2 + 0] = p0;\n"
"                P_data[ni][rp*2 + 1] = p1;\n"
"                row_sum[rp] += p0 + p1;\n"
"            }\n"
"        }\n"
"        float r0a = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 1); row_sum[0] += r0a;\n"
"        float r0b = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 2); row_sum[0] += r0b;\n"
"        float r1a = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 1); row_sum[1] += r1a;\n"
"        float r1b = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 2); row_sum[1] += r1b;\n"
"        l_state[0] += row_sum[0]; l_state[1] += row_sum[1];\n"
"        m_state[0] = new_m[0]; m_state[1] = new_m[1];\n"
"\n"
"        /* Stash P as BF16 into smP for re-read as A-fragment */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            smP[gid * FABF16_BKV + col0]     = f32_to_bf16_bits(P_data[ni][0]);\n"
"            smP[gid * FABF16_BKV + col1]     = f32_to_bf16_bits(P_data[ni][1]);\n"
"            smP[(gid+8) * FABF16_BKV + col0] = f32_to_bf16_bits(P_data[ni][2]);\n"
"            smP[(gid+8) * FABF16_BKV + col1] = f32_to_bf16_bits(P_data[ni][3]);\n"
"        }\n"
"        __syncwarp();  /* smP is per-warp */\n"
"\n"
"        /* O += P . V via mma. 16 N-iters of m16n8 (head_dim/8). 2 K-iters (BKV=32 / k=16). */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            int n_base = ni * 8;\n"
"            int b_col = n_base + gid;  /* head_dim col */\n"
"#pragma unroll\n"
"            for (int kc = 0; kc < 2; kc++) {\n"
"                int k_off = kc * 16;\n"
"                /* Build P A-fragment for this k chunk (cols k_off .. k_off+15 of smP) */\n"
"                unsigned int p0, p1, p2, p3;\n"
"                {\n"
"                    int row0 = gid;\n"
"                    int row1 = gid + 8;\n"
"                    p0 = *(const unsigned int *)(smP + row0 * FABF16_BKV + k_off + tid4*2);\n"
"#if __CUDA_ARCH__ >= 1200\n"
"                    p1 = *(const unsigned int *)(smP + row1 * FABF16_BKV + k_off + tid4*2);\n"
"                    p2 = *(const unsigned int *)(smP + row0 * FABF16_BKV + k_off + tid4*2 + 8);\n"
"#else\n"
"                    p1 = *(const unsigned int *)(smP + row0 * FABF16_BKV + k_off + tid4*2 + 8);\n"
"                    p2 = *(const unsigned int *)(smP + row1 * FABF16_BKV + k_off + tid4*2);\n"
"#endif\n"
"                    p3 = *(const unsigned int *)(smP + row1 * FABF16_BKV + k_off + tid4*2 + 8);\n"
"                }\n"
"                unsigned int b0 = 0, b1 = 0;\n"
"                if (b_col < head_dim) {\n"
"                    /* smVT laid out as [head_dim, BKV]; row=b_col gives K bytes */\n"
"                    const unsigned short *vp = smVT + b_col * FABF16_BKV + k_off;\n"
"                    b0 = *(const unsigned int *)(vp + tid4 * 2);\n"
"                    b1 = *(const unsigned int *)(vp + tid4 * 2 + 8);\n"
"                }\n"
"                float d0 = O[ni][0], d1 = O[ni][1], d2 = O[ni][2], d3 = O[ni][3];\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0), \"=f\"(d1), \"=f\"(d2), \"=f\"(d3)\n"
"                    : \"r\"(p0), \"r\"(p1), \"r\"(p2), \"r\"(p3),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0), \"f\"(d1), \"f\"(d2), \"f\"(d3)\n"
"                );\n"
"                O[ni][0] = d0; O[ni][1] = d1; O[ni][2] = d2; O[ni][3] = d3;\n"
"            }\n"
"        }\n"
"        __syncthreads();  /* before next tile overwrites smK/smVT */\n"
"    }\n"
"\n"
"    /* Final write: divide by l_state. No descale -- no 448 scaling. */\n"
"    int row0 = q_base + gid;\n"
"    int row1 = q_base + gid + 8;\n"
"    float inv_l0 = (l_state[0] > 0.0f) ? 1.0f / l_state[0] : 0.0f;\n"
"    float inv_l1 = (l_state[1] > 0.0f) ? 1.0f / l_state[1] : 0.0f;\n"
"#pragma unroll\n"
"    for (int ni = 0; ni < 16; ni++) {\n"
"        int col0 = ni * 8 + tid4 * 2;\n"
"        int col1 = col0 + 1;\n"
"        if (row0 < N && col0 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col0] = O[ni][0] * inv_l0;\n"
"        if (row0 < N && col1 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col1] = O[ni][1] * inv_l0;\n"
"        if (row1 < N && col0 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col0] = O[ni][2] * inv_l1;\n"
"        if (row1 < N && col1 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col1] = O[ni][3] * inv_l1;\n"
"    }\n"
"}\n"
"\n"
"/* Bulk F32 -> BF16 cast kernel for converting Q/K/V before flash_attn_bf16. */\n"
"__global__ void cast_f32_to_bf16(const float *src, unsigned short *dst, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i >= n) return;\n"
"    dst[i] = f32_to_bf16_bits(src[i]);\n"
"}\n"
"#endif\n"
;

#endif /* CUDA_FP8_MMA_KERNELS_H */
