/* ============================================================================
 * cuda_fp8_mma_kernels.h — Shared FP8 MMA GEMM + FP8 flash attention kernels
 * for hand-written PTX mma.sync on sm_89+ (with sm_120 a1/a2 fragment swap).
 *
 * Provides the following symbols inside the NVRTC module:
 *   fp8e4m3_to_f32         — device helper (used by flash_attn_fp8_ref)
 *   gemm_fp8_scaled_f32    — m16n8k32 FP8 MMA GEMM (F32 X, F32 Y), w_scale descale
 *   gemm_fp8_scaled_bf16   — same, BF16 X pre-rounding (ComfyUI-matching)
 *   flash_attn_fp8         — 4-warp CTA FP8 MMA flash attention (head_dim=128)
 *   flash_attn_fp8_ref     — scalar reference for bisecting MMA bugs
 *   quantize_to_fp8_e4m3   — per-tensor F32 → e4m3 quantizer (with scale writeback)
 *   reduce_max_abs_f32     — 1-pass atomic-max reduce to a single F32 slot
 *   zero_f32               — small helper
 *
 * This file is duplicated from cuda/flux2/cuda_flux2_runner.h. Both copies must
 * stay in sync — if a kernel changes in one place, update the other.
 *
 * Consumer pattern: include inside an extern "C" { ... } block in the NVRTC source
 * after a to_bf16(float) device fn has been declared (used by the _bf16 variant).
 * ============================================================================ */
#ifndef CUDA_FP8_MMA_KERNELS_H
#define CUDA_FP8_MMA_KERNELS_H

static const char *fp8_mma_kernels_src =
"\n/* ---- FP8 MMA kernels (shared by flux2 and qimg) ---- */\n"
"__device__ __forceinline__ float fp8e4m3_to_f32(unsigned char b) {\n"
"    int sign = (b >> 7) & 1;\n"
"    int exp  = (b >> 3) & 0xF;\n"
"    int mant = b & 0x7;\n"
"    float v;\n"
"    if (exp == 0 && mant == 0) return 0.0f;\n"
"    if (exp == 15 && mant == 7) return 0.0f;\n"  /* NaN → 0 */
"    if (exp == 0) v = ((float)mant / 8.0f) * (1.0f / 64.0f);\n"  /* subnormal: 2^-6 */
"    else v = (1.0f + (float)mant / 8.0f) * exp2f((float)(exp - 7));\n"
"    return sign ? -v : v;\n"
"}\n"

/* ============================================================
 * MMA-based FP8 GEMM (m16n8k32, sm_89+) with per-tensor weight scale.
 * Grid: (ceil(n_out/256), ceil(n_tok/16)), Block: 128 threads (4 warps).
 * Shared mem: 16 * 32 * sizeof(float) = 2048 bytes for X tile.
 * Each warp computes 16 rows × 64 cols of Y via 8 mma.sync issues.
 * sm_120 (Blackwell) has the a1/a2 fragment swap (same as cuda_kernels_common.h).
 * ============================================================ */
"#if __CUDA_ARCH__ >= 890\n"
"#define FP8_GEMM_NTILE 8\n"
"#define FP8_GEMM_MTILE 2   /* number of m16n8 M-tiles per CTA (32 rows) */\n"
"#define FP8_GEMM_NWARPS 4  /* warps per CTA (4 × 64 N = 256 N cols per CTA) */\n"
"__global__ void gemm_fp8_scaled_f32(float *Y, const unsigned char *W, const float *X,\n"
"                                     const float *bias, int n_out, int n_in, int n_tok,\n"
"                                     float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ float fp8_smem_x[];\n"
"    /* Per-tensor input scaling. If x_max_ptr is non-null, derive\n"
"     * x_scale = max(|X|) / 448 and divide X by x_scale at load time so\n"
"     * values fit in FP8 e4m3 range (±448) without saturating. Multiply\n"
"     * the F32 accumulator by x_scale at writeback to restore magnitude.\n"
"     * Matches torch._scaled_mm(input_fp8, weight_fp8, scale_input, 1). */\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) {\n"
"            x_scale     = mx / 448.0f;\n"
"            x_inv_scale = 448.0f / mx;\n"
"        }\n"
"    }\n"
"    /* sm_x: [FP8_GEMM_MTILE*16 rows × 32 K cols] = 1024 floats per iter */\n"
"    int tok_base = blockIdx.y * (16 * FP8_GEMM_MTILE);\n"
"    int warp_id = threadIdx.x / 32;\n"
"    /* Each warp covers NTILE × 8 N cols = 8*NTILE cols of output */\n"
"    int out_base = blockIdx.x * (8 * FP8_GEMM_NTILE * FP8_GEMM_NWARPS) + warp_id * (8 * FP8_GEMM_NTILE);\n"
"    int lane = threadIdx.x % 32;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane % 4;\n"
"    int tid = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    /* 2 M-tiles × 8 N-tiles × 4 f32 per thread = 64 f32 per lane */\n"
"    float d0[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d1[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d2[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d3[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < FP8_GEMM_NTILE; i++) {\n"
"            d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0;\n"
"        }\n"
"    }\n"
"\n"
"    int M_ROWS = 16 * FP8_GEMM_MTILE;\n"
"    for (int k = 0; k < n_in; k += 32) {\n"
"        /* Cooperative load M_ROWS × 32 K tile. 128 threads × 8 floats = 1024\n"
"         * floats per pass. For MTILE=2 (32 rows) one pass covers everything;\n"
"         * for MTILE=4 (64 rows) we iterate with a 32-row stride. */\n"
"        int scol = (tid & 3) * 8;\n"
"#pragma unroll\n"
"        for (int row_base = 0; row_base < M_ROWS; row_base += 32) {\n"
"            int srow = row_base + tid / 4;\n"
"            if (srow < M_ROWS) {\n"
"                int grow = tok_base + srow;\n"
"#pragma unroll\n"
"                for (int j = 0; j < 8; j++) {\n"
"                    float v = (grow < n_tok && k + scol + j < n_in)\n"
"                            ? X[(long)grow * n_in + k + scol + j] : 0.0f;\n"
"                    fp8_smem_x[srow * 32 + scol + j] = v * x_inv_scale;\n"
"                }\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"#define CVT_E4M3_PAIR(reg, r, c) \\\n"
"        { unsigned short lo, hi; \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)]), \"f\"(fp8_smem_x[(r)*32+(c)+1])); \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)+2]), \"f\"(fp8_smem_x[(r)*32+(c)+3])); \\\n"
"          reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"\n"
"        /* Load all A frags for each M-tile once (hoisted outside N-tile loop) */\n"
"        unsigned int a0[FP8_GEMM_MTILE], a1[FP8_GEMM_MTILE], a2[FP8_GEMM_MTILE], a3[FP8_GEMM_MTILE];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"            int mr = mt * 16;\n"
"            CVT_E4M3_PAIR(a0[mt], mr + gid,     tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid + 8, tid4*4)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid,     tid4*4 + 16)\n"
"#else\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid,     tid4*4 + 16)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid + 8, tid4*4)\n"
"#endif\n"
"            CVT_E4M3_PAIR(a3[mt], mr + gid + 8, tid4*4 + 16)\n"
"        }\n"
"#undef CVT_E4M3_PAIR\n"
"\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int bc = out_base + nt * 8 + gid;\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (bc < n_out && k + tid4*4 + 19 < n_in) {\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                b0 = *(const unsigned int *)(wp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(wp + tid4 * 4 + 16);\n"
"            } else if (bc < n_out) {\n"
"                unsigned char tmp[8] = {0,0,0,0,0,0,0,0};\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                for (int j = 0; j < 4; j++) {\n"
"                    int kk = k + tid4*4 + j;\n"
"                    if (kk < n_in) tmp[j] = wp[tid4*4 + j];\n"
"                    int kk2 = k + tid4*4 + 16 + j;\n"
"                    if (kk2 < n_in) tmp[4+j] = wp[tid4*4 + 16 + j];\n"
"                }\n"
"                b0 = ((unsigned int)tmp[0]) | ((unsigned int)tmp[1] << 8) | ((unsigned int)tmp[2] << 16) | ((unsigned int)tmp[3] << 24);\n"
"                b1 = ((unsigned int)tmp[4]) | ((unsigned int)tmp[5] << 8) | ((unsigned int)tmp[6] << 16) | ((unsigned int)tmp[7] << 24);\n"
"            }\n"
"\n"
"            /* Issue mma for each M-tile with shared B */\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            float sc = w_scale * x_scale;\n"
"            /* Fused BF16 truncation at writeback — saves one full pass over\n"
"             * the output tensor (op_bf16_trunc) per GEMM. */\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] * sc + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] * sc + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] * sc + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] * sc + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/* BF16-X sibling of gemm_fp8_scaled_f32.\n"
" *\n"
" * Mirrors the MTILE=2, 4-warp, per-tensor-input-scaled f32 kernel above with\n"
" * two differences:\n"
" *   (1) X is pre-rounded to BF16 at the smem load (match ComfyUI BF16 infer).\n"
" *   (2) Output is written as BF16-truncated F32 inline, saving the follow-on\n"
" *       op_bf16_trunc kernel launch.\n"
" *\n"
" * Same (Y, W, X, bias, n_out, n_in, n_tok, w_scale, x_max_ptr) signature as\n"
" * gemm_fp8_scaled_f32 so the runner can swap them 1:1. */\n"
"__global__ void gemm_fp8_scaled_bf16(float *Y, const unsigned char *W, const float *X,\n"
"                                      const float *bias, int n_out, int n_in, int n_tok,\n"
"                                      float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ float fp8_smem_x[];\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) {\n"
"            x_scale     = mx / 448.0f;\n"
"            x_inv_scale = 448.0f / mx;\n"
"        }\n"
"    }\n"
"    int tok_base = blockIdx.y * (16 * FP8_GEMM_MTILE);\n"
"    int warp_id = threadIdx.x / 32;\n"
"    int out_base = blockIdx.x * (64 * FP8_GEMM_NWARPS) + warp_id * 64;\n"
"    int lane = threadIdx.x % 32;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane % 4;\n"
"    int tid = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    float d0[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d1[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d2[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"    float d3[FP8_GEMM_MTILE][FP8_GEMM_NTILE];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"#pragma unroll\n"
"        for (int i = 0; i < FP8_GEMM_NTILE; i++) {\n"
"            d0[mt][i]=0; d1[mt][i]=0; d2[mt][i]=0; d3[mt][i]=0;\n"
"        }\n"
"    }\n"
"\n"
"    int M_ROWS = 16 * FP8_GEMM_MTILE;\n"
"    for (int k = 0; k < n_in; k += 32) {\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        if (srow < M_ROWS) {\n"
"            int grow = tok_base + srow;\n"
"#pragma unroll\n"
"            for (int j = 0; j < 8; j++) {\n"
"                float v = (grow < n_tok && k + scol + j < n_in)\n"
"                        ? X[(long)grow * n_in + k + scol + j] : 0.0f;\n"
"                fp8_smem_x[srow * 32 + scol + j] = to_bf16(v * x_inv_scale);\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"#define CVT_E4M3_PAIR(reg, r, c) \\\n"
"        { unsigned short lo, hi; \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)]), \"f\"(fp8_smem_x[(r)*32+(c)+1])); \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)+2]), \"f\"(fp8_smem_x[(r)*32+(c)+3])); \\\n"
"          reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"\n"
"        unsigned int a0[FP8_GEMM_MTILE], a1[FP8_GEMM_MTILE], a2[FP8_GEMM_MTILE], a3[FP8_GEMM_MTILE];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"            int mr = mt * 16;\n"
"            CVT_E4M3_PAIR(a0[mt], mr + gid,     tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid + 8, tid4*4)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid,     tid4*4 + 16)\n"
"#else\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid,     tid4*4 + 16)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid + 8, tid4*4)\n"
"#endif\n"
"            CVT_E4M3_PAIR(a3[mt], mr + gid + 8, tid4*4 + 16)\n"
"        }\n"
"#undef CVT_E4M3_PAIR\n"
"\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int bc = out_base + nt * 8 + gid;\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (bc < n_out && k + tid4*4 + 19 < n_in) {\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                b0 = *(const unsigned int *)(wp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(wp + tid4 * 4 + 16);\n"
"            } else if (bc < n_out) {\n"
"                unsigned char tmp[8] = {0,0,0,0,0,0,0,0};\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                for (int j = 0; j < 4; j++) {\n"
"                    int kk = k + tid4*4 + j;\n"
"                    if (kk < n_in) tmp[j] = wp[tid4*4 + j];\n"
"                    int kk2 = k + tid4*4 + 16 + j;\n"
"                    if (kk2 < n_in) tmp[4+j] = wp[tid4*4 + 16 + j];\n"
"                }\n"
"                b0 = ((unsigned int)tmp[0]) | ((unsigned int)tmp[1] << 8) | ((unsigned int)tmp[2] << 16) | ((unsigned int)tmp[3] << 24);\n"
"                b1 = ((unsigned int)tmp[4]) | ((unsigned int)tmp[5] << 8) | ((unsigned int)tmp[6] << 16) | ((unsigned int)tmp[7] << 24);\n"
"            }\n"
"\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < FP8_GEMM_MTILE; mt++) {\n"
"        int mr = mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < FP8_GEMM_NTILE; nt++) {\n"
"            int yc0 = out_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            float sc = w_scale * x_scale;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = to_bf16(d0[mt][nt] * sc + bv0);\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = to_bf16(d1[mt][nt] * sc + bv1);\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = to_bf16(d2[mt][nt] * sc + bv0);\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = to_bf16(d3[mt][nt] * sc + bv1);\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * 128×128 tiled FP8 MMA GEMM — CUDA-C port of gemm_fp8_tc128_e4m3 from
 * cuda/fp8/fp8_gemm.c, adapted for qwen-image's transposed W layout
 * (Y[tok,n_out] = X[tok,n_in] @ W[n_out,n_in]^T).
 *
 * CTA tile: 128 rows × 128 cols, 16 warps (512 threads) arranged in a 4×4 grid.
 * Each warp computes 32 × 32 via 8 m16n8k32 MMAs (2 M-tiles × 4 N-tiles of 16×8).
 * Shared mem: 128 × 32 f32 = 16 KB for X tile (cvt to e4m3 at MMA load time).
 *
 * Feature parity with gemm_fp8_scaled_f32: bias, per-tensor w_scale,
 * per-tensor input scaling via x_max_ptr. Output is F32; downstream pipeline
 * applies op_bf16_trunc like the MTILE=2 sibling. Note: the sandbox kernel's
 * comment claims 128×128 but the 4 MMAs/warp only cover 32×16 per warp → the
 * sandbox effective CTA is 128×64. This port fills in the missing 4 MMAs so
 * the CTA is actually 128×128 as advertised.
 * ============================================================================ */
"#if __CUDA_ARCH__ >= 890\n"
"#define TC128_MWARPS 4     /* warp grid M-dim */\n"
"#define TC128_NWARPS_N 4   /* warp grid N-dim */\n"
"#define TC128_WARP_M 2     /* M-tiles per warp */\n"
"#define TC128_WARP_N 4     /* N-tiles per warp */\n"
"__global__ void gemm_fp8_scaled_tc128_f32(float *Y, const unsigned char *W,\n"
"                                           const float *X, const float *bias,\n"
"                                           int n_out, int n_in, int n_tok,\n"
"                                           float w_scale, const float *x_max_ptr) {\n"
"    extern __shared__ float fp8_smem_x[];\n"
"    /* Per-tensor input scaling — same as gemm_fp8_scaled_f32. */\n"
"    float x_inv_scale = 1.0f;\n"
"    float x_scale     = 1.0f;\n"
"    if (x_max_ptr) {\n"
"        float mx = *x_max_ptr;\n"
"        if (mx > 448.0f) {\n"
"            x_scale     = mx / 448.0f;\n"
"            x_inv_scale = 448.0f / mx;\n"
"        }\n"
"    }\n"
"    int tok_base = blockIdx.y * 128;\n"
"    int out_base = blockIdx.x * 128;\n"
"    int warp_id  = threadIdx.x / 32;\n"
"    int lane     = threadIdx.x % 32;\n"
"    int gid      = lane / 4;\n"
"    int tid4     = lane % 4;\n"
"    int tid      = threadIdx.x;\n"
"    if (tok_base >= n_tok) return;\n"
"\n"
"    /* Warp position in 4×4 grid: warp_m = warp_id & 3, warp_n = warp_id >> 2 */\n"
"    int warp_m_base = (warp_id & 3) * 32;\n"
"    int warp_n_base = (warp_id >> 2) * 32;\n"
"\n"
"    /* 2 M-tiles × 4 N-tiles × 4 f32 = 32 f32 accumulators per lane */\n"
"    float d0[TC128_WARP_M][TC128_WARP_N];\n"
"    float d1[TC128_WARP_M][TC128_WARP_N];\n"
"    float d2[TC128_WARP_M][TC128_WARP_N];\n"
"    float d3[TC128_WARP_M][TC128_WARP_N];\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < TC128_WARP_N; nt++) {\n"
"            d0[mt][nt]=0; d1[mt][nt]=0; d2[mt][nt]=0; d3[mt][nt]=0;\n"
"        }\n"
"    }\n"
"\n"
"    for (int k = 0; k < n_in; k += 32) {\n"
"        /* Cooperative X load: 128 rows × 32 cols = 4096 f32.\n"
"         * 512 threads × 8 f32 = 4096. tid → row = tid/4, col = (tid%4)*8. */\n"
"        int srow = tid / 4;\n"
"        int scol = (tid & 3) * 8;\n"
"        int grow = tok_base + srow;\n"
"#pragma unroll\n"
"        for (int j = 0; j < 8; j++) {\n"
"            float v = (grow < n_tok && k + scol + j < n_in)\n"
"                    ? X[(long)grow * n_in + k + scol + j] : 0.0f;\n"
"            fp8_smem_x[srow * 32 + scol + j] = v * x_inv_scale;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"#define CVT_E4M3_PAIR(reg, r, c) \\\n"
"        { unsigned short lo, hi; \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)]), \"f\"(fp8_smem_x[(r)*32+(c)+1])); \\\n"
"          asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) \\\n"
"              : \"f\"(fp8_smem_x[(r)*32+(c)+2]), \"f\"(fp8_smem_x[(r)*32+(c)+3])); \\\n"
"          reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"\n"
"        /* Hoist A frags for this warp's 2 M-tiles */\n"
"        unsigned int a0[TC128_WARP_M], a1[TC128_WARP_M], a2[TC128_WARP_M], a3[TC128_WARP_M];\n"
"#pragma unroll\n"
"        for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"            int mr = warp_m_base + mt * 16;\n"
"            CVT_E4M3_PAIR(a0[mt], mr + gid,     tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid + 8, tid4*4)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid,     tid4*4 + 16)\n"
"#else\n"
"            CVT_E4M3_PAIR(a1[mt], mr + gid,     tid4*4 + 16)\n"
"            CVT_E4M3_PAIR(a2[mt], mr + gid + 8, tid4*4)\n"
"#endif\n"
"            CVT_E4M3_PAIR(a3[mt], mr + gid + 8, tid4*4 + 16)\n"
"        }\n"
"#undef CVT_E4M3_PAIR\n"
"\n"
"        /* For each N-tile: read B frags directly from W (global), then issue\n"
"         * MMA for all M-tiles with that shared B. */\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < TC128_WARP_N; nt++) {\n"
"            int bc = out_base + warp_n_base + nt * 8 + gid;\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (bc < n_out && k + tid4*4 + 19 < n_in) {\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                b0 = *(const unsigned int *)(wp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(wp + tid4 * 4 + 16);\n"
"            } else if (bc < n_out) {\n"
"                unsigned char tmp[8] = {0,0,0,0,0,0,0,0};\n"
"                const unsigned char *wp = W + (size_t)bc * n_in + k;\n"
"                for (int j = 0; j < 4; j++) {\n"
"                    int kk = k + tid4*4 + j;\n"
"                    if (kk < n_in) tmp[j] = wp[tid4*4 + j];\n"
"                    int kk2 = k + tid4*4 + 16 + j;\n"
"                    if (kk2 < n_in) tmp[4+j] = wp[tid4*4 + 16 + j];\n"
"                }\n"
"                b0 = ((unsigned int)tmp[0]) | ((unsigned int)tmp[1] << 8) | ((unsigned int)tmp[2] << 16) | ((unsigned int)tmp[3] << 24);\n"
"                b1 = ((unsigned int)tmp[4]) | ((unsigned int)tmp[5] << 8) | ((unsigned int)tmp[6] << 16) | ((unsigned int)tmp[7] << 24);\n"
"            }\n"
"#pragma unroll\n"
"            for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(d0[mt][nt]), \"=f\"(d1[mt][nt]), \"=f\"(d2[mt][nt]), \"=f\"(d3[mt][nt])\n"
"                    : \"r\"(a0[mt]), \"r\"(a1[mt]), \"r\"(a2[mt]), \"r\"(a3[mt]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(d0[mt][nt]), \"f\"(d1[mt][nt]), \"f\"(d2[mt][nt]), \"f\"(d3[mt][nt])\n"
"                );\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    float sc = w_scale * x_scale;\n"
"#pragma unroll\n"
"    for (int mt = 0; mt < TC128_WARP_M; mt++) {\n"
"        int mr = warp_m_base + mt * 16;\n"
"        int yr0 = tok_base + mr + gid;\n"
"        int yr1 = tok_base + mr + gid + 8;\n"
"#pragma unroll\n"
"        for (int nt = 0; nt < TC128_WARP_N; nt++) {\n"
"            int yc0 = out_base + warp_n_base + nt * 8 + tid4 * 2;\n"
"            int yc1 = yc0 + 1;\n"
"            float bv0 = (bias && yc0 < n_out) ? bias[yc0] : 0.0f;\n"
"            float bv1 = (bias && yc1 < n_out) ? bias[yc1] : 0.0f;\n"
"            if (yr0 < n_tok && yc0 < n_out) Y[(long)yr0 * n_out + yc0] = d0[mt][nt] * sc + bv0;\n"
"            if (yr0 < n_tok && yc1 < n_out) Y[(long)yr0 * n_out + yc1] = d1[mt][nt] * sc + bv1;\n"
"            if (yr1 < n_tok && yc0 < n_out) Y[(long)yr1 * n_out + yc0] = d2[mt][nt] * sc + bv0;\n"
"            if (yr1 < n_tok && yc1 < n_out) Y[(long)yr1 * n_out + yc1] = d3[mt][nt] * sc + bv1;\n"
"        }\n"
"    }\n"
"}\n"
"#endif\n"

/* ============================================================================
 * FP8 Flash Attention helper: F32 -> e4m3 quantization with shared per-tensor
 * scale. Two-pass: caller pre-zeroes max_buf, then runs reduce_max_abs_f32 to
 * compute max, then quantize_to_fp8_e4m3 to write the FP8 buffer + scale.
 * ============================================================================ */
"__global__ void zero_f32(float *p, int n) {\n"
"    int i = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (i < n) p[i] = 0.0f;\n"
"}\n"

"__global__ void reduce_max_abs_f32(float *out_max, const float *in, int n) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= n) return;\n"
"    float v = fabsf(in[idx]);\n"
"    /* warp reduce */\n"
"    for (int off = 16; off > 0; off >>= 1) {\n"
"        float other = __shfl_xor_sync(0xFFFFFFFF, v, off);\n"
"        if (other > v) v = other;\n"
"    }\n"
"    if ((threadIdx.x & 31) == 0 && v > 0.0f) {\n"
"        /* atomicMax on int interpretation works for non-negative IEEE f32 */\n"
"        int new_int; memcpy(&new_int, &v, 4);\n"
"        atomicMax((int*)out_max, new_int);\n"
"    }\n"
"}\n"

"__global__ void quantize_to_fp8_e4m3(unsigned char *out, float *out_scale,\n"
"                                      const float *in, const float *max_buf, int n) {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    float max_abs = max_buf[0];\n"
"    float scale = (max_abs > 1e-30f) ? (max_abs / 448.0f) : 1.0f;\n"
"    if (idx == 0) *out_scale = scale;\n"
"    if (idx >= n) return;\n"
"    float v = in[idx] / scale;\n"
"    unsigned short pair;\n"
"    /* d=pair, a=0, b=v -> low byte = e4m3(v), high byte = e4m3(0) */\n"
"    asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %1, %2;\" : \"=h\"(pair) : \"f\"(0.0f), \"f\"(v));\n"
"    out[idx] = (unsigned char)(pair & 0xFF);\n"
"}\n"

/* ============================================================================
 * FP8 Flash Attention (mma.sync m16n8k32 e4m3, sm_89+).
 * 1 warp per CTA, 16 Q rows per CTA, BKV=32 KV tile.
 * Grid: (n_heads, ceil(N/16))
 * Block: 32 threads (1 warp)
 * Shared: K[32,128] + V_T[128,32] + P[16,32 f32] = 4KB+4KB+2KB = 10KB
 *
 * Q,K,V: [N, n_heads, head_dim] uint8 e4m3 with per-tensor scales sQ, sK, sV.
 * P scale = 1/448 (P after softmax is in (0,1], use full e4m3 range).
 * ============================================================================ */
/* Scalar reference: same FP8 buffers, scalar dot products. Used as a debug
 * cross-check for the MMA version. Same launch params. */
"__global__ void flash_attn_fp8_ref(\n"
"    float *__restrict__ out,\n"
"    const unsigned char *__restrict__ Qb,\n"
"    const unsigned char *__restrict__ Kb,\n"
"    const unsigned char *__restrict__ Vb,\n"
"    int N, int n_heads, int head_dim,\n"
"    const float *__restrict__ scales) {\n"
"    float sQ = scales[0], sK = scales[1], sV = scales[2];\n"
"    int h = blockIdx.x;\n"
"    int qi = blockIdx.y * 32 + threadIdx.x;  /* one Q row per thread */\n"
"    if (qi >= N) return;\n"
"    int dim = n_heads * head_dim;\n"
"    /* Dequantize Q row to local f32 (head_dim=128) */\n"
"    float q_loc[128];\n"
"    for (int d = 0; d < head_dim; d++)\n"
"        q_loc[d] = (float)Qb[(long)qi * dim + h * head_dim + d] * 0.0f;\n"
"    /* Above is just a placeholder; do real dequant via cvt */\n"
"    for (int d = 0; d < head_dim; d++) {\n"
"        unsigned char b = Qb[(long)qi * dim + h * head_dim + d];\n"
"        q_loc[d] = fp8e4m3_to_f32(b) * sQ;\n"
"    }\n"
"    float scale = rsqrtf((float)head_dim);\n"
"    float m_i = -1e30f, l_i = 0.0f;\n"
"    float O_loc[128];\n"
"    for (int d = 0; d < head_dim; d++) O_loc[d] = 0.0f;\n"
"    for (int kj = 0; kj < N; kj++) {\n"
"        float dot = 0.0f;\n"
"        for (int d = 0; d < head_dim; d++) {\n"
"            unsigned char b = Kb[(long)kj * dim + h * head_dim + d];\n"
"            dot += q_loc[d] * (fp8e4m3_to_f32(b) * sK);\n"
"        }\n"
"        float score = dot * scale;\n"
"        float new_m = fmaxf(m_i, score);\n"
"        float alpha = expf(m_i - new_m);\n"
"        float p = expf(score - new_m);\n"
"        l_i = l_i * alpha + p;\n"
"        for (int d = 0; d < head_dim; d++) {\n"
"            unsigned char b = Vb[(long)kj * dim + h * head_dim + d];\n"
"            O_loc[d] = O_loc[d] * alpha + p * (fp8e4m3_to_f32(b) * sV);\n"
"        }\n"
"        m_i = new_m;\n"
"    }\n"
"    float inv_l = (l_i > 0.0f) ? 1.0f / l_i : 0.0f;\n"
"    for (int d = 0; d < head_dim; d++)\n"
"        out[(long)qi * dim + h * head_dim + d] = O_loc[d] * inv_l;\n"
"}\n"

"#if __CUDA_ARCH__ >= 890\n"
"#define FAFP8_BKV    32\n"
"#define FAFP8_M      16\n"
"#define FAFP8_HD    128\n"
"#define FAFP8_NWARPS 4\n"
"__global__ void flash_attn_fp8(\n"
"    float *__restrict__ out,\n"
"    const unsigned char *__restrict__ Qb,\n"
"    const unsigned char *__restrict__ Kb,\n"
"    const unsigned char *__restrict__ Vb,\n"
"    int N, int n_heads, int head_dim,\n"
"    const float *__restrict__ scales) {\n"
"    float sQ = scales[0], sK = scales[1], sV = scales[2];\n"
"    int h = blockIdx.x;\n"
"    int warp = threadIdx.x / 32;\n"
"    int lane = threadIdx.x & 31;\n"
"    int gid = lane / 4;\n"
"    int tid4 = lane & 3;\n"
"    /* Each warp owns its own 16 Q rows (block covers 64 Q rows total) */\n"
"    int q_base = blockIdx.y * (FAFP8_M * FAFP8_NWARPS) + warp * FAFP8_M;\n"
"    int dim = n_heads * head_dim;\n"
"\n"
"    /* ----- Load Q into A-fragment registers (4 K-chunks of 32) ----- */\n"
"    unsigned int q_frag[4][4];\n"
"#pragma unroll\n"
"    for (int kc = 0; kc < 4; kc++) {\n"
"        int k0 = kc * 32;\n"
"        int row0 = q_base + gid;\n"
"        int row1 = q_base + gid + 8;\n"
"        const unsigned char *qbase0 = (row0 < N) ? Qb + (long)row0 * dim + h * head_dim : (const unsigned char *)0;\n"
"        const unsigned char *qbase1 = (row1 < N) ? Qb + (long)row1 * dim + h * head_dim : (const unsigned char *)0;\n"
"        unsigned int z = 0;\n"
"        q_frag[kc][0] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*4)      : z;\n"
"#if __CUDA_ARCH__ >= 1200\n"
"        q_frag[kc][1] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*4)      : z;\n"
"        q_frag[kc][2] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*4 + 16) : z;\n"
"#else\n"
"        q_frag[kc][1] = qbase0 ? *(const unsigned int *)(qbase0 + k0 + tid4*4 + 16) : z;\n"
"        q_frag[kc][2] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*4)      : z;\n"
"#endif\n"
"        q_frag[kc][3] = qbase1 ? *(const unsigned int *)(qbase1 + k0 + tid4*4 + 16) : z;\n"
"    }\n"
"\n"
"    /* O accumulator: 16 N-iters (head_dim=128 / N=8) × 4 floats per thread per N-iter */\n"
"    float O[16][4];\n"
"#pragma unroll\n"
"    for (int i = 0; i < 16; i++) {\n"
"        O[i][0] = 0.0f; O[i][1] = 0.0f; O[i][2] = 0.0f; O[i][3] = 0.0f;\n"
"    }\n"
"    /* Per-row state (each thread has 2 row groups: gid, gid+8) */\n"
"    float m_state[2] = {-1e30f, -1e30f};\n"
"    float l_state[2] = {0.0f, 0.0f};\n"
"\n"
"    float qk_scale = sQ * sK * rsqrtf((float)head_dim);\n"
"\n"
"    extern __shared__ unsigned char fa_smem[];\n"
"    unsigned char *smK  = fa_smem;                                               /* [BKV, hd] */\n"
"    unsigned char *smVT = smK + FAFP8_BKV * FAFP8_HD;                            /* [hd, BKV] */\n"
"    float *smP_all = (float*)(smVT + FAFP8_HD * FAFP8_BKV);                      /* [NWARPS * 16 * BKV] */\n"
"    float *smP = smP_all + warp * 16 * FAFP8_BKV;                                /* this warp's slice */\n"
"\n"
"    int n_kv_tiles = (N + FAFP8_BKV - 1) / FAFP8_BKV;\n"
"    for (int kvt = 0; kvt < n_kv_tiles; kvt++) {\n"
"        int kv_base = kvt * FAFP8_BKV;\n"
"\n"
"        /* Cooperative load: K row-major [BKV, hd], V transposed [hd, BKV]. All 128 threads. */\n"
"        for (int idx = threadIdx.x; idx < FAFP8_BKV * FAFP8_HD; idx += FAFP8_NWARPS * 32) {\n"
"            int kr = idx / FAFP8_HD, kd = idx % FAFP8_HD;\n"
"            int row = kv_base + kr;\n"
"            unsigned char kk = (row < N) ? Kb[(long)row * dim + h * head_dim + kd] : 0;\n"
"            unsigned char vv = (row < N) ? Vb[(long)row * dim + h * head_dim + kd] : 0;\n"
"            smK[kr * FAFP8_HD + kd] = kk;\n"
"            smVT[kd * FAFP8_BKV + kr] = vv;\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        /* S = Q · K^T : [16, BKV=32]. 4 N-iters of m16n8k32, 4 K-chunks per. */\n"
"        float S[4][4];\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            S[ni][0] = 0.0f; S[ni][1] = 0.0f; S[ni][2] = 0.0f; S[ni][3] = 0.0f;\n"
"        }\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int n_base = ni * 8;\n"
"            int b_col = n_base + gid;  /* col of mma B = row of K in smK */\n"
"#pragma unroll\n"
"            for (int kc = 0; kc < 4; kc++) {\n"
"                int k_off = kc * 32;\n"
"                unsigned int b0 = 0, b1 = 0;\n"
"                if (b_col < FAFP8_BKV) {\n"
"                    const unsigned char *kp = smK + b_col * FAFP8_HD + k_off;\n"
"                    b0 = *(const unsigned int *)(kp + tid4 * 4);\n"
"                    b1 = *(const unsigned int *)(kp + tid4 * 4 + 16);\n"
"                }\n"
"                asm volatile(\n"
"                    \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                    \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                    : \"=f\"(S[ni][0]), \"=f\"(S[ni][1]), \"=f\"(S[ni][2]), \"=f\"(S[ni][3])\n"
"                    : \"r\"(q_frag[kc][0]), \"r\"(q_frag[kc][1]), \"r\"(q_frag[kc][2]), \"r\"(q_frag[kc][3]),\n"
"                      \"r\"(b0), \"r\"(b1),\n"
"                      \"f\"(S[ni][0]), \"f\"(S[ni][1]), \"f\"(S[ni][2]), \"f\"(S[ni][3])\n"
"                );\n"
"            }\n"
"        }\n"
"\n"
"        /* Apply qk_scale and mask out-of-bounds KV cols. D-fragment col mapping:\n"
"         * d0=col tid4*2, d1=col tid4*2+1, d2=col tid4*2, d3=col tid4*2+1 (rows differ). */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            int kvr0 = kv_base + col0;\n"
"            int kvr1 = kv_base + col1;\n"
"            S[ni][0] = (kvr0 < N) ? S[ni][0] * qk_scale : -1e30f;\n"
"            S[ni][1] = (kvr1 < N) ? S[ni][1] * qk_scale : -1e30f;\n"
"            S[ni][2] = (kvr0 < N) ? S[ni][2] * qk_scale : -1e30f;\n"
"            S[ni][3] = (kvr1 < N) ? S[ni][3] * qk_scale : -1e30f;\n"
"        }\n"
"\n"
"        /* Online softmax: per-row max */\n"
"        float new_m[2], alpha[2];\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"            float my = -1e30f;\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < 4; ni++) {\n"
"                my = fmaxf(my, S[ni][rp*2 + 0]);\n"
"                my = fmaxf(my, S[ni][rp*2 + 1]);\n"
"            }\n"
"            /* Reduce across the 4 lanes that share gid (xor 1, 2 over tid4) */\n"
"            float o1 = __shfl_xor_sync(0xFFFFFFFF, my, 1); my = fmaxf(my, o1);\n"
"            float o2 = __shfl_xor_sync(0xFFFFFFFF, my, 2); my = fmaxf(my, o2);\n"
"            new_m[rp] = fmaxf(m_state[rp], my);\n"
"            alpha[rp] = expf(m_state[rp] - new_m[rp]);\n"
"        }\n"
"\n"
"        /* Rescale O and l */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            O[ni][0] *= alpha[0]; O[ni][1] *= alpha[0];\n"
"            O[ni][2] *= alpha[1]; O[ni][3] *= alpha[1];\n"
"        }\n"
"        l_state[0] *= alpha[0]; l_state[1] *= alpha[1];\n"
"\n"
"        /* P = exp(S - new_m). Scale up by 448 so e4m3 conversion uses full range. */\n"
"        float P_data[4][4];\n"
"        float row_sum[2] = {0.0f, 0.0f};\n"
"#pragma unroll\n"
"        for (int rp = 0; rp < 2; rp++) {\n"
"#pragma unroll\n"
"            for (int ni = 0; ni < 4; ni++) {\n"
"                float p0 = expf(S[ni][rp*2 + 0] - new_m[rp]);\n"
"                float p1 = expf(S[ni][rp*2 + 1] - new_m[rp]);\n"
"                P_data[ni][rp*2 + 0] = p0;\n"
"                P_data[ni][rp*2 + 1] = p1;\n"
"                row_sum[rp] += p0 + p1;\n"
"            }\n"
"        }\n"
"        float r0a = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 1); row_sum[0] += r0a;\n"
"        float r0b = __shfl_xor_sync(0xFFFFFFFF, row_sum[0], 2); row_sum[0] += r0b;\n"
"        float r1a = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 1); row_sum[1] += r1a;\n"
"        float r1b = __shfl_xor_sync(0xFFFFFFFF, row_sum[1], 2); row_sum[1] += r1b;\n"
"        l_state[0] += row_sum[0]; l_state[1] += row_sum[1];\n"
"        m_state[0] = new_m[0]; m_state[1] = new_m[1];\n"
"\n"
"        /* Stash P (scaled by 448) into smP for re-read as A-fragment */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 4; ni++) {\n"
"            int col0 = ni * 8 + tid4 * 2;\n"
"            int col1 = col0 + 1;\n"
"            smP[gid * FAFP8_BKV + col0]     = P_data[ni][0] * 448.0f;\n"
"            smP[gid * FAFP8_BKV + col1]     = P_data[ni][1] * 448.0f;\n"
"            smP[(gid+8) * FAFP8_BKV + col0] = P_data[ni][2] * 448.0f;\n"
"            smP[(gid+8) * FAFP8_BKV + col1] = P_data[ni][3] * 448.0f;\n"
"        }\n"
"        __syncwarp();  /* smP is per-warp, only warp-local barrier needed */\n"
"\n"
"        /* Convert P to FP8 A-fragment (1 K-chunk: BKV=32 = K) */\n"
"        unsigned int p_frag[4];\n"
"        {\n"
"            int row0 = gid;\n"
"            int row1 = gid + 8;\n"
"#define CVTPF(reg, row, c) { \\\n"
"                unsigned short lo, hi; \\\n"
"                asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(lo) : \\\n"
"                    \"f\"(smP[(row)*FAFP8_BKV + (c)]), \"f\"(smP[(row)*FAFP8_BKV + (c)+1])); \\\n"
"                asm(\"cvt.rn.satfinite.e4m3x2.f32 %0, %2, %1;\" : \"=h\"(hi) : \\\n"
"                    \"f\"(smP[(row)*FAFP8_BKV + (c)+2]), \"f\"(smP[(row)*FAFP8_BKV + (c)+3])); \\\n"
"                reg = (unsigned int)lo | ((unsigned int)hi << 16); }\n"
"            CVTPF(p_frag[0], row0, tid4*4)\n"
"#if __CUDA_ARCH__ >= 1200\n"
"            CVTPF(p_frag[1], row1, tid4*4)\n"
"            CVTPF(p_frag[2], row0, tid4*4 + 16)\n"
"#else\n"
"            CVTPF(p_frag[1], row0, tid4*4 + 16)\n"
"            CVTPF(p_frag[2], row1, tid4*4)\n"
"#endif\n"
"            CVTPF(p_frag[3], row1, tid4*4 + 16)\n"
"#undef CVTPF\n"
"        }\n"
"\n"
"        /* O += P · V via mma. 16 N-iters of m16n8 (head_dim=128/8). 1 K-iter (BKV=32). */\n"
"#pragma unroll\n"
"        for (int ni = 0; ni < 16; ni++) {\n"
"            int n_base = ni * 8;\n"
"            int b_col = n_base + gid;  /* head_dim col */\n"
"            unsigned int b0 = 0, b1 = 0;\n"
"            if (b_col < head_dim) {\n"
"                const unsigned char *vp = smVT + b_col * FAFP8_BKV;\n"
"                b0 = *(const unsigned int *)(vp + tid4 * 4);\n"
"                b1 = *(const unsigned int *)(vp + tid4 * 4 + 16);\n"
"            }\n"
"            float d0 = O[ni][0], d1 = O[ni][1], d2 = O[ni][2], d3 = O[ni][3];\n"
"            asm volatile(\n"
"                \"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\\n\\t\"\n"
"                \"    {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\"\n"
"                : \"=f\"(d0), \"=f\"(d1), \"=f\"(d2), \"=f\"(d3)\n"
"                : \"r\"(p_frag[0]), \"r\"(p_frag[1]), \"r\"(p_frag[2]), \"r\"(p_frag[3]),\n"
"                  \"r\"(b0), \"r\"(b1),\n"
"                  \"f\"(d0), \"f\"(d1), \"f\"(d2), \"f\"(d3)\n"
"            );\n"
"            O[ni][0] = d0; O[ni][1] = d1; O[ni][2] = d2; O[ni][3] = d3;\n"
"        }\n"
"        __syncthreads();  /* before next tile overwrites shared smK/smVT */\n"
"    }\n"
"\n"
"    /* Final write: descale by sV/448 (P scale was 1/448), divide by l_state */\n"
"    int row0 = q_base + gid;\n"
"    int row1 = q_base + gid + 8;\n"
"    float inv_l0 = (l_state[0] > 0.0f) ? 1.0f / l_state[0] : 0.0f;\n"
"    float inv_l1 = (l_state[1] > 0.0f) ? 1.0f / l_state[1] : 0.0f;\n"
"    float fac = sV * (1.0f / 448.0f);\n"
"#pragma unroll\n"
"    for (int ni = 0; ni < 16; ni++) {\n"
"        int col0 = ni * 8 + tid4 * 2;\n"
"        int col1 = col0 + 1;\n"
"        if (row0 < N && col0 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col0] = O[ni][0] * fac * inv_l0;\n"
"        if (row0 < N && col1 < head_dim)\n"
"            out[(long)row0 * dim + h * head_dim + col1] = O[ni][1] * fac * inv_l0;\n"
"        if (row1 < N && col0 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col0] = O[ni][2] * fac * inv_l1;\n"
"        if (row1 < N && col1 < head_dim)\n"
"            out[(long)row1 * dim + h * head_dim + col1] = O[ni][3] * fac * inv_l1;\n"
"    }\n"
"}\n"
"#endif\n"
;

#endif /* CUDA_FP8_MMA_KERNELS_H */
