/* Flat-layout FA2 kernel for LLM runner */
/* Modified from cuda/fa2/cuda_fa2_kernels.h */
/* Uses hstride_q/hstride_kv for global memory strides */
/* Supports [S, H*D] flat KV cache layout */
"typedef unsigned short dt_t;\n"
"typedef unsigned int   uint32_t;\n"
"\n"
"#ifndef FA2_D\n"
"#define FA2_D 128\n"
"#endif\n"
"#ifndef FA2_BR\n"
"#define FA2_BR 64\n"
"#endif\n"
"#ifndef FA2_BC\n"
"#define FA2_BC 32\n"
"#endif\n"
"#ifndef FA2_CAUSAL\n"
"#define FA2_CAUSAL 0\n"
"#endif\n"
"\n"
"#define FA2_DK  (FA2_D / 16)\n"   /* k-iters of mma along D for Q@K^T   */
"#define FA2_BCN (FA2_BC / 8)\n"   /* N-tiles along BC for Q@K^T         */
"#define FA2_BCK (FA2_BC / 16)\n"  /* k-iters along BC for P@V           */
"#define FA2_DN  (FA2_D  / 8)\n"   /* N-tiles along D for P@V (= O frags)*/
"#define FA2_DP  (FA2_D + 8)\n"    /* padded sK/sV row stride (LDS-32 free)*/
"#define FA2_NTHR (FA2_BR / 16 * 32)\n" /* threads/CTA = (BR/16) warps x 32 */
"\n"
"#ifdef FA2_BF16\n"
"#define FA2_MMA \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\"\n"
"__device__ __forceinline__ dt_t f2dt(float f){\n"
"    dt_t h; asm(\"cvt.rn.bf16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"__device__ __forceinline__ uint32_t pack2(float lo, float hi){\n"
"    dt_t a, b;\n"
"    asm(\"cvt.rn.bf16.f32 %0, %1;\" : \"=h\"(a) : \"f\"(lo));\n"
"    asm(\"cvt.rn.bf16.f32 %0, %1;\" : \"=h\"(b) : \"f\"(hi));\n"
"    return ((uint32_t)b << 16) | (uint32_t)a;\n"
"}\n"
"#else\n"
"#define FA2_MMA \"mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32\"\n"
"__device__ __forceinline__ dt_t f2dt(float f){\n"
"    dt_t h; asm(\"cvt.rn.f16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"__device__ __forceinline__ uint32_t pack2(float lo, float hi){\n"
"    uint32_t r;\n"
"    asm(\"{ .reg .b16 a, b; cvt.rn.f16.f32 a, %1; cvt.rn.f16.f32 b, %2;\\n\"\n"
"        \"  mov.b32 %0, {a, b}; }\" : \"=r\"(r) : \"f\"(lo), \"f\"(hi));\n"
"    return r;\n"
"}\n"
"#endif\n"
"\n"
"#ifdef FA2_MINBLK\n"
"#define FA2_LB __launch_bounds__(FA2_NTHR, FA2_MINBLK)\n"
"#else\n"
"#define FA2_LB __launch_bounds__(FA2_NTHR)\n"
"#endif\n"
"extern \"C\" __global__\n"
"FA2_LB\n"
"void fa2_attn(dt_t *O,\n"
"              const dt_t *Q,\n"
"              const dt_t *K,\n"
"              const dt_t *V,\n"
"              int S, int D_in, float scale) {\n"
"    /* D_in must equal FA2_D (caller responsible). */\n"
"    const float LOG2E = 1.4426950408889634f;\n"
"    float lscale = scale * LOG2E;          /* fold base-2 into the score scale */\n"
"    int bh   = blockIdx.y;\n"
"    int wid  = threadIdx.x >> 5;\n"
"    int lane = threadIdx.x & 31;\n"
"    int warp_q0 = blockIdx.x * FA2_BR + wid * 16;\n"
"\n"
"    int row_a = lane >> 2;            /* 0..7  */\n"
"    int row_b = row_a + 8;            /* 8..15 */\n"
"    int col_g = (lane & 3) * 2;       /* 0,2,4,6 */\n"
"\n"
"    const dt_t *Qh = Q + (size_t)bh * FA2_D;\n"
"    int kv_bh = bh / gqa_ratio; const dt_t *Kh = K + (size_t)kv_bh * FA2_D;\n"
"    const dt_t *Vh = V + (size_t)kv_bh * FA2_D;\n"
"          dt_t *Oh = O + (size_t)bh * FA2_D;\n"
"\n"
"    /* ---- Q frag (held across all K-tiles): A-frag of m16n8k16 Q@K^T ---- */\n"
"    uint32_t qfrag[FA2_DK][4];\n"
"    int gqr_a = warp_q0 + row_a;\n"
"    int gqr_b = warp_q0 + row_b;\n"
"    int valid_a = (gqr_a < S);\n"
"    int valid_b = (gqr_b < S);\n"
"    for (int kk = 0; kk < FA2_DK; kk++) {\n"
"        int kbase = kk * 16;\n"
"        const dt_t *qa_lo = Qh + (size_t)gqr_a * hstride_q + kbase + col_g;\n"
"        const dt_t *qb_lo = Qh + (size_t)gqr_b * hstride_q + kbase + col_g;\n"
"        qfrag[kk][0] = valid_a ? *(const uint32_t *)qa_lo       : 0u;\n"
"        qfrag[kk][1] = valid_b ? *(const uint32_t *)qb_lo       : 0u;\n"
"        qfrag[kk][2] = valid_a ? *(const uint32_t *)(qa_lo + 8) : 0u;\n"
"        qfrag[kk][3] = valid_b ? *(const uint32_t *)(qb_lo + 8) : 0u;\n"
"    }\n"
"\n"
"    float ofrag[FA2_DN][4];\n"
"    for (int n = 0; n < FA2_DN; n++) for (int i = 0; i < 4; i++) ofrag[n][i] = 0.0f;\n"
"    float m_a = -1e30f, m_b = -1e30f, l_a = 0.0f, l_b = 0.0f;\n"
"\n"
"    /* ---- SMEM: double-buffered K + V, row stride padded to FA2_DP ---- */\n"
"    extern __shared__ dt_t smem[];\n"
"    dt_t *sK0  = smem;\n"
"    dt_t *sK1  = sK0  + FA2_BC * FA2_DP;\n"
"    dt_t *sV0  = sK1  + FA2_BC * FA2_DP;\n"
"    dt_t *sV1  = sV0  + FA2_BC * FA2_DP;\n"
"    dt_t *sK_buf[2] = { sK0, sK1 };\n"
"    dt_t *sV_buf[2] = { sV0, sV1 };\n"
"\n"
"    int total_u4 = (FA2_BC * FA2_D) / 8;   /* uint4 (8 halves) per K/V tile */\n"
"    int row_u4   = FA2_D / 8;\n"
"    /* causal: this CTA's queries span [bx*BR, bx*BR+BR); KV beyond max q row is masked */\n"
"    int s_eff = S;\n"
"#if FA2_CAUSAL\n"
"    int q_blk_max = blockIdx.x * FA2_BR + FA2_BR;  /* exclusive */\n"
"    if (q_blk_max < s_eff) s_eff = q_blk_max;\n"
"#endif\n"
"    int n_tiles  = (s_eff + FA2_BC - 1) / FA2_BC;\n"
"\n"
"    /* ---- Prologue: cp.async tile 0 into buffer 0 ---- */\n"
"    {\n"
"        dt_t *dK_ = sK_buf[0];\n"
"        dt_t *dV_ = sV_buf[0];\n"
"        for (int idx = threadIdx.x; idx < total_u4; idx += blockDim.x) {\n"
"            int j_  = idx / row_u4;\n"
"            int dd_ = (idx - j_ * row_u4) * 8;\n"
"            unsigned dst_k = __cvta_generic_to_shared(dK_ + j_ * FA2_DP + dd_);\n"
"            unsigned dst_v = __cvta_generic_to_shared(dV_ + j_ * FA2_DP + dd_);\n"
"            const void *src_k = (const void *)(Kh + (size_t)j_ * hstride_kv + dd_);\n"
"            const void *src_v = (const void *)(Vh + (size_t)j_ * hstride_kv + dd_);\n"
"            int src_bytes = (j_ < S) ? 16 : 0;\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_k), \"l\"(src_k), \"r\"(src_bytes));\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_v), \"l\"(src_v), \"r\"(src_bytes));\n"
"        }\n"
"    }\n"
"    asm volatile(\"cp.async.commit_group;\\n\" ::);\n"
"\n"
"    int ldm_row_off  = lane & 7;\n"
"    int ldm_col_xtra = (lane & 8) ? 8 : 0;\n"
"\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int cur = t & 1;\n"
"        int nxt = 1 - cur;\n"
"        int kv0 = t * FA2_BC;\n"
"\n"
"        if (t + 1 < n_tiles) {\n"
"            int kv0n = (t + 1) * FA2_BC;\n"
"            dt_t *dK_ = sK_buf[nxt];\n"
"            dt_t *dV_ = sV_buf[nxt];\n"
"            for (int idx = threadIdx.x; idx < total_u4; idx += blockDim.x) {\n"
"                int j_  = idx / row_u4;\n"
"                int dd_ = (idx - j_ * row_u4) * 8;\n"
"                int kv_ = kv0n + j_;\n"
"                unsigned dst_k = __cvta_generic_to_shared(dK_ + j_ * FA2_DP + dd_);\n"
"                unsigned dst_v = __cvta_generic_to_shared(dV_ + j_ * FA2_DP + dd_);\n"
"                const void *src_k = (const void *)(Kh + (size_t)kv_ * hstride_kv + dd_);\n"
"                const void *src_v = (const void *)(Vh + (size_t)kv_ * hstride_kv + dd_);\n"
"                int src_bytes = (kv_ < S) ? 16 : 0;\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_k), \"l\"(src_k), \"r\"(src_bytes));\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst_v), \"l\"(src_v), \"r\"(src_bytes));\n"
"            }\n"
"            asm volatile(\"cp.async.commit_group;\\n\" ::);\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\" ::);\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\" ::);\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        dt_t *sK = sK_buf[cur];\n"
"        dt_t *sV = sV_buf[cur];\n"
"\n"
"        /* ---- Q @ K^T -> sfrag[BCN][4] (m16n8k16, ldmatrix.x2 for B-frag) ---- */\n"
"        float sfrag[FA2_BCN][4];\n"
"        for (int n = 0; n < FA2_BCN; n++) for (int i = 0; i < 4; i++) sfrag[n][i] = 0.0f;\n"
"        for (int kk = 0; kk < FA2_DK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            for (int nn = 0; nn < FA2_BCN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                unsigned saddr = __cvta_generic_to_shared(\n"
"                    sK + (nbase + ldm_row_off) * FA2_DP + kbase + ldm_col_xtra);\n"
"                uint32_t b0, b1;\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x2.shared.b16 {%0, %1}, [%2];\"\n"
"                    : \"=r\"(b0), \"=r\"(b1) : \"r\"(saddr));\n"
"                uint32_t a0 = qfrag[kk][0], a1 = qfrag[kk][1], a2 = qfrag[kk][2], a3 = qfrag[kk][3];\n"
"                float c0 = sfrag[nn][0], c1 = sfrag[nn][1], c2 = sfrag[nn][2], c3 = sfrag[nn][3];\n"
"                asm(FA2_MMA\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                sfrag[nn][0] = c0; sfrag[nn][1] = c1; sfrag[nn][2] = c2; sfrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"\n"
"        /* ---- scale + OOB mask (+ causal mask) ---- */\n"
"        for (int nn = 0; nn < FA2_BCN; nn++) {\n"
"            int kv_c0 = kv0 + nn * 8 + col_g + 0;\n"
"            int kv_c1 = kv0 + nn * 8 + col_g + 1;\n"
"            int va0 = (kv_c0 < S), va1 = (kv_c1 < S);\n"
"            int vb0 = va0, vb1 = va1;\n"
"#if FA2_CAUSAL\n"
"            va0 = va0 && (kv_c0 <= gqr_a); va1 = va1 && (kv_c1 <= gqr_a);\n"
"            vb0 = vb0 && (kv_c0 <= gqr_b); vb1 = vb1 && (kv_c1 <= gqr_b);\n"
"#endif\n"
"            sfrag[nn][0] = va0 ? sfrag[nn][0] * lscale : -1e30f;\n"
"            sfrag[nn][1] = va1 ? sfrag[nn][1] * lscale : -1e30f;\n"
"            sfrag[nn][2] = vb0 ? sfrag[nn][2] * lscale : -1e30f;\n"
"            sfrag[nn][3] = vb1 ? sfrag[nn][3] * lscale : -1e30f;\n"
"        }\n"
"\n"
"        /* ---- row max over the 4-thread row group ---- */\n"
"        float mx_a = -1e30f, mx_b = -1e30f;\n"
"        for (int nn = 0; nn < FA2_BCN; nn++) {\n"
"            mx_a = fmaxf(mx_a, fmaxf(sfrag[nn][0], sfrag[nn][1]));\n"
"            mx_b = fmaxf(mx_b, fmaxf(sfrag[nn][2], sfrag[nn][3]));\n"
"        }\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 1));\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 2));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 1));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 2));\n"
"\n"
"        float m_new_a = fmaxf(m_a, mx_a);\n"
"        float m_new_b = fmaxf(m_b, mx_b);\n"
"        float alpha_a = exp2f(m_a - m_new_a);\n"
"        float alpha_b = exp2f(m_b - m_new_b);\n"
"        l_a *= alpha_a; l_b *= alpha_b;\n"
"        for (int n = 0; n < FA2_DN; n++) {\n"
"            ofrag[n][0] *= alpha_a; ofrag[n][1] *= alpha_a;\n"
"            ofrag[n][2] *= alpha_b; ofrag[n][3] *= alpha_b;\n"
"        }\n"
"        m_a = m_new_a; m_b = m_new_b;\n"
"\n"
"        /* ---- P = exp2(S - m), pack to dt pfrag (A-frag of P@V) ---- */\n"
"        uint32_t pfrag[FA2_BCK][4];\n"
"        float rs_a = 0.0f, rs_b = 0.0f;\n"
"        for (int kk = 0; kk < FA2_BCK; kk++) {\n"
"            float p0 = exp2f(sfrag[2*kk    ][0] - m_a);\n"
"            float p1 = exp2f(sfrag[2*kk    ][1] - m_a);\n"
"            float p2 = exp2f(sfrag[2*kk    ][2] - m_b);\n"
"            float p3 = exp2f(sfrag[2*kk    ][3] - m_b);\n"
"            float p4 = exp2f(sfrag[2*kk + 1][0] - m_a);\n"
"            float p5 = exp2f(sfrag[2*kk + 1][1] - m_a);\n"
"            float p6 = exp2f(sfrag[2*kk + 1][2] - m_b);\n"
"            float p7 = exp2f(sfrag[2*kk + 1][3] - m_b);\n"
"            rs_a += p0 + p1 + p4 + p5;\n"
"            rs_b += p2 + p3 + p6 + p7;\n"
"            pfrag[kk][0] = pack2(p0, p1);\n"
"            pfrag[kk][1] = pack2(p2, p3);\n"
"            pfrag[kk][2] = pack2(p4, p5);\n"
"            pfrag[kk][3] = pack2(p6, p7);\n"
"        }\n"
"        rs_a += __shfl_xor_sync(0xffffffff, rs_a, 1);\n"
"        rs_a += __shfl_xor_sync(0xffffffff, rs_a, 2);\n"
"        rs_b += __shfl_xor_sync(0xffffffff, rs_b, 1);\n"
"        rs_b += __shfl_xor_sync(0xffffffff, rs_b, 2);\n"
"        l_a += rs_a; l_b += rs_b;\n"
"\n"
"        /* ---- P @ V via ldmatrix.x2.trans on sV[bc, d] row-major ---- */\n"
"        for (int kk = 0; kk < FA2_BCK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            int bc_row = kbase + ldm_row_off + ((lane & 8) ? 8 : 0);\n"
"            for (int nn = 0; nn < FA2_DN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                unsigned saddr = __cvta_generic_to_shared(sV + bc_row * FA2_DP + nbase);\n"
"                uint32_t b0, b1;\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x2.trans.shared.b16 {%0, %1}, [%2];\"\n"
"                    : \"=r\"(b0), \"=r\"(b1) : \"r\"(saddr));\n"
"                uint32_t a0 = pfrag[kk][0], a1 = pfrag[kk][1], a2 = pfrag[kk][2], a3 = pfrag[kk][3];\n"
"                float c0 = ofrag[nn][0], c1 = ofrag[nn][1], c2 = ofrag[nn][2], c3 = ofrag[nn][3];\n"
"                asm(FA2_MMA\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                ofrag[nn][0] = c0; ofrag[nn][1] = c1; ofrag[nn][2] = c2; ofrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    /* ---- epilogue: divide by l, store O ---- */\n"
"    float inv_a = (l_a > 0.0f) ? 1.0f / l_a : 0.0f;\n"
"    float inv_b = (l_b > 0.0f) ? 1.0f / l_b : 0.0f;\n"
"    for (int nn = 0; nn < FA2_DN; nn++) {\n"
"        int d_col = nn * 8 + col_g;\n"
"        if (gqr_a < S) {\n"
"            Oh[(size_t)gqr_a * hstride_q + d_col + 0] = f2dt(ofrag[nn][0] * inv_a);\n"
"            Oh[(size_t)gqr_a * hstride_q + d_col + 1] = f2dt(ofrag[nn][1] * inv_a);\n"
"        }\n"
"        if (gqr_b < S) {\n"
"            Oh[(size_t)gqr_b * hstride_q + d_col + 0] = f2dt(ofrag[nn][2] * inv_b);\n"
"            Oh[(size_t)gqr_b * hstride_q + d_col + 1] = f2dt(ofrag[nn][3] * inv_b);\n"
"        }\n"
"    }\n"
"}\n";

/* ---- FP8 FA2 kernel: e4m3 Q@K^T (m16n8k32) + bf16 P@V (m16n8k16) ----
 *
 * SageAttention-style mixed precision: Q,K are stored as e4m3 bytes with
 * per-tensor max-abs scales s_q,s_k (folded into the score scale by the host).
 * The softmax probabilities P live in [0,1] and quantize poorly to e4m3, so V
 * is kept in bf16 and P@V is the *identical* m16n8k16 bf16 path as fa2_attn.
 *
 * Q@K^T uses mma.sync.m16n8k32.f32.e4m3.e4m3.f32. The e4m3 A/B fragments are
 * read straight from SMEM as uint32 (4 bytes = 4 e4m3) — no ldmatrix (that's a
 * 16-bit op). K rows are padded to FA2_D+16 bytes so the strided uint32 reads
 * land conflict-free (b_col*(D+16)/4 % 32 cancels to lane). sm_120 uses the
 * standard m16n8k32 a0,a1,a2,a3 ordering (row0,row1 then +16-byte half).
 *
 * Host prepends: FA2_D, FA2_BR, FA2_BC, FA2_CAUSAL. Output O is bf16.
 * scale arg already carries (1/sqrt(D)) * s_q * s_k.
 */
static const char *k_fa2_attn_fp8_src =
"typedef unsigned short dt_t;\n"
"typedef unsigned char  e4m3_t;\n"
"typedef unsigned int   uint32_t;\n"
"\n"
"#ifndef FA2_D\n"
"#define FA2_D 128\n"
"#endif\n"
"#ifndef FA2_BR\n"
"#define FA2_BR 64\n"
"#endif\n"
"#ifndef FA2_BC\n"
"#define FA2_BC 32\n"
"#endif\n"
"#ifndef FA2_CAUSAL\n"
"#define FA2_CAUSAL 0\n"
"#endif\n"
"\n"
"#define FA2_DK32 (FA2_D / 32)\n"  /* k-iters of m16n8k32 along D for Q@K^T */
"#define FA2_BCN  (FA2_BC / 8)\n"  /* N-tiles along BC for Q@K^T            */
"#define FA2_BCK  (FA2_BC / 16)\n" /* k-iters along BC for P@V              */
"#define FA2_DN   (FA2_D  / 8)\n"  /* N-tiles along D for P@V (= O frags)   */
"#define FA2_DP   (FA2_D + 8)\n"   /* padded sV row stride (halves)         */
"#define FA2_KP   (FA2_D + 16)\n"  /* padded sK row stride (bytes)          */
"#define FA2_NTHR (FA2_BR / 16 * 32)\n" /* threads/CTA = (BR/16) warps x 32 */
"\n"
"#define FA2_PV \"mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32\"\n"
"__device__ __forceinline__ dt_t f2bf(float f){\n"
"    dt_t h; asm(\"cvt.rn.bf16.f32 %0, %1;\" : \"=h\"(h) : \"f\"(f)); return h;\n"
"}\n"
"__device__ __forceinline__ uint32_t packbf(float lo, float hi){\n"
"    dt_t a, b;\n"
"    asm(\"cvt.rn.bf16.f32 %0, %1;\" : \"=h\"(a) : \"f\"(lo));\n"
"    asm(\"cvt.rn.bf16.f32 %0, %1;\" : \"=h\"(b) : \"f\"(hi));\n"
"    return ((uint32_t)b << 16) | (uint32_t)a;\n"
"}\n"
"\n"
"#ifdef FA2_MINBLK\n"
"#define FA2_LB __launch_bounds__(FA2_NTHR, FA2_MINBLK)\n"
"#else\n"
"#define FA2_LB __launch_bounds__(FA2_NTHR)\n"
"#endif\n"
"extern \"C\" __global__\n"
"FA2_LB\n"
"void fa2_attn_fp8(dt_t *O,\n"
"                  const e4m3_t *Q,\n"
"                  const e4m3_t *K,\n"
"                  const dt_t   *V,\n"
"                  int S, int D_in, float scale) {\n"
"    const float LOG2E = 1.4426950408889634f;\n"
"    float lscale = scale * LOG2E;\n"
"    int bh   = blockIdx.y;\n"
"    int wid  = threadIdx.x >> 5;\n"
"    int lane = threadIdx.x & 31;\n"
"    int warp_q0 = blockIdx.x * FA2_BR + wid * 16;\n"
"\n"
"    int row_a = lane >> 2;            /* 0..7  (= gid) */\n"
"    int row_b = row_a + 8;            /* 8..15 */\n"
"    int col_g = (lane & 3) * 2;       /* 0,2,4,6 */\n"
"    int tid4  = lane & 3;\n"
"\n"
"    const e4m3_t *Qh = Q + (size_t)bh * S * FA2_D;\n"
"    const e4m3_t *Kh = K + (size_t)bh * S * FA2_D;\n"
"    const dt_t   *Vh = V + (size_t)bh * S * FA2_D;\n"
"          dt_t   *Oh = O + (size_t)bh * S * FA2_D;\n"
"\n"
"    /* ---- Q frag (held across K-tiles): m16n8k32 e4m3 A-frag, 4 regs/k32 ---- */\n"
"    uint32_t qfrag[FA2_DK32][4];\n"
"    int gqr_a = warp_q0 + row_a;\n"
"    int gqr_b = warp_q0 + row_b;\n"
"    int valid_a = (gqr_a < S);\n"
"    int valid_b = (gqr_b < S);\n"
"    for (int kk = 0; kk < FA2_DK32; kk++) {\n"
"        int k0 = kk * 32;\n"
"        const e4m3_t *qa = Qh + (size_t)gqr_a * FA2_D + k0 + tid4 * 4;\n"
"        const e4m3_t *qb = Qh + (size_t)gqr_b * FA2_D + k0 + tid4 * 4;\n"
"        qfrag[kk][0] = valid_a ? *(const uint32_t *)qa        : 0u;\n"
"        qfrag[kk][1] = valid_b ? *(const uint32_t *)qb        : 0u;\n"
"        qfrag[kk][2] = valid_a ? *(const uint32_t *)(qa + 16) : 0u;\n"
"        qfrag[kk][3] = valid_b ? *(const uint32_t *)(qb + 16) : 0u;\n"
"    }\n"
"\n"
"    float ofrag[FA2_DN][4];\n"
"    for (int n = 0; n < FA2_DN; n++) for (int i = 0; i < 4; i++) ofrag[n][i] = 0.0f;\n"
"    float m_a = -1e30f, m_b = -1e30f, l_a = 0.0f, l_b = 0.0f;\n"
"\n"
"    /* ---- SMEM: double-buffered K (e4m3 bytes) + V (bf16 halves) ---- */\n"
"    extern __shared__ unsigned char smem_b[];\n"
"    e4m3_t *sK0 = smem_b;\n"
"    e4m3_t *sK1 = sK0 + FA2_BC * FA2_KP;\n"
"    dt_t   *sV0 = (dt_t *)(sK1 + FA2_BC * FA2_KP);\n"
"    dt_t   *sV1 = sV0 + FA2_BC * FA2_DP;\n"
"    e4m3_t *sK_buf[2] = { sK0, sK1 };\n"
"    dt_t   *sV_buf[2] = { sV0, sV1 };\n"
"\n"
"    int k_chunks = FA2_D / 16;             /* 16 e4m3 bytes per cp.async */\n"
"    int v_chunks = FA2_D / 8;              /* 8 halves (16 B) per cp.async */\n"
"    int total_k  = FA2_BC * k_chunks;\n"
"    int total_v  = FA2_BC * v_chunks;\n"
"    int s_eff = S;\n"
"#if FA2_CAUSAL\n"
"    int q_blk_max = blockIdx.x * FA2_BR + FA2_BR;\n"
"    if (q_blk_max < s_eff) s_eff = q_blk_max;\n"
"#endif\n"
"    int n_tiles  = (s_eff + FA2_BC - 1) / FA2_BC;\n"
"\n"
"    /* ---- Prologue: cp.async tile 0 ---- */\n"
"    {\n"
"        e4m3_t *dK_ = sK_buf[0];\n"
"        dt_t   *dV_ = sV_buf[0];\n"
"        for (int idx = threadIdx.x; idx < total_k; idx += blockDim.x) {\n"
"            int j_ = idx / k_chunks; int c_ = (idx - j_ * k_chunks) * 16;\n"
"            unsigned dst = __cvta_generic_to_shared(dK_ + j_ * FA2_KP + c_);\n"
"            const void *src = (const void *)(Kh + (size_t)j_ * FA2_D + c_);\n"
"            int nb = (j_ < S) ? 16 : 0;\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst), \"l\"(src), \"r\"(nb));\n"
"        }\n"
"        for (int idx = threadIdx.x; idx < total_v; idx += blockDim.x) {\n"
"            int j_ = idx / v_chunks; int c_ = (idx - j_ * v_chunks) * 8;\n"
"            unsigned dst = __cvta_generic_to_shared(dV_ + j_ * FA2_DP + c_);\n"
"            const void *src = (const void *)(Vh + (size_t)j_ * FA2_D + c_);\n"
"            int nb = (j_ < S) ? 16 : 0;\n"
"            asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst), \"l\"(src), \"r\"(nb));\n"
"        }\n"
"    }\n"
"    asm volatile(\"cp.async.commit_group;\\n\" ::);\n"
"\n"
"    int ldm_row_off = lane & 7;\n"
"\n"
"    for (int t = 0; t < n_tiles; t++) {\n"
"        int cur = t & 1;\n"
"        int nxt = 1 - cur;\n"
"        int kv0 = t * FA2_BC;\n"
"\n"
"        if (t + 1 < n_tiles) {\n"
"            int kv0n = (t + 1) * FA2_BC;\n"
"            e4m3_t *dK_ = sK_buf[nxt];\n"
"            dt_t   *dV_ = sV_buf[nxt];\n"
"            for (int idx = threadIdx.x; idx < total_k; idx += blockDim.x) {\n"
"                int j_ = idx / k_chunks; int c_ = (idx - j_ * k_chunks) * 16;\n"
"                int kv_ = kv0n + j_;\n"
"                unsigned dst = __cvta_generic_to_shared(dK_ + j_ * FA2_KP + c_);\n"
"                const void *src = (const void *)(Kh + (size_t)kv_ * FA2_D + c_);\n"
"                int nb = (kv_ < S) ? 16 : 0;\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst), \"l\"(src), \"r\"(nb));\n"
"            }\n"
"            for (int idx = threadIdx.x; idx < total_v; idx += blockDim.x) {\n"
"                int j_ = idx / v_chunks; int c_ = (idx - j_ * v_chunks) * 8;\n"
"                int kv_ = kv0n + j_;\n"
"                unsigned dst = __cvta_generic_to_shared(dV_ + j_ * FA2_DP + c_);\n"
"                const void *src = (const void *)(Vh + (size_t)kv_ * FA2_D + c_);\n"
"                int nb = (kv_ < S) ? 16 : 0;\n"
"                asm volatile(\"cp.async.cg.shared.global [%0], [%1], 16, %2;\" :: \"r\"(dst), \"l\"(src), \"r\"(nb));\n"
"            }\n"
"            asm volatile(\"cp.async.commit_group;\\n\" ::);\n"
"            asm volatile(\"cp.async.wait_group 1;\\n\" ::);\n"
"        } else {\n"
"            asm volatile(\"cp.async.wait_group 0;\\n\" ::);\n"
"        }\n"
"        __syncthreads();\n"
"\n"
"        e4m3_t *sK = sK_buf[cur];\n"
"        dt_t   *sV = sV_buf[cur];\n"
"\n"
"        /* ---- Q @ K^T -> sfrag[BCN][4] (m16n8k32 e4m3, direct uint32 K reads) ---- */\n"
"        float sfrag[FA2_BCN][4];\n"
"        for (int n = 0; n < FA2_BCN; n++) for (int i = 0; i < 4; i++) sfrag[n][i] = 0.0f;\n"
"        for (int kk = 0; kk < FA2_DK32; kk++) {\n"
"            int k_off = kk * 32;\n"
"            for (int nn = 0; nn < FA2_BCN; nn++) {\n"
"                int b_col = nn * 8 + row_a;          /* KV row within tile */\n"
"                const e4m3_t *kp = sK + b_col * FA2_KP + k_off + tid4 * 4;\n"
"                uint32_t b0 = *(const uint32_t *)kp;\n"
"                uint32_t b1 = *(const uint32_t *)(kp + 16);\n"
"                uint32_t a0 = qfrag[kk][0], a1 = qfrag[kk][1], a2 = qfrag[kk][2], a3 = qfrag[kk][3];\n"
"                float c0 = sfrag[nn][0], c1 = sfrag[nn][1], c2 = sfrag[nn][2], c3 = sfrag[nn][3];\n"
"                asm(\"mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32\"\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                sfrag[nn][0] = c0; sfrag[nn][1] = c1; sfrag[nn][2] = c2; sfrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"\n"
"        /* ---- scale + OOB mask (+ causal mask) ---- */\n"
"        for (int nn = 0; nn < FA2_BCN; nn++) {\n"
"            int kv_c0 = kv0 + nn * 8 + col_g + 0;\n"
"            int kv_c1 = kv0 + nn * 8 + col_g + 1;\n"
"            int va0 = (kv_c0 < S), va1 = (kv_c1 < S);\n"
"            int vb0 = va0, vb1 = va1;\n"
"#if FA2_CAUSAL\n"
"            va0 = va0 && (kv_c0 <= gqr_a); va1 = va1 && (kv_c1 <= gqr_a);\n"
"            vb0 = vb0 && (kv_c0 <= gqr_b); vb1 = vb1 && (kv_c1 <= gqr_b);\n"
"#endif\n"
"            sfrag[nn][0] = va0 ? sfrag[nn][0] * lscale : -1e30f;\n"
"            sfrag[nn][1] = va1 ? sfrag[nn][1] * lscale : -1e30f;\n"
"            sfrag[nn][2] = vb0 ? sfrag[nn][2] * lscale : -1e30f;\n"
"            sfrag[nn][3] = vb1 ? sfrag[nn][3] * lscale : -1e30f;\n"
"        }\n"
"\n"
"        /* ---- row max over the 4-thread row group ---- */\n"
"        float mx_a = -1e30f, mx_b = -1e30f;\n"
"        for (int nn = 0; nn < FA2_BCN; nn++) {\n"
"            mx_a = fmaxf(mx_a, fmaxf(sfrag[nn][0], sfrag[nn][1]));\n"
"            mx_b = fmaxf(mx_b, fmaxf(sfrag[nn][2], sfrag[nn][3]));\n"
"        }\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 1));\n"
"        mx_a = fmaxf(mx_a, __shfl_xor_sync(0xffffffff, mx_a, 2));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 1));\n"
"        mx_b = fmaxf(mx_b, __shfl_xor_sync(0xffffffff, mx_b, 2));\n"
"\n"
"        float m_new_a = fmaxf(m_a, mx_a);\n"
"        float m_new_b = fmaxf(m_b, mx_b);\n"
"        float alpha_a = exp2f(m_a - m_new_a);\n"
"        float alpha_b = exp2f(m_b - m_new_b);\n"
"        l_a *= alpha_a; l_b *= alpha_b;\n"
"        for (int n = 0; n < FA2_DN; n++) {\n"
"            ofrag[n][0] *= alpha_a; ofrag[n][1] *= alpha_a;\n"
"            ofrag[n][2] *= alpha_b; ofrag[n][3] *= alpha_b;\n"
"        }\n"
"        m_a = m_new_a; m_b = m_new_b;\n"
"\n"
"        /* ---- P = exp2(S - m), pack to bf16 pfrag (A-frag of P@V) ---- */\n"
"        uint32_t pfrag[FA2_BCK][4];\n"
"        float rs_a = 0.0f, rs_b = 0.0f;\n"
"        for (int kk = 0; kk < FA2_BCK; kk++) {\n"
"            float p0 = exp2f(sfrag[2*kk    ][0] - m_a);\n"
"            float p1 = exp2f(sfrag[2*kk    ][1] - m_a);\n"
"            float p2 = exp2f(sfrag[2*kk    ][2] - m_b);\n"
"            float p3 = exp2f(sfrag[2*kk    ][3] - m_b);\n"
"            float p4 = exp2f(sfrag[2*kk + 1][0] - m_a);\n"
"            float p5 = exp2f(sfrag[2*kk + 1][1] - m_a);\n"
"            float p6 = exp2f(sfrag[2*kk + 1][2] - m_b);\n"
"            float p7 = exp2f(sfrag[2*kk + 1][3] - m_b);\n"
"            rs_a += p0 + p1 + p4 + p5;\n"
"            rs_b += p2 + p3 + p6 + p7;\n"
"            pfrag[kk][0] = packbf(p0, p1);\n"
"            pfrag[kk][1] = packbf(p2, p3);\n"
"            pfrag[kk][2] = packbf(p4, p5);\n"
"            pfrag[kk][3] = packbf(p6, p7);\n"
"        }\n"
"        rs_a += __shfl_xor_sync(0xffffffff, rs_a, 1);\n"
"        rs_a += __shfl_xor_sync(0xffffffff, rs_a, 2);\n"
"        rs_b += __shfl_xor_sync(0xffffffff, rs_b, 1);\n"
"        rs_b += __shfl_xor_sync(0xffffffff, rs_b, 2);\n"
"        l_a += rs_a; l_b += rs_b;\n"
"\n"
"        /* ---- P @ V via ldmatrix.x2.trans on sV[bc, d] (bf16) ---- */\n"
"        for (int kk = 0; kk < FA2_BCK; kk++) {\n"
"            int kbase = kk * 16;\n"
"            int bc_row = kbase + ldm_row_off + ((lane & 8) ? 8 : 0);\n"
"            for (int nn = 0; nn < FA2_DN; nn++) {\n"
"                int nbase = nn * 8;\n"
"                unsigned saddr = __cvta_generic_to_shared(sV + bc_row * FA2_DP + nbase);\n"
"                uint32_t b0, b1;\n"
"                asm volatile(\"ldmatrix.sync.aligned.m8n8.x2.trans.shared.b16 {%0, %1}, [%2];\"\n"
"                    : \"=r\"(b0), \"=r\"(b1) : \"r\"(saddr));\n"
"                uint32_t a0 = pfrag[kk][0], a1 = pfrag[kk][1], a2 = pfrag[kk][2], a3 = pfrag[kk][3];\n"
"                float c0 = ofrag[nn][0], c1 = ofrag[nn][1], c2 = ofrag[nn][2], c3 = ofrag[nn][3];\n"
"                asm(FA2_PV\n"
"                    \" {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\"\n"
"                    : \"+f\"(c0), \"+f\"(c1), \"+f\"(c2), \"+f\"(c3)\n"
"                    : \"r\"(a0), \"r\"(a1), \"r\"(a2), \"r\"(a3),\n"
"                      \"r\"(b0), \"r\"(b1));\n"
"                ofrag[nn][0] = c0; ofrag[nn][1] = c1; ofrag[nn][2] = c2; ofrag[nn][3] = c3;\n"
"            }\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"\n"
"    /* ---- epilogue: divide by l, store O (bf16) ---- */\n"
"    float inv_a = (l_a > 0.0f) ? 1.0f / l_a : 0.0f;\n"
"    float inv_b = (l_b > 0.0f) ? 1.0f / l_b : 0.0f;\n"
"    for (int nn = 0; nn < FA2_DN; nn++) {\n"
"        int d_col = nn * 8 + col_g;\n"
"        if (gqr_a < S) {\n"
"            Oh[(size_t)gqr_a * FA2_D + d_col + 0] = f2bf(ofrag[nn][0] * inv_a);\n"
"            Oh[(size_t)gqr_a * FA2_D + d_col + 1] = f2bf(ofrag[nn][1] * inv_a);\n"
"        }\n"
"        if (gqr_b < S) {\n"
"            Oh[(size_t)gqr_b * FA2_D + d_col + 0] = f2bf(ofrag[nn][2] * inv_b);\n"
"            Oh[(size_t)gqr_b * FA2_D + d_col + 1] = f2bf(ofrag[nn][3] * inv_b);\n"
"        }\n"
"    }\n"
"}\n";

/* ---- naive non-tiled GPU reference (causal-aware), correctness oracle ---- */
static const char *k_fa2_ref_src =
"typedef unsigned short dt_t;\n"
"#ifndef FA2_D\n"
"#define FA2_D 128\n"
"#endif\n"
"#ifndef FA2_CAUSAL\n"
"#define FA2_CAUSAL 0\n"
"#endif\n"
"#ifdef FA2_BF16\n"
"__device__ __forceinline__ float dt2f(dt_t h){ unsigned int b=((unsigned int)h)<<16; float f; asm(\"mov.b32 %0, %1;\":\"=f\"(f):\"r\"(b)); return f; }\n"
"__device__ __forceinline__ dt_t f2dt(float f){ dt_t h; asm(\"cvt.rn.bf16.f32 %0, %1;\":\"=h\"(h):\"f\"(f)); return h; }\n"
"#else\n"
"__device__ __forceinline__ float dt2f(dt_t h){ float f; asm(\"cvt.f32.f16 %0, %1;\":\"=f\"(f):\"h\"(h)); return f; }\n"
"__device__ __forceinline__ dt_t f2dt(float f){ dt_t h; asm(\"cvt.rn.f16.f32 %0, %1;\":\"=h\"(h):\"f\"(f)); return h; }\n"
"#endif\n"
"\n"
"extern \"C\" __global__\n"
"void fa2_ref(dt_t *O, const dt_t *Q, const dt_t *K, const dt_t *V,\n"
"             int S, int D, float scale) {\n"
"    int qi  = blockIdx.x;\n"
"    int bh  = blockIdx.y;\n"
"    int tid = threadIdx.x;\n"
"    if (tid >= D) return;\n"
"    const dt_t *Qh = Q + (size_t)bh * S * D + (size_t)qi * D;\n"
"    const dt_t *Kh = K + (size_t)bh * S * D;\n"
"    const dt_t *Vh = V + (size_t)bh * S * D;\n"
"          dt_t *Oh = O + (size_t)bh * S * D + (size_t)qi * D;\n"
"    float q_d = dt2f(Qh[tid]);\n"
"    extern __shared__ float scores[];\n"
"#if FA2_CAUSAL\n"
"    int kv_lim = qi + 1;\n"
"#else\n"
"    int kv_lim = S;\n"
"#endif\n"
"    for (int kv = 0; kv < kv_lim; kv++) {\n"
"        float partial = q_d * dt2f(Kh[(size_t)kv * D + tid]);\n"
"        for (int o = 16; o > 0; o >>= 1) partial += __shfl_xor_sync(0xffffffff, partial, o);\n"
"        __shared__ float warp_sums[8];\n"
"        int wid = tid >> 5, lane = tid & 31;\n"
"        if (lane == 0) warp_sums[wid] = partial;\n"
"        __syncthreads();\n"
"        float s = 0.0f; int n_warps = blockDim.x >> 5;\n"
"        if (tid < n_warps) s = warp_sums[tid];\n"
"        for (int o = n_warps >> 1; o > 0; o >>= 1) s += __shfl_xor_sync(0xffffffff, s, o);\n"
"        if (tid == 0) scores[kv] = s * scale;\n"
"        __syncthreads();\n"
"    }\n"
"    __shared__ float mx_sh, sum_sh;\n"
"    if (tid == 0) {\n"
"        float mx = -1e30f;\n"
"        for (int j = 0; j < kv_lim; j++) if (scores[j] > mx) mx = scores[j];\n"
"        float sum = 0.0f;\n"
"        for (int j = 0; j < kv_lim; j++) { scores[j] = expf(scores[j] - mx); sum += scores[j]; }\n"
"        mx_sh = mx; sum_sh = sum;\n"
"    }\n"
"    __syncthreads();\n"
"    float inv = 1.0f / sum_sh;\n"
"    float acc = 0.0f;\n"
"    for (int j = 0; j < kv_lim; j++) acc += scores[j] * dt2f(Vh[(size_t)j * D + tid]);\n"
"    Oh[tid] = f2dt(acc * inv);\n"
"}\n";

#endif
